### ISSUE TITLE
Request: Better Ore Dictionary Support

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1]
Currently, the fuel can recipe does not allow you to use other mods' plastic sheets/plates (like Gregtch's polyethylene sheets).

Also, I do not think you can use other mods' deuterium/tritium/lithium.

**Comment by HbmMods** [comment]
The recipes themselves will probably stay that way (so no shared alloy recipes like some mods can actually do) but using the ore dict to determine input items is quite possible, I'll take a look at that.

**Comment by HbmMods** [comment]
The algorithm is done, now all I have to do is implementing it for all current and future recipes.
