### ISSUE TITLE
Why cant i do this??

### ISSUE THREAD

**Issue by iamsoNewBee** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1000]
<img width="370" alt="image" src="https://user-images.githubusercontent.com/98573273/232120717-a43b1dec-dd6d-4b23-a299-18ef16386b1f.png">

**Comment by iamsoNewBee** [comment]
and let`s celebrate the               #1000                 issue XD

**Comment by OlorinIV** [comment]
**wrong sense of humor**

**Comment by iamsoNewBee** [comment]
Just trying to improve efficiency like what ie does

**Comment by HbmMods** [comment]
bruh

**Comment by burningwater202** [comment]
![Uploading 34BAE7FE-396E-4959-A55A-E7828076ACF4.gif…]()

**Comment by HbmMods** [comment]
you hit the comment button too soon

**Comment by burningwater202** [comment]
F

**Comment by iamsoNewBee** [comment]
???

**Comment by burningwater202** [comment]
> ???

I tried to post a reaction gif but didn’t let it upload, laugh at me
