### ISSUE TITLE
A dazzling white light should appear before a nuclear explosion to match reality

### ISSUE THREAD

**Issue by iamsoNewBee** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1005]
![bili_v_d_1682003159065](https://user-images.githubusercontent.com/98573273/233409232-c8971947-64b5-4893-8273-40011112928d.gif)
like this.what do u think?

**Comment by username90001** [comment]
it is already added?

**Comment by HbmMods** [comment]
we quite literally already have that
