### ISSUE TITLE
Where did dynosynthesis go?

### ISSUE THREAD

**Issue by danielJin100** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1007]
There are other ways to create schrabidium/euphemium, but now the only way to make dineutronium is through the temporary sparkticle recipe. I don't think this was intentional, but I could be wrong.

Mod version used: HBM-NTM-.1.0.27_X4900xJ96X2.jar

**Comment by HbmMods** [comment]
it's dead

it went straight to hell where it belongs
