### ISSUE TITLE
Potential Watz Meltdown Bug

### ISSUE THREAD

**Issue by Antineutrino-4444** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1008]
When multiple Watzs are stacked and a meltdown occurs, only the top watz will break leaving the rest of the stack intact. Additionally, the rest of the stack have a maxed out amount of mud but not exploding.

**Comment by SoB1nary** [comment]
![Screenshot_20230424_090423](https://user-images.githubusercontent.com/88827565/233891134-28039da8-a78f-49f5-84de-b8f8437fe03f.jpg)

**Comment by Antineutrino-4444** [comment]
No the problem I am trying to say is that the rest of the segment have a maxed out mud, maybe it should be voided or smt like that.

**Comment by HbmMods** [comment]
Mud isn't going to magically disappear, you'll have to drain it before using the reactor again.
