### ISSUE TITLE
Doesn't work with other mods

### ISSUE THREAD

**Issue by LaryWulf** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1010]
### Describe the bug

I can't use with other mods like 
Mekanism, buildcraft , EnderIO ,ThermalDynamics etc,
  if cant use  other mods well dis mod bad

**Comment by HbmMods** [comment]
Could you at least try to be a bit more descriptive? Does it crash, what is the crash log, does the game not even start at all, are there any gameplay issues caused by the mod that makes it unplayable, anything?

**Comment by LaryWulf** [comment]
Doesn't work with other mods !!!  
i cant use other pipes, tanks, pumps, etc

**Comment by burningwater202** [comment]
That sounds more like a skill issue to me

**Comment by LaryWulf** [comment]
sounds mod is bad for other mods lol

**Comment by HbmMods** [comment]
The fluids work in a completely different manner, if they were compatible forge fluids we wouldn't have things like fluid traits or tank restrictions. I'm not even sure why you would use any of those other mods' pipes considering NTM's pipes are not only cheaper but also have *infinite throughput* and doesn't require any dedicated pumps to work.

**Comment by LaryWulf** [comment]
well dis mod suck i removeing of my server :D ,  Devs are to lay to add support lol is trash mod i don't recommend of 
People there much more batter mods that that carp devs maded LoL

**Comment by HbmMods** [comment]
Oh no! The game-breaking issue of....not being able to use objectively worse pipes and interchanging like 3 fluids (out of over a hundred) that other mods also have.

that's not even a bruh moment anymore

**Comment by SoB1nary** [comment]
Cry about it.

**Comment by LaryWulf** [comment]
lol shit post mod hahah
