### ISSUE TITLE
Suggestion: Energy cost of Deuterium Extractors

### ISSUE THREAD

**Issue by Nici660** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1016]
Would you consider cutting the Energy cost of the deuterium extractors in half, cause i just feel like 1 MHE is a bit much for shy 1500 Mb of Heavy Water (And my infinite hydrogen-deuterium fusion reactor makes minus now, so um yeah please?)

**Comment by HbmMods** [comment]
Consumption has been reduced by 90%.
