### ISSUE TITLE
Single color full screen/Display bug

### ISSUE THREAD

**Issue by CorporalRaymond** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1019]
The issue: After launching the minecraft from it's official launcher, downloading the latest forge version for the version: 1.7.10, running the HBM-NTM-.1.0.27_X4585 version of the mod and creating a world, the screen goes a single colour and can't fix it, I tried using other versions of the mod (3 other versions) and they all had the same issue, I decided that the problem was with the mod because without the mods, the game runs normally without the screen displaying a single pixel, I ran it with other mods and it had absolute no problem, I ran the game is at should have been by selecting 1.7.10-Forge10.13.4.1614-1.7.10, clicking on play after dragging the HBM mod to the mods folder located in .minecraft. Couldn't find someone having the same problem so ended up coming here.

Mod Screen (https://user-images.githubusercontent.com/132620996/236339953-8e34cb7b-b85f-40af-beb7-01efaa003bb4.png)
Mod screen (https://user-images.githubusercontent.com/132620996/236339966-f7d9d852-8a0c-42f9-b0e1-3fb467264638.png)
In-Game (https://user-images.githubusercontent.com/132620996/236339978-4b52f760-5dda-4406-8a95-bd4d75569443.png)

Note that all other mods don't have any effect on the HBM mod since it runs the same without the mods, thanks.

**Comment by OlorinIV** [comment]
uh, see 1.7.10 graphics issues on top

**Comment by HbmMods** [comment]
See #985

**Comment by CorporalRaymond** [comment]
Well I just downloaded the oldest geforce driver (late 2022 because it is the oldest driver available on official website) it solved the issue but also definitely not, now I can see blocks, but well... They are single coloured like lego bricks or something, tree leaves are green, soil is just brown sand is just yellow and can't do anything or see anything like inventory, thanks for responding. I only ran it with the hbm mod

**Comment by HbmMods** [comment]
Check if the game is actually running on your dedicated GPU, the F3 display might show it, although it might require Optifine to do that. In addition you can try to install Neodymium, the changes it makes to chunk rendering often also end up fixing the issue.

**Comment by CorporalRaymond** [comment]
Neodymium solved the issue, at least as what I see now, thanks for the help.
