### ISSUE TITLE
Server is laggy and keeps timing out

### ISSUE THREAD

**Issue by VoidOfMistakes** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1021]
added this to a server and it keeps breaking
says [FML]: HBM's Nuclear Tech Mod loaded a new chunk [-109, 76] in dimension 0 (overworld) while populating chunk [-108, 77], causing cascading worldgen lag.

**Comment by JameH2** [comment]
version? mod number?

**Comment by VoidOfMistakes** [comment]
version 1.12.2 and 1.8.3

**Comment by JameH2** [comment]
yell at alcater, this is 1.7.10

**Comment by VoidOfMistakes** [comment]
oh mb bro
