### ISSUE TITLE
Can't spawn hbm's mob correctly

### ISSUE THREAD

**Issue by sdddddf80** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1022]
### Describe the bug

I try to spawn hbm's mobs, but even though I write the code as same as the code in BossSpawnHandler.java
```
package com.hbm.blocks.siege;

import com.hbm.blocks.BlockBase;
import com.hbm.entity.mob.EntityFBI;
import com.hbm.entity.mob.EntityMaskMan;
import net.minecraft.block.material.Material;
import net.minecraft.entity.EntityLiving;
import net.minecraft.entity.player.EntityPlayer;

import net.minecraft.world.World;
import net.minecraftforge.event.ForgeEventFactory;


public class Basement extends BlockBase {
    public Basement() {
        super(Material.iron);
    }
    @Override
    public boolean onBlockActivated(World world, int x, int y, int z, EntityPlayer player, int side, float hitX, float hitY, float hitZ)
    {
        if(world.isRemote){

            EntityLiving FBI = new EntityMaskMan(world);
            FBI.setLocationAndAngles(x, y, z, world.rand.nextFloat() * 360.0F, 0.0F);
            world.spawnEntityInWorld(FBI);
            ForgeEventFactory.doSpecialSpawn(FBI , world, x, y, z);
            FBI.onSpawnWithEgg(null);
        }
        return true;
}
```
![QQ截图20230506230737](https://user-images.githubusercontent.com/53573250/236632413-0b387df3-1a98-4aa7-97ce-c87984b7cbbb.png)

, the mob spawned has no ai, no collision volume.
![QQ截图20230506230814](https://user-images.githubusercontent.com/53573250/236632410-35c33b99-2701-41f7-8ec3-c897c660b371.png)

**Comment by HbmMods** [comment]
`world.isRemote` means it's client-side only, you want to do the opposite.

**Comment by sdddddf80** [comment]
> `world.isRemote` means it's client-side only, you want to do the opposite.

Well removing `world.isRemote` doesn't change the situation😹

**Comment by JameH2** [comment]
You dont remove it, you insert an ! At the beginning

**Comment by BallOfEnergy1** [comment]
Yeah, make it a not (!) world.isRemote

**Comment by sdddddf80** [comment]
God I ignore that
