### ISSUE TITLE
Meteor events breaking machines

### ISSUE THREAD

**Issue by solundev** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1025]
Those events of meteorites are destroying every building on the world, is there a way to disable it?
![image](https://user-images.githubusercontent.com/82925878/236723405-42d6c1a5-b92f-43c2-ba80-e7f3ae52ad0e.png)

**Comment by HbmMods** [comment]
If you put a protection charm onto your chestplate, all meteorites will fall away from you and meteor impacts won't destroy blocks.

Alternatively, you can turn them off in the config, just set `1.10_enableMeteorStrikes` to `false`.
