### ISSUE TITLE
How to conveniently add and modify the generated structure

### ISSUE THREAD

**Issue by sdddddf80** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1026]
@HbmMods How to conveniently add and modify the hbm's generated structures？I make a block which makes the process of exploring and generating buildings more interesting and challenging for players and I want to test whether it works well with the generated structure.

**Comment by HbmMods** [comment]
Structures are just lists of setBlock operations, there's no easy way of making larger modifications to those. As for adding new ones, there's probably a script for generating the code out of a schematic file, otherwise you'd have to do it by hand.

**Comment by sdddddf80** [comment]
Are these tools useful for modifying or adding structures? 
![image](https://user-images.githubusercontent.com/53573250/236853889-28aec5a6-b764-4cb1-8214-528539ad4dd3.png)

**Comment by HbmMods** [comment]
Those were meant for the structure component system which I don't know how it works since it was added via PR. You are free to make your own tools of course.
