### ISSUE TITLE
Bug: Chargerate of FEnSU not shown correctly in Gui

### ISSUE THREAD

**Issue by Alcatergit** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1027]
When transferring energy to and from FEnSUs the charge rate is always +0HE/s. This can be replicated by charging one FEnSU with another one. 
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/117086491/5dde4996-15cf-435a-8b6a-297a47acf6ed)

**Comment by Alcatergit** [comment]
Version is HBM-NTM-.1.0.27_X4592

**Comment by BallOfEnergy1** [comment]
Yeah, I also noticed this, but I chalked it up to me being on a older version. Guess it's an issue still.

**Comment by HbmMods** [comment]
Fixed in X4606.
