### ISSUE TITLE
Rare Gneiss

### ISSUE THREAD

**Issue by lycc193** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1028]
### Describe the bug

I found that rare earth gneiss was added in the [block register](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/blob/dcec2627173a05733ad4f7c248553c803d86af85/src/main/java/com/hbm/blocks/ModBlocks.java#L2428
), but in the world generation, the rare earth gneiss was generated as [asbestos gneiss](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/blob/dcec2627173a05733ad4f7c248553c803d86af85/src/main/java/com/hbm/lib/HbmWorldGen.java#LL132C1-L132C1
), is it intentional?

**Comment by HbmMods** [comment]
Fixed in X4606.
