### ISSUE TITLE
Some visual bugs and well, some annoying ones

### ISSUE THREAD

**Issue by CorporalRaymond** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1030]
Big nuclear reactor depleted uranium fuel cannot be stored in the empty rods for some kind of reason 
 /!\ (https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/132620996/47b3062e-9acf-4596-acb9-b0cc6a460a45)

and some other visual bugs
1-(https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/132620996/9e76cca0-fee0-493d-97e6-544b83ba73a9)
2-(https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/132620996/38caf99f-cc40-4547-95e0-bdb7a4a269f6)
3-(https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/132620996/87a0cd06-d921-491f-b552-dca43bdb2dd9)

**Comment by HbmMods** [comment]
![grafik](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/16674258/ad17f515-438b-44e0-8342-380621fff277)

For some reason instead of `i` your version of the mod uses the dotless `ı` which breaks localization and resource loading. Did you compile that version yourself or are you using one of the releases? If so, what's the MD5 hash of your version?

**Comment by CorporalRaymond** [comment]
93A7D26A46DD9ACC384AE4187A6D2625
(https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/132620996/feb1abd3-7b34-460e-b089-b6f38f92258f)

**Comment by HbmMods** [comment]
The MD5 matches so the file shouldn't be damaged or altered in any way. Perhaps it's another mod interfering with it somehow?

**Comment by CorporalRaymond** [comment]
Only ran HBM, here are the results
(https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/132620996/6e379a04-7a3a-4fe2-b3be-bad17eb2e33f)
(https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/132620996/3581cf87-bb20-4b36-8442-7a7034e083a8)

**Comment by BallOfEnergy1** [comment]
Looks like everything with an 'i' is broken, not sure what could cause an issue like that. I'd assume another mod is breaking something in localization, but you mentioned running it standalone.

**Comment by HbmMods** [comment]
I think I figured it out

all of these items use the `ItemEnumMulti` base class which generates both the name and texture string out of the enum's name, for example `STEEL_DIAMOND` for the diamond-tipped steel drill. To turn that enum name into a texture name, it runs `toLowerCase()` with no parameters which implies system locale, which means that in languages where there is separate dotted and dotless `i`s, `DIAMOND` turns into `dıamond`. This should be easy to fix by specifying a default locale (for example US) to run the method with.

**Comment by HbmMods** [comment]
As for the reactor thing, those depleted rods were removed a while back when all the items were unified, I might just add them back in so that the manual unloading works again.

**Comment by CorporalRaymond** [comment]
If there is an auto unload, how do I do it?

**Comment by HbmMods** [comment]
Fixed in X4606.
