### ISSUE TITLE
No sound for assembler and chem. plant.

### ISSUE THREAD

**Issue by Kkelos** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1032]
### Describe the bug
Just watch the video

I'm playing on 1.7.10 and on 1.0.27_X4592 version of the mod. Idk what it is, but it happens in all my worlds, although the file itself is in the mod. That's weird, maybe this issue only I have

Video: https://youtu.be/h3GqA3h9YYE

**Comment by HbmMods** [comment]
Fixed in X4606.
