### ISSUE TITLE
Turbofan sound issue

### ISSUE THREAD

**Issue by Nufag** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1036]
Turbofan sound does not repeat smoothly on 1.0.27X4606 release. 

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/121898607/634e346c-c38a-47aa-b234-b927202b8cc5

**Comment by HbmMods** [comment]
Fixed in 1.0.27X4607.
