### ISSUE TITLE
No RBMK Destruction if there are blocks above it

### ISSUE THREAD

**Issue by Alcatergit** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1038]
When changing the RBMK code for the explosions i found out that if the RBMK is covered with any block then no destruction happens above.
Bug is in 1.12.2 and 1.7.10 so when i find a solution for the bug ill post it here too.
Use the screenshots to recreate. 
![2023-05-22_15 38 04](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/117086491/9ce48734-c61a-4811-8aed-78c5669920cc)

**Comment by HbmMods** [comment]
Did your reactor have any cover panels that aren't made from glass?

**Comment by Alcatergit** [comment]
Happens with and without covers.

Without Covers Before
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/117086491/7b013ca8-67de-438a-a51c-9d0737c5026f)
Without Covers After
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/117086491/9c972cb3-6831-4d04-97af-7f3cb034fb20)

With Covers Before
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/117086491/a62eb8ed-2d2f-4ec1-b636-172acd760030)
With Covers After
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/117086491/60ca6832-d7e2-402d-9710-ed9fe4114934)

**Comment by Alcatergit** [comment]
Where is the roof destruction code located? Searched TileEntityRBMKBase and TileEntityRBMKRod but cant find it.

**Comment by HbmMods** [comment]
Fixed in X4613.
