### ISSUE TITLE
Crucible recipes file crash

### ISSUE THREAD

**Issue by Crimento** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1040]
### Removing underscore from _hbmCrucible.json makes the game crash on startup

Just tried it with fresh install of 1.7.10 on PrismLauncher with same result.
Attaching the crashlog: https://pastebin.com/72gjWyzN

**Comment by HbmMods** [comment]
Did you make any changes to the file or did you use the template as-is?

**Comment by HbmMods** [comment]
oop i see the issue

**Comment by Crimento** [comment]
> use the template as-is?

Yeah, I tried to use file without modifications to be sure it's not caused by me

**Comment by HbmMods** [comment]
Fixed in X4613.
