### ISSUE TITLE
Craft achievement trigger bug

### ISSUE THREAD

**Issue by Crimento** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1044]
Achievements won't trigger with added recipes if created with different crafting handler

for example, I added Blast Furnace recipe for crafting table but crafting it using new recipe won't trigger the achievement.
But changed recipe for press would still trigger it because it's still crafted using crafting table.

So far I managed to work around it with `/achievement give achievement.blastFurnace @p` command in Better Questing rewards but would be great to have a native solution

**Comment by HbmMods** [comment]
Triggers just fine for me, do you have the prerequisite achievement you get from crafting a burner press?

**Comment by HbmMods** [comment]
Fixed in X4613, all NTM triggers should now be interchangeable between machines.
