### ISSUE TITLE
Heavy artillery gun 

### ISSUE THREAD

**Issue by Eggmayor** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1047]
Heavy artillery gun causes a crash when placed down 

I am using the newest version of Hbm Ntm extended edition.

I am running optifine in my modpack.

**Comment by Antineutrino-4444** [comment]
Dude seriously at least include a crash report

**Comment by LePeeperSauvage** [comment]
This is, in case you have not noticed, the 1.7.10 GitHub page. And you didn't even include a crash log, so even if Alcater saw it, he wouldn't even be able to do anything.

**Comment by SoB1nary** [comment]
That's the 1.7 github, we physically cannot help you, go to alcater's

**Comment by OlorinIV** [comment]
seriously bob should add a '**1.7.10 ONLY**' under 'Describe the bug' in the template

**Comment by HbmMods** [comment]
Report it to [Extended Edition](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/issues) instead
