### ISSUE TITLE
question/bug

### ISSUE THREAD

**Issue by BlitzFan1209** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1051]
my derrick isnt working even tho theres a new oil deposoit under it i have it directly connected to a heater and a oil refinery if thats a problem its getting powered version: 1.7.10

**Comment by HbmMods** [comment]
Is the indicator a red [ ! ] or does it show the "no oil" sign? if it's the former it might be jammed, if it's the latter you probably just missed the deposit. In either case you should dig down and check where the pipe went.

**Comment by BlitzFan1209** [comment]
Yeah i saw it was jammed with natrual gas
