### ISSUE TITLE
assembly mcahine not working

### ISSUE THREAD

**Issue by BlitzFan1209** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1052]
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/98890042/e5bfbf4c-c3f5-4041-b13e-ba6d744f9276)
it dosnt work 
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/98890042/0f869843-7d9f-4fdb-b76d-b0ea29c36f3e)

**Comment by HbmMods** [comment]
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/16674258/a877a4e1-6422-405c-83b5-183075ab0301)

Wrong steel pipes

**Comment by BlitzFan1209** [comment]
oh

**Comment by BlitzFan1209** [comment]
Also how do i get concrete
