### ISSUE TITLE
Niter Liquefaction Doesn't Work

### ISSUE THREAD

**Issue by TehDrpStr** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1055]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.

I add the niter (I've tried both thermal niter and HBM niter) to the liquefactor. The liquefactor is at full power. Nothing happens.
Version 1.0.27_X4613.

**Comment by HbmMods** [comment]
Fixed in X4621.
