### ISSUE TITLE
New Texture for Industrial Generator

### ISSUE THREAD

**Issue by Nuclearenergy1415** [HbmMods/Hbm-s-Nuclear-Tech-GIT#106]
Industrial Generator didn't running correctly in Minecraft Forge 1.7.10😔😞

**Comment by ShimmeringBlaze** [comment]
It might help if you elaborated on that, and maybe share some screenshots as well so we know what the issue is

**Comment by HbmMods** [comment]
The IGen got decommissioned like a month ago, it's currently being reworked from the ground up but that will take a while.
