### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BlitzFan1209** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1061]
Does radioactive stuff go away from like a nuclear bomb after a long time

**Comment by Ade0924** [comment]
As far as I know radioactive stuff doesn't become less radioactive over time. If an rbmk explodes picking up the debris will make the area less radioactive but the items themselves don't become less radioactive.

**Comment by HbmMods** [comment]
The radiation from the nuclear explosion is relatively short lived, any residual radiation is caused by the sellafite blocks that spawn. Sellafite will decay after some time, turning into non-radioactive slaked sellafite, so after a while the crater should become non-radioactive.

**Comment by BlitzFan1209** [comment]
Alright thanks
