### ISSUE TITLE
Question about recent fix

### ISSUE THREAD

**Issue by Nufag** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1069]
In [1.0.27X4627] the following fix was implemented:
_Fixed potential issue where tanks would send fluids to invalidated tile entities, voiding themselves almost instantly_
The question is: could exact same issue take a place with energy and energy storage blocks? We suffered both issues playing server with [1.0.27X4592] version.
Thank you in advance.

**Comment by HbmMods** [comment]
That exact issue was solved months ago for energy networks. A similar issue existed a while ago with battery blocks that are directly connected to leviathan turbines but that was also fixed a while back.
