### ISSUE TITLE
[suggestion] wire connector

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [HbmMods/Hbm-s-Nuclear-Tech-GIT#107]
Small wire connectors like the ones Immersive Engineering has as an alternative to the poles.

**Comment by Drillgon200** [comment]
What does that even mean.

**Comment by bHXDgiuMa5yLHyC8** [comment]
NTM has poles to use with the HE wires but not single block bushings like these:

https://static.wikia.nocookie.net/ftb_gamepedia/images/8/89/IE_Wire_Examples.png

**Comment by Drillgon200** [comment]
Can't you just use a regular cable for that?

**Comment by bHXDgiuMa5yLHyC8** [comment]
Small connectors are useful for decorative builds.

**Comment by TheForge129** [comment]
To add on to this, I would like to see cable facades, either from this mod
or from another, as cables are normally very ugly imo

**Comment by HbmMods** [comment]
Yup, we have those now.
