### ISSUE TITLE
question..

### ISSUE THREAD

**Issue by BlitzFan1209** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1072]
does upgrading the mod version from like a previous version corrupt chunks or anything?

**Comment by HbmMods** [comment]
> does upgrading the mod version from like a previous version corrupt chunks or anything?

There's no known issue regarding corrupted chunks

> Also how do i transport balefire without instantly dying with my very useless power armor

Get better power armor, install cladding, use med-x or if all fails get tainted heart for full radiation immunity.

**Comment by BlitzFan1209** [comment]
Ah ok thanks
