### ISSUE TITLE
Incorrect work of converters

### ISSUE THREAD

**Issue by Artem-VV** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1078]
Energy converters do not work. RF energy is not accumulated in the converter and is not transferred to the storage. Tried different connection options.
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/121773727/da30e459-f157-4233-b53c-35e217d466df)

**Comment by HbmMods** [comment]
Seems to be an issue with BuildCraft since the converters work just fine with both Thermal and Mekanism.

**Comment by HbmMods** [comment]
Fixed in X4641 and tested with BuildCraft.
