### ISSUE TITLE
Watz issues

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [HbmMods/Hbm-s-Nuclear-Tech-GIT#108]
- can't shift click pellets into the reactor

- depleted titanium filter seems to be useless, maybe add a recycling recipe?

**Comment by HbmMods** [comment]
> can't shift click pellets into the reactor

Lots of older machines suffer from this, but that shouldn't be too hard to fix.

> depleted titanium filter seems to be useless, maybe add a recycling recipe?

I totally forgot that was a thing (which should outline how garbage the watz actually is from a quality standpoint) but I suppose a shredder recipe sounds like a good idea. Perhaps it transmutes the U238-content into something else? Polonium, or perhaps a tiny bit of schrabidium might sound reasonable, we'll see.
