### ISSUE TITLE
Mod Suggestion/New Feature

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1086]
I know i already posted another issue to the forum a little ago, but i had an idea for a new feature, how about adding a MSR (Molten Salt Reactor) that is a multiblock, like the watz powerplant, it could work with a Thorium, Fluorine, Lithium and Beryllium based fuel salt (ThFLiBe) (Made with the industrial liquefaction machine from pellets) and a brand new coolant salt tailor made for the reactor (which would be about 250-350 C° and also made with the liquefaction machine), and have all the mechanics, like the freeze plug, heat exchangers, etc, in my opinion it would be in its own tier between the RBMK and the Watz powerplant, and would also make fuels like Thorium more useful since i barely see them used, let me know what you think

Thanks for reading

-Chosen

**Comment by HbmMods** [comment]
An MSR was considered a while ago but I scrapped the idea. Thorium itself is already very useful in bismuth breeder RBMKs.

**Comment by TheChosenIndividual** [comment]
I understand, thank you, however, will we be getting any new reactor types in the future?
