### ISSUE TITLE
Hardcore Darkness is broken when NTM is installed

### ISSUE THREAD

**Issue by Fehrstix** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1089]
Greetings. I have a problem when installing Hardcore Darkness mod and HBM's Nuclear Tech mod on client, with default configuration files. This problem is about adding blue sky light at night, instead of completely dark silhouettes of the blocks. 

Steps to Recreate:
1. Install Hardcore Darkness v1.7 and HBM's Nuclear Tech Mod v1.0.27_X4627 on Minecraft 1.7.10
2. Launch the game 
3. Enter a Minecraft world
4. Wait till night in the world

Hardcore Darkness with NTM installed: 
![2023-06-25_18 50 11](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/76903563/fb59a9a9-76f2-400e-8e90-002fd03ac487)

Hardcore Darkness without NTM installed:
![2023-06-25_21 28 46](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/76903563/2f3cc4cd-0604-4a14-a242-c077b0e31e2f)

I'm sorry if I created the issue thread in a wrong way, I'm new to this, actually. Will be grateful to you for help.

**Comment by HbmMods** [comment]
Please refer to the [compatibility notice](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT#compatibility-notice), you'll have to disable the world provider and possibly the custom sky box as well.

**Comment by Fehrstix** [comment]
Thank you, it worked.
