### ISSUE TITLE
[enhancement] block destruction blacklist

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [HbmMods/Hbm-s-Nuclear-Tech-GIT#109]
Set off a DFC today, and it broke through GT6 bedrock ores at Y=0. It would be nice to have a config files that allows the user to specify blocks that should be immune to explosions.

**Comment by Drillgon200** [comment]
You set off a DFC, potentially the most powerful explosion in the mod, what were you expecting? Of course it's going to rip through everything, that's the whole point.

**Comment by bHXDgiuMa5yLHyC8** [comment]
I'd rather not have holes in the world floor.

**Comment by UFFR** [comment]
Then don't use Schrabidic nukes or set off DFCs.

**Comment by HbmMods** [comment]
I mean you kinda signed up for the "holes in the world" part when you decided to start up the DFC, the gap in the last bedrock layer adds a bit of spice to that.
