### ISSUE TITLE
nuclear creeper creates square of dead grass

### ISSUE THREAD

**Issue by RagexPrince683** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1090]
### Describe the bug

Not sure if this was intentional but seems out of place, using version 1.0.27_X4627
![2023-06-25_18 42 49](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/49804375/9a6dbf7b-f84a-47ac-8561-b27df73da893)

**Comment by HbmMods** [comment]
Nuclear creepers don't have a fallout effect but they do cause chunk radiation which is what causes the grass to die.

**Comment by RagexPrince683** [comment]
Cool, the grass is dead in squares (chunks) and does not fully end up in a circle of dead grass like most nuclear bombs. Not sure if that was intentional given it's a creeper but okay.
