### ISSUE TITLE
Placing dynamite block next to fire will cause it to disappear/turn into fire without actually spawning the dynamite entity to explode

### ISSUE THREAD

**Issue by RagexPrince683** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1094]
### Describe the bug

ver 1.0.27_X4627
![2023-06-29_00 02 00](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/49804375/6e048e80-e6f4-4ba8-b967-267b71794cf9)
![2023-06-29_00 02 04](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/49804375/4426a937-9f4c-47ef-854f-62cef92b4025)

**Comment by HbmMods** [comment]
Should be fixed in the most recent version, forge doesn't have an event for when blocks are broken by fire, instead dynamite will now ignite instantly when touching fire.
