### ISSUE TITLE
Powered armour possible visual bug/conflict

### ISSUE THREAD

**Issue by SsilverLeopard** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1099]
A short word of warning: 1, I'm Australian, so I spell armour with a u. 2, this issue has a lot of images attached, apologies if that causes problems.

I play HBM in a home-made modpack with a few other mods, most noticeably Optifine, better FPS and cosmetic armour (which I'll abbreviate to CA). I also use a 1.14 port texture pack because I dislike the old textures, but removing that doesn't fix anything and makes everything look sad. Either HBM, Optifine, Better FPS, CA or one of the other mods I play with breaks all the powered armour sets and the murky/limp wings to appear as a static model of the starmetal armour set (although the wings appear as some sort of white-dyed leather armour?). It shouldn't be any of the extra mods I have, however I can't test what happens if I remove Optifine or Better FPS as my puny laptop simply won't run the game, and when I remove CA nothing changes. (The list of mods I use is at the bottom of this issue.) It seems to only be the powered armour sets and their icons and function are still fine, but I'm fairly certain that DNT isn't quite the same as starmetal. I don't know if this is a known conflict between HBM and Optifine, but I couldn't find any existing issues with a similar problem, so who knows.

And now, the screenshots begin. (each caption is for the image above it)

![how broken power armour works](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/90362124/6af768ae-57dc-424a-b633-4190839438ca)
How the broken texture looks, aka that feeling when you try to walk and your pants don't move.

![how normal starmetal works](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/90362124/ae4be809-a713-4f90-ace5-012bda1c6c9b)
How armour sets with that moon on the front should work, aka when you try to walk and your pants do move.

![limp wings](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/90362124/a822070c-cab6-41fb-9346-fa8097767a31)
What the limp/murky wings look like (this screenshot was from limp, but it's the same for murky)

Another thing I've noticed, on a similar thread, is the T45 armour texture is _completely_ messed up. As in, there are bits of gray and brown everywhere, even when I only wear the helmet. It might be how it's meant to look, but I doubt it.
![t45 helmet](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/90362124/3ea9de2c-f5e9-4be4-a233-25dbf635d443)
T45 helmet

![t45 chestplate](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/90362124/04d7b365-4ee5-48e5-aa9e-a5b281b1d996)
T45 chestplate

![t45 leggings](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/90362124/5333e5ac-9813-4531-968f-1b8abdc9f1ac)
T45 leggings

![t45 boots](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/90362124/25e15b5e-9937-4f4a-bc91-e47debfa4d9d)
T45 boots

![full t45](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/90362124/2a918ee5-63fb-4b81-9b77-3e2f708b3bd0)
Full T45 set

And now, a visual list of all the armour sets (minus T45), and a written list of all my mods.
![armour sets with starmetal texture](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/90362124/ca6cd739-e0d3-4cc9-aaaa-93f38d43ae30)
Armour sets with static starmetal texture

![armour sets with normal texture part 1](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/90362124/89114fd5-9dbe-4e80-a0ef-b2c0d61816ab)
Armour sets that are fine part 1 (side note: the PaA not-battle armour set seems to be missing a helmet, or I just couldn't find it)

![armour pieces with normal texture part 2](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/90362124/76117515-779d-430d-9d71-51ee74dcb766)
Armour pieces that are fine part 2 
My modlist:
- Actually Additions
- Backhand
- Backlytra
- Better Builder's Wands
- Better FPS
- CodeChickenCore (for NEI)
- CodeChickenLib
- Controlling
- Cosmetic Armour Reworked
- Crafting Tweaks
- Extra Utilities
- Fast Leaf Decay
- FTB lib
- FTB Utilities
- HBM's Nuclear Tech Mod (latest version, 1.0.27 X4648, but it happens on all versions I can be bothered to load up)
- Inventory Tweaks
- Iron Backpacks
- Iron Chests
- Journeymap
- MCHeli
- MmmMmmMmmMmm (target dummy)
- Mouse Tweaks
- Mr Crayfish's Furniture Mod
- Vic's Modern Warfare
- Nature's Compass
- Not Enough Items
- OpenBlocks
- OpenModsLib
- Open Modular Turrets
- OptiFine (version HD_U_E7)
- SecurityCraft
- Vic's Modern Warfare
- Waila
- Waila features
- Wawla (aka more Waila features)
- Waystones

**Comment by sendhelppls213** [comment]
Remove Vic's Modern Warfare. That mod features a coremod, which messes with the rendering methods of a lot of other mods, including NTM.

**Comment by SsilverLeopard** [comment]
Oh, that makes sense. Thanks so much!
