### ISSUE TITLE
Request: Turn off meteorites

### ISSUE THREAD

**Issue by FinlayDaG33k** [HbmMods/Hbm-s-Nuclear-Tech-GIT#11]
As the name suggest, please add an option to turn off meteorites...

**Comment by Eddybeast** [comment]
You can in the settings of the mod in the config folder but help me  batteries don't work!!!!!!!!!!!!!!!!

**Comment by FinlayDaG33k** [comment]
Yea, I found the config by now :) 
forgot to close :) 

as for your issue, I'll check your issue (#12) in a moment.
