### ISSUE TITLE
Add a gamerule to make rbmk explosion bigger

### ISSUE THREAD

**Issue by valina354** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1100]
not bug just a suggestion

there should be a way to make it how big the rbmk explosion is, in my map after it explodes the explosion doesnt reach high enough to go through the roof

**Comment by OctoberE** [comment]
this is the issue tracker it's not for suggestions

**Comment by valina354** [comment]
> this is the issue tracker it's not for suggestions

well i see some other issues have the 'enhancement' tag soo

**Comment by JameH2** [comment]
dont even bother trying to argue this, suggestions are not allowed on this issue page, its for bugs only

**Comment by LePeeperSauvage** [comment]
> 

The cute twink's right.
