### ISSUE TITLE
MK5 algorithm oddities

### ISSUE THREAD

**Issue by 70000hp** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1101]
If you've seen the bug report I made, skip this whole bit
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/105080577/e8e51e0c-dd3d-49fe-99ab-8bd76cbd3439)
Whenever MK5 is called somewhere completly encased by blastproof blocks, such as concrete and etc, it errors badly and deletes everything in a circular radius. The picture above shows a comparison between a little boy, greg nuclear shells (both of which spawn their explosion above the concrete) , and a nuclear missile (spawned the blast within the concrete)

If I were to hazard a guess, the issue would be at the processing, since I checked ray hits using a debugger and they seemed to hit about where they meant to
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/105080577/51d517ec-0c5b-492d-a5c1-2e90a080b1b7)

Specifically the inChunk check, since the only chunk that errors is the chunk where mk5 was actually called at.
Here's a glitched chunk, made by completly encasing a nuclear charge in concrete
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/105080577/49c5acce-9301-4cb6-a8b3-19ff1f45153a)
Another reason why its probably the inChunk check, is because when I removed it entirely for testing, the blast had the exact same shape, except it was all the chunks it affected 
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/105080577/785f37c9-4a12-482f-9138-d7bee9d0925a)

A temporary fix for the missiles would be to simply offset where the explosion is called up, proportional to how big the blast is, I found that 6 blocks up works for a 100 radius missile.

**Comment by HbmMods** [comment]
![grafik](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/16674258/1a680059-a0a8-41d0-bfc0-cbdaae42a3d8)

this guy goes into the negatives when processing the center chunk, causing the explosion rays to extend in the opposite direction
