### ISSUE TITLE
armor with effects crashes other people on a server

### ISSUE THREAD

**Issue by Epikreaper19** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1106]
when a person is wearing an armor that provides a full set bonus, it crashes people that are in the same loaded chunk range.

i am not currently able to get a crash log, but i think i know the problem.

typically this happens because Armorinslot value (client sided) is used instead of getinventory value.

**Comment by HbmMods** [comment]
Neither `EntityPlayer` nor `EntityLivingBase` have a method called `armorInSlot` nor any client-only methods related to getting armor, nor can i do a whole lot without the actual crash report.

**Comment by JameH2** [comment]
How did you make that conclusion when you dont even have the crash log “right now” as you said, please provide the report so your issue can be resolved properly

**Comment by Epikreaper19** [comment]
i will admit that my knowledge is lacking, but this is a known issue for mods all around, i will provide a crash 


On Sunday, July 9, 2023, 11:59 AM, JameH2 ***@***.***> wrote:




How did you make that conclusion when you dont even have the crash log “right now” as you said, please provide the report so your issue can be resolved properly
