### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1109]
I was looking on the RBMK rod flux functions and thought to myself:
What is X? All the flux equations have it and its not clarified anywhere what exactly it stands for, even in the source code so i thought it would be useful to have it clarified somewhere

Thanks for reading :P

-Chosen

**Comment by HbmMods** [comment]
Incoming flux, the whole reactor works off of the concept that rods exchange and react to neutrons. Please refer to the instruction manual.
