### ISSUE TITLE
Add a mixer to produce concrete more efficiently

### ISSUE THREAD

**Issue by iamsoNewBee** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1110]
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/98573273/24237481-736e-41a5-8c68-ce7c76090151)
it`s closer to the reality (and very cool).

**Comment by JameH2** [comment]
>le realisme

Its best you cite a different reason why you want this in the mod

Better yet, suggestions arent allowed here!

**Comment by iamsoNewBee** [comment]
Chemical Plant shouldnt be so powerful to do everything and nowhere to suggest

**Comment by JameH2** [comment]
Im sorry have you heard of
-the industrial mixer
-the solidifier
-the liquefaction machine
Or any sort of petrochemical machine out there

**Comment by JameH2** [comment]
A mixer with a solid output does sound like a great idea but having one machine for one thing is blehhh :p

**Comment by iamsoNewBee** [comment]
> Im sorry have you heard of -the industrial mixer -the solidifier -the liquefaction machine Or any sort of petrochemical machine out there

so why not to have more machines to share  Chemical Plant s duty while concret is a building resources with high demand and dependence.(i dont hope it replaces Chemical Plant`s function but to be more efficiently

**Comment by JameH2** [comment]
Because bob and his ~~slaves~~ contributors are busy with literally everything else to care about that

Idk what to tell you

**Comment by iamsoNewBee** [comment]
i am not pushing him to add. just a suggestion maybe one day i will make a mod to achieve this if he doesnt like it lol

**Comment by JameH2** [comment]
A suggestion is a suggestion, no matter if
Its pushy or subtle

The chad move is to fork and pr, and pray to god he accepts it and if he doesnt? Woopsie

**Comment by iamsoNewBee** [comment]
maybe u dont have to be so serious?i dont think its pushy but u

**Comment by HbmMods** [comment]
Concrete is already incredibly cheap and ridiculously easy to make.

> Chemical Plant shouldnt be so powerful to do everything 

The whole point of the chemical plant is to have a universal machines so that I don't have to make 400 machines for every single chemical process.

> and nowhere to suggest

And there's a good reason for that.
