### ISSUE TITLE
Where is the Benelli Non-Drum Version?

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1112]
With the recent addition of the Benelli M4 Semi-automatic shotgun as a weapon, i was thrilled and immediatly began testing, however, i realized that the Benelli does NOT have a version where it uses its standard magazine size (Civilian 5+1 Shell capacity) so i thought it would be better to have the standard benelli have the Civilian Shell capacity and then make a 9+1 military upgrade, and THEN have the drum 24 shell magazine, and then have the drum version slow you down or slow down firerate to make the shorter versions more viable, this is just my opinion and i dont really know if its possible but i´d love to hear your thoughts on it

Thanks for reading

-Chosen

**Comment by JameH2** [comment]
Hi

this is a great idea! Unfortunately suggestions arent allowed on this board, so your beneli M4 idea will be referred to someone else…


Introducing the suggestions box! Here, you can put any suggestions, flip this switch, and it turns into a bunch of little flakes to play with! Fun for the whole family


Suggestions arent allowed here. Please never make one again

**Comment by HbmMods** [comment]
so you're asking for three variants of the exact same gun, with the only difference being the mag size. yeah that's not happening.
