### ISSUE TITLE
Is there a way to remove the new mechanics of opening large doors through redstone?

### ISSUE THREAD

**Issue by Wekdol** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1113]
I can't get used to the new mechanics, and I don't want to switch to the old version because there is noticeably less content. Please help me. Version: 1.12.2-1.9.7

**Comment by JameH2** [comment]
This is for 1.7.10, not 1.12

**Comment by HbmMods** [comment]
Please refer to #1039
