### ISSUE TITLE
Game crashes when placing a ME Storage Bus on Template Crate

### ISSUE THREAD

**Issue by Creeper-banner** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1116]
### Describe the bug

When trying to put a ME Storage Bus (from an unofficial version of Applied Energistics 2 made by GTNH team, which can be found at https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial) on a Template Crate (from HBM), the game crashes.
Crash report: https://pastebin.com/7ftdMxcm

HBM version: X4662, Applied Energistics 2 version: rv3-beta-238-GTNH-pre.
No other mods installed.

**Comment by HbmMods** [comment]
Fixed in X4663.
