### ISSUE TITLE
Question: Hematite blast resistance

### ISSUE THREAD

**Issue by slipwolff** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1121]
Running version 1.0.27_X4663.
Not sure if this is a bug or not, but should hematite not get destroyed when a nuclear explosion occurs? I decided to do some tests on a singleplayer world and accidentally found that hematite did not get destroyed after dropping a size 15 nuclear warhead as visible in the screenshot below:
![2023-07-23_13.33.33.png](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/27822055/a5761b9c-3d6a-4ca9-9183-65de44c2204f)

**Comment by HbmMods** [comment]
Hematite has roughly the same blast resistance as stone, what you're seeing is an overly deep crater due to how little blast resistance sandstone has.

**Comment by slipwolff** [comment]
Thanks for letting me know, love the mod.
