### ISSUE TITLE
RBMK rods have a offset

### ISSUE THREAD

**Issue by therealtunge** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1127]
### Describe the bug

RBMK rods have an offset from their actual block, here's an image
![Untitled](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/139690696/b127bace-6c27-4853-b092-e8451ae94e2d)

**Comment by HbmMods** [comment]
That's a floating point error that affects many blocks, not just RBMKs, it's because of the position you're at.

**Comment by therealtunge** [comment]
oh, i just remembered im at 100000 in z and x
welp
