### ISSUE TITLE
 Machine addition

### ISSUE THREAD

**Issue by AVASSON** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1129]
Hello author, how can I add a machine to HBM by modifying the code?

**Comment by OlorinIV** [comment]
https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/wiki/Custom-Machines-Guide
Wiki's unfinished, you could try to refer to the example machines in the mod or wait for the mod author to update the wiki.
