### ISSUE TITLE
Items/Blocks registered with the item./tile. string

### ISSUE THREAD

**Issue by TrueSanicWasHere** [HbmMods/Hbm-s-Nuclear-Tech-GIT#113]
Hey HBM,
novice modder Sanic here! So, I took a look at the src, so I could probably gain some new knowledge on modding. I am grateful I did, since I managed to obtain some valuable knowledge, despite the fact I didn't really see much.
So, I got at the ModBlocks.java file, and guess what I found:

GameRegistry.registerBlock(placeholder, placeholder.getUnlocalizedName()):

What is the issue with this? Well, instead of showing modid:placeholder, it shows modid:tile.placeholder. Oh yes, I know it can take a great deal of time fixing this, but it can be quite annoying. In my opinion, adding a .substring(5) after the .getUnlocalizedName() can be an exceptionalo quality-of-life addition.

To my last point: Was it intentional not to substring it?
Thanks for your time, looking forward to your answer!
-Sanic

**Comment by HbmMods** [comment]
Not only is that not much of an issue, "fixing" this would also have the side effect of breaking every single block in every existing world that updates. Not to mention any custom recipe files, item ban lists from plugins and so on.

**Comment by TrueSanicWasHere** [comment]
Understandable, have a great day
