### ISSUE TITLE
Custom machines set up issues

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1131]
With the recent experimental HBM versions i have begun experimenting with custom machines, i took the three preset machines set in the release, i extracted the contents of the .json file and pasted it into the HBM config folder, for some reason despite the multiblock forming it does NOT perform its actions, all three machines are irresponsive, with the only custom machine working being the paper press, the three machines accept energy and liquids, but dont work or output anything, have not tested creating my own machines

Thanks for reading

-Chosen

**Comment by HbmMods** [comment]
Currently known issues are that custom machines don't properly output fluids and that item inputs don't work beyond the first slot, everything else works fine. Are you sure the config is a valid JSON file? Did you ensure that the JSON format is valid? Also, do all machines have valid recipe sets as defined in the recipe config?

**Comment by TheChosenIndividual** [comment]
I didnt do any changes to the .json file sample, i just took it and pasted it into the HBM config folder, which might be what is causing problems, personally i did not encounter any input issues, with the paper press at least, however i did notice that the circuit blocks are left unused, which may not be shown in the hologram and might be causing issues? hope this clears your questions

-Chosen

**Comment by HbmMods** [comment]
There was a known issue where the machines would lookup recipes with their unlocalized name instead of the recipe key, which means that if the unlocalized name and recipe key were different, none of the recipes would work. This issue has been resolved.
