### ISSUE TITLE
Extra Cells storage disks don't have radiation

### ISSUE THREAD

**Issue by jonab03** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1134]
### Describe the bug

When you put radioactive materials in a ME storage cell it gets radioactive.

This doesn't hold true for the extra large storage cells from [Extra Cells 2. ](https://www.curseforge.com/minecraft/mc-mods/extra-cells-2-samlam140330s-fork)

Steps to reproduce:
1. Set up an ME system with a storage cell from extra cells 2.
2. Insert radioactive materials into this ME system.
3. Observe the lack of radiation from the storage disk.

Video because I have too much time on my hands: 

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/57867790/f4500c8b-0cff-4bd6-a3e0-7758d497756c

**Comment by HbmMods** [comment]
There's no standardized save structure behind AE2 cells, if Extra Cells uses a different format than standard AE2 then there isn't a whole lot I can do about it.
