### ISSUE TITLE
Question: How do i install custom machines to my game?

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1136]
This is a follow up to my previous issue where i said the custom machines had set up issues....since im an idiot and that is no surprise i started to wonder wether i had even installed them correctly after the NEI handler was set up, can anyone give me a simple guide so that i can install the custom machines properly? (Note: Im using the document provided by the github releases and it has not been modified, i tried pasting it directly into the HBM config folder, which didnt work as you might be assuming) Thanks in advance

-Chosen

**Comment by RaidhoSketch** [comment]
Well, if you're not _changing_ anything, well, there are two config folders, hbmConfig and hbmRecipes, and, IIRC, the first folder also holds a default (with an underscore) hbmCustomMachines.json, which you need to delete. And that's pretty much it, to be honest.

**Comment by HbmMods** [comment]
The [guide for all configs required for custom machines](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/wiki/Custom-Machines-Guide) was complated yesterday.

**Comment by TheChosenIndividual** [comment]
Thanks HBM
