### ISSUE TITLE
Why i can't build RBMK-1000 in survival?

### ISSUE THREAD

**Issue by SaneckekKrasava** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1137]
Why i can't? 
A cubic zirconia is needed for the fuel rod, a zirconium fragment is needed for it, an ore something is needed for it, and for it reinforced shredder blades are needed, which are made of 2 plates of advanced alloy and reinforced shredder blades... Something's not right here, is it? I wish it could be fixed. Version 1.12.2. The mod itself is a top, but it really upset me.

**Comment by SoB1nary** [comment]
you don't need **reinforced** shredder blades, you can use any of them, the only difference is durability (reinforced ones' is infinite)

**Comment by SaneckekKrasava** [comment]
Спс бро

вт, 8 авг. 2023 г., 11:43 SoB1nary ***@***.***>:

**Comment by WebmasterAnonymail** [comment]
#1039 and he has true in 1.12 advanced sherdder blade have a recipe missing and are uncraftable but they are needed to make somethings
