### ISSUE TITLE
Current GPU support

### ISSUE THREAD

**Issue by DB4000K** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1144]
I have heard that there have been accounts of graphical issues on **AMD** and **NVIDIA** cards, but I am also experiencing the issue on an **INTEL ARC A770** card. I am also wondering If support for Intel cards exists.

**Comment by HbmMods** [comment]
This issue is most prevalent on intel GPUs (especially integrated ones), please check out #985 for a list of things you can try to get the game to work.
