### ISSUE TITLE
(suggestion) turbine needs lubricant, control rod color

### ISSUE THREAD

**Issue by Ade0924** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1149]
Turbine needs lubricant, if it doesn't have lubricant it can still spin but it will damage over time and you will need to repair it with steel plates, you input lubricant through a separate input for it. Once inputted the lubricant will slowly convert into lubricant with metal shavings and to turn it back you need to put it through a filter. When you choose the color of the control rod the cover visually changes color to the chosen one.

**Comment by HbmMods** [comment]
that is horrible

**Comment by Ade0924** [comment]
Atleast the rod color :(((

**Comment by JameH2** [comment]
why would you ever do that to turbines

**Comment by Ade0924** [comment]
Realism but I just realized it's a pain
