### ISSUE TITLE
Can't load up minecraft

### ISSUE THREAD

**Issue by NightBasil32671** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1150]
When I had the mod on it would crash with exit code 1. I just wanted to play the mod. Here is my crash report. The only other mod was Not Enough Items. They were both at the top of the 1.7.10 version list. Can you fix it? 
[launcher_log0.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/12353653/launcher_log0.txt)

**Comment by burningwater202** [comment]
Looks like you’re trying to run 1.7.10 NTM on 1.12.2 forge based on the log, with the 1.18.2 version of Optifine

**Comment by burningwater202** [comment]
No wait- I was too early in the log
Check to see if you have codechickencore as that is a requirement for NEI and it shows in the log that it is missing
