### ISSUE TITLE
DFC bug? 

### ISSUE THREAD

**Issue by BloomerBro** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1153]
### DFC emitter not shooting its lasers out correctly
HBM-NTM-.1.0.27_X4648 - 4690

I'm trying to set up a looping single core DFC reactor from a Savage Vegeta video and when I place a DFC emitter it will only shoot out on block in front of it and not beyond that, I even tried it in different directions and still wont work right. so I thought maybe it was because it was in a bunker? so I put a DFC emitter outside of it and it works properly as it shoots out to its usual distance and I I built the reactor 4 times in a throwaway flat world to make sure I wouldn't mess up and blow it up so I know it works. I was running version X4648 so I assumed it would fix if I updated to the latest and still the issue persist 

sometimes my world crashes so I'll provide a crash log and latest log in case it helps:

[crash-2023-08-17_11.42.00-client.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/12373462/crash-2023-08-17_11.42.00-client.txt)

[latest.log](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/12373455/latest.log)

pic related 
![errorDFC](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/142539193/f2340fe3-f4a6-4bc8-932c-06b0fc94acee)

**Comment by BloomerBro** [comment]
I also now realize the stabilizer also doesn't' shoot its lazer at all either when supplied with power

slighty better pic of the emitters not shooting right 
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/142539193/87ae82f2-b06d-4310-b4ff-17c9a4a3f637)

**Comment by ncr-t** [comment]
if your modpack has railcraft, then that’s the root of your problem, go in the config and make sure air blocks are disabled

**Comment by BloomerBro** [comment]
THANKS 
also in the folder for railcraft do ya have any idea as to which file air blocks would be in? 
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/142539193/9613bb5f-6954-4854-8397-80068f82f730)

**Comment by BloomerBro** [comment]
I mean what I'd have to edit I know it would be blocks but not sure what I'm lookin for

**Comment by ncr-t** [comment]
there’s a railcraft file in your config folder, in the .minecraft directory, you might be able to access it through the main menu as well though

**Comment by BloomerBro** [comment]
yea sorry I cannot find air blocks or I'm blind 
 IN the file named railcraft right? 
 
 
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/142539193/30be1c7e-37db-4efb-8c0e-9812f58211d4)

**Comment by ncr-t** [comment]
idk man check everything I guess I don’t know the file structure by heart

**Comment by BloomerBro** [comment]
I decided to delete the mod since I don't use it anyways and the problem _kinda_ persist still with the stabilizer not shooting out and the emitters only shooting if you place and break a block in front of it.

**Comment by BloomerBro** [comment]
nvm the emitters are still fucked

**Comment by HbmMods** [comment]
NTM is supposed to automatically remove the Railcraft air block to prevent stuff like that from happening. Do you by any chance have Galacticraft? I know its arc lamps have a similar issue because they work by replacing air with invisible glowing blocks.

**Comment by BloomerBro** [comment]
yeah I do... this would have been useful to know when I still had my world (deleted everything to remake my modpack ) anything I could do to fix it? cause there was one in the room also

**Comment by HbmMods** [comment]
Not sure, although the most recent commit might fix the issue for all air-like blocks that aren't vanilla air.

**Comment by HbmMods** [comment]
Should be fixed in X4704.
