### ISSUE TITLE
A config for all condenser types to need water input

### ISSUE THREAD

**Issue by Ade0924** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1155]
In real life, condensers need cool water in order to condense steam. It would be cool to have a config for it to add more realism :D.

**Comment by OlorinIV** [comment]
> Introducing realism in the game is for interesting mechanics and reasonable development pathways as I see it, not for the sake of its own or causing player pain level to rise during playthroughs for common issues.
That's a good conclusion to this issue and the other one before. Also notice suggestions are invalid here.

**Comment by OlorinIV** [comment]
> Introducing realism in the game is for interesting mechanics and reasonable development pathways as I see it, not for the sake of its own or causing player pain level to rise during playthroughs for common issues.

That's a good conclusion to this issue and the other one before. Also notice suggestions are invalid here.

**Comment by BallOfEnergy1** [comment]
realism realism, also it would induce more pain than its worth

**Comment by BallOfEnergy1** [comment]
(Also suggestions aren't really taken here, especially since its primarily a place to report bugs in the mod)
