### ISSUE TITLE
the game closes upon opening chemical plant

### ISSUE THREAD

**Issue by Bencek123** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1156]
i had my game crash whenever i open  a chemicel plant it just started happening
i will atach my crash log to the issue
[crash-2023-08-20_14.52.56-client.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/12388209/crash-2023-08-20_14.52.56-client.txt)

**Comment by HbmMods** [comment]
Did you change any of the chemical plant recipes? Because if the processing time is set to 0, this exact crash would happen.

**Comment by Bencek123** [comment]
I think its because i used a speed mk3 and two overdrive mk3 in the chemichal plant wich makes them go instantly

**Comment by BallOfEnergy1** [comment]
> I think its because i used a speed mk3 and two overdrive mk3 in the chemichal plant wich makes them go instantly

That shouldn't happen, though I haven't tried it so I'm not sure.

**Comment by Bencek123** [comment]
> That shouldn't happen, though I haven't tried it so I'm not sure.

wich recipe where you using? I was using the boosted xenon to use in my plant to convert liquid oxygen into xenon and that has a 1 secont time with no upgrades
