### ISSUE TITLE
guide book

### ISSUE THREAD

**Issue by xiaolizi558855** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1162]
### Describe the bug
1.7.10-forge 10.13.4.1614
HBM-NTM-.1.0.27_X4690
I will receive a guide-book after entering the game, but I don't want to get it for free, because it can be used as unlimited fuel. I want to close it but I can't find this item in the configuration file.

**Comment by HbmMods** [comment]
Fixed in X4704, you only get one after joining for the first time.
