### ISSUE TITLE
Problems with custom machines

### ISSUE THREAD

**Issue by MCNaOtlichnoYT** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1167]
I tried to make a machine that can produce your first schrabidium without damaging the world. The recipe is meant to be 1 nuclear charge + 64 uranium ore = 1 schrabidium ore. The machine assembles perfectly but it produces schrabidium using only power. It doesn't even need input items. Here is my config from HbmConfig (they are .json but I can't upload .json).
[hbmCustomMachines.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/12447987/hbmCustomMachines.txt)

**Comment by MCNaOtlichnoYT** [comment]
And this is from hbmRecipes.
[hbmCustomMachines.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/12447988/hbmCustomMachines.txt)
What am I doing wrong?

**Comment by HbmMods** [comment]
I think the issue is on line 29, after the entry for `oreUranium` you have a comma followed by nothing, which because of the JSON parser implementation defaults to a `null` value. Usually the recipe should just refuse to load, but in certain instances it might result in weirdness like that.

**Comment by MCNaOtlichnoYT** [comment]
Thank you, now it works as I expected.
