### ISSUE TITLE
[Mod compatibility] Vampire enchantment, ironically, causes Vampire players from Witchery to die without dropping a grave (openblocks)

### ISSUE THREAD

**Issue by penguin-glitch** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1168]
This may not be a bug on HBM's end, but seeing as the other two mods involved in this are no longer actively updated for 1.7.10, I thought I'd give this a try here. 

HBM version: 1.0.27_X4648
Witchery version: 1.7.10-0.24.1
Openblocks version: 1.7.10-1.6

Description of bug: Weapons with the Vampire enchantment (added by this mod) can kill Witchery vampires, overriding their immortality (which is normal, actually, because I assume it's magic damage), but prevents a grave from spawning. Behavior does not occur with any other form of magic damage (which do kill vampires, but allow a grave to spawn). Most notably, a death message does not appear in chat, though OpenBlocks does seem to log the death correctly and the inventory can be restored with /ob_inventory restore. 

Occurred on multiplayer server, tested in singleplayer using Thermal Expansion autonomous activator equipped  with schrabidium and CMB steel swords. Behavior does not occur with any other weapon, including max level meteor sword. Same behavior applies to Schrabidium Hammer, but not the /kill command. Similar weapon, the Sword of the Cosmos from Avaritia, kills vampires but allows grave to spawn. 
Nonvampires appear unaffected (i mean they still die), but other methods of immortality have not been tested. Impossible to test if this applies to the shackle, as player dies of radiation poisoning or shackled leggings break before the enchantment can get their health low enough to test.

**Comment by HbmMods** [comment]
Fixed in X4760.
