### ISSUE TITLE
[Suggestion] Config option to limit shackle death preventions

### ISSUE THREAD

**Issue by penguin-glitch** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1169]
Shackle appears to have infrastructure in place to be limited, though the limit does not appear to be implemented ("revives remaining: infinity"). A config option would be nice to limit the amount of revives, especially on servers where the infinite revives is somewhat unbalanced given the cost.

**Comment by LePeeperSauvage** [comment]
It doubles your radiation everytime you die, and doesn't revive you if you're radiation poisoned to death, you goob

**Comment by HbmMods** [comment]
> though the limit does not appear to be implemented

While there is no hard limit on the revives like the other items, there is a soft cap caused by the increasing amounts of radiation you get per revive, capping effectively at 31.
