### ISSUE TITLE
Items in breeding reactor disappear when quitting singleplayer

### ISSUE THREAD

**Issue by TrueSanicWasHere** [HbmMods/Hbm-s-Nuclear-Tech-GIT#117]
Title, but the uses left don't.

**Comment by TrueSanicWasHere** [comment]
How to reproduce:
1) Put some stuff in reactor
2) Quit singleplayer world
3) Rejoin singleplayer world
4) Check reactor. It should be empty

**Comment by Nos74** [comment]
It hungers! **FOR MORE**

**Comment by TrueSanicWasHere** [comment]
**Nom nom nom... oooom nom.**
**Breeding reactor materials make me STRONK**

**Comment by HbmMods** [comment]
Fixed, there was some leftover code from the old breeding reactor that would create a new instance of the slot array.

**Comment by TrueSanicWasHere** [comment]
yay, ty

**Comment by TrueSanicWasHere** [comment]
Lol @DrNostalgia I saw your Super Mario RPG issue. Hilarious.
