### ISSUE TITLE
Bedrock oil ore

### ISSUE THREAD

**Issue by di127** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1172]
what is the use of oil bedrock oil? Is there any way to extract It?  #171

**Comment by TheChosenIndividual** [comment]
Yes, you can extract it with a hydraulic fracking tower, from there it has a processing chain equal to that of regular oil, except bedrock oil lasts longer/never runs out, you CANNOT extract it with an oil derrick

Cheers

-Chosen

**Comment by di127** [comment]
> Yes, you can extract it with a hydraulic fracking tower, from there it has a processing chain equal to that of regular oil, except bedrock oil lasts longer/never runs out, you CANNOT extract it with an oil derrick
> 
> Cheers
> 
> -Chosen

Thanks Bro, u saved me
