### ISSUE TITLE
When will the 1.16.5 version be released?

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1176]
**Today I decided to try to remake NTM for Minecraft version 1.16.5, but I didn't succeed.
Therefore, I wanted to find out about the official release of the mod for this version.**

**Comment by burningwater202** [comment]
The 1.16.5 version will release in July of 2085

or never, whichever comes first

**Comment by JameH2** [comment]
It came out in 2005, you just need to find it

**Comment by ghost** [comment]
> 
Логичный и разумный ответ!

> Версия 1.16.5 выйдет в июле 2085 года
> 
> или никогда, в зависимости от того, что наступит раньше
