### ISSUE TITLE
Paintable Red Copper Cable glitches with Grass Block

### ISSUE THREAD

**Issue by coolestkid91021** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1178]
Minecraft Version: 1.7.10
Hbm's NTM Version: 1.0.27 X4707

If I use a grass block on a paintable red copper cable, the top texture displays a white color.

![2023-09-01_15 31 31](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/140053519/d909e4d5-5441-49b3-81c3-d37633a6f948)

Pls fix.

**Comment by coolestkid91021** [comment]
forgot to add this

**Comment by coolestkid91021** [comment]
This also applies to Paintable Coated Universal Fluid Duct.

![2023-09-01_15 38 19](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/140053519/febc5a58-7de2-44f0-ba39-89bda3c1b368)

**Comment by HbmMods** [comment]
Known issue, grass uses hardcoded rendering which I can't emulate using the paintable blocks, causing the biome-specific color to be lost. Not much that I can do about it.
