### ISSUE TITLE
[Question/Bug] Got infinite PTSD effect from blowing a nuke

### ISSUE THREAD

**Issue by Skyliner77** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1180]
So we detonated little boy in full H.E.V. suite set and still got blinded to oblivion, HUD shaking and blind effect still on after 20min or so, PTSD medication, respawning, restarting or dying isn't helping, /effect clear does nothing either, couldn't find any useful info in player.dat too. 
HBM-NTM-.1.0.27_X4707

**Comment by HbmMods** [comment]
There was similar reports back when the digamma ash overlay was still a thing. Do you have any other mods? Because the flash is based on a small timer that is neither a potion effect nor part of the playerdata, rather it's just a number that exists on the client that is supposed to tick down over 5 seconds, but something is preventing it from doing that.

**Comment by Skyliner77** [comment]
Oh boy, do I
Here the list:
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\Carpenters_Blocks_v3.3.8.1_MC_1.7.10.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\CashCraft-[1.7.10]-1.0.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\Chisel-2.9.5.11.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\codechickencore-1.7.10-1.0.7.48-universal.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\cofhcore-1.7.103.1.4-329.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\coroutil-1.7.10-1.1.6 (1).jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\CosmeticArmorReworked-1.7.10-v7.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\craftingex_1.7.2-v1.0.5.1.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\creativecore-v1.3.24-mc1.7.10.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\CustomStuff3-0.7.10-MC1.7.10.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\dimensional-anchor-59.0.3.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\endercore-1.7.10-0.2.0.39_beta.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\enderio-1.7.10-2.3.0.429_beta.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\EnergyControl-1.7.10-0.3.4f.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\extracells-1.7.10-2.3.14b200.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\extrautilities-1.2.12.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\ForgeMultipart-1.7.10-1.2.0.345-universal.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\gravestonemod0.7.10.3-1.7.10.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\HBM-NTM-.1.0.27_X4707.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\Immibis-Core-1.7.10.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\ingameconfigmanager-alpha-v0.1.15-mc1.7.10.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\InventoryTweaks_1.7.10_1.59_dev_152.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\iron_chests_mod_1.7.10.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\jaad-0.8.5.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\justenoughcalculation-1.7.10-3.8.5.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\MatterOverdrive-1.7.10-0.4.2.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\minetweaker3-1.7.10-3.0.10b.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\mobproperties-1.7.10-1.0.2.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\modtweaker2-0.9.6.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\mouse-tweaks-mod-1.7.10.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\naturescompass-1.7.10-1.3.1.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\neiaddons-1.12.14.40-mc1.7.10.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\notenoughitems-1.7.10-1.0.5.120-universal.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\onlinepicframe-v1.0-mc1.7.10.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\oredictionaryconverter-1.6.1.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\RWG_alpha_1.3.2.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\SlimevoidLibrary_1.7.10_2.0.4.7.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\smoothfont-1.7.10-1.15.3.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\thermaldynamics-1.7.101.2.1-172.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\thermalexpansion-1.7.104.1.5-248.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\thermalfoundation-1.7.101.2.6-118.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\ThutMods-2.1.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\tradebooth.1.7.10.2.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\Traincraft-4.4.1_020-CE_6.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\VendingBlockRevived-v1.2.3.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\Waila-1.5.10_1.7.10.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\wanionlib-1.7.10-1.8.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\worldedit_forge_mc1.7.10_6.1.1_dist.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\WorldEditCuiFe-v1.0.3-mf-1.7.10-10.13.4.1566.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\xaeros_minimap_21.10.11_forge_1.7.10.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\XaerosWorldMap_1.14.1.5_Forge_1.7.10.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\zombieawareness-1.7.10-1.10 (1).jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\1.7.10securitycraftv1.8.13.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\1.7.10Treecapitator-universal-2.0.4.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\appliedenergistics2_mc1.7.10_rv3_beta_6.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\b3m-1.7.9-17.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\bariss-music-player-1.2.1.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\Baubles-1.7.10-1.0.1.10 (1).jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\BetterFps-1.0.1.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\BetterQuesting-3.0.328.jar"
"C:\Users\Skyliner\AppData\Roaming\.minecraft\mods\BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar"
Running this modpack on a 1.7.10 forge server with thermos installed as a core and offline mode enabled.
P.S. I saw warning in config about thermos but unfortunately I have no idea what tileentities.yml, is it that bad? Should I consider changing server core?

**Comment by Skyliner77** [comment]
No issues in single player. Must be server sided.
Upd: After some time I logged back on the server and effect was gone.

**Comment by HbmMods** [comment]
Should be fixed now, the flash now uses a global timestamp instead of a counter that can be interrupted. I'll close the issue if you can confirm it as fixed, as I couldn't replicate the original issue myself.

**Comment by Skyliner77** [comment]
Yep, all fixed, thank you ❤️
