### ISSUE TITLE
Redcoil Capacitor can not be output from Schrabidium Transmutation Device

### ISSUE THREAD

**Issue by gengyunmaster** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1187]
Hello! I found some difficulties in automating the productive process of Schrabidium by using Schrabidium Transmutation Device. The Redcoil Capacitor with 1/10 durability in the left upper corner slot of Schrabidium Transmutation Device can not be extracted by ANY item pump I have known. Is there an intended feature you designed to force manual producing or a bug? I hope a better way to implement the automation will be possible in the coming version of HBM's NTM. Thanks for your time reading this question/suggestion.

**Comment by BallOfEnergy1** [comment]
It's intended, as it will only output when it reaches 0/10 durability.

**Comment by HbmMods** [comment]
The capacitor can be pulled out just fine using pipes once it has hit 0 durability, yours still has some usage left.
