### ISSUE TITLE
How can i calculate incoming flux for the RBMK?

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1189]
A little while ago i posted a question, and that was "What is X in the Flux function of RBMK fuel rods?" Apparently it stands for Incoming Flux, however, i do not know how to calculate it, and as such cant anticipate the amount of flux that will happen in my reactor BEFORE running, is there any way to calculate incoming flux taking into account things like control rod insertion or xenon poison? 

Thanks

-Chosen

**Comment by BallOfEnergy1** [comment]
Calculating xenon generation/burn isn't the easiest for a human, though it's possible to calculate it with 0 xenon.
Control rods block a % of the flux going through the column depending on the insertion (100% insertion being 100% blocked; 1:1 ratio)
When a rod receives flux from another rod, it will begin outputting its own flux, which can flow back into the rod that originally made the flux, increasing the total flux. This makes it somewhat complex to calculate, though with a small script or some patience you can calculate the interaction between 2 fuel rods.
Xenon just makes it harder, as it changes (like a control rod), but being dependent on the flux. I haven't quite found a method to externally calculate RBMK fuel rods entirely, though calculating without xenon isn't that difficult.
Hope it makes enough sense.

**Comment by TheChosenIndividual** [comment]
> Calculating xenon generation/burn isn't the easiest for a human, though it's possible to calculate it with 0 xenon. Control rods block a % of the flux going through the column depending on the insertion (100% insertion being 100% blocked; 1:1 ratio) When a rod receives flux from another rod, it will begin outputting its own flux, which can flow back into the rod that originally made the flux, increasing the total flux. This makes it somewhat complex to calculate, though with a small script or some patience you can calculate the interaction between 2 fuel rods. Xenon just makes it harder, as it changes (like a control rod), but being dependent on the flux. I haven't quite found a method to externally calculate RBMK fuel rods entirely, though calculating without xenon isn't that difficult. Hope it makes enough sense.

Okay, so, drop Xenon, what about pre-calculating X BEFORE igniting the reactor core?

**Comment by BallOfEnergy1** [comment]
Well, there's an issue there.
You don't.
Before you ignite the reactor core, there's 0 flux as all control rods would be 100% inserted.
For calculating starting the reactor, you can use the flux rate from a neutron source to start as your first neutron flux value. (ofc multiplied by the control rod height)

**Comment by OlorinIV** [comment]
In my opinion it is unlikely possible for us to calculate the flux of a reactor that has not yet been ignited, or one that has not reached flux equivalence. And I think DODD has all information we need for a stable reactor, which flux scales with fuel reactivity and nothing else. DODD would probably solve your problem.
If not, then I hope you can describe your question more specifically. Give an example instead of vaguely saying 'calculate'.

**Comment by TheChosenIndividual** [comment]
> In my opinion it is unlikely possible for us to calculate the flux of a reactor that has not yet been ignited, or one that has not reached flux equivalence. And I think DODD has all information we need for a stable reactor, which flux scales with fuel reactivity and nothing else. DODD would probably solve your problem. If not, then I hope you can describe your question more specifically. Give an example instead of vaguely saying 'calculate'.

By using the neutron source flux giveoff function like @BallOfEnergy1 said, maybe we can calculate how much flux the reactor would have upon start up by using the interactions between fuel rods? although i´d take a bit more effort to calculate flux at criticality right?

**Comment by OlorinIV** [comment]
You can read incoming flux from a fuel rod's DODD, which can be done in a creative test world. I don't see the necessity of being able to predict whatever heat, flux or fuel depletion over time of a reactor since testing cost is little to zero in your creative test world.
However, I could give you a concept of how painful it will be to do this calculation ourselves, according to RBMK code.
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/104282311/d6316694-be5f-4077-b4bd-6bd7a00deb63)
And g(e), which the game isn't even supposed to inform you.
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/104282311/249b81c3-29df-419d-ae23-4ffb26744e11)
Okay, knowing these is probably going to help you choose the right function type for the automatic control rod if you wanted smooth power gen throughout most of your rod's lifespan.

**Comment by TheChosenIndividual** [comment]
can you explain g(e) a little....simpler...pls

**Comment by JameH2** [comment]
if you want to save yourselves a brainache, you can simply take any number and cite it as the "incoming neutrons" of an rbmks flux function.

for example, in the function for NU being:
log(x+1) * 0.5 * 15
x is equal to the incoming neutrons, that can be from anywhere, ranging from ra226be, to your mother when she falls into a PWR core.

in the function for Natural Uranium, the logarithm (used to find the exponentiation of a number) of (x+1) which we substitute x for incoming neutron flux, is then multiplied by 0.5 and 15 to get the total flux that is produced from incoming neutrons
for example, if the incoming flux is 14 then the output flux is 8.820
you can use a graph to visualize the exponential growth of a fuel rods flux function, where x is incoming neutrons and y is outbound splitted neutrons.

oh and apparently this also cites xenon, for that you can take the xenon burn function and it can tell you how many neutrons you need to successfully burn off xenon

control rods are interesting, im not sure what the math is behind that

**Comment by JameH2** [comment]
if you want to streamline this process, use this graphing website:
 https://www.desmos.com/calculator/n3vemkym6f
 this already has the listed functions for you to enjoy

**Comment by TheChosenIndividual** [comment]
Jame....you´re a hero, i did realize that before, but i had no reliable way to test it so....yeah....but wait is it flux in ALL directions? or is it divided in the 4 cardinals, because according to what i´ve seen its divided, but i still havent been able to find the RBMK math document yet, i´ve looked EVERYWHERE

**Comment by JameH2** [comment]
directions dont actually matter, all you need to account is the incoming flux, as that can literally be from anywhere

**Comment by JameH2** [comment]
however, reasim is in all cardinal directions, while normal rbmks are in 4, take this into account, as reasim is usually used differently

**Comment by TheChosenIndividual** [comment]
I have that in mind, taking into account i have made RBMK reasims before, i guess by adding the flux emitted by neutron sources we can determine flux and as such heat, that sounds like a good starting point

**Comment by Shibva** [comment]
I was gonna open something on this but I am glad this is here

Which OpenComputers support being present and online resources being an option; what if someone could make a program to help give a general idea of a RBMK setups behavior with certain fuels or a program that can give a rough idea of how certain functions would behave with other functions.


Either that or a section on the RBMK page to give a rundown on how to predict such; there was some but nothing about how to go about trying to get an idea on how a certain setups fuel would function

**Comment by BallOfEnergy1** [comment]
> I was gonna open something on this but I am glad this is here
> 
> Which OpenComputers support being present and online resources being an option; what if someone could make a program to help give a general idea of a RBMK setups behavior with certain fuels or a program that can give a rough idea of how certain functions would behave with other functions.
> 
> Either that or a section on the RBMK page to give a rundown on how to predict such; there was some but nothing about how to go about trying to get an idea on how a certain setups fuel would function

I would, though I've recently gotten busy. I may come back to my RBMK simulator I was designing, though it could be a while.
