### ISSUE TITLE
HBM 1.7.10, Nuke Flash & Shake permanent

### ISSUE THREAD

**Issue by gmBlahaj** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1190]
### Description
Version: HBM-NTM-[1.0.27_X4705] (on a server)
Detonating any nuke without being in an enclosed Room triggeres a permanent screen shake & very bright light

## How2Reproduce:
1. Detonate any Nuke
2. Look directly into the mushroom cloud

![2023-09-08_21 38 07](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/68054963/5c7e9fdb-f770-432f-ae2d-9c3f293dfcfd)

# Things ive tried to fix it:
1. Restarting the Server
2. Deleting Playerdata
3. Wait (like in the other [issue](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/issues/1180))

[Modlist](https://pastebin.com/pR7AvHbS)

**Comment by gmBlahaj** [comment]
Also: Killing yourself and PTSD Meds dont work either

**Comment by HbmMods** [comment]
You may want to update to [X4711](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/tree/1.0.27X4711) since it was fixed and confirmed there.

**Comment by Schizo272** [comment]
> You may want to update to [X4711](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/tree/1.0.27X4711) since it was fixed and confirmed there.

Worked thx

**Comment by gmBlahaj** [comment]
Worked thx
