### ISSUE TITLE
Nukes from hbm’s ntm cant render properly if you are too far away

### ISSUE THREAD

**Issue by FartasticYYZ** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1194]
If you try going far from the nuke it will disappear, but what really messes the effect up is that it turns invisible if you come closer to the explosion. If anyone knows a fix please let me know. And yes this is from 1.7.10.

**Comment by username228a91** [comment]
its caused by rendering distance

**Comment by HbmMods** [comment]
Yeah that's just render distance, either stay closer to the blast or use OptiFine to extend the render distance.

**Comment by username228a91** [comment]
or use chunk loading block covered with blast resistant things
