### ISSUE TITLE
New batteries aren't working!!!

### ISSUE THREAD

**Issue by Eddybeast** [HbmMods/Hbm-s-Nuclear-Tech-GIT#12]
Help me!! I can't use new batteries this is sad!! I take them in creative mode but they aren't work!!! SOrry for bad english I am 13 and i fail my english test but i love your mod!! Have fun and thanks for your mod!!

-Eddy05 the czech blockdestroyer beast

**Comment by FinlayDaG33k** [comment]
Hii Eddy, could you please tell me what you are trying to accomplish (maybe with screenshots?) and what the actual result is (also with screenshots preferably?)

**Comment by Eddybeast** [comment]
This is the screenshots!! The batteries don't discharge!!! They are like a carrott,they don't have charge and this is sad thank you finlay for helping me!!
![2018-04-14_14 12 50](https://user-images.githubusercontent.com/38373448/38768061-25d5d364-3fee-11e8-8f68-949dc571d8cb.png)

**Comment by FinlayDaG33k** [comment]
Hm... I can't even seem to find that particular item (even though it does show in the git repo).
What version of the mod are you running (or did you compile it yourself)?

**Comment by GrTaiyaki** [comment]
I compiled myself the last version in the repository last night!!! That battery is soooo cool 😃

**Comment by Eddybeast** [comment]
I compiled it myself!! That battery is soo cool!!

**Comment by FinlayDaG33k** [comment]
Hm... I can't really help you with that (I tried to compile the source but I get a bunch of errors when I drop the `assets` folder into the JAR (why do we need to do that manually anyways?)...)

**Comment by GrTaiyaki** [comment]
@FinlayDaG33k put the `assets` folder in a folder with the compiled jar and run `jar uf *.jar assets` from cmd,it will work

@Eddybeast in the "library.java" file @HbmMods forgot to add new "for" cycles to make new batteries charge or discharge
It's quite simple to implement a charge function so if hbm doesn't want to fix that bug i will (already did that on my pc on the ludicrous 100 THE crystal)

**Comment by Eddybeast** [comment]
Great!!! Let's see if hbm fixes or i will use your code!! Thank you GrTaiyaki!!

**Comment by HbmMods** [comment]
As the name implies, the current beta versions are not complete, so expect features to be half-baked. The new batteries will be finished no later when I add the new energy storage blocks.

PS: I just figured out that GH has email notifs, hopefully I'll stop missing all these issues. Derp.
