### ISSUE TITLE
Please add config option to return old nuke explosion

### ISSUE THREAD

**Issue by iocmet** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1200]

**Comment by JameH2** [comment]
But why? Is it performance?

**Comment by iocmet** [comment]
It looks better for me

**Comment by JameH2** [comment]
How so?

**Comment by iocmet** [comment]
New looks more like vanilla thing and not realistic

**Comment by Vaern** [comment]
muh réalisme

**Comment by JameH2** [comment]
Alright, I understand your point of view and everyone has your prefrences.


That being said, its a *minecraft mod* the nuke explosion effect resembling Minecraft at least puts a charm on the mod that wasnt there before, maybe im looking into it too much but considering that the new one has a convection simulation. I dont think old one was that realistic at all

And even then, why does it matter?? Why do people want the realism so bad??? A literal convection simulation is used but there is something missing? What the hell.


But again, its your choice. Just so you know i don’t believe suggestions are allowed here

**Comment by HbmMods** [comment]
no
