### ISSUE TITLE
No depleted uranium and thorium rods

### ISSUE THREAD

**Issue by WiccPL** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1202]
When i tried to transfer depleted uranium from my big nuclear reactor to a empty rod, it did not work. I tried thorium and it did not work too.
And they are not visible in creative

**Comment by JameH2** [comment]
big nuclear reactor? not the pwr?

**Comment by WiccPL** [comment]
Is says big nuclear reactor

**Comment by JameH2** [comment]
yes well the big nuclear reactor is deprecated, the pwr is the replacement

**Comment by WiccPL** [comment]
Oh ok thanks
