### ISSUE TITLE
Suggestion/Improvement: Various QOL Changes.

### ISSUE THREAD

**Issue by Howdidibreakit** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1204]
This is a simple improvement, focused on the realism. Essentially when a player looks at a nuclear explosion without headgear that gives the "bright lights" protection, they are blinded for 30 seconds.
Along with this, armor that protects against fire damage (when you're on fire you take no damage with this armor equipped) also hides the fire effect that covers half the screen.
Sound delay for nuclear explosions. Not sure if this is possible, but when they're detonated the sound only plays when the blast wave reaches you (the brown dust and gets flung up along with the mushroom cloud you know what i'm trying to say here).

**Comment by Antineutrino-4444** [comment]
you can try making a pr, which have possibility of being accepted. however saying it in issues will do nothing.
________________________________
From: Howdidibreakit ***@***.***>
Sent: Monday, September 25, 2023 9:37 AM
To: HbmMods/Hbm-s-Nuclear-Tech-GIT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [HbmMods/Hbm-s-Nuclear-Tech-GIT] Suggestion/Improvement: Various QOL Changes. (Issue #1204)


This is a simple improvement, focused on the realism. Essentially when a player looks at a nuclear explosion without headgear that gives the "bright lights" protection, they are blinded for 30 seconds.
Along with this, armor that protects against fire damage (when you're on fire you take no damage with this armor equipped) also hides the fire effect that covers half the screen.
Sound delay for nuclear explosions. Not sure if this is possible, but when they're detonated the sound only plays when the blast wave reaches you (the brown dust and gets flung up along with the mushroom cloud you know what i'm trying to say here).

**Comment by Howdidibreakit** [comment]
alright.
