### ISSUE TITLE
The wordgen menu button "generate structures" cannot disable the generation of structures from this mod

### ISSUE THREAD

**Issue by Maksymisio** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1209]
it just doesn't work

**Comment by JameH2** [comment]
This is because Minecrafts vanilla generation is seperate from ntm generation, to disable ntm generation, go to the cfg file in config and find the option to disable

**Comment by Maksymisio** [comment]
Ok i know about such possibility, but i have a problem that might be niche: if i have two worlds on which i play one in survival and one in superflat for testing setups do i need to reset my game and redefine the spawning values to make it so one of them has structures enabled and the other one has them disabled?

**Comment by OlorinIV** [comment]
It would be better if structure gen config is independent for different saves, and can be disabled by that button.

**Comment by HbmMods** [comment]
X4746 now disables worldgen if the superflat settings has structures disabled. Things like flowers will most likely still spawn, though.
