### ISSUE TITLE
Issues with Folly

### ISSUE THREAD

**Issue by TrueSanicWasHere** [HbmMods/Hbm-s-Nuclear-Tech-GIT#121]
The issues are the following:
1) The Folly (you know, the weapon whose actual name I don't know) can be stacked in stacks greater than 1.
2) The only ammunition accepted by the Folly is Starmetal Silver Bullets.

On a completely unrelated note, what software should I use to create 3d models for Minecraft?

**Comment by HbmMods** [comment]
The thing is also not craftable and the one shell that does work doesn't do what it's supposed to. That's because the folly isn't finished.
