### ISSUE TITLE
greg causes a crash when delivering a resource crate

### ISSUE THREAD

**Issue by TheVitya2127** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1211]
I don't know if this works in a single player world, but it works on a server. When trying to stuff an express delivery shell with a crate of resources into a greg, i fire at another base. A little wait and voila! **The server crashed.**

**Comment by HbmMods** [comment]
what do you want me to do without a crash report

**Comment by TheVitya2127** [comment]
Sorry, but I don't have access to the server

**Comment by TheVitya2127** [comment]
and yes, it's a server error

**Comment by TheVitya2127** [comment]
And so, I received a server crash report
[crash-2023-09-18_13.29.13-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/12801175/crash-2023-09-18_13.29.13-server.txt)

**Comment by HbmMods** [comment]
The server seems to be running version X4707 where this was a known issue which is cased by the delivery shells in general and unrelated to its contents. The crash has been fixed in newer versions.

**Comment by TheVitya2127** [comment]
Got it, thank you very much and sorry for bothering you
