### ISSUE TITLE
Custom machines dont accept firebricks as building materials

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1213]
When trying to make a recreation of an improved blast furnace, i ran into the issue that for some reason custom machines DONT accept non machine casing blocks such as fire bricks as their composing material, despite machines like the generator accepting lead, as such, i would like to know if this is intentional or a bug?, i feel like it is a bug due to the strange working of the generator and lead casing

**Comment by Vaern** [comment]
Please read [the guide for custom machines](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/wiki/Custom-Machines-Guide) before opening an issue, thanks.

**Comment by TheChosenIndividual** [comment]
> Please read [the guide for custom machines](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/wiki/Custom-Machines-Guide) before opening an issue, thanks.

I did, and the file complies with the set parameters, thanks

**Comment by HbmMods** [comment]
Are you going to show us the config or do we have to guess what you did wrong?

**Comment by TheChosenIndividual** [comment]
> Are you going to show us the config or do we have to guess what you did wrong?

Oh, right, my bad
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/120053489/e8e649cf-24c2-4739-9346-30bd6c7822b3)

**Comment by HbmMods** [comment]
Block #4 doesn't have a closing bracket at the end, so the entire JSON is invalid. Please use a JSON validator to make sure that the syntax is correct.

**Comment by TheChosenIndividual** [comment]
Thanks, will check

**Comment by TheChosenIndividual** [comment]
Fixed, still doesnt work

**Comment by HbmMods** [comment]
Did you check the JSON integrity with a validator? Does it work with the firebrick replaced by custom machine blocks? Does the machine's hologram even show up?

**Comment by OlorinIV** [comment]
[hbmCustomMachines.json](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/12863279/hbmCustomMachines.json)
Send your file.

**Comment by TheChosenIndividual** [comment]
> Did you check the JSON integrity with a validator? Does it work with the firebrick replaced by custom machine blocks? Does the machine's hologram even show up?

Machine controllers are invalidated, JSON validator gives the green light

**Comment by HbmMods** [comment]
> Machine controllers are invalidated

what does that mean? Does the hologram show up? Does it work if you just replace the firebrick registry names with CM blocks? What does your config file even look like?

**Comment by TheChosenIndividual** [comment]
> > Machine controllers are invalidated
> 
> what does that mean? Does the hologram show up? Does it work if you just replace the firebrick registry names with CM blocks? What does your config file even look like?

It does not, the controllers are all invalidated, holograms do not show up, yes, it does work if i replace the firebrick registry name

**Comment by HbmMods** [comment]
Had to use OCR to turn your screenshot into usable text (would it have killed you to just post the config file?), but the structure works just fine, with and without firebrick.
