### ISSUE TITLE
Schrabidium explosions break bedrock ores in the most bottom layer of the world.

### ISSUE THREAD

**Issue by TeslaP09** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1214]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.
![Screenshot (170)](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/131558426/2999c12c-b78b-4498-8acf-0fe194ff2004)

I don't know if this is intended behaviour or not, but the F.L.E.I.J.A. and The Protototype and only those bombs seem to be able to break bedrock ores at the bottom of the world. I know that those bombs simply delete all blocks in a certain radius, but the most bottom layer of bedrock never gets deleted (and that's a good thing), however the bedrock ores on the most bottom layer, so y=0 all get deleted from my testing, which results in holes in the world, allowing the player to easily fall into the void. And yes, I'm running the latest version if that's relevant (X4740). The log also doesn't show any errors at all.
Edit: This also happens when ONLY HBM NTM is installed.

**Comment by HbmMods** [comment]
Fixed in X4746.
