### ISSUE TITLE
(Bug)

### ISSUE THREAD

**Issue by CREEPERBOY585** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1217]
wires not rendering properly
![2023-10-10_13 37 55](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/104661463/6c130041-bc83-43d1-94c6-7707404c8ce0)

**Comment by funnyman8** [comment]
This is likely due to Optifine, which breaks loads of rendering stuff in mods, there's been many other compatibility issues with NTM's effects in the past, so this likely stems from that. Your best bet is to either drop the shaders, or roll with the visual glitches.

**Comment by kotmatross28729** [comment]
This is NOT an optifine error, this is a SHADER error, which is actually very easy to fix. It is enough to replace `tessellator.addVertex` with `tessellator.addVertexWithUV` in the `RenderPylonBase.java` , and add 0, 1 (UV) at the end. I will also say that this method can fix ALL rendering errors in this mod.
However, in some places you need to add a “dummy” texture (I just use a white background)
Here's how it works:

(original code)
![Снимок](https://github.com/kotmatross28729/Hbm-s-Nuclear-Tech-GIT-master-serious/assets/110309314/5839b27a-b086-4126-90a5-db7b9485a914)

=
![2023-10-11_13 19 10](https://github.com/kotmatross28729/Hbm-s-Nuclear-Tech-GIT-master-serious/assets/110309314/65257b48-44d6-4339-94ac-85e7ec21edd4)


---------------------
(modified code)
![1Снимок](https://github.com/kotmatross28729/Hbm-s-Nuclear-Tech-GIT-master-serious/assets/110309314/a6d6bfc9-c876-4308-92f6-e55911f0bfd5)


=
![2023-10-11_13 19 14](https://github.com/kotmatross28729/Hbm-s-Nuclear-Tech-GIT-master-serious/assets/110309314/a8b210ae-c4e9-4fb1-95a5-536ea180d3e0)

---------------------

**Comment by HbmMods** [comment]
Shaders have this habit of breaking any solid colored faces when `GL_TEXTURE_2D` is disabled. Using a dummy texture is not so much a fix as it is a workaround, since shaders aren't supposed to break solid colored faces to begin with. There's plenty of times where that approach is used in vanilla (ender dragon flares, hurt mobs, flashing TNT, etc), so really it's shaders that are supposed to fix the issue.
