### ISSUE TITLE
Custom machine anchor registers block placement wrongly

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1219]
Despite putting the anchor facing the machine´s interior it turned out backwards, Left is how i put the anchor when i took the measurements, right is how the system registered the block placement
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/120053489/8f1ce40a-f516-4fd5-a666-ea3fd89a2cd8)

**Comment by TheChosenIndividual** [comment]
Update: I managed to bypass it by putting the anchor on the other side, putting it with the inside facing south fixes it, so it looks like a directional dependent grid issue

**Comment by HbmMods** [comment]
Fixed in X4760.
