### ISSUE TITLE
Customized machine output items with NBT of probability

### ISSUE THREAD

**Issue by sdddddf80** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1220]
### Describe the bug

The probability of nbt is added to the ItemSack that needs to be output in this recipe when players check nei. That is to say, as long as players enter the game and use nei to query this recipe, this nbt exists in this recipe, and running this recipe later will produce items with nbt until the player exits the game.

![QQ图片20231013162033](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/53573250/6b3ead10-8413-4f89-b60b-044043b8319b)
![QQ图片20231013163727](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/53573250/d9dcac8c-5de5-4ded-8e2b-ff56306fea01)
This can cause great difficulties in stacking, sorting, and storing items.Perhaps it is possible to use the methods provided by Nei itself to display probabilities in text or to detect and delete corresponding NBT data when the machine outputs items?

**Comment by HbmMods** [comment]
Fixed in X4760.
