### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by CREEPERBOY585** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1223]
I will have more information but I'm on vacation right now

Mc heli crashes when I use it and I don't want to use 1.12.2

Thanks

**Comment by OlorinIV** [comment]
McHeli's stopped maintaining for years, could be anything else's problem. 
Find a programmer friend of yours and have a private discussion on your problem and stop bothering people with a issue that's likely not their business.
