### ISSUE TITLE
Desh pickaxe / basic reactor

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1225]
###infinite durability / basic reactor

I don't know if the pickaxe is meant to have so much durability.

the basic reactor has no recipe

**Comment by SoB1nary** [comment]
the desh pickaxe is supposed to have infinite durability because it only mines at the iron pickaxe level and is comparatively slow
wdym by the basic reactor

**Comment by HbmMods** [comment]
Desh pickaxes have infinite durability.

Several reactors have been phased out and only exist as decorative blocks. If you're in 528 mode, certain blocks may also not have recipes.

**Comment by ghost** [comment]
> Desh pickaxes have infinite durability.
> 
> Several reactors have been phased out and only exist as decorative blocks. If you're in 528 mode, certain blocks may also not have recipes.

how do you change the mode?
