### ISSUE TITLE
Crash with the containment box

### ISSUE THREAD

**Issue by MCNaOtlichnoYT** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1226]
**Version:** Latest
**Bug:** you can use number keys to transfer items from/into a slot where the cursor is located (minecraft feature). If you use this to put a containment box into itself, the game crashes.
**Steps to reproduce:**
1. Have a containment box  in slot 1
2. Open it
3. Point your mouse at one of the slots and press 1
4. Minecraft crashes

**Comment by HbmMods** [comment]
Fixed in X4760.
