### ISSUE TITLE
The cooling tower.

### ISSUE THREAD

**Issue by Maulment** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1232]
When i go to put the low-pressure-steam into the cooling tower or auxtilery tower, it just goes up to the max the tower can handle and produces smoke for a split second then stops. pelase help if i am doing something wrong please tell me!

**Comment by Voxelstice** [comment]
you have to put the output water from the cooling tower to somewhere else.

**Comment by TheChosenIndividual** [comment]
Additionally could be a over-saturated water loop or improper set-up

**Comment by Maulment** [comment]
> you have to put the output water from the cooling tower to somewhere else.

I did and it still does it

**Comment by Maulment** [comment]
> Additionally could be a over-saturated water loop or improper set-up

its not improper and i just put a water tank down

**Comment by TheChosenIndividual** [comment]
> > Additionally could be a over-saturated water loop or improper set-up
> 
> its not improper and i just put a water tank down

well, what size is the water tank? is your reactor or plant big or small? does the tank have an infinite water source inside of it? how many tanks are there?

**Comment by Maulment** [comment]
> > > Additionally could be a over-saturated water loop or improper set-up
> > 
> > 
> > its not improper and i just put a water tank down
> 
> well, what size is the water tank? is your reactor or plant big or small? does the tank have an infinite water source inside of it? how many tanks are there?

the water tank is the big ass water tank 9000, is in 3 rows and 3 in each row and yes, an infinite liquid tank is in the big ass tank 9000.

**Comment by Maulment** [comment]
Nevermind that rbmk was just broken so i turned it into a museum

**Comment by OlorinIV** [comment]
You're clogging your system with water from the infi fluid barrel. The steam cycle does not consume water yet you keep inputting more into it. And you're playing creative anyway so why not just shove your spent steam into another infi fluid barrel.
Shut down this issue before the author notices it and tags it 'skill issue', or expect to get mocked at.

**Comment by TheChosenIndividual** [comment]
> You're clogging your system with water from the infi fluid barrel. The steam cycle does not consume water yet you keep inputting more into it. And you're playing creative anyway so why not just shove your spent steam into another infi fluid barrel. Shut down this issue before the author notices it and tags it 'skill issue', or expect to get mocked at.

Jeez man calm down, if he needs help then he needs help no need to pressure others into not getting the help they need

**Comment by Maulment** [comment]
**i got it, it was too little towers for the steam and water to vent because i had 9 reactors and 2 cooling towers**
