### ISSUE TITLE
Realistic Collider

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1233]
If the particle colliders are ment to mirror the ones IRL to a degree, then pumping them with power is not really enough. The collider multiblock should require something (preferably a frigid liquid) to be pumped into it in order for the magnetic coils themself to achieve the superconductivity needed for an accelerator to operate.

##TLDR
the collider multiblock should require coolant in order to operate, like how a cyclotron requires an item that is a coolant source in order not to blow up. 

The comment below is just my ideas on how to go about this to make it realistic; please disregard unless interested

**Comment by Shibva** [comment]
- Quenching: quenching occurs when the magnet/coils fail to maintain their superconductivity as a result of becoming too warm. This is not seen as a bad thing unless, of course your collider is running. Failing to maintain cooling of all coils while operating will result in the collider receiving moderate damage at the failed area(s).

- Coolant: it should go without saying that only very cold liquids like cryogel are needed to prevent your collider from becoming a pile of scrap metal. Given that there's a variety; it could be made to where the type of coolant used that meets the temperature threshold could provide different levels of energy efficiency to offset the monstrous amount of power needed to run the collider. 

- Coils: The amount of X coolant needed per tick is directly proportional to the number of coils in the multi; higher-end coils consume more than lower-end ones will but consumes less than the amount needed for using lower end coils to reach the same level as a higher end one; this will encourage people to build higher tier coils to offset the amount of coolant need per tick of operation. Coils when they're not running, will consume a small amount passively unlike when they are running. The rate of consumption, regardless of coil, shifts depending on the status of each coils temperature; with coils becoming cooled would require more coolant at first, in order to get down to the subzero temperatures required, and not needing as much to maintain that temperature; so try to keep a constant supply provided to have minimal loss.
Mesa Coils will not require coolant due to the unique properties that it consist of when made makes it superconductive at room-temperature (can still receive coolant; with the coldest available, possibly reducing the total power cost needed for an operation by 50% but in exchange for requiring a massive amount of it per tick of operation). Distribution works similarly to powering a Collider using access ports to supply and remove coolant; the only notable difference is that the Maximum spacing between points is doubled the max distance between power inlets (I.e, the range of one coolent inlet and outlet is twice the range of a power port)

- Maintaining your Collider: as said above, coolant is required for a safe and operational Collier. Maintaining it is as it was before, but just with an additional factor to keep an eye on. In addition to ensuring that your collider is properly powered; you will now be required to both maintain and circulate coolant to ensure safe operation. Coolant, once used, will need to be circulated out to prevent the increase of temperature; when building is recommended to have both inlet and outlet linear to one another, as both will have the same range.

- Safeguard (extra): will not protect you or your collider from operating without coolant, but will prevent operation if the multi block does not consist of at least one coolant, inlet and outlet. The sole purpose, for this is the prevent pre-existing colliders it's such was implemented from running post update; more or less preventing existing colliders from blowing themselves up.

###what's the point?
This is to provide a more realistic collider by introducing a additional mechanic that is considered vital for any collider in real life to run and this expands on possibly how to approach such if I were to do it. Whether you choose to follow this path or make one of your own it's up to you.

**Comment by Vaern** [comment]
The issues tab is for issues, not suggestions. Please take this elsewhere

**Comment by HbmMods** [comment]
oh hell yeah, let's take this thing that most people struggle with already and make it even more obtuse, with enough variables we can finally make sure that *nobody* will ever use it again! wooooooo

**Comment by Shibva** [comment]
> The issues tab is for issues, not suggestions. Please take this elsewhere

Alr, feel free to pointe into the right direction; your call.


> oh hell yeah, let's take this thing that most people struggle with already and make it even more obtuse, with enough variables we can finally make sure that *nobody* will ever use it again! wooooooo


I'll be honest; I didn't really realize that a lot of people complain about it as is judging by the sound of things; I just really like thinking out side of the box when possible and ideas to possibly improve and expand upon a mod that is in my opinion one of my personal favorites of all time. With the aim of how things are going with, including somewhat realistic content (i.e. black long, asbestos, item, hazards, ETC.) I figure, I suggest, maybe adding coolant to keep the magnets cold to the collider to have it be realistic, other than the power demand. I will admit that I did go a bit overboard with my thinking on how this could work; I usually do when I like something.


Anyhow, feel free to close this comment if you wish; not really sure if and where I can post something like this properly, I'm still technically "shadow-banned" for whatever reason despite not being on the ban list from what I was told.

Anyhow, till next time when I find a bug.
