### ISSUE TITLE
HBM Crashing with Energy Control Mod

### ISSUE THREAD

**Issue by solundev** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1234]
The error seems to be caused when acessing class **TileEntityCoreTitanium** << not found

`---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 10/30/23 12:43 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: com/hbm/tileentity/machine/TileEntityCoreTitanium
	at com.zuxelus.energycontrol.crossmod.CrossHBM.getCardData(CrossHBM.java:1455)
	at com.zuxelus.energycontrol.items.kits.ItemKitHBM.getSensorCard(ItemKitHBM.java:28)
	at com.zuxelus.energycontrol.items.kits.ItemKitMain.getSensorCard(ItemKitMain.java:103)
	at com.zuxelus.energycontrol.items.kits.ItemKitMain.onItemUseFirst(ItemKitMain.java:120)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:360)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: com.hbm.tileentity.machine.TileEntityCoreTitanium
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 9707551600 bytes (9257 MB) / 13958643712 bytes (13312 MB) up to 13958643712 bytes (13312 MB)
	JVM Flags: 9 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xms13312m -Xmx13312m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1614} [Minecraft Forge] (modpack.jar) 
	UCHIJAAAAAAAAA	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJAAAAAAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAAAAAAA	securitycraft{v1.8.13} [SecurityCraft] ([1.7.10]+SecurityCraft+v1.8.13.jar) 
	UCHIJAAAAAAAAA	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCHIJAAAAAAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAAAAAAA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHIJAAAAAAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(29oct17).jar) 
	UCHIJAAAAAAAAA	PTRModelLib{1.0.0} [PTRModelLib] (DecoCraft-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	props{2.4.1} [Decocraft] (DecoCraft-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	doggystyle{1.1.3.99} [Doggy Style] (DoggyStyle-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7.jar) 
	UCHIJAAAAAAAAA	DynamicTransport{0.1.2.0} [Dynamic Transport] (Dynamic-Transport-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	EasyCrafting{1.7.10-2.0.1.16} [Easy Crafting] (Easy-Crafting-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	IC2{2.2.628-experimental} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.7.10.jar) 
	UCHIJAAAAAAAAA	energycontrol{1.7.10-0.3.4} [Energy Control] (EnergyControl-1.7.10-0.3.4.jar) 
	UCHIJAAAAAAAAA	flansmod{1.57} [Flan's Mod Ultimate] (Flans-Ultimate-Stability-Edition-Mod-Forge-1.7.10.jar) 
	UCHIJAAAAAAAAA	hbm{1.0.27 BETA (4746)} [Hbm's Nuclear Tech] (HBM-NTM-.1.0.27_X4746.jar) 
	UCHIJAAAAAAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAAAAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJAAAAAAAAA	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCHIJAAAAAAAAA	MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar) 
	UCHIJAAAAAAAAA	mcheli{1.0.3} [MC Helicopter] (mcheli) 
	UCHIJAAAAAAAAA	moreplayermodels{1.7.10b} [MorePlayerModels] (MorePlayerModels_1.7.10b.jar) 
	UCHIJAAAAAAAAA	cfm{3.4.7} [ 9MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	mw{0.4.2.4} [Modern Warfare Contagion] (mw_2.0-0.4.2.4+(Halloween+Update)_mc1.7.10.jar) 
	UCHIJAAAAAAAAA	RWG{Alpha 1.1} [Realistic World Gen Alpha] (Realistic-World-Gen-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJAAAAAAAAA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
	UCHIJAAAAAAAAA	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalDynamics: -[1.7.10]1.2.1-172
	Flan's Mod Content Packs: 
1-7-10-ww2-content-pack-improved-v2.jar (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\1-7-10-ww2-content-pack-improved-v2.jar)
British Military Pack V1.131.jar (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\British Military Pack V1.131.jar)
FC Pack V8.02 1.7.10-1.8 FM5.1.jar (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\FC Pack V8.02 1.7.10-1.8 FM5.1.jar)
Flag-Content-Pack-Forge-1.7.10.jar (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\Flag-Content-Pack-Forge-1.7.10.jar)
Flans-Modern-Weapons-Pack-1.7.10.jar (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\Flans-Modern-Weapons-Pack-1.7.10.jar)
Fleet Pack - unzip me (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\Fleet Pack - unzip me)
Germany-WW2-Content-Pack-Forge-1.7.10.jar (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\Germany-WW2-Content-Pack-Forge-1.7.10.jar)
Greylight_3.0.1-1.7.10.jar (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\Greylight_3.0.1-1.7.10.jar)
Hospital_Mod_Facilities_Pack_1.12.2.jar (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\Hospital_Mod_Facilities_Pack_1.12.2.jar)
ManusWW2Package-Content Pack V4.0-1.7.10-4.10.0.jar (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\ManusWW2Package-Content Pack V4.0-1.7.10-4.10.0.jar)
MilitaryUniform-1.0.0-1.19.4.jar (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\MilitaryUniform-1.0.0-1.19.4.jar)
Minecraft SMP Parts Package 4.0-Content Pack-1.7.10-4.10.0 (2).jar (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\Minecraft SMP Parts Package 4.0-Content Pack-1.7.10-4.10.0 (2).jar)
Modern Warfare-Content Pack-1.7.10-4.10.0.jar (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\Modern Warfare-Content Pack-1.7.10-4.10.0.jar)
Prototype Sci Fi V3 1.7.10-1.8 FM5.1.jar (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\Prototype Sci Fi V3 1.7.10-1.8 FM5.1.jar)
Simple Parts-Content Pack-1.7.10-4.10.0.jar (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\Simple Parts-Content Pack-1.7.10-4.10.0.jar)
TaskForce51s-Basic-Pack-4-Content-Pack-Forge-1.7.10.jar (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\TaskForce51s-Basic-Pack-4-Content-Pack-Forge-1.7.10.jar)
United-States-Marines-Modern-War-Pack-4-Content-Pack-Forge-1.7.10.jar (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\United-States-Marines-Modern-War-Pack-4-Content-Pack-Forge-1.7.10.jar)
Ye Olde-Content Pack-1.7.10-4.10.0.jar (filepath: C:\Users\mathe\AppData\Roaming\.technic\modpacks\hbms-nuclear-tech-hbmmods\Flan\Ye Olde-Content Pack-1.7.10-4.10.0.jar)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Stefzy'/1108, l='M ilitary Airfield', x=-726.69, y=14.00, z=-137.79]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 12
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 Compatibility Profile Context 23.9.2.230827
	OpenGlRenderer: AMD Radeon(TM) RX Vega 11 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8`

**Comment by HbmMods** [comment]
Seems to be a duplicate of #816. Originally I wanted to fork EC to submit a fix but I couldn't get the workspace to work. Someone reported that apparently it was fixed, so I stopped. Looks like it was never fixed after all.

**Comment by HbmMods** [comment]
Small update here, I got to talk to Zuxelus about the compat, there's a small bit of extra code I need to write so that EC can receive all the required info without becoming incompatible in the future, I'll probably get around doing that the coming week.

**Comment by HbmMods** [comment]
Was fixed by EC a few weeks ago, everything should be compatible as it used to be.

**Comment by JefferyKerman** [comment]
Where do I get the new version? The 1.7.10 version on curseforge hasn't updated on almost a year.
