### ISSUE TITLE
Problem with weapon textures when reloading

### ISSUE THREAD

**Issue by asddsa3211233** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1235]
With the latest updates, the textures of weapons disappear when fucking reloading, and not only the weapons from this mod, EVERYTHING I pick up is not displayed from the 3rd person

**Comment by HbmMods** [comment]
What's your modlist? Do you have any other keybinds that overlap with the reload key?

**Comment by asddsa3211233** [comment]
![Скриншот 31-10-2023 115033](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/116473920/2bebbd8e-0ca3-427c-a049-bb5f9ff5346c)
![Скриншот 31-10-2023 115113](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/116473920/ebfa4def-ef14-4dfa-9330-7d2b9e2d46e2)
![Скриншот 31-10-2023 115136](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/116473920/c4f7343b-d841-4e47-bdba-fdbb82a6a6f4)
![Скриншот 31-10-2023 115147](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/116473920/26246fb1-1a54-4f3d-91d0-7946d1ec6cd6)

**Comment by asddsa3211233** [comment]
the theme with the binding did not help

**Comment by HbmMods** [comment]
That's definitely a mod conflict because nobody else has this problem, and it works just fine with just NTM. I'd recommend taking out all performance and coremods out first. You're on your own for this one.
