### ISSUE TITLE
Particle Accelerator automation

### ISSUE THREAD

**Issue by MrKimkimora** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1236]
I have a question.
How can I automate **Particle Accelerator** if conveyor inserter/hopper/ME interface/ME output bus fills the first slot first. (For crafts with different ingridients it is OK, but for euphemium or antischrabidium it is not OK)
Shreder has a function of distributing items across different slots.

![Screenshot_20231030_194140](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/144221261/005d2a9a-6794-4986-afc3-01abb6453895)
![Screenshot_20231030_194259](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/144221261/afdee1ef-9216-4bc0-8bb2-7fb57e551382)

**Comment by TheChosenIndividual** [comment]
If im not wrong there´s a setting for this already? not sure, im not really a hadron collider geek, but i think there is a setting on the GUI for hopper slot locking

**Comment by MrKimkimora** [comment]
> If im not wrong there´s a setting for this already? not sure, im not really a hadron collider geek, but i think there is a setting on the GUI for hopper slot locking

Yes, there is a yellow button at right. But, it only sets a type of an item. So they still stacks to one slot.

**Comment by TheChosenIndividual** [comment]
¬(:/)¬ (that is supposed to be a shrug)

**Comment by MrKimkimora** [comment]
The BobCat heard me and added it, but... (new issue)
