### ISSUE TITLE
Explosive block defusal duping

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1239]
When defusing an explosive block with the high-tech bomb defuser, the item is dropped twice, essentially duping it, i have only encountered this bug with C-4 explosives (Explosive block tnt-like, NOT mining charge) but i suspect the other NTM explosives may also be guilty of this bug

thats all for now

thanks

-Chosen

**Comment by HbmMods** [comment]
That was fixed in X4760, what version are you on?

**Comment by TheChosenIndividual** [comment]
...somehow i get embarrased every time i find an issue and im like "OH BOY I GOT EM THIS TIME" and...bruh...
