### ISSUE TITLE
Particle accelerator automation (yeah, again)

### ISSUE THREAD

**Issue by MrKimkimora** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1241]
I'm grateful to be heard, but

**The BobCat** said: _Particle accelerators will now evenly distribute items using IO if both inputs are equal, making the antischrabidium recipe a lot easier to automate_ 

Maybe I am a bit stupid, but i tried hopper, conveyor inserter, ME output bus and ME interface. Tried with antimatter and antischrabidium. Tried point hopper (and others) directly to PA core and access terminal. It still stacks to the first slot.

Loaded the freshest version 4774 (with pigeon).
![Screenshot_20231106_010327](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/144221261/2c426b66-115f-4ce6-91ca-95a258a9f520)
![Screenshot_20231106_011248](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/144221261/05453ffa-87e6-4aeb-a653-6fad95ecc4f8)
![Screenshot_20231106_011306](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/144221261/76de846a-a279-4e25-89e7-fdadb61454eb)

**Comment by OlorinIV** [comment]
Apparently you have to fill the slots with two same items _beforehand_. Frankly, I don't think that the update has solved your problem of having one hadron run multiple recipes with ME buses. The best solution is to add another mode switching button that determines which filling method should be used.

**Comment by MrKimkimora** [comment]
> Apparently you have to fill the slots with two same items _beforehand_. Frankly, I don't think that the update has solved your problem of having one hadron run multiple recipes with ME buses. The best solution is to add another mode switching button that determines which filling method should be used.

Oh, yeah, I just tested this. 
Yes, it is not the best solution. But better, than it was before (now you do not need spend stack of capsules).

I think I will build one more accelerator.

**Comment by HbmMods** [comment]
Version X4775 has a new IO mode that limits the input to a single item per slot, essentially forcing the input to be split evenly.
