### ISSUE TITLE
More custom machine problems

### ISSUE THREAD

**Issue by MCNaOtlichnoYT** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1244]
Tried to make a machine called farm. It assembles and the recipes are shown in NEI. Hovewer I can't perform any of them.
[hbmCustomMachines.json](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/13299531/hbmCustomMachines.json)
[hbmCustomMachines_from_hbmconfig.json](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/13299536/hbmCustomMachines_from_hbmconfig.json)

**Comment by HbmMods** [comment]
The custom machines seem to use the wrong value for looking up recipes, the workaround for this is making sure that the unlocalized name of the machine and the recipe key are the same.
