### ISSUE TITLE
Add an ability to drink mercury.

### ISSUE THREAD

**Issue by yellowcake3d** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1245]
Dear HbmMods:

Thank you for having mercury as an actual item you can make in your modification. This item is amazing and has lots of uses, although I couldn't help but notice that you didn't add a very important thing: an ability for players to drink it. I think the fact that players can't do so is quite upsetting. In my opinion adding an ability for players to drink mercury would turn out greatly for this modification in the long run. Many parts of the mod lore would come together, and it would make mercury actually useful. I realize that mercury is used to make desh and many other useful parts, but most of it by far not as useful as an ability to drink it. I hope you will listen to this suggestion and actually implement this long-awaited feature to the mod.

Sincerely,
Mercury fan.

**Comment by JameH2** [comment]
bob doesnt know what the effects are, can you try drinking some and then get back to us with results?

**Comment by OlorinIV** [comment]
> bob doesnt know what the effects are, can you try drinking some and then get back to us with results?

Obviously he drank a lot of mercury already, with the symptoms showing up as well.

**Comment by username228a91** [comment]
according to anicent chinise medicine mercury makes you immortal or and increases your lifetime
