### ISSUE TITLE
Server lag after nuclear bomb explosion.

### ISSUE THREAD

**Issue by aloyen1** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1250]
I detonated a nuclear charge. But, after that, the server started lagging: from time to time its TPS drops to 8 (or somewhere around a second, the north does not reproduce the tick at all). And this even happens when the explosion area is not loaded. Enrages.

Here's the video: https://rezon.host/HBM_Bug.mp4
*Sorry for this ugly laggy video...*

Server specifications: 16 GB DDR4, SSD disk, 3.4GHz processor (6 threads).

And logs...
![изображение](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/98328698/3cde9152-7e03-4484-83c1-c1a718e2aed4)

**Comment by HbmMods** [comment]
Could you run a profiler? The log itself doesn't provide any details.

**Comment by aloyen1** [comment]
No problems
https://spark.lucko.me/ZJDloaw2P1

**Comment by HbmMods** [comment]
That's 1.12, please refer to #1039
