### ISSUE TITLE
Crash error code -1

### ISSUE THREAD

**Issue by Oakley0156** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1256]
The game crashed when trying to open search items, it has also crashed when flying in creative mode (no bug report). I believe the flying one is if you fly too fast it has trouble rendering (just a guess from experience, its happened twice). The one that links to the crash report below is from opening the inventory. May be another mod playing up, though if it is this mod then a fix would be appreciated! The mod is unplayable for me as of now.

Mods in use:
Mcheli (no longer in development)
HBM NTM (Exact version in report)
NEI
Aegis weapon system

Thanks,
Appreciate the hard work this mod is amazing! I would trade all my other mods to keep this one lol. Keep up the hard work!

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 26/11/23 20:04
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: 1
	at com.hbm.util.function.Function$FunctionLogarithmic.getDangerFromFuel(Function.java:54)
	at com.hbm.items.machine.ItemPWRFuel.func_77624_a(ItemPWRFuel.java:59)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.updateFilteredItems(GuiContainerCreative.java:378)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:350)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:550)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.hbm.util.function.Function$FunctionLogarithmic.getDangerFromFuel(Function.java:54)
	at com.hbm.items.machine.ItemPWRFuel.func_77624_a(ItemPWRFuel.java:59)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.updateFilteredItems(GuiContainerCreative.java:378)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:350)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:550)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['(MINECRAFT USERNAME WAS REMOVED FOT PRIVACY)'/271, l='MpServer', x=-608.05, y=5.62, z=27.27], MCH_ViewEntityDummy['McHeliDummyEntity'/40693, l='MpServer', x=0.00, y=-4.00, z=0.00]]
	Chunk stats: MultiplayerChunkCache: 975, 975
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-523,4,-29), Chunk: (at 5,0,3 in -33,-2; contains blocks -528,0,-32 to -513,255,-17), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 682 game time, 682 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 154 total; [EntitySlime['Slime'/56320, l='MpServer', x=-687.40, y=4.00, z=33.60], EntityCreeper['Creeper'/32775, l='MpServer', x=-574.50, y=4.00, z=-10.50], EntityCow['Cow'/10, l='MpServer', x=-688.78, y=4.00, z=-28.78], EntityClientPlayerMP['(USERNAME REMOVED)'/271, l='MpServer', x=-608.05, y=5.62, z=27.27], EntityHorse['Horse'/17, l='MpServer', x=-687.41, y=4.00, z=-33.41], EntitySheep['Sheep'/18, l='MpServer', x=-686.91, y=4.00, z=-37.22], EntitySheep['Sheep'/19, l='MpServer', x=-681.56, y=4.00, z=-33.16], EntitySheep['Sheep'/20, l='MpServer', x=-678.09, y=4.00, z=-45.09], EntitySlime['Slime'/21, l='MpServer', x=-669.75, y=4.00, z=-11.31], EntityHorse['Horse'/22, l='MpServer', x=-676.22, y=4.00, z=-31.56], EntityCow['Cow'/23, l='MpServer', x=-687.50, y=4.00, z=-31.50], EntityCow['Cow'/24, l='MpServer', x=-690.19, y=4.00, z=-21.16], EntitySlime['Slime'/25, l='MpServer', x=-687.89, y=4.61, z=24.71], EntityVillager['Villager'/26, l='MpServer', x=-673.50, y=5.00, z=96.50], EntityVillager['Villager'/27, l='MpServer', x=-668.03, y=5.00, z=80.44], EntityVillager['Villager'/28, l='MpServer', x=-667.88, y=5.00, z=81.50], EntityCreeper['Creeper'/20508, l='MpServer', x=-576.50, y=4.00, z=-13.50], EntityVillager['Villager'/29, l='MpServer', x=-664.47, y=4.00, z=85.06], EntityVillager['Villager'/30, l='MpServer', x=-661.22, y=5.00, z=87.22], EntityVillager['Villager'/31, l='MpServer', x=-665.50, y=5.00, z=96.50], EntityVillager['Villager'/32, l='MpServer', x=-661.88, y=4.00, z=109.34], EntityVillager['Villager'/41, l='MpServer', x=-662.22, y=4.00, z=78.41], EntityVillager['Villager'/42, l='MpServer', x=-650.38, y=4.00, z=84.78], EntityVillager['Villager'/43, l='MpServer', x=-660.22, y=5.00, z=86.72], EntityVillager['Villager'/44, l='MpServer', x=-647.50, y=5.00, z=85.50], EntityVillager['Villager'/45, l='MpServer', x=-647.50, y=5.00, z=86.50], EntityVillager['Villager'/46, l='MpServer', x=-650.63, y=4.00, z=88.34], EntityVillager['Villager'/49, l='MpServer', x=-658.66, y=5.81, z=107.59], EntityPig['Pig'/51, l='MpServer', x=-639.78, y=4.00, z=-50.78], EntityPig['Pig'/52, l='MpServer', x=-638.19, y=4.00, z=-49.19], EntityPig['Pig'/56, l='MpServer', x=-638.50, y=4.00, z=-47.50], EntityPig['Pig'/57, l='MpServer', x=-637.50, y=4.00, z=-45.50], EntityPig['Pig'/58, l='MpServer', x=-625.34, y=4.00, z=-46.81], EntitySheep['Sheep'/59, l='MpServer', x=-633.78, y=4.00, z=-41.78], EntitySheep['Sheep'/60, l='MpServer', x=-632.19, y=4.00, z=-40.19], EntitySheep['Sheep'/61, l='MpServer', x=-635.50, y=4.00, z=-39.50], EntitySheep['Sheep'/62, l='MpServer', x=-636.50, y=4.00, z=-41.50], EntityHorse['Donkey'/63, l='MpServer', x=-629.38, y=4.00, z=-46.38], EntityHorse['Donkey'/64, l='MpServer', x=-627.00, y=4.00, z=-42.09], EntityPig['Pig'/65, l='MpServer', x=-623.94, y=4.00, z=-11.63], EntityPig['Pig'/66, l='MpServer', x=-626.50, y=4.00, z=-6.50], EntitySlime['Slime'/26946, l='MpServer', x=-567.78, y=4.85, z=11.74], EntityPig['Pig'/67, l='MpServer', x=-626.25, y=4.00, z=-10.78], EntityPig['Pig'/68, l='MpServer', x=-627.50, y=4.00, z=-14.50], EntitySheep['Sheep'/69, l='MpServer', x=-624.50, y=4.00, z=-7.50], EntitySlime['Slime'/31045, l='MpServer', x=-668.24, y=4.00, z=-27.06], EntitySheep['Sheep'/70, l='MpServer', x=-624.66, y=4.00, z=-12.88], EntitySlime['Slime'/71, l='MpServer', x=-621.78, y=4.00, z=74.22], EntityChicken['Chicken'/72, l='MpServer', x=-625.50, y=4.00, z=107.50], EntitySheep['Sheep'/75, l='MpServer', x=-627.50, y=4.00, z=102.50], EntitySheep['Sheep'/76, l='MpServer', x=-630.50, y=4.00, z=104.50], EntityPig['Pig'/82, l='MpServer', x=-620.50, y=4.00, z=-45.78], EntityPig['Pig'/83, l='MpServer', x=-630.97, y=4.00, z=-50.13], EntityPig['Pig'/84, l='MpServer', x=-621.16, y=4.00, z=-44.53], EntityPig['Pig'/85, l='MpServer', x=-615.97, y=4.00, z=-3.06], EntityPig['Pig'/86, l='MpServer', x=-619.63, y=4.00, z=-4.22], EntitySheep['Sheep'/87, l='MpServer', x=-621.19, y=4.00, z=-3.91], EntitySheep['Sheep'/88, l='MpServer', x=-623.84, y=4.00, z=-8.59], EntityPig['Pig'/89, l='MpServer', x=-622.75, y=4.00, z=-11.84], EntityChicken['Chicken'/90, l='MpServer', x=-618.81, y=4.00, z=107.28], EntitySlime['Slime'/91, l='MpServer', x=-613.64, y=4.95, z=-52.41], EntityChicken['Chicken'/92, l='MpServer', x=-592.50, y=4.00, z=59.50], EntitySlime['Slime'/31838, l='MpServer', x=-552.23, y=4.85, z=105.11], EntitySkeleton['Skeleton'/95, l='MpServer', x=-576.50, y=4.00, z=-12.50], EntityZombie['Zombie'/96, l='MpServer', x=-577.50, y=4.00, z=-13.50], EntityCreeper['Creeper'/97, l='MpServer', x=-574.13, y=4.00, z=-14.73], EntityHorse['Horse'/98, l='MpServer', x=-578.09, y=4.00, z=61.34], EntityHorse['Horse'/99, l='MpServer', x=-577.34, y=4.00, z=65.18], EntityHorse['Horse'/100, l='MpServer', x=-580.87, y=4.00, z=56.13], EntityBat['Bat'/47716, l='MpServer', x=-575.75, y=4.64, z=-11.25], EntityHorse['Horse'/101, l='MpServer', x=-579.50, y=4.00, z=51.50], EntityPig['Pig'/102, l='MpServer', x=-581.22, y=4.00, z=59.78], EntityCow['Cow'/103, l='MpServer', x=-577.22, y=4.00, z=58.50], EntityCow['Cow'/104, l='MpServer', x=-578.81, y=4.00, z=58.50], EntityCow['Cow'/105, l='MpServer', x=-584.38, y=4.00, z=52.25], EntityCow['Cow'/106, l='MpServer', x=-582.16, y=4.00, z=56.50], EntityCow['Cow'/107, l='MpServer', x=-584.81, y=4.00, z=62.22], EntityCow['Cow'/108, l='MpServer', x=-587.66, y=4.00, z=61.06], EntityChicken['Chicken'/109, l='MpServer', x=-587.84, y=4.00, z=62.78], EntityChicken['Chicken'/110, l='MpServer', x=-593.41, y=4.00, z=60.53], EntityChicken['Chicken'/111, l='MpServer', x=-583.50, y=4.00, z=61.50], EntityCow['Cow'/112, l='MpServer', x=-588.47, y=4.00, z=66.09], EntityBat['Bat'/22128, l='MpServer', x=-572.25, y=6.90, z=-13.45], EntityCow['Cow'/113, l='MpServer', x=-582.78, y=4.00, z=71.81], EntityChicken['Chicken'/114, l='MpServer', x=-576.53, y=4.00, z=70.47], EntityChicken['Chicken'/115, l='MpServer', x=-579.22, y=4.00, z=65.44], EntityChicken['Chicken'/116, l='MpServer', x=-587.28, y=4.00, z=65.19], EntityCreeperPhosgene['Phosgene Creeper'/117, l='MpServer', x=-573.31, y=4.00, z=-15.55], EntityBat['Bat'/118, l='MpServer', x=-561.74, y=5.31, z=-32.32], EntitySpider['Spider'/119, l='MpServer', x=-567.14, y=4.00, z=-15.00], EntityGlyphid['Glyphid'/120, l='MpServer', x=-572.88, y=4.00, z=-13.21], EntitySkeleton['Skeleton'/121, l='MpServer', x=-575.69, y=4.00, z=-15.69], EntityCreeper['Creeper'/122, l='MpServer', x=-575.09, y=4.00, z=-5.75], EntityZombie['Zombie'/123, l='MpServer', x=-573.33, y=4.00, z=-11.79], EntityGlyphid['Glyphid'/125, l='MpServer', x=-570.85, y=4.00, z=-12.91], EntityBat['Bat'/126, l='MpServer', x=-574.25, y=6.10, z=-16.75], EntityGlyphid['Glyphid'/127, l='MpServer', x=-568.99, y=4.00, z=-14.16], EntitySlime['Slime'/18559, l='MpServer', x=-612.34, y=4.02, z=-33.09], EntityEnderman['Enderman'/128, l='MpServer', x=-573.32, y=4.00, z=-14.73], EntityBat['Bat'/129, l='MpServer', x=-562.82, y=7.55, z=0.40], EntityCreeper['Creeper'/130, l='MpServer', x=-569.43, y=4.00, z=-12.25], EntityZombie['Zombie'/131, l='MpServer', x=-575.22, y=4.00, z=-12.16], EntityCreeper['Creeper'/132, l='MpServer', x=-575.69, y=4.00, z=-11.31], EntityItem['item.item.rottenFlesh'/133, l='MpServer', x=-575.47, y=4.13, z=-0.44], EntityBat['Bat'/134, l='MpServer', x=-576.13, y=6.10, z=-12.75], EntitySlime['Slime'/135, l='MpServer', x=-570.34, y=4.00, z=0.03], EntitySlime['Slime'/136, l='MpServer', x=-573.06, y=4.14, z=13.71], EntityChicken['Chicken'/137, l='MpServer', x=-569.50, y=4.00, z=26.50], EntityChicken['Chicken'/138, l='MpServer', x=-569.50, y=4.00, z=25.50], EntityChicken['Chicken'/139, l='MpServer', x=-573.50, y=4.00, z=22.50], EntityCow['Cow'/140, l='MpServer', x=-568.16, y=4.00, z=25.75], EntityCow['Cow'/141, l='MpServer', x=-561.06, y=4.00, z=24.81], EntityCow['Cow'/142, l='MpServer', x=-570.03, y=4.00, z=28.53], EntityCow['Cow'/143, l='MpServer', x=-571.06, y=4.00, z=34.03], EntityCow['Cow'/144, l='MpServer', x=-571.50, y=4.00, z=40.50], EntityCow['Cow'/145, l='MpServer', x=-571.22, y=4.00, z=36.72], EntityCow['Cow'/146, l='MpServer', x=-562.25, y=4.00, z=34.25], EntityPig['Pig'/147, l='MpServer', x=-574.81, y=4.00, z=60.50], EntityPig['Pig'/149, l='MpServer', x=-544.22, y=4.00, z=-52.69], EntityPig['Pig'/152, l='MpServer', x=-551.25, y=4.00, z=-19.16], EntityPig['Pig'/153, l='MpServer', x=-553.50, y=4.00, z=-21.50], EntityChicken['Chicken'/154, l='MpServer', x=-553.47, y=4.00, z=-16.47], EntitySlime['Slime'/58778, l='MpServer', x=-534.60, y=4.00, z=63.40], EntityPig['Pig'/155, l='MpServer', x=-549.34, y=4.00, z=-11.78], EntityPig['Pig'/156, l='MpServer', x=-550.50, y=4.00, z=-15.50], EntityBat['Bat'/157, l='MpServer', x=-552.67, y=4.48, z=1.60], EntityChicken['Chicken'/158, l='MpServer', x=-549.28, y=4.00, z=-14.28], EntitySlime['Slime'/159, l='MpServer', x=-548.29, y=4.18, z=-4.73], EntityCow['Cow'/161, l='MpServer', x=-558.97, y=4.00, z=29.81], EntityChicken['Chicken'/170, l='MpServer', x=-543.69, y=4.00, z=-8.19], EntityChicken['Chicken'/171, l='MpServer', x=-543.50, y=4.00, z=-12.50], EntityChicken['Chicken'/172, l='MpServer', x=-536.63, y=4.00, z=-15.41], EntityChicken['Chicken'/173, l='MpServer', x=-541.56, y=4.00, z=-5.59], EntityChicken['Chicken'/174, l='MpServer', x=-547.47, y=4.00, z=-3.53], EntityChicken['Chicken'/175, l='MpServer', x=-539.50, y=4.00, z=-8.50], EntitySlime['Slime'/177, l='MpServer', x=-538.78, y=4.00, z=63.84], EntitySlime['Slime'/178, l='MpServer', x=-539.13, y=4.00, z=52.56], EntityChicken['Chicken'/179, l='MpServer', x=-531.50, y=4.00, z=76.50], EntityChicken['Chicken'/180, l='MpServer', x=-532.38, y=4.00, z=76.22], EntityChicken['Chicken'/181, l='MpServer', x=-535.56, y=4.00, z=80.38], EntitySlime['Slime'/29877, l='MpServer', x=-590.25, y=4.00, z=-43.53], EntityHorse['Horse'/182, l='MpServer', x=-529.50, y=4.00, z=77.13], EntityHorse['Horse'/183, l='MpServer', x=-527.63, y=4.00, z=83.97], EntityItem['item.item.rottenFlesh'/9655, l='MpServer', x=-556.69, y=4.13, z=1.13], EntitySlime['Slime'/31929, l='MpServer', x=-604.75, y=4.00, z=-41.96], EntitySheep['Sheep'/190, l='MpServer', x=-536.03, y=4.00, z=74.06], EntityItem['item.item.rottenFlesh'/5323, l='MpServer', x=-577.19, y=4.13, z=-19.25], EntitySlime['Slime'/41943, l='MpServer', x=-634.97, y=4.00, z=82.34], EntityBat['Bat'/3293, l='MpServer', x=-569.64, y=5.20, z=3.44], EntityBat['Bat'/3296, l='MpServer', x=-577.75, y=4.00, z=-13.25], EntityBat['Bat'/3297, l='MpServer', x=-561.64, y=5.80, z=0.47], EntityBat['Bat'/3298, l='MpServer', x=-574.25, y=5.60, z=-10.25], MCH_ViewEntityDummy['McHeliDummyEntity'/40693, l='MpServer', x=0.00, y=-4.00, z=0.00], EntityItem['item.item.rottenFlesh'/14590, l='MpServer', x=-580.34, y=4.13, z=-13.28]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 505636456 bytes (482 MB) / 1577058304 bytes (1504 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	AegisSystemMod{1.5.7a} [Aegis System Mod] (ASM-[1.7.10]-1.5.7a-single-obfuscated.jar) 
	UCHIJAAAA	D3Core{1.1.2.41} [D3Core] (D3Core-1.7.10-1.1.2.41.jar) 
	UCHIJAAAA	AutoCrafter2000{1.1.0.33} [AutoCrafter2000] (AutoCrafter2000-1.7.10-1.1.0.33.jar) 
	UCHIJAAAA	hbm{1.0.27 BETA (4795)} [Hbm's Nuclear Tech] (HBM-NTM-.1.0.27_X4795.jar) 
	UCHIJAAAA	mcheli{1.0.3} [MC Helicopter] (mcheli) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 546.17' Renderer: 'NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 546.17, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by JameH2** [comment]
Yeahhhh… so about that.

redownload the release

**Comment by HbmMods** [comment]
The release got hotfixed just  a few minutes ago, just redownload the file.

**Comment by Oakley0156** [comment]
Thanks, appreciate the quick response!

(Sorry if that seemed extremely sarcastic I didn't mean it like that)
