### ISSUE TITLE
The game crashes when you press the "search" button in creative mode.

### ISSUE THREAD

**Issue by NEKO-001** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1257]
The entire description of the issue is in the title, the crash report is attached.

[crash-2023-11-26_20.16.39-client.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/13467969/crash-2023-11-26_20.16.39-client.txt)

**Comment by Vaern** [comment]
Redownload the latest release, it's fixed now.
