### ISSUE TITLE
[suggestion] World of Tanks thingies

### ISSUE THREAD

**Issue by YuRaihn** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1259]
I suggest to make something like Mirny-13 event reimagination at Minecraft. I mean, adding thematic thingies, mobs, boss and maybe even a driveable tank.

Quick info: according to lore, there is an abandoned town where the anomaly matter rose from dead and made a lot of tankz who decided to destroy the humanity, so this is why the town is abandoned.

Thingies to make:

Mirium - the radioactive fluid-like matter. Can be met as fluid. Can be collected into the bucket (from where it can leak because of open top), canister (can leak too), cell, fluid tank, fluid barrel, block barrels (can leak from every), antimatter barrel, machine orbus and Magnus
Magnus - specialized Mirium collector working with magnetic technology like antimatter barrel. Kinda big. Maybe a multi-block.
Corrupted (by Mirium) evil mobs - common zombie/skeleton/creeper with a bit modernized texture who made a digamma-radiation when hit player.
Lost FBI agent - corrupted by Mirium FBI agent who will never accomplish his mission.
Hunter - BIG mob who will chase the player until either player or hunter is destroyed.
Rabbit - BIG corrupted by Mirium mob who will run from player everytime he tries to come close.
Hedgehog - BIG mob who will explode player.
Immortal - boss mob, a tank. It is unable to destroy when digamma-radiation level is low. Never ever try to come close.
Grenadier - driveable mob-tank, can be used to destroy Immortal if player has no more powerful weapon.
Mosquito - a KV-2 turret which can be used as... Turret.
The town - meteor dungeon-like generated town made from khrushchevkas, warehouses and at least one Magnus.

~ ~ ~

The link to watch the Immortal's model - https://tanks.gg/v12210/tank/the-immortal/model

(thou also can find there models of other tanks, use the tag "event vehicle" at the version 1.22.1)

~ ~ ~

If thou art interestedm I can try to help in it.

~ ~ ~

![изображение_2023-11-27_200339104](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/142492519/9de13ea5-a098-40a5-acc1-4c567ffd1cfb)

**Comment by JameH2** [comment]
This is ntm sir

Also what do you exactly mean by help

**Comment by YuRaihn** [comment]
I do not know, actually, I cannot even create models or code... But who knows, maybe there is anything I can do.

At least think that I am fine builder XD

**Comment by YuRaihn** [comment]
By the way now I began to try to build the Magnus.

Yup, the Magnus is actually big.

![2023-11-27_21 56 13](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/142492519/4aabea82-f935-4ba8-9ed1-c996b3021f42)

**Comment by YuRaihn** [comment]
Also I think that I overestimated it's sizes as actual one looks much smaller LMAO

![изображение_2023-11-27_221439095](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/142492519/6f1e2bf1-69e5-42f7-9bdf-63a003c15179)
