### ISSUE TITLE
[suggestion/enhancement] Rapid RBMK commissioning

### ISSUE THREAD

**Issue by R-Kaenbyou** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1262]
In all game modes, commissioning the control rods and steam channels is a very tedious part to construct RBMK reactor, especially large RBMK reactors which used lots of steam channels and control rods. 
To reduce the time consumed in construction, could you add tools or functions which used for commissioning multiple control rods or steam channels at once into the game?

**Comment by OlorinIV** [comment]
I guess you mean 'Redprint' from Thermal Series. 
But rather than an item, it could be a function embedded in RBMK console, and players could sit behind a screen and set, copy/paste instead of having to check out everywhere.

**Comment by R-Kaenbyou** [comment]
> I guess you mean 'Redprint' from Thermal Series. But rather than an item, it could be a function embedded in RBMK console, and players could sit behind a screen and set, copy/paste instead of having to check out everywhere.

I didn't play the Thermal Series, so I'm not sure about the function of "Redprint".

**Comment by R-Kaenbyou** [comment]
> In all game modes, commissioning the control rods and steam channels is a very tedious part to construct RBMK reactor, especially large RBMK reactors which used lots of steam channels and control rods. To reduce the time consumed in construction, could you add tools or functions which used for commissioning multiple control rods or steam channels at once into the game?

Besides, commissioning the RBMK fluid heaters can also be tedious if much of them were used. If possible, please add tools or functions used for commissioning multiple fluid heaters.
