### ISSUE TITLE
[suggestion/enhancement] MIRV Warheads + Missiles similar to the 1.12 version of the Mod, but added to the 1.7 version , Along with adding vehicles like Tanks or Operable Planes

### ISSUE THREAD

**Issue by KorKorSolos** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1263]
It would be really cool if you could add the MIRV Warheads, as seen in the 1.12 version (Or if they already are present, im just unaware, i would like to know how to construct one). Carrying on, the addition of battle tanks such as the M1 Abram, or the Leopard, along with the addition of stealth bombers, or other similar models of planes would be a lovely addition! You could use the aircrafts or bombers to drop armed tactical nuclear missiles, instead of placing them where you wish to detonate them you can drop them, you could use the Tanks and vehicles similar such as the HIMARS to shoot

**Comment by username228a91** [comment]
suggestions are banned

**Comment by KorKorSolos** [comment]
oh,.

**Comment by HbmMods** [comment]
do these people not know what flan's mod is
