### ISSUE TITLE
(mod conflict) Extreme lag when using WAILA(What am I looking at) mod and opening some containers.

### ISSUE THREAD

**Issue by Howdidibreakit** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1264]
### Describe the bug
So, when opening a steel crate, spend fuel rod drum, any barrel, and probably a bunch of other things, while using the WAILA mod, and having your screen focused on the storage device, the game lags to oblivion. I'm talking going from 60 fps to 2. I know I've made this issue before but this one is kinda different because now I know what the problem is.

**Comment by OlorinIV** [comment]
Never encountered such issue. Try using GTNH's new version of WAILA.
https://github.com/GTNewHorizons/waila/releases/download/1.6.5/Waila-1.6.5.jar

**Comment by HbmMods** [comment]
None of these GUIs do anything special compared to any other GUI, even if that were the issue (which I doubt), there wouldn't be a whole lot I can do about it.

**Comment by Howdidibreakit** [comment]
Actually, they do have some pretty big differences behind the scenes. In update MEMEPACK-9 (which i'm like 90% sure has kept the changes it made) You reworked how some crates work. You see, iron crates recycle some code from the blast furnace to exist, but the steel crate uses a dedicated storage... thing to work. For whatever reason, WAILA gets mad at the dedicated storage thing and confuses the computer. Now, if you know about your code, you know the blast furnace's code is recycled for a slew of things. All those other things, WAILA doesn't like for some other reason, possibly because it's trying to display fluid ID or something like that. I don't know, it's weird, label it as a silly little quirk of this thing, and close it oh my god I'm so tired of WAILA.

**Comment by HbmMods** [comment]
> Actually, they do have some pretty big differences behind the scenes.

There are no functional differences except for the storage capacity and the GUI texture.

> You see, iron crates recycle some code from the blast furnace to exist

The GUI has some boilerplate copied from the blast furnace which is the same for almost all containers, including the steel crate. The only thing that's different is the name of one variable, but structurally the GUI classes are absolutely identical.

> possibly because it's trying to display fluid ID or something like that

It dos no such thing, in fact most of the base code is shared between all crates.

In addition, plenty of people use WAILA and nobody has issues like that, so I doubt it's caused by the crates.

**Comment by Howdidibreakit** [comment]
This is the weirdest bug ive ever had to deal with (can you close the other issue like this one because that issue is dead)

**Comment by BallOfEnergy1** [comment]
Can confirm, I've never seen an issue like this in my own gameplay, despite using WALIA and NTM very frequently.
