### ISSUE TITLE
Custom Bobmazon

### ISSUE THREAD

**Issue by TheVitya2127** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1271]
I have a question. Is it possible to change the Bobmazon catalog for my products? This would be useful for servers where the main currency is caps.

This will also make bobmazon more valuable than before.

**Comment by HbmMods** [comment]
There are no configs for Bobmazon offers, nor are they planned.

**Comment by TheVitya2127** [comment]
It's a shame, it would have made the bobmazon a more unique item.
