### ISSUE TITLE
screen error like only colors on screen 

### ISSUE THREAD

**Issue by nightmare2862** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1272]
this bug is not from the launcher but everytime i open the world thats only just green and when i move my arrow up its goes blue like the world color form a unknown block idk if my verson is not up to date i tried everything to fix but it will not fix the problem please look into this incase if its a bug (using the supported verson of this mod)

**Comment by nightmare2862** [comment]
proof of bug link down below

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/153718696/385ff3b4-ba97-4136-9039-85db63c7a82e

**Comment by HbmMods** [comment]
Please refer to #985
