### ISSUE TITLE
pollution detector ui not working

### ISSUE THREAD

**Issue by nightmare2862** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1274]
pollution detector its ui is bugged everytime i am in a radioactive area like nuked area it don't change its numbers like fallout still remains 0.0 i hope u are aware of this kind regards nightmare_2862

**Comment by nightmare2862** [comment]
i mean like the detector does not wan to calculate

**Comment by HbmMods** [comment]
Fallout pollution has currently no sources, if you want to detect radiation, use a geiger counter.
