### ISSUE TITLE
Suggestion (Suit Recharge Device)

### ISSUE THREAD

**Issue by nightmare2862** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1275]
Hello again i am here to suggest a idea for the power suits maybe u could add i device where u can carry a recharging device which can be recharged by storage blocks this is suggestion or enchantment if u like to call it that way.

**Comment by HbmMods** [comment]
Suit batteries and fusion cores already exist

**Comment by nightmare2862** [comment]
well the infinite fusion core does not do anything
