### ISSUE TITLE
Heavy infinite water tank not working

### ISSUE THREAD

**Issue by Oakley0156** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1283]
Could just be me but when I put the infinite heavy water tank into a fluid container (such as a tank), it won't fill up. I have double checked the fluid identifier and all.
![2023-12-23](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/93942410/db64ae04-1f3f-4ee4-abfc-d14dfd487133)

**Comment by Oakley0156** [comment]
I forgot to say, I'm using the latest version of NTM

**Comment by Oakley0156** [comment]
Works with regular water fluid identifier, I'll reopen if the problem persists.

**Comment by Voxelstice** [comment]
the infinite water tank items are specifically for water, nothing else. not even heavy water

**Comment by Oakley0156** [comment]
Sorry to waste your time. Keep up the good work!
