### ISSUE TITLE
Watz Plant Mud Spike on Init

### ISSUE THREAD

**Issue by OlorinIV** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1286]
### Describe the bug

This makes extreme builds like 12 Pure Schrab +12 Boron dangerous.  Idk if this was some feature, or the watz has failed to find its tanks in time _again_. However active Watz Plants are stable during exit/load, and do not appear to be buggy when they shut down and re-activate. The bug seems to be more common if an item I/O(in my case, conveyor ejector) is applied to the reactor.

**Comment by HbmMods** [comment]
The watz pellets have the unique property of becoming less reactive with higher temperature, which means they will run at full steam the first ticks until the reactor has gotten hot. It's therefore not recommended to use too many high mud pellets like pure schrabidium.
