### ISSUE TITLE
Screen glitch

### ISSUE THREAD

**Issue by peio2** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1287]
why when i put the hbm mod and i open minecraft with the mod this happens to the game
is this like a glitch on my computer or its the game, i don't understand, if anyone can help me to fix this i will be apreciated.
https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/85181756/895ad01a-c3e4-42ff-96b7-e124dbb784fd

**Comment by HbmMods** [comment]
Check #985
