### ISSUE TITLE
Block of slag appearing as gravel when created by artillery shell

### ISSUE THREAD

**Issue by dishonest-truth** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1298]
### Block of slag has the gravel texture apparently.

Below are 2 images displaying the bug, and also my mod list. I'm currently using the high explosive artillery shell. Anyways, the block of slag created by the explosion from the artillery has the texture of gravel.
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/143570676/d5562be2-2777-460c-bbd7-74865385fe23)
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/143570676/7e2c9200-12dc-4a8f-91c0-42c8af792cb4)
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/143570676/639b602f-67d9-4461-9492-7b55e6379452)

**Comment by gmhs022** [comment]
This is intentional afaik, it's meant to resemble broken slag rather than a big thing of casted slag.

**Comment by HbmMods** [comment]
Artillery as well as volatile creepers create slag with metadata 1 which was intentionally made to look more gravel-esque, while still yielding slag which can be recycled.
