### ISSUE TITLE
Glyphid Spawner OOB Excepttion causes a crash 

### ISSUE THREAD

**Issue by Joey-Destroyah** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1301]
### Describe the bug
When I attempt to load up a world, new or previously created, it crashes with an OOB Exception
Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.

To reproduce it, simply load up a world on 4845 NTM and you'll get booted with an OOB exception

HBM4845

log

[crash-2024-01-16_12.29.38-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/13953896/crash-2024-01-16_12.29.38-server.txt)

**Comment by HbmMods** [comment]
Did you change your config file or did you previously use 70k's fork? If so then you probably have to delete the config, since the glyphid spawn parameters now need 3 numbers instead of the initial 2.

**Comment by Joey-Destroyah** [comment]
Did what you said and I'm fine now
