### ISSUE TITLE
Game Crash when Initializing

### ISSUE THREAD

**Issue by Antineutrino-4444** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1305]
The game crashed right after phase 1 of initializing mod.

I made a brand-new install with nothing more, but HBM and it still happened. Game version is X4851 (newest version). OS is Windows 11.

Log and Crash Report attached. Thanks :>
[latest.log](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/14002779/latest.log)
[crash-2024-01-21_15.47.28-client.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/14002780/crash-2024-01-21_15.47.28-client.txt)

**Comment by HbmMods** [comment]
That was a bug with the initial file, download the release again to get the fixed version.

**Comment by Antineutrino-4444** [comment]
Fixed. Thanks!
