### ISSUE TITLE
Server is closing when players join w/ HBM 

### ISSUE THREAD

**Issue by Tyt0u** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1311]
Hi

Mods used: 
![Screenshot_20240123-145213](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/157497147/624e6f62-a7af-4ff4-adf7-0da1ddea4894)
+ Last HBM version

(Downgrading HBM does not work either)

We have an issue when joining our Minecraft server with HBM mod.
The server is closing up each Time we try to connect 
Hère is the crash report : 
https://pastebin.com/LQwE9LAv

Even when we try to launch the Map in solo, the game crashes with thé error code : -1
The 2 pictures attached shows what happens when trying to open the Map in solo mode.
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/157497147/d3be3951-20b3-4714-9148-a4669ab1fc7b)
![image-1](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/157497147/0cc653de-fd89-44b9-bd9e-452ba727f10f)

We sure know that the problem Comes from a generation issue, we did not succed to use Minecraft region fixer either...

The Map only opens in solo when not using the HBM mod but we don't want to lose all our progress so far.

Have you any Idea of how Can we recover our Map ?

**Comment by HbmMods** [comment]
The crash report indicates world corruption, if you don't have a backup (which you should always have) you can try loading the world in McEdit and delete the offending chunk. The error in the second screenshot just shows items being removed due to downgrading to an older version, that's normal when doing that.

**Comment by Tyt0u** [comment]
Using McEdit worked out, we had a plains chunk who popped out in our desert biome ! thanks
