### ISSUE TITLE
Mod doesn't load worlds

### ISSUE THREAD

**Issue by Glebertyt** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1317]
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/145223133/2906a778-476e-4007-a2ae-79e217dbf99d)
 this happens every time I try to enter any world of mine, I tried do it with other mods, and with HBM only.

**Comment by HbmMods** [comment]
If you have an Intel GPU, you might wanna check out #985

Otherwise, the log file would be good to have.
