### ISSUE TITLE
EMP missle

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1321]
### EMP storage block

when energy storage block gets hit by an storng EMP missle it will haven the energy that the storage block can hold but if you break it it does not hold it nbt so it wont be halved I dont know if this is intensiual.

HBM-NTM-.1.0.27_X4859.jar

**Comment by HbmMods** [comment]
Could you please rephrase that because I'm not sure what you mean

**Comment by ghost** [comment]
> Could you please rephrase that because I'm not sure what you mean

im mean if i blow a energy block with an EMP missle it wil "sweat?" but if you break the block it will reset it I dont know if intensiual.

**Comment by HbmMods** [comment]
For performance reasons, machines are only scanned once, and breaking them removes them from the list of affected machines. Things that are placed after the EMP effect begins is not affected at all.
