### ISSUE TITLE
Steam Connector on RBMK (Not the RealSim one)

### ISSUE THREAD

**Issue by B4ssB0mb3r** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1330]
So, I made a test RBMK to check if it runs or not on 1.7.10 with the latest mod version, and the steam connectors seem not to work. When I connect it directly trough the top to the turbine it works. What can be the issue? (Got a screenshot in case needed)
![RBMK doesn't work](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/159541260/d0c04990-321f-42cb-9279-061ae9f26e60)

**Comment by SoB1nary** [comment]
you're not supposed to have more than 1 block of space between the connector and the boiler

**Comment by B4ssB0mb3r** [comment]
> you're not supposed to have more than 1 block of space between the connector and the boiler

Giant thanks to you dude! I already tried everything I could, thanks!
