### ISSUE TITLE
Petition to add Tungsten Carbide and Tungsten carbide tools.

### ISSUE THREAD

**Issue by Tech-Support22** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1336]
Petition to add tungsten carbide. it could be used in machines or tools. maybe comparable to diamonds and have some special properties.
Just a suggestion. :3

**Comment by Vaern** [comment]
we already have tungsten carbide

**Comment by Tech-Support22** [comment]
oh, i'll try looking for it in the mod. But I can't seem to find anything about it on the internet.

**Comment by Ashen-sysadmin** [comment]
It's called neutron reflector ingame, look at the recipe.

**Comment by Tech-Support22** [comment]
I was talking about tools made using tungsten carbide like swords, pickaxes, and axes.

**Comment by HbmMods** [comment]
Why would we need that
