### ISSUE TITLE
When u going to add New radioactive gem production? 

### ISSUE THREAD

**Issue by nightmare2862** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1354]
Question When are u going to add a new way to make radioactive gem ore?
because the only way u can make radioactive gem ore is by the rad volcano lava when dry's off after use
(note this is a question not a bug report)

**Comment by gmhs022** [comment]
Yea, this is how volcanic gems are obtained too, I don't see a real reason to change it, atm the only issue is that radioactive gems aren't really useful, but the process of getting them is fine, it matches the non-rad equivalent.

**Comment by nightmare2862** [comment]
ok thanks for tell me i will close this question as answered and declined suggestion
:)
