### ISSUE TITLE
野火过于强大

### ISSUE THREAD

**Issue by OnDreamQwQ** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1355]
HBM X4880 
野火一直烧个不停

未人身攻击，不要没事找事

**Comment by OlorinIV** [comment]
永燃就是野火的特性，不喜欢的话自己fork然后做改版啊，代码都是开源的

this guy asks if balefire blocks could be made not everlasting.

翻译英文这么难吗？这才几年级水平

**Comment by Antineutrino-4444** [comment]
野火烧不尽，春风吹又生
既然MC都是春天，野火烧不尽也很合理不是么
Translation: Wildfire can't be eliminated, but it grows again in the spring.
Since it's spring in MC, it makes sense that wildfire can't be eliminated, right?

**Comment by Antineutrino-4444** [comment]
Also close the issue pls :>

**Comment by OnDreamQwQ** [comment]
h，乐子（

**Comment by xiongboj** [comment]
说得对 附图:

**Comment by xiongboj** [comment]
你说的对，图：
野火烧不尽，春风吹又生 真·野火

**Comment by OnDreamQwQ** [comment]
@Antineutrino-4444 
说得对 ，我当时也这么评论的

**Comment by OnDreamQwQ** [comment]
@OlorinIV 未人身攻击，不要没事找事 未人身攻击，不要没事找事 未人身攻击，不要没事找事未人身攻击，不要没事找事 未人身攻击，不要没事找事   懒得翻，我才初一（

**Comment by OnDreamQwQ** [comment]
@OlorinIV 我不实名上网行了吧

**Comment by OnDreamQwQ** [comment]
@OlorinIV 难泵

**Comment by OnDreamQwQ** [comment]
> 永燃就是野火的特性，不喜欢的话自己fork然后做改版啊，代码都是开源的
> 
> 这家伙问，Balefire方块是否可以成为永恒的。
> 
> 翻译英文这么难吗？这才几年级水平

h

**Comment by Antineutrino-4444** [comment]
> @OlorinIV 未人身攻击，不要没事找事 未人身攻击，不要没事找事 未人身攻击，不要没事找事未人身攻击，不要没事找事 未人身攻击，不要没事找事 懒得翻，我才初一（

这还是你的问题啊，还在这说屁呢😂
