### ISSUE TITLE
item.antiknock.antiknock.name

### ISSUE THREAD

**Issue by coolestkid91021** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1362]
Umm the TEL item used for leaded gasoline making broke and turned into this.
![Screenshot 2024-02-26 144750](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/140053519/f3ec0ece-5892-4e15-bb78-bb7db1202472)

MC Version: 1.7.10
Hbm's NTM Version: 1.0.27_X4880
Has Optifine: Yes

**Comment by gmhs022** [comment]
Pretty sure this is fixed in dev now

**Comment by HbmMods** [comment]
It is, still leaving this open until the release.
