### ISSUE TITLE
Missiles dont chunkloads

### ISSUE THREAD

**Issue by ELJOKER900** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1368]
Hello , i was testing with anti-ballistic missile and i found missiles dont chunkloads (with an custom missile)
Im in the last version , the 1.0.27 (4880) , got screenshot
![Captura de pantalla 2024-03-03 142446](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/121907632/6a62061a-e861-43a2-83e7-e3ea1e21810a)

And other glitch is when an air raid siren is running , you unload that chunk and load that chunk , the siren still sounds enabled or disabled.

**Comment by HbmMods** [comment]
What's your modlist? Optifine is known for breaking chunkloading in most things, including missiles.

**Comment by ELJOKER900** [comment]
Sorry , i didnt saw your message , i have OptiFine installed but anyways there the modlist 
![Captura de pantalla 2024-03-06 173953](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/121907632/58851381-e998-4986-acfe-39283cd0d210)
