### ISSUE TITLE
Leviathan Turbine Animation Error

### ISSUE THREAD

**Issue by nightmare2862** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1370]
i recently find out that 3 of my RBMK reactor turbines have a animation error my reactor is stable but three of my turbines seems to have no running animation the one on the left as shown in the video is running but the other 3 isn't let me know if this is a real bug and if it can be fixed or not then maybe next update u will fix

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/153718696/77f946f6-4633-479a-9ac9-3d03ae4e9c2f

**Comment by HbmMods** [comment]
I can't tell from the video, what steam type are the leviathans set to? And did you make sure that the pipes are configured correctly?

**Comment by nightmare2862** [comment]
yep the pipes are set correctly and the first turbine is on ultra dense steam 2nd is super dense third dense and last steam

**Comment by nightmare2862** [comment]
just to confirm if my pipes were not correct then my reactor would have a explosion and would not report this but let me know if you can find this as bug after this message

**Comment by nightmare2862** [comment]
wait nvm i fixed it
