### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Riccardus** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1371]
I think that fluid valves to restrict flow direction and amount like the Red Copper Diode does would be very handy and one the same note an over/underflow valve would be a big improvement imo.

Also a recipe for Glowstone/Glowstone Dust would be cool.

**Comment by HbmMods** [comment]
Flow restriction valves are already planned, although only after the fluid system is fixed (who knows when that's gonna happen), and overflow valves are already possible by checking a tank's fill level with a comparator and using that to toggle redstone valves.

**Comment by Riccardus** [comment]
Ok thanks, I wasnt aware of the redstone valve thingy.
I take from this that a glowstone recipe wont be added?

**Comment by OlorinIV** [comment]
glowstone is reproducible as a hell bedrock ore

**Comment by Riccardus** [comment]
> glowstone is reproducible as a hell bedrock ore

How? I haven't found anything
