### ISSUE TITLE
It crashes when I use newer versions. 

### ISSUE THREAD

**Issue by Biskupsky** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1372]
X4837 is the newest version I can use for update of older version. When I use newer versions X4845, X4858, X4859 it crashes. Never mind if its few years old world, some newer ones or completly new one. It looks like that:

java.lang.NullPointerException: Exception in server tick loop
	at drzhark.customspawner.CustomSpawner.RemoveCustomSpawn(CustomSpawner.java:523)
	at drzhark.customspawner.environment.EnvironmentSettings.populateSpawns(EnvironmentSettings.java:847)
	at drzhark.customspawner.environment.EnvironmentSettings.updateSettings(EnvironmentSettings.java:260)
	at drzhark.customspawner.utils.CMSUtils.addWorldEnvironment(CMSUtils.java:128)
	at drzhark.customspawner.EventHooks.structureMapGen(EventHooks.java:196)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_113_EventHooks_structureMapGen_InitMapGenEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.terraingen.TerrainGen.getModdedMapGen(TerrainGen.java:29)
	at rtg.world.gen.ChunkProviderRTG.<init>(ChunkProviderRTG.java:156)
	at rtg.world.WorldTypeRTG.getChunkGenerator(WorldTypeRTG.java:66)
	at net.minecraft.world.WorldProvider.func_76555_c(WorldProvider.java:66)
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:654)
	at net.minecraft.world.World.<init>(World.java:245)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

I find it sad, becuase I cannot get to big radar and other features versions :v

**Comment by Ashen-sysadmin** [comment]
That is just the stacktrace, do you have a full crashlog?

**Comment by HbmMods** [comment]
The crash seems entirely unrelated to NTM, some mob spawner code from`drzhark` causes the issue.

**Comment by Biskupsky** [comment]
Honestly i used previous version of hbm and it works
Any new or old world does not work with newer ones

wt., 5 mar 2024, 08:01 użytkownik HbmMods ***@***.***>
napisał:

**Comment by Ashen-sysadmin** [comment]
> The crash seems entirely unrelated to NTM, some mob spawner code from`drzhark` causes the issue.

Its the mo-creatures mod, a mod that is legendary for causing random crashes and breaking things.

**Comment by Biskupsky** [comment]
> That is just the stacktrace, do you have a full crashlog?

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 04.03.24 23:25
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at drzhark.customspawner.CustomSpawner.RemoveCustomSpawn(CustomSpawner.java:523)
	at drzhark.customspawner.environment.EnvironmentSettings.populateSpawns(EnvironmentSettings.java:847)
	at drzhark.customspawner.environment.EnvironmentSettings.updateSettings(EnvironmentSettings.java:260)
	at drzhark.customspawner.utils.CMSUtils.addWorldEnvironment(CMSUtils.java:128)
	at drzhark.customspawner.EventHooks.structureMapGen(EventHooks.java:196)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_113_EventHooks_structureMapGen_InitMapGenEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.terraingen.TerrainGen.getModdedMapGen(TerrainGen.java:29)
	at net.minecraft.world.gen.ChunkProviderGenerate.<init>(ChunkProviderGenerate.java:66)
	at net.minecraft.world.WorldType.getChunkGenerator(WorldType.java:149)
	at net.minecraft.world.WorldProvider.func_76555_c(WorldProvider.java:66)
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:654)
	at net.minecraft.world.World.<init>(World.java:245)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 11380522208 bytes (10853 MB) / 19142803456 bytes (18256 MB) up to 38654705664 bytes (36864 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx36G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 109 mods loaded, 109 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJAA	voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
	UCHIJAA	FoamFixCore{1.0.0-beta1} [FoamFixCore] (minecraft.jar) 
	UCHIJAA	sapmanpack{2.4.1} [SanAndreasPs Manager Pack CORE edition] (SAPManPack-1.7.10-2.4.1.jar) 
	UCHIJAA	securitycraft{v1.8.13} [SecurityCraft] ([1.7.10]+SecurityCraft+v1.8.13.jar) 
	UCHIJAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
	UCHIJAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAA	deconstruction{2.2.5} [The Deconstruction Mod] ([MC1.7.10]deconstruction[v2.2.5].jar) 
	UCHIJAA	BuildCraft|Core{7.1.10} [BuildCraft] (buildcraft-7.1.10.jar) 
	UCHIJAA	BuildCraft|Transport{7.1.10} [BC Transport] (buildcraft-7.1.10.jar) 
	UCHIJAA	BuildCraft|Silicon{7.1.10} [BC Silicon] (buildcraft-7.1.10.jar) 
	UCHIJAA	BuildCraft|Factory{7.1.10} [BC Factory] (buildcraft-7.1.10.jar) 
	UCHIJAA	additionalpipes{4.7.7} [Additional Pipes] (Additional-Pipes-Mod-1.7.10.jar) 
	UCHIJAA	ambientsounds{0.1} [Ambient Sounds] (AmbientSounds Alpha v0.1 mc1.7.10.zip) 
	UCHIJAA	AncientWarfare{2.4.114-beta-MC1.7.10} [Ancient Warfare Core] (Ancient-Warfare-Mod-1.7.10.jar) 
	UCHIJAA	AncientWarfareAutomation{2.4.114-beta-MC1.7.10} [Ancient Warfare Automation] (Ancient-Warfare-Mod-1.7.10.jar) 
	UCHIJAA	AncientWarfareNEIPlugin{2.4.114-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (Ancient-Warfare-Mod-1.7.10.jar) 
	UCHIJAA	AncientWarfareNpc{2.4.114-beta-MC1.7.10} [Ancient Warfare NPCs] (Ancient-Warfare-Mod-1.7.10.jar) 
	UCHIJAA	AncientWarfareStructure{2.4.114-beta-MC1.7.10} [Ancient Warfare Structures] (Ancient-Warfare-Mod-1.7.10.jar) 
	UCHIJAA	Backpack{2.0.0} [Backpack] (backpack-2.0.0-1.7.x.jar) 
	UCHIJAA	badmobs{1.0.1} [Bad Mobs] (BadMobs-1.0.1-1.7.10.jar) 
	UCHIJAA	weaponmod{v1.14.3} [Balkon's WeaponMod] (Balkons-Weapon-Mod-1.7.10.jar) 
	UCHIJAA	BetterFoliage{2.0.17} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.17.jar) 
	UCHIJAA	BiblioCraft{1.11.2} [BiblioCraft] (BiblioCraft[v1.11.2][MC1.7.10].jar) 
	UCHIJAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) 
	UCHIJAA	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (bibliowoods-biomes-oplenty-edition-mod-1.7.10.jar) 
	UCHIJAA	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods-Natura-Edition-Mod-1.7.10.jar) 
	UCHIJAA	BrickaBrac{1.7.10-1.1.0b} [Brick-a-Brac] (Brick-a-Brac-Mod-1.7.10.jar) 
	UCHIJAA	PreciousBricks{1.7.10-1.0.0b} [Precious Bricks] (Brick-a-Brac-Mod-1.7.10.jar) 
	UCHIJAA	BuildCraft|Builders{7.1.10} [BC Builders] (buildcraft-7.1.10.jar) 
	UCHIJAA	BuildCraft|Energy{7.1.10} [BC Energy] (buildcraft-7.1.10.jar) 
	UCHIJAA	BuildCraft|Robotics{7.1.10} [BC Robotics] (buildcraft-7.1.10.jar) 
	UCHIJAA	cabinetsreloaded{3.0.14} [Cabinets Reloaded] (Cabinets-Reloaded-Mod-1.7.10.jar) 
	UCHIJAA	ctbupdater{1.0} [Call to Battle Updater] (ctbupdater-1.7.10-1.0.0.jar) 
	UCHIJAA	ctb{6.2} [Call To Battle] (Call to Battle 2.jar) 
	UCHIJAA	Chimneys{1.7.2} [Chimneys] (Chimneys-Mod-1.7.10.jar) 
	UCHIJAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.1d.jar) 
	UCHIJAA	claysoldiers{2.0.0-beta.2} [Clay Soldiers Mod] (ClaySoldiersMod-1.7.10-2.0.0-beta.2.jar) 
	UCHIJAA	climatecontrol{0.8.1} [Climate Control] (ClimateControl-0.8.2.jar) 
	UCHIJAA	craftguide{1.6.9.0} [CraftGuide] (CraftGuide-1.6.9.0-forge.jar) 
	UCHIJAA	CraftHeraldry{1.1.3} [CraftHeraldry] (CraftHeraldry-Mod-1.7.10.jar) 
	UCHIJAA	craftingpillars{1.6.0} [Crafting Pillars Mod] (CraftingPillars-1.7.x-1.6.1.jar) 
	UCHIJAA	customskymod{1.0} [Custom Sky Mod] (Custom Sky-Mod-Forge-1.7.10.jar) 
	UCHIJAA	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) 
	UCHIJAA	customnpcs{1.8.5} [CustomNPC+] (CustomNPC-Plus-1.8.5.jar) 
	UCHIJAA	doorsoplenty{0.1} [Doors O' Plenty] (Doors-O-Plenty-Mod-1.7.10.jar) 
	UCHIJAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAA	thebombzenapi{2.4.1} [ThebombzenAPI] (Thebombzen-API-1.7.10.jar) 
	UCHIJAA	enchantview{4.0.4} [EnchantView] (EnchantView-v4.0.4-mc1.7.10.jar) 
	UCHIJAA	erde{1.0c} [Entity Render Extender] (EntityRenderDistanceExtender-1.0c.jar) 
	UCHIJAA	flansmod{1.56} [Flan's Mod Ultimate] (Flan's+Mod+Ultimate+Stability+Edition-1.56.jar) 
	UCHIJAA	flycommand{2.1} [FlyCommandMod] (FlyCommandMod-1.7.10-2.1.jar) 
	UCHIJAA	foamfix{@VERSION@} [FoamFix] (FoamFix-1.7.10-universal-1.0.0-beta1.jar) 
	UCHIJAA	GardenContainers{1.7.10-1.7.0} [Garden Containers] (Garden-Stuff-Mod-1.7.10.jar) 
	UCHIJAA	GardenCore{1.7.10-1.7.0} [Garden Core] (Garden-Stuff-Mod-1.7.10.jar) 
	UCHIJAA	GardenStuff{1.7.10-1.7.0} [Garden Stuff] (Garden-Stuff-Mod-1.7.10.jar) 
	UCHIJAA	GardenTrees{1.7.10-1.7.0} [Garden Trees] (Garden-Stuff-Mod-1.7.10.jar) 
	UCHIJAA	GenCreator{1.0} [GenCreator] (GenCreator 1.1.jar) 
	UCHIJAA	GollumCoreLib{2.0.0} [Gollum Core Lib] (Gollum-Core-Lib-1.7.10.jar) 
	UCHIJAA	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (Grim3212-Core-1.7.10.jar) 
	UCHIJAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (HarvestCraft-Mod-1.7.10.jar) 
	UCHIJAA	hbm{1.0.27 BETA (4880)} [Hbm's Nuclear Tech] (HBM-NTM-.1.0.27_X4880.jar) 
	UCHIJAA	voltzengine{1.9.14.302} [Voltz Engine] (VoltzEngine-1.7.10-1.9.14b302.jar) 
	UCHIJAA	icbmclassic{2.16.2.205} [ICBM-Classic] (ICBM-classic-1.7.10-2.16.2b205.jar) 
	UCHIJAA	iChunUtil{4.1.3} [iChunUtil] (iChunUtil-4.1.3.jar) 
	UCHIJAA	IC2{2.2.727-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.727-experimental.jar) 
	UCHIJAA	inventorytweaks{1.57-116} [Inventory Tweaks] (InventoryTweaks-1.57-116.jar) 
	UCHIJAA	JammyFurniture{5.0.0 [Build Smeagol]} [Jammy Furniture Mod] (Jammy-Furniture-Reborn-Mod-1.7.10.jar) 
	UCHIJAA	MapWriter{2.1.2} [MapWriter] (MapWriter-1.7.10-2.1.2.jar) 
	UCHIJAA	mcheli{1.0.5} [MC Helicopter] (mcheli) 
	UCHIJAA	MedicineCraft{V4.0} [MedicineCraft] (MedicineCraft V4.2.jar) 
	UCHIJAA	MetallurgyCore{4.0.3} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.3.11.jar) 
	UCHIJAA	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAA	Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281(2).jar) 
	UCHIJAA	MekanismGenerators{9.1.0} [MekanismGenerators] (MekanismGenerators-1.7.10-9.1.0.281(1).jar) 
	UCHIJAA	MekanismTools{9.1.0} [MekanismTools] (MekanismTools-1.7.10-9.1.0.281(1).jar) 
	UCHIJAA	Metallurgy{4.0.3} [Metallurgy 4] (Metallurgy-1.7.10-4.0.3.36.jar) 
	UCHIJAA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (Mine-Blade-Battlegear-2-Mod-1.7.10.jar) 
	UCHIJAA	mobinhibitor{1.7.10-1.1} [Mob Inhibitor] (mobinhibitor-1.7.10-1.1.jar) 
	UCHIJAA	morematerials{0.9.20150214.0} [More Materials] (More-materials-mod-by-localtoast-1.7.10.jar) 
	UCHIJAA	nmsot{1.2.0-mc1.7.10} [No Mob Spawning on Trees] (No-Mob-Spawning-on-Trees-Mod-1.7.10.jar) 
	UCHIJAA	plasmacraft{0.3.5-beta2} [PlasmaCraft] (PlasmaCraft-Mod-1.7.10.jar) 
	UCHIJAA	QuarryPlus{2.1.0} [QuarryPlus] (QuarryPlus-Mod-1.7.10.jar) 
	UCHIJAA	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHIJAA	RTG{1.7.10-1.1.1.7} [Realistic Terrain Generation] (RTG-1.7.10-1.1.1.7.jar) 
	UCHIJAA	ShowDurability2{1.3.0} [ShowDurability2] (Show-Durability-2-Mod-1.7.10.jar) 
	UCHIJAA	SirenMod{2.2.01} [TheRealMcrafter's Siren Mod (Version 3.0.0)] (Siren-Mod-1.7.10.jar) 
	UCHIJAA	SmartRender{2.1} [Smart Render] (Smart-Render-Mod-1.7.10 (1).jar) 
	UCHIJAA	timehud{7.1.0} [Time HUD] (TimeHUD-Forge-1.7.10-7.1.0.jar) 
	UCHIJAA	tlhpoeCore{1.7} [TLHPoE Core] (tlhpoecore-1.7-1.7.10.jar) 
	UCHIJAA	TooMuchTNT{2.9} [TooMuchTNT] (Too-Much-TNT-Mod-1.7.10.jar) 
	UCHIJAA	tc{4.4.1_020-CE_6.0} [Traincraft - Community Edition] (Traincraft-4.4.1_020-CE_6 (1).jar) 
	UCHIJAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAA	universalcoins{1.7.10-1.5.8} [Universal Coins] (UniversalCoins-1.7.10-1.5.8.jar) 
	UCHIJAA	yumalib{0.0.0} [YumaLib] (UpToDateMod-mc1.7.10-2.4.1.jar) 
	UCHIJAA	uptodate{2.4.1} [UpToDateMod] (UpToDateMod-mc1.7.10-2.4.1.jar) 
	UCHIJAA	voltzenginemodcompat{1.9.14.302} [Voltz Engine Mod Compatibility Loader] (VoltzEngine-1.7.10-1.9.14b302.jar) 
	UCHIJAA	voltzenginemodflag{1.9.14.302} [VoltzEngine mod protection, flag, and region system] (VoltzEngine-1.7.10-1.9.14b302.jar) 
	UCHIJAA	Your Records Mod{Alpha} [§aYour Records Mod] (Your-Records-Mod-1.7.10.jar) 
	UCHIJAA	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAA	redgear_core{2.2.2} [Red Gear Core] (RedGearCore-1.7.10-2.2.2.jar) 
	UCHIJAA	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Mantle Environment: Environment healthy.
	Flan's Mod Content Packs: 
DAK-by-Plume.jar (filepath: C:\Users\Kacper\AppData\Roaming\.minecraft\Flan\DAK-by-Plume.jar)
flansmod-1.40.jar (filepath: C:\Users\Kacper\AppData\Roaming\.minecraft\Flan\flansmod-1.40.jar)
HAG-fixed.jar (filepath: C:\Users\Kacper\AppData\Roaming\.minecraft\Flan\HAG-fixed.jar)
Last+Winter+-+Modern+Warfare+Pack+v1.4.jar (filepath: C:\Users\Kacper\AppData\Roaming\.minecraft\Flan\Last+Winter+-+Modern+Warfare+Pack+v1.4.jar)
Machetemen Arms Pack Japanese Update (Pt 1).jar (filepath: C:\Users\Kacper\AppData\Roaming\.minecraft\Flan\Machetemen Arms Pack Japanese Update (Pt 1).jar)
Modern Warfare-Content Pack-1.7.10-4.10.0.jar (filepath: C:\Users\Kacper\AppData\Roaming\.minecraft\Flan\Modern Warfare-Content Pack-1.7.10-4.10.0.jar)
TF51 Basic Pack (filepath: C:\Users\Kacper\AppData\Roaming\.minecraft\Flan\TF51 Basic Pack)
USAF Modern War Pack (filepath: C:\Users\Kacper\AppData\Roaming\.minecraft\Flan\USAF Modern War Pack)
Warfare-44-Content-Pack-1.7.10.jar (filepath: C:\Users\Kacper\AppData\Roaming\.minecraft\Flan\Warfare-44-Content-Pack-1.7.10.jar)
WH_pack_0_1.zip (filepath: C:\Users\Kacper\AppData\Roaming\.minecraft\Flan\WH_pack_0_1.zip)
WW2-Content Pack-1.7.10-4.10.0.jar (filepath: C:\Users\Kacper\AppData\Roaming\.minecraft\Flan\WW2-Content Pack-1.7.10-4.10.0.jar)
[1.7.10] Flan's-Mod-Armours-fix-for-Custom-NPCs.jar (filepath: C:\Users\Kacper\AppData\Roaming\.minecraft\Flan\[1.7.10] Flan's-Mod-Armours-fix-for-Custom-NPCs.jar)
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'


This is full report

**Comment by Biskupsky** [comment]
As I mentioned, every version newer than this from 07.01.24 does crash the game. Thats strange as hell why is this somehow connected

**Comment by HbmMods** [comment]
The game runs fine with Mo'Creatures installed, I can't reproduce the crash.

**Comment by Biskupsky** [comment]
Hm I dont know what to do then

śr., 6 mar 2024, 11:12 użytkownik HbmMods ***@***.***>
napisał:

**Comment by HbmMods** [comment]
My next best guess from reading the spawner code would be that Mo'Creatures might have an issue with the crater biomes (in combination with some other mod), you could try disabling the crater biomes in the config (`17.B_toggle`).

**Comment by Biskupsky** [comment]
> My next best guess from reading the spawner code would be that Mo'Creatures might have an issue with the crater biomes (in combination with some other mod), you could try disabling the crater biomes in the config (`17.B_toggle`).

Oki, gonna try

**Comment by Biskupsky** [comment]
That worked ! Thanks <3
