### ISSUE TITLE
Fog Problems

### ISSUE THREAD

**Issue by VeiTheOne** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1374]
A world that got Tom'ed, and as soon as I entered a outer crater biome, the fog stayed. Nothing else to it.

![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/82922007/d6b3eab4-c595-497b-99c9-09800f625701)

**Comment by HbmMods** [comment]
Does it still happen with the new version? There was a fix for the fog issues PR'd recently but I don't remember if that came with the last release or the one before that.
