### ISSUE TITLE
4837 version. Radar does shows player from full range (1000m), but it doesnt give redstone signal. If player is still in the air and other player place redstone ones again it gives signal, but it never stops, even when player is not detected by radar. So there is a problem with redstone signal

### ISSUE THREAD

**Issue by Biskupsky** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1375]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.

**Comment by HbmMods** [comment]
Does the same problem happen when the radar detects missiles, or does it only happen for players?

**Comment by Biskupsky** [comment]
Didnt test yet, but solved by using comparator as output
Problem is that when other player is away from radar it doesnt show other
players on radar so also doesnt send redstone signal. That means radar are
not chunk loaders like missiles ? Is it any way to make radar detect
players from full range even when nobody next to radar ?

wt., 5 mar 2024, 19:14 użytkownik HbmMods ***@***.***>
napisał:

**Comment by HbmMods** [comment]
Machines don't load their own chunks, you will need a chunkloader mod for that.

**Comment by fbfnysnshnsgnwg** [comment]
stale?
