### ISSUE TITLE
can't place lights under stairs

### ISSUE THREAD

**Issue by coolestkid91021** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1380]
When I was renovating a factory, i can't place lights under stairs.

MC Version: 1.7.10
Hbm's NTM Version: 1.0.27_X4895

**Comment by HbmMods** [comment]
Which lights are you using? Cage lamps, fluorescent lights and arc lamps seem to attach to the underside of stairs (vanilla and modded) just fine.
