### ISSUE TITLE
Mod Feature Requests/Changes

### ISSUE THREAD

**Issue by PeanuteBJellytime** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1383]
Make it so placing dirt/sand/stone blocks above oil deposit blocks slowly turns them into their oily variant
Add chemplate recipes for making oily scrap from crude oil + dirt/sand/stone

Change the recipes for the reformer and hydrotreater instead of having 4 technetium/cadmium to being 4 bismuth instead since the convert requires it anyway so nobody can accidentally make it not knowing it requires the converter only to find out it requires bismuth.(Yes I know it has a tooltip I still didn't see it and the mistake can still happen)

PLEASE either reduce it from 256 to 64 oily scrap for a arsenic nugget or make it so 256 oily scrap gives one arsenic ingot as getting 2,304 oily scrap on a legit overworld survival world is actually a lot crazy and a very hard ask to do.

**Comment by Creeper-banner** [comment]
Bob is not open to suggestions, and you actually can do most of what you said BY YOURSELF by editing config file.

**Comment by HbmMods** [comment]
Adding chemplant recipes would defeat the point of the oily scrap process, destroying the landscape with a fracking tower was the intention.

Reducing the amount of scrap needed for arsenic is planned, along with a few recipe changes regarding how arsenic is processed/used.

**Comment by PeanuteBJellytime** [comment]
Man well that's lame what if I don't want to destroy my landscape I like how my overworld surface looks like with my buildings and have been playing the mod keeping pollution low and in control without destroying my surface so it's near impossible to get arsenic or progress to bismuth

**Comment by Vaern** [comment]
Try making high-performance solvent in an RBMK using the irradiation channel. Tungsten, gold, and neodymium bedrock ores can actually output bismuth byproduct if you do the highest level (x64) of processing using it. It's actually quite a bit, too, so once you get the high-perf all you need for bismuth is the mining drill with its drillbit, some excess niter, a centrifuge, and an ore acidizer. You can find the right bedrock ore by making a survey scanner - deposits always spawn around the center of chunks. Hope this helps!

**Comment by PeanuteBJellytime** [comment]
Holy shit! Yeah that does actually help thank you I didn't know I can irradiate my way to HPS that what I was originally trying to do is get bismuth through tungsten bedrock ore byproducts needing reformate for the HPS
