### ISSUE TITLE
Nuke Transmutation Enhancements

### ISSUE THREAD

**Issue by OlorinIV** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1386]
![2024-03-17_10 28 25](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/104282311/aacdb537-4ff2-49bb-a48f-190b8dc9c6b1)
1) current conversion is outer 1/2 instead of inner 1/2
2) uranium ore that isn't within conversion area gets destroyed instead of turning into sellafite variants
3) weird rule in deciding whether a block that is caught in an mk5 explosion should be turned into sellafite, i.e. iron blocks do not change at all, but cmb tiles change despite that they are resistant enough to survive the blast

**Comment by gmhs022** [comment]
These seem more like issues with using such a high yield, I haven't encountered the first two when using smaller yields, like the little boy and custom nukes and such.
