### ISSUE TITLE
Wood-burning generator does not output energy to cables and does not accept fluids from its fluid port

### ISSUE THREAD

**Issue by Majora320** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1389]
Tested on the latest commit. Fluid ducts and copper cables appear to connect to the ports on the machine, but they don't actually transmit any power/fluid.

**Comment by Majora320** [comment]
Also, the generator model emits smoke even when the output energy buffer is full and it isn't burning anything

**Comment by HbmMods** [comment]
Fixed in X4914.
