### ISSUE TITLE
Enhancement: High-quality ice cream production

### ISSUE THREAD

**Issue by R-Kaenbyou** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1390]
Dear HbmMods:
According to the following information:

1.Vanilla Minecraft allows players to acquire some materials which can be used in ice cream production (milk, eggs, sugar, ect).
2.HBM allows players to acquire fluid which have extremely low temperature (liquid oxygen, liquid hydrogen, ect).
3.HBM allows players to access high-performance centrifuges which is strong enough to separate U235F6 and U238F6.
4.In reality, fluid which have extremely low temperature (liquid nitrogen, ect) can be used in high-quality ice cream production.
5.In reality, centrifuges are necessary for cream production, and cream is necessary for ice cream production.

Thus, the players of HBM may have enough materials and devices to produce ice cream in game. If high-quality ice creams were added into the game, it would increase the amount of foods available for players, and also give extra usages to gas centrifuge, which lacks on usage.

**Comment by HbmMods** [comment]
![grafik](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/16674258/9f79f671-d249-4468-8285-29d654348d71)

**Comment by SoB1nary** [comment]
I support this suggestion.

**Comment by gmhs022** [comment]
Sounds more fitting for JameH's fork, he already has a milk separator.

**Comment by Kal19801** [comment]
![v2-624ee973d13378c5c17d9b27c2cbebd5_720w](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/158162434/a2f7b680-bfea-4374-af3f-f3430457d9f5)
