### ISSUE TITLE
Rare Earth Chunk bedrock ore is unminable

### ISSUE THREAD

**Issue by diminanoga** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1394]
The rare earth chunk bedrock ore is unminable via large mining drill.
Version X4895

The ore says it's tier 2 and requires 500mb Hydrogen Peroxide. When the drill starts "mining" it, it says it needs Sulfuric Acid.
I've tested this on a creative world, it doesn't work with any other drillbits, and the infinite barrel doesn't insert any fluids into the drill.

**Comment by HbmMods** [comment]
Did you set the bore fluid in the large mining drill to peroxide?

**Comment by diminanoga** [comment]
No, my bad
