### ISSUE TITLE
Can not play HBM in 1.7.10

### ISSUE THREAD

**Issue by badname64** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1398]
every time i load a world it loads for a second but everything is invisible if i try an older one on curseforge it works the screen looks like its 1 pixel and its  color changing depending on where i am and where i look but i can still hear

**Comment by Creeper-banner** [comment]
> every time i load a world it loads for a second but everything is invisible if i try an older one on curseforge it works the screen looks like its 1 pixel and its color changing depending on where i am and where i look but i can still hear

Try to install mod Neodymium or CoreTweaks, both of which can be found in Github.

**Comment by HbmMods** [comment]
Please refer to #985
