### ISSUE TITLE
world gen issues

### ISSUE THREAD

**Issue by THEkindKnight** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1403]
### world gen issues :( (its doing things in multiple chunks at once)
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/156622350/5a7342fc-d4a4-41bd-9e40-8bc80bd4de63)

**Comment by Vaern** [comment]
wrong version

**Comment by imholger420** [comment]
> wrong version

as in this will happen for the newest 1.12.2 version? because im using the newest version of 1.12.2 and im getting the same issue

**Comment by Vaern** [comment]
This repository is for 1.7.10 only. Check #1039
