### ISSUE TITLE
applied energistics compatibility with fluids

### ISSUE THREAD

**Issue by ecstxasy** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1404]
please i beg of you just make the fluids compatible with ae2 they dont need to be forge fluids i just want it to work so i can auto craft. you dont understand modded minecraft is unplayable without automation

**Comment by HbmMods** [comment]
You can already automate every single application of fluids in recipes or otherwise using the fantastic technology called "fluid duct", you might want to try it some time.
