### ISSUE TITLE
Bale fire server crash.

### ISSUE THREAD

**Issue by nightmare2862** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1405]
Hello I was cleaning up the bale fire that i put a bomb on accident but when using the foam fire extinguisher randomly the game jsut had it plsu bale fire for some reason once its put on some block and stays there forever untill someone extinguish it please let me know if this is not enough info or a bug 
 (crash code -1) ![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/153718696/a7e7163f-2e91-45b0-9b77-d772ac0a7fd7)

**Comment by HbmMods** [comment]
Could you please provide the crash report

**Comment by nightmare2862** [comment]
Sadly i didnt view it after senting u this error code but i will try my best to see if this happens again oh and btw i found out that after taking out the balefire with the foam extinguisher the lighting render stays there after putting it out

**Comment by nightmare2862** [comment]
i will try my best to see if this happens again i will put crash report

**Comment by nightmare2862** [comment]
Im Testing the server now and heres some more proof but i will try to see if this server will crash and if so i will provide crash report 

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/153718696/16b1e95f-89b7-4414-9220-7221c8257c29

**Comment by nightmare2862** [comment]
good news is that the server didnt crash when testing it but bad news is the lighting render is still like the image above so i will test it one more time if u dont see crash report the next day i will close this issue as cant be fixed

**Comment by mindbound** [comment]
The crash report is saved in a file, you can simply upload it here.

https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report

**Comment by nightmare2862** [comment]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 3/29/24 6:47 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at com.hbm.render.tileentity.RenderDoorGeneric.func_147500_a(RenderDoorGeneric.java:50)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.hbm.render.tileentity.RenderDoorGeneric.func_147500_a(RenderDoorGeneric.java:50)

-- Block Entity Details --
Details:
	Name: tileentity_ntm_door // com.hbm.tileentity.TileEntityDoorGeneric
	Block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (61,46,-54), Chunk: (at 13,2,10 in 3,-4; contains blocks 48,0,-64 to 63,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['nightmare_2862'/94, l='MpServer', x=-88.57, y=49.09, z=-260.43]]
	Chunk stats: MultiplayerChunkCache: 610, 610
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (160,64,244), Chunk: (at 0,4,4 in 10,15; contains blocks 160,0,240 to 175,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1763988 game time, 74691 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 206 total; [EntityZombie['Zombie'/5412434, l='MpServer', x=-152.50, y=19.00, z=-284.50], EntityZombie['Zombie'/4923977, l='MpServer', x=-31.53, y=-5776.60, z=-51.04], EntityZombie['Zombie'/5312599, l='MpServer', x=-33.03, y=-37.09, z=40.40], EntitySkeleton['Skeleton'/4734543, l='MpServer', x=30.71, y=-5972.75, z=-33.38], EntityZombie['Zombie'/5401691, l='MpServer', x=-26.50, y=34.00, z=-248.50], EntityBat['Bat'/5410904, l='MpServer', x=-116.44, y=19.00, z=-287.34], EntityBat['Bat'/5410905, l='MpServer', x=-116.31, y=14.29, z=-279.78], EntityItem['item.item.dyePowder.black'/5270108, l='MpServer', x=-79.59, y=59.13, z=-198.16], EntityBat['Bat'/5410910, l='MpServer', x=-115.38, y=15.00, z=-268.28], EntityZombie['Zombie'/5401692, l='MpServer', x=-29.00, y=34.00, z=-247.44], EntityBat['Bat'/5410909, l='MpServer', x=-118.41, y=16.00, z=-284.91], EntitySkeleton['Skeleton'/4711511, l='MpServer', x=26.30, y=-124.17, z=16.61], EntityZombie['Zombie'/5404230, l='MpServer', x=-146.50, y=15.00, z=-322.50], EntityZombie['Zombie'/5404231, l='MpServer', x=-146.50, y=15.00, z=-323.50], EntitySkeleton['Skeleton'/4922461, l='MpServer', x=-39.43, y=-1628.43, z=-30.58], EntityCreeper['Creeper'/5404228, l='MpServer', x=-158.66, y=23.00, z=-273.03], EntitySkeleton['Skeleton'/4734544, l='MpServer', x=30.71, y=-4288.35, z=-27.38], EntitySkeleton['Skeleton'/4734545, l='MpServer', x=27.71, y=-4285.35, z=-30.38], EntityWitch['Witch'/5360718, l='MpServer', x=-82.94, y=21.00, z=-261.50], EntitySpider['Spider'/3119631, l='MpServer', x=-13.04, y=-14762.36, z=-43.29], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413494, l='MpServer', x=-92.22, y=48.97, z=-260.06], EntityEnderman['Enderman'/5387895, l='MpServer', x=-66.50, y=23.00, z=-314.50], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413495, l='MpServer', x=-92.22, y=48.97, z=-260.06], EntityCreeper['Creeper'/5398645, l='MpServer', x=-116.00, y=19.00, z=-298.41], EntityZombie['Zombie'/4607596, l='MpServer', x=37.22, y=-827.52, z=10.09], EntityZombie['Zombie'/5364323, l='MpServer', x=-90.05, y=21.73, z=-267.50], EntityZombie['Zombie'/5400160, l='MpServer', x=-21.50, y=37.00, z=-250.88], EntityCreeper['Creeper'/5402212, l='MpServer', x=-42.50, y=30.00, z=-236.97], EntitySkeleton['Skeleton'/5412458, l='MpServer', x=-50.50, y=32.00, z=-194.50], EntityZombie['Zombie'/5397611, l='MpServer', x=-61.50, y=16.00, z=-256.50], EntityZombie['Zombie'/5412459, l='MpServer', x=-52.50, y=32.00, z=-195.50], EntityCreeper['Creeper'/5396590, l='MpServer', x=-19.00, y=37.00, z=-268.41], EntitySpider['Spider'/5396591, l='MpServer', x=-21.34, y=37.00, z=-260.66], EntityBat['Bat'/5412882, l='MpServer', x=-75.43, y=35.00, z=-219.31], EntityBat['Bat'/5398039, l='MpServer', x=-58.16, y=19.48, z=-247.25], EntityPig['Pig'/5223944, l='MpServer', x=-126.50, y=72.00, z=-181.53], EntitySkeleton['Skeleton'/4921857, l='MpServer', x=-29.86, y=-42.24, z=31.68], EntitySkeleton['Skeleton'/4922369, l='MpServer', x=-45.24, y=-1628.43, z=-20.96], EntityItem['item.item.rottenFlesh'/5345307, l='MpServer', x=-133.47, y=26.13, z=-308.06], EntityZombie['Zombie'/5088774, l='MpServer', x=-56.07, y=-151.06, z=4.69], EntitySkeleton['Skeleton'/4475912, l='MpServer', x=5.77, y=-845.75, z=-0.90], EntityZombie['Zombie'/4555786, l='MpServer', x=-11.58, y=-9427.71, z=-58.89], EntitySkeleton['Skeleton'/4613641, l='MpServer', x=24.22, y=-124.17, z=19.45], EntityBat['Bat'/5403165, l='MpServer', x=-153.25, y=22.10, z=-280.28], EntityWitch['Witch'/5391362, l='MpServer', x=-120.50, y=13.00, z=-276.50], EntitySkeleton['Skeleton'/5130267, l='MpServer', x=-49.81, y=-480.57, z=-10.19], EntityZombie['Zombie'/4520978, l='MpServer', x=6.60, y=-812.43, z=10.61], EntityItem['item.item.dyePowder.black'/5267976, l='MpServer', x=-73.13, y=58.25, z=-204.13], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413386, l='MpServer', x=-95.50, y=47.66, z=-259.90], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413387, l='MpServer', x=-94.73, y=47.71, z=-260.14], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413385, l='MpServer', x=-95.32, y=47.80, z=-259.82], EntitySpider['Spider'/4734486, l='MpServer', x=26.35, y=-4283.35, z=-30.24], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413388, l='MpServer', x=-94.61, y=47.83, z=-259.99], EntitySpider['Spider'/5395511, l='MpServer', x=-15.00, y=19.00, z=-257.91], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413434, l='MpServer', x=-93.25, y=48.72, z=-260.08], EntitySkeleton['Skeleton'/4858403, l='MpServer', x=8.68, y=-176.92, z=12.74], EntitySkeleton['Skeleton'/5060132, l='MpServer', x=5.61, y=-55.75, z=31.10], EntitySkeleton['Skeleton'/4555311, l='MpServer', x=-34.90, y=-115.47, z=26.05], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413433, l='MpServer', x=-93.26, y=48.72, z=-260.06], EntityZombie['Zombie'/4858404, l='MpServer', x=10.89, y=-61.19, z=16.04], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413422, l='MpServer', x=-93.86, y=48.28, z=-260.16], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413423, l='MpServer', x=-93.86, y=48.30, z=-260.09], EntitySkeleton['Skeleton'/4208191, l='MpServer', x=-8.96, y=-14765.36, z=-42.11], EntitySpider['Spider'/5009612, l='MpServer', x=36.31, y=-1579.45, z=-31.74], EntityZombie['Zombie'/5412048, l='MpServer', x=-43.35, y=35.95, z=-200.66], EntityZombie['Zombie'/5403866, l='MpServer', x=-116.00, y=34.00, z=-224.56], EntityBat['Bat'/5396184, l='MpServer', x=-144.25, y=16.00, z=-320.55], EntitySpider['Spider'/4611275, l='MpServer', x=34.77, y=-829.52, z=9.06], EntitySkeleton['Skeleton'/5397215, l='MpServer', x=-79.44, y=21.00, z=-260.06], EntitySpider['Spider'/5129945, l='MpServer', x=-45.11, y=-1609.76, z=-21.67], EntityZombie['Zombie'/5010133, l='MpServer', x=33.66, y=-1582.45, z=-30.50], EntityCreeper['Creeper'/5412045, l='MpServer', x=-146.50, y=57.00, z=-192.50], EntityBat['Bat'/5403894, l='MpServer', x=-119.44, y=14.00, z=-283.63], EntityZombie['Zombie'/4405990, l='MpServer', x=9.90, y=-41.52, z=47.51], EntityBat['Bat'/5403895, l='MpServer', x=-114.69, y=22.10, z=-278.25], EntityZombie['Zombie'/4639456, l='MpServer', x=5.68, y=-6149.15, z=-37.14], EntitySpider['Spider'/4858093, l='MpServer', x=11.66, y=-180.91, z=14.19], EntityZombie['Zombie'/4406510, l='MpServer', x=6.84, y=-38.52, z=50.45], EntitySkeleton['Skeleton'/5411068, l='MpServer', x=-70.50, y=39.00, z=-238.50], EntityBat['Bat'/5394146, l='MpServer', x=-114.48, y=20.06, z=-283.25], EntitySkeleton['Skeleton'/5397216, l='MpServer', x=-76.44, y=21.00, z=-259.66], EntityZombie['Zombie'/5401824, l='MpServer', x=-18.50, y=19.00, z=-256.50], EntitySkeleton['Skeleton'/5410534, l='MpServer', x=-107.50, y=15.00, z=-239.50], EntitySkeleton['Skeleton'/5410533, l='MpServer', x=-106.50, y=15.00, z=-241.50], EntitySpider['Spider'/5401832, l='MpServer', x=-73.53, y=19.00, z=-246.84], EntityZombie['Zombie'/4924151, l='MpServer', x=-13.65, y=-5762.19, z=-58.07], EntityItem['item.item.slimeball'/5377774, l='MpServer', x=-71.44, y=38.13, z=-285.75], EntityZombie['Zombie'/4924148, l='MpServer', x=-21.73, y=-5773.60, z=-58.47], EntityZombie['Zombie'/5403792, l='MpServer', x=-106.50, y=25.00, z=-261.50], EntitySpider['Spider'/5398682, l='MpServer', x=-65.50, y=15.00, z=-265.28], EntitySkeleton['Skeleton'/5400222, l='MpServer', x=-20.50, y=37.00, z=-253.50], EntitySkeleton['Skeleton'/5400223, l='MpServer', x=-20.50, y=37.00, z=-254.50], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413535, l='MpServer', x=-90.88, y=48.97, z=-260.13], EntityZombie['Zombie'/5400221, l='MpServer', x=-119.50, y=15.00, z=-312.50], EntitySkeleton['Skeleton'/5396617, l='MpServer', x=-117.50, y=22.00, z=-271.50], EntitySkeleton['Skeleton'/5129873, l='MpServer', x=-46.70, y=-1611.76, z=-23.87], EntityBat['Bat'/5412493, l='MpServer', x=-27.63, y=13.64, z=-203.66], EntitySpider['Spider'/4406435, l='MpServer', x=-11.44, y=-46.38, z=38.61], EntitySkeleton['Skeleton'/5010092, l='MpServer', x=35.58, y=-1582.45, z=-28.20], EntitySpider['Spider'/5398197, l='MpServer', x=-114.50, y=21.00, z=-293.06], EntityZombie['Zombie'/5398203, l='MpServer', x=-115.50, y=21.00, z=-289.50], EntityCreeper['Creeper'/5398200, l='MpServer', x=-112.44, y=21.00, z=-295.56], EntitySpider['Spider'/5311676, l='MpServer', x=-31.83, y=-35.09, z=43.21], EntityClientPlayerMP['nightmare_2862'/94, l='MpServer', x=-88.57, y=49.09, z=-260.43], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413536, l='MpServer', x=-90.88, y=48.97, z=-260.13], EntityCreeper['Creeper'/5400225, l='MpServer', x=-21.50, y=37.00, z=-255.50], EntitySkeleton['Skeleton'/4554928, l='MpServer', x=-34.86, y=-115.47, z=31.87], EntityZombie['Zombie'/4475576, l='MpServer', x=1.41, y=-2430.77, z=-3.22], EntityZombie['Zombie'/4711236, l='MpServer', x=27.31, y=-833.89, z=15.30], EntityBat['Bat'/5412182, l='MpServer', x=-126.28, y=25.90, z=-207.56], EntitySkeleton['Skeleton'/4522306, l='MpServer', x=8.49, y=-817.43, z=12.64], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413210, l='MpServer', x=-97.76, y=41.98, z=-259.16], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413211, l='MpServer', x=-98.46, y=41.47, z=-259.44], EntityZombie['Zombie'/5088070, l='MpServer', x=-57.29, y=-148.06, z=6.85], EntityZombie['Zombie'/5392734, l='MpServer', x=-114.50, y=21.00, z=-288.50], EntityZombie['Zombie'/4710748, l='MpServer', x=29.96, y=-119.17, z=24.23], EntityZombie['Zombie'/3119410, l='MpServer', x=-5.03, y=-14765.36, z=-43.02], EntityZombie['Zombie'/5407564, l='MpServer', x=-146.06, y=34.00, z=-195.44], EntitySpider['Spider'/4406620, l='MpServer', x=9.88, y=-36.52, z=51.32], EntitySkeleton['Skeleton'/5396813, l='MpServer', x=-64.50, y=14.00, z=-257.50], EntityZombie['Zombie'/4639591, l='MpServer', x=7.43, y=-6154.15, z=-41.18], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413232, l='MpServer', x=-98.07, y=42.98, z=-259.25], EntityZombie['Zombie'/5088105, l='MpServer', x=-56.04, y=-146.06, z=6.23], EntityZombie['Zombie'/4736365, l='MpServer', x=16.53, y=-5973.75, z=-37.07], EntitySkeleton['Skeleton'/5088104, l='MpServer', x=-55.21, y=-151.06, z=10.31], EntityZombie['Zombie'/5161828, l='MpServer', x=42.48, y=-486.78, z=-7.56], EntityItem['item.item.dyePowder.black'/5356925, l='MpServer', x=-84.19, y=51.13, z=-220.88], EntitySpider['Spider'/5161827, l='MpServer', x=40.43, y=-488.78, z=-6.45], EntityZombie['Zombie'/4639592, l='MpServer', x=4.49, y=-6151.15, z=-39.01], EntitySkeleton['Skeleton'/5399421, l='MpServer', x=-96.50, y=20.00, z=-256.50], EntitySpider['Spider'/5059965, l='MpServer', x=7.48, y=-50.75, z=27.88], EntityZombie['Zombie'/4522365, l='MpServer', x=6.27, y=-817.43, z=11.57], EntitySkeleton['Skeleton'/4736368, l='MpServer', x=20.34, y=-5976.75, z=-35.49], EntityBat['Bat'/5402984, l='MpServer', x=-117.25, y=15.13, z=-304.56], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413231, l='MpServer', x=-97.74, y=42.70, z=-259.54], EntityZombie['Zombie'/4736268, l='MpServer', x=16.37, y=-5971.75, z=-34.32], EntitySkeleton['Skeleton'/4636429, l='MpServer', x=37.39, y=-4031.02, z=-27.72], EntityZombie['Zombie'/5368577, l='MpServer', x=-114.66, y=19.00, z=-300.50], EntitySkeleton['Skeleton'/5312773, l='MpServer', x=-28.12, y=-39.86, z=41.69], EntityZombie['Zombie'/5396237, l='MpServer', x=-94.07, y=22.00, z=-259.47], EntityZombie['Zombie'/5401910, l='MpServer', x=-114.75, y=20.00, z=-295.72], EntityZombie['Zombie'/5401911, l='MpServer', x=-112.72, y=21.00, z=-291.50], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413179, l='MpServer', x=-98.25, y=40.89, z=-258.62], EntityItem['item.item.dyePowder.black'/5268794, l='MpServer', x=-81.53, y=59.13, z=-198.66], EntityZombie['Zombie'/4736292, l='MpServer', x=18.42, y=-5976.75, z=-38.13], EntityBat['Bat'/5403453, l='MpServer', x=-112.10, y=24.29, z=-264.02], EntitySkeleton['Skeleton'/5412669, l='MpServer', x=-31.50, y=30.00, z=-214.50], EntityZombie['Zombie'/4556598, l='MpServer', x=-4.84, y=-9427.71, z=-59.69], EntityZombie['Zombie'/5009723, l='MpServer', x=38.39, y=-1577.45, z=-31.83], EntityItem['item.item.dyePowder.black'/5356845, l='MpServer', x=-79.19, y=59.13, z=-197.13], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413328, l='MpServer', x=-96.20, y=46.46, z=-259.91], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413329, l='MpServer', x=-96.18, y=46.60, z=-259.97], EntityCreeper['Creeper'/5409238, l='MpServer', x=-22.50, y=37.00, z=-252.50], EntityZombie['Zombie'/4520897, l='MpServer', x=5.07, y=-814.43, z=10.57], EntityCreeper['Creeper'/5409239, l='MpServer', x=-21.50, y=37.00, z=-254.50], EntitySkeleton['Skeleton'/5409236, l='MpServer', x=-21.50, y=37.00, z=-253.50], EntitySkeleton['Skeleton'/5409237, l='MpServer', x=-23.50, y=37.00, z=-252.50], EntityCreeper['Creeper'/5403098, l='MpServer', x=-17.06, y=25.00, z=-263.28], EntityItem['item.item.slimeball'/5381576, l='MpServer', x=-79.88, y=39.13, z=-276.81], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413326, l='MpServer', x=-97.20, y=46.31, z=-259.65], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413327, l='MpServer', x=-96.95, y=46.15, z=-259.75], EntitySkeleton['Skeleton'/5130731, l='MpServer', x=-49.78, y=-480.57, z=-15.93], EntityBat['Bat'/5410805, l='MpServer', x=-65.17, y=13.82, z=-253.13], EntityZombie['Zombie'/5060069, l='MpServer', x=8.47, y=-52.75, z=29.70], EntitySpider['Spider'/4475373, l='MpServer', x=3.84, y=-2430.58, z=-5.16], EntitySkeleton['Skeleton'/5060068, l='MpServer', x=12.82, y=-55.75, z=27.06], EntitySkeleton['Skeleton'/4476399, l='MpServer', x=5.80, y=-2429.44, z=-6.96], EntityEnderman['Enderman'/5391359, l='MpServer', x=-119.31, y=14.00, z=-282.50], EntitySpider['Spider'/4554741, l='MpServer', x=-35.56, y=-110.47, z=27.20], EntityItem['item.item.dyePowder.black'/5310433, l='MpServer', x=-80.31, y=54.13, z=-209.84], EntityZombie['Zombie'/4921850, l='MpServer', x=-32.45, y=-39.24, z=28.26], EntityZombie['Zombie'/4921852, l='MpServer', x=-30.63, y=-42.24, z=26.73], EntityZombie['Zombie'/4556285, l='MpServer', x=-3.60, y=-9422.71, z=-61.57], EntityZombie['Zombie'/4921845, l='MpServer', x=-38.84, y=-40.34, z=28.81], EntityZombie['Zombie'/4611462, l='MpServer', x=25.87, y=-124.17, z=17.58], EntitySpider['Spider'/4922250, l='MpServer', x=-47.53, y=-1623.43, z=-24.69], EntitySkeleton['Skeleton'/5161867, l='MpServer', x=43.48, y=-491.78, z=-3.56], EntityZombie['Zombie'/3103718, l='MpServer', x=-11.04, y=-14760.36, z=-44.29], EntitySkeleton['Skeleton'/4565900, l='MpServer', x=-50.56, y=-2427.16, z=-10.59], EntitySkeleton['Skeleton'/4859267, l='MpServer', x=8.38, y=-57.54, z=19.42], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413275, l='MpServer', x=-97.25, y=44.96, z=-259.92], EntityZombie['Zombie'/4556169, l='MpServer', x=-5.46, y=-9424.71, z=-60.80], EntitySkeleton['Skeleton'/4922247, l='MpServer', x=-45.91, y=-1625.43, z=-24.96], EntitySkeleton['Skeleton'/5407646, l='MpServer', x=-44.50, y=21.00, z=-198.50], EntityCreeper['Creeper'/5372317, l='MpServer', x=-16.44, y=37.00, z=-274.16], EntityCreeper['Creeper'/5372316, l='MpServer', x=-17.41, y=37.00, z=-277.00], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413276, l='MpServer', x=-97.23, y=44.50, z=-260.00], EntitySkeleton['Skeleton'/5372318, l='MpServer', x=-16.31, y=37.00, z=-272.56], EntityZombie['Zombie'/5394307, l='MpServer', x=-140.50, y=17.00, z=-318.50], EntitySkeleton['Skeleton'/5411715, l='MpServer', x=-149.06, y=13.00, z=-230.60], EntitySkeleton['Skeleton'/4636562, l='MpServer', x=34.47, y=-4031.02, z=-31.30], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413254, l='MpServer', x=-97.88, y=43.91, z=-260.10], EntitySkeleton['Skeleton'/4636563, l='MpServer', x=36.75, y=-4028.02, z=-32.90], EntityBulletBaseNT['entity.hbm.entity_bullet_mk3.name'/5413253, l='MpServer', x=-97.98, y=43.64, z=-259.82], EntitySkeleton['Skeleton'/5312396, l='MpServer', x=-31.46, y=-40.09, z=38.78], EntitySpider['Spider'/4666776, l='MpServer', x=-25.29, y=-844.14, z=7.53], EntitySkeleton['Skeleton'/5388722, l='MpServer', x=-86.38, y=20.96, z=-258.49], EntitySpider['Spider'/4636583, l='MpServer', x=38.41, y=-5578.51, z=-33.57], EntityZombie['Zombie'/4924329, l='MpServer', x=-12.65, y=-5767.19, z=-60.07], EntityZombie['Zombie'/5161895, l='MpServer', x=43.38, y=-491.78, z=-9.36], EntityZombie['Zombie'/5399997, l='MpServer', x=-106.94, y=21.00, z=-277.56], EntitySkeleton['Skeleton'/4554675, l='MpServer', x=-37.52, y=-112.47, z=28.17], EntitySpider['Spider'/5398436, l='MpServer', x=-135.00, y=17.00, z=-318.34], EntityZombie['Zombie'/5398437, l='MpServer', x=-141.50, y=17.00, z=-318.50], EntitySkeleton['Skeleton'/4639679, l='MpServer', x=7.95, y=-6154.15, z=-40.88], EntitySpider['Spider'/4710844, l='MpServer', x=26.85, y=-121.17, z=23.55]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 624174856 bytes (595 MB) / 2075131904 bytes (1979 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	securitycraft{v1.8.13} [SecurityCraft] ([1.7.10] SecurityCraft v1.8.13.jar) 
	UCHIJAAAA	hbm{1.0.27 BETA (4915)} [Hbm's Nuclear Tech] (HBM-NTM-.1.0.27_X4915.jar) 
	UCHIJAAAA	cfm{3.4.7} [ 9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAA	neodymium{0.2.3} [Neodymium] (neodymium-1.7.10-0.2.3.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 31.0.101.4502' Renderer: 'Intel(R) UHD Graphics'
	Launched Version: forge-10.13.4.1614
	LWJGL: 2.9.1
	OpenGL: Intel(R) UHD Graphics GL version 4.6.0 - Build 31.0.101.4502, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by nightmare2862** [comment]
if this is not bug then i will close the issue tomorrow

**Comment by nightmare2862** [comment]
as cant be fixed

**Comment by OneX-Developer** [comment]
> Could you please provide the crash report

here is one, of balefire crashing on touch with TNT!

The game crashed whilst exception while ticking a block
Error: java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=explode, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=hbm:balefire, properties=[age, east, north, south, up, west]}
