### ISSUE TITLE
Rather, it's not even a problem, but just a question. Trench armor.

### ISSUE THREAD

**Issue by Xray1716** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1406]
I haven't noticed any fashion mistakes yet, I wanted to ask how to find this trench armor except in the creative. There is no crafting, there is no consumption of anything to power the armor either. Based on this, I have 2 questions, 1: where can I find the armor? 2: what configuration should I get into to make this armor consume (for example, electricity/steam). Thank you in advance!

**Comment by SoB1nary** [comment]
You can find it in the red room, and it doesn't require charging.
https://ntm.fandom.com/ru/wiki/Красная_комната

**Comment by Xray1716** [comment]
> Вы можете найти его в красной комнате, и он не требует зарядки. [https://ntm.fandom.com/ru/wiki/Красная_комната](https://ntm.fandom.com/ru/wiki/%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%B0%D1%8F_%D0%BA%D0%BE%D0%BC%D0%BD%D0%B0%D1%82%D0%B0)

Thank you. it was not about how to charge it, but how to make it so that it could be charged. on our server, this Armor will be too unbalanced. Thanks again)

**Comment by HbmMods** [comment]
There's no config for that, you would have to rewrite part of the armor's code to make it accept power or have durability.

**Comment by Xray1716** [comment]
> Для этого нет конфигурации, вам придется переписать часть кода брони, чтобы она принимала мощность или имела долговечность.

I'll tell my programmer friend, thanks for the support!
