### ISSUE TITLE
Configs Resetting After Game Startup

### ISSUE THREAD

**Issue by LivingTank12345** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1408]
The title essentially is the entire problem. But, to give you a rundown on what I am attempting to do, I go into the config to change the recipes in some of the Oil Refinement and Oil Processing machines, mainly just the amount of outputs the machines have, not actually what the output is. (In terms of the output name) I have made sure to properly edit the configs as I am simply changing a number, and I have been making mod packs for a few years now and I don't think I would mess up changing a number in a config file. It resets the moment I load the game, I don't even have to load into a world. I have used multiple programs to edit it and still have had no luck.

I am using the current version of the game, and to my knowledge, there is no mod conflicts going on as the game runs smoothly and I have yet to have any crashes or intense lag spikes. I am open to any suggestions, but I am more or less convinced this is a problem with this version of the mod as I have edited this config multiple times with zero problem. (Other than a few mistakes made by me)

**Comment by HbmMods** [comment]
Did you remove the leading underscore from the config's name?

**Comment by LivingTank12345** [comment]
No? Am I supposed to do this?

**Comment by HbmMods** [comment]
In the same folder you should have a file like this

![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/16674258/dde038a7-bab2-47a3-861f-9dc3b8a26f05)

**Comment by LivingTank12345** [comment]
Oh...now I kinda feel dumb. Thanks though, I have never edited recipes before, only the normal configs. Have a great day!
