### ISSUE TITLE
(Suggestion) Radiation API

### ISSUE THREAD

**Issue by TheForge129** [HbmMods/Hbm-s-Nuclear-Tech-GIT#141]
Move the radiation system to a seperate jar inside the ntm jar as well as releasing it on its own. The radiation API would work the same way as radiation in the regular mod. The radaway, geiger counter, rad resistance stuff, etc would all be kept inside the radiation api jar. This would make it possible for other developers to use the ntm radiation system without requiring the ntm jar and a fuckton of work essentially making their own modified ntm jar.
It'd take a lot of work, however. This is a situation of "Is it worth the effort". I would say no, but it is definitely an idea.

**Comment by HbmMods** [comment]
Is there anyone that is currently trying to work on NTM radiation compatibility? Player contamination is a simple NBT tag and most other radiation related classes could get some API interfaces to make it easier to work with, so I doubt a separate jar is needed.

**Comment by TheForge129** [comment]
The seperate jar was only so that it didn't require the base NTM jar if the player doesn't want it. I don't think anyone is trying to use the ntm radiation right now, so this would basically just be a key to a door no one has looked for yet.

**Comment by Shibva** [comment]
might not be a bad idea to add some way for omeone to create an addon that allows for other tiems with radiation to give RADS and have their own rad overlay

Like with the items from NuclearCraft

**Comment by TheForge129** [comment]
> might not be a bad idea to add some way for omeone to create an addon that allows for other tiems with radiation to give RADS and have their own rad overlay
> 
> Like with the items from NuclearCraft

that's basically the idea i was going for

**Comment by TheForge129** [comment]
closing because it's kind of cluttering the issue tracker and it's probably not gonna happen
