### ISSUE TITLE
Soot cannot be produced

### ISSUE THREAD

**Issue by LSK-LW** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1420]
The chimney seems to have lost its function

**Comment by HbmMods** [comment]
Could you be a bit more specific? What machines did you use for making smoke, what fuels did you use, are you sure you hooked up the pipes correctly, is there smoke coming out of the chimney at all?

**Comment by LSK-LW** [comment]
> Could you be a bit more specific? What machines did you use for making smoke, what fuels did you use, are you sure you hooked up the pipes correctly, is there smoke coming out of the chimney at all?

![2024-04-03_18 34 06](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/12579533/9220bfa4-5cd2-4074-8865-0fc71a07a344)
![2024-04-03_18 43 07](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/12579533/5a63db5d-0b65-406e-9967-4040a1ec4252)

I used Fluid Burner and Coker Unit. The fuel is fuel oil and heavy oil. There is no smoke in the chimney.

**Comment by OlorinIV** [comment]
it's these machines in your screenshot that's not working. Solid fuel-burning machines like heating ovens still output smoke correctly, while all fluid-burning machines seem to disfunction.
with some heating ovens connected to smokestacks, they could work properly and generate ash in ash pit, but no smoke particles come out on top.

**Comment by gmhs022** [comment]
Cokers also have never worked with chimneys, and I believe that's intentional.
