### ISSUE TITLE
Where is the new missile silo structure!?

### ISSUE THREAD

**Issue by DB4000K** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1422]
I cant find it anywhere!

**Comment by R-Kaenbyou** [comment]
> I cant find it anywhere!

I found one in a superflat world, seed 4262799965756342300, position (962, -3974).

**Comment by DB4000K** [comment]
you sir
are a gigachad
thanks very much

> > I cant find it anywhere!
> 
> I found one in a superflat world, seed 4262799965756342300, position (962, -3974).
