### ISSUE TITLE
Enhancement about Ore processing

### ISSUE THREAD

**Issue by R-Kaenbyou** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1423]
Beryllium is a widely used material in HBM. However, there is still no way to acquire beryllium fastly and infinitively without cheating and/or high cost. But many other materials can be acquired infinitively and do not require extremely high costs from bedrock ores.

Thus, it may help to solve this problem if allow players to acquire beryllium from emeralds. Thus, allow player to acquire more emeralds can also benefit players. A possible solution is allowing player to acidize emerald ores for emerald crystals.

Besides, for player who require lots of cokes, allow acidize lignite ores for lignite crystals which can be centrifuged into lignite powder may help a lot.

**Comment by JameH2** [comment]
gpt core

**Comment by OlorinIV** [comment]
why not just say you wanted emerald-beryllium silex recipe

**Comment by gmhs022** [comment]
Allow it to be silex'd for beryllium, aluminum, and quartz and you've got a pretty accurate recipe, though there's also no way to get infinite emeralds iirc, so I'm unsure of how useful it would be.

**Comment by gmhs022** [comment]
(Well except villagers but they suck)

**Comment by OlorinIV** [comment]
you can actually get infinite emeralds by shredding them then crystallizing in an ore acidizer with green upgrade installed, dunno if bob will remove this though
but i guess not considering green upgrades consume A LOT of acid, making this recipe strange but fair

**Comment by HbmMods** [comment]
Emeralds have a bedrock ore now, and can be crucible smelted into beryllium.
