### ISSUE TITLE
Rocket artillery bug

### ISSUE THREAD

**Issue by Jundix22** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1427]
I've been testing the rocket artillery system for a while know and i've discovered that it has contained a bug where once you load the rocket artillery with rockets and fire it or leave it loaded then proceed to close off the world/game and then re-open it, then all the rocket ammunition inside of it suddenly disappears leaving the artillery out of ammo. This is quite the annoyance whenever i'm making expensive rockets in survival. The video shows how it happens:

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/165779754/c8c9a8b7-cdf0-4133-884d-d5151ea5c93c

Tested in X4921 version

**Comment by HbmMods** [comment]
Fixed in X4939.
