### ISSUE TITLE
Game crashing randomly

### ISSUE THREAD

**Issue by CinarDumanli12** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1428]
I was playing on and old version (4859 i guess) and then i updated it to last vers. 4921.
Whenever i open my world it starts to lag for the first minute and every 30 mins. or less game randomly crashs and shutdown.
It crashes when i open up my assembly template chest(i didnt check the last vers. maybe you removed smh and that crashes my game)
If you find it pls lemme know

**Comment by HbmMods** [comment]
Ah yes, I will now use my telepathic powers to read the crash log that's in your minecraft folder, give me a sec.
