### ISSUE TITLE
Absolutely massive render time for the heliostat mirrors

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#143]
The mirrors create absolutely massive performance issues, and should have a config option to disable the visual effects.
When not facing them, the framerate is in VSYNC. When facing them, the framerate drops to ~20 FPS. And this is with OptiFine.

**Comment by 9Valjew** [comment]
Get a better PC smh smh

**Comment by HbmMods** [comment]
Previous release should address that, mirrors no longer use TESR rendering and all the light beams are now part of the boiler's renderer which on its own should be a massive improvement. If that's not enough then I'll probably add a config to turn off the light beams completely later on.
