### ISSUE TITLE
Unstable operation of the power grid of the network. Mod version 4936

### ISSUE THREAD

**Issue by Zscreeper** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1438]
the power grid is severely broken, the electric heater is difficult to use, the batteries do not work as before, they are reluctant to fill up even when there is plenty of energy

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/130389090/8a9d0eed-def3-4d9c-9a6d-5aeb0d2bbdfc

**Comment by HbmMods** [comment]
Batteries have a transfer limit, by chaining up a ton of them all in buffer mode they end up using all their transfer capacity just by flinging power left and right. Either invest in better batteries, use capacitors or use diodes to prevent the batteries wasting their transfer capacity doing nothing.

**Comment by Zscreeper** [comment]
I tried to use diodes to differentiate the network, but before the 4935-4936 update everything was very good and these minor energy losses could be considered as inductive heating. at this moment, the power grid is in an unplayable state, I think it's worth rolling back the changes to update 4921

**Comment by Vaern** [comment]
This is the result of player error and not actually an issue with the new update. There's no universe where the old energy system is reintroduced due to its _horrible_ performance compared to the new energy system, and your issues with oscillation can be easily solved by adding diodes (you're supposed to separate your input from your output on batteries).

**Comment by HbmMods** [comment]
I mean there are some things I *could* do but every minor change has the very real possibility of breaking things that are more important. I can run some tests, sure, but I can't promise that there will be a fix for that.

**Comment by Zscreeper** [comment]
I literally spent 2 hours trying to store energy in different ways. In the end, I just removed all the energy storage and just laid the wires, but the energy network works when you rearrange the blocks of wires, as if the network does not work after some time.

**Comment by HbmMods** [comment]
Most likely fixed with the most recent version, large clusters of batteries should no longer waste transfer capacity just ping-ponging energy around while not doing anything useful, which is most likely the phenomenon we've seen here.

**Comment by HbmMods** [comment]
Energy got rewritten again in X4942 and should work pretty much exactly as it did before the new system, if possible please test your setup in the new version.
