### ISSUE TITLE
Infinite energy bug

### ISSUE THREAD

**Issue by Jundix22** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1440]
Seeing the new energy update i decided to test out the energy system, but when i used the energy storage blocks in conjunction with the diodes set at a fixed energy output per tick, it suddenly produced infinite power for my electric heaters.

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/165779754/7c773b66-3204-48a1-90c8-fd96dad0fc27

Tested in version 4936

(EDIT: I tested this exact energy configuration in my new world and for some reason it stopped producing infinite power for my electric heater + machines)

**Comment by OlorinIV** [comment]
Sometimes re-entering a dimension helps solve problems with pre-mk2 worlds. Not guaranteed, but going back to title screen or restarting the game is definitely not going to improve anything. Newly created worlds seem to be fine.

**Comment by HbmMods** [comment]
There was a potential issue that might cause negative energy to be returned (which could even out the usage resulting in a net zero loss), you might want to try that with the most recent version.

**Comment by HbmMods** [comment]
Setup seems to work as expected in X4942.
