### ISSUE TITLE
Sounds are broken

### ISSUE THREAD

**Issue by JosephFrankFir** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1441]
### Describe the bug

When too many machines work at the same time, the sounds break, making the game unplayable.

### Attachment

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/74981187/07b8524f-c2e5-4790-9712-d8688e64f69b

### Version

HBM-NTM-.1.0.27_X4921

**Comment by HbmMods** [comment]
Minecraft has a limit on how many sounds can play at once, after which it will simply forcefully stop older sounds. looped sounds will restart themselves if they are stopped, which is why they will then constantly start and stop due to hitting the limit. I don't think there's anything I can do about that, since I can't find where in the code that limit is imposed or how to avoid it.

**Comment by JosephFrankFir** [comment]
So it's hardcoded or what?

**Comment by JosephFrankFir** [comment]
I guess the only way is to hardcode OpenAL library and potentially Minecraft's internal architecture but it's complex i think

**Comment by JosephFrankFir** [comment]
it's working well so far and the code for it is
```java
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import paulscode.sound.SoundSystemConfig;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        SoundSystemConfig.setNumberNormalChannels(1024);
        SoundSystemConfig.setNumberStreamingChannels(32);
    }
   ```

**Comment by HbmMods** [comment]
what the hell, it's that easy?

**Comment by JosephFrankFir** [comment]
Yeah, just a simple research xd

**Comment by JosephFrankFir** [comment]
will there be an update

**Comment by HbmMods** [comment]
At the latest on sunday, although with the current issues of the new power grid, probably sooner.

**Comment by HbmMods** [comment]
Update is out, regular sounds are now capped at 1000 and streaming sounds at 50.
