### ISSUE TITLE
Unequal energy distribution bug

### ISSUE THREAD

**Issue by Jundix22** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1442]
When i was playing on my survival world i discovered that wood burning generators do not distribute equal energy distribution to my machines, causing only one machine to be powered by one wood burning generator and not the other generators for some reason. Although i would suggest this also applies to other power generating machines.

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/165779754/e920216e-b4ed-4e7a-a6b0-be23dd17a119

Tested in NTM version 4936

EDIT: it got even stranger as i hooked up 4 wood burning generators to a diode set at 1MHE/t connecting all the machines to it, somehow, making the chemical plant drain it's energy to negative numbers possibly to supply the arc welder with infinite energy?

![2024-04-17_04 03 39](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/165779754/ae499350-84f0-4e42-bf00-dac92d08403c)

In the video below I showed how the bug is manifesting itself, as it was generating power unequally while also draining the chemical plant of its energy, so that the wood burning generator can sustain itself.

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/165779754/eacfc60b-ca2c-4674-8c77-c8c8a07f2b3f

However, once i turned on the diode's energy output to max, draining the power generation of the 4th wood burner it somehow stops the infinite energy glitch and resetting the negative energy numbers of the chemical plant to normal, albeit with no power.

**Comment by HbmMods** [comment]
Might be fixed with the most recent version, some stuff regarding output priority changed, I tested it with the same setup and it seems to work. Diodes also had a potential issue where they could return negative energy, although I couldn't replicate that before or after the potential fix.

**Comment by Jundix22** [comment]
> Might be fixed with the most recent version, some stuff regarding output priority changed, I tested it with the same setup and it seems to work. Diodes also had a potential issue where they could return negative energy, although I couldn't replicate that before or after the potential fix.

Unfortunately, i tested it out in the newest version (4939) it turned out not to have been resolved. and the negative energy problem still exists along with the unequal energy distribution problem.

![2024-04-19_15 33 49](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/165779754/8189b26d-dee3-4e4d-8e8e-94d2fd434ff8)

**Comment by Zscreeper** [comment]
one is being treated and the other is being maimed

**Comment by HbmMods** [comment]
Energy was rewritten again, please check if it works in X4942.

**Comment by Jundix22** [comment]
> Energy was rewritten again, please check if it works in X4942.

Yup it works, power generators now distribute equally and I havent seen any negative energy bug, thanks so much
