### ISSUE TITLE
Monster spawner page in nei, the screen freezes.

### ISSUE THREAD

**Issue by BluesManXin** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1443]
Every time I turn to hbm's monster spawner page in nei, the game freezes.
Fast rendering has been turned off
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/66367121/3a5077c5-9cb7-48eb-98df-921a727060a0)
[latest.log](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/15001592/latest.log)
[fml-client-latest.log](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/15001593/fml-client-latest.log)
[fml-server-latest.log](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/15001599/fml-server-latest.log)

**Comment by HbmMods** [comment]
Fixed in X4939.
