### ISSUE TITLE
buffer mode enhancement? bug?

### ISSUE THREAD

**Issue by OlorinIV** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1444]
Buffer mode batteries tend to keep their charge level at a low percentage, for low priority ones this value is about 5%. 
When there is excess power in the network, low-buffers below 5% power behave like low-input ones, absorbing all excess energy; over 5% power they will use their energy to supply the consumers(but very reluctantly), even if this meant some generators would temporarily cause energy spill.

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/104282311/189c61e9-96b8-4d6b-8937-33d1f5dfb4df

And when charge level gets over 95%, buffer mode batteries would refuse to interact with the net no matter what, can only recv/send power from inv slots and face-to-face transmits(which is the only stable power transfer method in the current version).

ps: Buffer or output mode batteries could send power to isolated mode batteries face-to-face.

The network decides to transfer power when the arc welder's internal energy drops below 50%, causing an interval to appear between updates.

And output mode batteries:

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/104282311/73184a1f-a382-457b-ac32-de778e0a3526

Whether they send energy into the net is also associated with their remaining power, but in a more complicated method compared to buffer mode. In the case of the video, by adding and draining energy to and from the battery via inventory slots, it could be observed that when added energy is less than 200MHE during 'network update intervals', or draining energy to below 100MHE, the battery would try to output all its energy between intervals. If not, the battery stays isolated, and somehow 'persuades' some of the generators to stop providing energy to the machine.

**Comment by HbmMods** [comment]
Energy was rewritten again, please check if it works in X4942.

**Comment by OlorinIV** [comment]
No problem so far; I believe they're all fixed.
