### ISSUE TITLE
No power output/cables not working

### ISSUE THREAD

**Issue by JewelTheDragon** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1446]
The problem is exactly as in title. I updated my game 2 days ago to version HBM-NTM-.1.0.27_X4936 and my concrete production has stopped once I started the game again. Stirling generator seem to run just fine. I tried many times disconnecting the cable and connecting it again but energy was not being exported from Stirling generator

**Comment by OlorinIV** [comment]
My suggestion: rollback the version, everything concerning power transfer is very unstable now. And there wasn't much that has been added in the recent 2 updates except for the second power system that's pretty much unusable.

**Comment by HbmMods** [comment]
Stirling generators were broken, they didn't output energy into cables at all. Should be fixed with the most recent version.
