### ISSUE TITLE
HTR rocket question

### ISSUE THREAD

**Issue by Jundix22** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1448]
Will the HTR rocket ever return in some way? Will it be remodeled or renamed? Considering the Soyuz rocket being cheaper and satelites being incredibly useful, its still extremely hard to find the whiskey drenched notebook for the soyuz rocket (so far i have not found it in my multiple survival playthroughs), I'm just wondering if it's going to be that way or will it be brought back in then near future?

**Comment by HbmMods** [comment]
I did consider a replacement, but since the Soyuz launcher's recipe got changed, there wasn't a whole lot of demand for it. The notebook requirement is something I'll most likely change considering the Soyuz is now mandatory for all space related things.

**Comment by Jundix22** [comment]
> I did consider a replacement, but since the Soyuz launcher's recipe got changed, there wasn't a whole lot of demand for it. The notebook requirement is something I'll most likely change considering the Soyuz is now mandatory for all space related things.

Thank you for your answer, it didnt make sense to me why such an amazing rocket was hidden behind a notebook after the htr got removed. I'm looking forward to that update
