### ISSUE TITLE
Nukes wont generate selafite and wont destroy blocks

### ISSUE THREAD

**Issue by Jundix22** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1449]
I started speedrunning minecraft to achieve the manhattan project achievement, but after i detonated the nuke and died, the terrain i just nuked somehow didnt generate any sellafite nor radiation, instead, it turned into a gaint unscaved pit.

![2024-04-19_13 42 35](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/165779754/7530d674-5b95-446e-8931-a4b1c65b2217)

So after that, i went into a new creative world in to try and test out why this happens. So i discovered that if you get killed in a few seconds in close proximity to the nuke before the sellafite loads and then respawn outside of those loaded chunks, it wont generate any sellafite nor radiation, and if you are immediately incinerated by the nuke then the destruction wont occur.

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/165779754/d05d3036-5551-4fa9-bc6e-74e2e28dad47

Tested in HBM's latest version 4939

**Comment by Antineutrino-4444** [comment]
maybe the chunk was unloaded? including the log could be helpful :)

**Comment by HbmMods** [comment]
Yeah I see the issue, nuclear explosions are chunkloading, but the fallout effect entity isn't, so after the explosion completes, the fallout either fails to spawn or just despawns immediately due to being unloaded. If you bury a chunkloader encased in concrete directly under the nuke or wait before respawning, it will probably work.

**Comment by Jundix22** [comment]
> Yeah I see the issue, nuclear explosions are chunkloading, but the fallout effect entity isn't, so after the explosion completes, the fallout either fails to spawn or just despawns immediately due to being unloaded. If you bury a chunkloader encased in concrete directly under the nuke or wait before respawning, it will probably work.

You're right, I buried a chunkloader encased in reinforced cmb bricks and it worked right after i immediately got killed and respawned at the same time. Without the chunkloader it would not have caused any destruction + fallout.

I would also like to mention that the destruction of the surrounding area wont load after you immediately respawn outside of the loaded area, thereby, negating all of its devastating effects, so thats also an issue to be aware of.

**Comment by HbmMods** [comment]
Chunkloading was added to fallout in X4942, as for the explosion being completely canceled due to respawning, this *could* be due to the game completely reloading the world which will abort the explosion, although if that's the case then there's not much I can do about it.

**Comment by Jundix22** [comment]
> Chunkloading was added to fallout in X4942, as for the explosion being completely canceled due to respawning, this _could_ be due to the game completely reloading the world which will abort the explosion, although if that's the case then there's not much I can do about it.

Yes its fixed, after i died and respawned outside of the loaded area the explosion generated along with the radiation. I did the same test like in the previous version and it worked! Thanks for the fix

![2024-04-22_05 01 58](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/165779754/ee4e99f9-fac3-4de3-9117-f09cb22a2bc0)
