### ISSUE TITLE
Energy distribution bug (not distributing to a connected machine at all)

### ISSUE THREAD

**Issue by QuadBitBrain** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1451]
### Describe the bug
Version: HBM-NTM-.1.0.27_X4939

Some machines not getting energy at all at random (changes with each restart), examples:
![изображение](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/16286770/748b0394-9b11-437e-9a70-9ac36c6fc20d)
![изображение](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/16286770/f395601d-96be-465c-8ecc-fc419d29e4d6)
![изображение](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/16286770/53085b88-b58f-48c8-8d10-6c0a641bb137)
![изображение](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/16286770/4982ccbc-5d81-4063-88b8-58e6c3c4c08d)

**Comment by HbmMods** [comment]
Energy got rewritten again, likely resolved in X4942.

**Comment by QuadBitBrain** [comment]
Seems to be working right for now, at least for my network. (after updating to X4942)
