### ISSUE TITLE
Biomes'O Plenty

### ISSUE THREAD

**Issue by re7gog** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1458]
### Describe the bug

Biomes'O Plenty biome id conflicts with HBM, so there is Inner Crater biome generated instead of normal biome

**Comment by HbmMods** [comment]
The config category `17_biomes` lets you change the biome IDs.

**Comment by re7gog** [comment]
Thanks

**Comment by re7gog** [comment]
If anyone would face this issue:
Change
`I:17.B00_craterBiomeId=80
I:17.B01_craterBiomeInnerId=81
I:17.B02_craterBiomeOuterId=82`
To
`I:17.B00_craterBiomeId=124
I:17.B01_craterBiomeInnerId=125
I:17.B02_craterBiomeOuterId=126`
