### ISSUE TITLE
Add X20 and Hellfire to Fallout 4

### ISSUE THREAD

**Issue by IMRDz2203659098** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1462]
A guy who doesn’t have a Github account asked me to ask when Bob will add X20 and Hellfire to Fallout 4.

**Comment by HbmMods** [comment]
Considering I don't mod Fallout 4 I'm not sure why they want me out of all people to add things to Fallout 4

**Comment by gmhs022** [comment]
Hellfire, of course, being the song from Disney's _The Hunchback of Notre Dame_.
