### ISSUE TITLE
Grenades cause game to crash

### ISSUE THREAD

**Issue by thecodeconsumes** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1471]
### Describe the bug When throwing grendades (specifically IF grenades) the game crashes shortly afterwards. Unfortunately The time between throwing the grenade and the crash is erratic.

crash log: https://docs.google.com/document/d/1QawsYVWK92hwEA_4sKfpKclLCtiDUkHYeN04qVxTk4w/edit?usp=sharing
Version : https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/tree/1.0.27X4879

**Comment by HbmMods** [comment]
The log you've sent doesn't contain any crashes.

**Comment by Bencek123** [comment]
Have you attempted to use a launcher other than prism? 

It migth have something to do with a false positive chras protection triggeing and exiting the game
