### ISSUE TITLE
Problems with updating mod version

### ISSUE THREAD

**Issue by VillagerTU** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1474]
I have been playing Hbm ntm world on version [1.0.27_X4522]. I wanted to update the mod to version [1.0.27_X4895] when i did that everything was fine but jetpacks didn't work. All i did was replacing the old mod with new one in mods folder.

**Comment by HbmMods** [comment]
Check if the jetpack is fueled, it uses the correct fuel and that the jetpack is turned on via the "backpack" keybind.
