### ISSUE TITLE
"outer crater" spawning as a naturally occurring biome

### ISSUE THREAD

**Issue by ifofa** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1476]
![2024-05-06_18 00 07](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/169075488/2d1c9c19-5e91-4b7d-a380-f83ed3d858dd)
![2024-05-06_17 59 52](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/169075488/0247d6b2-0147-4e09-9eb3-2199dfaad0ad)
![2024-05-06_17 59 30](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/169075488/c20b4701-8ed4-4470-ab44-72b22449ca4c)

**Comment by JameH2** [comment]
Do you have any other biome mods?

**Comment by ifofa** [comment]
biomes'o plenty

**Comment by JameH2** [comment]
Alright make sure to set the crater biomes id to any number below 128, or install one of those id extender mods

**Comment by HbmMods** [comment]
Biomes o' Plenty has an ID overlap with crater biomes, either change the crater biome IDs in the config or disable crater biomes outright.
