### ISSUE TITLE
Latest version not available on Aternos (or Forge)

### ISSUE THREAD

**Issue by ironswordX** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1477]
Me and my friend were playing an older version of this mod one day on our aternos server, so we decided we should give it an update. Though when i went to go find the latest version, it wasn't listed. I checked on the forge page, and it wasn't there either. If the dev(s) of this mod could publish the latest version to forge, it would be greatly appreciated. 

Thank you

**Comment by HbmMods** [comment]
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/16674258/b01a30a0-ec9b-49f5-b425-e03243173e96)

CurseForge is doing its best (i.e. jackshit)

**Comment by ironswordX** [comment]
Ah, oh. I had no idea that it was still being scanned by the lengthy layers of anti-virus on forge
