### ISSUE TITLE
Barrel texture not correct

### ISSUE THREAD

**Issue by 32bitmeterpreterwastaken** [HbmMods/Hbm-s-Nuclear-Tech-GIT#148]
The barrels texture is not on the barrels hitbox

![Screenshot 2021-03-13 162647](https://user-images.githubusercontent.com/65788718/111044847-f89c3380-8418-11eb-96c7-9b6d6c367872.png)

**Comment by HbmMods** [comment]
It's interesting to see since the barrels get offset in *different directions*. Do you have any other mods installed? It might be a rounding error of some sorts, what position were you at?
