### ISSUE TITLE
Italian localization doesn't work

### ISSUE THREAD

**Issue by Hacker6400** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1480]
I tried the new italian localization but it doesn't work. I've even tried to look inside it but it all normal.

**Comment by Hacker6400** [comment]
sorry, i don't look at completely at the file. 
Furthermore i've notice that you need more translation and maybe I can help you since I'm Italian.

**Comment by HbmMods** [comment]
According to the pull request #1470 the localization isn't quite complete yet. If you want to add your own localization, open a PR.
