### ISSUE TITLE
i have found the limit of the ICF

### ISSUE THREAD

**Issue by Bencek123** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1486]
i have made a really powerfull ICF system but its limited by the fluid system having the flow rate based on the buffer size and the amount of heat liquid sodium is capable of handeling

i have attempetd to get the ICF as close as i can to full power these are the following readings i took:

power output: 1,25GHE/s
sodium flow:449'856mb/t
water flow:891'650mb/t
steam flow:89'169'800mb/t
low-pressure steam flow:891'750mb/t

this is just about 15,6% of the maximum power that my boiler system can handle

**Comment by HbmMods** [comment]
is there an actual issue here or why are you telling me this

**Comment by Bencek123** [comment]
> is there an actual issue here or why are you telling me this

You know what im not sure why i did this
