### ISSUE TITLE
RBMK reactor's neutron reflector resets the amount of distance the neutron flux has traveled when reflecting

### ISSUE THREAD

**Issue by ifofa** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1489]

**Comment by OlorinIV** [comment]
Neutrons didn't really travel distances in RBMK. A lot of RBMK builds would be destroyed if this comes true, and besides that there is just no reason to do so.

**Comment by gmhs022** [comment]
Yeah given neutrons can only be reflected back at the source, this isn't an issue, it just keeps fuel rods and reflectors consistent.
