### ISSUE TITLE
ICF not heating up

### ISSUE THREAD

**Issue by Bencek123** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1490]
im giving the ICF 99.5MTU with two lasers and for some reason its not heating up beyond 1.28KTU 
im using a deuterium/tritum fuel

**Comment by Vaern** [comment]
well yeah, it's WIP and fuels don't have stats yet

**Comment by Bencek123** [comment]
> well yeah, it's WIP and fuels don't have stats yet

oh i have read the changelog but i didnt know what they ment by default stats 
thanks!

**Comment by HbmMods** [comment]
The reaction is in fact intended to work but the heat generation is bugged so it doesn't actually make heat when the buffer is at 0TU.

**Comment by Bencek123** [comment]
> The reaction is in fact intended to work but the heat generation is bugged so it doesn't actually make heat when the buffer is at 0TU.

did you also make the lasers less powerfull? cause i have made my lasers more than 2x larger but their power just gone down

**Comment by HbmMods** [comment]
Not directly, there just was a bug that caused laser parts to be considered valid even though the placement of the dependency parts was incorrect, so it just means you built the laser incorrectly.
