### ISSUE TITLE
RBMK heat exchanger not working with liquid sodium

### ISSUE THREAD

**Issue by Bencek123** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1493]
due to saftey i disabled meltdown for the testing of a liquid sodium cooled RBMK but when i attempetd to turn on the reactor the temperature just kept rising without the heat exchangers doing anything

is this intenional for it to not work with liquid sodium or is it a bug?

**Comment by BallOfEnergy1** [comment]
Intentional, RBMKs cannot take thorium or sodium coolants.

**Comment by Bencek123** [comment]
> Intentional, RBMKs cannot take thorium or sodium coolants.

Then only PWR and ICF takes sodium and thorium coolants?

**Comment by BallOfEnergy1** [comment]
> > Intentional, RBMKs cannot take thorium or sodium coolants.
> 
> Then only PWR and ICF takes sodium and thorium coolants? 

Yes.
