### ISSUE TITLE
Strand Caster and crucible, queue of materials problem

### ISSUE THREAD

**Issue by MrKimkimora** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1494]
I am playing Nuclear Tech Mod in solo world. 

config changes:
528 enabled
expensive mode enabled

I spot a problem with casting something of queue of materials by Strand Caster.

We will use cast plates as an example.
We use hopper, 18 copper blocks and 18 iron ones.

Hopper starts filling crucible with copper blocks, some of them is melt, some don't.
Right after the copper runs out, hopper starts putting iron blocks to crucible.
Iron slug completely fills up the crucible. Iron is not pouring into Strand Caster because of not finished copper casting cycle.
So process stops fully.
![2024-05-17_23 52 18](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/144221261/dcee7216-0661-41d8-b743-d646726f1b7a)
![2024-05-17_23 52 28](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/144221261/d9f04f9c-fb83-4eac-b8b5-65e2bad8d212)
![2024-05-17_23 52 31](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/144221261/c714ae43-ab34-4346-af1f-9457ab7e3a89)
![2024-05-18_00 21 39](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/144221261/a7c515ce-332c-4553-a043-3982793774a8)

I found temporary solution by filling crucible with not castable slug (2 blocks per slug) and filling almost all crucible with it.
So it prevent accumulating of materials.
![2024-05-17_23 53 08](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/144221261/447b38a6-25a7-4005-b027-e23c8862af80)
 Yeah, it works, but... it is kinda sucks. Also we need remember that crucible emits pollution when something molten inside. 

I think there can be more elegant solution.
My ideas:
Make number of crucible slots changeable (or just reduce them to 1, anyway everybody use hopper)
Make special item that can fill extra slots and will not be melted.
Allow put everything into crucible to fill extra slots. (grass block, dirt, wheat seeds)

I will give more information if needed.

**Comment by OlorinIV** [comment]
The most elegant solution to this problem is to use _another hopper/conveyor inserter_ with one empty slot for input and others filled with crucible-unaccepted items.

**Comment by Vaern** [comment]
The crucible (fairly reasonably) isn't aware of what it is pouring into, only that there is space and the material is accepted by the receiver; as such, part of its learning curve is not mixing metal types, unless there is somewhere for overflow (e.g. using slag filters, multiple channels, etc.). 

Channels will _always_ prefer to pour into non-channels first (like outlets, shallow molds) so you could solve this by first pouring it into a channel which has an outlet for the strand caster and a channel leading to regular molds with hoppers. If the strand caster is ever blocked up, the other metal will divert to the molds and unclog the system over time. Or, you could have two strand casters with metal filters to prevent this from happening.

**Comment by MrKimkimora** [comment]
> The most elegant solution to this problem is to use _another hopper/conveyor inserter_ with one empty slot for input and others filled with crucible-unaccepted items.

It will not help. There is no difference use 1 hopper or multiple. Problem not with hopper.  
Imagine i am using 2 hoppers instead of one. We will use same 18 blocks of copper and iron. 
Copper from first hopper will fill all item slots in crucible (maybe it will be mixed with iron blocks, but it does not matter, cycle already broken)
Right after copper runs out iron fill ups all crucible. 

Same situation. Problem not solved.

**Comment by MrKimkimora** [comment]
> The crucible (fairly reasonably) isn't aware of what it is pouring into, only that there is space and the material is accepted by the receiver; as such, part of its learning curve is not mixing metal types, unless there is somewhere for overflow (e.g. using slag filters, multiple channels, etc.).
> 
> Channels will _always_ prefer to pour into non-channels first (like outlets, shallow molds) so you could solve this by first pouring it into a channel which has an outlet for the strand caster and a channel leading to regular molds with hoppers. If the strand caster is ever blocked up, the other metal will divert to the molds and unclog the system over time. Or, you could have two strand casters with metal filters to prevent this from happening.

Huge net of foundry channels is not a solution.
Main idea of Strand Caster is using it for many materials without blockage.  If I will build separate SCaster for each material, it will destroy main idea of it. Also foundry channels will increase waiting time a lot. I have to cast cast plates by thousands and I do not wanna wait half an hour. I need solution for one caster and one crucible, it is the fastest combo. As i said, i found lame solution with not castable material and it its sounds a lot better, than making huge net of channels, but it its a crutch. 

Problem not solved.

**Comment by OlorinIV** [comment]
The crucible will refuse to load items into its item buffer if the molten item will exceed the crucible's fluid limit. And the full speed at which the crucible melts items shall also exactly match one hopper's item transfer speed. So you see, your issue shouldn't have existed, given that you're running your crucible at full speed, or there's a bug with your mod file, or you have definitely done something wrong.
And also the strand caster is not designed for taking multiple types of metals, so consider building separate systems.

**Comment by Vaern** [comment]
> Huge net of foundry channels is not a solution. Main idea of Strand Caster is using it for many materials without blockage. If I will build separate SCaster for each material, it will destroy main idea of it. 

Wrong actually, the strand caster is specifically meant for automation requiring continuous batch-cooling. It's up to the player to be sane, control their metal flow, and prevent blockages, idk what else you expected.

**Comment by MrKimkimora** [comment]
> The crucible will refuse to load items into its item buffer if the molten item will exceed the crucible's fluid limit. And the full speed at which the crucible melts items shall also exactly match one hopper's item transfer speed. So you see, your issue shouldn't have existed, given that you're running your crucible at full speed, or there's a bug with your mod file, or you have definitely done something wrong. And also the strand caster is not designed for taking multiple types of metals, so consider building separate systems.

Pouring speed is the bottleneck here. Yes u right that crucible stops accepting items when it full, but..
https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/144221261/7cb39158-2a3f-4bf1-a955-af5282c333b9


And I will not build separated system. Thanks for your ideas, but I found much better (for me) solution with uncastable slug. I just suggest an ideas. 
Also HBM is adding big arc furnace that can work in liquid mode, so maybe it will solve my problem.
But for now I am still with my "uncastable slug" solution.

**Comment by MrKimkimora** [comment]
New Arc Furnace
