### ISSUE TITLE
Maybe bug with 2 recipes 

### ISSUE THREAD

**Issue by 6weesh9** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1495]
Maybe I don't know something, maybe some patchbook says about it, but for some reason I don't have the ability to craft conventional and electric oil heaters, neither in NEI nor in the templates for the assembly machine they are not. Like I click on them in NEI and nothing happens, the crafting recipe is not displayed, well, I don't find them in the template folder either
![2024-05-18_11 25 54](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/76618319/da8b71b3-ba5e-45a0-8f96-6bbbd3db2674)

**Comment by MrKimkimora** [comment]
![изображение](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/144221261/777dcdd5-95ec-4743-842f-9e091727e5b7)

release 4956

**Comment by 6weesh9** [comment]
> ![изображение](https://private-user-images.githubusercontent.com/144221261/331780855-777dcdd5-95ec-4743-842f-9e091727e5b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMjYyNTUsIm5iZiI6MTcxNjAyNTk1NSwicGF0aCI6Ii8xNDQyMjEyNjEvMzMxNzgwODU1LTc3N2RjZGQ1LTk1ZWMtNDc0My04NDJmLTllMDkxNzI3ZTViNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQwOTUyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjhmNDIxZjQ3MGE2NzJlZmNhN2NhMjBhMDRhOGQ0ZTc2N2UyODNjMDMzMjBhYWRlZDRhOTczZTkxMmUyZTVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hMmW0nXxjdZSgzw7WREUk9v8MlM_3oSkAO6zx5vVbK8)
> 
> release 4956

okay, i understand, thx
