### ISSUE TITLE
Please Add Vortex Rifle/Gun To the en_us lang file.

### ISSUE THREAD

**Issue by HAJONK** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1498]
The vortex rifle (not sure if it is vortex rifle or vortex gun) is missing from the en_us lang file, causing it to be called "item.gun_vortex.name"
**Revision:**
It's missing from all of the lang files

**Comment by TheChosenIndividual** [comment]
Same for the sodium material for the crucible im pretty sure, at least according to NEI it is :P

**Comment by HbmMods** [comment]
The gun was never even finished to begin with. The gun rework will come soon, which means it will either be completed or scrapped entirely.
