### ISSUE TITLE
ICF not cycling coolant

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1499]
Since the ICF came out, i made an ICF setup for testing for a video, however, upon turning on the lasers, and injecting Liquid Sodium into the reactor, the reactor will not cycle it, meaning no Hot Liquid Sodium is created, which means no power can be created, even with the core being full of fuel, the coolant will just, not cycle no matter what, i have tried almost everything, and still no results, below is a screenshot of my setup, in case im an idiot and its somehow wrong

thanks for reading, and i hope for a quick response

![ICF reactor setup](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/120053489/699fa95c-3769-4938-9bda-ad6fd7ed2522)

![Captura de pantalla 2024-05-23 132559](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/120053489/61d89d1b-ce0f-4499-b085-7a0a547e8e36)

![Captura de pantalla 2024-05-23 132607](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/120053489/9443310a-8909-461a-8d6c-380b3d5a6683)

-Chosen

**Comment by HbmMods** [comment]
![2024-05-23_20 42 46](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/16674258/8890d575-fda3-46bf-9612-cc3cb3e587ad)

Works on my end, although the ICF's output gauge does show 0mB due to the synchronization happening at the end of the tick, after the ICF has already sent out the hot coolant. Are you sure the ICF isn't actually cooling and the sodium is getting lost somewhere else?

**Comment by TheChosenIndividual** [comment]
Absolutely sure, Reading gauge from the reactor core to the return sodium tank doesnt show anything, and both buffers from the reactor core and return sodium tank are also empty, so, it would be logical to assume its not even being made in the first place

btw i love that you're making the ICF in a blast crater lmao

**Comment by TheChosenIndividual** [comment]
Update: So i created a DIFFERENT modpack, to discard the possibility of config/mod issues, and, it worked, i got it to work...so...i guess we'll focus on the config and mods later, but first things first...i realized that...strangely...the ICF generates MORE heat when the core is empty, rather than when fuel pellets are inserted, which is...paradoxical, using Tritium/Deuterium pellets, i managed to get less than 1M TU/s, which, should be just enough to not generate any power, I used a laser length of 8 cells, sodium coolant cycle, and the previously mentioned T/D fuel pellets, with, basically the same set up as before, so...any...ideas on why thats happening? btw, i AM using the latest patch if that helps

**Comment by HbmMods** [comment]
Pellets not actually working is a bug that was fixed about a week ago, you'll see without pellets it makes more energy because on idle it captures 25% of the incoming laser energy. Fix should be out very soon.

**Comment by TheChosenIndividual** [comment]
alr, and what about the possible config issues? want me to look through those and let you know?

**Comment by HbmMods** [comment]
Did you by any chance edit the fluid trait config? Because the ICF cooling ability is an addition to the cooling trait, and a custom config os obviously not gonna have the new values after the update.

**Comment by TheChosenIndividual** [comment]
Not sure...but i think i might have done when i tried to make a PWR before a PWR lol, ill look into it and let you know

**Comment by TheChosenIndividual** [comment]
Yeah, i did edit the FluidTraits file, im pretty sure, so yeah, thanks for that, also, Question before i do something stupid worthy of an internet beatdown, If i delete the FluidTraits config file, will the game auto re-generate it in its default state?

**Comment by HbmMods** [comment]
Yes, if a config isn't present, the game will generate it with default values.
