### ISSUE TITLE
Long time Request to fix a particle issue

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#150]
this has been fixed by Drillgon200 on his end but I went back to 1.7.10 to play with a dev for another mod and It kind of hurts to see it still not fixed on your end

Could you please fix the player decontaminator so that smoke it produced dosent sink, its kind of anoying and in this case it is

![image](https://user-images.githubusercontent.com/38770780/111399862-99e6ec00-869c-11eb-848b-a2b89729f61b.png)

thanks in advance

**Comment by HbmMods** [comment]
Cloud particles sinking when they collide with players is standard minecraft behavior, they just happened to change it in 1.12.

**Comment by HbmMods** [comment]
Decons now use cyan tinted void particles that do not interact with nearby players.
