### ISSUE TITLE
Bug: OpenComputers integration doesn't work

### ISSUE THREAD

**Issue by GNUser224** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1502]
So, basically, the  computer doesn't see any kind of launch pads connected to, i mean, neither with adapter! Screenshots below
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/74462742/e955ae14-f881-4a94-97b3-119c7f576190)

![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/74462742/83e3f315-6642-4981-a270-e74c1cadd5fc)
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/74462742/b801ed96-7ef7-4ecb-9271-dcc94885855c)

**Comment by TheChosenIndividual** [comment]
Well...im no nuclear scientist...but isnt there supposed to be a wired modem there?, or something? if not, then you're right, this also applies to RBMK components apparently

**Comment by HbmMods** [comment]
OC integration hasn't been added to the new launchpads yet.

**Comment by BallOfEnergy1** [comment]
It has since been added, so this issue is no longer relevant.
