### ISSUE TITLE
Liquidator Suit Helmet "Unnamed"

### ISSUE THREAD

**Issue by meepofthedeep** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1503]
Liquidator helmet becomes "Unnamed 6082" when gas mask combo filter is equipped on it. 
Does not display any information like the other pieces of the armor.
When held in hand name displayed is Liquidator Suit Helmet.

**Comment by HbmMods** [comment]
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/16674258/834cc0c4-d3da-4c24-a277-a631b571fdc1)

Works fine on my end, as do all other filters and masks. Does it only happen to the liquidator mask with the combo filters or to other mask/filter combinations as well? What other mods are you running?

**Comment by Zscreeper** [comment]
I also have such a problem, but here not only with the helmet of the liquidator, but also with helmets in which gas masks are integrated and with the M65-Z gas mask with installed filters

![image](https://github.com/user-attachments/assets/777ec80a-ee1b-48e2-be28-1ea1a66aef04)
![image](https://github.com/user-attachments/assets/60719dd4-3367-44dc-b198-226fffa82591)
![image](https://github.com/user-attachments/assets/2a64b310-8910-4fac-b8e8-69c01dbad283)
