### ISSUE TITLE
gliching the minecraft

### ISSUE THREAD

**Issue by BatuhanGanici90** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1504]
After playing for half an hour, a chunk becomes invisible and random colors appear. I'm trying to take a screenshot, but just as I'm about to take it, the screen goes black and after a few seconds the computer freezes.

**Comment by JameH2** [comment]
There is quite literally nothing anyone can do without specifics. Lets start with what your modlist is

**Comment by HbmMods** [comment]
If your entire computer freezes I doubt it's a minecraft problem to begin with

**Comment by BatuhanGanici90** [comment]
finaly ı got the screenshot
![Ekran görüntüsü 2024-05-25 214505](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/170823212/daaaba7a-2f94-4b12-950f-c06b1c3dec1b)

**Comment by HbmMods** [comment]
That looks more like you GPU dying than anything

**Comment by BatuhanGanici90** [comment]
GPU ram is 520MB and my CPU type is F but CPU is good

**Comment by nightmare2862** [comment]
u tryed updating the gpu?

**Comment by BatuhanGanici90** [comment]
ı m using laptop not PC

**Comment by OlorinIV** [comment]
what's your average fps
and do blocks glitch back when you're trying to mine them

**Comment by BatuhanGanici90** [comment]
avg fps like 100-150
I mined nothing happend

**Comment by OlorinIV** [comment]
not bad pc either...perhaps just a rare bug

**Comment by HbmMods** [comment]
Once again, if your entire PC ends up freezing, it's definitely not an issue with minecraft at all. And even if it were, you have a bunch of other mods too, so it's impossible to say which one it even would be.

**Comment by TheChosenIndividual** [comment]
Yeah...im pretty sure thats a GPU failure friend...either its not powerful enough, or its getting all fucked up

**Comment by BatuhanGanici90** [comment]
my gpu doesn t failtrue on HBM-NTM-.1.0.27_X4690 version
