### ISSUE TITLE
Is Crafttweaker Support Planned? 

### ISSUE THREAD

**Issue by QuantumKn1ght** [HbmMods/Hbm-s-Nuclear-Tech-GIT#151]
As title suggests,

Thank you

**Comment by ShimmeringBlaze** [comment]
I can say with almost complete certainty: No, and it won't be
Sorry

**Comment by HbmMods** [comment]
Crafting and smelting recipes can already be changed with CT, and the assembler has its own configuration file. For everything else there's nothing planned of the sorts.
