### ISSUE TITLE
Telex machine recipe question

### ISSUE THREAD

**Issue by Jundix22** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1510]
Is it supposed to be normal for the telex machine recipe to be able to craft two machines instead of one?

![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/165779754/8682a2b9-13b2-4672-a7dc-a05a7fe97e07)

Version is X4977

**Comment by SoB1nary** [comment]
yes
