### ISSUE TITLE
Bug: Crucible is eating my steel.

### ISSUE THREAD

**Issue by rattlemebones1** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1511]
Version: 4977 (current newest on git)
I am trying to make a large number of steel welded plates for the plasma heater, along with tungsten. For whatever reason the crucible keeps voiding exactly 7 quanta of material, and it only happens with steel.
How I did it: I compressed 21 steel blocks worth, shoved it into a hopper that fed into the crucible, and when i came back there was exactly 1 quantum and 2 ingots left in the casting basin. I did it a second time with less blocks, and it had stolen another 7 quanta of steel. 
Images attached:
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/109101492/30b00a69-0e96-4d0b-88e3-f9e9287d77de)
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/109101492/985e6ba6-4300-4037-a8ab-e0503ba62018)

Also sorry for not responding last time, i forgor.

**Comment by rattlemebones1** [comment]
I can't reproduce it again, seems to have fixed itself? No idea what happened

**Comment by HbmMods** [comment]
Did you unload the chunks while the pouring happened? It's possible that there's a slight delay between the chunk saving and the last pouring operation before the chunk unloads (especially on chunk borders) which might have caused the mold to revert back in time by a tick when it was loaded again, losing a small amount of material.

**Comment by rattlemebones1** [comment]
I was standing near it the whole time iirc, but i could be misremembering. It was on a server if that means anything

**Comment by TheChosenIndividual** [comment]
i think the crucible was hungry, jokes aside, it could be a chunk unloading issue, OR material voiding due to some bug, in case you edited the crucible recipes config in some way

**Comment by rattlemebones1** [comment]
I'm still unable to recreate this problem again, and I don't think it ever will happen again. I'm thinking it may have been a serverside lag moment, and I'm closing this because of that.
