### ISSUE TITLE
Is this a bug or is it supposed to be like this? Soyuz rocket

### ISSUE THREAD

**Issue by TheVitya2127** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1516]
In CARGO MODE, you can deliver resources to other territories and even calculate fuel, but for some reason you cannot send resources over longer distances due to the fact that it requires more fuel, but the tank itself does not increase.
Perhaps someone will say that this is realistic, but in my opinion, a flight from the earth to the moon spends more fuel than a rocket flight from 0 to 600,000 coordinates.
Mod version: X4980

**Comment by HbmMods** [comment]
The soyuz now has a lower base consumption, and consumption is capped at the tank's capacity, meaning that the effective range is now unlimited.
