### ISSUE TITLE
A bug about energy transmission of storage battery.

### ISSUE THREAD

**Issue by zmx945** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1518]
In the latest version, a storage battery is placed between the machine that generates energy or can output energy and the machine that uses energy. Any control mode of the storage battery (such as output only, input only or neither output nor input mode) will transmit the energy in the machine that generates energy to the machine that uses energy, just like wires.

**Comment by HbmMods** [comment]
That's because batteries do act like wires now. It makes setups with large clusters of batteries easier because they can simply be placed next to each other without the need for an additional row of wires connecting them.
