### ISSUE TITLE
Schrabidium missle drops stone shell.

### ISSUE THREAD

**Issue by MrKimkimora** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1519]
Launched schrabidium rocket. 
Used Howard turret.
After destroying dropped this. 
I can't reproduce it.
![Screenshot_20240602_000201](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/144221261/781114e5-8c31-4882-8b15-ef27ef9fafb1)
(translation: stone shell)

**Comment by HbmMods** [comment]
Found the issue, the missile debris spawner creates new ItemStack instances ignoring both stack size and metadata instead of simply copying the stack like it should.
