### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by DamondSword2247** [HbmMods/Hbm-s-Nuclear-Tech-GIT#152]
Not an issue but this is the only way I could think to get a response.

I can seem to get version 1.0.27_X3808 to load in the mod order am I doing something wrong? Forge doesn't seem to want to acknowledge its existence. I'm using OverWolf Curseforge.

**Comment by HbmMods** [comment]
I have no idea what OverWolf Curseforge is but it sounds a lot like one of those weird launchers that only download mods from curseforge. The past couple releases aren't on there and it will take some time until I can upload to curse again, in the meantime either install the mod manually or consider using a better launcher.

**Comment by IbramGaunt28** [comment]
afaik overwolf is officially partnered with curseforge after it is no longer on with twitch. but you can select the open folder option and adjust the version of ntm yourself.

**Comment by HbmMods** [comment]
Then I don't see any real reason why it shouldn't work. Could be a mod conflict or some general wonkyness of the launcher, but that would usually manifest in a crash instead of the thing outright not loading. Did you perhaps download the zipped source code instead of the jar file on accident? Perhaps it uses a very old version of forge?

**Comment by DamondSword2247** [comment]
I made a new pack with the latest forge with NTM being the only thing in the pack but forge doesn't see it when loading mods

**Comment by IbramGaunt28** [comment]
which mc version are you using? ntm is for 1.7.10. also make sure to put it in the mods folder and to restart the launcher. i am using overwolf myself since multimc isnt working on my computer dor some reason. and for me it works

**Comment by DamondSword2247** [comment]
1.12.2... I thought this was the Github page for the 1.12.2 port... I'm an idiot.

**Comment by HbmMods** [comment]
This isn't exactly the first time that has happened, I suspect it's because Drillgon put a link to this version's release page into his version's release page and since the pages look identical, people end up downloading the wrong version.

**Comment by DamondSword2247** [comment]
I'll delete the issue if I can if not I'll close it.
