### ISSUE TITLE
Low priority enhancment: high temperature RBMK heat exchanger

### ISSUE THREAD

**Issue by Bencek123** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1523]
This heat exchanger would be able to use high temperature coolants like liquid sodium and fissonable liquid coolants like liquid thorium salt

Just a small thing i would like to see and it may also add some new RBMK desings chanlanges that are interesting

**Comment by HbmMods** [comment]
Liquid sodium was only as good as it was because of the RBMK's different cooling implementation, causing sodium to *dupe* heat. A fixed version would most likely be pretty bad coolant, since it can only cool as much as the boiling/heating point of the fluid is.
