### ISSUE TITLE
High-Speed Steel Pipe Anvil Bug

### ISSUE THREAD

**Issue by PeanuteBJellytime** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1526]
High-Speed Steel Pipes can be crafted in an anvil, but it's only available in level 1 anvil's.

**Comment by HbmMods** [comment]
![grafik](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/16674258/d6d59476-cc83-4ab0-b78f-5ee75acf1b66)

Seems to work fine, all pipes use the same autogen code after all.

**Comment by PeanuteBJellytime** [comment]
Oh whoops you right it does i'm just actually blind apparently lol.
