### ISSUE TITLE
please buff sulfuric acid

### ISSUE THREAD

**Issue by ecstxasy** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1528]
i love automation especially in this mod but the #1 bottleneck is always sulfuric acid as there is no sulfur bedrock ore (except for the fragments which are a even worse source than sour gas) and getting it from sour gas is extremely annoying and inefficient

**Comment by HbmMods** [comment]
Sulfuric acid was buffed last week, I just forgot to mention that in the changelog. It now yields 4x more and just needs an extra 1000mB of water with the standard chemplant recipe.
