### ISSUE TITLE
NEI doesn't work.

### ISSUE THREAD

**Issue by Misha600** [HbmMods/Hbm-s-Nuclear-Tech-GIT#153]
This probably isn't the right place to ask, but i've followed all the steps to get the latest version and everything seems to work fine, but NEI doesn't. I'm pretty sure it's supposed to be bundled in with the completed JAR but when i press the key that's supposed to be bound to open the NEI GUI it doesn't do anything. I've probably royally screwed up compiling it but I thought i did everything right. There was also an error in the logs. I attached both the JAR and the log in case it helps. Thank you.

https://drive.google.com/file/d/1sAoPQDNi6OF24JH0ESLTtrBZ3HWBvz-W/view?usp=sharing

[2021-03-18-1.log](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/6167979/2021-03-18-1.log)

**Comment by HbmMods** [comment]
The NEI dependencies for building the project give it NEI *integration*, i.e. allowing you to see machine recipes. You still have to install NEI yourself.
