### ISSUE TITLE
FEnSU does not charge above 10 PHE

### ISSUE THREAD

**Issue by MrKimkimora** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1534]
I am running on 4963 version.
the same in the newest one.

FEnSU does not charge above 10 PHE (voids energy?).  Only in green mode.

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/144221261/e76840a1-230e-498d-9619-d786053899ea

I disconnected all providers (except spark ES), tried.
I disconnected all receivers, tried.
I disconnected both of them at the same time, tried.
In all that cases it voids energy above 10 PHE. 

I will give more information if needed.

**Comment by MrKimkimora** [comment]
528 and expensive mod are enabled.

**Comment by Bencek123** [comment]
I migth try this and see what happenes on my side 

Also may i ask what font do you use?

**Comment by MrKimkimora** [comment]
> I migth try this and see what happenes on my side
> 
> Also may i ask what font do you use?

![изображение](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/144221261/cead1f28-7c90-4f53-ac1a-fcee99153569)

**Comment by MrKimkimora** [comment]
![изображение](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/144221261/3b462cfd-d74b-4ed1-ba49-5756acfbdfa5)
Just tested it again with PURE ntm (absolutely no other mods, only ntm)
The one at right side is charged up to 10 PHE and in green mode. They are connected by cable.
![изображение](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/144221261/19c1acf4-ca35-4802-931e-0a0c70f29ef1)

mod version: 4991

**Comment by TheVitya2127** [comment]
Hm.

**Comment by zmx945** [comment]
I've come across cases where the source code limits the energy transmission limit of fensu

**Comment by zmx945** [comment]
I've been in this situation before. The reason is that the source code limits the upper limit of the energy transmission of the fensu.
