### ISSUE TITLE
Bug: Breaking WATZ ate almost all of my bolts

### ISSUE THREAD

**Issue by rattlemebones1** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1537]
Version: 4977

I know I'm outdated, the host insists on not updating it yet. Anyway, I was making my WATZ reactor room and decided to move it to expand the room more. I went to break it, and:
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/109101492/5a2da127-a693-4f0a-96e3-ac1e2784d61b)
this is what I got back.
I'm gonna ask the owner if I can cheat in the bolts back, but I don't want this to be a permanent solution.

**Comment by HbmMods** [comment]
Found the issue, during the transition to the new bolt items, the stacksize was lost, it was supposed to drop three stacks individually, now it only drops three single items.
