### ISSUE TITLE
control units not found inside certain WMD recipes

### ISSUE THREAD

**Issue by Jundix22** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1538]
Considering control units were added in the recipes of all nuclear devices, i came across a few recipes that haven't changed, mainly the custom nuclear warheads sizes 10, 15 and 20

![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/165779754/23fa642f-64b5-4c03-84e3-527902aa4fb4)

Tested in x4991

**Comment by HbmMods** [comment]
None of the custom missile part recipes were updated because custom missiles will be reworked soon enough anyway.
