### ISSUE TITLE
Artifice overwrites Sulfur Blocks with its ore variant 

### ISSUE THREAD

**Issue by brandyyn** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1546]
Artifice overwrites Sulfur Blocks with its ore variant, Artifice is abandoned so it has to be fixed on HBM NTM's side, for reference, I have sulfur blocks disabled in Artifice.

![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/11356565/21e72a95-c1d0-4f32-971a-4253f23e896a)

![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/11356565/5db5ce0e-38c5-408b-935e-f5d05bce6b47)

**Comment by HbmMods** [comment]
Not a whole lot I can do about it I'm afraid, if Artifice generates their ores after mine and has the generation target defined loosely enough to overwrite sulfurous rock then there's no real way of preventing that. Plus, NTM sulfur still generates so it's not a gamebreaking issue either.

**Comment by brandyyn** [comment]
> Not a whole lot I can do about it I'm afraid, if Artifice generates their ores after mine and has the generation target defined loosely enough to overwrite sulfurous rock then there's no real way of preventing that. Plus, NTM sulfur still generates so it's not a gamebreaking issue either.

I assume the sulfur rock likely has some sort of ore tag associated with it, would it be possible to remove that tag within the block?

**Comment by HbmMods** [comment]
Yes, and that would break all the recipes and compat for the sulfurous stone, so that's not an option.
