### ISSUE TITLE
Crash with the new PRISM system

### ISSUE THREAD

**Issue by Darek505** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1547]
**[pastebin.com](https://pastebin.com/fjVVAuvH) | [mclo.gs](https://mclo.gs/P1S6Xkd)**

version - 1.0.27_X4998 

Happened by accident, I just placed radioactive blocks and blocks with blast resistance. The last thing I place before the crash was a plutonium-238 block; immediately after I place it, game crashed, although I’m not sure if it’s related. 

The crash says that there is a problem with the iterator or something like that 

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/blob/dda1025fe261a480dbc7835b6085c305cf0dfa0a/src/main/java/com/hbm/handler/radiation/ChunkRadiationHandlerPRISM.java#L223-L225

**Comment by HbmMods** [comment]
The crash is already known, I was hoping i could weasel around concurrent modification issues by using an iterator, and it looked like it worked in the test world (it did not). I added a separate map for new additions, fix should be out sometime this week.
