### ISSUE TITLE
auto update / version manager ?

### ISSUE THREAD

**Issue by ecstxasy** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1549]
this mod updates extremely often, and not just like basic bug fixes/changes but very often it will add completely new features and i will just forget to check the github so it would be really cool if like you were on an old version it would tell you that there is a new update and what comes with the update so you can decide if you want it or not

**Comment by HbmMods** [comment]
The mod already tells you about new versions when you join a world, it even comes with a "click here" hyperlink that takes you to the changeog/download link.

**Comment by ecstxasy** [comment]
okay i guess im stupid but i want to ask is there any equivalent of methane pyrolysis? like just heating methane with no oxygen for a bunch of hydrogen electrolysis is really slow

**Comment by HbmMods** [comment]
No, but something like that is planned.

**Comment by ecstxasy** [comment]
is there a better place i can post suggestions? or should i still use issues

**Comment by HbmMods** [comment]
Suggestions are generally not accepted.
