### ISSUE TITLE
Custom Machine Crash

### ISSUE THREAD

**Issue by CoolDude10123** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1552]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.

I am running version X4998 of the mod. Every time I place down a Custom Machine block such as the paper press or one of my own, it kicks everybody on the server, and says "A fatal Error has occurred". After checking the server console to see the problem it shows nothing of significance.

**Comment by rattlemebones1** [comment]
sounds like it crashed, can you check  if theres a crash report in the crash report folder?
if there is one, please send it here for the people who can read those

**Comment by CoolDude10123** [comment]
No one's minecraft actually crashed, it just booted everyone from the server. When i have custom machines on the server's config folder is all players who play on the server required to have the custom machine JSONs in there configs?

**Comment by rattlemebones1** [comment]
i was referring to the server itself crashing
and you should always give config files to other players if you changed them

**Comment by HbmMods** [comment]
Custom machine configs as well as recipe configs have to be shared between server and client, otherwise bad things are going to happen.
