### ISSUE TITLE
Bug: Night vision goggles drain power only from the helmet, instead of the entire suit

### ISSUE THREAD

**Issue by rattlemebones1** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1553]
Version: 4991

How to produce this: Equip NVGs to powered armor. Have not tried it on anything other than HEV, so it could be HEV only.

I do not believe its supposed to do this. If it is, feel free to tell me otherwise.

**Comment by HbmMods** [comment]
Using only helmet power is intended.
