### ISSUE TITLE
This stupid cancer mistake of mine cost me my life.

### ISSUE THREAD

**Issue by TheVitya2127** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1554]
I thought it was a good idea to stick 8 AE cells with 200000 Rad/s into steel crates, break them and put them in a containment box. The result did not wait. Now, other than completely clearing the inventory, there is no other way to solve the problem, because the server would not let me in. The server constantly kicks me out of the server. Perhaps the NBT is broken.

Version: X4991

**Comment by gmhs022** [comment]
You overflowed the NBT data and essentially bookbanned yourself, it's not a bug NTM can fix because it's literally an issue in vanilla Minecraft.

**Comment by TheVitya2127** [comment]
It might be possible to somehow issue a notification that the NBTs are full, as was done with the crate. When the NBT overflowed, they simply broke and scattered items. I will close this issue since it cannot be solved and this is mostly my mistake than NTM’s mistake
