### ISSUE TITLE
RF to HE converter is an infinite energy source

### ISSUE THREAD

**Issue by leytilera** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1555]
When the RF to HE converter is directly connected to a machine/storage, it works as supposed, but when connected to a cable, it is an infinite energy source, as it does not consume any RF. To fix this the energy should be transfered through the cables before the receiveEnergy method returns, otherwise the returned value assumes, that no energy was transfered.

**Comment by HbmMods** [comment]
I can't exactly replicate this behavior, in fact I'm seeing the opposite, the leadstone energy cell will start draining energy and never stop, even when i remove the converter.

**Comment by leytilera** [comment]
> I can't exactly replicate this behavior, in fact I'm seeing the opposite, the leadstone energy cell will start draining energy and never stop, even when i remove the converter.

Do I understand this correctly, that the leadstone energy cell looses energy, even if it is not connected to anything?

**Comment by HbmMods** [comment]
Correct

**Comment by leytilera** [comment]
Strange, seems like a bug in Thermal Expansion. Have you tried this with other RF energy sources?

**Comment by leytilera** [comment]
For reference: [pccompat#16](https://git.tilera.org/Anvilcraft/pccompat/issues/16)

**Comment by TheChosenIndividual** [comment]
Oh this has happened before to me!, i can vouch for the fact that it constantly consumes energy, in fact i think i made an issue about this way too long ago, anyways just put switches between your energy source and the converter when you're not using it

**Comment by HbmMods** [comment]
Converters have been reworked to act as buffers again, this should also fix any issues caused by the new energy system with energy either being duped or destroyed.

**Comment by Square2Cat** [comment]
The main issue I have with the converter is that it is an infinite energy sink. Meaning all my power gets sucked into it with no limit and the diode can do nothing to stop this. It should be draw based or have a capacity.
