### ISSUE TITLE
make destroying your entire world optional for osmiridium

### ISSUE THREAD

**Issue by ecstxasy** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1559]
i would like for there a way to not destroy the world to have osmiridium, while still being just as hard to obtain. the explosion is unplayable on servers and i have never been able to finish the explosion. (even in singleplayer worlds) i assign my client 8gb and my server 12gb for context

**Comment by HbmMods** [comment]
NTM has recipe configs for almost every machine as well as a config system for adding your own custom multiblock machines, you are of course free to add alternate recipes for osmiridium.
