### ISSUE TITLE
having the issue of the latest pre compiled version from the github not running in 1.7.10 forge

### ISSUE THREAD

**Issue by lag145** [HbmMods/Hbm-s-Nuclear-Tech-GIT#156]
i tried running it on the latest reccomendet version of forge as of mar 23 2021 it dosent have any dependencies to run in 1.7 correct if i missed an dependency tell me and colose this or if you arent andev and you cnat close it tell me thati forgot something and i will install it look and if it works ill close this

**Comment by pbk20191** [comment]
Create fork from my github then merge fork of mine with hbm's update. Finally use that repos to compile and build hbm nuke.
