### ISSUE TITLE
Too powerful mini nuke (high yield)

### ISSUE THREAD

**Issue by R-Kaenbyou** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1560]
Version 1.0.17 X5000
During this version, I found out that the mini nuke (high yield) is too powerful so that it is extremely imbalance.
During testing, it can kill player who wear euphemium armor or player who wear DNT nano suit.
But the mini nuke (high yield) is extremely cheap while comparing to euphemium armor or DNT nano suit.
Thus, it is probably too imbalance, so it may be good to make mini nuke (high yield) weaker than now.

**Comment by HbmMods** [comment]
Likely due to the gamma flash bypassing radiation resistance, I'd say small nukes like that shouldn't have a flash at all.
