### ISSUE TITLE
NotEnoughResources compatability?

### ISSUE THREAD

**Issue by Bratorsortnal** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1561]
Maybe add a compatability for modded ores in NER?

**Comment by HbmMods** [comment]
Couldn't find the NER files in any of the maven repos to add direct compatibility, and the built in IMC compatibility thing they have lacks documentation and I couldn't get it to work after a couple hours of work, so unless the devs respond to the issue i opened on their repo, I don't see compatibility for NER happening.
