### ISSUE TITLE
electric arc furnaces cause horrible tps

### ISSUE THREAD

**Issue by ecstxasy** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1566]
its as simple as the title
in the video you see me setting all the arc furnaces to air and theres obviously a lag spike but i am reffering to before i even ran the command. the pigs ai are slow and jittery but the second i remove all of them and the command is done, the pigs are back to normal

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/82160421/1bfa3ef1-83b9-4da6-949e-4dad5e11402c

**Comment by HbmMods** [comment]
Could you run a profiler? That would narrow the issue down to the exact part of the arc furnace that causes the lag spike. [Spark](https://www.curseforge.com/minecraft/mc-mods/spark/files/4271867) for example is a pretty good one

**Comment by ecstxasy** [comment]
https://spark.lucko.me/VFiJlllbv1

**Comment by HbmMods** [comment]
Yup that's the inserters, they had a similar issue for some other machines too. Shouldn't be terribly hard to fix.

**Comment by ecstxasy** [comment]
what can i do in the mean time to like insert stuff into them because i remember only using them because the thermal dynamics pipes wouldnt insert into the arc furnace so i made them insert into the inserter

**Comment by HbmMods** [comment]
Slowing down the insertion speed would work, you can probably do this by butting a hopper between the arc furnace and the inserter since hoppers only transfer a single item per second. It's gonna make your furnaces way less efficient though.

**Comment by ecstxasy** [comment]
can we have lubricated foundry channels..? pleaseeeee or is there a config option to make them faster

**Comment by HbmMods** [comment]
Arc furnaces have recipe caching now so all operations that need to resolve recipes (i.e. the furnace's own ticks as well as anything that transfers items into it) should be much faster now.
