### ISSUE TITLE
power gauge shows the current energy stored in FEnSU

### ISSUE THREAD

**Issue by Bencek123** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1570]
the title is basicly what is happening but it migth be do to me useing the power poles to transmit the output from my leviathan turbines

**Comment by Goaty1208** [comment]
Having the same issue with cabled connections while the FEnSU is in any discharging mode. Not sure whether or not it's a bug though.

**Comment by HbmMods** [comment]
Likely caused by the same bottlenecking issue as #1534, I'm leaving the issue open for now.
