### ISSUE TITLE
Enhancement: Sodium Ingot and Strontium Ingot

### ISSUE THREAD

**Issue by R-Kaenbyou** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1572]
In 1.0.27X5020, sodium and strontium are both valid material that can be molten in crucible. But it is not possible to change foundry scraps of sodium and strontium into sodium powder and strontium powder because there is no something like sodium ingot or strontium ingot in the mod.
Please add those two items into game. I really need to change my foundry scraps of sodium into liquid sodium for my ICF and change the foundry scraps of strontium into strontium powder for craft atomic clocks. (I used electric arc furnace to process byproducts)

**Comment by Ilikepotatochips** [comment]
there is a strontium-90 ingot
