### ISSUE TITLE
Advanced Rocketry mod support

### ISSUE THREAD

**Issue by Zscreeper** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1573]
Hi, I want to know if it is possible to support the Advanced Rocketry mod in HBM NTM. Advanced Rocketry is a very good mod for space and I would like you to try it so that it can be integrated into HMB NTM

**Comment by Goaty1208** [comment]
What would this support look like?

**Comment by HbmMods** [comment]
Could you be a bit more specific because "support" can mean a lot of things

**Comment by Zscreeper** [comment]
![image](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/130389090/13f51981-7d15-427f-85fa-9f992b4ad02f)
approximately the same integration as in the Mekanism mod in the screenshot below, the complexity of crafting through components from HBM NTM

**Comment by HbmMods** [comment]
I don't know enough about AR to add integration recipes, nor is that the point. You are of course free to add your own recipes via the configs.
