### ISSUE TITLE
Enhancement: Sulfur cave and Asbestos cave should not replace blocks in natural formed structures

### ISSUE THREAD

**Issue by R-Kaenbyou** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1574]
Please don't let this happen again
![QQ图片20240709180338](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/152870189/096ec3b7-3d94-4dc8-9a0a-db0535f334fd)

**Comment by HbmMods** [comment]
What version are you running? That was supposed to be fixed ages ago.

**Comment by R-Kaenbyou** [comment]
> What version are you running? That was supposed to be fixed ages ago.

The version is 1.0.27X5000, seed 8020683010578053705, position (x:570 z:1075)

**Comment by HbmMods** [comment]
Looks like this on my end

![2024-07-17_08 56 19](https://github.com/user-attachments/assets/ee1ceef4-ddb6-4039-a55f-1bcabbe21326)

Are you sure you didn't generate the world with an older version?
