### ISSUE TITLE
turning off 'generate structures' still causes hbm structures to generate

### ISSUE THREAD

**Issue by ecstxasy** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1575]
im trying to build something for later and sometimes the structures are simply just in the way. i can turn off generate structures but the hbm ones will still remain

**Comment by HbmMods** [comment]
What version are you on and what toggle did you use for disabling the structures? The config or the world generation option?

**Comment by ecstxasy** [comment]
im on the latest hbm version and mc version 1.7.10 and i did through the world generation options

**Comment by HbmMods** [comment]
By default, the structure config will ignore the world generator options, you can change this by setting `1.03_enableDungeonSpawn` as well as `5.00_enableStructures` to `flag` in the config file, this will make the structure setting depend entirely on the world generator options.
