### ISSUE TITLE
The nuclear mini-charges are broken

### ISSUE THREAD

**Issue by TheVitya2127** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1579]
It seems to me that mine nuclear weapons work strangely. The green color raises fewer questions than the MIRV Mini-Charge
![2024-07-13_07 08 37](https://github.com/user-attachments/assets/7a999da3-9863-4146-b8f6-5e6ea0439a56)
![2024-07-13_07 07 13](https://github.com/user-attachments/assets/f268885f-c3a5-473e-936b-a11d4ee7e28e)
![2024-07-13_07 09 28](https://github.com/user-attachments/assets/155a0161-f8a5-4ce9-9ffb-8194d4a10ced)

**Comment by TheVitya2127** [comment]
![2024-07-13_07 11 12](https://github.com/user-attachments/assets/cfce297e-5ee5-415c-9b48-85881c29d246)

**Comment by HbmMods** [comment]
Could you please elaborate because I don't know what the issue is supposed to be.

**Comment by TheVitya2127** [comment]
Explosion green.

**Comment by TheVitya2127** [comment]
And what is the difference between Mini nuke and Mini MIRV?

**Comment by HbmMods** [comment]
Explosions being green either happens at a 1% chance or if the polaroid is broken. The difference between mini nukes and MIRVs is that MIRVs will split into 6 mini nukes after about a second in the air.

**Comment by TheVitya2127** [comment]
I'm probably just stupid and should close this issue. Thank you
