### ISSUE TITLE
turrets dont ignore ascending missiles?

### ISSUE THREAD

**Issue by ecstxasy** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1580]
simply put my maxwell turret just laser beams my custom missiles when they leave and its like ouch thats alot of resources down the shitter but its an 'easy?' fix by just turning off targeting machines however i think the turrets should at least not target the missiles of whoever is whitelisted on them or they could be smart like the radar. just a nitpick i guess not a huge deal

**Comment by HbmMods** [comment]
With X5026, turrets should now ignore missiles unless they have downwards momentum
