### ISSUE TITLE
if a ZIRNOX reactor is placed into a 4 block tall space, the reactor will still place and annihilate the 5th layer of blocks in the way, including blocks such as bedrock

### ISSUE THREAD

**Issue by ifofa** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1581]

**Comment by ifofa** [comment]
after more testing, it seems that as long as there is a 2 block tall space and a 5x5 area to place the zirnox, the reactor will just obliterate anything in it's way

**Comment by HbmMods** [comment]
Fixed in X5026.
