### ISSUE TITLE
Crash caused by IF - Tossable Brimstone Mine launched by Vanilla Dispenser

### ISSUE THREAD

**Issue by R-Kaenbyou** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1582]
When an IF- Tossable Brimstone Mine launched by vanilla dispenser explodes, the game crashed.
The crash report is in here.
[错误报告-2024-7-13_11.04.18.zip](https://github.com/user-attachments/files/16215448/-2024-7-13_11.04.18.zip)

**Comment by HbmMods** [comment]
Fixed in X5026.
