### ISSUE TITLE
infinite energy bug

### ISSUE THREAD

**Issue by Zscreeper** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1583]
just watch the video

https://github.com/user-attachments/assets/7096309c-262d-4a5e-b2bc-8bd9eb4f5042

**Comment by Zscreeper** [comment]
the latest version of the mod is playing on the server

**Comment by HbmMods** [comment]
Fixed with X5026, energy transfer now has compensation for rounding errors, preventing leftover energy from building up.
