### ISSUE TITLE
NBT data causing stacking and crafting issues

### ISSUE THREAD

**Issue by LEGOmanbig2003** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1587]
HBM-NTM-[1.0.27_X4998], the NBT tag {ntmContagion:1b} causes items to not stack properly and become useless in crafting

**Comment by HbmMods** [comment]
I'm afraid you now have bigger problems than not being able to stack things

**Comment by LEGOmanbig2003** [comment]
yeah i figured that out last night, didnt know what that item did lol, still a bug though. Wiki says MKUnicorn should only affect unstackable items

**Comment by HbmMods** [comment]
> Wiki says MKUnicorn should only affect unstackable items

That's incorrect, and it would be kinda weird if it did.

**Comment by LEGOmanbig2003** [comment]
![wiki](https://github.com/user-attachments/assets/261bb14e-7fe0-44ba-a50b-bdd7f01ae331)
wiki is incorrect then
