### ISSUE TITLE
Missing structures in config file

### ISSUE THREAD

**Issue by VladSog** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1588]
Why in config file in structures missing two positions: 4.07 and 4.08?
It is marked on this image:
![image](https://github.com/user-attachments/assets/983c9a6a-2684-4d81-903c-adeafc9098ad)

**Comment by HbmMods** [comment]
Those were the silo and the bunker, those no longer use the old structure system and therefore none of the old configs.
