### ISSUE TITLE
I also have such a problem  #1503 reference

### ISSUE THREAD

**Issue by Zscreeper** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1589]
#1503
but here not only with a helmet of the liquidator, but also with a helmet in which gas masks are built in, and with gas masks with filters installed
![image](https://github.com/user-attachments/assets/411cc7b9-f14d-4207-af5b-4ea4cb03e918)
![image](https://github.com/user-attachments/assets/e3c49c0f-92dd-47e3-9ca9-30ab39829e20)
![image](https://github.com/user-attachments/assets/32788d3a-9ae7-4035-8a39-3ad4930a42aa)
![image](https://github.com/user-attachments/assets/c1150957-0054-449e-aafd-56add43382f4)

**Comment by Zscreeper** [comment]
I found a mod that causes this problem, it's called Show Durability (a mod that shows the durability of weapons, tools and armor)

**Comment by HbmMods** [comment]
Why would you even need a mod like that when vanilla literally already shows durability?

**Comment by Zscreeper** [comment]
it is more convenient for me to see a numerical value than an incomprehensible strip or go into the inventory to see how much strength is left
It is very nice that you respond quickly

**Comment by HbmMods** [comment]
![image](https://github.com/user-attachments/assets/1617e3b7-b700-4f68-b641-63e3fea2abf6)

That is part of vanilla's F3+H display, which you appear to have enabled anyway. Durability is now listed twice.

**Comment by Zscreeper** [comment]
Well, sometimes I need to see how much strength I have in my inventory, I won't look away to the lower right corner of the screen every time.
and besides, I'm not looking at the strength, but the name of the subject in English

**Comment by HbmMods** [comment]
In either case there's not a whole lot I can do about it, you might want to report this to the Show Durability devs assuming that mod is still supported.
