### ISSUE TITLE
Wither wkeletons drop wrong type of coal with decapitator

### ISSUE THREAD

**Issue by TehTemmie** [HbmMods/Hbm-s-Nuclear-Tech-GIT#159]
Killing a wither skeleton using a weapon with the decapitator ability drops coal with a metadata value of 3 instead of normal coal, which has a metadata value of 0. This only applies to the "bonus" coal from decapitator.

**Comment by HbmMods** [comment]
It seems like I confused metadata with stack size again. Should be resolved in the next update.
