### ISSUE TITLE
Code Question

### ISSUE THREAD

**Issue by A-Boring-Square** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1590]
In the file EntitySpear.java 

```
@Override
	protected void readEntityFromNBT(NBTTagCompound p_70037_1_) { }

	@Override
	protected void writeEntityToNBT(NBTTagCompound p_70014_1_) { }
```

what is p_70037_1_ and where is it defined

**Comment by JameH2** [comment]
Obfuscated naming, also since its in the nbt method the “ p_70037_1_ “ is just the name of the field, you can use it to read/write to nbt (save to the game)

**Comment by A-Boring-Square** [comment]
Thanks
