### ISSUE TITLE
Enhancement: Forge Multipart support for cables

### ISSUE THREAD

**Issue by LekKit** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1591]
Some other mods implement Forge Multipart interop for their cables. This allows placing a cover around the exposed cable, similar to cable facades (but without the need to implement actual facades yourself).
Additionally, this allows to separate cable connections that are otherwise in direct proximity to each other.

![2024-07-20_14 49 32](https://github.com/user-attachments/assets/d4579c4f-33c1-4814-be6c-a43c0874f505)

I might implement this myself if others agree this is useful, but I need to figure out the multipart API first, and will try this on my own mod beforehand.

**Comment by gmhs022** [comment]
There's already a way to effectively add facades over cables, that being the paintable cables, the only difference is the small dot in the center to show where it actually lies, I'd suggest putting the actual cables a block below the floor and using paintable cables for when they go between the layers.
I kinda doubt FMP support would be added, it's quite an old mod and with age comes jankiness that is annoying to implement and can lead to weird bugs.
