### ISSUE TITLE
no way to launch lunar mining ship

### ISSUE THREAD

**Issue by okkookko2** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1595]
when i put the lunar mining ship in the soyuz satellite spot it doesnt let me launch but if i put any other satellite in the same spot i can launch. everything is checked as ready and i can even launch the asteroid mining ship

**Comment by A555552** [comment]
you need to put lunar mining ship in satellite slot
and under the satellite slot you need to put orbital module
