### ISSUE TITLE
Sentry turret "Brown" Missing a recipe

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1598]
When preparing for a new survival series video, i was debating on the topic of automated home defense, and eventually arrived at sentry turrets, however, upon checking the recipes, i realized that the sentry turret "Brown" was missing a recipe, when pressing R in NEI no recipe shows up, neither does any assembly template when searched for in both minecraft creative and NEI, when i built and tested the turret, it worked fine, is this a bug? or is it intentional?

-Chosen

**Comment by HAJONK** [comment]
Yeah, I have noticed that as well in my own survival world. Im subbed, so i will be watching the survival series when it comes out
