### ISSUE TITLE
Add scorched Bedrock + scorched non-radioactive stone variants for large explosions

### ISSUE THREAD

**Issue by The-Explosive-Chemist** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1604]
This isn't a bug or issue but instead a suggestion.

Basically it really annoys me when I create a huge explosion and I just see plain bedrock on the bottom.
It really doesn't match the colour of the sellafite. 
So that's where scorched bedrock comes in. It would be very similar aesthetically to sellafite, but only the texture would be different from normal bedrock. There would also be a radioactive version from nuclear explosions.

Also, for non-nuclear weapons (i.e. the N₂ mine) add a scorched rock variant (almost like a non-nuclear sellafite) to also increase realism and immersion.

**Comment by Hacker6400** [comment]
I like that idea

**Comment by fbfnysnshnsgnwg** [comment]
seems it was added in latest version as sellafite bedrock

**Comment by The-Explosive-Chemist** [comment]
> seems it was added in latest version as sellafite bedrock

That's great to hear! The bedrock texture always annoyed me, and since it was added I feel great joy.

**Comment by fbfnysnshnsgnwg** [comment]
Actually it was X5057, but it does say it exists
