### ISSUE TITLE
1.12.2 Release?

### ISSUE THREAD

**Issue by daniel8hun** [HbmMods/Hbm-s-Nuclear-Tech-GIT#161]
Hello to whoever is reading this.
i have recently started to play minecraft with this mod and its great, but
my only problem is that MC 1.7.10 doesn't run very well on my pc. (lag spikes every 5 seconds)
but the twist is that 1.12.2 doesn't.

And i know this mod currently has a 1.12.2 version, but its not up to date unfortunatly.
Im not trying to rush you on anything, this is just a simple question.

Thanks for your reply.

**Comment by sendhelppls213** [comment]
There is a 1.12 port on github that is just slightly behind 1.7. The developer of the 1.12 currently has other stuff to do, but sooner or later he will update the port. Also the 1.7 lagspike is something I never heard about and we can probably help you out in the discord.

**Comment by daniel8hun** [comment]
Thank you for the help.
