### ISSUE TITLE
Enhancement: Can we have an RBMK fuel crane extension feature for directly storing spent fuel in spent fuel pools?

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1612]
I realized a long time ago that there was no way to get a hot, extremely radioactive fuel rod, out of the reactor, and into a spent fuel pool without having to manipulate it yourself, which can be a hassle for people with weak radiation protection, or lack of fireproof status, as such, i propose extending the range of the fuel crane, to fit a fuel pool somewhere close by, and being able to lower a secondary arm of the crane to insert the spent fuel in the drums, maybe it could even have a configurable range via machine config, plus, it would be more realistic, since operators dont actually handle fuel rods in real life

-Chosen

**Comment by gmhs022** [comment]
You can transport RBMK fuel in and out of storage columns using hoppers or conveyors, then transport them to a spent fuel pool using those means, I'd suggest just designating an input and output storage column and using the crane to shift rods between them and the fuel columns.

**Comment by TheChosenIndividual** [comment]
> You can transport RBMK fuel in and out of storage columns using hoppers or conveyors, then transport them to a spent fuel pool using those means, I'd suggest just designating an input and output storage column and using the crane to shift rods between them and the fuel columns.

Yeah i know, its just, in my experience it is WAY more difficult than if there was a way to just put them in straight, since without mods like thermal dynamics (which are buggy at times) its basically a long line of hoppers or conveyors that often dont look great and take up way too much space, and are expensive, maybe we could re-balance the crane if having that extra functionality makes it op or something, like make it the crane controller plus an item that is crafted with steel and motors and stuff, but thats just my two cents

**Comment by HbmMods** [comment]
nah, conveyors connecting the fuel pool to the storage columns already work, and so do drones
