### ISSUE TITLE
HE to RF converter 1/5-ing HE input

### ISSUE THREAD

**Issue by slasherforce** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1613]
### HE to RF converter error

So basically the HE to RF converter provided by NTM is making the output 1/5 rather than multiplying it by 4x (if i remeber that is what its supposed to be) the version im on is X5036 
![Screenshot 2024-08-03 150300](https://github.com/user-attachments/assets/1d3adcf7-da3b-4eb0-b554-43cca697c11c)
that screenshot is how much RF is made after putting 5khe inside the converter
EDIT: fixed it by modifying the configs, i dont know if it was orginally supposed to be 4x the rf or not, i was just going by the wiki page: https://ntm.fandom.com/wiki/Converters
modlist of used client:
NTM X5036
Better Builder's wands
Bibliocraft
Codechickencore
Cofh core
ezstorage
lunatriuscore
MCheli overdrive
mekanism and its tools and generators mod
minefactory reloaded
xaero's minimap and world map
and schematica

**Comment by gmhs022** [comment]
This was recently changed, 1 RF is now equal to 4 HE, and converters now have a small idle cost, so converting HE to RF is now farr less efficient.

**Comment by HbmMods** [comment]
please for the love of god read the changelog before updating i am begging you
