### ISSUE TITLE
Pipes arent connecting

### ISSUE THREAD

**Issue by ELJOKER900** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1614]
help my pipes arent connecting to my PWR reactor 

Im at the latest version of HBM 1.7.10 , for dont ask me = yes , im using OF but that didnt affect me before.

Video here = 

https://github.com/user-attachments/assets/445df22b-afa9-4dd8-91b3-30a81b364bc2

**Comment by TheChosenIndividual** [comment]
PWR structure is built incorrectly, the texture around the control panel should cover the ENTIRE structure, so long as the structure isnt complete, the pipe will not connect

**Comment by HbmMods** [comment]
Your ports aren't part of the assembled PWR structure so naturally they will not work. Mind the connected textures.
