### ISSUE TITLE
High Minecraft Version

### ISSUE THREAD

**Issue by Hxgfk** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1617]
I'm a big fan of HBM mods, but I haven't been able to work with later versions of Minecraft, such as 1.19.

**Comment by Creeper-banner** [comment]
You can do it by yourself.

**Comment by TheChosenIndividual** [comment]
there are versions of HBM for newer versions of minecraft, they are linked in the main page at the bottom

**Comment by Hxgfk** [comment]
> there are versions of HBM for newer versions of minecraft, they are linked in the main page at the bottom

they haven't been updated in a long time

**Comment by Hxgfk** [comment]
> You can do it by yourself.

but i don't knoe how to make Minecraft mod

**Comment by nightmare2862** [comment]
this mod dont support 1.19 it only supports 1.7.10

**Comment by TheChosenIndividual** [comment]
> > there are versions of HBM for newer versions of minecraft, they are linked in the main page at the bottom
> 
> they haven't been updated in a long time

I mean, yeah, but you can also try other tech mods that also exist in the newer versions
