### ISSUE TITLE
[Enhancement] Foundry outlets liquid blacklist.

### ISSUE THREAD

**Issue by XxSIBxX** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1618]
A blacklist for a specific liquid in the foundry outlets, where specific liquids cannot use a foundry outlet when added to a blacklidt would be very useful.

 I came across a need for this in my attempt at fully automating ore refining, where when I put crystals in a electrolysis machine usually the main green side outputs in ingots, except with rare earth ore crystals that outputs 6 zirconium nuggets. So if I put in 1 rare earth ore crystal, and the foundry mold on the green side is a ingot mold, then I cant put a new crystal in until i manually come in and empty the 6 zirconium nuggets in the ingot mold. But if I just leave a nugget mold there then some liquids just wont output because theres no nugget version of that metal.

Please add this, thank you!!!

**Comment by HbmMods** [comment]
Using foundry scraps on an outlet will set a whitelist filter which only allows that type to pass. With a hand drill, you can invert that filter, turning it into a blacklist for that one type. Filters only support a single material type, but with a cascading setup it should be relatively easy to separate materials and prevent clogging.

**Comment by XxSIBxX** [comment]
Sorry if I just misunderstood your explanation of how it works but, it doesn't appear to work for me. If I right click a foundry outlet with or without a hand drill, it does say that it is "Redstone inverted" but it just appears to block all liquid from coming out, not the expected blocking only the filtered liquid.

**Comment by XxSIBxX** [comment]
@HbmMods Sorry for the mention, haven't gotten a reply to my previous comment, and I really would love to know the situation.

**Comment by XxSIBxX** [comment]
I really would love to know the situation, I'm sorry but if I don't get a reply soon I will be making a new issue.

**Comment by HbmMods** [comment]
> If I right click a foundry outlet with or without a hand drill, it does say that it is "Redstone inverted"

Make sure you have a filter material set first, then shift click with a hand drill which should toggle "Filter inverted".

**Comment by XxSIBxX** [comment]
> > If I right click a foundry outlet with or without a hand drill, it does say that it is "Redstone inverted"
> 
> Make sure you have a filter material set first, then shift click with a hand drill which should toggle "Filter inverted".

THANK YOU SO MUCH IT WORKS

this NEEEDS to be put on the wiki, this makes things so much easier
