### ISSUE TITLE
is it possible to optimize pylons ? (fps)

### ISSUE THREAD

**Issue by ecstxasy** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1622]
when i run a profiler i notice alot of the lag comes from pylons. i dont spam them, i dont even use the quadruple ones. i just have ~15 total wires (3 wires per medium pylon, 1 per regular pylon) and it is the cause of most of my lag. is there anyway to optimize them any better?

**Comment by HbmMods** [comment]
Could you share your profiler results? I use pylons a ton and never noticed any issues

**Comment by ecstxasy** [comment]
https://spark.lucko.me/6HW15EJmp2

**Comment by HbmMods** [comment]
Oh yeah forgot to mention, that should have been fixed weeks ago, pylons now use way fewer unnecessary trig calls and there's a config for reducing the detail on the wires, further reducing lag.
