### ISSUE TITLE
Dineutronium armor incorrectly named

### ISSUE THREAD

**Issue by TehTemmie** [HbmMods/Hbm-s-Nuclear-Tech-GIT#163]
The names of the dineutronium helmet and chestplate are swapped (The helmet is called "DNT Nano Suit Chestplate" while the chestplate is called "DNT Nano Suit Helmet"). Additionally, the leggings are misspelled as "Leggins".

**Comment by sendhelppls213** [comment]
What did you expect from an April fools update?

**Comment by HbmMods** [comment]
The suit was cobbled together in a short amount of time for april fools, you may also notice how it has no radiation resistance and the unique abilities being rather wonky.
