### ISSUE TITLE
crash when playing ManaMetalMod and HBM-NTM

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1630]
when loading, game is crashing:
check the crashlog
https://mclo.gs/nUrej18

**Comment by HbmMods** [comment]
Adding another safeguard to the recipe system for cases like these. The underlying problem is that ManaMetal apparently adds furnace recipes with stacks that have `null` items, this shouldn't ever happen and I'm pretty sure that's gonna cause a lot more problems for things that rely on the furnace system.

**Comment by ghost** [comment]
so i should report that M3 then, and this issue can be closed?

**Comment by ghost** [comment]
lol abyssalcraft integration is also crashing with HBM same issue

**Comment by HbmMods** [comment]
Safeguards should now be in place with the most recent version, please close the issue once you get around testing it.

**Comment by ghost** [comment]
not working, crashing with the same issue

**Comment by ghost** [comment]
however if modpack mods count reach certain point (e.g. 120 mods) hbm m3 and abyssalcraft integtation works fine together

**Comment by HbmMods** [comment]
Do you have the log for the latest crash?

**Comment by ghost** [comment]
i have no internet on pc, but i'll try a bit later

**Comment by ghost** [comment]
[fml-client-latest.log](https://github.com/user-attachments/files/16677266/fml-client-latest.log)

**Comment by HbmMods** [comment]
*Might* be fixed now, please test it to confirm.

**Comment by ghost** [comment]
thanks
