### ISSUE TITLE
Feature request: InventoryTweaks support for crates

### ISSUE THREAD

**Issue by abel1502** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1631]
It would be really nice to be able to sort items in crates with the InventoryTweaks mod, and from what I can tell, it is fairly simple to implement on your side: just add a `@invtweaks.api.container.ChestContainer(rowSize=..., isLargeChest=true)` annotation to the crates' Container classes. Thanks in advance!

**Comment by HbmMods** [comment]
I can't use the annotation without having InvTweaks as a dependency, and I can't add it as a dependency because the [official Maven repo](https://github.com/Inventory-Tweaks/inventory-tweaks/issues/408) seems to be down.

**Comment by abel1502** [comment]
Oh, that's sad(. Would it work, perhaps, to just copy the contents of [ChestContainer.java](https://github.com/Inventory-Tweaks/inventory-tweaks/blob/develop/src/main/java/invtweaks/api/container/ChestContainer.java) into NTM's source, and use it without an explicit dependency? Maybe even exclude that class from the resulting jar, in case a duplicate class causes any problems. Alternatively, maybe you could use [the jitpack.io repository](https://jitpack.io/#Inventory-Tweaks/inventory-tweaks/1.59)?

**Comment by HbmMods** [comment]
Copying the class likely would work, although it's a pretty terrible way of handling dependencies (the RF support for example works like that). I'll try the other repository instead. If all else fails I can still add my own dumbed down version of inventory sorting, the code behind it is really simple.

**Comment by HbmMods** [comment]
Jitpack apparently supplies he jar file by pulling a Github release and then building it, but the build file is outdated and no longer works so it just yields errors. Unless the maven file is hosted somewhere else I am afraid I can't include the dependency.

**Comment by abel1502** [comment]
Actually, it appears the Iron Chests mod uses [an extracted class file](https://github.com/progwml6/ironchest/blob/1.7.10/src/api/java/invtweaks/api/container/ChestContainer.java) since 2014, so maybe it is an acceptable solution

**Comment by HbmMods** [comment]
I think I solved it by including Gregtech's maven repo in my buildscript. I just hope nothing breaks.

**Comment by HbmMods** [comment]
![grafik](https://github.com/user-attachments/assets/9f3dfaf6-cd31-4d72-a125-a8a0d177b0be)

there we go

**Comment by abel1502** [comment]
Oh yes, thank you very much!
