### ISSUE TITLE
missing basic assembly, basic, enhanced, advanced, overclocked, high performance, adaptable assembly and adaptable circuit item texture

### ISSUE THREAD

**Issue by sansfellXD** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1632]
![image](https://github.com/user-attachments/assets/14c03657-59d2-4127-a855-03a3bba07c89)
this is the bug i just found in my survival world (ik, bad idea)

**Comment by Creeper-banner** [comment]
Those circuits have been phased out and removed in the latest release, so this issue is unlikely to be fixed and you should use new circuits.

**Comment by HbmMods** [comment]
Those items literally do not exist anymore
