### ISSUE TITLE
Nuclear Fallout/Radition don't work as it should be (or the system in the new Version just sucks)

### ISSUE THREAD

**Issue by OneX-Developer** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1633]
When i launch a nuke or anything and it explodes it makes the zone to a Biome "crator, inner crator, etc", which has certain radiation settings which i dont like (because the radition dont decays) so i disabled that nuke would change biomes but that removed radiation completly which makes it boring, and nothing else works, i just want it like in the older version (i think) or like its currently in the latest 1.12.2 port, so that it just does the chunk radiation thing, and which just decays over time like irl, and that you can change that too (speed and stuff), but just that its realistic and not needs that biome thing which is PERMANENT and that should not be

**Comment by HbmMods** [comment]
Turning off the part that makes radiation gets rid of radiation, that shouldn't come as a surprise.

You can pretty much restore the old craters by using `hbmFallout.json` (don't forget to remove the underscore), simply replace the inner block conversions to slaked sellafite with regular sellafite.

> but just that its realistic and not needs that biome thing which is PERMANENT and that should not be

I disagree, hence why it was changed

**Comment by OneX-Developer** [comment]
> Turning off the part that makes radiation gets rid of radiation, that shouldn't come as a surprise.
> 
> You can pretty much restore the old craters by using `hbmFallout.json` (don't forget to remove the underscore), simply replace the inner block conversions to slaked sellafite with regular sellafite.
> 
> > but just that its realistic and not needs that biome thing which is PERMANENT and that should not be
> 
> I disagree, hence why it was changed

So i did "hbmFallout.json" so i removed the "_" and enabled should change biomes, so all it did (again) just the ambient radiation but not the chunk radiation at all, then i tried it with change biomes set to false, but yeah that means no radiation at all, so at which version this was changed? so i can get the latest version where that was still available, since the only thing i want at all is that radiation is able to decay like in irl (even tho irl it would take many years)

**Comment by HbmMods** [comment]
> and enabled should change biomes

Why would you enable the permanent radiation thing when you said you didn't want permanent radiation?

> then i tried it with change biomes set to false, but yeah that means no radiation at all

Like I said, use the fallout config to restore the old crater behavior, it's only a matter of having the inner rings be regular sellafite instead of the slaked variant.

**Comment by OneX-Developer** [comment]
> > and enabled should change biomes
> 
> Why would you enable the permanent radiation thing when you said you didn't want permanent radiation?
> 
> > then i tried it with change biomes set to false, but yeah that means no radiation at all
> 
> Like I said, use the fallout config to restore the old crater behavior, it's only a matter of having the inner rings be regular sellafite instead of the slaked variant.

yes, i did the fallout thing i removed the "_" of it, BUT IT DEOSNT work, so ye i thought that that biome thing is wrong, so i did turned it off again afterwards anyways, but no matter what it only went like: there Is permanent radiation or no radiation at all!

**Comment by HbmMods** [comment]
> yes, i did the fallout thing i removed the "_" of it, BUT IT DEOSNT work

And what did you change the config to? Is the JSON format valid? Are there any related error messages in the startup log?

**Comment by OneX-Developer** [comment]
> > yes, i did the fallout thing i removed the "_" of it, BUT IT DEOSNT work
> 
> And what did you change the config to? Is the JSON format valid? Are there any related error messages in the startup log?

no errors, its in the json format, and the config there i just disabled the biomes thing

**Comment by HbmMods** [comment]
May I see the changes you've done to the fallout config?
