### ISSUE TITLE
Suggestion: new uranium bomb , adding neutron bomb

### ISSUE THREAD

**Issue by Uran-228** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1636]
Suggestion: Hello, as I see you have beautiful models of nuclear bombs that were used in real life, so, I suggest you add a new nuclear bomb from real history: MK-18 “King”, and I can also suggest adding neutron bombs, its peculiarity is that the destructive effect is mainly due to penetrating radiation (up to 40% fast neutrons). Thank you for your efforts and work, I wish you all the best, greetings from Russia :)

![IMG_1448](https://github.com/user-attachments/assets/ba0fefaf-02dd-4225-96fe-87023debe89c) -MK-18
“King”

https://www.britannica.com/technology/neutron-bomb - information about neutron bombs

**Comment by HbmMods** [comment]
nah

**Comment by ghost** [comment]
Dude forgot that the blue rinse exists... LOL
