### ISSUE TITLE
Colored concrete crafting recipes bug

### ISSUE THREAD

**Issue by abel1502** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1639]
Colored and Builder's choice concrete variants have recipes to turn them back into regular concrete, but as of now they only accept the first variant of each (i.e. white and industrial tinge).

I'll also sneak in a little suggestion to perhaps replace those two recipes with a more general conversion from `anyConcrete` oredict to regular concrete.

**Comment by HbmMods** [comment]
`anyConcrete` likely includes ducrete and downgrading ducrete into regular concrete would be a bit weird, even if not gamebreaking

**Comment by abel1502** [comment]
That's fair. Then I guess this is just a bug report (about colored and builder's concrete), not an enhancement request

**Comment by abel1502** [comment]
I see it's now fixed, so I'm closing this. Thank you!
