### ISSUE TITLE
Foundry casting basin improvement suggestion

### ISSUE THREAD

**Issue by abel1502** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1647]
It would be nice to be able to extract the mold from a casting basin without having to mine the basin. Maybe by clicking with a screwdriver, or a hand drill, similar to what is done for handling filters on outlets?

**Comment by BallOfEnergy1** [comment]
Suggestions aren't allowed here for the most part.

**Comment by BallOfEnergy1** [comment]
Though iirc the screwdriver can remove molds.

**Comment by HbmMods** [comment]
Screwdrivers can already remove molds, the mold just has to be empty.
