### ISSUE TITLE
Suggestion: add new energy storage

### ISSUE THREAD

**Issue by Uran-228** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1649]
### Discussed in https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/discussions/1648

<div type='discussions-op-text'>

<sup>Originally posted by **DraganBor** August 23, 2024</sup>
As for me, energy storage is an important part of the game, and for my survival situation, lithium-ion batteries are difficult to manufacture, and conventional energy storage is unprofitable. Therefore, I suggest adding sodium-ion energy storage facilities.
Storage description
I think that the volume of energy can be 125-200 MHE maybe
And the craft can look like that:
12 PVC, 16 cobalt powder, 16 sodium
To make an energy storage in an assembly machine, the production time is 7 seconds

Thanks for reading this suggestion :-)
If you like it I can offer another idea 😉
GOOD LUCK! 😎
</div>

**Comment by XxSIBxX** [comment]
Why not just start making your batteries into power cells, or use capacitors and energy blocks? This mod has a ton of energy storage already.

**Comment by HbmMods** [comment]
nah
