### ISSUE TITLE
lets stay relivant with the new times comming and add an item as tribute to almost 20 years since it started

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#165]
Add yet another variation of the Battle Axe Sign, only this one is rare in spawing with zombies, this is to serve as a symbol for those that were around back durring the era of the Old internet, and would be a nice reference to Madness Combat as it is aproaching or is currently 19 years old since the start of it all

The weapon: Tricky The Clowns Battle Sigh
Ref image:
![image](https://user-images.githubusercontent.com/38770780/113488818-6a065980-948e-11eb-8080-ce00cbd1e0e0.png)

**Comment by Shibva** [comment]
as for anything special with it when used by the player is up to the dev(s)

cool visuals would be nice but this is just an idea

**Comment by Shibva** [comment]
Side Suggestion: I like the way the new Deposits look, Wonder if they can be cut into bricks or something

**Comment by rryan-revived** [comment]
when in the hell has madness combat ever been part of this community damn

**Comment by Shibva** [comment]
its not, though the mod does make a good number of refences to other things ngl

**Comment by HbmMods** [comment]
There's a distant memory of seeing something in the likes of madness combat in 2009, but since then I haven't heard nor thought about it.
