### ISSUE TITLE
HE to RF converter has 10 MHE buffer

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1650]
The HE to RF converter has a 10 MHE buffer, which doesn't seem to be intentional, as it can completely overwhelm networks that can't generate enough power to fill it quickly. Version is 1.0.27_X5061.

**Comment by HbmMods** [comment]
A larger buffer is required because the buffer is what limits throughput, and the "no buffer" solution no longer works with the new energy grid. If you want to limit the amount of energy going into a converter, use a diode.

**Comment by ghost** [comment]
Perhaps it could have an adjustable buffer simlar to the diode's adjustable throughput. In some cases, you would need to either have a set of many diodes to match the power consumption or potentially have significantly more power flowing through than needed.

**Comment by HbmMods** [comment]
That would just be the same functionality built into the converters that diodes already have, and diodes are cheap, so I don't really see an issue.

**Comment by ghost** [comment]
With diodes, the converter will always draw power at a constant rate regardless of the RF side's demand. Having a filled buffer allows the converter to adapt to however much the RF side needs.
