### ISSUE TITLE
Enchancement:Matter creator and more RBMK rods

### ISSUE THREAD

**Issue by yee32767** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1654]
Matter Creator is a machine that uses 1PHE power to copy an item.It can be the final machine.We don't have any machine to use the power after the DFC is made,so I came up with the idea.

RBMK magnet container is a fuel rod that can prevent melting down if the temperature of the surface of the fuel rod is too high.It should be made after ITER.So that we can have more power before ICF.

RBMK neutron source:uses stellar flux to produce thousands of neurton.

**Comment by ghost** [comment]
Get eclipse and edit the source code
