### ISSUE TITLE
Ore Acidizer invisible and crashes the game

### ISSUE THREAD

**Issue by Drnoob23** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1656]
When i place an ore acidizer its just an invisible block when i left click it dissapears. But when i somehow place 2 of them down on a same block my game crashes and when i open the world again the ore acidizer is spawned in but the invisible one is still in the front of it. I dont know which settings i need to change.
log link: https://securelogger.net/files/aa6fcffa-337d-48ef-8891-93ca1e1a3d6b.txt
![2024-08-31_16 12 13](https://github.com/user-attachments/assets/8f153a37-9162-4a05-91af-67756d558bd6)
![2024-08-31_16 35 01](https://github.com/user-attachments/assets/9f8f6988-3b7d-4c9a-9639-0e2fe83b7af9)

Current mod version is:1.0.27_X5036 (but it has been a problem in the older versions as well)

**Comment by HbmMods** [comment]
```
java.lang.NullPointerException: Unexpected error
	at com.tierzero.stacksonstacks.block.BlockPile.getPickBlock(BlockPile.java:159)
	at net.minecraft.block.Block.getPickBlock(Block.java:1796)
	at codechicken.nei.api.ItemInfo.getIdentifierItems(ItemInfo.java:492)
	at codechicken.nei.HUDRenderer.renderOverlay(HUDRenderer.java:42)
```

Looks like "stacksonstacks" is involved here, not sure what's causing that and I haven't seen this issue pop up anywhere else, does it happen when you remove that mod?

**Comment by Drnoob23** [comment]
Yeah removing the mod fixed it.
