### ISSUE TITLE
Steam heating exchange is actually broken [Steam-Dense Steam]

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1657]
Quick context: I was making experiments with PWR reactors to compare their output to an RBMK reactor, and then began to experiment with heat-exchanging steam compression
![image](https://github.com/user-attachments/assets/95ebfd80-2835-40c2-aec0-17e375358908)
(Aka, Using the hot coolant cycled throughout the reactor to compress the steam in various stages, as seen in the image, for reactors that dont support internal steam compression, all of them except the RBMK)

Upon completing the turbines and heat exchangers setup, i realized that the energy produced was significantly lower, running some tests and looking at the game's steam compression stats, i realized that a mb of dense steam GENERATES THE EXACT SAME AMOUNT OF ENERGY as a mb of normal steam, which would be fine if they had a 1:1 conversion ratio, however, instead, they have a 10:1 conversion ratio, which means that when converting steam to dense steam, you will always objectively get less energy than if you left it at uncompressed steam, which, essentially means, that the energy harnessed by all following steps of steam compression, is always lower than what it would be if scaled correctly, maybe it was made for balance purposes and im just unaware of that, but in case it wasnt, im posting it here so it can be fixed, should be an easy fix anyway, increasing the amount of energy a mb of dense steam produces, without needing to change the conversion ratio

Thanks for reading

-Chosen

**Comment by HbmMods** [comment]
Diminishing returns from compressed steam is very much intentional, the point of compressed steam is to allow higher throughput for things with limited buffer sizes, like reactors. Manually compressing steam isn't the intended way of doing it.

**Comment by TheChosenIndividual** [comment]
> Diminishing returns from compressed steam is very much intentional, the point of compressed steam is to allow higher throughput for things with limited buffer sizes, like reactors. Manually compressing steam isn't the intended way of doing it.

yeah i know when it comes to the actual quantity of steam, but isnt it a bit problematic that a mb of dense steam produces the same as a mb of normal steam?
