### ISSUE TITLE
Superior Updated version not on CurseForge

### ISSUE THREAD

**Issue by TreehouseCumLord** [HbmMods/Hbm-s-Nuclear-Tech-GIT#166]
Greetings fellow Cumlord, I don't know why but the version on Curse is only X3697, instead of the latest.  Is it possible for you to update it sometime soon?  Thanks in advance.

**Comment by ShimmeringBlaze** [comment]
Because Curseforge takes forever and a half to verify files and Bob simply doesn't want to deal with the headaches that Curseforge brings to him
