### ISSUE TITLE
Fluid valve visual glitch

### ISSUE THREAD

**Issue by abel1502** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1660]
Pipes connected to fluid valves incorrectly react to the valve being switched on and off. When the valve is activated, pipes are displayed as if disconnected, and the other way round. The fluid still flows correctly, only the visuals are affected. Updating the pipe block manually fixes the issue.

**Comment by Bencek123** [comment]
also i had sometimes when i disconected one valve it disconnected the other one that was connected to the same line
