### ISSUE TITLE
Enhancement: waterloggability

### ISSUE THREAD

**Issue by Hacker6400** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1666]
Add waterlog for certain items like steel grate or barrel (basically all the block that are not full blocks) and if you can even the machine

**Comment by HbmMods** [comment]
Waterlogging doesn't even exist in 1.7

**Comment by Hacker6400** [comment]
I know but it can be cool if your blocks can be waterloggable

**Comment by JameH2** [comment]
Please think about the feasibility of what you are suggesting right now

**Comment by Hacker6400** [comment]
Well, for that i have the solution. There is already a mod that permitt to water log some block and maybe if you try to do something like inventore tweaks, it can work

**Comment by HbmMods** [comment]
I think if a mod like that existed I would have already heard about it, especially since the Legacy people haven't managed to backport waterlogging either.

**Comment by Hacker6400** [comment]
Here the link https://www.curseforge.com/minecraft/mc-mods/aquatweaks

**Comment by HbmMods** [comment]
That's not waterlogging, that's just a clientside coremod that makes water render more or less smoothly into non-solid blocks.

**Comment by Hacker6400** [comment]
At least it can do that to make something look better instead of a hydrofobic barrel

**Comment by gmhs022** [comment]
\>Coremod
\>Requires explicit compat

I doubt support will be done, and NTM itseslf is _definitely_ not adding in pseudo-waterlogging just for shits n giggles lol.
