### ISSUE TITLE
Enhancement: one-way pipes/valves

### ISSUE THREAD

**Issue by jarezzz** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1668]
Are there any plans to add pipes or valves that transfer liquids only in one direction, so we can make separate pipe networks or isolate certain tanks to prevent them from throwing liquid to other tanks while being able to transfer to chemlabs and other machinery?

**Comment by HbmMods** [comment]
Planned, although the fluid net will have to be reworked beforehand.
