### ISSUE TITLE
Ticking block entity crash w/ chunk pregenerator

### ISSUE THREAD

**Issue by Shirhix** [HbmMods/Hbm-s-Nuclear-Tech-GIT#167]
Hello, our server is experiencing crashes when chunks are generated using a chunk pregenerator.
This one: https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator

The blocks causing the crash are called "trapped bricks".

For anyone having the same problems, the crash report will tell you which region the blocks are in, and you can delete the region file manually, then stop the pregenerator before it tries to load the region again.

**Crash report**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390 (2).jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  HCASM (HammerCore-1.12.2-2.0.5.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63 (1).jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 4/8/21 7:19 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.world.World.func_175647_a(World.java:3073)
	at net.minecraft.world.World.func_72872_a(World.java:3068)
	at com.hbm.tileentity.deco.TileEntityTrappedBrick.func_73660_a(TileEntityTrappedBrick.java:43)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.World.func_175647_a(World.java:3073)
	at net.minecraft.world.World.func_72872_a(World.java:3068)
	at com.hbm.tileentity.deco.TileEntityTrappedBrick.func_73660_a(TileEntityTrappedBrick.java:43)

-- Block entity being ticked --
Details:
	Name: hbm:tileentity_trapped_brick // com.hbm.tileentity.deco.TileEntityTrappedBrick
	Block type: ID #351 (tile.brick_jungle_trap // com.hbm.blocks.generic.TrappedBrick // hbm:brick_jungle_trap)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-2582,24,1239), Chunk: (at 10,1,7 in -162,77; contains blocks -2592,0,1232 to -2577,255,1247), Region: (-6,2; contains chunks -192,64 to -161,95, blocks -3072,0,1024 to -2561,255,1535)
	Actual block type: ID #351 (tile.brick_jungle_trap // com.hbm.blocks.generic.TrappedBrick // hbm:brick_jungle_trap)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Season 2 World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 923 Drop: 0
	Level seed: 4405470654689179142
	Level generator: ID 04 - customized, ver 0. Features enabled: true
	Level generator options: {"coordinateScale":600.0,"heightScale":1200.0,"lowerLimitScale":1200.000,"upperLimitScale":100.000,"depthNoiseScaleX":100.000,"depthNoiseScaleZ":100.000,"depthNoiseScaleExponent":0.5,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"baseSize":8.2,"stretchY":9.0,"biomeDepthWeight":0.00,"biomeDepthOffset":0.00,"biomeScaleWeight":0.00,"biomeScaleOffset":0.00,"seaLevel":64,"useCaves":true,"useDungeons":true,"dungeonChance":8,"useStrongholds":true,"useVillages":true,"useMineShafts":true,"useTemples":true,"useMonuments":true,"useMansions":true,"useRavines":true,"useWaterLakes":true,"waterLakeChance":4,"useLavaLakes":true,"lavaLakeChance":80,"useLavaOceans":false,"fixedBiome":-1,"biomeSize":2,"riverSize":6,"dirtSize":33,"dirtCount":10,"dirtMinHeight":0,"dirtMaxHeight":256,"gravelSize":33,"gravelCount":8,"gravelMinHeight":0,"gravelMaxHeight":256,"graniteSize":33,"graniteCount":10,"graniteMinHeight":0,"graniteMaxHeight":80,"dioriteSize":33,"dioriteCount":10,"dioriteMinHeight":0,"dioriteMaxHeight":80,"andesiteSize":33,"andesiteCount":10,"andesiteMinHeight":0,"andesiteMaxHeight":80,"coalSize":20,"coalCount":12,"coalMinHeight":10,"coalMaxHeight":255,"ironSize":10,"ironCount":10,"ironMinHeight":10,"ironMaxHeight":60,"goldSize":8,"goldCount":6,"goldMinHeight":10,"goldMaxHeight":30,"redstoneSize":8,"redstoneCount":4,"redstoneMinHeight":5,"redstoneMaxHeight":20,"diamondSize":8,"diamondCount":2,"diamondMinHeight":4,"diamondMaxHeight":13,"lapisSize":7,"lapisCount":1,"lapisCenterHeight":24,"lapisSpread":16}
	Level spawn location: World: (-68,65,370), Chunk: (at 12,4,2 in -5,23; contains blocks -80,0,368 to -65,255,383), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 145394 game time, 145394 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 79388 (now: false), thunder time: 96389 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.10.0-1160.11.1.el7.x86_64
	Java Version: 1.8.0_282, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Red Hat, Inc.
	Memory: 2751891424 bytes (2624 MB) / 4194304000 bytes (4000 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 20 total; -Xmx6144M -Xms3993M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 62 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version                  | Source                                                | Signature                                |
	|:------ |:--------------------- |:------------------------ |:----------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                   | minecraft.jar                                         | None                                     |
	| LCHIJA | mcp                   | 9.42                     | minecraft.jar                                         | None                                     |
	| LCHIJA | FML                   | 8.0.99.99                | forge_1.12.2.jar                                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2855             | forge_1.12.2.jar                                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | obfuscate             | 0.2.6                    | minecraft.jar                                         | None                                     |
	| LCHIJA | anvilpatch            | 1.0.0                    | anvilpatch-1.0.1.jar                                  | None                                     |
	| LCHIJA | jei                   | 4.15.0.293               | jei_1.12.2-4.15.0.293.jar                             | None                                     |
	| LCHIJA | appleskin             | 1.0.9                    | AppleSkin-mc1.12-1.0.9 (1).jar                        | None                                     |
	| LCHIJA | armorcurve            | 1.2.0                    | armorcurve-1.2.9.jar                                  | None                                     |
	| LCHIJA | baubles               | 1.5.2                    | Baubles-1.12-1.5.2 (1).jar                            | None                                     |
	| LCHIJA | betterbuilderswands   | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70 (1).jar   | None                                     |
	| LCHIJA | bettercaves           | 1.12.2                   | bettercaves-1.12.2-1.6.0.jar                          | None                                     |
	| LCHIJA | bettercombatmod       | 1.5.6                    | BetterCombat-1.12.2-1.5.6 (1).jar                     | None                                     |
	| LCHIJA | biometweaker          | 3.2.369                  | BiomeTweaker-1.12.2-3.2.369.jar                       | 631f326344f7f5fd7df7eb940760ebd52b7c9c17 |
	| LCHIJA | bountifulbaubles      | 0.0.1                    | Bountiful+Baubles-1.12.2-0.1.5.jar                    | None                                     |
	| LCHIJA | geckolib3             | 3.0.0                    | forge-1.12.2-geckolib-3.0.0-beta.7.jar                | None                                     |
	| LCHIJA | cqrepoured            | 2.4.2B                   | Chocolate_Quest_Repoured-1.12.2-2.4.2B.jar            | None                                     |
	| LCHIJA | chunkpregenerator     | 2.5.0                    | Chunk+Pregenerator-V1.12-2.5.0.jar                    | None                                     |
	| LCHIJA | extendedrenderer      | v1.0                     | coroutil-1.12.1-1.2.37 (1).jar                        | None                                     |
	| LCHIJA | coroutil              | 1.12.1-1.2.37            | coroutil-1.12.1-1.2.37 (1).jar                        | None                                     |
	| LCHIJA | configmod             | v1.0                     | coroutil-1.12.1-1.2.37 (1).jar                        | None                                     |
	| LCHIJA | modcurrency           | 1.12-1.3.11              | Currency-1.12.0-1.3.11.jar                            | None                                     |
	| LCHIJA | cyclicmagic           | 1.19.18                  | Cyclic-1.12.2-1.19.18.jar                             | None                                     |
	| LCHIJA | mantle                | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55 (2).jar                          | None                                     |
	| LCHIJA | tconstruct            | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                      | None                                     |
	| LCHIJA | defiledlands          | 1.4.3                    | defiledlands-1.12.2-1.4.3 (1).jar                     | None                                     |
	| LCHIJA | flansmod              | 5.5.2                    | Flan_s Mod-1.12.2-5.5.2.jar                           | None                                     |
	| LCHIJA | flansmodapocalypse    | 1.0                      | Flan_s Mod-1.12.2-5.5.2.jar                           | None                                     |
	| LCHIJA | foamflower            | 1.12.2-1.0.0.0-beta1     | foamflower-1.12.2-1.0.0.0-beta1 (1).jar               | None                                     |
	| LCHIJA | hammercore            | 2.0.5.0                  | HammerCore-1.12.2-2.0.5.0.jar                         | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | hbm                   | hbm-1.4.0A-1.12.2        | hbm-1.4.1a (1).jar                                    | None                                     |
	| LCHIJA | waila                 | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                           | None                                     |
	| LCHIJA | ido                   | 1.0.6                    | ido-1.12.2-1.1.0.jar                                  | None                                     |
	| LCHIJA | improvableskills      | 65r                      | ImprovableSkills-1.12.2-65r.jar                       | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63 (1).jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest             | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847 (1).jar                   | None                                     |
	| LCHIJA | journeymap            | 1.12.2-5.7.0             | journeymap-1.12.2-5.7.0.jar                           | None                                     |
	| LCHIJA | mekanism              | 1.12.2-9.8.3.390         | Mekanism-1.12.2-9.8.3.390 (2).jar                     | None                                     |
	| LCHIJA | mekanismgenerators    | 1.12.2-9.8.3.390         | MekanismGenerators-1.12.2-9.8.3.390 (2).jar           | None                                     |
	| LCHIJA | mekanismtools         | 1.12.2-9.8.3.390         | MekanismTools-1.12.2-9.8.3.390 (2).jar                | None                                     |
	| LCHIJA | progressivedifficulty | 1.12_3.1                 | ProgressiveDifficulty-1.12_3.1.jar                    | None                                     |
	| LCHIJA | thaumcraft            | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                      | None                                     |
	| LCHIJA | railcraft             | 12.0.0                   | railcraft-12.0.0.jar                                  | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | recycler              | 3.2.4                    | recycler-3.2.4-1.12.jar                               | None                                     |
	| LCHIJA | roguelike             | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0 (1).jar                | None                                     |
	| LCHIJA | ruins                 | 17.2                     | Ruins-1.12.2.jar                                      | None                                     |
	| LCHIJA | simplecobblegen       | X.F.1                    | simplecobblegen-1.12.2-X.F.1.jar                      | None                                     |
	| LCHIJA | spartanweaponry       | beta 1.3.8               | SpartanWeaponry-1.12.2-beta-1.3.8.jar                 | None                                     |
	| LCHIJA | srparasites           | 1.8.2                    | SRParasites-1.12.2v1.8.2.jar                          | None                                     |
	| LCHIJA | superiorshields       | 1.12.2-1.0.2             | SuperiorShields-1.12.2-1.0.2.jar                      | None                                     |
	| LCHIJA | tombstone             | 4.0.1                    | tombstone-4.0.1-1.12.2.jar                            | None                                     |
	| LCHIJA | waystones             | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                            | None                                     |
	| LCHIJA | weather2              | 1.12.1-2.6.12            | weather2-1.12.1-2.6.12 (1).jar                        | None                                     |
	| LCHIJA | drplibrary            | 1.12.2-0.1.3-SNAPSHOT    | drplibrary-1.12.2-0.1.3-SNAPSHOT-20190129.084240.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcmmaarg            | 1.12.2-0.10.0-SNAPSHOT   | drpcmmaarg-1.12.2-0.10.0-SNAPSHOT-20181116.124036.jar | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcmguis             | 1.12.2-0.0.2-SNAPSHOT    | drpcmguis-1.12.2-0.0.1-SNAPSHOT-20181125.050253.jar   | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcmlocks            | 1.12.2-1.0.1             | drpcmlocks-1.12.2-1.0.0-SNAPSHOT-20181126.041203.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcore               | 1.12.2-0.4.7             | drpcore-1.12.2-0.4.8.jar                              | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpmedieval           | 1.12.2-0.3.6             | drpmedieval-1.12.2-0.3.6.jar                          | None                                     |
	| LCHIJA | llibrary              | 1.7.20                   | llibrary-1.7.20-1.12.2 (1).jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | drpcmblueprints       | 1.12.2-1.2.3             | drpcmblueprints-1.12.2-1.2.3.jar                      | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | mysticallib           | 1.12.2-1.10.0            | mysticallib-1.12.2-1.10.0.jar                         | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MekanismCoremod (Mekanism-1.12.2-9.8.3.390 (2).jar)
  mekanism.coremod.KeybindingMigrationHelper
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
HCASM (HammerCore-1.12.2-2.0.5.0.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63 (1).jar)
  invtweaks.forge.asm.ContainerTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 834 names; 870 stacks.
Pastebin Connection: Okay.
Dependent Mods:
    -Improvable Skills (improvableskills) @65r

	Profiler Position: N/A (disabled)
	Player Count: 0 / 15; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Drillgon200** [comment]
Meta is 4, it should not have even created a tile entity. Sounds like the pregenerator's fault to me. In any case I'll still add a check.
Just so you know, I have my own fork that I'm more likely to check for bug issues on in 1.12.2.

**Comment by HbmMods** [comment]
In case this also happens in 1.7, I added a default non-null bounding box in case the TE is created despite not having a bounding box.
