### ISSUE TITLE
Enhancement: New model and texture for the ICF pellet maker

### ISSUE THREAD

**Issue by Hacker6400** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1670]
The ICT pellet maker is kinda ugly because is litteraly a gold block whit a Hopper and a new model for it's can looks better

**Comment by HbmMods** [comment]
and that was worth opening an issue for?

**Comment by Hacker6400** [comment]
Everyone open an enhancement on issue

**Comment by Hacker6400** [comment]
So i Belived that the enhancement can be open here
