### ISSUE TITLE
Achievement bug

### ISSUE THREAD

**Issue by Hacker6400** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1676]
If you make tantalum polycrystal in a chem factory, don't give the achievement. Similar to that if you don't smelt directly the schrabidium ore and you process it in another ways (like what i do), still don't give the achievement

**Comment by HbmMods** [comment]
Achievements not being granted by chemfac output has just been fixed, achievements not triggered due to things like automation is a vanilla issue that I can't do anything about.
