### ISSUE TITLE
Missile lag

### ISSUE THREAD

**Issue by SmiteX134** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1677]
For some reason, after launching a tier 1 HE missile, server started lagging really badly, but before everything worked perfectly
Spark: https://spark.lucko.me/pjmimiLZB8

**Comment by HbmMods** [comment]
98% of your CPU time are being consumed by `EntityArrow` which I don't think has a whole lot to do with any missiles. Maybe someone spammed one of those ancient frag grenades which spawn arrows?

**Comment by SmiteX134** [comment]
> 98% of your CPU time are being consumed by `EntityArrow` which I don't think has a whole lot to do with any missiles. Maybe someone spammed one of those ancient frag grenades which spawn arrows?

I dont think so, because the lag starts immediately after i launch a missile

**Comment by HbmMods** [comment]
Well sure but that doesn't automatically imply causation, profiler says that the lag comes from arrows, and missiles neither use nor spawn those, so that seems to be unrelated.

**Comment by SmiteX134** [comment]
Is there any way to kill every entity on the server in 1.7.10?

**Comment by HbmMods** [comment]
On a vanilla server? No, but I think Essentials has a command for that, assuming you have that plugin.

**Comment by SmiteX134** [comment]
Well, I'll see what I can do about that. Thanks for help

**Comment by SmiteX134** [comment]
Yeah, I fixed the problem by just deleting the region that contained 8000 arrows (bruh), but I still find it weird that the lag only starts when launching a missile

**Comment by gmhs022** [comment]
Missiles chunkload, it might have been the missile just loaded the chunk with 8k arrows which led to lag.
