### ISSUE TITLE
Mouse right button double click problem

### ISSUE THREAD

**Issue by LSK-LW** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1683]
in 5082/5900
All right clicks will become double clicks.
Setting hbm.gunSecondary to another key will fix this issue.

**Comment by HbmMods** [comment]
Do you have MouseTweaks installed? Until now everyone who has this issue has, and removing it seemed to fix it.

**Comment by HbmMods** [comment]
New release changes a few small things regarding keybinds, could you test whether it changes anything in regards to the bug?

**Comment by LSK-LW** [comment]
> New release changes a few small things regarding keybinds, could you test whether it changes anything in regards to the bug?

I don't have MouseTweaks installed.
This problem was fixed in 5091, thanks
