### ISSUE TITLE
Valves shut off the fluid flow entirely on branching ducts

### ISSUE THREAD

**Issue by rattlemebones1** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1688]
Mod version: 5036
I am on a server

I was building a turbine room, and when I decided to shut down turbine 2 the ducts kinda just shit themselves and both of them shut down. I have replicated this bug every time, closing and opening valve 1 fixes it. I took a video to better show what I mean:

https://github.com/user-attachments/assets/02e9c620-465f-4df4-886b-3bac9753e9ab

**Comment by rattlemebones1** [comment]
Just found out, the valve that stayed open acts as if it is still closed if the other valve is opened. I dont expect this bug to do much other than break automation if it affects redstone valves too, though.
![image](https://github.com/user-attachments/assets/55f19558-8213-4cf8-b3ef-eac123aa53d3)

**Comment by Jundix22** [comment]
interestingly enough i tried to replicate your bug, it did actually fix itself. Maybe its because you're on an older version.

![2024-09-20_14 30 00](https://github.com/user-attachments/assets/0c591b81-b186-4667-b584-d09228ca56af)

**Comment by HbmMods** [comment]
I can't replicate this either, it might have something to do with the issue where valves would disconnect which itself had a more severe underlying issue, but that was fixed a while ago. It looks like you're on an older version because the boxducts have some minor graphical jank that was fixed this week.

**Comment by rattlemebones1** [comment]
The barrel might be changing things. In my facility, the barrel is just an infinite water barrel that goes to 4 geo exchangers. That might cause some differences? I'd test in a newer version but I need the server owner to change it, and he usually waits a while incase bugs occur.

**Comment by rattlemebones1** [comment]
Can't reproduce, still on the old version. It's probably the server.
