### ISSUE TITLE
Enhancement: config in game

### ISSUE THREAD

**Issue by Hacker6400** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1689]
I was thinking the possibilità of change the config file in game, like some others mod, instead of shut down the game, find the config file and find the interested part

**Comment by Hacker6400** [comment]
The custom machine can be still in the old way for pratical reasons

**Comment by rattlemebones1** [comment]
I don't think this is really possible without hbm making an entire framework around saving configs in-game from scratch. The reason create can do that is because they've had years to make that exact thing not suck garbage.

**Comment by HbmMods** [comment]
nah
