### ISSUE TITLE
Snow destruction inconsistency during nuclear explosions

### ISSUE THREAD

**Issue by abel1502** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1691]
I've accidentally discovered that naturally generated snow layer is only partially destroyed by a nuclear explosion's fallout (see minimap screenshot below). Seems aligned to quarter-chunks, sometimes to 1/8th of a chunk. Sorry for lacking report, I only stumbled across it accidentally and in a hurry. Should be reproducible easily, but just in case it has an effect, my explosion was of a metastable U238-M2 ingot.

![{B1AC7183-B924-4A58-9FAD-4860143F7F53}](https://github.com/user-attachments/assets/043b32e0-432e-41cd-a8dd-bd4ef4bebe8c)

**Comment by HbmMods** [comment]
For performance reasons, explosions only cause block updates on the very edges which saves a lot of processing time. Fixing this without causing even more lag than having block updates would be complicated as well as useless since a new explosion system is already being worked on.
