### ISSUE TITLE
SPAS 12 doesn't work

### ISSUE THREAD

**Issue by Hacker6400** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1696]
Strangely the spas-12 doesn't work (it shoot but it don't do damage to the mobs)

**Comment by HbmMods** [comment]
Works fine for me. What ammo are you using?

**Comment by Hacker6400** [comment]
12 blue gauge

**Comment by HbmMods** [comment]
Standard ammo works on my end, could you describe the situation more? What are you shooting at, what range are we talking about, do you hear ricochet sounds when shooting at the floor at a shallow angle, have you tried any other ammo types?

**Comment by Hacker6400** [comment]
here a video:
file:///C:/Users/Thor/Desktop/Minecraft%201.7.10%202024-09-27%2017-07-39.mp4

**Comment by HbmMods** [comment]
bruh

**Comment by Hacker6400** [comment]
What???

**Comment by HbmMods** [comment]
you posted the file path *from your hard drive* instead of the video
