### ISSUE TITLE
Radio

### ISSUE THREAD

**Issue by atomicbastion** [HbmMods/Hbm-s-Nuclear-Tech-GIT#170]
I saw that their is a broken radio how about a working radio that uses a antenna 📡 also their could be a income voice chat that you use on the radios but you can also use the radios to speak to other parts of you empire to tell them if war is going to happen. This is also where the newly found red emergency beacon could be used (its just a spinning red emergency alarm). This is for the people this part. If you used a wireless red stone mod you could uses this to your advantage. If a war broke out.i also think to use the radar you should have to have a satellite 🛰.

**Comment by TheForge129** [comment]
radars don't use satellites
also please don't stroke next time you post a suggestion
