### ISSUE TITLE
Drop Pod Docking 

### ISSUE THREAD

**Issue by BruhBronxy** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1703]
When you attempt to dock a drop pod in a port that is already full it just docks anyways and it makes both of the drop pods docked there impossible to break unless you delete your save file.

**Comment by BruhBronxy** [comment]
Also after using the drop pod a few times it will start missing the dock entirely.

**Comment by HbmMods** [comment]
what

**Comment by JameH2** [comment]
You might wanna put this in the ntm space github

**Comment by BruhBronxy** [comment]
My bad I will close this issue.
