### ISSUE TITLE
When I press E to open inventory "Sometimes" and game will crash

### ISSUE THREAD

**Issue by THATsGARY** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1706]
Game version: 1.7.10
Forge

I've also installed lots of mods, and I'll post the crash log too.
[2024-09-28-7.log](https://github.com/user-attachments/files/17176007/2024-09-28-7.log)

**Comment by THATsGARY** [comment]
Please help me

**Comment by HbmMods** [comment]
The log you've sent doesn't contain any crash reports, could you check the `crash-reports` folder for logs instead?

**Comment by THATsGARY** [comment]
> The log you've sent doesn't contain any crash reports, could you check the `crash-reports` folder for logs instead?

I don't know if that's a normal crash. The game was stuck when I open inventory sometimes, and stuck like 2-3 seconds and the game shows "Shutting down", then the game's window closed

**Comment by THATsGARY** [comment]
[crash-2024-09-28_20.32.21-client.txt](https://github.com/user-attachments/files/17196501/crash-2024-09-28_20.32.21-client.txt)

Here you go the crash report

**Comment by HbmMods** [comment]
Seems like the random item name generator for the undefined item caught an item that can't properly resolve a name, I'll just add some exception handling around that part.

**Comment by THATsGARY** [comment]
> Seems like the random item name generator for the undefined item caught an item that can't properly resolve a name, I'll just add some exception handling around that part.

Thanks so much

**Comment by THATsGARY** [comment]
> Seems like the random item name generator for the undefined item caught an item that can't properly resolve a name, I'll just add some exception handling around that part.

Hi, is this fix yet?

**Comment by HbmMods** [comment]
A fix was committed but the release won't be out until the gun rework is done and that'll take some time.

**Comment by THATsGARY** [comment]
> A fix was committed but the release won't be out until the gun rework is done and that'll take some time.

Okay
