### ISSUE TITLE
A Suggestion

### ISSUE THREAD

**Issue by NyaShiroko** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1709]
In the current latest version (5091), the fluid buckets and fluid tanks require the liquid to exceed their maximum capacity before they can be filled. Could it be changed to be like version HBM'NTM Reloaded in 1.12.2, where the fluid buckets and tanks can be filled even if the required liquid doesn't exceed their maximum capacity?
![屏幕截图 2024-09-30 201316](https://github.com/user-attachments/assets/d31a7141-584e-41cf-8afe-3bc31679d385)
![屏幕截图 2024-09-30 201442](https://github.com/user-attachments/assets/73af32da-f21c-4625-ae3b-4b53457053f0)

**Comment by NyaShiroko** [comment]
For example, "0/16000 mb" in the image.

**Comment by BallOfEnergy1** [comment]
Check the Pipette for variable storage (mB amounts).

**Comment by HbmMods** [comment]
That's what pipettes are for.

**Comment by NyaShiroko** [comment]
> That's what pipettes are for.

As shown in the figure, the fluid bucket cannot be filled with fluid
![屏幕截图 2024-10-01 115246](https://github.com/user-attachments/assets/9ccfc6ae-7ca7-4fd9-a767-f3923f10b78d)

**Comment by NyaShiroko** [comment]
> That's what pipettes are for.

It had to reach 24000 mB to fill fluid, which was inconvenient.

**Comment by BallOfEnergy1** [comment]
Again, pipettes. Also, universal storage tanks for 1000mB amounts.

**Comment by NyaShiroko** [comment]
> Again, pipettes. Also, universal storage tanks for 1000mB amounts.

Thanks.
