### ISSUE TITLE
question

### ISSUE THREAD

**Issue by atomicbastion** [HbmMods/Hbm-s-Nuclear-Tech-GIT#171]
does anyone know a mod that would work with the radar on this mod and make it so that when i have a group that i can add my group of friends and so when i look on the radar it will show them as a green dot but the players that have not been added will be shown as red.??

**Comment by ShimmeringBlaze** [comment]
Nope

**Comment by TheForge129** [comment]
join this https://discord.com/invite/YDUWGaf and go to #questions
