### ISSUE TITLE
V1 Removal

### ISSUE THREAD

**Issue by BMS10-11** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1714]
I just opened the latest update, and the V1 armor upgrade is gone.

The community loved this upgrade, and it was also very useful.

Please consider putting it back in the mod.

**Comment by HbmMods** [comment]
![skull_issue](https://github.com/user-attachments/assets/51d791e4-43c8-4f10-a413-d703e4fb8bd8)

**Comment by BMS10-11** [comment]
What do you mean? Is it still there and I can't find it?

**Comment by fbfnysnshnsgnwg** [comment]
jamesh2 fork has it
