### ISSUE TITLE
Suggestion: Raccoon pets.

### ISSUE THREAD

**Issue by DTK-MrRaccoon** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1717]
Add raccoons that can be tamed, the reason is that we have ducks so we must have raccoons too. And I like them, I have 3 raccoons.

![photo_6023684572170011955_y](https://github.com/user-attachments/assets/7000d42b-8398-4e4b-95ea-e9c5382f13ee)

**Comment by HbmMods** [comment]
I suck at making mobs that don't look like garbage so I'm afraid that's not gonna happen
