### ISSUE TITLE
Heatsinks caused PWR meltdown

### ISSUE THREAD

**Issue by R-Kaenbyou** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1718]
For a PWR which includes 215 or more heatsinks, it would explode immediately after the construction finished.

**Comment by Seagate-1TB** [comment]
I would love to a see a video of this

**Comment by TheChosenIndividual** [comment]
how did bro find out that it is EXACTLY 215 or more heatsinks

**Comment by R-Kaenbyou** [comment]
> how did bro find out that it is EXACTLY 215 or more heatsinks

I've done many experiments; you can try it by yourself.

**Comment by Hinanium-Ion** [comment]
> how did bro find out that it is EXACTLY 215 or more heatsinks

Because bob got something wrong in the code. 215 heatsinks will lead to overflow, and the PWR heat capacity will become a negative number, so the reactor will meltdown immediately as it finished

**Comment by JameH2** [comment]
why are you using 215 heatsinks

**Comment by R-Kaenbyou** [comment]
> why are you using 215 heatsinks

I was trying to find out that how powerful can PWR be.

**Comment by TheChosenIndividual** [comment]
I remember when i was doing that too, perhaps we should join our research

**Comment by R-Kaenbyou** [comment]
> I remember when i was doing that too, perhaps we should join our research

Someone else already found the result, 214 heatsinks can lead to the maximum output of 544.36MHE/s
