### ISSUE TITLE
3 Suggestion and 1 Recomendation

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#172]
Suggestions:

1. The large capacity on the HE to RF and Vice versa block can be a bit of a pain for those that are generating low power and are using multiple of them to distribute power to other non HE machines, so why not make it so its crafted with batteries so the lowest capacity one can store about 1000 HE : 4000 RF when crafted with a Normal mundane battery and the highest capacity one made with either a powercell block or a Lith-ion Powercell block

2. some method to "camouflaged" the wire Block (not the actual wire, but the whole wire sized block) with another block of desired choice to blend in to the environment

3.
the Portable Hazardous Environment Detector [P.H.E.D.) (or something with reference to the HEV suit)
an expensive Detector that is the last one that you ever need!
*Can detect Radiation, Digamma Radiation (the bar will be a bit thinner overlaying the Radiation bar) and Asbestos Contamination Indicator (will cover over the Digamma bar and is a thin line)
*Right clicking it will display Radiation, Digamma, and Asbestos Contamination status like with a Geiger counter
*Overlay will have a 5 second strobe between different hazards that are detected when in inventory
(Ie, if there's Monoxide present and radiation, it will display the Radiation warning and then change into the CO warning after X seconds; will show CO, Radon (irrelevant, just normal radiation symbol or something), 
Recommendation:

![image](https://user-images.githubusercontent.com/38770780/115127117-f8f09700-9fa1-11eb-982c-5858e4e03983.png)

Add Infernal Coal to the accepted fuels to the blast furnace

Non-serious suggestion: add the infernal coal block, holding it in your inventory BURNS and have the Cybercrabs also deal fire damage so that vampire players cant raid and farm them easier (source: did this myself, cybercrabs and radiation dont kill, might be best to make their defense harder since I know HBM hates vampires XD)

**Comment by Shibva** [comment]
side suggestion: Zirconium slivers can drop from rare earths, but is rare when mining it, Fortune does not increase its odds (unless wanted to)

**Comment by ShimmeringBlaze** [comment]
Why is everybody __suggesting__ in the __issues__ section? That's not what this is for

**Comment by Shibva** [comment]
sorry, dont know there was an suggestion section and if its in the discord then I cant get in because I was banned there for some uknown reason or something (This is Doge_9000 Speaking)

**Comment by RagexPrince683** [comment]
>because I was banned there for some uknown reason or something

good

**Comment by Shibva** [comment]
well well well, 

out of all the people I was expecting to resopond here, you were the last I was expecting to

long time no see and
dint you get banned too?

**Comment by HbmMods** [comment]
Neither one of you are, or have been banned for quite a long time. I can't even remember what happened quite honestly.

**Comment by Shibva** [comment]
then my suspicions are confirmed, its some form of glitch with discord thats preventing me form entering "thinking" that i have been banned or something.

sometimes I can enter only to be kicked out again

I can only assume at this point that theres something else preventing me form entering like an IP ban on me or another account that I used to rejoin, 
its by far the most plausable

but why talk about this here? this is ment to be for issues damnit

**Comment by HbmMods** [comment]
By the way, there's a possibility that it's due to Discord's automated alt removal thing that also shadowbans accounts with the same IP,  so in case you had any alts on the server they might just keep you banned until I manually unban them.

**Comment by gatoborrachon** [comment]
> Why is everybody **suggesting** in the **issues** section?

does that thing even exists?

because, taking advantage of the name of this issue, i just want to say that something like the [Seismic Vibrator](https://wiki.aidancbrady.com/wiki/Seismic_Vibrator) (from Mekanism, to detect ores) but with the skin/sounds of the [Restrictors](https://half-life.fandom.com/wiki/Restrictor) (from Half Life 2) would be nice.
or maybe just to avoid the spawn/permanence of mobs, like the original Restrictor does.

**Comment by HbmMods** [comment]
> does that thing even exists?

It doesn't.
