### ISSUE TITLE
Catalyic cracking tower not changing recipes

### ISSUE THREAD

**Issue by SUP3R10R1** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1726]
I'm playing on the newest version of HBM on my server which has a few other mods, when I click on the catalyic cracking tower with a different recipe it doesn't work, instead of saying the required ingredients it just says none for all the slots, I've tried breaking it and replacing it and restarting my server

![2024-10-09_19 00 15](https://github.com/user-attachments/assets/0f16b666-9407-459e-9e41-72691b89878d)

**Comment by HbmMods** [comment]
It does this when it's set to a fluid that doesn't match any recipe, what input did you set?

**Comment by SUP3R10R1** [comment]
> It does this when it's set to a fluid that doesn't match any recipe, what input did you set?

Thank you for the reply, I have to set to make unsaturated hydrocarbons and I have the natural gas and steam pipes connect to it

**Comment by HbmMods** [comment]
Outputs aren't unique, you can't define a recipe with unsaturated hydrocarbons because multiple recipes yield those, you have to set the input type.

**Comment by JameH2** [comment]
https://github.com/user-attachments/assets/97e6d2fc-5cd1-4c3f-a3f6-6a403a5c342e
