### ISSUE TITLE
Enhancement: end stone usage

### ISSUE THREAD

**Issue by abel1502** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1728]
Players get a lot of end stone when mining for trixite, but you can't use it for anything (literally; other than building something ugly), so it just sits there wasting space. I think it would make sense if it could at least be shredded into dust like most other things are. Perhaps also liquefied into ender juice, or oredicted to `stone` instead.

**Comment by HbmMods** [comment]
I'm pretty sure end stone can already be shredded into dust, since it has no recipes it shreds into scrap, and scrap can be shredded into dust.

**Comment by abel1502** [comment]
Oh, I see. NEI didn't show the "anything to scrap" recipe, I didn't realize it existed
