### ISSUE TITLE
Is it possible to craft in HBM reloaded the Reiium ingots/nuggets?

### ISSUE THREAD

**Issue by RaresBares** [HbmMods/Hbm-s-Nuclear-Tech-GIT#173]
jEI tells me, that i need the ingots to craft bars and the bars to craft ingots. But how do I get the Ingots from powder?
Is it even possible?

**Comment by Big-Boofer** [comment]
Bruh

**Comment by TheForge129** [comment]
1. This is the 1.7 version
2. the 1.12 is just called hbm's nuclear tech, not reloaded
3. yes, there is an issue with that actually, there is just no smelting recipe. drillgon will probably fix it in the next update

**Comment by Big-Boofer** [comment]
Can't you just smelt the powder Its kind of obvious

**Comment by TheForge129** [comment]
> Can't you just smelt the powder Its kind of obvious

wierd bug says no
