### ISSUE TITLE
auto crafting table isnt tabling

### ISSUE THREAD

**Issue by spenkluker645** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1730]
### Describe the bug
simple, look at the image
![image](https://github.com/user-attachments/assets/8caf68ae-515a-4fce-add0-3da89cac9c09)

**Comment by HbmMods** [comment]
What version are you on? That was a confirmed issue shortly after the recipe filter changes but that should have been fixed for quite some time now.

**Comment by spenkluker645** [comment]
i was using the one from curseforge, updates fixed it
