### ISSUE TITLE
Can't lower Control Rods in Research Reactor (Bug)

### ISSUE THREAD

**Issue by Cor1t** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1732]
Mod Version: HBM-NTM-.1.0.27_X5091
In research reactor, after you set the value of control rods, next time you want to change it, it's always automatically set's on 100%.

**Comment by HbmMods** [comment]
Did you hit the save button?

**Comment by Cor1t** [comment]
Yes

**Comment by Cor1t** [comment]
I'm sending you a clip from MC with input overlay, so you will understand better: https://streamable.com/9b1ggc

**Comment by HbmMods** [comment]
You entered 1 when the level was set to 97, setting it to 971, capping to 100. The field acts like a regular text field, so you will have to delete the current level with backspace.

**Comment by Cor1t** [comment]
Thank you, I thought when it was blinking, it will replace text. Sorry for trouble.
