### ISSUE TITLE
[Suggestion] New Doors Idea

### ISSUE THREAD

**Issue by MiniRaptor** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1735]
I know it's kinda strange idea for nuclear tech mod, but what about adding doors which will work and look like hell gates from DOOM Eternal?

https://youtu.be/3O5dPSzmzkw?t=1598

It would be epic addition to mod

**Comment by LePeeperSauvage** [comment]
No

**Comment by HbmMods** [comment]
no

**Comment by MiniRaptor** [comment]
> no

why so serious 🥺
