### ISSUE TITLE
Conveyor grabber issue

### ISSUE THREAD

**Issue by Ilikepotatochips** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1740]
In the latest release, 5091, Conveyor grabbers only grab from the first conveyor block on a belt, not any other..

**Comment by TheChosenIndividual** [comment]
im pretty sure someone already uploaded an issue about this, but HBM seems to have closed it so...guess that means he doesnt really intend to fix or change it ¯\_(ツ)_/¯

Upd: nevermind you're talking about a DIFFERENT issue, which seems like the guy who did the PR and "fixed" it, didnt actually do it right

**Comment by HbmMods** [comment]
Not sure what you mean with "first conveyor block on a belt", could you describe the situation a bit more?

**Comment by Ilikepotatochips** [comment]
sure! when you put a conveyor grabber on a conveyor directly next to the ejector, it will work and grab the item set. But  when you place the grabber on any other conveyor, it won't work

**Comment by TheChosenIndividual** [comment]
> Not sure what you mean with "first conveyor block on a belt", could you describe the situation a bit more?

Hey Dr. Hb, can i ask you a weird and trivial question? also unrelated to the mod?

**Comment by HbmMods** [comment]
@Ilikepotatochips I can't really replicate this behavior, can you send a screenshot of your setup?
@TheChosenIndividual sure but don't hijack random issues for that

**Comment by TheChosenIndividual** [comment]
@HbmMods okey doke...ill...uh...ill go and...look for your discord...just...yeah...you get it
