### ISSUE TITLE
Strontium uncastablility

### ISSUE THREAD

**Issue by Ilikepotatochips** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1741]
In the latest release, 5091, Strontium-90 is uncastable despite having a smeltable form. This is very annoying when trying to automate rare-earth-ore bedrock ore. I understand this is to enable BSCCO but strontium should be castable to.

**Comment by R-Kaenbyou** [comment]
Sodium and Neodymium have similar problem.

**Comment by HbmMods** [comment]
Duplicate of #1572
