### ISSUE TITLE
Game Crashes when crucible is equipped.

### ISSUE THREAD

**Issue by Fussyband** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1745]
[2024-10-25-7.log.gz](https://github.com/user-attachments/files/17528474/2024-10-25-7.log.gz)

**Comment by HbmMods** [comment]
You probably want to report this to [Extended Edition](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/issues) instead
