### ISSUE TITLE
Mass storage item dupe

### ISSUE THREAD

**Issue by abel1502** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1746]
If you switch the item stored in a mass storage unit (i.e. left click the filter slot with it) while it's not empty, all the items inside are transformed into the new one. I believe the solution is to forbid changing the item stored in non-empty MSUs.

**Comment by HbmMods** [comment]
Can't replicate this since filter slots are already supposed to be locked when the thing is filled.

**Comment by abel1502** [comment]
I can see the check in https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/blob/17b667bf3d64c4280ebdf29b93f0c245a88f482c/src/main/java/com/hbm/inventory/container/ContainerMassStorage.java#L78-L80 , but I have once again tested it manually and the item can be changed even when the storage isn't empty. It seems to work reliably and regardless of the kind of MSU. I suspect `slotClick` simply isn't invoked, since if I place a stack of items into the filter slot, it is retained as a stack despite https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/blob/17b667bf3d64c4280ebdf29b93f0c245a88f482c/src/main/java/com/hbm/inventory/container/ContainerMassStorage.java#L84-L86

**Comment by HbmMods** [comment]
Wait, are you using the NH version of NEI?

**Comment by abel1502** [comment]
Yes, I am

**Comment by HbmMods** [comment]
god dammit not again

**Comment by TheChosenIndividual** [comment]
> god dammit not again

"Help i accidentally used the NH version of NEI again"
