### ISSUE TITLE
How to turn off meteorites.

### ISSUE THREAD

**Issue by gurosamaa** [HbmMods/Hbm-s-Nuclear-Tech-GIT#175]
Someone said that it was possible to turn off the meteorites via the config file but after searching inside it for a while i couldn't find the variable.

**Comment by Big-Boofer** [comment]
![Screenshot 2021-04-24 180055](https://user-images.githubusercontent.com/50680915/115976864-0a4c1d00-a527-11eb-9e92-d4aa34c282a3.png)

**Comment by Big-Boofer** [comment]
almost impossible to miss

**Comment by gurosamaa** [comment]
Thank you a lot!
