### ISSUE TITLE
Question: do all burner machines emit the same amount of soot if filled with the same fuel?

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1754]
Self-explanatory, i want to know if the soot stat is actually attached to fuels or machines, which will hopefully prevent super smokestacking

**Comment by HbmMods** [comment]
Burner machines have constant soot output no matter the fuel. Only liquid fueled machines use variable pollution stats.

**Comment by TheChosenIndividual** [comment]
> Burner machines have constant soot output no matter the fuel. Only liquid fueled machines use variable pollution stats.

got it, also, now that you're here, unrelated question: Do you still talk with Rodol?

**Comment by HbmMods** [comment]
Haven't seen rodol in years. Apparently updates to the game are still coming out or something? At least I overheard some people on the RR discord talking about that.

**Comment by TheChosenIndividual** [comment]
> Haven't seen rodol in years. Apparently updates to the game are still coming out or something? At least I overheard some people on the RR discord talking about that.

Idk, he's off like, developing the games, but all of his channels have been offline for at least 2 years, also, THERE'S A RR DISCORD?!

**Comment by HbmMods** [comment]
The RR discord has been around since at least 2017, in fact it was the first discord I ever joined. A few years ago it got nuked and recreated but the old one is still around.

**Comment by TheChosenIndividual** [comment]
> The RR discord has been around since at least 2017, in fact it was the first discord I ever joined. A few years ago it got nuked and recreated but the old one is still around.

Interesting...well...im in a bad spot, im trying to find the studio version of the song Rodol used for the RR vs the illuminati series as the theme, neither the artist nor the song, or remixes, show up, i thought maybe the man himself had the answers but...actually, you know anything about the production of RR vs the illuminati HB?

**Comment by HbmMods** [comment]
no clue man, that happened like 10 years ago

**Comment by TheChosenIndividual** [comment]
> no clue man, that happened like 10 years ago

Well fuck, thanks still, have a good day
