### ISSUE TITLE
NTM particles remove the surface of water with certain performace mods active

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1756]
NTM particles will cause the surface of water behind them to not appear with some performance mods active. This occurs both with [Angelica](https://modrinth.com/mod/angelica) and with [BugTorch](https://modrinth.com/mod/bugtorch), but I believe other mods cause it as well. This is easily reproducable using a drain pipe. Gases have the most noticable effect. Version is 1.0.27_X5091.

Drain pipe releasing steam while Angelica is active:
![image](https://github.com/user-attachments/assets/773ad5c8-99c3-43e0-91e2-e82e75a50bdd)

**Comment by HAJONK** [comment]
I have the opposite problem, certain particles, like the ones from the tsar bomba will cause water to be visible through the particles, like xray

**Comment by HbmMods** [comment]
Render ordering being broken for transparent objects is a pretty old vanilla bug, especially when water and particles are involved. If performance mods break it even further, then there's not a whole lot I can do about it.
