### ISSUE TITLE
game crash when loading world

### ISSUE THREAD

**Issue by qwertog** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1759]
mod version: ntm 5091
after testing a nuke from far away, not visible, i went over to see crater but it crashed. now i cannot go load in, as it crashes.
how do i recover the world 
log: https://pastebin.com/kGScy7AL

**Comment by HbmMods** [comment]
In `forge.cfg`, set `B:removeErroringEntities` to `true`, this should delete entities that throw exceptions instead of crashing the game entirely.
