### ISSUE TITLE
Stereotopical green ooze fog

### ISSUE THREAD

**Issue by Hacker6400** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1760]
When you sink under the stereotopical green pose, it's transparente and there is no fog

**Comment by HbmMods** [comment]
Fog in fluids only applies to anything with the water or lava material, neither of which the green ooze uses, and the geniuses at Mojang made their checks hardcoded. Could in theory be solved with the fog setup event hooks and some custom handling, but the whole system is flimsy enough as-is and would probably clash with the fog stuff we're forced to do for the custom biomes to work.
