### ISSUE TITLE
Enhancement: ToKaMaK reactor Lithium blanket

### ISSUE THREAD

**Issue by TheChosenIndividual** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1764]
More of just a personal pet peeve with the inefficiency of the fusion reactor's breeding channel, as such, i propose a simple item, a blanket for the fusion reactor with the same (or slightly lower) durability of a tungsten reactor blanket, but with a special ability: when the reactor is online, it will consistently output tritium (Through ducts probably) which can then be cycled into the reactor to make plasma

Keep in mind: the lithium blanket is based on real science, so, that should be a bit of realism

Edit: Another reason i believe this is a good idea, is due to automation of the breeding channel being...complicated...to say the least, like having to input or output items on the toroidal magnets, and due to the fact that the input/output process requires filters, otherwise the output will eject EVERYTHING

Thanks, and cya

-Chosen

**Comment by HbmMods** [comment]
nah

**Comment by TheChosenIndividual** [comment]
> nah

_bitch wtf_
