### ISSUE TITLE
[ENHANCEMENT] Add Radiation to Raw EFR ores

### ISSUE THREAD

**Issue by LunatiK-ExpiX** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1765]
The Raw EFR ores don't have radiation when they are supposed to, like Raw Uranium. Adding them should increase compatibility with EFR

**Comment by Vaern** [comment]
NTM ores intentionally don't have radiation values, mainly as QoL for mining in the early game.

**Comment by HbmMods** [comment]
Indeed, all `oreUranium` and `oreThorium` is blacklisted from the hazard system.
