### ISSUE TITLE
Mares leg gun model is bugged

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1768]
"Mare's leg 5373" and "Mare's Leg (Dark) 5374" model sizes are extremely large in the inventory screen in my latest build of the mod.

**Comment by JameH2** [comment]
well the build isnt done yet??????

**Comment by JameH2** [comment]
*the latest release
self compiled commits 99% of the time wont be bugfree

**Comment by BallOfEnergy1** [comment]
genius

**Comment by ghost** [comment]
I will only look for bugs in the official, builds if that is what is helpful.
