### ISSUE TITLE
mushroom clouds not visible

### ISSUE THREAD

**Issue by Kozabeksa69** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1769]
The mushroom cloud dissapears when around 3 chunks away from it. Its there when im close. I dunno if its only this mods issue but i suspect rubidium. The version of hbm im using is  nucleartech-1.18.2-0.0.20.0

**Comment by HbmMods** [comment]
You should probably report this to the [1.18 page](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/issues)
