### ISSUE TITLE
radar

### ISSUE THREAD

**Issue by atomicbastion** [HbmMods/Hbm-s-Nuclear-Tech-GIT#177]
hi im a big fan of the mod and love every aspect but one thing sort of puts this mod back and that is the radars. i have tried to find other mods to cover this area but them to not like to work together so why not ask a question will there be a future update that adds different strength radars like like a short range , mid range and a long range and for every radar they have their own specialty like the long range radar can see multiple targets from a further distance but having less accuracy while the short range having the best accuracy but offering a less response time. and can missiles have like ways of making anti-ballistic missiles miss like a flare system or a radar jammer or something like that.?????

**Comment by sendhelppls213** [comment]
Sir, this is an issue report tool, not a suggestion/request tool.

**Comment by HbmMods** [comment]
no.

**Comment by atomicbastion** [comment]
Your right I was a question.
