### ISSUE TITLE
Feature Idea: Demonic RBMK fuel

### ISSUE THREAD

**Issue by Seagate-1TB** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1771]
I have an idea for a new RBMK fuel called "the demonic RBMK fuel rod" and the descript could be "666kHz" and it should have a flux of 666 and either could be dangerous/linear or the type digamma rods use

666.0RAD/s could be an funny idea as well

I created the chemical structure for everyone to look at (This may need to have AlAs aka "Aluminium Arsenide" added to the mod as well) which could have a description that reads "Tor, Tor, Tor, and more TOR!"

![Screenshot_20241116_232112_KingDraw Chemical Structure Editor](https://github.com/user-attachments/assets/03f389ca-4906-47c6-ac7a-e4c2720f125a)

It's up to everyone to decide what happens to the RBMKs using it once it melts down and explode (I was thinking of a singularity that teleports everything to the nether/hell, incl players and mobs) that lasts for 11 minutes and 6 seconds (666 seconds)

**Comment by BallOfEnergy1** [comment]
what

**Comment by HbmMods** [comment]
can you don't

**Comment by HbmMods** [comment]
![image](https://github.com/user-attachments/assets/15b82950-3e03-4444-b560-f4d46c3a2fdd)
also that's definitely not even how hydrogen works
