### ISSUE TITLE
[Gameplay Enhancement] Make nuke generation quicker a bit like Lucky TNT (It doesnt generate instantly in that mod either but its far more optimized)

### ISSUE THREAD

**Issue by The-Explosive-Chemist** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1778]
Idk if this is possible in 1.7.10 but I would really appreciate it if the nuke generation was better optimized and generally quicker.

**Comment by HbmMods** [comment]
I spent way more time than I'd like to admit reading through LuckyTNT's code just to figure out what I already knew, using their approach for explosions would just make everything way worse.
