### ISSUE TITLE
Can't use gradlew build

### ISSUE THREAD

**Issue by Joey-Destroyah** [HbmMods/Hbm-s-Nuclear-Tech-GIT#178]
C:\Users\Joseph Goldsmith\OneDrive\Desktop\hbm>gradlew build
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:sourceMainJava
:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not find forgeSrc.jar (:forgeSrc:1.7.10-10.13.4.1558-1.7.10).
  Searched in the following locations:
      http://files.minecraftforge.net/maven//forgeSrc/1.7.10-10.13.4.1558-1.7.10/forgeSrc-1.7.10-10.13.4.1558-1.7.10.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 23.885 secs

C:\Users\Joseph Goldsmith\OneDrive\Desktop\hbm>

If you need the stacktrace, then tell me.

**Comment by HbmMods** [comment]
About a week ago one of the files required to set up a 1.7 workspace was removed from the forge servers, so the current way no longer works. I'll change the readme in the near future after I'm done with the current update.
