### ISSUE TITLE
Missles. Issue 

### ISSUE THREAD

**Issue by atomicbastion** [HbmMods/Hbm-s-Nuclear-Tech-GIT#179]
When the missle is launched it disappears or goes at super speed

**Comment by HbmMods** [comment]
Sounds like lag. Could you provide any additional info?

**Comment by atomicbastion** [comment]
I am running the game fine at like 120fps and I'm always monitoring it but
as soon as I launch a missle is goes at super speed when I want it to do
what I did before that was slow at the start then fast or it just vanishes
and then re appears in the sky.

**Comment by HbmMods** [comment]
What missiles exactly? Was it custom missiles or the prebuilt ones? Which launcher did you use?

**Comment by atomicbastion** [comment]
All the missles are doing it and so are the launchers. This happend after
the configuration got deleted and I had to import it back but I decided to
uninstall it and reinstall it but it keeps doing it.

**Comment by HbmMods** [comment]
Missile behavior isn't at all affected by the config. I'm still not sure what exactly the problem is, missiles disappearing might just be them leaving the rendering range, which can be influenced by the mods you use.

**Comment by atomicbastion** [comment]
Yeah it might but the problem is that I used the mod by its self.
