### ISSUE TITLE
Stg's scope is weird

### ISSUE THREAD

**Issue by SmiteX134** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1790]
![image](https://github.com/user-attachments/assets/691c49b4-2d71-40b5-b9f2-81aade1f9712)

**Comment by HbmMods** [comment]
What other mods are you running? The scope is still known to be weird but not *that* weird.

**Comment by SmiteX134** [comment]
I use only NTM and NEI

**Comment by SmiteX134** [comment]
Other guns with a scope are fine
