### ISSUE TITLE
[Preview] Cases are not affected by FOV

### ISSUE THREAD

**Issue by Darek505** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1791]
FOV = 70 (standard)

https://github.com/user-attachments/assets/070a6893-8786-410c-8c4b-77f8d3441c41

---

FOV = 120

https://github.com/user-attachments/assets/2a93b8c4-c0a9-4f42-a530-084180a9617e

This is probably due to the fact that cases are an entity, and changing the client's FOV does not affect their spawn location on the server

**Comment by HbmMods** [comment]
Not sure how or if I can even fix that since the server doesn't keep track of player FOV

**Comment by Darek505** [comment]
I think it is possible to make 2 sided cases: server/client (integrated server)

On the client (integrated server), casings will spawn according FOV, since their place is significant in the context of a first-person view

On the server, casings can spawn the same way as now, since it’s not particularly important there

Although, this is quite difficult to implement, and I think there are better ways
