### ISSUE TITLE
Hematite doesn't want to overflow from the melting furnace

### ISSUE THREAD

**Issue by 123123123-wq** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1794]
A bug that I've spent an inordinate amount of time on. In short: hematite doesn't want to remelt into ingots/blocks, meaning it won't even remelt into the continuous casting machine/casting tank/casting pool even though I used a template to remelt hematite! Without the template, it also doesn't overflow either
![javaw_5yzPiRvTBK](https://github.com/user-attachments/assets/e4123bcc-7556-4175-8b73-ed9496ee1b5e)
![javaw_1GINcIUYRa](https://github.com/user-attachments/assets/6039b210-1de4-4d9a-a11b-f061e9f4f339)
![изображение](https://github.com/user-attachments/assets/fccc25df-33d3-4aa5-a4da-108165fd0307)
Here's an example of iron (below), it's shimmering.
![изображение](https://github.com/user-attachments/assets/1b3525e0-f0e4-4ff5-88ea-e24fd9e87b7c)

HBM version X5091 (latest at the moment)

**Comment by 123123123-wq** [comment]
This is the official version of the mod 1.7.10, if anything, the skin is ported with SkinPort mod

**Comment by R-Kaenbyou** [comment]
Hematite is only used for alloying, not for casting. This is not a bug, because it was designed so.

**Comment by HbmMods** [comment]
Hematite is considered an additive like carbon so it can't be cast. Even if it were castable, it doesn't have any valid shapes you could cast it into, there's no hematite blocks or ingots, just hematite ore. Not even sure what the point of smelting hematite is if you aren't gonna process it into iron to be honest.

**Comment by 123123123-wq** [comment]
> Hematite is considered an additive like carbon so it can't be cast. Even if it were castable, it doesn't have any valid shapes you could cast it into, there's no hematite blocks or ingots, just hematite ore. Not even sure what the point of smelting hematite is if you aren't gonna process it into iron to be honest.

So hematite cannot be converted to iron? Is it only used as an alloy?

**Comment by HbmMods** [comment]
Hematite can be made into iron by using the recipe for it, however doing so doesn't involve pouring it. Insert the template for the recipe, *then* add the hematite (as doing so beforehand will cause the hematite to go in the wrong spot), carbon and flux.

**Comment by 123123123-wq** [comment]
> Hematite can be made into iron by using the recipe for it, however doing so doesn't involve pouring it. Insert the template for the recipe, _then_ add the hematite (as doing so beforehand will cause the hematite to go in the wrong spot), carbon and flux.

Thank you, I was racking my brains before how to turn it into hardware since the Russian-language wiki does not say this
