### ISSUE TITLE
You had one fucking Job... (bug)

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#180]
And you couldn't even get zat right 
![image](https://user-images.githubusercontent.com/38770780/116804660-84177400-aaee-11eb-9d0c-96921ffa27f2.png)

The Bug: there seems to be an error with the Tesla coil armor attachment upgrade rendering in the wrong spot when its placed on an armor stand (Travelers Gear)

on another note the Tesla bolts dont render when it attacks entites when you wear it
![image](https://user-images.githubusercontent.com/38770780/116804718-19b30380-aaef-11eb-87d8-d42c9157afdc.png)

**Comment by rryan-revived** [comment]
my guy acting like the tesla backpack is the mods main fucking feature

**Comment by rryan-revived** [comment]
but no ill put it in the mods bug-reports page 😎

**Comment by rryan-revived** [comment]
What the bobert himself said

"yeah i've seen that
haven't bothered to reply
like
armor attachments aren't even supposed to render on non-players
it's just that one mod that fucks up rotation for their dummy player
and the arc renderer was left out on purpose"

**Comment by rryan-revived** [comment]
he wont write a patch for travelers gear, plus the arc renderer was left out for a reason.

**Comment by Shibva** [comment]
alright, at least have them share what methods they use to render the armor so that it could possably be made invisable when on such stand for the HBM end

**Comment by HbmMods** [comment]
Armor attachments are part of the player rendering event which relies on a player actually wearing the armor. It seems like TG is rendering the armor stand with an invisible dummy player unlike BilbioCraft which just renders the ModelBiped outright, hence why armor mods aren't present. It just seems like the dummy player isn't positioned right, causing the mods being placed in weird places. While I _can_ fix that, it's so much of a fringe-case non-issue that I'm not going to spend any time trying to solve this, you may consider this an unintentional easter egg for all I care.

And let's be real, having the coil come out of the guy's face is hilarious.

**Comment by Shibva** [comment]
... thats so true
the guy had one job XD
