### ISSUE TITLE
FBI is broken

### ISSUE THREAD

**Issue by SmiteX134** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1801]
FBI agents are still using the old guns which one shot everything

**Comment by HbmMods** [comment]
they currently use paper cutouts of guns because the military industrial complex isn't doing so great right now

**Comment by SmiteX134** [comment]
Why not sticks

**Comment by HbmMods** [comment]
i didn't test them in the slightest because i hate this shitass feature but i replaced the old guns with the new ones so i'm guessing it's fixed now
