### ISSUE TITLE
HBM zh_cn-Lang error

### ISSUE THREAD

**Issue by UlyssesHayes** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1809]
### HBM X5180 zh_cn-Lang error
This is a serious problem. When I switch the language to Simplified Chinese, the names of some items are still in English or have an extra ".name" appended to them. I found that the zh_cn-lang file in version X5180 of HBM is different from that of the old version. The ".name" is missing after the item IDs. I suspect that this is the cause of the error. Later tests showed that it was indeed this reason that led to the error

**Comment by HbmMods** [comment]
should have been resolved with #1805
