### ISSUE TITLE
(1.12.2) Guns not firing when left clicked

### ISSUE THREAD

**Issue by Goosegg23** [HbmMods/Hbm-s-Nuclear-Tech-GIT#181]
at first, when I installed the mod, guns worked fine. however, after using the minigun for a little while, no other gun would fire. they would reload and aim but not shoot. I then made a new world and they didn't work there, either. turrets and bombs still work, as does basically everything else as far as I know. right-click weapons such as the Immolator work fine too.

**Comment by TheForge129** [comment]
use the 1.12.2 issue tracker
https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/issues/new

**Comment by Goosegg23** [comment]
ah, thanks. My bad!

**Comment by TheForge129** [comment]
don't feel bad, i once opened a pull request for an outdated repository
because the 1.12 version had no issue tracker and i didn't really know how
github worked
