### ISSUE TITLE
The new guns don't break glass?

### ISSUE THREAD

**Issue by UlyssesHayes** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1813]
### The new guns don't break glass?
**version: 1.0.27 X5180**    
1.The error that guns other than destructive guns and ammunition cannot break glass (note: Guns before X5180 can break glass)
2.Guns can't break glass means bullets can't penetrate the glass to attack entities behind it, but this is just a minor issue

**Comment by HbmMods** [comment]
known issue, should have been resolved with commit ce3bff9
