### ISSUE TITLE
Add gun fault animation

### ISSUE THREAD

**Issue by 2Canned** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1814]
Perhaps it is possible to add fault animations to those firearms. The probability of occurrence is affected by factors such as the durability of the firearm and the materials used. For example, when the durability is below 50%, the firearm will begin to malfunction, but the probability is relatively small. When the durability is below 33%, the probability will increase significantly. If the materials used to manufacture firearms are poor, the probability of failure will be higher. If the materials used are normal, the probability of failure will be normal. If high-quality materials such as desh and sa326 are used, the probability of failure will remain extremely low or even be eliminated. These faults may include poor ammunition supply, detachment of fixing devices, jamming, etc. When a malfunction occurs, players need to press the R key to handle it, otherwise they will not be able to continue using the gun for shooting.

**Comment by HbmMods** [comment]
no
