### ISSUE TITLE
Enhancement: Remove molten wood

### ISSUE THREAD

**Issue by R-Kaenbyou** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1815]
Molten wood is unbelievably unreasonable, remove it please!
![8FD39F023941139C9C7EBB66FBC812B7](https://github.com/user-attachments/assets/22015de3-e1c2-4bfe-aa2b-96dfb81f4dcf)

**Comment by HbmMods** [comment]
Apparently a problem with the crucible accepting things marked as `NOT_SMELTABLE`
