### ISSUE TITLE
Enhancement: Make foundry basin's mold easily changeable

### ISSUE THREAD

**Issue by Agarmal** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1819]
`Foundry Basin`s and `Shallow Foundry Basin`s have an annoying problem: **their molds can't be quickly changeable**. You have to destroy them in order to place them again with a different mold...

It would be much better being able to just **right-click the basin with a different mold to change it**, returning the mold previously placed in it back into the slot the new mold was.

Thanks for reading

**Comment by HbmMods** [comment]
You can take molds out with a screwdriver

**Comment by SmiteX134** [comment]
👆

**Comment by Agarmal** [comment]
oh sorry.
