### ISSUE TITLE
Boiler not accepting fluid

### ISSUE THREAD

**Issue by onIceD** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1820]
I try to turn my crude oil to hot crude oil with the default boiler, but its just not accepting my fluid barrels and everything else.
![Base Profile Screenshot 2024 12 22 - 22 08 29 06](https://github.com/user-attachments/assets/4fb094ad-a452-4389-8653-883a7a44d7a4)

**Comment by HbmMods** [comment]
I think 1.12 has partially fillable canisters so it looks like it should work (in 1.7 barrels refuse to empty into anything that doesn't have enough space). No clue though, you might want to ask on the 1.12 repo about 1.12 problems.
