### ISSUE TITLE
Boiler not accepting crude oil

### ISSUE THREAD

**Issue by AnRac00** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1822]
I'm trying to convert my crude oil into heated crude oil, but there's no way to do so. I'm playing on HBM-NTM-[1.0.21_X5027].jar, MINECRAFT 1.7.10, the NEI mod shows no recipe for "OIL HEATER" and the "BOILER" mod doesn't allow any fluid other than water.
Any solution?
![oil heater](https://github.com/user-attachments/assets/29ca3e7c-3801-4ec7-ae27-2af7d221d7d1)

**Comment by SmiteX134** [comment]
Oil heaters are disabled and their recipes were removed, use industrial boiler or regular one

**Comment by HbmMods** [comment]
The large copper boiler can have its input type set via fluid ID, the old oil heaters are deprecated and only spawn as decorative elements in some structures in the most recent versions.
