### ISSUE TITLE
Questions about Charms of Protection and Meteor Charms

### ISSUE THREAD

**Issue by Agarmal** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1824]
I have two questions:

1. Do Meteor Charms **disable meteor generation worldwide**? If not, what's the effective range?
2. Is it possible to make Meteor Charms or Charms of Protection work in my server **while I'm away**? Like, placing it somewhere and keeping it chunkloaded (specially for power plants that need to be always online), or do I have to use the forcefield?

I couldn't find answer to these questions online,
thanks in advance.

**Comment by HbmMods** [comment]
The way meteors work is that the game chooses a random player as a "target", then spawns a meteor in the loaded area around that player (I think 200 blocks in each direction). If that target has a charm, then the meteors are not spawned (or spawned with a lower likelihood, depends on the exact one). If there's two players, one with a charm and one without, there can still be meteors in the first player's range, if the game chose the second player as the target, and both players are in close proximity.
