### ISSUE TITLE
crash when shift clicking in smelter gui 

### ISSUE THREAD

**Issue by Gregorycat101** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1828]
[crash-2024-12-24_23.59.04-client.txt](https://github.com/user-attachments/files/18243440/crash-2024-12-24_23.59.04-client.txt)
open up the smelter gui and shift left click 2 steel plates into the smelter this will result in a crash

**Comment by QuadBitBrain** [comment]
Same issue for me, also happens if inserter tries to insert an item into a crucible
