### ISSUE TITLE
Regarding the issue of armor damage resistance

### ISSUE THREAD

**Issue by 2Canned** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1829]
Will the damage resistance of armor continue to be improved after x5188, and will the damage limit, damage threshold, fire resistance, and other effects of armor be added again or with similar effects in versions before x5180? And how will the complete armor resistance system operate?

**Comment by HbmMods** [comment]
Damage threshold still exists, in fact it is now dependent on the damage type instead of being one DT value for everything. Damage caps have been removed and won't return.
