### ISSUE TITLE
Replace the Removed Lunatic Sniper Rifle with the Lunarian Service Rifle

### ISSUE THREAD

**Issue by LunatiK-ExpiX** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1830]
Ditto, given how the Lunatic Sniper Rifle was one of the most unique weapons, it should have an equivalent that it gets replaced with to not completely remove the reference of the original. I recommend making it still quite expensive, but not as expensive as the original, but reduce the damage done to balance it out.

**Comment by HbmMods** [comment]
A Hecate II is planned, but the model hasn't been made yet. A direct successor to the lunatic rifle isn't planned.
