### ISSUE TITLE
Enhancment: Redstone Lock

### ISSUE THREAD

**Issue by ssdcurve** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1832]
I was wondering if we could get something like a redstone lock? like an item to make doors only open via redstone and not open when clicking.

(ver is 1.0.27 X5027)

**Comment by HbmMods** [comment]
no

**Comment by BruhBronxy** [comment]
I'm curios why you are opposed to making doors open with a redstone signal instead of a right click?

**Comment by ssdcurve** [comment]
combine with securitycraft to make keycard doors
also combination lock doors and more

im fine with making them open on right click i just want it to be more immersive when i build stuff
like make a redstone link to a vault door so you need to go to a special control room or sumthn
