### ISSUE TITLE
cyclotron blew up and now the server crashes on startup

### ISSUE THREAD

**Issue by BayCan59** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1836]
i tried using the cyclotron, and overheated. and the last thing i saw was the chat message that i died of a nuclear explosion before the server crashed. now i can start the server fine, but whenever someone joins the server immediately crashes.

here are the crash logs in order from the initial crash, the first time i tried joining, and the most recent time i tried joining

[first crash log.txt](https://github.com/user-attachments/files/18266618/first.crash.log.txt)

[first join crash log.txt](https://github.com/user-attachments/files/18266619/first.join.crash.log.txt)

[latest join crash log.txt](https://github.com/user-attachments/files/18266620/latest.join.crash.log.txt)

**Comment by HbmMods** [comment]
You probably want to report that to NTM Extended Edition instead

**Comment by BayCan59** [comment]
alright will do
