### ISSUE TITLE
RBMK reactor subcritical or critical on low power

### ISSUE THREAD

**Issue by rysiu2007** [HbmMods/Hbm-s-Nuclear-Tech-GIT#184]
RMBK reactor isn't outputting any heat on default gamerule settings. Even with digamma fuel it isn't working. Not self-igniting fuels  are having too small neutrons to operate and they just poisoning with xenon. Just make every fuel more sensitive to neutrons.

**Comment by rysiu2007** [comment]
But congrats for explosion effects

**Comment by UFFR** [comment]
You do realize the RBMK and its components still aren't finished and 
this is just a demo right?

-- 
UFFR

**Comment by rysiu2007** [comment]
I know

**Comment by rysiu2007** [comment]
But info is always useful

**Comment by Big-Boofer** [comment]
My cum barrels are awakening

**Comment by rysiu2007** [comment]
Testing if the issue was solved...
