### ISSUE TITLE
oil refinery UI not working

### ISSUE THREAD

**Issue by floorwaxer2** [HbmMods/Hbm-s-Nuclear-Tech-GIT#189]
![2021-05-16_18 36 41](https://user-images.githubusercontent.com/48165383/118415020-e7201380-b675-11eb-8c4a-0d2ea2e9ab43.png)

**Comment by Drillgon200** [comment]
Mug moment.

**Comment by sendhelppls213** [comment]
![fuckthis](https://user-images.githubusercontent.com/57670225/118415119-d3af8f80-b6eb-11eb-9293-2418a2da3703.png)

**Comment by 9Valjew** [comment]
I swear to fucking god

**Comment by ShimmeringBlaze** [comment]
God fucking damn it
