### ISSUE TITLE
Request: MineTweaker Support

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [HbmMods/Hbm-s-Nuclear-Tech-GIT#19]
Since so many items are now made in the Assembly Machine instead of the vanilla crafting table, it is no longer possible to change their recipes using MineTweaker. It would be useful to be able to write MT scripts to add/edit/remove recipes from the Assembly Machine, Chemical Plant, Centrifuge, etc. If that is too time consuming, allowing users to disable specific recipes in a config file would work as a substitute.

**Comment by HbmMods** [comment]
No idea how MT's API works, however it shouldn't be too hard to make my own config for machine recipes. I'll think about it.
