### ISSUE TITLE
I got banned from the discord server for no reason

### ISSUE THREAD

**Issue by I-Like-kittys** [HbmMods/Hbm-s-Nuclear-Tech-GIT#190]
Help my Discord name is O5-1 Penaut (lvl 25) can u unban me?

**Comment by sendhelppls213** [comment]
rules exist for a reason.

**Comment by sendhelppls213** [comment]
and you failed to comply.

**Comment by ShimmeringBlaze** [comment]
You were banned because you left and rejoined after you were punished for something

**Comment by I-Like-kittys** [comment]
well im sorry give me one more chance plz

**Comment by Big-Boofer** [comment]
thats like running someone over, having to go to court, not going to court, 5 days later trying to come clean and then asking for forgiveness

**Comment by Big-Boofer** [comment]
> 
> 
> well im sorry give me one more chance plz

and sorries dont fix much

**Comment by ShimmeringBlaze** [comment]
We have clear rules about leaving and rejoining just to clear roles
![image](https://user-images.githubusercontent.com/67163329/119061887-a8020300-b992-11eb-97b9-8391d2d33023.png)

**Comment by I-Like-kittys** [comment]
ohh im sorry I am bad with memory I also didn't see that ):

**Comment by Big-Boofer** [comment]
Bob literally told everyone to read them

**Comment by ShimmeringBlaze** [comment]
Rules are there for a reason, and it's your responsibility to keep them in mind, if you forget them, that's on you

**Comment by Big-Boofer** [comment]
![Uploading Screenshot 2021-05-20 164559.png…]()

**Comment by I-Like-kittys** [comment]
Can I pleaassseee have just 1 more chance I swear on my life that I will be a good guy

**Comment by Big-Boofer** [comment]
Fuck No

**Comment by ShimmeringBlaze** [comment]
No, that's final

**Comment by Big-Boofer** [comment]
Nein

**Comment by I-Like-kittys** [comment]
ok... ):

**Comment by Big-Boofer** [comment]
good boy
