### ISSUE TITLE
Sorry i posted in the wrong place

### ISSUE THREAD

**Issue by LorenzoMJ02** [HbmMods/Hbm-s-Nuclear-Tech-GIT#192]
Sorry i posted in the wrong place

**Comment by sendhelppls213** [comment]
Sir, this is a github issue page.

**Comment by LorenzoMJ02** [comment]
> Sir, this is a github issue page.

I'm sorry I never used GitHub
How I correct

**Comment by sendhelppls213** [comment]
Usually people go here when they have a bug or an issue to report. All the suggestions or request are usually handled via direct communication with the lead developer.

**Comment by HbmMods** [comment]
You could always just close the issue instead of breaking it :P
