### ISSUE TITLE
Boilers not accepting oil

### ISSUE THREAD

**Issue by floorwaxer2** [HbmMods/Hbm-s-Nuclear-Tech-GIT#193]
I am playing on a server with a small community of about 8 players. Boilers were working after an update but then stop after a day or two. I have tried using all kinds of pipes like mekanism mechanical pipes, hbm universal pipes, extra utilities transfer nodes. I cant move forward with the mod without making hot oil from the boiler.

![2021-05-29_13 37 32](https://user-images.githubusercontent.com/48165383/120079700-1e81bd80-c083-11eb-8a20-27f919706124.png)
![2021-05-29_13 37 30](https://user-images.githubusercontent.com/48165383/120079702-1e81bd80-c083-11eb-9b67-e255e6ec4ca0.png)

**Comment by Big-Boofer** [comment]
What version are you on?

**Comment by Drillgon200** [comment]
Can you upload a log?

**Comment by floorwaxer2** [comment]
Minecraft version 1.12.2     forge-14.23.4.2855  

Waiting on server owner for log he is off right now.

**Comment by JohnnyDabb2** [comment]
This is the latest.log of the server that he is referring to --> https://drive.google.com/file/d/1cIcDMmiShrCrFWIfhKgbZGUIPglgZ1JY/view?usp=sharing

I am the owner.

**Comment by Drillgon200** [comment]
![image](https://user-images.githubusercontent.com/50186362/120256270-9cd88e00-c242-11eb-8a9d-f802ab4bf9c0.png)
Probably not related to this issue, but looks like you set some invalid config values.

**Comment by Drillgon200** [comment]
I'm pretty sure I fixed all this garbage. What's the jar's name?
![image](https://user-images.githubusercontent.com/50186362/120256858-e7a6d580-c243-11eb-8dd4-72a4e8bc5875.png)

**Comment by JohnnyDabb2** [comment]
I didn't update it from 1.4.1a because every time I tried to it would result in some weird issues with Optifine.  Not entirely sure if it was hbm that caused this however, because I'd always update it along with other mods.

**Comment by Drillgon200** [comment]
I'm not going to look into an issue that may or may not already be solved in a later version. Optifine's fast render conflicts with NTM's shaders. You can disable NTM's shaders by turning enableShaders2 in the config to false. You can disable Optifine's fast render in video settings. I plan on disabling my shaders by default next update until I get a chance to work on compatibility a bit more.

**Comment by JohnnyDabb2** [comment]
That's totally understandable.  Thanks for the help.

**Comment by Shibva** [comment]
Yes, I was the person that found out this bug orignialy when oil from Galaticraft was accepted First, this was however noy for the 1.12.2 version and after some work was hopfuly corrected

**Comment by Shibva** [comment]
this bug should have been fixed in the lattest 1.12.2 release, I was told that this was fixed I belive but I dont fully recall

**Comment by UserDeleted-404** [comment]
Guys if you uisng Galacticraft, it's reason of problem, oil names are same and HBM don't know which oil to use, so try to trun off galacticraft and check

**Comment by Me1234589** [comment]
So I found that if you install the HBM bug fix mod it solves this issue still don't know what causes it but that's a fix.[](https://www.curseforge.com/minecraft/mc-mods/hbm-fixesl)
