### ISSUE TITLE
java.lang.IndexOutOfBoundsException (Cant enter world)

### ISSUE THREAD

**Issue by Bastitron** [HbmMods/Hbm-s-Nuclear-Tech-GIT#194]
Hello my english is not the best so sorry for the ugly text :( ,
My issue is that if i try to enter a world in the newest mod and forge version it would crashing. 
The Crash report is in the file
[crash-2021-05-29_23.02.38-client.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/6565318/crash-2021-05-29_23.02.38-client.txt)

**Comment by HbmMods** [comment]
Go into your graphics settings and lower your render distance. You'll probably find that the distance slider is outside the usual range.

**Comment by Bastitron** [comment]
Sorry i know its not a new functions channel but i like the Fallout 4 doors that you made.
And its cool if you add more doors or elevators from Fallout 4 :)
