### ISSUE TITLE
Screen Issue

### ISSUE THREAD

**Issue by Fur-Politician** [HbmMods/Hbm-s-Nuclear-Tech-GIT#197]
Well for some reason when I start Minecraft forge 1.12.2 with this mod lastest version the screen goes black and white and my computer lags terribly...

I have a toaster and my graphics card is an Radeon C-60 

I just want to know if it's my graphics card or is something in the mod.

**Comment by Drillgon200** [comment]
It's probably optifine conflicting with NTM. Make sure fast render is disabled. Alternatively you can disable shaders in the NTM config by setting enableShaders2 to false.

**Comment by Drillgon200** [comment]
If your PC isn't good, you probably want to go with the disabling shaders route.

**Comment by Fur-Politician** [comment]
Hi again! Sorry for not responding ,you were right ,optifine is conflicting with HBM but I deactivated Fast render and it's working fine ,but I can't set FPS limits or use some of the optifine options because it immediately crashes , however really thanks for the solution .I am creating a surprise server for playing a war (not serious) Roleplay
