### ISSUE TITLE
Request: Fluid Compatibility

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [HbmMods/Hbm-s-Nuclear-Tech-GIT#2]
I've tried using EnderIO fluid conduits with the small nuclear reactors and it did not work. It would be very useful if water, coolant, deuterium, tritium, uranium hexafluoride, plutonium hexafluoride, diesel fuel etc. were Forge fluids which could be pumped in and out of machines using other mods' pipes without needing cells or rods.

**Comment by HbmMods** [comment]
Having them as forge fluids wouldn't be a problem, it's more that machines would need some kind of special fluid container class, I'm not sure if that's a built-in forge thing or if I need a lib for that.

**Comment by HbmMods** [comment]
Bad news - forge has multiple classes that look like they could work with buildcraft, but I still can't figure out what exact classes have to be used and in what way to use them so buildcraft would recognize it. I haven't found any proper documentation or examples from other mods (as they either don't have that sort of integration, use a different version or are simply obfuscated to some extent) just by trial and error alone it could take weeks (if it worked at all) to figure out how to make machines fluid compatible.

**Comment by bHXDgiuMa5yLHyC8** [comment]
I think https://github.com/JohannesGaessler knows a lot about implementing fluid containers in machines, maybe you could ask him for advice.

**Comment by HbmMods** [comment]
That's beautiful, the complexity of his work will make figuring out the basics very hard, but I think I can work with that.

**Comment by HbmMods** [comment]
Or I could add an analog adapter piece of sorts. For instance, BC item pipes don't work with my machines as they don't use the predefined hopper ports (I think AE wires use those if I remember correctly) so instead, one could feed the hoppers via BC pipes and the hoppers are connected to the machines.

Same thing could work for fluids, I could add a funnel that absorbs ajacent fluids and pipes them into machines (I've already though out a different, more simple fluid containment system). one could connect BC pipes with machines by placing a floodgate over such a funnel as a kind of adapter.

It's one of these crappy approaches I'm famous for, it's by far not as professional but it'd be much more fun to make.

**Comment by TheMiCraft** [comment]
Is it now possible to connect both?
If yes how?
