### ISSUE TITLE
Antimatter clusters not clearing Digamma Particle Black Hole Correctly

### ISSUE THREAD

**Issue by blinkor** [HbmMods/Hbm-s-Nuclear-Tech-GIT#202]
It seems that when a Digamma Particle Black hole is created from dropping the Digamma particle, and a heavy antimatter cluster is dropped to remove the black hole, it creates crushed obsidian, stops the sound of the black hole, and removes the destruction of the black hole but does not remove the animation of the black hole itself.

![image](https://user-images.githubusercontent.com/66094636/121789482-7e07bf00-cb93-11eb-9347-df071e7093db.png)

**Comment by ShimmeringBlaze** [comment]
That's a known bug, relog and it should update

**Comment by HbmMods** [comment]
Fixed in X3913.
