### ISSUE TITLE
an issue regarding the new Depth Block 

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#204]
While I like the idea, I just came to a thought about how easy it can be to trap yourself or others inside of a box made of it, and considering that only explosive can break it, you might be out of luck

Hence I have thought of a quick solution; add a new block, Cracked Depth Blocks.

Crack Depth Blocks are obtained from blasting apart Depth Rock with explosives and will drop instead of Regular Depth Blocks as they do now. The Major Difference between the 2 is that Cracked Depth Block is minable, but takes twice as long to mine a block of Obsidian with a diamond pickaxe

**Comment by HbmMods** [comment]
Probably resolved by the fact that tier 2 pickaxes can now break depth rock outright. It's still possible to trap yourself, but suicide is always an option.
