### ISSUE TITLE
RBMK Steam Connector

### ISSUE THREAD

**Issue by Nuclearenergy1415** [HbmMods/Hbm-s-Nuclear-Tech-GIT#206]
There is a problem in that block because RBMK Steam Channels Didn't output steam on down side & Its reactor steam Output on upper side only in RBMK Steam Channel 😩😥

**Comment by HbmMods** [comment]
What?

**Comment by MAX2136** [comment]
That's... what the steam connector is for
You place it under the steam channel and you can then pull steam out of it (the connector)
