### ISSUE TITLE
Suggestion: Californium

### ISSUE THREAD

**Issue by I-Like-kittys** [HbmMods/Hbm-s-Nuclear-Tech-GIT#207]
Californium is a strong radioactive element this Is what google says: Californium is a radioactive chemical element with the symbol Cf and atomic number 98. The element was first synthesized in 1950 at the Lawrence Berkeley National Laboratory, by bombarding curium with alpha particles, I recommend getting californium-252 as first it is used in rbmk's and second its the most well known so it could be a really strong Rbmk fuel.

**Comment by sendhelppls213** [comment]
Sir/maam, this is where you report issues, not make suggestions/requests.

**Comment by I-Like-kittys** [comment]
People do make suggestions here... I think

**Comment by sendhelppls213** [comment]
if they do it then they aren't doing it in the right place.

**Comment by I-Like-kittys** [comment]
I was banned from the discord how can I suggest?

**Comment by sendhelppls213** [comment]
then you can't. congratulations.

**Comment by I-Like-kittys** [comment]
Question are you an admin?

**Comment by I-Like-kittys** [comment]
I don't think so...

**Comment by I-Like-kittys** [comment]
Not saying anything

**Comment by I-Like-kittys** [comment]
well anyways I just hope they add it

**Comment by TheForge129** [comment]
Yes, he is an admin

**Comment by I-Like-kittys** [comment]
...

**Comment by I-Like-kittys** [comment]
no plz don't I support this I admit I was being a b*tch

**Comment by I-Like-kittys** [comment]
I just want it added

**Comment by I-Like-kittys** [comment]
I understand if hbm does not like me he makes a damn good mod tho...

**Comment by sendhelppls213** [comment]
not to spoil updates or anything but it, sooner or later, will be added.

**Comment by I-Like-kittys** [comment]
HYPE!!!!!

**Comment by I-Like-kittys** [comment]
aight ima close dis

**Comment by I-Like-kittys** [comment]
byyyyyeeee

**Comment by TheForge129** [comment]
I received 20 emails from this and most, if not all of them were
unnecessary.
Thank God it's over

**Comment by username90001** [comment]
> Californium is a strong radioactive element this Is what google says: Californium is a radioactive chemical element with the symbol Cf and atomic number 98. The element was first synthesized in 1950 at the Lawrence Berkeley National Laboratory, by bombarding curium with alpha particles, I recommend getting californium-252 as first it is used in rbmk's and second its the most well known so it could be a really strong Rbmk fuel.

there was concept to use californium for bullet sized nuclear devices - imagine tank getting heated to few thousands degrees with just one bullet
