### ISSUE TITLE
Can't we make monsters with gas masks spawn less?

### ISSUE THREAD

**Issue by SpencerMeow** [HbmMods/Hbm-s-Nuclear-Tech-GIT#208]
Every 1/4 zombie wears some sort of gas mask and there's no place in the config to turn it off or reduce it.

**Comment by HbmMods** [comment]
Config option `12.D01_enableMobGear` has been added.

**Comment by SpencerMeow** [comment]
> Config option `12.D01_enableMobGear` has been added.

I can't find it anywhere

**Comment by SpencerMeow** [comment]
Is that on the latest 1.12.2 version?

**Comment by HbmMods** [comment]
I made the option 5 minutes ago, you'll have to wait until the next release.

**Comment by SpencerMeow** [comment]
> I made the option 5 minutes ago, you'll have to wait until the next release.

Oh wow that was quick
