### ISSUE TITLE
max frame rate changes to 10 when using latest beta hbm1.0.27_BETA3111

### ISSUE THREAD

**Issue by RagexPrince683** [HbmMods/Hbm-s-Nuclear-Tech-GIT#21]
max framerate keeps changing itself to 10 or 60 with hbm beta 3111 installed.

**Comment by Nos74** [comment]
Quit blaming the mod for your own stupidity/shitty vietnamese hardware, lmao

**Comment by RagexPrince683** [comment]
it legit only happens with hbm installed lmao

**Comment by HbmMods** [comment]
I can't fix an issue that I can not replicate.

**Comment by RagexPrince683** [comment]
I am using mac not sure if that would be a problem or not, I think its the new textures, something is really wrong for me, I can show you proof.
