### ISSUE TITLE
lighting issues when interacting with Hardcore Darkness

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#210]
A small note I made is that when lights such as an Anti-Schrabidum folkvangr field causes all the light that exist in the darkness to turn cyan for a brief moment

This might have something todo with Hardcore Darkness removing the minimal light level, would be nice if this was fixed, and might not be a bad idea to test other explosions along with it

**Comment by Shibva** [comment]
If the Folkvangr Field is going to be reworked, it might be best to also look into this issue

**Comment by HbmMods** [comment]
I'm not sure what the actual problem is

**Comment by Shibva** [comment]
the affect might only be noticeable at night

Steps to Recreate:
1. Install Hardcore Darkness
2. Lauch game and enter a world in creative
3. set it to midnight
4. Drop a item that will produce a FolkVangr field
5. see the lighting glitch (screenshots comming, please hold)
6.

**Comment by Shibva** [comment]
ok heres the screenshots
(Note: it was found to also be with the nuclear charge as well)
Before detonation
![image](https://user-images.githubusercontent.com/38770780/123487156-655bc800-d5db-11eb-953f-79aa02448927.png)

After Detonation
![image](https://user-images.githubusercontent.com/38770780/123487182-71e02080-d5db-11eb-9f06-eaa05c37cd0d.png)
Notice the blue light, this is the issue I am talking about

the issue is __NON-Existent When its day__ (as can be seen here)
![image](https://user-images.githubusercontent.com/38770780/123487318-a653dc80-d5db-11eb-9630-33597abad8e0.png)

**Comment by Shibva** [comment]
this interaction can be found with this [mod](https://www.curseforge.com/minecraft/mc-mods/hardcore-darkness)

**Comment by HbmMods** [comment]
I have no idea what Hardcore Darkness does exactly, let alone how it works. Since it apparently changes the way lighting works on a fundamental level, I'm not sure what I'm supposed to do about it.

**Comment by Shibva** [comment]
alright, it seems to be Open Source so maybe someone else can figure it out, 

heres the link to its github https://github.com/lumien231/Hardcore-Darkness

Hope this can help in some way

**Comment by HbmMods** [comment]
The fleija orb does literally only two things, it renders a fullbright orb with no lighting (similar to burning entities or blazes) and it increments the lightning timer to keep the sky bright, that's it. If something as basic as that somehow breaks when combined with a mod that *uses ASM to change the vanilla lightning engine* then I'm sorry but there is nothing I can do about that. Either ask the HD devs about it or live with it.

**Comment by Shibva** [comment]
ok, thank you for the response and explanation

**Comment by Shibva** [comment]
Unrelated final note: Nuclear Creepers blowing up dont seem to cause this issue

**Comment by HbmMods** [comment]
Because nuclear creepers use a smaller particle effect that doesn't cause the sky to flash.

**Comment by Shibva** [comment]
I also decided to test this with Complementary Shaders and the shaders actually work on Complimentary Mode, just thought I should let you know in terms of the nuke rendering

**Comment by RagexPrince683** [comment]
in other news: doge still installing infinite mods and wondering why errors are happening

**Comment by Shibva** [comment]
This was in a modpack called GTNH
