### ISSUE TITLE
I don't think I can get the newest version please help

### ISSUE THREAD

**Issue by I-Like-kittys** [HbmMods/Hbm-s-Nuclear-Tech-GIT#212]
I think there is an issue where I can't download the latest version its been stuck on beb for 11 day's, and I wonder if either you have not made it or I just can't download it.

**Comment by divine-ray** [comment]
bob simply hasnt got around of making a new release. all you can do is wait.

**Comment by HbmMods** [comment]
X3902 from the release "beb" *is* the latest version.
