### ISSUE TITLE
Blocks do not break after being hit by a rocket

### ISSUE THREAD

**Issue by FlappyBanan** [HbmMods/Hbm-s-Nuclear-Tech-GIT#225]
When I fire a rocket at blocks from the HBM mod. They just don't react to it at all. Any missile !! How can you arrange PVP if the base blocks do not break?

**Comment by HbmMods** [comment]
What's the base made from and what missile did you use?

**Comment by FlappyBanan** [comment]
I used a lot of concrete, reinforced concrete and many other blocks. In the test world, literally everything. The missiles are all high-explosive. Well, nuclear ones do not break anything either.

**Comment by HbmMods** [comment]
All of the blocks you've mentioned are blast proof, though usually a direct hit with a nuke should at least create a small hole in concrete. High-explosive missiles use standard vanilla explosions which are simply upscaled, so they won't do anything at all.
