### ISSUE TITLE
How can I get meteorite_ingots and meteorite_knife?

### ISSUE THREAD

**Issue by rick-200** [HbmMods/Hbm-s-Nuclear-Tech-GIT#229]
I tried burn meteorite powder and decompose meteorite block, nothing did I get.

**Comment by thePalindrome** [comment]
The ingots are produced by using a blast furnace to combine a meteorite block (not the broken one), and some cobalt. The wiki notes it but it's never shown in game (regardless of polaroid status).
I'd personally say that swings into "bug" territory and will just cause more questions like this to crop up
