### ISSUE TITLE
max frame rate still changes to 10 AGAIN i'm using mac something to do with your new textures

### ISSUE THREAD

**Issue by RagexPrince683** [HbmMods/Hbm-s-Nuclear-Tech-GIT#23]
alright, I know what I'm seeing, this is a bug I can show you proof im using a mac, I tried it with vanilla, technic, still nothing your mod is editing my max fps every time I left click please fix this, I can't use your mod without lagging.
![2019-06-19_21 39 27](https://user-images.githubusercontent.com/49804375/59819057-696df480-92f4-11e9-9e21-fadfb5e8fffd.png)
![2019-06-19_21 44 44](https://user-images.githubusercontent.com/49804375/59819068-72f75c80-92f4-11e9-8352-e47382f5f0fa.png)
![2019-06-19_21 44 32](https://user-images.githubusercontent.com/49804375/59819083-77bc1080-92f4-11e9-8a59-0cb93f929af5.png)

**Comment by HbmMods** [comment]
For the third time, if I can't replicate the issue, if there's no log or anything tangible that would explain what's happening on a technical level, there's absolutely nothing that can be done about this. And blaming some new textures is stupid, they are loaded and used the exact same way as any other texture, and there's no way they could ever automatically change your FPS settings.

**Comment by RagexPrince683** [comment]
you did something in that update, what did you do?

**Comment by RagexPrince683** [comment]
Fixed:
*Fixed potential 0-division crash for fallout entities
*Fixed boats creating boxcar death message
*Fixed memory-leaks and frame drops for certain clients

^ whatever you did here screwed me

**Comment by Nos74** [comment]
Get cucked, nerd

**Comment by HbmMods** [comment]
fixed in X3182
