### ISSUE TITLE
Crash near   the 0,500,0

### ISSUE THREAD

**Issue by mcmso** [HbmMods/Hbm-s-Nuclear-Tech-GIT#232]
https://paste.ubuntu.com/p/hYSRzbJGqj/
 
Hi HBMTheBobcat, this is my Crash

**Comment by TheForge129** [comment]
[image: image.png]
just make the bound positive

**Comment by HbmMods** [comment]
The "bound" in that case is a range in a randomizer function. The object causing the crash is a little satellite that is rendered over spawn that displays a small random message. Usually it'd fetch a list of messages from a github gist page, but even if that fails it should add one default message to appease the randomizer needing a value above 0. Not sure why that still happens but I've added a few additional checks to keep it in order. I'll close the issue as soon as the new release is out.
