### ISSUE TITLE
[Question] How to fuel the ion jetpack on the winged lunar chestplate?

### ISSUE THREAD

**Issue by Joey-Destroyah** [HbmMods/Hbm-s-Nuclear-Tech-GIT#234]

**Comment by HbmMods** [comment]
It's electric, so long as you have the full armor set it works.

**Comment by Joey-Destroyah** [comment]
Only the Chestplate, leggings, and boots are in the creative menu... What helmet do I use?

**Comment by HbmMods** [comment]
The eyepatch with thermal sensor, it's the item right before the chestplate in the creative inventory.

**Comment by Joey-Destroyah** [comment]
oh ok. Thanks
