### ISSUE TITLE
Request: More Warheads!

### ISSUE THREAD

**Issue by Joey-Destroyah** [HbmMods/Hbm-s-Nuclear-Tech-GIT#236]
Maybe you could add more custom warheads or crafting recipes. Maybe some more 2.0 unit parts. No need to rush.

**Comment by sendhelppls213** [comment]
You are supposed to report issues here, not ask for stuff to be added.

**Comment by Joey-Destroyah** [comment]
Someone mentioned something about HB having a discord server, but every invite link was invalid...

**Comment by SoB1nary** [comment]
https://discord.com/invite/YDUWGaf
if this one is invalid, you're banned

**Comment by HbmMods** [comment]
There's no person with "joey" in the name on the ban list.

**Comment by Joey-Destroyah** [comment]
The link worked, thanks!
