### ISSUE TITLE
Game crashed when I open the RBMK control console's GUI

### ISSUE THREAD

**Issue by sdddddf80** [HbmMods/Hbm-s-Nuclear-Tech-GIT#238]
After I built a RBMK reactor in my survive world,I want to use the RBMK control console to monitor it. First I put it about ten blocks away from the reactor and when I try to open it,the game crashed.Then I try many methods,mining the control console and put it again, stopping the reactor, put it dozens of  chunks away from the reactor,etc.Most of them doesn't work. Sometimes I managed to open the GUI,but that situation can't hold for long.I only discovered that when I can clicking "HOW 2 RBMK" book on the RBMK console and get the guide book,I can successfully open the GUI,or I will directly open the GUI and crash the game.But in other world I didn‘t meet this problom.The mod version is 3920 and 3936.Here is the crash report:

---- Minecraft Crash Report ----
// My bad.

Time: 21-7-22 下午9:55
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 5, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
	at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1027)
	at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
	at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
	at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1027)
	at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
	at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['player'/66, l='MpServer', x=-2388.65, y=65.62, z=1111.47]]
	Chunk stats: MultiplayerChunkCache: 441, 450
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-232,64,172), Chunk: (at 8,4,12 in -15,10; contains blocks -240,0,160 to -225,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 5435937 game time, 6539946 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 49 total; [EntityItem['item.item.sulphur'/132, l='MpServer', x=-2390.63, y=17.13, z=1062.47], EntityItem['item.item.sulphur'/133, l='MpServer', x=-2389.78, y=19.13, z=1069.13], EntityItem['item.item.sulphur'/134, l='MpServer', x=-2392.38, y=38.13, z=1066.09], EntityBat['蝙蝠'/135, l='MpServer', x=-2390.25, y=39.10, z=1066.25], EntityBat['蝙蝠'/136, l='MpServer', x=-2392.47, y=39.10, z=1072.13], EntitySquid['鱿鱼'/137, l='MpServer', x=-2398.38, y=51.34, z=1067.88], EntitySquid['鱿鱼'/138, l='MpServer', x=-2390.16, y=51.94, z=1059.50], EntitySquid['鱿鱼'/139, l='MpServer', x=-2400.63, y=52.34, z=1066.59], EntitySquid['鱿鱼'/140, l='MpServer', x=-2389.94, y=48.00, z=1056.84], EntityBat['蝙蝠'/141, l='MpServer', x=-2396.85, y=27.00, z=1086.97], EntityBat['蝙蝠'/142, l='MpServer', x=-2391.24, y=37.93, z=1074.30], EntityBat['蝙蝠'/143, l='MpServer', x=-2386.19, y=36.73, z=1093.86], EntityItem['item.item.dyePowder.black'/148, l='MpServer', x=-2382.22, y=48.13, z=1048.13], EntityItem['item.item.bootsIron'/150, l='MpServer', x=-2368.03, y=25.13, z=1063.94], EntityItem['item.item.sulphur'/151, l='MpServer', x=-2371.06, y=17.13, z=1069.66], EntityBat['蝙蝠'/152, l='MpServer', x=-2367.44, y=19.10, z=1061.25], EntitySquid['鱿鱼'/153, l='MpServer', x=-2374.50, y=57.00, z=1057.56], EntitySquid['鱿鱼'/154, l='MpServer', x=-2378.56, y=57.34, z=1064.88], EntitySquid['鱿鱼'/155, l='MpServer', x=-2379.63, y=59.38, z=1065.63], EntitySquid['鱿鱼'/156, l='MpServer', x=-2382.84, y=59.31, z=1061.25], EntityItem['item.item.rottenFlesh'/157, l='MpServer', x=-2372.19, y=43.13, z=1082.19], EntityXPOrb['经验球'/158, l='MpServer', x=-2372.88, y=43.25, z=1087.56], EntityXPOrb['经验球'/159, l='MpServer', x=-2372.75, y=43.25, z=1086.97], EntityXPOrb['经验球'/160, l='MpServer', x=-2368.75, y=37.25, z=1085.75], EntityTrail['未知'/416, l='MpServer', x=-2388.65, y=65.62, z=1111.47], EntityXPOrb['经验球'/161, l='MpServer', x=-2368.75, y=38.25, z=1082.25], EntityItem['item.tile.sandStone.smooth'/162, l='MpServer', x=-2375.81, y=48.13, z=1083.88], EntityBat['蝙蝠'/163, l='MpServer', x=-2358.93, y=17.00, z=1087.50], EntityBat['蝙蝠'/166, l='MpServer', x=-2358.83, y=21.18, z=1151.61], EntityItem['item.item.rottenFlesh'/172, l='MpServer', x=-2367.81, y=25.13, z=1063.97], EntityItem['item.item.arrow'/173, l='MpServer', x=-2360.13, y=31.13, z=1068.63], EntityItem['item.item.arrow'/174, l='MpServer', x=-2360.88, y=41.13, z=1062.06], EntityItem['item.item.bone'/175, l='MpServer', x=-2360.88, y=41.13, z=1061.19], EntityItem['item.item.skull.skeleton'/176, l='MpServer', x=-2365.88, y=26.13, z=1078.66], EntityItem['item.item.skull.zombie'/177, l='MpServer', x=-2365.88, y=26.13, z=1078.88], EntityBat['蝙蝠'/178, l='MpServer', x=-2361.56, y=19.10, z=1072.75], EntityBat['蝙蝠'/179, l='MpServer', x=-2365.10, y=17.35, z=1072.73], EntityItem['item.item.rottenFlesh'/180, l='MpServer', x=-2367.25, y=36.13, z=1082.81], EntityBat['蝙蝠'/181, l='MpServer', x=-2344.50, y=28.27, z=1065.97], EntityScent['entity.ZAMod.EntityScent.name'/67, l='MpServer', x=-2388.66, y=64.00, z=1111.44], EntityClientPlayerMP['player'/66, l='MpServer', x=-2388.65, y=65.62, z=1111.47], EntitySpider['蜘蛛'/476, l='MpServer', x=-19.35, y=-42.62, z=-8.47], EntitySquid['鱿鱼'/103, l='MpServer', x=-2450.09, y=56.00, z=1117.03], EntitySquid['鱿鱼'/108, l='MpServer', x=-2445.25, y=56.91, z=1121.75], EntityBat['蝙蝠'/111, l='MpServer', x=-2436.16, y=31.72, z=1112.34], EntityBat['蝙蝠'/112, l='MpServer', x=-2433.16, y=31.01, z=1106.06], EntitySquid['鱿鱼'/113, l='MpServer', x=-2447.47, y=58.31, z=1115.91], EntitySquid['鱿鱼'/114, l='MpServer', x=-2452.53, y=48.19, z=1145.13], EntitySquid['鱿鱼'/127, l='MpServer', x=-2406.72, y=55.31, z=1076.88]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 9256241392 bytes (8827 MB) / 10015997952 bytes (9552 MB) up to 16928210944 bytes (16144 MB)
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx16140m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 89 mods loaded, 89 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] ([1.7.10]-物品管理器-NotEnoughItems-v1.0.5.120_universal.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCHIJAAAA	uniqore{1.1} [UniQore] (minecraft.jar) 
	UCHIJAAAA	AdvancedRocketryCore{1} [Advanced Rocketry] (minecraft.jar) 
	UCHIJAAAA	WarpDriveCore{1.7.10-1.4.2.-} [WarpDriveCore] (minecraft.jar) 
	UCHIJAAAA	FoamFixCore{1.0.0-beta3} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.25} [FastCraft] ([快速工艺]fastcraft-1.25.jar) 
	UCHIJAAAA	non_update{1.0} [NonUpdate] ([更新禁止]NonUpdate-1.7.10-1.0build7.jar) 
	UCHIJAAAA	NEIAddons{1.12.14.40} [NEI Addons] ([1.7.10]-NEI扩展-NEIAddons-v1.12.14.40.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] ([1.7.10]-NEI扩展-NEIAddons-v1.12.14.40.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] ([AE2]应用能源2 -rv3-beta-6.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] ([1.7.10]-NEI扩展-NEIAddons-v1.12.14.40.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] ([1.7.10]-NEI扩展-NEIAddons-v1.12.14.40.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] ([1.7.10]-NEI扩展-NEIAddons-v1.12.14.40.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] ([1.7.10]-NEI扩展-NEIAddons-v1.12.14.40.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] ([1.7.10]-NEI扩展-NEIAddons-v1.12.14.40.jar) 
	UCHIJAAAA	neiintegration{1.1.1} [NEI Integration] ([1.7.10]-NEI扩展-NEIIntegration-v1.1.1.jar) 
	UCHIJAAAA	Backpack{2.0.0} [Backpack] ([1.7.10]-背包-BackPacks.jar) 
	UCHIJAAAA	ragdollCorpses{0.12} [Ragdoll Corpses] ([1.7.10]物理尸体——Ragdoll Corpses[心殇搬运]-V0.12.jar) 
	UCHIJAAAA	easyconfigbutton{1.7.10-1.0} [EasyConfigButton] ([MOD配置优化]EasyConfigButton-1.0.jar) 
	UCHIJAAAA	damagemark{2.3} [DamageMark] ([伤害标识]DamageMarkMod-1.7.10-2.3.jar) 
	UCHIJAAAA	Torcherino{2.2s} [Torcherino] ([加速火把].jar) 
	UCHIJAAAA	anothermagicrecipe{0.0.4} [Another Magic Recipe] ([另一个可视化配方修改]Another Magic Recipe-0.0.4.jar) 
	UCHIJAAAA	recipehandler{1.7.10} [NoMoreRecipeConflict] ([合成冲突修复]NoMoreRecipeConflict-0.3(1.7.10).jar) 
	UCHIJAAAA	IC2{2.2.828-experimental} [IndustrialCraft 2] (工业2.jar) 
	UCHIJAAAA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] ([工业2版高级太阳能]AdvancedSolarPanel-1.7.10-3.5.1（工业2版高级太阳能）.jar) 
	UCHIJAAAA	BattleTowers{1.5.1} [Battle Towers] ([战斗高塔]BattleTowers-1.7.10.jar) 
	UCHIJAAAA	etfuturum{2.2.1} [§a§oEt Futurum Requiem] ([把未来带回现实]Et_Futurum_Requiem-2.2.1.jar) 
	UCHIJAAAA	p455w0rdslib{1.0.4} [p455w0rd's Library] (p455w0rdslib-1.7.10-1.0.4.jar) 
	UCHIJAAAA	ae2wct{1.7.10-rv3-1.8.7.9b} [AE2 Wireless Crafting Terminal] ([无线合成终端]WirelessCraftingTerminal-1.7.10-rv3-1.8.7.9b.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] ([末影核心]EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] ([末影接口]EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCHIJAAAA	ComputerCraft{1.75} [ComputerCraft] ([电脑工艺]ComputerCraft1.75.jar) 
	UCHIJAAAA	WarpDrive{1.7.10-1.4.2.-} [WarpDrive] ([曲率驱动]WarpDrive-1.7.10-1.4.2.-.jar) 
	UCHIJAAAA	netherlicious{3.0.5} [§6Netherlicious] ([更好的下界]netherlicious-3.0.5.jar) 
	UCHIJAAAA	ChunkAnimator{@VERSION@} [Chunk Animator] ([更好的区块加载动画]Chunk animator.jar) 
	UCHIJAAAA	betterbuilderswands{0.8.1} [Better Builder's Wands] ([更好的建筑之杖]BetterBuildersWands-0.8.1-1.7.10r92+aec06c3.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] ([红石计划-基础]ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] ([红石计划-世界生成]ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] ([红石计划-发电机]ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] ([红石计划-红石门]ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] ([红石计划-兼容]ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] ([红石计划-发电机]ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] ([红石计划-灯]ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] ([红石计划-红石门]ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] ([红石计划-集成电路]ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
	UCHIJAAAA	MineTweaker3{3.1.0} [MineTweaker 3] ([自定义合成表]CraftTweaker-1.7.10-3.1.0-legacy.jar) 
	UCHIJAAAA	mo{0.4.2} [Matter Overdrive] ([超能物质]MatterOverdrive-1.7.10-0.4.2.jar) 
	UCHIJAAAA	VeinMiner{0.36.0_1.7.10-28a7f13} [Vein Miner] ([连锁挖矿]VeinMiner-1.7.10-0.36.0.496+28a7f13.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.36.0_1.7.10-28a7f13} [Mod Support] ([连锁挖矿]VeinMiner-1.7.10-0.36.0.496+28a7f13.jar) 
	UCHIJAAAA	Mekanism{9.1.1} [Mekanism] ([通用机械]Mekanism-1.7.10-9.1.1.1031.jar) 
	UCHIJAAAA	MekanismGenerators{9.1.0} [MekanismGenerators] ([通用机械]发电机MekanismGenerators-1.7.10-9.1.0.281.jar) 
	UCHIJAAAA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJAAAA	GraviGun{4.0.0-beta} [GraviGun] ([重力枪]GravityGun-4.0.0-beta.jar) 
	UCHIJAAAA	FpsReducer{1.7.10-1.10.1} [FPS Reducer] ([闲置游戏时降低FPS]FpsReducer-1.7.10-1.10.1.jar) 
	UCHIJAAAA	extracells{2.3.14} [Extra Cells 2] ([额外储存单元]ExtraCells-1.7.10-2.3.14b200.jar) 
	UCHIJAAAA	libVulpes{0.2.8.-37} [libVulpes] (LibVulpes-1.7.10-0.2.8-37-universal.jar) 
	UCHIJAAAA	advancedRocketry{1.4.0-20} [Advanced Rocketry] ([高级火箭]AdvancedRocketry-1.7.10-1.4.0-20.jar) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] ([高级附魔台]EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAA	Avaritia{1.13} [Avaritia] (Avaritia-1.13.jar) 
	UCHIJAAAA	bookshelf{1.0.4.187} [Bookshelf] (Bookshelf-1.7.10-1.0.4.187.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	CoroPets{v1.0} [CoroPets] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (FoamFix-1.7.10-universal-1.0.0-beta3.jar) 
	UCHIJAAAA	hbm{1.0.27 BETA (3936)} [Hbm's Nuclear Tech] (HBM_1.0.27X3936.jar) 
	UCHIJAAAA	InfernalMobs{1.6.6} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAA	ZAMod{v1.10} [Zombie Awareness] (zombieawareness[僵尸意志]-1.7.10-1.10.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (区块加载器.jar) 
	UCHIJAAAA	journeymap{5.1.4p2} [JourneyMap] (（旅行地图）journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJAAAA	aobd{2.9.2} [Another One Bites The Dust] ([矿物形态延展]AOBD-2.9.2.jar) 
	UCHIJAAAA	uniq{1.7} [UniQ] ([矿辞统一]uniq-1.7.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 471.41' Renderer: 'NVIDIA GeForce RTX 2060/PCIe/SSE2'
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	EnderIO: Found the following problem(s) with your installation:
                  * Optifine is installed. This is NOT supported.
                  * The RF API that is being used (1.7.10R1.0.10 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.13 from [末影接口]EnderIO-1.7.10-2.3.0.429_beta.jar).
                    It is a supported version, but that difference may lead to problems.
                  * Our API got loaded from [末影接口]EnderIO-1.7.10-2.3.0.429_beta.jar. That's unexpected.
                  * Our API got loaded from [末影接口]EnderIO-1.7.10-2.3.0.429_beta.jar. That's unexpected.
                  * Our API got loaded from [末影接口]EnderIO-1.7.10-2.3.0.429_beta.jar. That's unexpected.
                  * An unknown AE2 API is installed (rv3 from [AE2]应用能源2 -rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                  * Our API got loaded from [末影接口]EnderIO-1.7.10-2.3.0.429_beta.jar. That's unexpected.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Launched Version: HMCL 3.3.188
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 471.41, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 10
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 471.41
	OpenGlRenderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
[crash-2021-07-22_21.55.13-client.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/6863011/crash-2021-07-22_21.55.13-client.txt)

**Comment by UFFR** [comment]
Were you wearing some kind of FSB armor? I had a similar issue and it 
appeared to have been due to me wearing a FSB armor, which was resolved 
by taking off the helmet before opening the GUI.

-- 
UFFR

**Comment by sdddddf80** [comment]
> 你穿着FSB的盔甲吗？我也有类似的问题，这似乎是因为我穿着FSB盔甲，这是通过在打开GUI之前摘下头盔来解决的。
> […](#)
> -UFFR

Thank you bro,your method worked! 👍 I wonder is this a bug? Would bob fix it in the future?

**Comment by HbmMods** [comment]
I was never able to replicate the crash but I know what caused it. Version X3942 fixes this issue.
