### ISSUE TITLE
double siren thing

### ISSUE THREAD

**Issue by strangelf47829** [HbmMods/Hbm-s-Nuclear-Tech-GIT#24]
when you turn on a siren, leave the chunk then re enter it you get the siren + another siren. after destroying or turning of the siren you still hear the non existant one

**Comment by 3mmfire** [comment]
I have same problem

**Comment by 3mmfire** [comment]
Do you have fix this?

**Comment by Drillgon200** [comment]
If you still haven't gotten around to fixing it, I've got a fix for it in my fork. Changed the siren packet and the siren tile entity.
