### ISSUE TITLE
Where to get "Medium Enriched Plutonium-239" pellets?

### ISSUE THREAD

**Issue by Sept0n** [HbmMods/Hbm-s-Nuclear-Tech-GIT#240]
I need _bismuth_, and to get it, I need nuclear waste

They are obtained from **granules**, but I do not know how to get them.

I was looking for how to get them for 1 hour, but I did not find anything, I will be grateful to those who will tell you how to get them

**Comment by TheForge129** [comment]
you can get nuclear waste from normal spent reactor fuel

if you don't have nei please get it

**Comment by Sept0n** [comment]
![image](https://user-images.githubusercontent.com/69248865/126934584-afbddb3b-3429-4f1c-a2be-76ba2763ba59.png)
I need such waste, but in NEI there is no recipe for the granules from which this waste is made.

**Comment by TheForge129** [comment]
oh, I thought you needed regular nuclear waste
i'm booting up ntm real quick and taking a look

**Comment by HbmMods** [comment]
RBMK pellets for fuel recycling can be made by putting RBMK fuel rods in the crafting grid. Make sure that the fuel is at least 1% depleted and no hotter than 50°C.
