### ISSUE TITLE
Missiles can’t function well in servers

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#243]
Greetings！
I set up my own server and loaded HBM nuclear mod.But I found that the missile will be "stuck" when it tries to enter an unloaded chunk.It won't continue flying unless a player approaches it and loads the chunk.
I know，in single player games，the missiles will load the chunk on their own and fly the whole route to hit the target.
I hope that you can fix it in the next update.For example，you can give the missile the ability to work like “the world anchor”，loading the chunks on its path to ensure a smooth flight.
Thank you!
I'm looking forward to your reply.

**Comment by HbmMods** [comment]
Missiles were specifically made to load chunks, if they do it in singleplayer they also do it in multiplayer. The system definitely does work on servers, but obviously depending on the server software, plugins or other mods, it's possible that something inhibits chunk loading. That's neither the mod's fault nor something within my control.

**Comment by ghost** [comment]
Sorry but I next used a server without any mod except hbm to test，and the same thing happened.My mod version is 3892.I will test it with the latest version later.

**Comment by ghost** [comment]
Latest mod 3942H2 still has this problem.
:(

**Comment by HbmMods** [comment]
What server software are you running?

**Comment by ghost** [comment]
Same problem :(
Server:1.7.10 spigot
only one mod Hbm X3942H2

**Comment by ghost** [comment]
My friends told me that the missile only went about 250 blocks(according to the Radar UI)then stopped.

**Comment by HbmMods** [comment]
I wasn't even aware that spigot worked with forge at all. We've had a couple of Thermos servers in the past and it seems to work just fine there, the radar not working seems like some kind of limit for entity tracking/AABB checks imposed by the server itself, maybe there's a config for that? Either way there's not a whole lot i can do about that.

**Comment by ghost** [comment]
I got no idea.I used a server pack made by others.But there is actually a working “spigot.yml”file in the pack.I will use another server core and test it.

**Comment by ghost** [comment]
Since missiles are OK in Thermos servers，maybe I will switch my server to Thermos too.
Anyway，thank you for paying attention！
