### ISSUE TITLE
Proposal for the Damage System of Explosion-Proof Blocks

### ISSUE THREAD

**Issue by FlappyBanan** [HbmMods/Hbm-s-Nuclear-Tech-GIT#244]
Hello. I understand that you can't write sentences here, but I don't know where to write them.
I would like to propose to implement a system of missile damage to blocks that have explosion protection. In the ICBM mod, some missiles can penetrate such blocks. If I'm not mistaken, they scatter them. The HBM mod can be used as an industrial mod. But definitely not a military man with such a mechanic of damage.

**Comment by Shibva** [comment]
hello @FlappyBanan 

this issue should be closed. its clear that this will be ignored and not taken into consideration. 

please close this as its just clutter at the bottom of the bin at this point
