### ISSUE TITLE
[Suggestion]New enemy and new missile launcher 

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#246]
Greetings!
I have some suggestions.

[1]Re-Add the old turrets.
I noticed that  in recent updates a lot of new turrets are added into the mod.However，they are bigger in size and a little harder to set before use.I hope the old turrets can still be crafted with a simplified recipe to help players get their defense methods quickly.

[2]New enemies
I think the hunter helicopter is a nice design in the game.The original Minecraft don’t have strong air enemies. I wish there will be more flying enemies such as fighters and bombers which will try to attack the player's base.

[3]Player-driveable vehicles
Planes，helicopters，cars，tanks.....etc.

[4]New missile launcher type
Cruise Missile Launcher  in ICBMclassic mod is great!Please add a similar one into hbm.

[5]new turrets
Grenade launcher turret.  Mortar. Howitzer.
And plz make the Flakturret（WIP）weaker！It can destroy a huge building in several shots.

I hope the Hbm mod will get more excellent!

**Comment by sendhelppls213** [comment]
You're supposed to report issues here, not suggest or request.

**Comment by sendhelppls213** [comment]
https://www.youtube.com/watch?v=IeqeUyPlRRs amd here you can see that a flak gun would indeed be able to destroy a huge building pretty fast.

**Comment by HbmMods** [comment]
1. The old turrets will not be re-added, other than being bigger they're inferior in every other aspect.
2. There's no new enemies currently planned.
3. A drivable tank was considered, but it's a ton of work and mods like Flan's Mod and MCHeli do the job better anyway.
4. Cruise missiles might be ported over from xRadar but they would use the same launcher.
5. A mortar-like turret is currently being worked on. The WIP anti aircraft turret will most likely be removed.
