### ISSUE TITLE
Suggestion: re-add manual turret controller 

### ISSUE THREAD

**Issue by IloveObraDinn** [HbmMods/Hbm-s-Nuclear-Tech-GIT#249]
do you think you could re-add the manual turret controller? I know you probably removed it for a reason, but perhaps it could be creative only?

I just really enjoyed using it.

thank you

**Comment by Shibva** [comment]
Please close this comment, the turret Controler was already added back in for a while now and would be best to close it due to this just being clutter now in the issues seciton
