### ISSUE TITLE
Bobmazon Not working

### ISSUE THREAD

**Issue by Big-Boofer** [HbmMods/Hbm-s-Nuclear-Tech-GIT#25]
When using every cap in the mod i cant order anything on the bobmazon. If its a wip i understand.

**Comment by HbmMods** [comment]
What message does it put in chat when you're trying to use bobmazon?

**Comment by Big-Boofer** [comment]
I says "[Bobmazon] Requirements not met"

**Comment by Big-Boofer** [comment]
Also could add a.way to control reactors with switches and screens?

You don't have too If not willing too.

**Comment by HbmMods** [comment]
> I says "[Bobmazon] Requirements not met"

It does what it's supposed to.

**Comment by Big-Boofer** [comment]
Oh thanks

**Comment by HbmMods** [comment]
You need the achievements to unlock the actual offers, if it were the cap's fault the message would be different.

**Comment by Big-Boofer** [comment]
Oh you're a big help thank you

**Comment by Big-Boofer** [comment]
so i cant unlock some of the achievements like chapter point twenty five

**Comment by HbmMods** [comment]
That one isn't even required, stick to the bobmazon ones.

**Comment by Big-Boofer** [comment]
so the metalworks achievement i unlock it by buying it or crafting it cause i cant buy it

**Comment by HbmMods** [comment]
Obviously by crafting it. Wouldn't make much sense if buying were the requirement for buying something, would it?

**Comment by Big-Boofer** [comment]
thanks for the help. also i love the mod

**Comment by Big-Boofer** [comment]
sorry for wasting your time with my dumb issue
