### ISSUE TITLE
Minor Issue: Template Folder does not recognize materials from other mods being used

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#258]
Desc: I was trying to make a Siren using the template folder, but when I tried to use it with another steel plate from another mod that has a plateSteel Oredic on it, it dint accept it for some unknown reason

Recomendation: Have the template accept materials using an oredict so its compatible with the same material form other mods

**Comment by TheForge129** [comment]
wasn't there an issue a while back about the assembler not accepting
pulverised gold from thermal?
you're using the latest version, right?

**Comment by HbmMods** [comment]
The template folder checks for the exact items, similarly it only accepts vanilla dyes.

> wasn't there an issue a while back about the assembler not accepting pulverised gold from thermal?

Similar issue but completely unrelated, back then the assembler system was reworked, requiring the recipes to be written with explicit ore dict definitions, it's just that some ore dict keys were missing.

**Comment by Shibva** [comment]
Notice that a change was made, if this what I think it is then you can close this issue 

and thanks for hearing me out ^w^
