### ISSUE TITLE
plan c lacing recipie doesnt work

### ISSUE THREAD

**Issue by Joey-Destroyah** [HbmMods/Hbm-s-Nuclear-Tech-GIT#260]
![2021-08-16_12 51 08](https://user-images.githubusercontent.com/62820134/129600349-1b6a94b6-1eaa-4e5f-a41b-f26faffbca33.png)

**Comment by HbmMods** [comment]
All the mod's anvil recipes now use the _NTM_ anvil.

**Comment by Joey-Destroyah** [comment]
oh. Thanks.
