### ISSUE TITLE
Tick Block Occurances

### ISSUE THREAD

**Issue by Bromack0304** [HbmMods/Hbm-s-Nuclear-Tech-GIT#261]
When playing in some worlds that are in Higher versions some blocks are replaced by this Tick block thing, it spreads constantly and its annoying because it creates huge clouds of it that are hard to remove.

**Comment by HbmMods** [comment]
It's generally not a great idea to open worlds from newer versions in older ones, especially with mods installed. Either load the world in vanilla first which will cause all blocks that don't yet exist to disappear or remove them with a mapping tool such as MCEdit.
