### ISSUE TITLE
[config] mod crashes by HBM when potions from mod extend past 127 (128 and up)

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#263]
I was told something about this mod extending the potion ids, though I cant remember if this was correct or not, if it s then its not letting the mods own potion ids extend past this limit

**Comment by 9Valjew** [comment]
Download potion id helper
As far as I remember in unfucks minecraft's shitty ass shitass stuff

**Comment by Shibva** [comment]
yes, but not all mods work with that (ie, Bugtorch will not run with potion Id helper

**Comment by ShimmeringBlaze** [comment]
Then I guess you're just out of luck then

**Comment by HbmMods** [comment]
NTM will automatically extend the potion array to 256 (from the default meager 32) if any of its potions are configged with an ID above the default range. Minecraft however uses the `byte` type for synchronizing potion effects, meaning that only effectively 128 effects are usable without installing a mod that changes this behavior. That's not really NTM's fault and there's not a whole lot I can do about it, and with any large enough modpack you're bound to run out of potion IDs eventually. You should consider opening an issue at the incompatible mod's repository and asking for potion ID helper compatibility.
