### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by lingualesta** [HbmMods/Hbm-s-Nuclear-Tech-GIT#266]
Hi, I tried to play this mod with a few others but everytime I use vic's modern warfare with hbm hazmat suit's texture become flat and bugged can someone help me to solve this problem?

**Comment by ncr-t** [comment]
oh well mate that's what we call a vic's modern warfare moment. anyway, no there aren't any fix for that visual glitch, the only way to "fix" that is to uninstall VMW

**Comment by lingualesta** [comment]
Minecraft version: 1.12.2
Hbm version: 1.4.4a

**Comment by Shibva** [comment]
this issue is redundant can should be closed, please report this o the current maintainer of the 1.12.2 fork
