### ISSUE TITLE
[Feature Request]Radar + forcefield

### ISSUE THREAD

**Issue by ektorthebigbro** [HbmMods/Hbm-s-Nuclear-Tech-GIT#269]
hello hbm i would really like to have a radar linking item and a new block that i could access my radar from underground. Also about the force field i would like it to stop everything including players and explosions. i also would like the force field  radius to have a more realistic texture. i hope you add these features in the next version of hbm

**Comment by sendhelppls213** [comment]
This is the issues report tool, it's not supposed to be used as a bad suggestion/request tool.

**Comment by ektorthebigbro** [comment]
where do i write suggestions then

**Comment by ektorthebigbro** [comment]
WHY it is invalid suggestion

**Comment by sendhelppls213** [comment]
To find out more about the suggestions you can always join the discord. And it's invalid because this never was, isn't and never will be a suggestion tool.

**Comment by Drillgon200** [comment]
Github issues are very much used as a suggestion system in most repos due to github's lack of a suggestion system. This mod simply has a no suggestions rule because nearly all suggestions are terrible quality.
