### ISSUE TITLE
Costum missile

### ISSUE THREAD

**Issue by 3mmfire** [HbmMods/Hbm-s-Nuclear-Tech-GIT#27]
Hello how can i launch a costum missile with detonator with lever?
I cant charge the missile with the hydrogen peroxyde what is and where can i fount hydrogen peroxyde?

Thanks

**Comment by HbmMods** [comment]
Hydrogen peroxide is made from water using the chemical plant, you can use peroxide tanks to fill it into the launch pad directly, much like how kerosene canisters work, or connect the chemical plant to the launch pad using pipes.
