### ISSUE TITLE
Advanced alloy shovel has the hoe recipe, along with its own

### ISSUE THREAD

**Issue by TrueSanicWasHere** [HbmMods/Hbm-s-Nuclear-Tech-GIT#271]
Advanced alloy shovel also has the recipe of its how counterpart, while the hoe has no recipe.

**Comment by ncr-t** [comment]
that's a known bug, and bob might've fixed it already

**Comment by HbmMods** [comment]
Wrong tool recipes have been fixed [here](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/commit/7a24c74435096bc343355eedae7d22381a44e2f2#diff-759d37133bd1d1dd5df49bcd8b114a054ce73b6343f88ee74e0a1f22e4b1c709) and [here](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/commit/0eadbbc2887b935e97ba0df21d523ec45dd7dc9e#diff-759d37133bd1d1dd5df49bcd8b114a054ce73b6343f88ee74e0a1f22e4b1c709). Expect the next release in about a week.
