### ISSUE TITLE
when is the update

### ISSUE THREAD

**Issue by Sinanemo21** [HbmMods/Hbm-s-Nuclear-Tech-GIT#272]
when will the radar be fixed in 1.12.2

because the radar still can't detect custom missiles and that's a pity

**Comment by sendhelppls213** [comment]
1.12 is discontinued.

**Comment by Sinanemo21** [comment]
> 1.12 durduruldu.

why

**Comment by sendhelppls213** [comment]
because Drillgon has better things to do

**Comment by Sinanemo21** [comment]
> > 1.12 durduruldu.
> 
> why

https://www.curseforge.com/minecraft/mc-mods/hbms-nuclear-tech-mod-reloaded

**Comment by Sinanemo21** [comment]
> çünkü Drillgon'un yapacak daha iyi işler var

uh ok

**Comment by sdddddf80** [comment]
But Drillgon200 just updated a bunch of assets 7 days ago.What will those assets be used for?

**Comment by ncr-t** [comment]
he was planning on releasing a last bugfix update iirc

**Comment by sdddddf80** [comment]
well,it looks like that there will be many new items

**Comment by Drillgon200** [comment]
Most of those were planned assets that I created before I decided to stop modding. I uploaded them to github so anyone who wants to implement them can. It would be a waste for those doors to never have the chance to see the light of the minecraft sun, and I can't exactly use them in my own projects. Not detecting custom missiles does, however, count as a bug, so I will fix that. I just realized I forgot to upload the anti tom turret model, so hopefully writing this message will remind me to later.

**Comment by Sinanemo21** [comment]
> Most of those were planned assets that I created before I decided to stop modding. I uploaded them to github so anyone who wants to implement them can. It would be a waste for those doors to never have the chance to see the light of the minecraft sun, and I can't exactly use them in my own projects. Not detecting custom missiles does, however, count as a bug, so I will fix that. I just realized I forgot to upload the anti tom turret model, so hopefully writing this message will remind me to later.

Why did you stop coding mods?

**Comment by Sinanemo21** [comment]
> Most of those were planned assets that I created before I decided to stop modding. I uploaded them to github so anyone who wants to implement them can. It would be a waste for those doors to never have the chance to see the light of the minecraft sun, and I can't exactly use them in my own projects. Not detecting custom missiles does, however, count as a bug, so I will fix that. I just realized I forgot to upload the anti tom turret model, so hopefully writing this message will remind me to later.


and how do i migrate mods from version 1.7.10 to 1.12.2

**Comment by Drillgon200** [comment]
I stopped because I wasn't learning enough new stuff from it, so I wasn't expanding my programming ability fast enough. Now I'm thinking I might still port features instead of commit by commit though, since that takes a lot less time (last update took less than a week to port many of the major features from months of 1.7 content, so the work load is much lighter and allows me to still do much heavier programming when not modding). The latest update actually does have those assets now by the way.

As for migrating mods, go learn how to make mods from the many tutorials on the internet and try to port some stuff hands on.

**Comment by Shibva** [comment]
you can close this issue now, its just clutter at this point
