### ISSUE TITLE
Explosion causing game to crash

### ISSUE THREAD

**Issue by MeferWT** [HbmMods/Hbm-s-Nuclear-Tech-GIT#278]
When the tossable antischrambium cell explodes on version 3990 (the one i saw it happening with) the game crashes, the problem seem to also make other mod components crash as well, such as the "intelligent munitions system" from Security Craft.

**Comment by HbmMods** [comment]
I have found the source of the issue, but I'm not at all sure how this relates to the SC munitions system which afaik uses vanilla explosions. I'll close the issue once the fix is tested and released.

**Comment by HbmMods** [comment]
Resolved in [X3991](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/releases/tag/1.0.27X3991).
