### ISSUE TITLE
Silo hatch

### ISSUE THREAD

**Issue by 3mmfire** [HbmMods/Hbm-s-Nuclear-Tech-GIT#28]
Hello how can i use the silo hatch can i use it like a piston for the missile launchere thanks

**Comment by Legion2019** [comment]
I have the same problem, i don't know how to use the silo hatch and the silo hatch open. I tried to search help on internet but it doesen't give me reply, could you help us please?

**Comment by HbmMods** [comment]
[Like this](https://cdn.discordapp.com/attachments/320301871233368064/494460482510651393/2018-09-26_12.47.23.png)

**Comment by Legion2019** [comment]
thank you
