### ISSUE TITLE
совместимость жидкостей

### ISSUE THREAD

**Issue by DANILKA1802** [HbmMods/Hbm-s-Nuclear-Tech-GIT#280]
когда появится совместимость труб из разных модов, например thermal dynamics или buildCraft?

мне нужно чтобы пар из РБМК попадал в турбину другого мода, но я не могу это сделать, так-как
HBM не поддерживает трубы из других модов.

возможно есть какой-то другой способ, просто я не в курсе?

**Comment by DANILKA1802** [comment]
when will the compatibility of pipes from different mods, for example, thermal dynamics or BuildCraft, appear?

I need the steam from the RBMK to get into the turbine of another mod, but I can't do it, so-how
HBM does not support pipes from other mods.

maybe there is some other way, I just don't know?

**Comment by HbmMods** [comment]
NTM steam is not compatible with steam form other mods, you will need to use an NTM turbine.
