### ISSUE TITLE
German translation is bad

### ISSUE THREAD

**Issue by alex-s168** [HbmMods/Hbm-s-Nuclear-Tech-GIT#283]
Who made this f*ing german translation.
it is weird.

**Comment by HbmMods** [comment]
Me.

What's wrong with it?

**Comment by alex-s168** [comment]
are you german?

**Comment by HbmMods** [comment]
Austrian.

**Comment by alex-s168** [comment]
im also from austria

**Comment by HbmMods** [comment]
I saw that. Are you gonna tell me what's wrong with the translations or not?

**Comment by alex-s168** [comment]
manches ist nicht übersetzt und bei manchen zeilen steht müll dabei

**Comment by alex-s168** [comment]
aber ist ja eig egal
