### ISSUE TITLE
[Suggestion] better missiles

### ISSUE THREAD

**Issue by alex-s168** [HbmMods/Hbm-s-Nuclear-Tech-GIT#286]
- More fuel tanks for custom missiles (higher and more fuel)
- More different engines
- Able to paint parts of custom missiles
- extra slot in custom missile table:<br> 
  Slot name: addon slot<br>
  for example:<br>
    an addon named flare:<br>
     if the missile gets targetet by turrets or so, it would automatically flare ("drops" fake targets) so the turrets cant destroy the missile easyly
- customisable warhead (similar to custom nukes)
- missile can fly to othee planets (advanced rocketry) if it has enought fuel

**Comment by alex-s168** [comment]
whats wrong with that

**Comment by ShimmeringBlaze** [comment]
For one, this is a place for ISSUES, not suggestions, and HBM normally doesn't take suggestions in the first place

**Comment by alex-s168** [comment]
but why not Suggestions

**Comment by SoB1nary** [comment]
because most suggestions are dumb
just like this one
