### ISSUE TITLE
[Suggestion] better guns

### ISSUE THREAD

**Issue by alex-s168** [HbmMods/Hbm-s-Nuclear-Tech-GIT#287]
- be able to change damage multiplier of all guns
- be able to generally disable guns of ntm
- zoom
Edit: Okay that's extremely useless and dumb)

**Comment by potatoee** [comment]
dude if you want that stuff, do it yourself as i doubt hbm will want to do 4 things for 1 single guy

**Comment by Billcyferka** [comment]
noone asked for that stuff
