### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Threepan** [HbmMods/Hbm-s-Nuclear-Tech-GIT#289]
Excuse me，Can you join many modern warfare weapons, such as Army guns, guns, rocket launchers, and then add different speeds to missiles, and more, such as anti-ship missiles, anti-aircraft missiles, Air Force fighter jets, helicopters, reconnaissance aircraft, and then aircraft carriers, destroyers, and real-time reconnaissance radar?

**Comment by sendhelppls213** [comment]
You aren't supposed to suggest things using the issue report tool.
