### ISSUE TITLE
Custom Nuke looks glitchy

### ISSUE THREAD

**Issue by whatsapp2** [HbmMods/Hbm-s-Nuclear-Tech-GIT#29]
Hello HBM.
I just wanted to notify about this texture "glitch" with the Custom Nuke. I tried your latest in-dev version (hbm1.0.27_BETA3231) with no other mods installed. 
Maybe a rendering problem with the new Little Boy texture
![2019-08-18_13 41 53](https://user-images.githubusercontent.com/25994176/63228854-f59a7c00-c1be-11e9-9b92-e60891097909.png)

**Comment by HbmMods** [comment]
Both the little boy model and texture were updated, the custom nuke one however was not. Since they both use the same model, it'll have the incorrect texture format until the custom nuke texture is also updated.

**Comment by whatsapp2** [comment]
Ok, thanks for the info.
btw, you have done an incredible work recently, keep it up ;D
