### ISSUE TITLE
Random Idea for bobfluid compatibility 

### ISSUE THREAD

**Issue by divine-ray** [HbmMods/Hbm-s-Nuclear-Tech-GIT#291]
A option to make the fluids compatible with other mods would be to make raw items that have a assigned value, i.e. “Drop of Kerosene” which can be used in modpack making or melted in thermals crucible into 250mB of that respective liquid, this could be done with a dynamic register thingy with metadata sets
The dangerous liquids like BF Fuel, Schrabidium Trisulfide, Antimatter and such would use the magnetic extraction device as upgraded reacher, kinda?

**Comment by HbmMods** [comment]
> this could be done with a dynamic register thingy with metadata sets

what
