### ISSUE TITLE
Update idea

### ISSUE THREAD

**Issue by Sinanemo21** [HbmMods/Hbm-s-Nuclear-Tech-GIT#292]
hello, I came up with an update idea, we know that the radar emits redstone when it detects a missile, so when I right-click on the radar, make a cursor at the bottom left and, for example, when the missile approaches 100 meters, redstone releases energy, or 300 or 400

**Comment by ncr-t** [comment]
please solve the following equation x²+3x-19=√(9x²)+6

**Comment by FatSassin** [comment]
But what purpose it would serve?
The radar is for detecting missiles, so setting lower range wouldn't  make much sense idk

**Comment by Sinanemo21** [comment]
> But what purpose it would serve? The radar is for detecting missiles, so setting lower range wouldn't make much sense idk

let me correct the text
hello, I came up with an update idea, we know that the radar emits redstone when it detects a missile, so when I right-click on the radar, make a cursor at the bottom left and, for example, when the missile approaches 100 meters, the redstone releases energy, or 300 or 400

**Comment by Sinanemo21** [comment]
@HbmMods hello, I came up with an update idea, we know that the radar emits redstone when it detects a missile, so when I right-click on the radar, make a cursor at the bottom left and, for example, when the missile approaches 100 meters, the redstone releases energy, or 300 or 400

**Comment by HbmMods** [comment]
Radars by default emit a redstone signal with the intensity based on the proximity - having an extra cursor to detect proximity would be redundant.
