### ISSUE TITLE
More GT related stuff

### ISSUE THREAD

**Issue by divine-ray** [HbmMods/Hbm-s-Nuclear-Tech-GIT#293]
Found this on greg’s forum. https://forum.mechaenetia.com/t/hbm-has-some-compatibility-problems-with-items-that-should-be-fluid/2052
(Just leaving this here)

**Comment by HbmMods** [comment]
I don't know what you want me to do.

**Comment by divine-ray** [comment]
half way relates to #291 since NTM lacks a way to "export" the fluids to other mods. The guy in that thread also pointed out the lack of a cylclotron/SILEX fluid in- output tank since xenon is a gas and bromine liquid

**Comment by HbmMods** [comment]
> So Bromine can easily be fixed using a Freezer and a Smelter Recipe.
> The Isotope Xenon-135 is not existing withing GT6, so I do not have to worry about that one.
> ~ Greg

I don't think bromine is common enough in mods for this to be a practical problem - in any case all the "fluid dusts" are ore dicted so whichever mod needs it could simply add ore dict recipes for it.
