### ISSUE TITLE
Wrong OreDict Registration for Tiny Piles of Dust.

### ISSUE THREAD

**Issue by GregoriusT** [HbmMods/Hbm-s-Nuclear-Tech-GIT#295]
### Describe the bug

You are registering your 1/9th piles of Dust as "dustSmall", but "dustSmall" is 1/4th of a Pile. "dustTiny" is 1/9th!

### Please solve this equation to x

x²+3x-19=√(9x²)+6
x is -3-√34, and also 5.
Here is my proof of work. :P
https://www.wolframalpha.com/input/?i=x%C2%B2%2B3x-19%3D%E2%88%9A%289x%C2%B2%29%2B6

**Comment by HbmMods** [comment]
Should be fixed with the most recent commit.
