### ISSUE TITLE
Request: Weapon Config

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [HbmMods/Hbm-s-Nuclear-Tech-GIT#3]
Techguns has a separate config file which allows you to adjust the stats of the various guns in detail.  It would be very helpful to modpack makers if this mod allowed you to adjust the damage of the various weapons and to enable or disable them (especially the schrabidium hammer) using a config file.

Also the Techguns mod has very good looking models and this mod's guns, like the Tau cannon, would look great if they were done the same way.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2728771-techguns-guns-worldgen-npcs-machines-and-more

**Comment by HbmMods** [comment]
The weapon config could even cover grenades (maybe limit the ZOMG grenade's beams, some basic explosion size adjustments) I like the idea.

About the models, they're already the best I can come up with and it takes an eternity to make just one that looks somewhat good. If something needed to be remodeled it's probably the missiles.
