### ISSUE TITLE
Bombs in 1.12 and in 1.7 in the last update doesn´t work properly special de Tsar and ivy mike

### ISSUE THREAD

**Issue by Rafaelitop** [HbmMods/Hbm-s-Nuclear-Tech-GIT#302]
### Describe the bug

In the 1.12.2 in the last update only the contamination appears in the Tsar bomb and ivy mike only show the animation.
In 1.7.10 last update both bombs only show animation

**Comment by HbmMods** [comment]
How long did you wait after setting off those bombs?

**Comment by Rafaelitop** [comment]
> How long did you wait after setting off those bombs?
sorry i commit a mistake , hey you know a mod that help with the boiler crude oil hud?
