### ISSUE TITLE
Some ideas on a refined fluid system for NTM

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#304]
### Forge Fluid Compatability

Dear Bobcat, I wonder if you could make some more NTM fluids placeable so that they can be recognised as fluids by forge and let them have their own versatile properties like inflammability and slipperiness by the way. In that case, NTM fluids would be of great fun and can be transported with pipes and fluid containers from other mods like the thermal series and Mekanism, and futher allowing the pipes from other mods to supply fluids to NTM machines and containers would really make the life of multi-mod players much easier than before.

### The fluid systm of NTM

Furthermore, from my own perspectives, it may be of great fun to get the currently really effective piping system of the mod refined in such a way that there would be fluids left in the pipes that can be seen from some transparent segments of the pipes and that there are things like valves and pumps and flowmeters that add an authentic industrial flavour to the piping system of NTM. This may make the piping of NTM unique and more real, meanwhile increasing the complexity and fun of the engineering of piping systems in game and making the machine sector of the mod even more perfect. (This may make the mod of more interest to fans of in-game industry.)

### Some words of mine to our dear developer

Well, in the end of the day, I have to say that these proposals of mine are not reasonalbly likely to provide any 'good-enough' new vision for the development of the fluid system of NTM as I am a noob who currently have few experiences or achievements of any type in any realm, but I would be really glad if this short message can bring you inspirations of some type in your future work with the mod. 

Thank you for your reading this message and for the efforts you are making for a better NTM.

### Please solve this equation to x

x²+3x-19=√(9x²)+6
x²+3x-19=|3x|+6

when x>=0
x²+3x-19=3x+6
x²-25=0
x²=25
As x>0,
x=5 

when x<0
x²+3x-19=-3x+6
x²+6x-25=0
As x<0,
x=-3-√(34)

Answer: x_1 = 5 and x_2 = -3-√(34)

**Comment by JoeyGu3412** [comment]
I am an idiot! 😆

**Comment by 9Valjew** [comment]
Bob, honey, its time for your weekly "asjrjjejd move to forgefluids!!!" Github issue

**Comment by ghost** [comment]
XD🤣

**Comment by 9Valjew** [comment]
shut up joey

‫בתאריך יום ד׳, 13 באוק׳ 2021 ב-12:49 מאת ‪JoeyGu3412‬‏ <‪
***@***.***‬‏>:‬

**Comment by 9Valjew** [comment]
shut up joey

**Comment by ghost** [comment]
affirmative👌

**Comment by Shibva** [comment]
@HbmMods could you close this if and when you have the time? seems like its gone stale or something, best to clean up the issues right?

**Comment by HbmMods** [comment]
g
