### ISSUE TITLE
Balefire Bomb Issue.

### ISSUE THREAD

**Issue by realShaiw** [HbmMods/Hbm-s-Nuclear-Tech-GIT#307]
Seems like that, at least in my case, Balefire Bomb completely ignored some chunk.
![Cattura](https://user-images.githubusercontent.com/92318003/136805682-ad5c4c6a-cba4-45c6-9df1-827e13a376a9.PNG)
s
![Cattura2](https://user-images.githubusercontent.com/92318003/136805694-538fc7e3-5e8b-47b1-82dd-1c7783f8f9e5.PNG)
![Cattura3](https://user-images.githubusercontent.com/92318003/136805706-ea36155d-5af0-4e50-a415-223ad65ccfd4.PNG)

.

**Comment by HbmMods** [comment]
All bombs have this issue, often times if a chunk hasn't even been generated yet, it'll remain almost untouched. I don't think there's anything I can do about it, you can however make sure that the area has been loaded at least once before setting off a bomb.

**Comment by realShaiw** [comment]
Well alright! Thanks for helping out.

**Comment by ghost** [comment]
Let the bomb load all the chunks in its range. [the very worst idea]
