### ISSUE TITLE
Fibrosis status isn't saved across restarts

### ISSUE THREAD

**Issue by FavoritoHJS** [HbmMods/Hbm-s-Nuclear-Tech-GIT#308]
### Describe the bug

At least according to the code, there is no saving of Fibrosis to NBT, thus, no way to save it after a restart

Haven't done any testing yet, but opening up a level.dat made after 4018 should show the issue.

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/blob/30765c5d110eddcb92956a13a12b7961758959ec/src/main/java/com/hbm/extprop/HbmLivingProps.java#L253-L271

Note the lack of `hfr_fibrosis`

PS: The Fibrosis variable is uppercase, while java variables should be lowercase.

### Please solve this equation to x
(this didn't show up for some reason, thanks github)

x²+3x-19=√(9x²)+6
x^2+3x-19=|3x|+6 _!! The goshdarned multiplication_
x^2+3x-25=|3x|
```
|      /|  As you can see, my plan of finding the bottom point
|     / |  and calculating from there isn't going to work...
\    /  /
 |  /  |   Time to copy someone else's idea!
 \ /   /
  /    |
 /\   /
/  \_/
```
x^2+3x-25=-3x | x^2+3x-25=3x
| --- | --- |
x^2-25=0  | x^2+6x-25=0
sqrt(25)^2-25=0 | x^2+6x-25=0
sqrt(25)=5 | x+sqrt(6x)=5
. | 3+sqrt(24)=Definitively Not Five
x is 5 | oh god am I reinventing the quadratic formula

PS: How do you make a collapsing spoiler in GFM?

**Comment by ghost** [comment]
Serious with your second solution for x? 😱

**Comment by FavoritoHJS** [comment]
_oh god i am not good with computer_

**Comment by HbmMods** [comment]
I didn't even think about the second solution when adding this requirement, so x=5 is perfectly acceptable.

**Comment by FavoritoHJS** [comment]
ok, it looks like #311 does indeed fix this.
waiting for merge

_this is not a desperate attempt to get chocolate, send help_

**Comment by ghost** [comment]
x = -3-√(34) also satisfies the equation. 😆

**Comment by Joey-Destroyah** [comment]
What is that for anyway? Human verification?

**Comment by FavoritoHJS** [comment]
pretty much.

> 
> What is that for anyway? Human verification?
>

**Comment by HbmMods** [comment]
It's mainly a test whether people manage to actually use the issue template or not, reminding them to use the github issue boards for issues and nothing else.

**Comment by FavoritoHJS** [comment]
Update on the fix: 311 (and any future PRs) are waiting for 228 to get merged, aka a long,  _long_ time

>I'm stopping PRs and any major changes until UFFR has finished merging his PR with the main branch, that way I'll avoid creating even more conflicts. Just be patient.
>
>_Originally posted by @HbmMods in https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/issues/311#issuecomment-945006794_

(890 files changed and 200k lines of code!? that must be a record)
PS: Sorry for pang, didn't realize the @ existed.

**Comment by Vaern** [comment]
Oh great, now my oversight will be immortalized for a while

**Comment by Vaern** [comment]
It is a real possibility that merging my PR would massively mess with UFFR's fork though, plus since he's already spent days working on it, it's fine

**Comment by HbmMods** [comment]
Was fixed in X4054 when vær's PR was merged.
