### ISSUE TITLE
Crashes because stupid

### ISSUE THREAD

**Issue by Chickn-man** [HbmMods/Hbm-s-Nuclear-Tech-GIT#314]
Im on X4025 and bob brokey the code so crashy now.
I was on main menu and it suddenly crashed.
Seems to be a sound issue.
[crash-2021-10-17_21.19.12-client.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/7361278/crash-2021-10-17_21.19.12-client.txt)

x = 5

**Comment by FavoritoHJS** [comment]
there is an @Spaghetti annotation...
this is not good

I'm guessing the problem is a player existing, but there is no world loaded.
Conglaturations indeed.

**Comment by Chickn-man** [comment]
I commented out lines 415-420 in com.hbm.main.ModEventHandlerClient and things started working.

**Comment by HbmMods** [comment]
Already fixed it locally, apparently the sound handler that plays the main menu theme also fires that event which assume as world instance to be open. I didn't notice it because I generally have the ingame music turned off.

**Comment by FavoritoHJS** [comment]
Fixed in 4026X
