### ISSUE TITLE
a bug with the texture of decorative blocks.

### ISSUE THREAD

**Issue by Leonoric** [HbmMods/Hbm-s-Nuclear-Tech-GIT#317]
All decorative and wires in blocks have lost their texture if put in the world.

**Comment by Leonoric** [comment]
![2021-10-19_13 43 52](https://user-images.githubusercontent.com/79148428/137894365-9b9b3112-c310-4904-8b90-4a9d66c0fd3d.png)

**Comment by Leonoric** [comment]
steel decorative block

**Comment by HbmMods** [comment]
It's the lighting that gives out, I think usually only at chunk borders. Placing a block in the dark spot should temporarily fix it.

**Comment by Leonoric** [comment]
So is this a lighting bug? I just have a mod Hardcore Darkness

**Comment by Leonoric** [comment]
I fixed it by turning off the soft lighting

**Comment by Leonoric** [comment]
if something is not clear, then I’m just from Russia and translate through a translator, I’ve been looking at your mod since 2019!

**Comment by Leonoric** [comment]
in what update will these multiblocks be updated?

**Comment by Leonoric** [comment]
![2021-10-19_14 01 25](https://user-images.githubusercontent.com/79148428/137896962-26693fd8-9dff-4a1c-a845-7661f394ce3a.png)
