### ISSUE TITLE
water fluid duct wont connect to rbmk steam connecter

### ISSUE THREAD

**Issue by Canina-X** [HbmMods/Hbm-s-Nuclear-Tech-GIT#318]
### Describe the bug

So i am trying to build a rbmk reactor, and i am done with the reactor thingy, now I'm building the pipes... I cannot attach the water fluid duct to rbmk steam connector... I am using the newest 1.12.2 Version.

### Please solve this equation to x

x²+3x-19=√(9x²)+6
??

**Comment by 7pheonix** [comment]
It's quite simple. Do you remember the quadratic formula?

**Comment by Canina-X** [comment]
What do you mean? Can you help me fix this problem?

**Comment by SoB1nary** [comment]
1. you are supposed to solve the equation, by not doing it you prove that you are 13 years of age or less
2. there is no bug, the connector itself doesnt need the water duct anyway

**Comment by Drillgon200** [comment]
Argh not this again.

**Comment by Drillgon200** [comment]
Like SoB1nary said, there is no bug. Water doesn't go through the connector, so it doesn't connect to water ducts.

**Comment by Promocriogen** [comment]
Then how to increase the connector for steam connector or for Fluid water?
