### ISSUE TITLE
Lighting issues with RBMK and Leviathan

### ISSUE THREAD

**Issue by VeiTheOne** [HbmMods/Hbm-s-Nuclear-Tech-GIT#320]
### Describe the bug

Noticed a handful of lighting errors on some blocks.

![image](https://user-images.githubusercontent.com/82922007/138922956-d21fc5bd-3619-4c8a-90dc-bc939219f85b.png)
![image](https://user-images.githubusercontent.com/82922007/138923008-1bb814e5-97fb-49f5-88aa-8f5ef1f69423.png)

### Please solve this equation to x

x²+3x-19=√(9x²)+6

I think x=5

**Comment by HbmMods** [comment]
The RBMK lids take their light information from the RBMK's core blocks which are at the bottom, although that shouldn't be hard to fix. The lighting on the levi however (as with all large multiblock machines) can't really be fixed unless I manually chop up the model and add a ton of additional lighting checks.
