### ISSUE TITLE
Some block have lightning plroblems.

### ISSUE THREAD

**Issue by Ching-Chong** [HbmMods/Hbm-s-Nuclear-Tech-GIT#321]
### Describe the bug
Reinforced glass, cable block, and some of the steel deco blocks act as not illuminated unless smooth lighting is turned off.

### Please solve this equation to x

x²+3x-19=√(9x²)+6
its this:(√(9x²)+6) all a root only (9x²) is?

![Screenshot_18](https://user-images.githubusercontent.com/75722086/139263754-4266a61c-7bf0-4cc0-93c8-722f01c8953d.png)

**Comment by HbmMods** [comment]
This is a known issue with blocks that use connected textures. It also does happen with smooth lighting off, but it's rarer.

**Comment by HbmMods** [comment]
Appears to be fixed in X4054.
