### ISSUE TITLE
Industrial generator output

### ISSUE THREAD

**Issue by Mooshroom8** [HbmMods/Hbm-s-Nuclear-Tech-GIT#323]
So when I use the industrial generator it doesn’t seem to output power when connected via cables. It won’t transfer at all just stay inside the machine. Version hbm-1.4.4a.jar on an afternoons modded Minecraft server.

**Comment by ncr-t** [comment]
1-the Industrial generator might have been removed in the latest 1.12.2 release. (though you should be able to recycle it in the NTM anvil added in the same release)
2-the industrial generator isn't really worthy of its name, as it performs terribly and shouldn't really be used

**Comment by Mooshroom8** [comment]
Wait it performs terribly..?

**Comment by Mooshroom8** [comment]
It generates decent power passively since I’m crap with the reactor and don’t got much desh so this thing is good power but I can’t find out how to output power.

**Comment by Mooshroom8** [comment]
Also it’s not removed

**Comment by Mooshroom8** [comment]
Didn’t mean to close

**Comment by potatoee** [comment]
igen is being remade, it sucks precisely for this reason and also isnt very efficient either

**Comment by HbmMods** [comment]
The iGen has been remade on 1.7, and assuming someone is going to continue porting some day, that issue will be resolved for 1.12 too. I'm closing the issue here, for any further 1.12 related issues please use the port's [issue tracker.](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/issues)
