### ISSUE TITLE
Charms

### ISSUE THREAD

**Issue by Hikmetcan-dev** [HbmMods/Hbm-s-Nuclear-Tech-GIT#327]
How to use the charm of protection etc. Cant be used in anyway.

**Comment by HbmMods** [comment]
It's an armor mod.

**Comment by Hikmetcan-dev** [comment]
Thank you for your response. I know it is an armor mod but the slots dont accept the charm. Should I install some other mode for inevntory?

**Comment by HbmMods** [comment]
It says what slot it goes in in the tooltip. Place a chestplate in the armor mod table first and then put the charm in the head slot.

**Comment by Hikmetcan-dev** [comment]
Okay I saw the armor modification table right now. Thank you so much for your kindness. Have a good day.
