### ISSUE TITLE
RBMK moderated fuel rods are only 50% effective

### ISSUE THREAD

**Issue by UFFR** [HbmMods/Hbm-s-Nuclear-Tech-GIT#328]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.

For moderated fuel rods only appear to moderate roughly ~50% of neutrons (give or take), leaving the other half to remain fast neutrons. While most fuels still work, they only do so at about half their efficiency.

### Please solve this equation to x

x²+3x-19=√(9x²)+6

**Comment by TehTemmie** [comment]
Based on my understanding of what happens in the runInteraction() function, it appears that a flux stream only checks if the target block is moderated and ignores the moderation of the source rod, which causes problems when a stream hits a reflector.

**Comment by HbmMods** [comment]
I haven't tested the exact behavior as described in the issue yet, but there is indeed an issue with moderated rods using reflectors. Reflectors don't actually reverse the stream's direction, instead they instantly apply the remaining flux to the source rod, bypassing all further column checking. I've added an additional case for when this happens with moderated columns, that should at least fix the issue for moderated fuel rods now working properly when used with reflectors.

**Comment by UFFR** [comment]
The update appears to have fixed the issue to the best of my knowledge.
