### ISSUE TITLE
How does the press work?

### ISSUE THREAD

**Issue by NekitPas** [HbmMods/Hbm-s-Nuclear-Tech-GIT#329]
I cannot understand how the press works, I brought electricity to it, but it does not work

**Comment by SoB1nary** [comment]
a burner press requires fuel and a stamp. stamps are made in the template folder from a flat stamp.

**Comment by NekitPas** [comment]
> a burner press requires fuel and a stamp. stamps are made in the template folder from a flat stamp.

I did everything that was needed, but it did not start

**Comment by HbmMods** [comment]
Can you send a screenshot of what you did?

**Comment by NekitPas** [comment]
> Can you send a screenshot of what you did?
![2021-11-04_21 06 13](https://user-images.githubusercontent.com/93726537/140395697-6490e775-5409-4e26-ac7a-fa07e4509e97.png)
![2021-11-04_21 06 33](https://user-images.githubusercontent.com/93726537/140395702-75e2deae-a73d-4599-869f-af2b55c7a27e.png)

**Comment by ncr-t** [comment]
its a flat stamp, use the plate stamp that you have in your inventory

**Comment by NekitPas** [comment]
> это плоский штамп, используйте пластинчатый штамп, который есть у вас в инвентаре

Oh,thanks!
