### ISSUE TITLE
Incorrect lighting with some blocks

### ISSUE THREAD

**Issue by luckybl0ck** [HbmMods/Hbm-s-Nuclear-Tech-GIT#330]
### Describe the bug

Starting from version 1.0.27_X4025, the lighting system does not work correctly with some blocks. Tested with decorative blocks of steel, tungsten, lead and beryllium.

**Forge version:** 10.13.4.1614
The problem exists both with and without OptiFine.

1.0.27 X4040:
![screenshot_4040](https://user-images.githubusercontent.com/79654924/140552201-0e03aa8c-e816-458b-b7a9-277a1714f2f3.png)

1.0.27 X4018:
![screenshot_4018](https://user-images.githubusercontent.com/79654924/140552121-544f381e-f79e-4994-8c75-b7f2fb50ef3b.png)

**Comment by HbmMods** [comment]
Already known issue, happens to every block using connected textures, apparently more common -but not exclusively - with smooth lighting on. See #321
