### ISSUE TITLE
Spark Energy Block Bug

### ISSUE THREAD

**Issue by TheGzGuy** [HbmMods/Hbm-s-Nuclear-Tech-GIT#332]
Spark Energy Block capacity turns to 1MHE rather than the normal 1THE when i leave and rejoin world.

**Comment by Antineutrino-4444** [comment]
I have the same problem

**Comment by potatoee** [comment]
happens to all energy blocks, all you can do is just break and replace them each time you rejoin, just make sure you dont waste that energy in it

**Comment by HbmMods** [comment]
That's a confirmed issue that has been fixed in-dev. Today's release will most likely fix it.
