### ISSUE TITLE
Barrels wont hold anything at all - latest version of "ouch my spleen" [CLOSED - MOD INCOMPATIBILITY]

### ISSUE THREAD

**Issue by HaxerCoder** [HbmMods/Hbm-s-Nuclear-Tech-GIT#333]

**Comment by HaxerCoder** [comment]
Hello, I was building an RBMK and no matter what I do, barrels will not hold a single thing at all

**Comment by SoB1nary** [comment]
have you even used a fluid identifier

**Comment by HaxerCoder** [comment]
yes, but I found the issue. It has a conflict with an industrialcraft beta
