### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by XanderMCDev** [HbmMods/Hbm-s-Nuclear-Tech-GIT#334]
Hello,

Is it possible to update this mod to 1.12.2?

Kind regards,
Xander

**Comment by sendhelppls213** [comment]
You do know that the 1.12 port was released more than half a year ago?

**Comment by XanderMCDev** [comment]
> You do know that the 1.12 port was released more than half a year ago?

Where can I download it?

**Comment by HbmMods** [comment]
See https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT

**Comment by XanderMCDev** [comment]
> See https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT

Well euhm, I can't code or do so I'm not sure if this works, I would just need the jar

**Comment by HbmMods** [comment]
![image](https://user-images.githubusercontent.com/16674258/141615142-deb91567-4ad7-4a60-918b-30daad876aa6.png)
![image](https://user-images.githubusercontent.com/16674258/141615145-449fd5ab-2461-4c57-86b3-7af1ca725cd7.png)

**Comment by XanderMCDev** [comment]
Is it the one released on 12 august 2020?

**Comment by HbmMods** [comment]
![image](https://user-images.githubusercontent.com/16674258/141615198-288a88fa-12ee-4078-a2dc-2840f853828a.png)
