### ISSUE TITLE
LAN world issues

### ISSUE THREAD

**Issue by Speecter** [HbmMods/Hbm-s-Nuclear-Tech-GIT#335]
At first I'd would like to note that it's not a issue that makes you unable to use whole fckn mod, but it's kinda annoying. I'm talking about problem with missiles de-rendering when flying away and that's it, they don't arrive to their target **unless** someone would be _that kind_ to render whole travel distance between launch silo and target.

**Comment by HbmMods** [comment]
Missiles are chunk-loading which has been confirmed to work in singleplayer, multiplayer and LAN worlds. I just tested it in a LAN world over a range of 1000 blocks and it seems to be working just fine. The only way I see this could be happening is if you're using a mod that messes with chunk loading, but there's not much I can do about that.

**Comment by Speecter** [comment]
Alright, found a culprit - it's optifine, and more specially (but not confirmed yet) it might be caused by one of it's settings

**Comment by HbmMods** [comment]
Quite a few people have claimed that optifine messes with chunk loading, although that's a matter of the server and OF is supposed to be a clientside only mod.

**Comment by PhantomCloak** [comment]
I can confirm that cause is optine after disabling, it started working again
