### ISSUE TITLE
Reminder about the Deuterium tower funnies + list of my sins

### ISSUE THREAD

**Issue by 7pheonix** [HbmMods/Hbm-s-Nuclear-Tech-GIT#336]
I never got time to commit this, so this is partly my fault. The deuterium tower's anvil recipe should use a tier 4 anvil, not a tier 5. The Deuterium tower is also missing a tile mapping, which is also my fault. Finally in the list of things i fucked up, the line `if(age >= 2)` in TileEntityDeuteriumExtractor, the 2 should be a 10 to limit deuterium extraction speeds, however you may want to adjust this for balancing purposes if enough people complain about it being slow.

### Please solve this equation to x

x²+3x-19=√(9x²)+6

x = 8.83
x = -2.83

**Comment by UFFR** [comment]
I believe your algebra is flawed.

-- 
UFFR

**Comment by HbmMods** [comment]
I just noticed that the deuterium extractor uses both the old `AuxElectricityPacket` and new `NBTPacket` to sync the energy level to the client, even though I can't seem to find any instance where that information is used. Could I safely remove that?
