### ISSUE TITLE
Mod Loading Issues

### ISSUE THREAD

**Issue by jackmaxim** [HbmMods/Hbm-s-Nuclear-Tech-GIT#337]
I have recently been attempting to download and use the HBM Nuclear Tech mod. However, the mod refuses to show up under the mod listing for Minecraft on the entry page. I have also started a world to see if it was just the mod listing page. It does not show up in creative or survival mode. Other mods will show up and run, so I am confident it is not an issue with the mod folder. I have also deleted then created a new mod folder, and nothing is fixed. I have tried several versions of the mod; however, none of them seem to work. I would like to know if it is a user issue, or something else.
I am currently running Minecraft 1.17.10, Forge 1.17.1 - 37.0.109, and I am attempting to run HBM's  Nuclear Tech Mod HBM-NTM-[1.0.27_X4026].jar
### Please solve this equation to x

x²+3x-19=√(9x²)+6

**Comment by FavoritoHJS** [comment]
Are you sure you are using 1.7.10 and not 1.17.1?
This mod is for 1.7.10, and a port for 1.12.2 exists.
HBM's Nuclear Tech Mod does not exist in 1.17.

**Comment by TheNewGuy19** [comment]
1.7.10 and 1.17.1 are different versions, and mods that are made for one will be completely incompatible with the other. If you want to use NTM, as Favorito said, there is a 1.7.10 version (the primary one), and a 1.12.2 port. If you're going to ask for someone to port the mod to 1.17.1, as has been said a thousand times before, do it yourself.

**Comment by jackmaxim** [comment]
Thank you for answering my question
