### ISSUE TITLE
CIWS "Howard" Unable to shoot down Missiles

### ISSUE THREAD

**Issue by Duncan56** [HbmMods/Hbm-s-Nuclear-Tech-GIT#340]
### Describe the bug

The Howard Turret Does not shoot down missiles
If has been set up correctly to the best of my knowledge. They shoot at the missiles but they do not destroy them
I will provide any mod lists that are necessary

**Comment by HbmMods** [comment]
What missiles did you test? How many turrets did you use? Do the turrets do damage at all, for example against mobs? Was the chunk with the turret loaded when the missile was approaching?

**Comment by Duncan56** [comment]
I tried a variety of missiles including:
HE Missile
Bunker Buster
Spare Missile

It does do damage to mods, but is extremely inaccurate and takes almost a whole clip to kill a pig

I used 4 Turrets

yes the chunks were loaded when the missile approached

**Comment by ncr-t** [comment]
HE is like the most basic missile in the mod, so if it can't destroy it there's a problem

**Comment by godtm23** [comment]
wavtr_5ffdcac3-f93a-4995-b868-b3a5c64b265d

**Comment by Shibva** [comment]
@Duncan56 could you please check with the most recent version to see if this issue is still valid?
