### ISSUE TITLE
Radars are not good

### ISSUE THREAD

**Issue by ektorthebigbro** [HbmMods/Hbm-s-Nuclear-Tech-GIT#344]
Hi I was trying to build an automatic defense system using antiballistics turrets and radars. Radars don't help a lot when they just five a Redstone output . You can fix that by adding a new setting like enable Redstone if the missile/player goes closer than (number) blocks or if you want to be more specific add a block that extends it and say like if there is  one target output there if two there .also you could add a configuration on the radar block for the player to specify where he wants it to put put and what

**Comment by HbmMods** [comment]
Redstone output is based on proximity (by default, at least) so you can easily trigger stuff like ABMs by simply spacing out your redstone line.
