### ISSUE TITLE
Maxwells 

### ISSUE THREAD

**Issue by ektorthebigbro** [HbmMods/Hbm-s-Nuclear-Tech-GIT#347]
I was playing with a friend today and when a missile came maxwells didn't even lock on it while I had the option on .I tested it multiple times but still the same

**Comment by HbmMods** [comment]
Turrets have limited elevation and missiles usually a steep impact trajectory, preventing most of them from being useful against missiles. The exception being the CIWS since it's a dedicated anti air turret.

**Comment by ncr-t** [comment]
why the fuck would you use the maxwell as an anti air. its not like CIWS ammo is expensive like

**Comment by ektorthebigbro** [comment]
Wanna tell you why cause maxwells don't need to reload but ciws need and when you have a large system it is a pain in the ass
