### ISSUE TITLE
gun shooting out flame 

### ISSUE THREAD

**Issue by fusge12** [HbmMods/Hbm-s-Nuclear-Tech-GIT#351]
hello i had an issue when a used the machine gun hbm in HBM-NTM-.1.0.27_X4060 1.7.10 after a while the gun started to not shoot 
but instead shot flames and smoke and the immolato and b93 work fine
![20211202_155539](https://user-images.githubusercontent.com/95415283/144409148-0169a5dc-45bd-41f1-b2c8-db1373f06136.jpg)
![20211202_155539](https://user-images.githubusercontent.com/95415283/144409190-591bd3b6-ddec-430b-a708-88ea9a31447b.jpg)

**Comment by ncr-t** [comment]
like a real gun... try shooting at something... (((You're EXPOSED)))

**Comment by fusge12** [comment]
it doesn't fire at mobs
and i tried with every other gun only guns that fire are guns which you can fire your right mouse button

**Comment by sendhelppls213** [comment]
Are you unable to read changelogs?
