### ISSUE TITLE
Request for a config option to change entity IDs(using antiidconflict as guidance)

### ISSUE THREAD

**Issue by WolfBV** [HbmMods/Hbm-s-Nuclear-Tech-GIT#354]
### Describe the bug

Using a mod called Arcana RPG, it requires on of its entities to have an ID under 32. This mod and one other along with base minecraft occupies the first 31 IDs. Could a config option to change the IDs of your entities be added?

### Please solve this equation to x

x²+3x-19=√(9x²)+6

I don't own a graphing calculator nor do I remember how to do this. I only learned to do math to get a passing grade with no thought to what I'd do if I forgot how to do it in the future .-.
https://www.wolframalpha.com/input/?i=x²%2B3x-19%3D√%289x²%29%2B6

**Comment by TheForge129** [comment]
you don't need a graphing calculator

**Comment by WolfBV** [comment]
Do entity IDs even need to be assigned >.<

nvm, I'll ask the Arcana RPG author if they can raise their ID limit from 31 to 200
