### ISSUE TITLE
Problem with cooling nuclear fuel

### ISSUE THREAD

**Issue by Burnedoutschrabidium327** [HbmMods/Hbm-s-Nuclear-Tech-GIT#356]
I waited an hour and depleted fuel didnt cooled down is it bug from new version or the time is longer.   (Yes i put spent fuel pool drum under water)

Please solve this equation to x
x²+3x-19=√(9x²)+6
x²+3x-19=3x+6
x²-19=6
√x²=√25
x = 5

**Comment by HbmMods** [comment]
Should be fixed in the current release.
