### ISSUE TITLE
suggestion for nuclear reactors

### ISSUE THREAD

**Issue by Burnedoutschrabidium327** [HbmMods/Hbm-s-Nuclear-Tech-GIT#360]
When Zirnox reactor meltdowns it leave destroyed in half 
So what if small nuclear reactor also could explode and leave destroyed in half and some radioactive pieces like fuel rods or broken metal bars and others.
And if its posible to make that green ooze will Solidify in variants od sellafite like corium does.

**Comment by ShimmeringBlaze** [comment]
![814904330020716624](https://user-images.githubusercontent.com/67163329/144765746-6f9b357f-e79e-4fe8-b55d-cd5f16751326.png)

**Comment by HbmMods** [comment]
what

**Comment by ncr-t** [comment]
1- I'm 99% sure that its said to not suggest stuff in the issues
2- the small reactor is getting erased soon
3-how the fuck do you even meltdown the small reactor when you have 3 braincells
