### ISSUE TITLE
Industrial generator rendering incorrectly

### ISSUE THREAD

**Issue by TehTemmie** [HbmMods/Hbm-s-Nuclear-Tech-GIT#361]
The industrial generator's item renders like this:
![2021-12-06_15 10 27](https://user-images.githubusercontent.com/36060353/144806087-d2f764ad-8179-43ad-a6c1-d03d086b9f43.png)

When placed, the model is offset from the actual dummy blocks in the generator. In the screenshot below, the yellow and black wool  marks out where the actual blocks are:
![2021-12-06_15 41 57](https://user-images.githubusercontent.com/36060353/144806682-e2e6565d-82fd-4e97-9446-aba09eec6e47.png)

### Please solve this equation to x

x²+3x-19=√(9x²)+6
x^2 + 3x - 25 = abs(3x)
Case 1: x^2 + 3x - 25 = 3x and x >= 0
x^2 - 25 = 0
x = 5
Case 2: x^2 + 3x - 25 = -3x and x < 0
x^2 + 6x - 25 = 0
x = (-6 - sqrt(36 + 100)) / 2 = -3 - sqrt(4 * 34) / 2 = -3 - sqrt(34)
x = 5, -3 - sqrt(34)

**Comment by HbmMods** [comment]
The model having the wrong offset is already a known issue. The held model looking like that is the result of the model being changed but the render class not being changed from the old iGen, I put that off for the next update since I was short on time.
