### ISSUE TITLE
??????????????????????????

### ISSUE THREAD

**Issue by ektorthebigbro** [HbmMods/Hbm-s-Nuclear-Tech-GIT#366]
![image](https://user-images.githubusercontent.com/85633839/145866122-86dbdfcd-4207-4e70-935a-d4cc42ca0c0d.png)
???????????????????????????????????????????????????????????????????????????
1)600the per second 
2)most powerful bomb in all hbm history
3)why do you allow things like these to happen?
4)64 cores
5)uses more fuel than anyone's mind can imagine 
??????????????????????????????????????????????????????????????????????????

**Comment by ektorthebigbro** [comment]
also i did not create this

**Comment by HbmMods** [comment]
...why did you feel the need to tell me about this? Is there something wrong here?

**Comment by ektorthebigbro** [comment]
why?

**Comment by ektorthebigbro** [comment]
tho

**Comment by Vaern** [comment]
Someone needs help here

**Comment by ektorthebigbro** [comment]
whatever i will close the issue

**Comment by HbmMods** [comment]
Why what? Are you alright my dude?

**Comment by ektorthebigbro** [comment]
i am just questioning why this exists in the mod

**Comment by HbmMods** [comment]
Why, what's wrong with it?

**Comment by ektorthebigbro** [comment]
ammm it can easily wipe out a really large area and would be bad for a server

**Comment by HbmMods** [comment]
That's what highly unstable plasma orb reactors do, shouldn't be too unexpected.

**Comment by ektorthebigbro** [comment]
ok but i am pretty sure that this is pretty late game

**Comment by ektorthebigbro** [comment]
if it is possible in survival

**Comment by HbmMods** [comment]
Yes, it is.

**Comment by ektorthebigbro** [comment]
ik but how do you run this thing,i mean the amounts of fuel you need per second

**Comment by Pato0101** [comment]
"bad for a server"
well yeah all it takes is beating the mod at that point you can probably allready do that for a much cheaper price

**Comment by ektorthebigbro** [comment]
i wonder what the explosion radius will be

**Comment by 7pheonix** [comment]
Wait, so you haven’t even tested it?

**Comment by ektorthebigbro** [comment]
you want this to explode in your computer really

**Comment by ektorthebigbro** [comment]
i personally don't have 4 graphic cards to test it

**Comment by Pato0101** [comment]
8 wont be bigger than 1...

**Comment by UFFR** [comment]
What even is the point of all this?

**Comment by ektorthebigbro** [comment]
to recreate infinate battery from creative invetory

**Comment by Adam29Adam29** [comment]
Uhh, why are you trying to recreate an *infinite* battery which is only used for creative only purposes

**Comment by ektorthebigbro** [comment]
infinite battery for survival version

**Comment by Adam29Adam29** [comment]
My fella, 1 DFC is the only thing you will ever need and not bloody 64 cores 

._.

**Comment by ektorthebigbro** [comment]
one dfc is not enough for more than three particle accelerators

**Comment by P3tux0** [comment]
please don't cancel me for creating this useless monstrocity

**Comment by ektorthebigbro** [comment]
oh yeah he created it

**Comment by Pato0101** [comment]
> one dfc is not enough for more than three particle accelerators

uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by ektorthebigbro** [comment]
ok if not 3 10

**Comment by Adam29Adam29** [comment]
Im in the lack of words by the brain rot of this whole opened issue. Which has no real purpose to even have been opened and is just causing unnecessary use of the issue opening tool....

**Comment by P3tux0** [comment]
also i made binary dfc reactor that diferently from that abomination of humanity is actualy good
output energy: 5.46the
does not consume that much fuel
has a cool name: Polarities
and has a explosion radius of 1048 blocks
![image](https://user-images.githubusercontent.com/96079456/145870363-8893af38-e2f2-4d0b-bb6a-6109ea978819.png)

**Comment by Pato0101** [comment]
dude.

**Comment by P3tux0** [comment]
what

**Comment by Vaern** [comment]
mmm, rotten brain

**Comment by ncr-t** [comment]
do you smell the glue too ? hmmpppphhhhfff

**Comment by Joey-Destroyah** [comment]
yes
