### ISSUE TITLE
Radiation Fog Lag

### ISSUE THREAD

**Issue by datboiiskool** [HbmMods/Hbm-s-Nuclear-Tech-GIT#370]
When I was trying to nuke or use a reactor, my game lags because of the radiation fog. HBM, can you fix the radiation fog lag so that I can nuke or use a reactor please.

**Comment by datboiiskool** [comment]
I also don't know how to add a tag, can you help me.

**Comment by sendhelppls213** [comment]
You can stop now

**Comment by ncr-t** [comment]
two option : 
-get a better pc
-just go in the config and disable it…

**Comment by HbmMods** [comment]
`6.07_fogThreshold` changes the minimum radiation required to start spawning fog particles, `6.08_fogChance` determines the average amount of seconds in between fog spawning in each chunk.

**Comment by datboiiskool** [comment]
> `6.07_fogThreshold` changes the minimum radiation required to start spawning fog particles, `6.08_fogChance` determines the average amount of seconds in between fog spawning in each chunk.

Thanks!
