### ISSUE TITLE
Gelid Euphemium don't desappear

### ISSUE THREAD

**Issue by The-Quarker** [HbmMods/Hbm-s-Nuclear-Tech-GIT#373]
When I try to break gelid euphemium, it automatically replaces. That's what they say on the wiki. They also say that it would desappear in a short period of time, but mine is still here even if I placed it yesterday.

**Comment by HbmMods** [comment]
Did you turn on the config for spreading/virus blocks? It's not going to do anything if that's turned off, which it is by default.

**Comment by The-Quarker** [comment]
ok thanks
