### ISSUE TITLE
Using missile and game crashed

### ISSUE THREAD

**Issue by caspap** [HbmMods/Hbm-s-Nuclear-Tech-GIT#374]
I used the missile launch pad to launch a missile when I input a redstone signal, the whole game crashed. Then I changed any kind of missile.But it's still crashing the game.I'm wondering what's cause this error or is any problem on my play?

**Comment by MartinTheDragon** [comment]
Please provide a crash report.

**Comment by caspap** [comment]
I found out what cause this crash,when I used a short range target designator and select no target.Then launch the missile will crash the game.Here's my gamelog:https://paste.ee/p/rmdvr

**Comment by TheEndBoss101** [comment]
Try setting a destination

**Comment by HbmMods** [comment]
Fixed in X4109
