### ISSUE TITLE
Digamma Screen Glitch

### ISSUE THREAD

**Issue by datboiiskool** [HbmMods/Hbm-s-Nuclear-Tech-GIT#375]
When I created a new world after melting down a RBMK with digamma fuel or using a null rocket, I see the digamma screen.

**Comment by Joey-Destroyah** [comment]
Firstly, what do you mean by digamma screen, and secondly, I thought that
the null item was supposed to be used for something else.

**Comment by datboiiskool** [comment]
I melted down a RBMK with digamma fuel or shooted a null rocket. After the explosion, I see the digamma screen sometimes. When I created a new world, I still see it sometimes.

**Comment by datboiiskool** [comment]
And also to shoot a null rocket, you need to load it in Karl.

**Comment by datboiiskool** [comment]
If you still don't know what is it, meltdown a RBMK with digamma fuel or shoot a null rocket to see it.

**Comment by potatoee** [comment]
> I melted down a RBMK with digamma fuel or shooted a null rocket. After the explosion, I see the digamma screen sometimes. When I created a new world, I still see it sometimes.

That's called "ash"

**Comment by potatoee** [comment]
Also, this issue is known
I think that it's an optifine issue
Delete optifine, or close the game fully

**Comment by datboiiskool** [comment]
> > I melted down a RBMK with digamma fuel or shooted a null rocket. After the explosion, I see the digamma screen sometimes. When I created a new world, I still see it sometimes.
> 
> That's called "ash"

Oh ok.

**Comment by Shibva** [comment]
I think I have the same isssue, though it looks like this

![image](https://user-images.githubusercontent.com/38770780/157338079-4cd9306a-0d47-41e8-a8fb-fb49a3e0c7bf.png)

**Comment by 7pheonix** [comment]
Is the ash overlay remaining upon switching worlds, dying or otherwise staying when it shouldn’t? Otherwise it’s not a bug, just an intended mechanic.

**Comment by Shibva** [comment]
it seems to linger a bit when you get out of its AOE

**Comment by 7pheonix** [comment]
If by that you mean it stays for 10 or so seconds, then that’s intended.

**Comment by Shibva** [comment]
yeah, but its kind of buggy, I thought it would look more like one of thaumcrafts effects or one of those things when you get close to something with chromacraft

like the screen starts to fog up

furthermore the ash googles are not working if that's what their also supposed todo

**Comment by 7pheonix** [comment]
Can you elaborate more about what’s not working about the ash goggles? Does the ash overlay persist for more than 20 or so seconds after putting them on?

**Comment by HbmMods** [comment]
Apparently some mods (it's probably optifine *again*) interfere with the overlay rendering, causing it to always render with fully occupancy. I'll probably rewrite the entire thing because right now there's (*yet another*) optifine incompatibility that causes the overlay to swivel off into the distance when you turn your head.

**Comment by Shibva** [comment]
no, I thought the ash goggles would prevent the overlay from happening

**Comment by Shibva** [comment]
id also thought it would look more like a screen effect that slowly covers up from the corners as if it was raining ash slowly. something like that would be sick AF

**Comment by HbmMods** [comment]
> no, I thought the ash goggles would prevent the overlay from happening

It should cap the occupancy at about 10%, compared to the roughly 80% when not wearing any protection.

**Comment by Shibva** [comment]
apperently thats not working

**Comment by Shibva** [comment]
it also flickering like mad when I'm in that zone

**Comment by SteamDoge9000** [comment]
Reworking it with a high effort visual effect would be sick! for a point of reference, maybe something like With ChromimacCrafts visual effects
Example:

keeping a distance
![image](https://user-images.githubusercontent.com/38770780/157391679-58958390-2a53-4102-8efa-0f8fd14a7627.png)

closer
![image](https://user-images.githubusercontent.com/38770780/157391783-77d2fe7a-9ddb-4130-a410-d2b872954ebe.png)

TOO CLOSE!
![image](https://user-images.githubusercontent.com/38770780/157391828-c071f94e-cd9d-471b-bcc1-ed1988cd9ef2.png)

something simular to these effects with ash would be a interesting visual effect, though this is just my thoughts of what ash would look like

(not literally red, but the effect patterns are close to what I had in mind originally when I Thought of ash overlay)

**Comment by SteamDoge9000** [comment]
the idea on this thought of mine was for this "ash coloed like fuzz" to begin to slowly overtake your screen and even more so when your closer to di-gamma ash

**Comment by HbmMods** [comment]
Technically fixed due to the digamma overlay effect being removed.
