### ISSUE TITLE
When will you add the conveyor belt?

### ISSUE THREAD

**Issue by datboiiskool** [HbmMods/Hbm-s-Nuclear-Tech-GIT#377]
When I was searching for something in the creative menu, I saw "tile.conveyor.name" or conveyor. When I try it out, It moves stuff, but unfortunatly, it's W.I.P. So @HbmMods , When will you add it because this mod currently lacks on automation?

**Comment by datboiiskool** [comment]
There's also "tile.machine_shredder_large.name" or large shredder.

**Comment by bebr9000** [comment]
xd
