### ISSUE TITLE
Plutonium-238 Texture Not Updated

### ISSUE THREAD

**Issue by datboiiskool** [HbmMods/Hbm-s-Nuclear-Tech-GIT#381]
The Plutonium-238 texture looks like the texture before Minecraft's Village & Pillage update. Can you update it?

**Comment by HbmMods** [comment]
![image](https://user-images.githubusercontent.com/16674258/148680702-58bca6b1-f1f3-41ba-8ab3-6e5372b3d664.png)
No?

**Comment by datboiiskool** [comment]
> ![image](https://user-images.githubusercontent.com/16674258/148680702-58bca6b1-f1f3-41ba-8ab3-6e5372b3d664.png) No?

Remember you updated most of the textures to fit the 1.14 update.

**Comment by Adam29Adam29** [comment]
![1d4217c867d2c6c959f517ec7bbd679f7c9eef68c938dc2ff4a6ab491ae23441_1](https://user-images.githubusercontent.com/92393622/148680905-044d8f17-67e2-4029-bba9-433056dd5a57.jpg)

**Comment by HbmMods** [comment]
> Remember you updated most of the textures to fit the 1.14 update.

An that is a completely new texture that's supposed to highlight the fact that plutonium-238 is glowing, which was made *after* most of the updated ingot textures using the 1.14 base.

**Comment by 7pheonix** [comment]
make a texture pack with your own texture if you don’t like it
