### ISSUE TITLE
what about pollution system

### ISSUE THREAD

**Issue by bebr9000** [HbmMods/Hbm-s-Nuclear-Tech-GIT#386]
what about pollution system like from pollution of realms but beter

**Comment by FatSassin** [comment]
There are not enough petrol based generatos for implementing pollution i think

**Comment by 7pheonix** [comment]
This is a place for bug and crash reporting, not suggestions

**Comment by SoB1nary** [comment]
This mod has Pollution of the Realms support. Have a good day.
