### ISSUE TITLE
[Suggestion] NTM Reloaded Control Panel

### ISSUE THREAD

**Issue by TheEndBoss101** [HbmMods/Hbm-s-Nuclear-Tech-GIT#395]
Feature Request
Control Panel from NTM reloaded
[Link of some one showing it off. ](https://youtu.be/BH34S4d-2Ik) 
Please add, I thought that this is really cool.
Thank you, TheEndBoss_101

**Comment by TheEndBoss101** [comment]
Please respond.

**Comment by TheEndBoss101** [comment]
Anyone

**Comment by 7pheonix** [comment]
Hello sir, I believe you are confused.
This is the “issues” section of GitHub, not the suggestions section, which does not exist.
Perhaps you mistook the words. I would reccomend getting glasses.

**Comment by TheEndBoss101** [comment]
Ok, then where are they

**Comment by TheEndBoss101** [comment]
And #408 is a suggestion

**Comment by TheEndBoss101** [comment]
And the enhancement label?

**Comment by Vaern** [comment]
> And #408 is a suggestion

Indeed it is, so neither it nor this suggestion will be merged into the mod.

**Comment by TheEndBoss101** [comment]
Then where do I submit to suggestions?

**Comment by ncr-t** [comment]
you don’t.

**Comment by Vaern** [comment]
Nowhere.
