### ISSUE TITLE
The new cables ruined DFC

### ISSUE THREAD

**Issue by P3tux0** [HbmMods/Hbm-s-Nuclear-Tech-GIT#397]
So basicaly the new cables have a capacity limit and cause that dfc can not be runned at its maximum potential making it not worth obtaining
![image](https://user-images.githubusercontent.com/96079456/150499008-dd79e5cb-43c2-4960-9177-6db5b381c80e.png)
![image](https://user-images.githubusercontent.com/96079456/150501164-d56d234e-6b02-4ea2-8250-dff729e24bc9.png)
![image](https://user-images.githubusercontent.com/96079456/150501252-adae5ed9-500a-43ab-a35a-545fa34e06dd.png)

**Comment by P3tux0** [comment]
can you make a new type of cable to suport that much energy

**Comment by TheEndBoss101** [comment]
That would be cool a high power cable

**Comment by HbmMods** [comment]
After some testing I've found that there was in fact an issue that would limit cable throughout to roughly 2.1 GHE/t per connection. It's fixed now in dev which should release this sunday.

> That would be cool a high power cable

I hate the idea of tiered cables and I can't stand how every tech mod uses them. NTM cables will always have infinite throughput.
