### ISSUE TITLE
Fog Causes HUGE amounts of lag

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#399]
![2022-01-21_16 14 52](https://user-images.githubusercontent.com/68939428/150601058-8266a96f-b79d-499f-b507-0e58a4963139.png)

Cooling towers are very essential for cooling RBMK's since they chug water at high temperatures. I need at least 2 to maintain a stable water supply but the lag is so dramatic that i can only have one to none at all. We need a system that limits the amount of fog that they spawn or a option to disable it all together. I don't want to even hear "Get a better PC" because that is not a good, valid excuse to leave it unpatched.

**Comment by ghost** [comment]
Also forgot to add the same issue with leviathan turbines.
![2022-01-21_16 17 37](https://user-images.githubusercontent.com/68939428/150601363-a800079d-efca-4886-b731-7a4b80c0c6bd.png)

**Comment by MientusOfficial** [comment]
M8 just disable particles minimum in options and you'll no longer see particles in turbines

**Comment by ghost** [comment]
It fixed the turbines but i can't say the same for the cooling towers.

**Comment by ghost** [comment]
POV: You are a staff in a discord server and you leave reactions in the github issues channel because they can't insult you there

**Comment by ncr-t** [comment]
POV: you don't have common sense and know basic things that could cause your performances to fail

**Comment by Vaern** [comment]
POV: bunger

**Comment by sendhelppls213** [comment]
![hqdefault (1)](https://user-images.githubusercontent.com/57670225/151087228-980b1a42-3655-4ac1-978d-4f309b3d95eb.jpg)

**Comment by Vaern** [comment]
![metal-gear-rising-smile](https://user-images.githubusercontent.com/90118520/151087398-91a3e217-4475-4653-966b-52728935d7df.gif)

**Comment by TheNewGuy19** [comment]
POV: argh

**Comment by ghost** [comment]
Bozo stay mad staff

**Comment by Vaern** [comment]
![resize](https://user-images.githubusercontent.com/90118520/151101214-bf32c633-65dc-4dd6-b691-c2493d7cb190.gif)

**Comment by sendhelppls213** [comment]
You're the one who has a skill issue and can't fix a problem which only appears on your end.

**Comment by ghost** [comment]
Suck my dick fag, your mod is buggy and is on 1.7.10.

**Comment by superturtle03** [comment]
> Suck my dick fag, your mod is buggy and is on 1.7.10.
> […](#)
> Sent from my iPad
> On Jan 25, 2022, at 11:04 PM, Nuclear_pashtet ***@***.***> wrote: ﻿ You're the one who has a skill issue and can't fix a problem which only appears on your end. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you modified the open/close state.

well if you dont like it you can fix it yourself

**Comment by UFFR** [comment]
![yuyuko cry about it](https://user-images.githubusercontent.com/63076393/151103953-6b570a39-8b83-449e-a49c-fc9e5fe2b1e2.gif)

**Comment by Pato0101** [comment]
issues that are mostly related to the opponents skill level, with extremely high chances that the problems in question are caused, directly or indirectly by the opponent coping.

**Comment by TheNewGuy19** [comment]
Jesus christ McUtter, no need to cope that hard over a major skill issue entirely on your part.

**Comment by Sexygeorgeofthejungle** [comment]
..it isn't that hard to just change the particles in config..

**Comment by Pato0101** [comment]
> issues that are mostly related to the opponents skill level, with extremely high chances that the problems in question are caused, directly or indirectly by the opponent coping.

In other words,
cope seethe mald reddit cope

**Comment by HbmMods** [comment]
Get a better PC
