### ISSUE TITLE
HBM will overlay Optifine's sky map

### ISSUE THREAD

**Issue by mcmso** [HbmMods/Hbm-s-Nuclear-Tech-GIT#400]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.

Didn't meet a crash
HBM will overlay Optifine's sky map
Are you compatible with it
thanks

### Please solve this equation to x

x²+3x-19=√(9x²)+6

±√34 -3 ±5

**Comment by HbmMods** [comment]
NTM's skybox isn't compatible with other mods right now and will always attempt to override them.
