### ISSUE TITLE
How to activated doRTGsDecay

### ISSUE THREAD

**Issue by SannUlya** [HbmMods/Hbm-s-Nuclear-Tech-GIT#401]
Can someone describe the tutorial how to enable RTG

**Comment by ncr-t** [comment]
its activated by default iirc, if not, edit it in the config. if its not in the config, remove the config file and restart your game

**Comment by SannUlya** [comment]
> ini diaktifkan secara default iirc, jika tidak, edit di konfigurasi. jika tidak ada dalam konfigurasi, hapus file konfigurasi dan mulai ulang game Anda

where is the config file located?
