### ISSUE TITLE
How to use a debug wand?

### ISSUE THREAD

**Issue by datboiiskool** [HbmMods/Hbm-s-Nuclear-Tech-GIT#403]
I saw an item called "Debug Wand", how do you use it?

**Comment by TEKNO3OOO** [comment]
If you are speaking about the debug want of vanilla its to rotate block i think
https://minecraft.fandom.com/wiki/Debug_Stick

**Comment by Joey-Destroyah** [comment]
He is probably talking about ntm

**Comment by TEKNO3OOO** [comment]
OOO yes the debug wand of hbm is for developer to test new WIP thing i think, on 1.12.2 hbm it spawn a buggy spider, before its spawn some structure ect

**Comment by Joey-Destroyah** [comment]
There is now a structure wand in place of the debug's original function,
and there is a wand which is a clone of worldedit, but with no commands.

**Comment by P3tux0** [comment]
debug want wasn't exactly meant to be used by players it even says on the description "Used for debugging purposes"
