### ISSUE TITLE
[suggestion]wuold u like to add a Liquid Concrete in 1.7.10( just like IE in 1.12.2)?

### ISSUE THREAD

**Issue by iamsoNewBee** [HbmMods/Hbm-s-Nuclear-Tech-GIT#408]
as my tittle
it`s much more convient for players to build large buildings...

**Comment by datboiiskool** [comment]
Y E S

**Comment by iamsoNewBee** [comment]
> Y E S

W H A T ?

**Comment by Shibva** [comment]
that could be useful, but unfornatly as many times as I was told, this is no place for suggestions and never will be a place for such. though it does make sense you mix concrete to make it, its unlikely this going to happen

id recommend closing this issue

**Comment by iamsoNewBee** [comment]
> 这可能很有用，但不幸的是，正如我被告知的那样，这不是提出建议的地方，也永远不会是提出建议的地方。虽然你混合混凝土来制造它确实有意义，但这不太可能发生
> 
> id 建议关闭此问题

it`s pity.and the new liquefactor is really suitable to do it
