### ISSUE TITLE
impossible to build 

### ISSUE THREAD

**Issue by ApexElite3303** [HbmMods/Hbm-s-Nuclear-Tech-GIT#409]
### Describe the bug

when i open the mod in gitbash, and attempt to decompile (or even build it for that matter) , the build fails. a log can be found here.
>$ ./gradlew setupDecompWorkspace

>FAILURE: Build failed with an exception.

>* What went wrong:
>Could not determine java version from '11.0.8-internal'.

for all I know, this could be an issue on my part, but reinstalling my java gave me the same result. any help would be appreciated 
### Please solve this equation to x

x²+3x-19=√(9x²)+6
(x^2)+3x-19=3x+6
(x^2)+3x-25=3x
(x^2)-25=0
x^2=25
x=5
i think

**Comment by HbmMods** [comment]
Minecraft 1.7 only works with java versions 6-8, NTM specifically uses code that requires java 8.

**Comment by ApexElite3303** [comment]
> Minecraft 1.7 only works with java versions 6-8, NTM specifically uses code that requires java 8.

yeah, i have java 8 version 321. im not exactly sure why it states 11.0.8.

**Comment by HbmMods** [comment]
JDK or JRE? Did you configure the java path correctly? Are you absolutely sure that you son't have any duplicate installs with higher versions?

**Comment by ApexElite3303** [comment]
after some playing around i found i had JRE installed, so i reinstalled JDK. i still have no idea where to put the openJDK file, so its just sitting in my download, and obviously the JAVA_HOME path has nowhere to go. am i meant to do change something?

**Comment by HbmMods** [comment]
I'd assume the OpenJDK file is an installer with the system variables pointing wherever it installs the JDK to, most likely into the Program Files folder. Did the page you got it from come with any instructions on how to use it?

**Comment by SannUlya** [comment]
Uninstall your latest java and installing java 8 (OpenJDK8). Sorry if I wrong 🗿🗿🗿
