### ISSUE TITLE
how big is the chance to get lodestone?

### ISSUE THREAD

**Issue by SannUlya** [HbmMods/Hbm-s-Nuclear-Tech-GIT#414]

**Comment by HbmMods** [comment]
1 in 64 every time you take iron ingots out of a furnace (or electric or arc furnace), stack size of the output is ignored, a full stack has the same 1:64 chance as a single ingot.

**Comment by SannUlya** [comment]
> 1 dari 64 setiap kali Anda mengeluarkan batangan besi dari tungku (atau tungku listrik atau busur), ukuran tumpukan dari output diabaikan, tumpukan penuh memiliki peluang 1:64 yang sama dengan satu batangan tunggal.

Iron ingot from crystal, from iron ore or powder?

**Comment by HbmMods** [comment]
It only works when you move the ingot out of the slot into your inventory (i.e. the same trigger that the iron achievement has), so automation won't work.
