### ISSUE TITLE
Some Odd Radiation

### ISSUE THREAD

**Issue by VeiTheOne** [HbmMods/Hbm-s-Nuclear-Tech-GIT#416]
Is this normal, or is it something I missed? Radiation spreads via Chunk instead of the usual circular.

![image](https://user-images.githubusercontent.com/82922007/151720272-4f060df8-ceb7-4445-b6ff-6137e6dc114f.png)

**Comment by MartinTheDragon** [comment]
Those are environmental radiation effects. Chunk radiation causes them, as well as Meltdown Gas released by the ZIRNOX. Bombs will still make that "circular" radiation, the fallout zone.

**Comment by VeiTheOne** [comment]
Ahhhhh
