### ISSUE TITLE
Light Gray Concrete in NEI, but not craftable

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#417]
In version X4130 the "Light Gray" color of concrete has neither the recoloring recipe, or the coloring recipe (using just concrete). Given that this concrete can be subsequently recolored into other colors and the fact it's in NEI leads me to believe that for whatever reason it's missing.

For the equation:
x²+3x-19=√(9x²)+6
x^2 + 3x - 19 = 3x + 6
x^2 - 19 = 6
x^2 = 25
x = 5 
(Yes I showed my work)

**Comment by HbmMods** [comment]
These recipes are actually autogenerated using vanilla's color names as the ore dictionary ingredient name. Turns out that forge's dict names for dyes match the vanilla names _except_ for light gray dye which is "lightGray" in the ore dict and "silver" in vanilla.

**Comment by thePalindrome** [comment]
Reporting it fixed with 4130H1 and closing, although gotta love the pure dabbery of it all
