### ISSUE TITLE
How to use FEL and SILEX

### ISSUE THREAD

**Issue by SannUlya** [HbmMods/Hbm-s-Nuclear-Tech-GIT#418]
Every time I turn on the fel, it destroys the **SILEX**

**Comment by 7pheonix** [comment]
The laser has to enter in the right port. It has to go into the squareish one in the centre of the silex’s side, and come out on the other identical port on the other side. You know you’ve got the right one because the other two remaining ports should connect to fluid ducts.

**Comment by SannUlya** [comment]
> Laser harus masuk di port yang benar. Itu harus masuk ke kotak persegi di tengah sisi silex, dan keluar di port identik lainnya di sisi lain. Anda tahu bahwa Anda memiliki yang benar karena dua port lainnya yang tersisa harus terhubung ke saluran fluida.

How about this

![2022-01-31_22 21 14](https://user-images.githubusercontent.com/98253949/151822926-84c8d5d3-3a32-44ab-b173-1d291fc2ac0f.png)

![2022-01-31_22 21 18](https://user-images.githubusercontent.com/98253949/151822895-9cd563ec-e44d-43ec-a732-487c07d9dd27.png)

**Comment by ncr-t** [comment]
its too close to the FEL I think it has to be 3 block far from it

**Comment by SannUlya** [comment]
> terlalu dekat dengan FEL saya pikir itu harus 3 blok jauh dari itu

Thank you so much, this is truthly help me 🗿🗿🗿 

![2022-01-31_22 46 25](https://user-images.githubusercontent.com/98253949/151826746-ee0ba4cb-87dd-44ab-b1db-f558d53bfb08.png)
