### ISSUE TITLE
Putting invalid item into liquefactor cause game crash.

### ISSUE THREAD

**Issue by C4885** [HbmMods/Hbm-s-Nuclear-Tech-GIT#421]
Works well for correct item such as coal. But dirt, lignite, etc... cause game crashes.

**Comment by HbmMods** [comment]
And thus, the "potential" crash turns into a "guaranteed" crash, oh dear.

**Comment by HbmMods** [comment]
Should be fixed with the latest release, I'll leave the issue open until we know for sure.
