### ISSUE TITLE
Renewable Energy Generation

### ISSUE THREAD

**Issue by datboiiskool** [HbmMods/Hbm-s-Nuclear-Tech-GIT#422]
Water Turbine:
-Generates HE with running water.
-Generates more HE with more running water.
Wind Turbine:
-Generates HE with wind.
-Generates more HE the higher the structure.
Solar Panel
-Generates HE with sunlight.
-Dosen't generates HE without sunlight.

**Comment by Adam29Adam29** [comment]
Sir, this isn't a "suggestion board" but to open issues for to report bugs and errors and not your crappy suggestions which were certainly already rejected when brought up on the discord server.

**Comment by datboiiskool** [comment]
> Sir, this isn't a "suggestion board" but to open issues for to report bugs and errors and not your crappy suggestions which were certainly already rejected when brought up on the discord server.

Oh, ok.

**Comment by HbmMods** [comment]
Renewables suck
