### ISSUE TITLE
Liquefactor turn coal to fluid coal oil

### ISSUE THREAD

**Issue by SannUlya** [HbmMods/Hbm-s-Nuclear-Tech-GIT#423]
Is this true?
Cause the last time that turned into crude oil

![2022-02-02_22 12 45](https://user-images.githubusercontent.com/98253949/152182626-03ca98f4-5164-41b7-9c33-752134d9ab1f.png)

**Comment by HbmMods** [comment]
The coal to oil conversion was only a placeholder, although the current version was supposed to have it still.
