### ISSUE TITLE
Long Loading Time With Gregtech 6

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [HbmMods/Hbm-s-Nuclear-Tech-GIT#43]
Greg tried to add integration for this mod to Gregtech 6 a while ago, but he couldn't do it because it takes longer than 30 minutes to load both of these mods at the same time. I just checked today and it is still true.  He said that this could probably be fixed with certain optimizations for this mod's NEI handler. @OvermindDL1 is very knowledgeable about programming and he might be able to show you some tricks.

(BTW, the new textures are top notch)

**Comment by sendhelppls213** [comment]
HBM will fix it ASAP

**Comment by HbmMods** [comment]
Thank you for telling me, I know Greg tried doing some integration stuff before, but that must've been over a year ago now. IIRC it's the shredder recipe handler which is barely working and poorly optimized, I did plan on rewriting it so I might as well do it now.

**Comment by HbmMods** [comment]
The recipe loader has been reworked, but has yet to be tested. I made sure to use hashmaps for the recipe getters and to only iterate through items as many times as is actually necessary (i.e. once through all ore dict entries and once through every matching stack for each entry) it's still quite a bit for when you have thousands of items, but I suppose it's much, much more managable.
