### ISSUE TITLE
[Statement - Please read] For "Uncle Bob"

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#432]
Greetings Bobcat, it's me again, I have a message for you @HbmMods 

I am a Beta-Tester of the Engender mod and semi-beta input (but a tester) of Titans mod Created by Enderman_of_D00M, I have information with the quacker rounds. 

while it seems that the titans are a dead mod, it's quite the opposite, the dev has been working on it in the last year, it's just that they are very slow. I would like to confirm that in the dev beta versions that this projectile regarding the "4 Gauge Quacker rounds" do work, but will be patched over ONLY for the titan mob themself (surprisingly all mods under titans will be susceptible to this but I, knowing the community, see this as mostly intentional)

The reason this is being patched over is due to the fact of titans of the dev. You see, they are almost like Quackos, beings to god-like status, but the titans being able to be "killed" via great feats of progression by the titans mod. 

the dev has had enjoyment using them to blow up his mobs, but he did find the method and I will say clever play.

now if I'm correct, you will TRY to find another way to kill them, and the dev will do the same to patch it up. IN short, I see it as a possible "Cold-War Standoff" situation arising

so, I would like to make an offer

in exchange for making the quacker rounds an End-game expensive ammunition, I (and the dev of Titans ) will fix things that are a possible reason for the quacker rounds to existing. but before I go into that, allow me to explain some stuff.

Titans are supposed to be a challenge but balancing (if you think of making the game farther, no, as the dev puts it, your fighting fallen gods, so course it will be hard to kill-em) a beta on their discord has been released after a long wait with various fixes and weekly fixes

The dev likes to reinforce the image of the titans, and that's the reason why an "Absurd" anti-cheat mechanic was developed; however, the open-beta releases are now an option that can be disabled.

So what could we give you, the possible reason why you did this.

I have speculated, and now with proper evidence found that one of the weapons in the titans mod can kill Quackos and that these projectiles were to serve as a strike back. The ironic thing is that (other than still working on the open beta's) is that this is an unintended bug, as Quakos is supposed to survive is a victim of the mod killing him still after hit (something the dev noticed through experimentation, IK since I was watching)

The Ultima-blade is the reward given in survival by defeating Witherzilla "or as the titan mod community, and lore refer to him as "Regnator". He is the final boss of the mod and a very difficult fight that can be beaten with enough gear and patience. 

while I cannot guarantee that this bug with Quackos and the Ultima would upon being fixed will spare Quackos; I and the Dev are willing to make an agreement. If you agree to make the projectile recipe for the quacker rounds Creative Only or an expensive end-game weapon, the dev agrees that he will make sure that any of the Titans mod Mechanics and titans will not kill or even bother to attack Quackos (unless some other mod makes it happen)
I do this as a compromise to avoid a heating cold war standoff scenario and think we can agree since both of you have a close similarity, Beings of power that cannot be or in the titan's case  hard to kill

This message is for the main developer of HBMmods, The Bobcat or known as the community as "Uncle Bob"

The method that you did this with the quaker rounds was patched (I believe) on their end, but will be convinced upon agreement of terms to allow them to work again along with Quackos's guaranteed immortality (even the dev remarked how clever you were on finding a hole in his system)

Furthermore, the means of despawning unwanted titans and even dealing with them was dealt with in the beta versions that can be found on Enderman_of_D00M's Server

The changes include:
a progression system designed to make it so 2 of the vanilla bosses (and one extra boss) are required to fight the titans. This also comes with a new system in the works, titans before these requirements are met, they will be dormant and mean you no harm, even it's planned for them to be passive with the new system the dev is working hard on

Health Buffups (a new health system was implemented, allowing it to go higher than what used to be the HP limit)
New martial progression and also materials
CONFIG OPTIONS AT LONG LAST (including an option to turn off the Anti-cheat mechanic, leave it on if you want to know what fighting a fallen deity is like)
New HP modification system (all mobs HP are now raised, including modded ones, yes the Mask Man also was found to be affected by this)
A bleeding mechanic (there are means to patch you up, but also setting yourself on fire will stop the bleeding as well)
MANY optimizations
-Main Beta Feature: Major rework of the code; now allows for multiplayer servers to run titans mod
-Planned: ways to get rid of titans you don't want to deal with

And much more, for more info on the changelogs, visit the server found on the curse forge page

please respond if you agree to our proposal

quick recap: 
**You give:** either make the Quaker rounds more expensive to use or creative based (may not instant kill them, but I will make sure that they can be an effective means to kill them still)
**You receive:**
-Guaranteed safeguarding on preventing Quackos from being killed by any of the means in the Titans mod
-Titans will identify them as a passive mob (this will make titans not attack or target him)

Thank you for taking your time to read this @HbmMods and have a nice day :)

PS: it was because of this that the dev finally got round to trying the mod and learned why I and another beta-tester of his loved it, and I thank you for that.

PPS: He added integration with HBM as a result of this, making some of the mob minions do a mini-nuke detonation if HBM is present

**Comment by Shibva** [comment]
what you will not get: "Dr. Nostalga" being able to rejoin the server; he still remembers the "brony" incident

**Comment by Vaern** [comment]
> what you will not get: "Dr. Nostalga" being able to rejoin the server; he still remembers the "brony" incident

![wheeze](https://user-images.githubusercontent.com/90118520/153531444-0a96dfc4-8af2-4f13-97ad-8151e5fdccba.png)

**Comment by EndermanofD00M** [comment]
Tis but a scratch

**Comment by Shibva** [comment]
^(hes the dev of the Titans mod; if you have any question HBMmods, ask him)

**Comment by UFFR** [comment]
![image](https://user-images.githubusercontent.com/63076393/153532829-3881efcd-0dae-43ac-a301-1609993564a0.png)

**Comment by EndermanofD00M** [comment]
ya yee

**Comment by sendhelppls213** [comment]
1) the titans mod is garbage
2) quackos literally doesn't have death in it's code, meaning that it can not "die" as minecraft mobs do.
3) this "cold war" of yours will just lead to that low-quality "heehoo strong monster" mod being ridiculed even harder
4) STOP USING THE ISSUES PAGE FOR DUMB SHIT LIKE THIS
And please, relay this message to your boss: "fuck off and stop sending your "beta testers" to "negotiate" with the developer, we do not negotiate with low-quality propreitary "devs""

**Comment by Shibva** [comment]
> STOP USING THE ISSUES PAGE FOR DUMB SHIT LIKE THIS
And please, relay this message to your boss: "fuck off and stop sending your "beta testers" to "negotiate" with the developer, we do not negotiate with low-quality propreitary "devs""

Tehincaly he dint, this was my idea and he agreed to it

**Comment by sendhelppls213** [comment]
You can fuck right off too

**Comment by EndermanofD00M** [comment]
ah, some rando
waiting for actual devs and not mockers

**Comment by sendhelppls213** [comment]
A modeller and translator is all you're getting now. Crawl back to your "all right reserved" sewer and don't taint this platform with your presence.

**Comment by EndermanofD00M** [comment]
I go where I want

**Comment by EndermanofD00M** [comment]
I shall now be waiting for Bob

**Comment by sendhelppls213** [comment]
Well let me tell you something, you aren't supposed to go into the github issues page to demand things from an independent developer of an actually decent mod.

**Comment by Shibva** [comment]
well, tbh, I would have went to him if I could on discord, but I'm still affected by some strange ban glitch (I'm not on the list but the system still says I am)

**Comment by sendhelppls213** [comment]
That's why you don't get your alts banned.

**Comment by Adam29Adam29** [comment]
Aight this rather into a case of a clusterfuck. First things is, this is a issue board (as in to report bugs, glitches and crashes) and not a "demand" board. 

Second thing is, Bob wasn't pleased with mod in general sense and not only for the Quackos problem.

Another problem is there is not really any "cold war" in any sense and its just an exaggeration, Bob was neither attacking anyone of the Titans mod community by making the quackos shotgun rounds and that, if an independent dev feels something is too outrageous then why couldn't he make changes in some mods while his mod is loaded along those mods?

**Comment by DrNostalgia** [comment]
> what you will not get: "Dr. Nostalga" being able to rejoin the server; he still remembers the "brony" incident

implying i even remember what you're talking about; writing an entire thesis on why bob should nerf the ammo specifically designed to nullify your dumbass mobs is hilariously retarded. kys

**Comment by HbmMods** [comment]
And to think that shoving vegetables into a shotgun was supposed to be a one-off meme, guess that kinda backfired.

So long as the comically large duck stays in one piece I think we have ourselves a deal.

**Comment by Nos74** [comment]
disappointing.

**Comment by EndermanofD00M** [comment]
Greetings Bob
I was actually having a blast blasting the crap out of things with HBM
you also indirectly helped me learn about the existence of a way to get classfiles without actually getting class files. this'll help me with mod compatibly alot

if Quackos is what I think he is, then him being basically invincible makes sense, as he'd be a Duck God, and Gods, though not as powerful as Titans generally, are just as indestructible and hard to dislodge for lower beings. Quackos could easily make himself unkillable if he is a God, and thus I'm willing to accept that Titans will ignore him on purpose.

I hope for us btw to have more interactions and even work together, since I'm wanting to make custom lightning actually work sometime. Thank you for your time sir.

from one mod creator to another

**Comment by EndermanofD00M** [comment]
also, if you'd like, I could make Quackos even more unkillable for you

**Comment by Shibva** [comment]
yeah, he helped make J-zahar from abyssalcraft stronger, (no not engender, he actually helped Shinnow improve his boss and he loved it)

in fact, AI is a specialty, maybe if ender is up to it he can help iron out some of the bugs with the BOT (ballz O tron) AI

**Comment by godtm23** [comment]
> yeah, he helped make J-zahar from abyssalcraft stronger, (no not engender, he actually helped Shinnow improve his boss and he loved it)
> 
> in fact, AI is a specialty, maybe if ender is up to it he can help iron out some of the bugs with the BOT (ballz O tron) AI

fuck you and fuck ender you dumb sack of nigger tranny shit
