### ISSUE TITLE
Electric Boiler potential sync issue?

### ISSUE THREAD

**Issue by SoB1nary** [HbmMods/Hbm-s-Nuclear-Tech-GIT#433]
### Describe the bug

Version: 1.0.27#X4130
Description: When the Electric Boiler with 0 HE in it's buffer recieves a battery, it gets energy (the blue-green meter rises) and begins working, but the tooltip when hovering over the HE buffer shows 0 HE (or more? depends on the battery that was inserted first, au198 self-chargers show 2.35k, spark batts 9.85k). Same happens with the heat value (the thermometer fills with red, the recipe starts but the tooltip says it's still on 20 C).
![2022-02-12_16 19 22](https://user-images.githubusercontent.com/88827565/153719488-f319946e-9fed-41f4-814c-2927c2cf95c2.png)

![2022-02-12_16 20 57](https://user-images.githubusercontent.com/88827565/153719278-59034af8-644f-4e9c-8e06-af859555fdf3.png)

**Comment by HbmMods** [comment]
Tile entities that actually change the block when activated (boilers, furnaces, etc.) had this issue where after a state change, certain packets would no longer arrive until you close and re-open the GUI. I've fixed that a few times now but it keeps breaking for some reason.

**Comment by HbmMods** [comment]
Found it, apparently my bandaid fix only applied to the background rendering (including gauges) but didn't do much about the tooltips that are handled separately.
