### ISSUE TITLE
HE->RF converter doesn't seem to consume HE

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#435]
Version: 4130H1

The HE to RF converter seems to provide RF without consuming HE, at least on loads of ~30 RF and lower. I would've expected < 10 RF to result in it not consuming HE (which is relatively fine I guess), but even larger loads seem to not do anything. This in combination with #431 could probably be handled in the same version bump, and is probably why the submitter of that tried it :P

**Comment by HbmMods** [comment]
I can't replicate that behavior (mostly because I can't think of anything that would provide this little HE), but I've tested Thermal Dynamics' flux ducts extensively without coming across any weird behavior. #431 seems to be related to Mekanism's cables, what RF conductor are you using?

**Comment by thePalindrome** [comment]
I'm directly connecting it to an OC computer case and an AE2 Power Acceptor. I'm powering it off an Lithium ion battery block set to I/O mode. The battery itself is reporting a change of 0 in the instances where my power generation is running. (both in when hovering over the bar, and directly comparing the number at the top of the UI (which I presume is more accurate)

I notice that if I turn off the power switch, it takes a few moments for my ME network (with no energy storage on it at all) to shut off, which seems to imply that it is running some odd sort of state where it's not keeping up with the power network.

**Comment by HbmMods** [comment]
Does the delay also happen when you use an RF generator outright? Perhaps the AE2 converter has an internal buffer that lasts for a few more seconds before going out?

**Comment by thePalindrome** [comment]
Okay, using a creative BC engine I managed to conclude that there does seem to be a buffer (I couldn't see it directly, but the AE2 network tool showed more power was being generated than consumed, which implies the existence of a buffer. Plus there was the few seconds of time)

So that's the delayed shutoff explained, but then why do my batteries suffer no drain whatsoever?

**Comment by HbmMods** [comment]
![2022-02-13_17 28 33](https://user-images.githubusercontent.com/16674258/153762800-5d774fca-9268-4c7a-9629-70211261df36.png)

This little test setup shows a drain of 100 HE/s on the li-ion battery, it also works when the HE/RF converter and the AE2 energy acceptor are connected with Mekanism cables. Do you have any generators running right now or perhaps other batteries in I/O mode that might throw off the discharge rate reading? You could try isolating the battery and the converter from the network. Does it happen with any other RF acceptor too or is it really just the AE2 converter?

**Comment by thePalindrome** [comment]
![2022-02-13_12 06 43](https://user-images.githubusercontent.com/1844681/153766177-76af47a9-8db3-4947-8321-9e761da9b78e.png)

Here's a test that I did, showing the bugged behavior... maybe it's the power switch somehow interfering with things?

EDIT: I slapped on an OC capacitor, and while it charged the battery didn't lose any HE at all. so it's not just the AE2 converter

**Comment by HbmMods** [comment]
![image](https://user-images.githubusercontent.com/16674258/153771920-b0c9b050-7895-442a-ae2d-3180f6c57fd2.png)

After dicking around for about half an hour I finally found a way to reliably replicate this issue, simply having a fluix cable next to the converter causes it to spit out energy for free. I'm not sure why it does this since fluix cables don't seem to carry RF. It also works with mekanism universal cables, so it's not the fluix cables being bugged (they're just a bit weird) nor the HE cable switch, but the converter's output.

**Comment by HbmMods** [comment]
Yup, it was definitely converter. I redid some of the math that keeps track of the energy being transmitted during one tick, it seems like it's properly deducting everything it should. I'm leaving this issue open for now, we can close it later after testing the upcoming version.

**Comment by thePalindrome** [comment]
Alright, it's drawing power, but looks to be drawing double what it should.

My ME network is drawing 11.3 RF/t, which should turn into 22.6 HE/s but my battery is reporting a loss of 42-44 HE/s

**Comment by SoB1nary** [comment]
as far as i am aware, the he/rf rate is 1/4, so it works as intended

**Comment by thePalindrome** [comment]
All I've seen says 1 HE is 10 RF, I don't think that's changed, either

**Comment by SoB1nary** [comment]
![Screenshot_20220214_082945](https://user-images.githubusercontent.com/88827565/153790010-d8bdf436-b5ee-4b59-a588-41a823dc6a65.jpg)
That's what the wiki says, and from my expirience, it was 1/4 with the buffered converter as well.

**Comment by thePalindrome** [comment]
Huh, alright, the old buffer converter claimed 1 HE to 10 RF iirc, which would be where I got confused.
Taking that into account, the numbers now seem to come out correctly (and looking at the current code seems to imply 1 HE to 4 RF)

So it seems like it works! (I'll leave the actual closing to HBM, just in case there's something else they want to do to wrap this up (like maybe an updated in-game conversion ratio :P )

**Comment by HbmMods** [comment]
The ratios might change in the future since HE generators are stupid powerful compared to most mods (or at least a config) but yes, the 1:4 ratio is the correct one.
