### ISSUE TITLE
Fluid ID Recycling returns stacks of plates

### ISSUE THREAD

**Issue by Vaern** [HbmMods/Hbm-s-Nuclear-Tech-GIT#439]
Recycling fluid IDs, judging from what's going on in horizons, returns stacks upon stacks of plates and crashes the server. Better to hotfix now rather than later.

**Comment by HbmMods** [comment]
I am uploading a hotfix as fast as possible

![image](https://user-images.githubusercontent.com/16674258/153778144-74e3664b-a175-46a5-a7d1-35fdd02d70bf.png)

**Comment by Vaern** [comment]
liquified trolling
