### ISSUE TITLE
I have a few questions...

### ISSUE THREAD

**Issue by Joey-Destroyah** [HbmMods/Hbm-s-Nuclear-Tech-GIT#44]
The soyuz (R7) doesnt launch after 10 seconds and there isnt even the spacecraft yet.

Are you planning to add the capability to go to other planets?
Because that looks like where you are going with the newly added R7/Soyuz rocket.
Ok sorry for having lots of questions.

**Comment by Drillgon200** [comment]
That's cataclysm mode, where burning satellites drop out of the sky and explode whenever a mob dies.

**Comment by Joey-Destroyah** [comment]
oh. didnt know why these satelites dropped out. Looks like im turning off cataclysm mode

**Comment by ghost** [comment]
I think that after finishing Soyuz , Gerald The Construction Android finally gonna have some purpose. (To make a space station or something)

**Comment by sendhelppls213** [comment]
Gerald willhave a purpose, but MUCH COOLER. And there will be no space exploration. (2% chance)

**Comment by Doctor17-git** [comment]
for example building _a super weapon on the moon_

**Comment by sendhelppls213** [comment]
;)

**Comment by Nos74** [comment]
to be honest, it's more akin to building a super weapon _with_ the moon

**Comment by Joey-Destroyah** [comment]
@sendhelppls213 Then why does it have a Soyuz spacecraft icon on the launch GUI?

**Comment by Doctor17-git** [comment]
this is for cargo transportation by coordinates

**Comment by HbmMods** [comment]
@joey-lg if you're referring to the slot below the satellite one, the spacecraft is only for certain items that do not have means of propulsion (unlike all current satellites), which as of now only includes Gerald.

**Comment by Joey-Destroyah** [comment]
Oh. Then why is there a Launch Escape System on top of the fairing?

**Comment by HbmMods** [comment]
Because the Soyuz-FG also has one. Besides, Gerald has feelings too, you know.

**Comment by Joey-Destroyah** [comment]
Then why didnt you use the Progress spacecraft?

**Comment by HbmMods** [comment]
Considering that they look the same, I might just rename it to something generic.

**Comment by Joey-Destroyah** [comment]
Its version of the r7 looks like this:
![images](https://user-images.githubusercontent.com/62820134/80409229-7a817d80-8896-11ea-9a6a-aa0bfbc7f7e8.jpg)

**Comment by HbmMods** [comment]
Oh I thought you meant the oribtal capsule. Yeah no, I'm not going to remodel it. Besides, I want it to be a u t h e n t i c.

**Comment by Joey-Destroyah** [comment]
Maybe after you get gerald to build a space station, maybe you can make so that people can visit.

**Comment by Joey-Destroyah** [comment]
I get why you dont want a remodel. I guess it took weeks of hard work to get the rocket working, yet alone launching.

**Comment by HbmMods** [comment]
Those weeks were mostly spent doing something completely different, though with all the work that went into the model, texture and the launch pad too, it's probably close to a full day.

**Comment by Joey-Destroyah** [comment]
oh. I thought it was very time consuming.

**Comment by Joey-Destroyah** [comment]
just wondering, how long will it take to get the R7 launch system working?

**Comment by HbmMods** [comment]
It's already in its final stages, only a few key things are pending:

- the launcher being a proper multiblock
- the rocket actually deploying the satellite
- the cargo pod entity and block

In addition to that, I'll most likely rework the current satellite system (which is poorly coded and barely functional) and introduce a few extra satellite functions (like teleportation and of course, Gerald)

**Comment by Joey-Destroyah** [comment]
what do you mean by "teleportation"?

**Comment by HbmMods** [comment]
As of now i'm thinking about two kinds, warping from place A to B and going into a new dimension entirely.

**Comment by Joey-Destroyah** [comment]
So you are going to have crew on there?

**Comment by HbmMods** [comment]
Where?

**Comment by Joey-Destroyah** [comment]
The soyuz spacecraft, or other crew modules.

**Comment by HbmMods** [comment]
I don't plan on adding actually rideable rockets like galacticraft has them, and all missions are either for cargo, satellites or placing stuff on the lunar surface.

**Comment by Joey-Destroyah** [comment]
If you are placing stuff on the lunar surface, then how is it useful?

**Comment by HbmMods** [comment]
Building super weapons on the moon, made from moon rock, or perhaps a teleportation relay? Stuff like that.

**Comment by Joey-Destroyah** [comment]
Which means the orbital death ray would be obsolete?

**Comment by HbmMods** [comment]
It would fill a drastically different role, that's like comparing a gun to a hydrogen bomb.

**Comment by Joey-Destroyah** [comment]
You mean more powerful then the Tsar Bomb?

**Comment by HbmMods** [comment]
Something like that, but with a different algorithm so the lag becomes bearable

**Comment by Joey-Destroyah** [comment]
unless tile drops are turned off, or you have a good PC, it might lead to a game crash, or in extremely rare cases, could get so laggy that it BSODs. I have a good PC but others might not be so lucky.

**Comment by Joey-Destroyah** [comment]
Do you know when the release date is? Or is it a secret?

**Comment by sendhelppls213** [comment]
the release date is a secret even to HbmMods

**Comment by Joey-Destroyah** [comment]
Thats What i thought.

**Comment by sendhelppls213** [comment]
can you, please, end the suffering of this issue?

**Comment by Joey-Destroyah** [comment]
ok

**Comment by Nos74** [comment]
how 2 lanch soyus plsv help??????
