### ISSUE TITLE
Burnt Bark

### ISSUE THREAD

**Issue by datboiiskool** [HbmMods/Hbm-s-Nuclear-Tech-GIT#443]
The andrioid requires a burnt bark. How to get it?

**Comment by sendhelppls213** [comment]
Can you stop making useless issues? These are for bug reports.

**Comment by HbmMods** [comment]
It's a rare drop from charred logs with a drop chance of about 0.1%.

**Comment by datboiiskool** [comment]
> Can you stop making useless issues? These are for bug reports.

They can be also questions.
