### ISSUE TITLE
[Enhancement] Secondary Hand drill use, drill into specific Blocsk

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#445]
### Describe the enhancment

The only use the drill has is to drill into graphite to make the chicago pile, but when I was consturting a test RBMK, I was thinking if their was something I could do to make the concrete shield wall flush with the cable (and now I just remember the cable block) but then it hit me; Why not give the hand drill a secondary use

By using the hand drill on blocks that can shield radiation in an enclosed space, (minus the reinforced glass), you can put any fuel pipe (minus the one that's not registered as a valid ID) into that hole, the block will provide effective protection and flush with the wall) Just like with the pile; the inserted pipes can be removed via a screwdriver. It could also remove by breaking it, but it will also strip it of its fluid ID

Some other side ideas: in the case of  reactor detonation, depending on how close or strong the block is, the block will begin to break down naturally, especially if its blasted constantly, CMB bricks will be the one of them that can be immune to wearing down. furthermore cracked variants of them may not be as RAD resistant, meaning some radiation can passively leak though them (let this be a lesson for those that think using cracked concrete bricks as a means of cutting corners)

One more idea: Universal Super M??? Automatic R??? Tuner (S.M.A.R.T) Fluid Identifier: this will take the mechanic thats had be used for 1.12.2 (due to the lack of Fluid Oredic or something that made what is used here not possible) where fluids would set the specific filter automatically. Just place the S.M.A.R.T Fluid ID into the top slot and then put any fluid (whether its fluid tank or pumping in from a pipe, it will set it as that fluid  (it will then move to the lower used slot) this can be useful for quick setup. While this might be too complex and if its the case that it takes more work on the fluid system than its worth, then it could be used as a index instead (R-click in hand to open a GUI and set its

**Comment by SoB1nary** [comment]
![IMG_20220210_174023](https://user-images.githubusercontent.com/88827565/153890158-6b45411f-dfb9-4f19-a497-4edc4f620f7a.jpg)

**Comment by sendhelppls213** [comment]
![download (14)](https://user-images.githubusercontent.com/57670225/153890488-0435fc3f-d484-40a9-9331-1163ac229f9c.jpeg)

**Comment by ncr-t** [comment]
Please refrain from using the "issue" page as a place to suggest, as it is not its intended purpose.

**Comment by HbmMods** [comment]
> By using the hand drill on blocks that can shield radiation in an enclosed space

Radiation is chunk-based, so that's not going to work.

> Some other side ideas: in the case of reactor detonation, depending on how close or strong the block is, the block will begin to break down naturally, especially if its blasted constantly

I don't think concrete or steel are affected by radiation to such an extent, nor is that a feature I think would make that big of an impact regardless.

> Just place the S.M.A.R.T Fluid ID into the top slot and then put any fluid (whether its fluid tank or pumping in from a pipe, it will set it as that fluid (it will then move to the lower used slot) this can be useful for quick setup.

That just sounds like a more complicated version of xR's system which doesn't even have fluid IDs and instead just sets the type if a bucket is inserted with no fluid being currently buffered. That's something I want to avoid because it's an "invisible" feature which obviously can't work in machines that only have inputs for some tanks (like refineries) where dynamically setting the type means getting the machine clogged with a fluid type that can neither be processed nor removed. And making it clear where this works and where it doesn't would require me to add either some sort of label or tooltip to every single tank of every machine.

**Comment by Shibva** [comment]
> Radiation is chunk-based, so that's not going to work.

oh, I thought this was going to be with that thing that drill did that's going to make radiation more containable in an enclosed space. sorry I was thinking on that part, Hope that this idea of radiation is still planned (with you using it as a reaslic thingy; idk since I'm not aware of everything atm)

**Comment by Drillgon200** [comment]
The lack of fluid ids for machines in 1.12 has nothing to do with the limitations of fluid oredict or whatever you're talking about. I simply thought it stupid to have to set a fluid id for every tank with a separate item when the fluid input can be determined from the fluid you put into the tank. 1.12 handles the machine clogging thing by limiting the fluids the machine can accept to things it can process. I ran into some issues with machines that output possible inputs, like the steam turbines, so they still use fluid ids (ideally this would be solved by side configs, but that's considerably more effort to implement).
