### ISSUE TITLE
[enhancment]Opencomputer hooks for tanks

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#453]
### Describe the idea

Becasue of the way the fluid system is set up, its impossible to have other mods to read how full a tank is from a remote system (this might not be the case for things like Intigrated Dynamics, IF it did exist in the 1.7.10 version) so why not add some way for OpenComputers to read this data. This would be useful to create programs that can monitor the fluid "fullness" of a tank and how much their is. OpenComputers has a tank upgrade that allows for reading the fluid levels, HOWEVER, this is only for the common fluid registry that HBM's fluid system does not use. Having a way to read this would be nice, I theorize that mods that can read NBT data from a block (like what Integrated Dynamics does) would be able to get this data and make it useable. This could be useful in a variety of ways such as creating programs to monitor reactor fluid levels easily (and maybe add a way to automatically shut it down if it runs low on whats needed to keep a reactor stable)

ik this is not the ideal place for recommendations and ideas, but I don't have access to the place where these can go, (still cant use discord for strange reasons)

**Comment by HbmMods** [comment]
I have no idea how the opencomputers API works and neither the time nor motivation to figure out both the API as well as the mod itself.

**Comment by Shibva** [comment]
@HbmMods yeah, that makes sence; however, even though it will never use the forge fluid system, could their be a way to implement something that could translate a part of the data into a commonly used fluid value (not saying that it will use it, but make the value be detectable for reading like with mods like WAILA, I believe that if this could be done, it would provide a means for the reader to take "false" forge fluid data that could be read accordingly
