### ISSUE TITLE
[New WoMD Idea] Co-ode Blu, a "Special" Nuke

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#454]
### Describe the idea

Project Name: Co-Ode BLu
Nickname: Cody 
unofficial name: "Dirty Dan"

Weapon type: Modified Thermonuclear Bomb
Type: Dirty Bomb

Desc: Cody is the (proposed name by me) name of a modified thermonuclear warhead. The explosive in its full (unofficial name) a Themoculular Bomb with a Pluto-Neptunium Core, modified with an outermost shell made of Tungsten Carbide neutron reflectors with an interior shell surrounding it with a 2mm thick sphere made of a blend of 1 part Schrabidium (for magnetization purposes), 6 parts Starmetal Dust and approx 32 parts of Cobalt (Cobalt-59 to be exact) and a bombshell size as to be determined. 

if it inst obvious at this point, this is a Cobalt Bomb

Destruction: The total area of destruction would be about 75% of a Fat man (theoretically). While this bomb would be expensive and a "waste" for being used as a fat man, its main purpose is to act as a massive "Area Contaminator" via the neutron reflectors within the explosive's outmost reaction shell to bombard the inner shell of Co-59 into Co-60; a highly radioactive substance with a long half-life. While it was found later on that Cobalt-59 (Co-59) is hard to transform into the nasty Co-60, by applying a touch of Schrabidium into the mix and having a Neutron-Rich core and the outermost shell of the explosive lens being coated in tungsten carbide neutron reflectors, It would result in the easy formation of Cobalt-60. While the explosive is not as great as a fat man, the main benefit of this explosive is its large radius of contamination along with its long half-life. When detonated, anything within the extremely large radius (300 blocks or more) will undergo radioactive contamination of Cobalt-60 particles. along with an extremely long-lasting fallout ("Fallout snow").

Co-60 contamination (optional implementation) By adding a small amount of Schrabidium into the Cobalt 59 compound mixture, the Cobalt-60 particles would become bombarded with free electrons and the starmetal's static generation properties, the particles will have an imbalance of charges, making them perfect for clinging on to things that could possess a static charge; as a result, this type of contamination is impossible to avoid getting in such scenarios. While wearing medium-grade hazmat protection with a particle filter will suffice, the armor itself (and anything else that's an armor except for the most advanced of power armors and possible modifications) will become contaminated with Cobalt-60. You will start to take the effects of this contamination debuff when the effect is greater than 2 (Cobalt Contamination II) and will only get Cobalt contamination I as long as you are wearing the suit. IF at any point you remove ANY part of it while still having this effect (or if the armor itself is given a "Co-60 tag" you will get the effect applied to you again at a strength of II; meaning that even if you put the thing back on you will still take in RADs (this will bypass any radiation resistance due to tot he fact that it's now it's on your body or in between you and the radioactive protection. The only way that this effect can be cleared off is by using a strong form of Rad-away (to clear off the effect) or being exposed to the decontaminator. In the case of contaminated armor, the only way to clean it is to have it on and stand in the player decontaminator.

Food contamination: any food that is eaten while contaminated will give you a 5 min effect of Normal Contamination and a small chance of Co-60 contamination (100% chance of Co-60 contamination debuff when on 526 mode) EVEN if your wearing protective gear.

Fallout: the area within the blast's overall contamination radius will undergo a fallout effect that will last drastically longer than normal. Generally speaking in real life, the time for Co-60 to emit radiation passive enough to be classified as background radiation would be 130 some years, so ill let you decide how long it will last, just as long at a minimum, the fallout "snow" will last for about 10x longer.

Note: While this is technically a dirty bomb, it CAN NOT be used to produce Schrabidium from uranium ore

**Comment by Shibva** [comment]
Addonal notes: Rad-X can still be used to decrease the number of rads you take in

**Comment by Vaern** [comment]
This is the issues page, not suggestions. Please take this elsewhere.

**Comment by Shibva** [comment]
im aware that this is not the proper place, is their anywhere else that I can go other than discord to suggest stuff?

**Comment by HbmMods** [comment]
Not even the discord server has a suggestions channel anymore, so no.
