### ISSUE TITLE
[enhancment] HBM keybinds break other keybinds binded to keys

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#456]
### Describe the bug

in cases where vic modden warfare has a reload key and its the same as the reload for HBM, only the HBM key will be output while the other is ignored, this is also the case with other keybinds that may conflict with HBM, only the HBM keys does not account for any other input that may happen

while this sounds redundant, I've seen mods in this version that allow for the same key to be pressed and both conflicts still work when pressed

**Comment by Vaern** [comment]
Rebind one of the keys to something else. This is not an issue with NTM.

**Comment by HbmMods** [comment]
Minecraft by default can only process one keybind bound to a given key at a time as key codes are assigned one binding each, meaning subsequent binds will be overwritten. There might be hacky workarounds (for example NTM's old hardcoded binds) but by using vanilla's `KeyBinding` class that allows customization though the options menu, this behavior will always happen. In fact, it was VMW overriding NTM's reload key bind when I tested VMW in my workspace just a week ago.
