### ISSUE TITLE
Null issue , Ignore

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#457]
### Describe the Enhancement

It can be annoying when you want your vault-tec door to open by the use of restone but not be protected by others opening it, and it loosing Redstone functionality when a key is bound to it. So as an old saying goes "You can't have your cake and eat it too". But why can we? I mean it only makes sense so this enchantment recommends an idea so you can have a locked door and still be useable by Redstone. Introducing the "Garage Door Opener" or the Wireless Lock Opener. It's a simple block that allows you to use Redstone to interact with blocks that require a key to open.

Here's how it works: when you right-click the block, a GUI opens with either a 1 x 1 or 3x3 grid with key outlines in them. For you to unlock any locked door without breaking the locked mechanic, the block must be within 3-6 blocks maximum from the door that you want to unlock and a key of the correct "pins" must be placed within the block [Counterfet keys are something I'm not sure about, you can decide if you want them to work]. The Red Key cannot be used in this case (to avoid breaking the purpose of personal base locks).

Additional properties: will emit a Redstone signal if the door is opened (Only works if you have a Comparator faced to the block.

Uses of Enhancement: This allows you to be able to have your door locked while still being able to use Redstone to also open it (as long as the right key for it is used in the sed opener block). This also opens cross-integration with other mods that use Redstone. In addition, with the additional properties, this could allow for a door opening detection system; creating more possibilities. 

For example, creating  a Redstone system that acts as a timer when it detects the door opening and closes it after a programed time via the Redstone signals (auto-closing doors!)

possible (unsure) ideas: if a repeater goes into this block (max strength) the block will cause the door to disable all signal functionality (great for when you want your blast doors to STAY FUCKIN CLOSED like a base/sector lockdown)

It may not seem much to add this now, but it is great for when more lockable doors are added, like with the transition seal

**Comment by Vaern** [comment]
Please stop. This place is for issues, not suggestions. Your suggestions will never even be considered if you continue to spam this page with them.

**Comment by Shibva** [comment]
ok, then where do I go to make them? I was told the discord server doesn't do them anymore,

**Comment by FatSassin** [comment]
So many people were suggesting bad ideas it's illegal now
Or so i think

**Comment by Shibva** [comment]
yeah, that I can understand, but you have to admit that this idea is not great or terrible, I see the practicality in this

Originally the idea was to just add Redstone use to doors, but then I thought; "then they would just use Redstone to bypass the doors without the red key." so I thought of a solution that happened to require a new block to be added to make it work

**Comment by Shibva** [comment]
if you want to go father on it, it could need power to opperate

**Comment by TheForge129** [comment]
do it yourself
here's an IDE <http://eclipse.org>
there are instructions on how set up the eclipse workspace on the github
page

**Comment by Vaern** [comment]
> ok, then where do I go to make them? I was told the discord server doesn't do them anymore,

There's nowhere to make suggestions because the server and GitHub has been inundated with them. Feel free to implement it yourself as the person above said, though
