### ISSUE TITLE
Coated fluid pipes not working

### ISSUE THREAD

**Issue by tueszay** [HbmMods/Hbm-s-Nuclear-Tech-GIT#458]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.
Coated fluid pipes do not transfer fluids
Using the most recent version

**Comment by HbmMods** [comment]
Confirmed and fixed in-dev, expect a fix with the upcoming version.

**Comment by HbmMods** [comment]
Fixed in X4158
