### ISSUE TITLE
power net cause a lot of lag in server

### ISSUE THREAD

**Issue by sdddddf80** [HbmMods/Hbm-s-Nuclear-Tech-GIT#459]
In my friend's forge server, if a ZIRNOX or a RBKM explode, than the nearby power net will cause a lot of lag until you mine the net.
Here is the report:https://spark.lucko.me/4Wj2048ppZ

**Comment by HbmMods** [comment]
The majority of the lag seems to be coming from battery blocks, how many do you have in your network? Also what version of the mod are you running? The part that seems to eat the most performance shouldn't even be present in the latest version anymore.

**Comment by mcmso** [comment]
> The majority of the lag seems to be coming from battery blocks, how many do you have in your network? Also what version of the mod are you running? The part that seems to eat the most performance shouldn't even be present in the latest version anymore.


Hello, my problem appears in HBM-NTM-.1.0.27_x4130H1

Does the latest version fix this problem

**Comment by TheForge129** [comment]
HBM just said it should

**Comment by HbmMods** [comment]
> Does the latest version fix this problem

I assume it would, since batteries only run a single `getBlock` operation and then buffer the result instead of constantly checking blocks every time the power net needs to know the battery's charge capacity (which given the assumed number of batteries is probably a lot).

**Comment by mcmso** [comment]
> > Does the latest version fix this problem
> 
> I assume it would, since batteries only run a single `getBlock` operation and then buffer the result instead of constantly checking blocks every time the power net needs to know the battery's charge capacity (which given the assumed number of batteries is probably a lot).

I'll give it a try

thanks

**Comment by mcmso** [comment]
> > Does the latest version fix this problem
> 
> I assume it would, since batteries only run a single `getBlock` operation and then buffer the result instead of constantly checking blocks every time the power net needs to know the battery's charge capacity (which given the assumed number of batteries is probably a lot).

Hello, I used the X4152 version and this still happens
https://spark.lucko.me/1yyvumjQ3d

**Comment by HbmMods** [comment]
Well that's good, the batteries are no longer causing excessive lag due to checking and re-checking their capacity. The issue right now seems to be your particle collider, or to be precise the power connectors. At least half the total CPU time goes into block updates caused by the connectors charging. I've just fixed it on my end, I'll report back as soon as the new version is out.

**Comment by mcmso** [comment]
> 很好，电池不再由于检查和重新检查其容量而导致过度滞后。现在的问题似乎是你的粒子对撞机，或者准确地说是电源连接器。至少有一半的总 CPU 时间用于连接器充电引起的块更新。我刚刚修复了它，我会在新版本发布后立即报告。

I cut the wire to the particle accelerator, and the problem was solved
But a new problem appears to be emerging
Please look at this  https://spark.lucko.me/LktIttxPEl

**Comment by mcmso** [comment]
> Well that's good, the batteries are no longer causing excessive lag due to checking and re-checking their capacity. The issue right now seems to be your particle collider, or to be precise the power connectors. At least half the total CPU time goes into block updates caused by the connectors charging. I've just fixed it on my end, I'll report back as soon as the new version is out.
I cut the wire to the particle accelerator, and the problem was solved
But a new problem appears to be emerging
Please look at this https://spark.lucko.me/LktIttxPEl
