### ISSUE TITLE
Long-range missile launch

### ISSUE THREAD

**Issue by CastomStrange** [HbmMods/Hbm-s-Nuclear-Tech-GIT#460]
When a rocket is launched at a distance of more than 3 thousand blocks, it simply does not load and hangs somewhere in space. You have to fly along the flight path and only then the rocket will hit the target

**Comment by HbmMods** [comment]
Are you playing on a server? What version of the mod are you using?

**Comment by CastomStrange** [comment]
I play in my solitary world. The latest version of the mod

**Comment by CastomStrange** [comment]
Tracking by radar, the rocket simply disappears on the way. When I arrive at the place where the rocket disappeared, it reappears and flies on

**Comment by HbmMods** [comment]
Do you have any other mods? Things for performance improvement or ones that alter chunk loading maybe?

**Comment by CastomStrange** [comment]
There are no such mods. Only after the problem occurred, I installed the mod on the block that loads the chunks. Optifine is also available

**Comment by HbmMods** [comment]
Could you try and remove Optifine? I'm not 100% sure but I've heard it changes some things regarding chunk loading which might conflict with the missile's chunk loader.

**Comment by CastomStrange** [comment]
Yes, I'll try it well. Thanks
I will write the result soon

**Comment by CastomStrange** [comment]
It worked, thanks. I assumed it was optifine, but for some reason I didn't attach any importance to it. The rocket flew calmly for 4000 blocks
