### ISSUE TITLE
Asphalt makes mobs fast but only makes me hungry

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#462]
Currently in 1.0.27 beta 4144 (which is not the latest, but the latest doesn't mention this), I paved some asphalt roadways between our buildings. While us players don't get speed boosts, our hunger drain is massively increased as if we were moving at supersonic speed!

On one of the nights, we managed to catch a zombie as it wandered onto the road, proceeding to ultra instinct his way to me nearly instantly!

Figured I should note it here that this is the exact behavior so somebody can fix it

**Comment by HbmMods** [comment]
The speed boost is very primitive, simply multiplying motion every "step". Do you have any other mods that somehow change the way the game handles player movement? Asphalt does work on players too in the small modpack we use for testing right now, so I'd assume it has to be a mod conflict.

**Comment by thePalindrome** [comment]
```
AppleCore-mc1.7.10-3.1.1.jar
appliedenergistics2-rv3-beta-6.jar
BetterBoat-1.7.10-1.1.0.jar
Bookshelf-1.7.10-1.0.4.187.jar
buildcraft-7.1.23.jar
CodeChickenCore-1.7.10-1.0.7.48-universal.jar
Controlling-1.7.10-1.0.0.jar
craftingtweaks-mc1.7.10-1.0.88.jar
DynamicSurroundings-1.7.10-1.0.6.4.jar
FastLeafDecay-1.7.10-1.4.jar
GlibysVC-1.7.10-0.6.2a.jar
HBM-NTM-.1.0.27_X4144.jar
LunatriusCore-1.7.10-1.1.2.21-universal.jar
malisiscore-1.7.10-0.14.3.jar
malisisdoors-1.7.10-1.13.2.jar
mod_voxelMap_1.7.0b_for_1.7.10.litemod
Morpheus-1.7.10-1.6.21.jar
NotEnoughItems-1.7.10-2.1.7-GTNH-universal.jar
OpenComputers-MC1.7.10-1.7.5.1290-universal.jar
OpenModsLib-1.7.10-0.10.1.jar
OpenPeripheralAddons-1.7.10-0.6.jar
OpenPeripheralCore-1.7.10-1.4.jar
OpenPeripheralIntegration-1.7.10-0.6.jar
Schematica-1.7.10-1.7.6.131-universal.jar
Thistle-1.7.10-1.1.0.jar
VoxelMods
Waila-1.5.10_1.7.10.jar
Wawla-1.0.5.120.jar
```

Not really seeing anything in this list that should cause a conflict. Even my friend wearing non-power armor (and as such has no buffs) doesn't get the bonus speed but has increased hunger.

If you have any suggestions on a debug thing I can use to help track down this problem, lemme know

**Comment by thePalindrome** [comment]
Giving a little bump to report that it persists on 4152, so that's not a factor (I wouldn't have expected it to matter, but now we know)

**Comment by HbmMods** [comment]
Instead of trying to fix an incompatibility that is impossible to track down, I threw out the old code (because being launched every step is stupid anyway) and instead rewrote the asphalt class. I believe that chisel's concrete uses a similar method, and that should be compatible with pretty much everything.

**Comment by thePalindrome** [comment]
Yeah, fair enough!

The only other one I could think to mention would be gregtech's concrete, which behaves like soul sand (including having a slightly lower hitbox)

**Comment by thePalindrome** [comment]
Confirmed fixed in the latest, thanks for your effort!
