### ISSUE TITLE
[tooltip issue] Fuel rod tooltips for Nuker furnace out-of-date

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#463]
### Describe the bug

im not sure if this is a general issue or its because I'm in 528 mode, but either way the tooltips for the acceptable nuclear fuel that can be used in a nuclear furnace (non RTG) seem to be very inaccurate, for example, I put in a Plu-239 dual rod that said it would last for 500 operations in a nuke furnace but only gave me 100

is this a general issue with the mod having outdated stuff or is it changed for 528 mode?

**Comment by thePalindrome** [comment]
I believe that's just outdated information, since my non-528 save seems to have 80 uses instead of 400 (which would imply that hbm dropped the operations by a factor of 5)

**Comment by HbmMods** [comment]
The number used to be automatically generated out of the number of uses in the breeding reactor. Thee multiplicator was apparently lost when the breeding reactor was updated but the display still assumed the old values. Should be fixed with X4158.
