### ISSUE TITLE
Chemical plants don't seem to output fluid post-rework

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#464]
running 4152, I dutifully broke all the chemical plants before updating then replaced them, but my hydrogen peroxide line no longer wants to output to my ore acidizer. They are connected properly, and I even broke and replaced one of the pipes just in case that was a factor (re-prototyping it ofc). Not sure if this is some extra feature you added (haven't tested any of my other chemical plants to see if they work, and H2O2's corrosive nature is preventing it from being used with fluid ducts), or if it's some odd lingering bug, but figured I'd report it.

**Comment by HbmMods** [comment]
That has already been fixed and will be released soon. The outputs do work, but the positions are offset by one block in the X and Z coordinates (in what direction depends on the chemplant's rotation), you can sort of work around this by placing a few extra pipes around the visual connection in the hopes of hitting the right spot.

**Comment by HbmMods** [comment]
Should be fixed in X4158, at least the positioning. I haven't tested the fluid IO implementation itself that much, so I'll leave the issue open for now.

**Comment by thePalindrome** [comment]
Updated to the new version, and at least my hydrogen peroxide line has immediately begin operating as intended, many thanks!
