### ISSUE TITLE
Shift clicking a stack of nuclear waste in a disposal drum voids all but one

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#466]
Version 4152

Shift clicking a stack of, say, 4 long lived U235 waste results in it placing down one in the disposal drum while voiding the rest. Many other machines have problems with the shift-click handler, so going through and reworking all of them to behave properly (I see code to restrict putting non-battery (and certain swords,hint hint) items in the battery slot, but even shift-click puts them there all the time.

**Comment by HbmMods** [comment]
I *finally* nailed down the cause of why I could never manage to replicate this issue, apparently it has something to do with a change made for forge version 1614 (i.e. the latest one) while the NTM workspace until now has always used 1558.

**Comment by thePalindrome** [comment]
Oh wow, what a bizzare forge bug to run into!

Well, glad we can finally get this one worked out now that you can replicate it in a devenv

**Comment by thePalindrome** [comment]
A weird thing I'm noticing: You can sometimes put in multiple items into one slot, I managed to put some (not decayed) long lived U235 waste in a stack with another of itself, forming a stack of two. I wonder if the slot guarding code is just doing something that's not being expected by forge?

**Comment by HbmMods** [comment]
Shift clicking for the disposal and spent fuel drums should be fixed now (turns out it wasn't even the forge version, instead I had COFH core installed on one machine which seems to fix this issue with ASM). I'm not exactly sure what's up with the other issue, clicking around in slots like a madman didn't really achieve anything. Perhaps you hit your scroll wheel which acts similar to shift-click?

**Comment by thePalindrome** [comment]
Fairly certain I hadn't, but I also don't have cofh core present either. Either way, I'll test with the next version and report if I can replicate it

**Comment by thePalindrome** [comment]
Tested it, behavior now correctly splits it amongst multiple slots. I'll close this for now, with a note that I didn't test shift clicking more items than there are available slots in the thing, but that's a slightly less common testcase
