### ISSUE TITLE
[Ehnancment/ quesion] Galaticraft, isnt their oil support for HBM's oil?

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#469]
### Describe the bug

ive seen that some things in galaticraft have been implemented, but isn't their something for using HBMs crude oil for galacticraft crude oil?

**Comment by Vaern** [comment]
NTM does not use forge fluids, so no. This is not a bug.

**Comment by Shibva** [comment]
ah, I thought he added compat for using HBM's crude oil as a way to eliminate the need for other oils

**Comment by Vaern** [comment]
No, he did not.

**Comment by Shibva** [comment]
ah, well it would be nice if he did add some one time exception to allow for heated crude oil could be converted into Gc Crude oil or something, I mean he did make it so the shreaders work with some GC blocks, so why not also make some of its resources possible to make Rocket fuel or something? in the meantime Im working on something that can work as a crude method

**Comment by Vaern** [comment]
Literally just use Galacticraft oil. This fitting together of two independent systems is only going to be wasted effort on the part of bob.

**Comment by HbmMods** [comment]
Shredders work because they generate almost all recipes out of the ore dictionary. As for converting NTM oil into GC fuel, a simple crafting recipe from turning canisters of NTM oil into GC fluid would be easy, but not exactly helpful since you'd have to dick around with unstackable fluid containers by hand. Fluid converters would be an option, but I still have no clue how forge fluids actually work.

**Comment by Shibva** [comment]
🤔 maybe someone on the group might know, wish I did

**Comment by Shibva** [comment]
Ya know, while it cant be done now, the minimal thing that could be done is to have the tank system fill up buckets and oil tanks from GC with GC oil; I mean its only like 1,000 mB

**Comment by Vaern** [comment]
Again, they do not use the same system. Putting compatibility between them for only one specific use case is just wasting time and effort.

**Comment by Shibva** [comment]
... you do realize I mean just to have the item put into the input slot and then replace it with a full version of it put in the output slot and then have it subtract

if (Galaticraft is present in the pack) {
 if (tank has crude oil in it AND if Fluid.amount <= 1000) [
   if (item in extract input slot 1 == bucket ) 
     [delete item in extract input slot,
      subtract 1000 from fluid.amount in block NBT,
      add output of Galaticraft crude oil bucket
      ]
   if (item in extract input slot 1 == Galaticraft:Fuel,drum,thing)
      [delete item in extract input slot,
      subtract 1000 from fluid.amount in block NBT,
      add output of Galaticraft item with 1000/1001 durability (full in this case)
      ]
      ]
      }

What I'm saying is that if the fluids maches crude oil and GC is present, then putting one of the containers in while still having over or equal to 1000 in the blocks NBT data that it would replace the item with a full version of it in the output slot and modify its data to be 1000 units less in the tank
