### ISSUE TITLE
Deco LIght Emitter Size Is Unlimited

### ISSUE THREAD

**Issue by datboiiskool** [HbmMods/Hbm-s-Nuclear-Tech-GIT#471]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.
Version: 1.7.10 1.0.27_X4158
I spammed right click on that block with a screwdriver and this happened.
![2022-02-28_16 46 59](https://user-images.githubusercontent.com/79916314/155952474-03d4a563-0dba-4269-b0ab-758c75051866.png)
![2022-02-28_16 47 20](https://user-images.githubusercontent.com/79916314/155952502-07aa0cb9-c8e8-4f2a-9558-84a129eedbf5.png)

**Comment by HbmMods** [comment]
So what exactly is the issue?

**Comment by datboiiskool** [comment]
> So what exactly is the issue?

I spammed right click on it with a screwdriver and this happened. If your still confused, try it.

**Comment by HbmMods** [comment]
Yes, a screwdriver makes the beam larger. If you click the emitter a lot, naturally the beam is going to be very large.

**Comment by thePalindrome** [comment]
Your bug report seems to be "there's no maximum beam size enforced by the block"

imo, as long as it doesn't leak memory, lag horrifically, or crash, it's not a bug, that's just a feature :P
