### ISSUE TITLE
Quackos on a leash murders the game

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#473]
Version 4158 (but this would probably apply to others), putting Quackos on a leash (like I had to keep him from moving too far away while I built a shrine) causes that function (updateLeashedState) to consume vast amounts of tick time (94.2% of our server's tick time when we profiled it). My *guess* is that because he's so large, the game thinks he's gotten too far away from his leashed point, but his frame prevents the game from properly pathing, thus sucking up everything.

I'd say an "easy" way would be to override updateLeashedState on Quackos himself so he simply doesn't attempt motion at all while tied to a fence post

**Comment by Shibva** [comment]
to me, that sounds like something intentional on Quackos' end

the ELDER GOD CAN NOT BE CONTAINED, especially by a leash

**Comment by HbmMods** [comment]
I couldn't reproduce this issue as I didn't even manage to put Quackos on a leash to begin with. However, I simply made Quackos unleashable much like hostile mobs.

As for moving Quackos, despawning him now drops several duck spawn eggs that allow for easy on-demand creation of comically large ducks.

**Comment by Shibva** [comment]
YOU ARE A SAINT!
