### ISSUE TITLE
The rewritten chemplants don't treat the sword right

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#477]
I still don't get how the sword's a battery, but either way, that step is currently broken

**Comment by HbmMods** [comment]
I *knew* I forgot something.

**Comment by thePalindrome** [comment]
Ah, and their output tanks can be filled by other things. If you want I can make another issue for that, or we'll just tack it onto this and hope nobody else notices :P

**Comment by HbmMods** [comment]
Oh yeah I noticed that when the peroxide output of my chemplants kept filling and emptying rapidly. I believe the commit from 2 days ago should fix it.

**Comment by HbmMods** [comment]
Confirmed to be fixed in X4172.
