### ISSUE TITLE
suggestion: add a 20x20 RBMK reactor, and a pressurized water reactor.

### ISSUE THREAD

**Issue by Voxelstice** [HbmMods/Hbm-s-Nuclear-Tech-GIT#478]
since the limit is 15x15, why not increase it by 5. that would allow for (possibly) somewhat even more power generation.
also i want a pressurized water reactor to exist aswell, not sure if you guys can do this

other than that, i don't know what else to say about this suggestion.

if this suggestion is declined i wont mind since I'm not begging/forcing for this to exist anyway

**Comment by HbmMods** [comment]
RBMKs don't have size limits, assuming you're talking about the 15x15 size of the console, you can manage larger reactors with multiple consoles. Not an ideal way to do things for sure, but the console's size has to end somewhere.

As for pressurized reactors, there are some vague plans about replacing the current large nuclear reactor with something of the likes, but it's relatively low priority right now.
