### ISSUE TITLE
[Enhancments] Enhancments to the current turret system with some more fuctionality ( +2 other ideas)

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#479]
Ik I made suggestions a lot, but this time I have some enhancement ideas to already existing content 

Telemetry Card: #SaveYourPets!
while this does seem redundant, sometimes you want your turret to target only certain things and spare others, like your turrets to kill animals but not your ocelots or your tamed cats! this is my idea

Sneak-Use on an entity (with a living base and has HP) will add data to the telemetry card with the entity's ID (not UUID) on it, you can then take the card into the Telementery Linker and add it to the turret-AI chip. This allows for you to have your smart turret system blacklist certain things on its kill list

Sneak+Use on an entity that's tamed will add data to the card (UUID or something) to allow for pets to be added to the turrets Blacklist (now you can kill everything without it killing your or your precious cat-companion (Note: for logic, if 2 or more different pets IDs are present on the card, it will make the turrets logic only to blacklist any Tamable animal (under the tamed base thingy) that's on its card. (for those of you that want turrets to attack others including their pets instead of sparing them overall.

(Possible Advancement for this: The Taste of Blood; can be triggered by having "MASER MAXWELL" (Turret_Maxwell) "accidentally" kill an ocelot or a tamed cat, you monster... [maybe using PotatOS in some way]; would make sense since it does gib's apart what it kills)

"PotatOS, TAKE THE WHEEL!":
PotatOS can be used as a Turret AI card "upgrade". Superior AI allows for other interactions to happen with turrets (internal item setting to allow you to adjust a certain thing, like adding Redstone capability on specific settings: ie, emit a signal when low on ammo or disable the turret when given a Redstone signal. [a comparator would need to add to the recipe to make potatoes]). Gives secondary functionality to turrets to target missiles if provided with a powered radar linked via telelinker (or another item) (putting PotatOS in the AI-slot will make a new one appear where you can put sed telelinker (or other link items), would check the spot where it was set to and if it returns with the correct block being there, set to detect missiles, and is powered, then the current targeting function for missiles will be activated) Accuracy with targeting may vary (but can be improved with existing upgrades [others upgrades might hurt it]); this can be toggled in the items internal settings, even comes with the settings with Redstone interactions.

in short; if you use PotatOS as a Turrets' AI,
-Turrets targeting will be "Smarter" (not sure about how though; maybe rotate on their axis quicker)
-Turrets will gain Redstone and missile settings (maybe through the use of the ability thing, or just add more things to the GUI when it is in that slot, whatever comes first)
-Turrets will be able to target missiles when provided with a linked item linking to a powered radar (with missile tracking enabled) but with some accuracy issues (upgrades can increase and decrease it)

Downsides to using PotatOS as a turret AI chip:
-Energy consumption for the turret is Doubled (Tripled or quadrupled when in 528 mode, no change in baby mode) due to additional power needed to operate it; Energy consumption is Quadrupled (or multiplied by 3.5) when it sets its target for an inbound missile (more power is needed to calculate incoming missiles trajectories, alr) [power consumption for targeting missiles is higher when in 528 Mode)
-might target you when you are low on hp (rare; odds are higher if you are on 528 mode); GLaDOS remembers you.... [will target you regardless if you use it for a Cheapo Gatling Sentry and also gives it 4 reloads worth of ammo (to shoot you with XD)]
[Easter egg: Any entity that is named "Weathly" that comes into range will cause the turret to abandon its  current target (if it has one) and target them instead; for obvious reasons]

Muffled Machines

"Oh no, is your machine too loud and you don't have enough space to attach your muffling block(s)? NEVER FEAR, MUFFLING MANN IS HERE 

New Item: Muffling Man's Muffling Kit  (Tooltip: The Muffler Man's long lost uncle) 
Created using a few muffler blocks, Asbestos (because why not?), Duct Tape, and one "Trade-Secret" item at its core. Can be used 5-7 times (2-3 on 528 mode); damage on an item varies on size [ex: if it's in normal mode, a sound-emitting machine that's the size of the Oil Refinery will use up the entire item, 2 of them if it is on 528;  1 damage of durability if used on something the size of a block (like the Diesel Generator)]

How to use it: Just like with renaming an item with a name tag, put any machine that makes sound into the NTM anvil and the Muffling Man's Muffling Kit in the Second Slot, and it will return the item with a -Muffled attribute tag. Doing the same thing again with the muffled item and replacing it with a Bladed Wrench will return the item as it was to start with (Wrench takes some durability, also you don't get anything back from undoing your muffling; no refunds). This can be done on any tier of NTM anvil.

 EDIT: + Can be used on turrets to give them a scilencer

Muffling Man; the scream muffler (bonus idea/ mechanic): Be warned, the muffling man is not to be taunted with. You can still use Muffling Kits on Machine blocks if the kit does not have enough durability; HOWEVER, in exchange for still getting the job done, you will lose HP to make up for what else was needed to finish the craft. The damage that will be dealt with the player can be calculated with the following equation (might need to be ironed out)
`Calculated Damage Delt =  [ (kit durability cost - durability remaining) / kit's durability cost ] * Players Current HP (<---rounded to the nearest whole if needed)`
[In 528 mode, Players Max HP is used instead of Current HP]
[If the output returns as a negative value, the damage action will be ignored; if it is positive, it will deal that value of HP to the player] (Note: machines that use up the entire kit would have a cost value of the kits max durability)

Any durability that's missing when using this kit and then "crafted" in the NTM anvil will cause the player's current hp to be reduced to the fraction of what is missing. [Ex: You use the kit with 3 uses left to muffle an industrial generator, whose durability requirement is 5, and craft it when your current HP is 50 out of a max of 75 HP; so... (5-3)/5 * 50 = 20. 20 is not a negative number so it will deal 20 points or 2/5 of the current HP on the player upon crafting it. If the kit had 8 durability remaining on the kit instead then it would be (5-8)/5 * 50 = -30. and because the number is negative, then nothing happens to the player's HP upon craft (a check would ignore it and not do anything)

in 528 mode, the player's max HP value is used instead so in the same first example; replace the 50 with 75 and you end up with 30 or 2/5 of the player's max hp delt to you. In this case, you can die from it and get a death message saying something like "@player lifeforce was muffled out by The Muffling Man" or something else regarding you hurting yourself for "cutting corners".

Kits can be crafted together to repair them, in 528 mode, you cant and the recipe to make them requires resources like rubber and other appropriate things (Block(s) of Asbestos instead of asbestos "ingots")

Easter egg for item: the kit itself will appear blood an additional tooltip in blood-red reading "There's Blood leaking out of it..." only when the polaroids appearance is altered to one (or more if you want) of the variety of outcomes (if it's based on rarity and not random, then preferably set it to rare ones)

non-serious suggestion: Hidden Catalog as loot
there's a chance that the hidden catalog can be obtained without cracking the riddle, by either finding it in a meteorite dungeon and/or as a drop from opening a red crate (will drop the book only in this instance) but with extremely low odds of it happening. if this was to be considered, id say the odds of getting it as loot or a drop from the red crate be either as rare as "the perfect zombie" spawn odds (rarest thing in vanilla Minecraft) or more or less the same odds of being struck by lightning 20-37 times in the same area and survive (IRL ods)

**Comment by Vaern** [comment]
Please stop flooding the issues page with suggestions.

**Comment by Shibva** [comment]
ok, the last one was more of a suggestion, ill admit, but the other 2 (or the first one especially) are ideas to enhance the functionality of turrets

**Comment by ncr-t** [comment]
[ideas to enhance the turrets] is just another sentence to say [suggestions for turrets]. Please refrain from using the [issue] page for suggesting.

**Comment by Shibva** [comment]
ah, well the first one I listed is a practical one for the turrets though, I actually tested this and turns out your turrets will attack your own pets if you have it set to kill animals, and theirs no way to have them be spared from it, hence this idea to enhance it. I even tossed in the cats to sell it a bit, after all, it did it with tamed dogs so it will do the same to cats. Besides, it also gives the Telementery Card a secondary use for survival and a practical purpose for singeplayer

I do love this mod and I do come up with some great ideas, thing is I cant share them on the discord for "banned when I'm not on the ban list" sort of situation, and I'm aware of suggestions being forbidden for the "metric fuck ton" of bad ideas, but with some of these, I put actual thought into them and do my best to give details on ideas that can be used to either add to or improve the mod.

**Comment by ncr-t** [comment]
Suggesting is forbidden both here on over to discord. Please refrain from suggesting in the [issue] page.

**Comment by Shibva** [comment]
alr, its hard to but ill try

though I will say the first one in this list is an issue, I mean, the new turrets are supposed to be smart and can be modified to include other players, using the tele card, but not for pets, I then gave a solution on what I would do if I knew how to code and do it without adding any sort of new items in the game (the telecard was made for adding players, so why not being able to add entities/pets to it as well?)

**Comment by Vaern** [comment]
> alr, its hard to but ill try
> 
> though I will say the first one in this list is an issue, I mean, the new turrets are supposed to be smart and can be modified to include other players, using the tele card, but not for pets, I then gave a solution on what I would do if I knew how to code and do it without adding any sort of new items in the game (the telecard was made for adding players, so why not being able to add entities/pets to it as well?)
> 

You are not trying, you are continuing to push your suggestions. Please stop.

**Comment by TheForge129** [comment]
As I have stated previously,
get Eclipse <http://eclipse.org/downloads>
and then follow the instructions at the bottom of the github page
if you don't know how to code, I'm sorry, that's not my problem

**Comment by HbmMods** [comment]
I have reason to suspect that engaging in the act of alcoholism on a workday wasn't the brightest of ideas, nor is responding to this issue right now, but at the same time I believe that If i don't do it now this issue will just keep staring back at me until time ends and I prefer not to challenge such a situation, so here we go
![image](https://user-images.githubusercontent.com/16674258/156643639-c7070342-71f4-420c-ab19-5bdc8bdfcfdb.png)

> Telemetry Card: #SaveYourPets!

Instead of trying to revive the flawed concept of telemetry cards in an attempt to somehow shoehorn that system back into turrets, there is two incredibly easy alternatives:

1. The list of exceptions doesn't just work for players and their display names but all named entities. Of course that means your herd of cats with no names still gets mowed down, but I'd assume if you care to get a pet you'd likely want to name it too (especially since NTM makes name tags craftable) (I haven't even seen anyone keep a pet in literal years, perhaps that's just NTM's tendency to kill everything via landmines, meteors or radiation) (third parenthesis)
2. Entities that are ownable will automatically be exempt if the owning player is whitelisted. That way we don't have to screw around with name tags and we can safely assume that 99.99% of players don't want their pets to be turned into swiss cheese no matter what. But your pet creeper that you have to keep locked in a cell won't be protected so there is a downside.

> The Taste of Blood; can be triggered by having "MASER MAXWELL"

TToB was supposed to be given out when being vaporized by the CEL-PRIME weapon system that was scrapped at least 3 years ago. Sure we can just reuse that achievement but why not just make up a new joke that fits the achievement trigger? Something about microwaving hamsters? Besides, murdering your own pets isn't exactly something I want to be giving achievements out for.

> "PotatOS, TAKE THE WHEEL!"

I have absolutely no idea what to make out of this one, how can a turret be "smarter"? Faster turn speed and detector delay? I'd argue all turrets already do these more than well enough for their use-cases. Missile scan ability? Every turret not only can do it, but the setting (machine target mode, the little cog) is enabled by default. It's just that most turrets are both too slow and too short-sighted to be effectively used against missiles. Besides, why would you, when Howard (my beloved) exists? Redstone-ability could be a valid point, but I don't see why something so simple would need to be gated post-spark (and therefore post-euph) when it could just be a simple functionality that all turrets can do by default?

> "Muffled Machines"

Most machines don't even have block-muffling implemented in the first place, not sure why we'd need an upgrade for that. I think there's a much better point being brought up by my man #468 which would move all machine sounds into a custom category so you can just turn all of them down without needing to mess around with smelly wool blocks. I haven't looked into how it works yet, but since I'm attempting to fix machine sound loops soon, I'm trying my hand at doing sound categories while I'm already at it.

> EDIT: + Can be used on turrets to give them a scilencer

I cannot think of a scenario where a large static piece of defense equipment would need silencing, but if we're already doing sound categories, why not weapons as well?

> Muffling Man; the scream muffler

I can't tell if I'm reading this one right, but why would a muffler upgrade use your HP to work? Do you glue styrofoam sheets onto your machinery with your blood? I mean we have iv bags full of your body juice already, who knows what we can use all that delicious iron fluid for? Red dye perhaps?

> non-serious suggestion: Hidden Catalog as loot

No.

Also GH's preview died and I can't remember what image i pasted into this at the beginning i just hope it was funny

**Comment by Shibva** [comment]
alr, thanks for the feedback, ill make a new "issue" that refers to what you said about pets and turrets and it being solely on that for it to be easy to reference

as for the Muffler man thing, it was supposed to be some joke, as in you use a kit up and it doesn't mean the durability requirement yet you can still use it. the gag with the damage was to infer that the mascot of this product does not like that one bit and "by some unknown means" takes some of your HP to compensate; thinking that the user is soo smart to use something like a kit with 1 hp to muffle something that needs full durability of it and, like a loan shark or something of the sort "finds you and beats you up" and it happens to be to the point where your HP is reduced to the point where only about what durability you were missing to PROPERLY use it is left. The best way to think about this is like having a mafia or gangster group coming after you and beating the ever-loving shit out of you. 

While that's was supposed to be the gag, in actuality, you just end up hurting yourself as you install it, not having enough of the materials to properly coat it, and end up hurting yourself in the process (on the premise of not cutting corners)

as for the PotatOS, the original idea was to just have it be used as an AI chip of some kind (considering they are made with one), but then I started to think of new ideas to make this practical, guess I got carried away (and that's what the cog button is for, I thought that was for something else) but glad to still hear the idea of restone can be used I had a thought when typing this up on a new type of AI chip that can be linked to a terminal (that can hold many different turret ids or the same frequency) and have it act like a "Master Control Terminal" to allow the user to manage all of their turrets at once or individually from one location, it would be probs be in a category between the production of the Turrets and before Spark stuff (sorry, I'm not familular with the progression terms order/list like you used when describing that one) and it serving as a more dynamic way of controlling your turrets without the use of restone 

anyhow, before I (or you) can close this semi-useless thread/issue report, I need to know some things

1. are turrets supposed to be able to function if there is no AI card in them, if not then that's a bug.
2. Are you going to implement the doors that Drillgon200 added into this version? (I've noticed the Transission Seal
3. is there a way to start the Seige in survival when it is finished? if not I have an idea on what can start it, lets's just say my idea on starting involves causing a "Resonance Cascade" if you catch my drift.

4. Cactus, is quackos immune to Cactus? I got lucky when I spawned close to a desert atom (and made it my home after using respawn bez-kill methods to remove the RAD' Sources) and he disappeared on me. Don't know what happened to him or if it was something I did. Guess his people needed him. I did find out that his readable HP is 4 so that's why I'm asking.

**Comment by Vaern** [comment]
There's no need to open up a new issue on it, Bob will probably remember.

**Comment by HbmMods** [comment]
> are turrets supposed to be able to function if there is no AI card in them, if not then that's a bug.

Yes, the AI chip is only necessary if you want a player whitelist, as there isn't a non-automatic mode on the new turrets

> Are you going to implement the doors that Drillgon200 added into this version? (I've noticed the Transission Seal

Probably

> is there a way to start the Seige in survival when it is finished?

It's a gamerule, there will be comprehensive instructions on how it works once we have the test server set up.

> Cactus, is quackos immune to Cactus?

Yes, unless something goes out of its way to instantly remove him or something, he can't take damage or have his health modified by conventional means, including anything vanilla has to offer.

**Comment by Shibva** [comment]
>Yes, unless something goes out of its way to instantly remove him or something, he can't take damage or have his health modified by conventional means, including anything vanilla has to offer.

@HbmMods what about is being unloaded? is it immune to the game despawning it
guess ill have no quackos

 yah know, this also gives me a stupid idea

Ducc creation, create your own duccs, and it be done [and the first to probably] be a mob transformation with digamma radiation
