### ISSUE TITLE
[#479 relocation] Turrets and Pets, be nice to have both (& Knuc-, I mean Redstone)

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#480]
> "Instead of trying to revive the flawed concept of telemetry cards in an attempt to somehow shoehorn that system back into turrets, there is two incredibly easy alternatives:
> 
> 1. The list of exceptions doesn't just work for players and their display names but all named entities. Of course that means your herd of cats with no names still gets mowed down, but I'd assume if you care to get a pet you'd likely want to name it too (especially since NTM makes name tags craftable) (I haven't even seen anyone keep a pet in literal years, perhaps that's just NTM's tendency to kill everything via landmines, meteors or radiation) (third parenthesis)
> 2. Entities that are ownable will automatically be exempt if the owning player is whitelisted. That way we don't have to screw around with name tags and we can safely assume that 99.99% of players don't want their pets to be turned into swiss cheese no matter what. But your pet creeper that you have to keep locked in a cell won't be protected so there is a downside.
>    "
> 
> * @HbmMods
> 
 (moved this from #479  to make locating this a bit easier)

**Comment by Shibva** [comment]
`To be honnest I like the idea of 1 more than 2, but I still think it would be nice to have the telemetry card be used as a way to "quick Copy" names of named pets as shortcut or something, just something to make the Telemetry Card has some more functionality to it

**Comment by HbmMods** [comment]
> used as a way to "quick Copy" names of named pets as shortcut

Names are already stored on the AI-chip which can indeed be copied with the old turret telemetry linker (assuming it still works, which it should)

**Comment by Shibva** [comment]
hmmm, never really tested it on named mobs, ill try that real quick

also, the idea or restone could be useful for restone control for the turrets

thinking about maybe a signal going into it would toggle the turrets function and adding a comparator would have it output a signal if it is out of ammunition (not sure for the MAZER)


As for TToB advancement (Sorry for the use of a newer version term), I like the idea of frying hampsters, but IDK what would be the hamster, I'm tempted for it to be a cat for some reason (not that I hate them, I had one before we gave it to my grand folks due to developed allergies) but as emphasizing the meaning of it being a total accident; and for this to best keep with your preference of intentionally killing a pet out of the picture, id say it would involve MASER-ing an ocelot. what would make even more sense to this is using PotatOS with this in some way, considering the advancement desc currently for TToB makes it sound like it was some testing accident (and I thought it was a portal ref too). either that or some gag among the line of letting PotatOS use a Cheapo Sentry and then kill you with it (because of revenge or something)

**Comment by HbmMods** [comment]
> hmmm, never really tested it on named mobs, ill try that real quick

It's not implemented to work on named mobs right now, the point is that once named mobs are considered valid exceptions, their name entries would behave the same way as player names on the chip, being able to be copied the same way.

**Comment by Shibva** [comment]
ah, yes, thats perfect. that way it can meet both our ideas; a way to save pets and also another use for the Telementery Turret card

... I wonder if in the future this card will no longer become just for turrets, but used as some sort of data-acquiring thing for other blocks that have frequencies, would open up more possibilities for what could be done, like that idea with turrets being lined to one chip to serve as a Baste turret defense terminal.

**Comment by 7pheonix** [comment]
ok thank you have a nice day the door is that way <3

**Comment by Shibva** [comment]
@HbmMods on side note: im modifying this recipe on my end using CT, the cable drum is made of steel, I mean, wheres the Red Alloy Cable in it that makes allows you to connect them that connects each other? would make sense to have some in it than using an empty spol to magically connect the 2 ploles together, might also not be a bad idea to have the spool become empty again after using it once.

(modified recipes)
![image](https://user-images.githubusercontent.com/38770780/156700796-f400eac8-2529-4cb0-837c-e16ca284ac36.png)

**Comment by HbmMods** [comment]
> wheres the Red Alloy Cable in it that makes allows you to connect them that connects each other?

It comes with the pylon and connector blocks, hinted to by the fact that every pylon is crafted with at least one spool of red copper wire. This was done because it's so much easier compared to either having wire items in your inventory that get used up or losing durability on your drum, which is just a pointless annoyance when you want to move connections around. In addition, it goes against my principle of making basic infrastructure like power nets just as complex as absolutely necessary.

**Comment by HbmMods** [comment]
Turret whitelists now work on any named entity.
