### ISSUE TITLE
Turbofan sound loop broken and funny drill bug & Toolbox Durability Glitch

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#482]
### Describe the bug

idk what is going on, but the moment the turbofan starts up it plays its loud ass sound, but then it just stops making sound

version: 1.0.27X4158

**Comment by 7pheonix** [comment]
I believe this is a wider issue with looped sounds as a whole stopping after a whie. Bob's working towards a fix sooner or later, just bear with him for now.

**Comment by Shibva** [comment]
would also be neat if blocks of insulator can act like a heatshield
![image](https://user-images.githubusercontent.com/38770780/156821794-b636896a-c5ae-4b61-84dc-15376e216f49.png)
or have the particles cancel out if they come into contact with a solid block (iron fences would still let them pass
![image](https://user-images.githubusercontent.com/38770780/156821877-07292d31-1976-4fd2-94c7-6609ff4c72de.png)

**Comment by Shibva** [comment]
@HbmMods oh on another note I just found this

![image](https://user-images.githubusercontent.com/38770780/156824444-b16a8832-e660-43da-94b3-1e355d445a67.png)
those are FBP and those are a telltale sign that gas blocks are being mined
is this supposed to happen

also it might be a nice thing to have this auto drill not mine the first layer of blocks, you call tbh
![image](https://user-images.githubusercontent.com/38770780/156824838-20f3b3e5-d906-4473-b821-de6806f1126f.png)

**Comment by Shibva** [comment]
oh yeah, heres one that I jsut found

Toolbox Dupe glich: some items will take durability rather than being crafted into a tool box

Ie; Screwdriver (non-desh)
