### ISSUE TITLE
[Visual bug] Broken hanging cables

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#484]
### Describe the bug
.... eh, your guess is as good as mine on this one
all I know is that it might have happened when i reloged into the world

![image](https://user-images.githubusercontent.com/38770780/156844693-29d229ed-e600-4159-8d01-cf3b283c81d1.png)
(reference shot)
![image](https://user-images.githubusercontent.com/38770780/156844702-ddd60c3f-af4c-4bfd-8d2a-07837eda7654.png)

**Comment by PewPewCricket** [comment]
This seems to happen when a wire is too long from my experience with worldedit. However, in your case, I am not too sure as the wire seems to be in range.

**Comment by Shibva** [comment]
might be an old bug that got patched
