### ISSUE TITLE
Electric Boilers don't update fluid tooltips when block power changes with gui open

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#485]
V4158

When processing a recipe in the electric boiler, when the internal battery runs out processing immediately stops, even if the heat is high enough that it should continue. Easily testable by getting it up to max heat, processing water into steam, then removing the power supply

Admittedly a bit lower priority, but it's a bit of a pain to have to continue pumping more power in

EDIT: Turns out this is a visual thing with the gui not updating the tooltip, so moving the issue to refer to that instead

**Comment by HbmMods** [comment]
Seems to be working just fine on my end with both water and oil. However there was a small syncing issue where the tooltip would get stuck when the GUI is left open during the block transition (off -> on) while the gauges would still show the correct amounts.

**Comment by thePalindrome** [comment]
Ah, you know what?
That's exactly what I'm seeing, on closer inspection.
Very... weird tbh, since the temperature tooltip goes down properly as the block runs out of power, but the fluid ones don't.

Editing the issue to reflect that

EDIT: some more testing shows that all the tooltips break, but they seem to take varying amounts of time. I'm going to assume it's just random noise from server load, network connections, and specific actions.

**Comment by HbmMods** [comment]
Should be fixed with the newest release, although I haven't ran any tests on servers yet.

**Comment by thePalindrome** [comment]
Confirmed Fixed, forgot to update this issue.
Many thanks!
