### ISSUE TITLE
All kinds of americium fuel unrecyclable

### ISSUE THREAD

**Issue by derdoodle1200** [HbmMods/Hbm-s-Nuclear-Tech-GIT#486]
Dont know wether this is a bug or if its supposed to be like this but i cant recycle any kind of americium fuel from RBMK pellets (including short- and long lived waste), NEI cant find any recipes neither. pls fix :(

**Comment by HbmMods** [comment]
Americium fuel recycling hasn't been implemented yet because the next level of RBMK fuels, californium, hasn't been added yet either.
