### ISSUE TITLE
[Enhancment/Bug] Power Armor's Helmets should cease the heads player render when being worn

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#487]
### Describe the bug

one thing that I happen to notice is that power armor's helmets sometimes tend to have issues with the head as you can see here
![image](https://user-images.githubusercontent.com/38770780/156899344-5a154d6b-bd60-4c71-9798-c79911875d5f.png)
and here
![image](https://user-images.githubusercontent.com/38770780/156899352-6a076882-8db2-43c9-9a4c-adb444c91695.png)

Turns out when you have Optifine Instaled the player's skin is adapted with the second layer of the skin just like in newer versions and because of this, the "Hat" part of the players skin renders and pops out of the amor like you see here

the most simple solution would be to disable the player's head render when its wearing any of the power armor helmets, thus eliminating the issue altogether

**Comment by HbmMods** [comment]
Also tends to happen with some leg pieces like Fau, disabling the player rendering as a whole is indeed planned for full power armor sets.

**Comment by Shibva** [comment]
I was going to say that but I saw only the head doing it, so yeah, not a bad idea

have it disable certain parts depending what power armor piece it has on

though the annoyance with this that I noticed is that it seems to also diable the player hand render in first person, guess you cant have both the the hand and the torso disabled

**Comment by SteamDoge9000** [comment]
on another note, Id think the reminants power armor should have some ancient scrap in it, I mean its only used for one recipe and you get a lot of it, so maybe something for making special palting using it in the anvil, tier 6 or higher anvils

**Comment by SteamDoge9000** [comment]
and just to finish this off, It would be also nice if there was a variant upgrade for the ash goggles to be put on armors, maybe the same could be done with the Geiger counter? I mean it makes sense

**Comment by 7pheonix** [comment]
Could you kindly not interject a normal bug report with your suggestions which we have told you _time and time again_ do not belong here?

**Comment by SteamDoge9000** [comment]
Important news: I found some interesting information

FoamFIx causes the player render to change and bulge more out than usual (pops out of armor more)

**Comment by Shibva** [comment]
@HbmMods I found that FoamFix is most likely to cause this issue, as it causes the other parts of the body to pop out as far as I have seen

**Comment by HbmMods** [comment]
Hat layers rendering over helmets should be fixed in X4178, though I haven't tested all helmets yet.

**Comment by Shibva** [comment]
Will it take into account with foamfix (addding this in seems to make the layer situation more noticeable)

I'll try it on my end when I have the chance
