### ISSUE TITLE
Crashing upon entering world

### ISSUE THREAD

**Issue by TheBrogan101** [HbmMods/Hbm-s-Nuclear-Tech-GIT#495]
[1.0.27X4158]
I make a new world and it crashes
https://pastebin.com/nt82nfAJ

**Comment by HbmMods** [comment]
Already known and fixed in-dev. Also, how are you even playing this mod without NEI?

**Comment by TheBrogan101** [comment]
I forgot to add it lol. Do I use an older version?

**Comment by HbmMods** [comment]
The mod depends on CodeChickeCore by accident, so having NEI installed (with CCC too of course) will fix it.

**Comment by HbmMods** [comment]
Fixed with X4172.
