### ISSUE TITLE
Pickaxe's abilities are not working properly

### ISSUE THREAD

**Issue by luckybl0ck** [HbmMods/Hbm-s-Nuclear-Tech-GIT#497]
### Describe the bug

If you activate Luck, Furnace or Silk ability on pickaxe and break the steel crate, it will disappear. The items in it will not be lost and will fall to the ground. Mod version - X4158.

**Comment by HbmMods** [comment]
Fixed for luck and silk touch, processing abilities most likely still suffer from this.
