### ISSUE TITLE
[suggestion, yes im being honnest about it this time] Helmet Special Upgrade idea; The Gobbler

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#505]
so let's be honest, I had this idea and yes it's a suggestion, but it could also be an enchantment for something. 

The Gobbler: A wonderful invention of the republic of Quak-reia that can be attached to your helmet and automatically feeds you on any available food in your inventory. inspired off the success of Jampsterdan's autoinjector

-Quack'n Wacks Co. does not take responsibility for the "The Gobbler" resulting in feeding you any spoiled food (rotten flesh and other bad things to eat) as a result of product design and by using this product you agree to the terms and conditions of the product and therefore can't sue Quack'n Wacks Co. for any claims regarding overconsumption, food poisoning, and death (if you have a plan c on you and nothing else to eat)

Edit: Quackos Approved

**Comment by 7pheonix** [comment]
Hey there, steamdoge. I'm really sorry about this, I have tried for several weeks to try and keep a positive outlook on you and your presence within the issues board. I'm going to sound like a total jackass/discord mod/reddit mod here but i really do not give a shit. Every time you've popped up to shove another uninteresting suggestion down into our eyes I've told people to give you "one more chance", that "he does make legitimate bug reports sometimes". But I wish to ask you why you are unable to read the now over 10 _fucking times_ that you have come up with an awful suggestion and blatantly posted it here despite us telling you that **suggestions do not belong in the Issues board.** Even when you make legitimate bug reports, you manage to shit in a little whip of a suggestion. But here we are, and you're back to blatantly disregarding our instruction, clogging up the Issues board making _legitimate bugs_ harder to sort through and find. Fuck you, steamdoge. You are not fucking welcome in this Issues board, you are a plague upon mine, Bob's and several other people's psyche. Please, if you take away one singular lesson from this: **Stop Suggesting Ideas For The Mod.** Get it into your thick skull and let it stick for all eternity.

**Comment by ncr-t** [comment]
![skeleton-skeleton-smoking-cigar](https://user-images.githubusercontent.com/88532121/158035389-286034a8-df92-46f7-9d92-d5be5df9cd4d.gif)

**Comment by Shibva** [comment]
ok, fine. I was just wanting to contribute to this mod, I mean, I love it and I wanted to help come up with some ideas for content and stuff for it. I mean I do get it, but you guys don't have to be trashy from it. I just like making ideas for things I really like.

ill be reporting only bugs now... thanks for this ig. 

as for calling my ideas shit, maybe you have your own for the mod too. but at least I was BRAVE and or foolish enough to post the ones I thought would be a nice lil addition to this mod.

**Comment by ncr-t** [comment]
Brave ? I don't get what's so brave about not breaking a rule

**Comment by 7pheonix** [comment]
Sorry, I kind of got a bit carried away with that message. But the message still stands; thank you for agreeing to stop posting suggestions.
