### ISSUE TITLE
[Suggestion for GitHub Issue Traker] Automatic Issue Closer bot for "Clutter Control"

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#506]
I got the message to stop making suggestions and whatnot, but this is different.

what @Vaern, @7pheonix, and [missing name] is true and so what im doing is just going back and telling others in the older remarks to close there's if they are not tagged or tagged with invalid suggestions and questions

I mean, no one else is going to do it so who else is gonna? If that's going to be the case still, then maybe adding a bot to automatically close issues that are marked with Invalid and question would be closed automatically after maybe a 3-4 day period, as for old remarks that are not tagged, they would be auto-closed by the bot after a month's time

Reports that are valid and tagged may still be left as it, but could also be auto-closed after 3 months of inactivity

I've stopped making suggestions to the mod, so I figured maybe this one would help clear out the clutter before it builds up too high}

Hope out of all the stupid ideas I've given that this could be at least a good one

**Comment by Vaern** [comment]
ayo what happened to no suggestions

**Comment by Vaern** [comment]
(I think it'd be fine enough to go through any older suggestions and close them)

**Comment by Shibva** [comment]
and as a courtesy, I went back an closed any of mine that don't have proper tags

**Comment by Shibva** [comment]
the oldest one thats valid was #200 and that would be closed by me if it wasn't still for the fact that the Dee Magnets still exist as of this time

**Comment by HbmMods** [comment]
nah
