### ISSUE TITLE
Gerald The Construction Robot

### ISSUE THREAD

**Issue by solundev** [HbmMods/Hbm-s-Nuclear-Tech-GIT#508]
While using it to construct the orbital superweapon, it actually made the map have literaly zero sun light and conflicted even with custom NPC, idk if it's suposed to happen but they all not only disapeared but mobs/npcs can't be spawned and created, it's like a huge server lag, but the destruction still consumes the entire world aparently, some screenshots showing the results...

![2022-03-12_06 20 41](https://user-images.githubusercontent.com/82925878/158046733-d256d4c7-b8f3-40f5-b366-f2acf9b2668f.png)
![2022-03-12_06 20 54](https://user-images.githubusercontent.com/82925878/158046714-6aae9ef3-4e4f-4eeb-a19d-0665218cd01f.png)
![2022-03-12_05 22 14](https://user-images.githubusercontent.com/82925878/158046718-16b8f76b-273b-498d-8aaa-5c2faaf042a7.png)
https://cdn.discordapp.com/attachments/831041528876499004/952131613846822922/unknown.png
https://cdn.discordapp.com/attachments/831041528876499004/952131299257245706/unknown.png

**Comment by SoB1nary** [comment]
*that means it worked.*

**Comment by HbmMods** [comment]
The impact causes a global firestorm that triggers a period of darkness, in addition to causing a mass extinction which disables spawning for most larger mobs. There is no direct way of undoing this ingame but if you have access to the world files, you can go into the save's folder, then into `data`, where you have to delete a file called `impactData.dat`. This will revert all darkness and extinction effects.

**Comment by solundev** [comment]
oh, thank you, that's news to me, that's cool then, i'm glad to be helping
