### ISSUE TITLE
cyclotron does not accept power

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [HbmMods/Hbm-s-Nuclear-Tech-GIT#51]
The cyclotron's internal power buffer will not fill up from batteries nor from cables. Tested with latest release X3493.

**Comment by Nos74** [comment]
I didn't even know it was possible to fill up the cyclotron's energy buffer by means other than as a byproduct of normal operation

**Comment by Drillgon200** [comment]
That's right, the cyclotron creates power, so you can't fill it.

**Comment by bHXDgiuMa5yLHyC8** [comment]
That's really counter-intuitive...
