### ISSUE TITLE
SPAS-12 alt-fire doesnt work with special shells

### ISSUE THREAD

**Issue by Pato0101** [HbmMods/Hbm-s-Nuclear-Tech-GIT#510]
### Describe the bug

version: 4172

when using the right click function of the spas-12 when its loaded with, say incendiary rounds, it will fire simply normal buckshot, and not the incendiary shells

**Comment by HbmMods** [comment]
Seems like having extra shells in your inventory causes the gun to use those for the projectiles instead of the shells that are loaded.

**Comment by HbmMods** [comment]
Fixed in X4178.
