### ISSUE TITLE
crash when holding any weapon 

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#511]
(using HBM-NTM-.1.0.27_X4172) game instantly crashes when holding any ntm weapon in your hand
[crash-2022-03-13_20.54.49-client.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/8240497/crash-2022-03-13_20.54.49-client.txt)

**Comment by HbmMods** [comment]
Did you perhaps change one of your keybinds to some unconventional button *again?*

**Comment by HbmMods** [comment]
It's probably related to mouse buttons having negative key indices by default, I switched the check for the reload button to use a vanilla function that can handle mouse buttons. In the meantime, you should probably rebind your reload key to something that isn't your mouse.

**Comment by HbmMods** [comment]
Should be fixed in X4174, although I haven't tested it yet.
