### ISSUE TITLE
Assembly Template ID Shifts are being frustrating

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#512]
version 4172 (and many versions before that)

I recall you mentioning that you've fixed the chemical recipe IDs shifting, but the assembly ones still need that protection. It's a bit of a pain when my circuit assemblers stop working because the blueprints have magically shifted!

**Comment by HbmMods** [comment]
Has been fixed with X4242, all new assembly templates now save their recipe as NBT instead of a metadata representing the recipe's index (which is what actually changes, causing ID shifts). Existing metadata-templates will still work, being highlighted with the "volatile template" tooltip.
