### ISSUE TITLE
Energy bug

### ISSUE THREAD

**Issue by solundev** [HbmMods/Hbm-s-Nuclear-Tech-GIT#514]
When using reactor for example to generate energy for turrets every of them, sometimes the energy drops to negative, forcing the player to use a infinite battery to fix the issue, and if you remove it sometimes it doesn't solves the issue at all

![image](https://user-images.githubusercontent.com/82925878/158129988-609cfdde-9418-41e9-a4f8-04e1fe313f5e.png)

**Comment by solundev** [comment]
looks like the energy is being pulled out from the turret for other ones, but still shouldn't be negative like this...

**Comment by HbmMods** [comment]
Do you have a FEnSU in your energy network?

**Comment by solundev** [comment]
> Do you have a FEnSU in your energy network?

yes, it does have

**Comment by solundev** [comment]
update in the issue, from the FEnSU not even the infinite battery is fixing this issue, i believe this is really a bug.

**Comment by HbmMods** [comment]
Fixed in X4178, the FEnSU now has a limited output of 10PHE/t.
