### ISSUE TITLE
How should Chemical Factory power with cables

### ISSUE THREAD

**Issue by mcmso** [HbmMods/Hbm-s-Nuclear-Tech-GIT#515]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.
![QQ截图20220314220921](https://user-images.githubusercontent.com/46519955/158189696-0e2da9ba-7ef5-43e4-8c3e-5fec03760878.png)
Is there any alternative to battery power
![QQ截图20220314221056](https://user-images.githubusercontent.com/46519955/158189887-70bf1c85-ac90-4fe1-9f67-3cdd0881d4f3.png)

**Comment by HbmMods** [comment]
Fixed in X4174.
