### ISSUE TITLE
gas centrifuges crash singleplayer game

### ISSUE THREAD

**Issue by Pato0101** [HbmMods/Hbm-s-Nuclear-Tech-GIT#516]
### Describe the bug

version: 4172

when i place down 4 gas centrifuges cascading into eachother, power them and fill them up with UF6, the server immediately closes, not the game, the server. i get set back to the title screen and there is no crash report. will send video as thats like the only thing i can send, there doesnt seem to be a log or a crash report so yeah

https://imgur.com/a/hGxMbRO

**Comment by Pato0101** [comment]
have not tested in a server

**Comment by HbmMods** [comment]
I can't replicate this issue, do you have any other mods installed? Does the log "fml-client-latest.log" show any error messages?

**Comment by Pato0101** [comment]
[latest.log](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/8248153/latest.log)

**Comment by HbmMods** [comment]
Seems like an issue related to the new sound category. Does your game crash when you try to change the volume levels? If so, could you redownload yesterday's release?

**Comment by Pato0101** [comment]
ah, allright

**Comment by Pato0101** [comment]
yup, doesnt crash now
was it crashing because it couldnt find the audio volume to play at? because i noticed the options.txt file was also missing

**Comment by HbmMods** [comment]
There was an issue preventing the sound category from initializing properly, which is what ended up causing the crashes or the sounds breaking to the point where it kicks you from the server. Does the options file work properly now?

**Comment by Pato0101** [comment]
Yes, thank you
