### ISSUE TITLE
Flashlead  RBMK pellets have negative radiation

### ISSUE THREAD

**Issue by TehTemmie** [HbmMods/Hbm-s-Nuclear-Tech-GIT#519]
Flashlead RBMK pellets (i.e. the ones you get from recycling RBMK fuel rods) with high xenon level have negative radiation. Other pellets likely have higher (or lower) radiation than intended due to how the RBMK radiation modifier is implemented. Specifically, this line seems to be the issue:
https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/blob/13c3250005e5481c5dff9653d455ece0106a2ab1/src/main/java/com/hbm/hazard/modifier/HazardModifierRBMKRadiation.java#L30
This works fine when the pellet's metadata is between 0 and 4, but high xenon pellets have metadata ranging from 5 to 9, which results in radiation levels outside the (presumably) intended range of radiation values.

**Comment by HbmMods** [comment]
Fixed in X4174.
