### ISSUE TITLE
schrabidium device does not respect ore dictionary

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [HbmMods/Hbm-s-Nuclear-Tech-GIT#52]
The schrabidium transmutation device does not accept other mods' uranium ingots. Tested with latest release X3493.

**Comment by Nos74** [comment]
Which mods'?

**Comment by Drillgon200** [comment]
Any, the transmutation device does not use ore dictionary. However, an ore dictionary converter may be able to transform other mod's uranium into NTM uranium.

**Comment by HbmMods** [comment]
The SchrabTrans has been adjusted to accept all "ingotUranium" OreDict items, you can try it once the next release comes out.
