### ISSUE TITLE
Armor pads don't reduce fall damage

### ISSUE THREAD

**Issue by TehTemmie** [HbmMods/Hbm-s-Nuclear-Tech-GIT#521]
Using version X4172
Armor pads (the type of armor mod that applies to boots) don't reduce fall damage at all. Falling a distance of 15 blocks while wearing boots with slime, rubber, or static pads results in 12 damage taken (6 hearts), which is the exact same damage as not wearing any armor at all.

**Comment by HbmMods** [comment]
Yeah, uh, so turns out that pads were lacking the code for them to do anything all this time.

**Comment by HbmMods** [comment]
Fixed in X4174.
