### ISSUE TITLE
Chemical plant connected drawer, output item will cause chemical plant to disappear

### ISSUE THREAD

**Issue by mcmso** [HbmMods/Hbm-s-Nuclear-Tech-GIT#522]
### Describe the bug
Chemical plant connected drawer, output item will cause chemical plant to disappear
Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.

**Comment by HbmMods** [comment]
Drawer? From the storage drawers mod? Could you try to do the same thing with the chemical factory? There was a bug where it would crash with Thermal Expansion caches but that was fixed, although it still affects the chemical plant.

**Comment by mcmso** [comment]
> Drawer? From the storage drawers mod? Could you try to do the same thing with the chemical factory? There was a bug where it would crash with Thermal Expansion caches but that was fixed, although it still affects the chemical plant.

https://user-images.githubusercontent.com/46519955/158789367-d43c3610-6ee5-4b14-867b-a5e913a1f198.mp4

**Comment by HbmMods** [comment]
The bug might be fixed in version X4178 but I haven't tested storage drawers yet, only Thermal's caches.
