### ISSUE TITLE
Blinding hazards don't reduce vision

### ISSUE THREAD

**Issue by TehTemmie** [HbmMods/Hbm-s-Nuclear-Tech-GIT#523]
Items with a blinding hazard apply blindness to the player for however many ticks their "blinding level" is, with most items having a blinding level of 5 or less. Some nominally blinding items don't apply blindness at all since the blinding level is less than 1, which gets rounded down to 0. Due to how Minecraft renders blindness, the last second of blindness has a significantly reduced effect on the player's vision. At 20 ticks, the effect on vision is still somewhat noticeable, but at 5 ticks or less, the only real effect is preventing players from sprinting.

**Comment by HbmMods** [comment]
Fixed in X4193.
