### ISSUE TITLE
[JankFix] Nuclear Furnace should *probably* have a separate slot for empty rods or slot guarding

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#526]
The nuclear fuel rods can be stacked, but if they're stacked in the fuel slot of the nuclear furnace, they're deleted until the last one (makes sense, given that there's nowhere to put them). So I guess either restricting it to only allow one item int he fuel slot at a time, or a separate dedicated slot that can't have items put in it externally that can hold onto the empty rods might be a good idea!

**Comment by HbmMods** [comment]
Should be fixed with X4178, the slot's stack limit has been changed back to 1 (which was the fuel rod's original limit).
