### ISSUE TITLE
TileEntityFluidDuctSimple heavily load the server

### ISSUE THREAD

**Issue by luckybl0ck** [HbmMods/Hbm-s-Nuclear-Tech-GIT#529]
### Describe the bug

TileEntityFluidDuctSimple heavily load the server even with a small number of online players. This is probably due to the updateConnections method.

Mod version - 1.0.27_X4144 (TileEntityFluidDuctSimple class has not changed in new versions)

https://spark.lucko.me/dITe9jzPid

Unfortunately, right now I don't have the opportunity to test this issue on newer versions.

**Comment by HbmMods** [comment]
Known, it's a fundamental flaw of the inefficient flood-fill based transmission code. Cables used to suffer from it too until the rewrite not long ago, fluid pipes will also receive the same treatment soon.
