### ISSUE TITLE
Bedrock coltan ore doesn't work

### ISSUE THREAD

**Issue by TehTemmie** [HbmMods/Hbm-s-Nuclear-Tech-GIT#535]
The mining drill is meant to extract a slow but infinite supply of coltan from bedrock coltan ore. However, after looking through the mining drill's code, it seems that it doesn't extract any coltan. The issue stems from the `tryDrill()` function: https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/blob/67e180ccb2d6773d4c256aa808e6ba8031144a3e/src/main/java/com/hbm/tileentity/machine/TileEntityMachineMiningDrill.java#L324
This line ends the function if the block detected either is air or has a hardness that is not between 0 and 70. As an unbreakable block, bedrock coltan ore has a hardness of -1 and will fail this check, and any subsequent interactions, including the one that extracts coltan, are ignored.

**Comment by HbmMods** [comment]
Adding an exception for `IDrillInteraction`-type blocks seems to fix the issue.

**Comment by HbmMods** [comment]
Fixed in X4186.
