### ISSUE TITLE
So... I activated Horizons and Got this MASSIVE Comet impacting Earth!

### ISSUE THREAD

**Issue by Joey-Destroyah** [HbmMods/Hbm-s-Nuclear-Tech-GIT#54]
![2020-05-27_14 58 22](https://user-images.githubusercontent.com/62820134/83061225-a5dcc100-a02a-11ea-9afa-1d520602759b.png)

Then I got this....

![2020-05-27_15 00 10](https://user-images.githubusercontent.com/62820134/83061347-d3296f00-a02a-11ea-80f4-9d485149b693.png)

HBM, Are you trolling us?

**Comment by Nos74** [comment]
Man, you must've done something wrong! When i activated Horizons™ in my game, all it did was give me the unlocked hidden catalog + $30 on paypal.

**Comment by Joey-Destroyah** [comment]
I set the coordinates to the same as mine on the Satelite designator. I got the horizons acheivement, then I saw the massive comet.

**Comment by Nos74** [comment]
Must be a bug

**Comment by UFFR** [comment]
That "comet" has a name you know.

**Comment by Joey-Destroyah** [comment]
Tom?

**Comment by UFFR** [comment]
Yes. Maybe you should've checked what Gerald did before sending him up, activating him, and posting this.

**Comment by HbmMods** [comment]
Works as advertised.

**Comment by Joey-Destroyah** [comment]
I got him out of the creative inventory.
Seems like Tom isnt a good lad after all.

**Comment by Joey-Destroyah** [comment]
Why would you send Tom home if all he would bring is destruction?

**Comment by ShimmeringBlaze** [comment]
Maybe he never liked his home? Idk, I suppose it doesn't matter, since the mod is meant to destroy stuff

**Comment by Nos74** [comment]
The mayhem caused by his return is a necessary sacrifice
