### ISSUE TITLE
cant use magnetic extractor

### ISSUE THREAD

**Issue by pandaboypr** [HbmMods/Hbm-s-Nuclear-Tech-GIT#542]
so i was just playing with the mod and foud a dud so i looked it up on the wiki what i cud do with it. on the wiki it says i can exstract stuff from it so i tryed to use the magnetic extractor on it but i woudent work. how does this work and/or am i doing some thing wrong 

p.s sorry fore my bad english im dislectic

**Comment by burningwater202** [comment]
You need to have empty cells in your inventory as well so that the material the magnetic extractor is pulling out will have somewhere to go, give that a try and see if that helps!

**Comment by pandaboypr** [comment]
thx i worked
