### ISSUE TITLE
Ores are registered for many things that aren't ores

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#545]
V4191

Just making a note that I'm seeing things like "starmetal helmet ore" and "basic factory cluster ore", which dont' make any sense, clutter up NEI pretty heavily, and will probably lead to weird bugs down the road. It *should* be fine to delay on fixing this, but should probably tighten up the (presumably) ore registration code

**Comment by TheForge129** [comment]
4/1

**Comment by Vaern** [comment]
4/1 strikes again

**Comment by HbmMods** [comment]
Having an ore generate for literally every item in the game was this year's haha funny april fools feature. Generation can be turned off in the config, it will be disabled by default (as well as the ore variants being generated for the inventory) in the next version later today.

**Comment by thePalindrome** [comment]
Oh lol, and here I thought you just managed to do a bug. Carry on then
