### ISSUE TITLE
Asteroid and lunar mining ship stop landing after a while

### ISSUE THREAD

**Issue by Globalfirestorm10** [HbmMods/Hbm-s-Nuclear-Tech-GIT#548]
After returning two or four times, the asteroid and lunar mining ship don’t return. This happens in 1.7 and 1.12.2

**Comment by HbmMods** [comment]
The mining ships have been tested for several hours at a time, working just fine. Did you unload the chunks or leave the world before it stopped working? Or have you launched any new satellites?

**Comment by Globalfirestorm10** [comment]
The only two satellites I have are the surfacing mapping and death ray ones. I did spend quite a bit away from the chunk and did leave the world a few times

**Comment by Globalfirestorm10** [comment]
If that is the cause of the ship not returning, is it possible for the devs to fix it?

**Comment by solundev** [comment]
Please, ensure that the storage isn't full, tip: you can place double chests in each sides of the cargo to store the items

**Comment by Globalfirestorm10** [comment]
The storage was empty, I put everything in a chest, yet it never came back

**Comment by solundev** [comment]
restarted the world?

**Comment by Globalfirestorm10** [comment]
Yes

**Comment by solundev** [comment]
It may be an isolated error or not, i'm not sure of what's causing this, maybe try creating a backup and relaunch the soyuz for test.
i hope you find out how to solve it's issue

**Comment by Globalfirestorm10** [comment]
well, lookes like my world was kinda corrupted, I tested it (in another world), it did its work, ill see if there are any issues considering I just launched it
