### ISSUE TITLE
Substations only function for a small period of time after being placed

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#549]
Version 4193

So the substations don't seem to proxy power through... except for immediately after being placed (they'll stop a fairly random amount of time later). I only noticed when my fusion hall no longer seemed to be connected to the power grid. I can tell it's the substations since even connecting an energy storage block on the other side wouldn't yield anything until I broke and re-placed it.

**Comment by HbmMods** [comment]
Seems like the proxy blocks (those at the sideways connectors) didn't relay the new re-eval information. You might be able to work around this by extending any cable that connects to the substation to go under it so that the cable touches the bottom center (where the substation's core block is).

**Comment by HbmMods** [comment]
Should be fixed in X4200. I haven't tested the power nets on a server or through unloaded chunks yet, so if there's any remaining connection issues, please use the power net analysis tool to see if there's any broken connections that didn't properly re-attach themselves.

**Comment by thePalindrome** [comment]
Looks to be fixed to me, many thanks for the quick fix!
