### ISSUE TITLE
Not sure if this is a bug, but hoppers extract the ai chip in the landing pad for the mining ship.

### ISSUE THREAD

**Issue by Globalfirestorm10** [HbmMods/Hbm-s-Nuclear-Tech-GIT#552]
I recently set up an asteroid mining ship, and I noticed that whenever I put a hopper below it, it extracts the ai chip. Not sure if this is a bug or not, but would appreciate it being fixed if it is.

**Comment by TheForge129** [comment]
put the hoppers on the side where the holes are; items will still output
but the ai chip won't

**Comment by Globalfirestorm10** [comment]
Ok thanks
