### ISSUE TITLE
[Suggestion] Add more Siren Track

### ISSUE THREAD

**Issue by MCTF-Alpha-27** [HbmMods/Hbm-s-Nuclear-Tech-GIT#556]
Such as comprehensive nuclear strike alarm. It is useful for some maps and servers

**Comment by SoB1nary** [comment]
friendly reminder that suggestions are not valid issues

**Comment by Globalfirestorm10** [comment]
Yes, but it wouldn’t hurt too add them. Also I agree with you, we should add more

**Comment by ncr-t** [comment]
two things :
-Like sob1nary said, issues are not to suggest.
-There's already a strike alarm.

**Comment by MCTF-Alpha-27** [comment]
> 

Um, so where can I give me suggetions to this mod?

**Comment by MCTF-Alpha-27** [comment]
> two things : -Like sob1nary said, issues are not to suggest. -There's already a strike alarm.

Um, so where can I give advice on this mod?

**Comment by Vaern** [comment]
Suggestions aren't really being accepted atm, at least not in issues.
