### ISSUE TITLE
[BUG] blocks on structures and villages are blackened out on the top and sometimes on the sides

### ISSUE THREAD

**Issue by Globalfirestorm10** [HbmMods/Hbm-s-Nuclear-Tech-GIT#557]
Villages just have weird shadow glitches while  HBM structures’s top’s are sometimes blackened out. This happens with deco steel and other deco blocks.

**Comment by 7pheonix** [comment]
this is an issue with Connected textures. I believe it’s caused by optifine, so uninstalling that should prevent the bug from happening
probably won’t be fixed for a while since connected textures crushed bob’s nuts so hard while implementing it

**Comment by Globalfirestorm10** [comment]
Ill try, but hopefully he can fix it in about a years time. Imma keep this open so bob can see it.

**Comment by HbmMods** [comment]
Isn't some stuff generating with a light level of 0 a pretty ancient vanilla bug? I know it's a lot more noticeable on NTM structures but you also get it with stuff like caves and ravines.
