### ISSUE TITLE
[BUG] Gas Mask Attachable does not render correctly

### ISSUE THREAD

**Issue by Pessimismus** [HbmMods/Hbm-s-Nuclear-Tech-GIT#558]
The attachable gas mask does not render on the head of the player, at least when wearing the Advanced Alloy Helmet

![2022-04-06_20 17 52](https://user-images.githubusercontent.com/102322619/162041936-88c7141f-9cc2-403a-85a8-7a6548594e17.png)

**Comment by HbmMods** [comment]
Fixed in X4200.
