### ISSUE TITLE
[BUG] Makeshift Gas Mask Filter does not work in the Gas Mask Attachable

### ISSUE THREAD

**Issue by Pessimismus** [HbmMods/Hbm-s-Nuclear-Tech-GIT#560]
The Makeshift Gas Mask Filter does not protect against airborne particles (Asbestos, Coal Dust) when installed in the the Gas Mask Attachable. I don't know if this Problem only appears with the Makeshift Gas Mask Filter or with all filters installed in the attachable gas mask.

![Unbenannt](https://user-images.githubusercontent.com/102322619/162543011-bec2c1ee-ebb8-412b-b8b2-efad6a34e403.PNG)

**Comment by HbmMods** [comment]
Can't replicate this one, both the attachable masks and the makeshift filters seem to work. Are you by any chance on 1.12? I've seen some reports that any of the newer gas mask filters don't seem to work at all.

**Comment by Pessimismus** [comment]
Mh, no, I'm playing the 1.7.10 version (X4193), the problem appeared in multiplayer.
I try to replicate the issue in Singleplayer and will give you more information.

**Comment by Pessimismus** [comment]
I did a lot of testing* in Singleplayer and I realized the error was sitting in front of the screen (as often...).
Now I know: 
- only filters with protection against "Particulates" will help against [Asbestos]
- the term "Airbone Particles" does only protect against  [Coal Dust]

Please correct me if I'm wrong.
I still don't unterstand the "hfr_fibrosis" counter, but i think this issue can be closed.

*all testing was done with the Gas Mask Attachable on the Advanched Alloy Helmet in an instance with only NEI and NTM installed

**Comment by HbmMods** [comment]
Asbestos is a lot finer than coal dust, so you do need a more modern filter. Fibrosis is a stat caused by radon gas which can also be filtered by anything that protects against particulates.

**Comment by Pessimismus** [comment]
Thank you
