### ISSUE TITLE
Startup crash NTM X4193 #bug

### ISSUE THREAD

**Issue by classicalten46** [HbmMods/Hbm-s-Nuclear-Tech-GIT#566]
Sorry for my english but i will try to explain the bug as good as i can...
I used different  version of this mod for 1 year and now i downloaded this version (X4193) because i want to start a server... when i try to start the game, during the initialization, it crashes. The crash-report says something abount OLD API of the CoFH core that has been repacked but i'm not sure of what is the bug about... i hope you can tell me some suggestion because i want to play this modpack with the CoFH mods and yours too. Sorry for the disturb.

this is the crash report:
[crash-2022-04-10_10.51.03-client.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/8458613/crash-2022-04-10_10.51.03-client.txt)

**Comment by HbmMods** [comment]
You installed the 1.7 version of the mod on 1.12.
