### ISSUE TITLE
Meteorite blocks can replace bedrock blocks

### ISSUE THREAD

**Issue by luckybl0ck** [HbmMods/Hbm-s-Nuclear-Tech-GIT#567]
### Describe the bug

When a meteorite falls on the bedrock, bedrock blocks are replaced by meteorite blocks. 

Mod version - X4193.

![2022-04-10_14 54 39](https://user-images.githubusercontent.com/79654924/162616939-02301898-0e92-4ff1-a212-3dc7298753c4.png)

**Comment by HbmMods** [comment]
Fixed in X4214.
