### ISSUE TITLE
Using cable drum hides jetpack toggle notifs

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#570]
v 420 lol

Relatively simple, moderately small use case, but I can never recall if my jetpack is on or off, and while running cable, the "Jetpack On" and "Jetpack Off" tooltips won't display. It'd be nice if that appeared above it, but you do you :P

**Comment by HbmMods** [comment]
![2022-04-20_20 29 09](https://user-images.githubusercontent.com/16674258/164298455-7c9a6fd8-faa7-46e5-a1de-56f17ae52ec7.png)

A simple new thing that replaces all info texts, it will be configurable (due to the sheer amount of HUD elements many packs have) to be aligned to the top left, top right, left of the crosshair and right.

**Comment by thePalindrome** [comment]
Thoughts on doing something similar to AM2's `/amuicfg` system to allow arbitrary placement of the UI elements per client? I'd understand if that's not something you'd want at this particular moment due to the effort involved, but worth thinking about

**Comment by HbmMods** [comment]
Perhaps some day I'll figure out how to use forge's ingame config menu that absolutely no mod in 1.7 uses. The couple configurations that it has now should at least be enough for the initial release.

**Comment by thePalindrome** [comment]
There are a small handful of mods that have at least partial support for it, but the system itself wasn't really finished by this point in time. the /amuicfg command was in the 1.7 version of AM2, so that might be worth looking at

**Comment by HbmMods** [comment]
The little HUD screen should now be in X4214, I'll keep the issue open until I finished a more sensible config for position and scale of the info display.
