### ISSUE TITLE
The large number of batteries caused the grid to fail

### ISSUE THREAD

**Issue by sun00055555** [HbmMods/Hbm-s-Nuclear-Tech-GIT#578]
Version：1.0.27_X4200
When I place multiple batteries in the same network, the batteries cannot power the machine (even though they are connected), the number of batteries decreases and goes back to normal.
I wonder why. I can't use enough batteries to power a large particle accelerator.

**Comment by HbmMods** [comment]
Are you running your batteries in buffered or in output mode? Buffered mode can cause issues because batteries will end up sharing a large amount of the power between each other instead of the accelerator.

**Comment by sun00055555** [comment]
All my batteries are in buffered mode, so that's what's causing this problem?

**Comment by HbmMods** [comment]
From the perspective of a single battery, it doesn't just have to send power to the accelerator but also to every other battery in the power grid. The issue becomes worse as the batteries discharge, as the share of energy that every machine in the power grid gets is proportional to how much of that machine's buffer is empty.

If you want to use your batteries to just power something, use output mode. If that's not an option, you might be able to decrease the amount of energy being sent to batteries by using diodes and limiting the flow between them.

**Comment by sun00055555** [comment]
Thank you. In addition, can you add the function of displaying the power supply of the particle accelerator power port, just like displaying the battery

**Comment by HbmMods** [comment]
Accelerator plugs have charge overlays now.
