### ISSUE TITLE
crash when I put ONLY 2 gold RTG pellets in the big RTG machine (the one with the radiolysis chamber)

### ISSUE THREAD

**Issue by mithrill5226** [HbmMods/Hbm-s-Nuclear-Tech-GIT#583]
hbm version:X4200
When I put ONLY 2 gold-198 RTG pellets in the big RTG (the one with the radiolysis chamber) the game will crash but
if there are any other RTG pellets (Not gold-198 because that will crash the game) in the big RTG machine (the one with the radiolysis chamber) the game wont crash

crash log:
[crash-2022-04-24_14.44.27-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/8549236/crash-2022-04-24_14.44.27-server.txt)

**Comment by HbmMods** [comment]
Fixed in X4214.
