### ISSUE TITLE
nether portal effect on the screen isnt transparent-ish

### ISSUE THREAD

**Issue by WhatDoIUseAsAName** [HbmMods/Hbm-s-Nuclear-Tech-GIT#588]
so i have no way to explain it but, at X4200 (and before) the portal effect slowly builds up in opacity
X4214 and X4215 however its just, there. like no transparency and looks solid , this also happens with clearing a nausea effect
ive taken screenshots of before and after updates, https://imgur.com/a/1gNvRys
also im unsure if this is a bug or a mod conflict so if need be, i can provide the mods im using

**Comment by HbmMods** [comment]
Most likely due to the changes in how the ash "sand storm" effect works now, looks like once again in an attempt to fix it, it broke even harder.

**Comment by HbmMods** [comment]
Fixed in X4228.
