### ISSUE TITLE
You need a shredder to get a shredder

### ISSUE THREAD

**Issue by TheForge129** [HbmMods/Hbm-s-Nuclear-Tech-GIT#59]
Basically, you need red copper (which you can't get without a shredder)
i dont know if im doing it wrong, but if i am, please tell me :/

**Comment by UFFR** [comment]
What? You get Red Copper from the Blast Furnace.

**Comment by Nos74** [comment]
NEI has handy little arrows at each side that show alternate recipes for what you're trying to make

**Comment by TheForge129** [comment]
ok fuck sorry

**Comment by Nos74** [comment]
![otisgod](https://user-images.githubusercontent.com/49816198/85084815-48acd900-b1ac-11ea-83cb-1cd548b8754d.png)

**Comment by TheForge129** [comment]
hang on...
you still need copper dust, right?
if so, than youre still fucked

**Comment by Nos74** [comment]
Copper ingots and redstone in a blast furnace is literally all you need

**Comment by TheForge129** [comment]
im a   D u m b a s s !

**Comment by rryan-revived** [comment]
agreed

**Comment by HbmMods** [comment]
bruh moment
