### ISSUE TITLE
Deuterium extraction tower tooltip input says heavy water and output is always blank

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#590]
Version 4215

The hover text now lists the amount of heavy water in the input tank of the tower (which is 0), and lists the heavy water in the output as also 0

**Comment by HbmMods** [comment]
Is it just the tower or the compact extractor too? The last display issue was a confirmed fix tested on the compact extractors, and those use the same tile entity so I assumed it would work.

**Comment by HbmMods** [comment]
Nvm the heavy water tank for the tower had the wrong index causing the display to break, should be fixed now.

**Comment by thePalindrome** [comment]
Think that'll fix the output text always being 0, too?

And yes, I managed to forget I filed that a few days ago XD

**Comment by HbmMods** [comment]
Yeah, both fluid tanks have the index 0 which means that both the water and heavy water tanks are being synchronized to the same "slot", while the slot that the heavy water is supposed to go to never receives any info from the server, making it stay empty.

**Comment by HbmMods** [comment]
Fixed in X4228.
