### ISSUE TITLE
[Visual bug] Custom nuke drop upgrade causes custom nuke to go invisible when detonated

### ISSUE THREAD

**Issue by mithrill5226** [HbmMods/Hbm-s-Nuclear-Tech-GIT#591]
### Describe the bug

The custom nuke entity goes invisible

the bug works with ntm with no other mods

https://user-images.githubusercontent.com/104295973/165695773-4e601450-27e2-4efd-b795-b4c7372bb166.mp4

version:1.0.27_X4215

**Comment by HbmMods** [comment]
Fixed in X4228.
