### ISSUE TITLE
Cooling tower emiting crazy amounts of steam

### ISSUE THREAD

**Issue by Someone835** [HbmMods/Hbm-s-Nuclear-Tech-GIT#598]
Mod Version: X4215  
Minecraft version: forge 1.7.10
When i connect the low pressure steam duct to the cooling tower the tower starts emiting large amounts of smoke/steam(looks like a giant smoke bomb went off rough radius: 100-150 blocks(might not be accurate) ) it lowers fps significantly (edit: i tried disconnecting  the ducts but it wont stop)

**Comment by 7pheonix** [comment]
What other mods are you using?

**Comment by Someone835** [comment]
Codechickencore, MCheil, NotEnoughItems, codechickenlib, im not sure if optifine is a mod

**Comment by Someone835** [comment]
Can I disable the smoke somehow while the issue is being resolved?

**Comment by HbmMods** [comment]
With release X4228, setting particles to minimal fully removes the steam effect on the cooling towers. I haven't been able to recreate the issue where the steam lingers on the ground, but I assume it's some mod turning off the noclip on the particles, causing them to get stuck inside of the tower.
