### ISSUE TITLE
Unable to Compile mod source

### ISSUE THREAD

**Issue by Weltkaiser** [HbmMods/Hbm-s-Nuclear-Tech-GIT#6]
Hi there.
I've been tried to compile the mod source into a .jar, but it seems to not work, in the creative tab, I actually have a iron pickaxes images on the tabs, and they are empty, here my logs of gradlew :

> C:\Users\Nyzoka>set JAVA_HOME="C:\Java\jdk1.8.0_161"
> 
> C:\Users\Nyzoka>cd Desktop\forge-1.7.10-10.13.4.1614-1.7.10-src
> 
> C:\Users\Nyzoka\Desktop\forge-1.7.10-10.13.4.1614-1.7.10-src>gradlew setupDecompWorkspace
> ****************************
>  Powered By MCP:
>  http://modcoderpack.com/
>  Searge, ProfMobius, Fesh0r,
>  R4wk, ZeuX, IngisKahn, bspkrs
>  MCP Data version : unknown
> ****************************
> :extractMcpData
> :getVersionJson
> :extractUserDev
> :genSrgs SKIPPED
> :extractNatives
> :getAssetsIndex
> :getAssets
> :makeStart
> [ant:javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
> [ant:javac] 1 warning
> :downloadMcpTools SKIPPED
> :downloadClient SKIPPED
> :downloadServer SKIPPED
> :mergeJars SKIPPED
> :deobfuscateJar SKIPPED
> :decompile SKIPPED
> :processSources SKIPPED
> :remapJar SKIPPED
> :extractMinecraftSrc SKIPPED
> :recompMinecraft SKIPPED
> :repackMinecraft SKIPPED
> :setupDecompWorkspace
> 
> BUILD SUCCESSFUL
> 
> Total time: 1 mins 33.982 secs
> C:\Users\Nyzoka\Desktop\forge-1.7.10-10.13.4.1614-1.7.10-src>gradlew eclipse
> ****************************
>  Powered By MCP:
>  http://modcoderpack.com/
>  Searge, ProfMobius, Fesh0r,
>  R4wk, ZeuX, IngisKahn, bspkrs
>  MCP Data version : unknown
> ****************************
> :eclipseClasspath
> Download https://libraries.minecraft.net/net/minecraft/launchwrapper/1.12/launchwrapper-1.12-sources.jar
> Download http://repo1.maven.org/maven2/org/ow2/asm/asm-debug-all/5.0.3/asm-debug-all-5.0.3-sources.jar
> Download http://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3-sources.jar
> Download http://repo1.maven.org/maven2/com/typesafe/config/1.2.1/config-1.2.1-sources.jar
> Download http://repo1.maven.org/maven2/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0-sources.jar
> Download http://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1-sources.jar
> Download http://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2-sources.jar
> Download http://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2-sources.jar
> Download http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1-sources.jar
> Download http://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1-sources.jar
> Download http://repo1.maven.org/maven2/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5-sources.jar
> Download http://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1-sources.jar
> Download http://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3-sources.jar
> Download http://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3-sources.jar
> Download http://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2-sources.jar
> Download http://repo1.maven.org/maven2/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3-sources.jar
> Download https://libraries.minecraft.net/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2-sources.jar
> Download https://libraries.minecraft.net/com/paulscode/codecjorbis/20101023/codecjorbis-20101023-sources.jar
> Download https://libraries.minecraft.net/com/paulscode/codecwav/20101023/codecwav-20101023-sources.jar
> Download https://libraries.minecraft.net/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123-sources.jar
> Download https://libraries.minecraft.net/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824-sources.jar
> Download https://libraries.minecraft.net/com/paulscode/soundsystem/20120107/soundsystem-20120107-sources.jar
> Download http://repo1.maven.org/maven2/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final-sources.jar
> Download http://repo1.maven.org/maven2/com/google/guava/guava/17.0/guava-17.0-sources.jar
> Download http://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2-sources.jar
> Download http://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4-sources.jar
> Download http://repo1.maven.org/maven2/commons-codec/commons-codec/1.9/commons-codec-1.9-sources.jar
> Download http://repo1.maven.org/maven2/net/java/jinput/jinput/2.0.5/jinput-2.0.5-sources.jar
> Download http://repo1.maven.org/maven2/net/java/jutils/jutils/1.0.0/jutils-1.0.0-sources.jar
> Download http://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.4/gson-2.2.4-sources.jar
> Download https://libraries.minecraft.net/com/mojang/authlib/1.5.16/authlib-1.5.16-sources.jar
> Download http://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9-sources.jar
> Download http://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9-sources.jar
> Download http://repo1.maven.org/maven2/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1-sources.jar
> Download http://repo1.maven.org/maven2/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1-sources.jar
> Download http://repo1.maven.org/maven2/org/scala-lang/scala-actors/2.11.0/scala-actors-2.11.0-sources.jar
> Download http://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2-sources.jar
> Download http://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1-sources.jar
> :eclipseJdt
> :eclipseProject
> :eclipse
> 
> BUILD SUCCESSFUL
> 
> Total time: 49.127 secs
> C:\Users\Nyzoka\Desktop\forge-1.7.10-10.13.4.1614-1.7.10-src>cd ..
> 
> C:\Users\Nyzoka\Desktop>cd saveforge
> 
> C:\Users\Nyzoka\Desktop\saveforge>gradlew build
> ****************************
>  Powered By MCP:
>  http://modcoderpack.com/
>  Searge, ProfMobius, Fesh0r,
>  R4wk, ZeuX, IngisKahn, bspkrs
>  MCP Data version : unknown
> ****************************
> :compileApiJava UP-TO-DATE
> :processApiResources UP-TO-DATE
> :apiClasses UP-TO-DATE
> :sourceMainJava
> :compileJava
> warning: [options] bootstrap class path not set in conjunction with -source 1.6
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 1 warning
> :processResources
> :classes
> :jar
> :compileTestJava UP-TO-DATE
> :processTestResources UP-TO-DATE
> :testClasses UP-TO-DATE
> :test UP-TO-DATE
> :extractMcpData UP-TO-DATE
> :getVersionJson
> :extractUserDev UP-TO-DATE
> :genSrgs SKIPPED
> :reobf
> :assemble
> :check UP-TO-DATE
> :build
> 
> BUILD SUCCESSFUL
> 
> Total time: 1 mins 26.081 secs
> C:\Users\Nyzoka\Desktop\saveforge

**Comment by GrTaiyaki** [comment]
Have you copied the assets folder into the jar?

**Comment by HbmMods** [comment]
@GrTaiyaki That can't be the problem, without the assets, the game would actually crash.
@KevinLimbes This is an issue that has been reported by a few people lately, I can not explain how the mod could possibly compile and be playable but without any registered items. Could you send me the faulty jar? I would like to take a look at it, maybe I can figure out what's going on.

**Comment by GrTaiyaki** [comment]
Oh i understand
By the way the mod works for me by extracting the jar into a folder in the mods folder,deleting META-INF and copying the assets folder there
