### ISSUE TITLE
a conflict with DragonAPI in 1.7.10

### ISSUE THREAD

**Issue by iamsoNewBee** [HbmMods/Hbm-s-Nuclear-Tech-GIT#604]
When hbm and DragonAPI  are added with a 
third mod(any mods else),this bug is triggered.

In this case,if i wear a helmet which gives a 'filter effect"(such as a Fire Proximity Helmet，a Gas Mask ,or even a Pumpkin...), i will see nothing except the effect.

![DG%~YMPH`@@_U9R M21~(FJ](https://user-images.githubusercontent.com/98573273/168304576-6bea48d9-04f5-4166-9a80-0c9fc8aef68a.png)
![M PSKZ1%% 7ML~1)ZVPVH2Q](https://user-images.githubusercontent.com/98573273/168304582-e598549f-0d7e-4bc2-a6eb-759e67dd4be3.png)
![UIS`YSH71WSDI9QDCSZZJ4U](https://user-images.githubusercontent.com/98573273/168304588-77840cd0-9382-4e18-ad67-41bc19bfc5cf.png)
![R0CWDO{IKYS36 })F@FY`4R](https://user-images.githubusercontent.com/98573273/168304590-ce7e9d72-b287-44c5-ac76-f7bcb8efb6c2.png)

PS：Only hbm and DragonAPI wont lead to this. **when hbm and DragonAPI  are added with a 
third mod(any mods else),this bug is triggered.**

**Comment by iamsoNewBee** [comment]
More pictures 

![M PSKZ1%% 7ML~1)ZVPVH2Q](https://user-images.githubusercontent.com/98573273/168304963-bb954668-f7fc-4f00-bc55-075bdc0eca21.png)

**Comment by iamsoNewBee** [comment]
![Y_G82WIVH B77M 46N12DTP](https://user-images.githubusercontent.com/98573273/168305375-94132f55-ced4-4c6f-bad3-4670f8f47acb.png)

**Comment by HbmMods** [comment]
Are pumpkins still affected when NTM is removed? What version of the mod are you using?

**Comment by iamsoNewBee** [comment]
> Are pumpkins still affected when NTM is removed? What version of the mod are you using?


Good question...When HBM is removed pumpkins still affected..Maybe there is another mod conflicting with DragonAPI..??

However, a musk in another mod (EnviroMine) is not affected by this conflict. Would u like to do sth to just aviod this？

<img width="638" alt="image" src="https://user-images.githubusercontent.com/98573273/168422711-e3cc7ad5-1a91-4d30-9acc-e411c548e20c.png">

**Comment by HbmMods** [comment]
Wait so if you have a bunch of other mods installed, what makes you think that it's caused by DragonAPI?

**Comment by IAmSoNewB** [comment]
> Wait so if you have a bunch of other mods installed, what makes you think that it's caused by DragonAPI?

I used to check my mods list and everything returns to normal when i removed DragonAPI..
(I don't have a computer on hand now.maybe I will find out the third conflicted mod days later..

**Comment by ghost** [comment]
It is likely to be some weird problem due to dragon api I guess. I used to install DragonApi for Condensed Ores, and the problem turned out to be worse in my case as I could see nothing else but the huds even when I did not have any helmet or potion effects that could give visual effects like these. Also, this occured randomly at the very beginning somehow, and it seriously deterioated when I added more mods (I can not recall which) into my pack. I do not think the problem has very much to do with ntm though, so I suppose we are to let Reika do the fixes if he/she can.

**Comment by ghost** [comment]
Maybe I can try reproducing the bug later in the days and get more information on the problem to actually specify the problem more clearly for possible fixes.

**Comment by IAmSoNewB** [comment]
> It is likely to be some weird problem due to dragon api I guess. I used to install DragonApi for Condensed Ores, and the problem turned out to be worse in my case as I could see nothing else but the huds even when I did not have any helmet or potion effects that could give visual effects like these. Also, this occured randomly at the very beginning somehow, and it seriously deterioated when I added more mods (I can not recall which) into my pack. I do not think the problem has very much to do with ntm though, so I suppose we are to let Reika do the fixes if he/she can.

is Dragonair still updating?

**Comment by ghost** [comment]
> 

It is possible that the api mod is still being updated by reika, as it was last updated on Cursedforge on Dec 21, 2021.
Reika seems to update it every few months or so. IDK XD

**Comment by HbmMods** [comment]
The initial issue i can probably fix, it's just a matter of turning semi-transparent texture support back on which should actually be the default for HUD.

**Comment by HbmMods** [comment]
Most likely fixed in X4242, I'll leave the issue open until we have confirmation because I can't test it myself.

**Comment by IAmSoNewB** [comment]
> Most likely fixed in X4242, I'll leave the issue open until we have confirmation because I can't test it myself.

u make it :)
