### ISSUE TITLE
Speed upgrade for normal Centrifuge

### ISSUE THREAD

**Issue by MCNaOtlichnoYT** [HbmMods/Hbm-s-Nuclear-Tech-GIT#606]
Ore processing is in most cases Acidizer->Centrifuge->Furnace
Acidizer can be upgraded with Speed III and Overdrive III
A fast furnace is Tungsten crate with DFC emitter or RTG furnace with Polonium, Gold-198 or Lead-209
But centrifuges can't be overclocked, the only way for fast processing is multiple centrifuges.
Can you make them support at least speed upgrades?

**Comment by Antineutrino-4444** [comment]
Here is "Issues", not "Suggestions".

**Comment by iamsoNewBee** [comment]
> Here is "Issues", not "Suggestions".

but "enhancement"is avaliable here.....
