### ISSUE TITLE
[suggestion]

### ISSUE THREAD

**Issue by Slawa8154** [HbmMods/Hbm-s-Nuclear-Tech-GIT#608]
Sorry, but I don't know where to write about proposals. Add thermobaric weapons, or as they are also called (volumetric bomb). I think this is a good idea.

**Comment by SoB1nary** [comment]
suggestions are not allowed in here, period.

**Comment by Slawa8154** [comment]
You can give a link for ideas about the mod. I will be very grateful.

**Comment by ncr-t** [comment]
There are none.
