### ISSUE TITLE
download problem: cant find build/libs or it is unclear what or where that is

### ISSUE THREAD

**Issue by redshadow3** [HbmMods/Hbm-s-Nuclear-Tech-GIT#611]
im trying to install the HBM mod and i cant find build/libs i cant find build but its not a file, a video on how to install that might be helpful cos either im an idiot or there actually isnt a build library on mine

**Comment by redshadow3** [comment]
ik im commenting under my own but please update to 1.8 cos i cant play normally without using liquid recipes and nei doesnt allow that, it gives you some %'s for every machine which i dont understand where those came from, basically nei doesnt support modded recipes at all

**Comment by SoB1nary** [comment]
i'm sorry, what?
are you trying to build the mod from source?
also, could you screenshot your funky %s problem?

**Comment by HbmMods** [comment]
If you want to download the mod, simply go to [the releases page](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/releases/tag/1.0.27X4242) and click on the JAR file that is listed under "Assets".

> but please update to 1.8

There once was a port for 1.8.9 but it was discontinued about 5 years ago and I have no intentions of porting the mod.

> i cant play normally without using liquid recipes and nei doesnt allow that, it gives you some %'s for every machine which i dont understand where those came from

what does that even mean

> basically nei doesnt support modded recipes at all

Of course it does - the vast majority of machines in the mod have custom recipe handling, only a few very simple ones don't (like "cooling tower makes LDS into water" or "the schrabidium transmutator makes schrabidium").

**Comment by Shibva** [comment]
oh, I think I know whats going on here. I think it might have todo with that fuckup that Forge did to old assets 
(the one where where it now cant download all the library and stuff)

I think there's something on the front page about this; and if not, drill (as far as I recall from my own memory) or the others here should have the needed assets

**Comment by redshadow3** [comment]
I can't give a screenshot but basically when i clicked on a machine in NEI it just showed like
(machine name) - %63.7
something like that except machine name was replaced with a machine's name and the %'s would be seemingly random

**Comment by redshadow3** [comment]
Also are you saying that the HBM mod is both for 1.7 and 1.8? beacause it only work's on 1.7 for me

**Comment by ncr-t** [comment]
it’s only for 1.7.10

**Comment by redshadow3** [comment]
![2022-07-18_14 37 31](https://user-images.githubusercontent.com/106045016/179512797-24b35f68-66b1-4f62-aa13-100970e57aa4.png)
%'s problem this appear's everytime i try to press on a machine no matter what key im using
(this one was attempted on the blast furnace but it happen's with every machine)

crafting in the workbench work's for the recipe's but anything about the machines just show's this

**Comment by Shibva** [comment]
-_-, have you tried clicking on the arrows on top?

and considered turning off Profiling Recipies?

**Comment by redshadow3** [comment]
> -_-, have you tried clicking on the arrows on top?
> 
> and considered turning off Profiling Recipies?

ill try to find a setting for profiling recipies and the arrow on top just changes to the same thing with a different name

edit: turning off profiling recipies causes the %'s to be removed but the usage of the item does not appear
