### ISSUE TITLE
Desert Atom Generation Issue

### ISSUE THREAD

**Issue by realShaiw** [HbmMods/Hbm-s-Nuclear-Tech-GIT#614]
Hello, a quick report, since the Gas Centrifuge has changed it's size making it 4 blocks tall, it's unable to spawn in the meltdown room upstairs in the Desert Atom structure. 
![2022-05-23_17 31 17](https://user-images.githubusercontent.com/92318003/169857410-23c3b9f6-cde6-4ac9-b73a-4f149882b166.png)

**Comment by HbmMods** [comment]
I'm pretty sure those were regular item centrifuges, it's most likely because the centrifuges now use the updated multiblock system and their metadata no longer matches what's required for them to exist. Should be easy enough to fix.

**Comment by realShaiw** [comment]
> I'm pretty sure those were regular item centrifuges, it's most likely because the centrifuges now use the updated multiblock system and their metadata no longer matches what's required for them to exist. Should be easy enough to fix.

Thanks, keep up the good work!
