### ISSUE TITLE
Euphenium armor makes breaking sound on any damage

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#625]
4251

Taking damage from any source (suffocating, being on fire, being attacked by a mob, or standing in fire) causes it to rapidly make the armor breaking sound except louder, due to it being played four times

**Comment by HbmMods** [comment]
Technically a feature but I can see what you mean. I've added a cooldown of half a second between sounds, and reduced the volume from an ear-piercing 5 to 0.5. Should also apply to the DNT nano suit which has the same sound.

**Comment by HbmMods** [comment]
Fixed in X4263.

**Comment by thePalindrome** [comment]
I don't quite get how it's a "feature" that the armor spams sound at you, since it does nothing to the player character but makes the player themselves unable to really hear what's going on due to either dealing with IRL sonic damage or turning down the game audio.

**Comment by HbmMods** [comment]
The sound itself is a feature, I often found myself not even realizing that I was getting attacked without it, but the entire "blowing your eardrums out" part was an unfortunate side effect of some things dealing damage per tick and therefore playing 20 sounds a second.
