### ISSUE TITLE
Stacking enabled in automatic crafting tables making certain recipes impossible

### ISSUE THREAD

**Issue by stinkytoot200** [HbmMods/Hbm-s-Nuclear-Tech-GIT#633]
Unlike the default crafting table, stacking is enabled in the automatic crafting table making certain recipes (such as nuclear waste into waste blocks) impossible when using conveyor belts or other methods of transporting items that dont involve manually placing them
![image](https://user-images.githubusercontent.com/86577879/174459116-ca05d169-c229-422d-b2f2-3965642480a6.png)

**Comment by stinkytoot200** [comment]
well not exaclty "impossible" but extremely inconvenient because sometimes it is difficult to fill in all the other spaces with full stacks

**Comment by HbmMods** [comment]
That's actually a bug with the conveyors, it works fine if you use hoppers. The IO is defined in a way where it always tries to fill the slot with the smallest amount of ingredients (similar to shredders), it's the inserters that have an issue implementing the IO standard.

**Comment by HbmMods** [comment]
The IO *should* be fixed for the conveyor inserters in the most recent version. I'm leaving the issue open for now since there might be some cases that haven't been accounted for.
