### ISSUE TITLE
Vein miner ability does not work on redstone ore

### ISSUE THREAD

**Issue by MCNaOtlichnoYT** [HbmMods/Hbm-s-Nuclear-Tech-GIT#638]
Tools with vein miner ability (like the advanced alloy ones) do not 'vein mine' redstone ore. When it is hit, it turns to Lit redstone ore. And the tool vein mines only the lit blocks. Can you make veinminer ability work with both variants of redstone ore?

**Comment by HbmMods** [comment]
Should be fixed in the latest release.
