### ISSUE TITLE
[Informant] PSA: slot configured belts are the key to automation

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#639]
Ive seen the belts are being worked on.  They could be the means for finally automating the machines with template management systems

One goal for some part of the automators of the modbase know how difficult it can be to autocraft using mods like AE2 but unable to swap templates out, but there is a way; I was able todo it in the 12.2 fork

In order for one to be able to efficiently automate the template machines, you will need a method for extracting and inserting items **based on slot**, Intigrated Tunnels (an ID addon) is a mod that adds this and the ability to control it with redstone. Because of this I Was able to be the first todo so on the 1.12..2 fork

The same could have been done if it wasn't for the fact that the Int-Dynamics series started at 1.8; but if your new belts could add some functionality for controlling what slots it would extract from then this could work; same goes for any other mod in 1,7.10 that is able todo the same with precise slot extraction

that is all, OH and just to give you a heads up the game is starting to become unstable in older versions for some reason. A 1.7.10 modpack group have made an announcement about more people having graphical issues with the game and is with integrated graphics cards. 

because this is an invalid post, this will be closed at one

**Comment by Vaern** [comment]
There's several issues with this.

If you knew this post was invalid, then _don't_ make it. That defeats the whole point.

AE2 autocrafting isn't difficult, you just have to plan things out. It can be very powerful and flexible depending on your setup.

Older versions don't just magically become unstable; great thing about software is that code doesn't disintegrate like a VCR tape would. Stop pushing for newer versions, there's already a 1.18 port and there's no point in annoying people over it.

**Comment by Shibva** [comment]
I wasent trying to push for a port, I was just trying to let him know that....


wait, there's a 1.18 port going on?

**Comment by Vaern** [comment]
Bob has already heard plenty about how 1.7.10 is an older version, and saying it's unstable is just wrong

**Comment by Shibva** [comment]
if I had to take a guess ,the reason why its suddenly doing this might be because of the new update

Minecraft DOES uese the same asset folder after all so I wonder if that might have anything todo it

but thanks for the information

and I dint know about the 18.2 fork; you have made my day. thankyou kind stranger

**Comment by Vaern** [comment]
New updates can't really retroactively affect older versions for a game like Minecraft, so I doubt that
