### ISSUE TITLE
How to ban the recipe in the template folder?

### ISSUE THREAD

**Issue by sdddddf80** [HbmMods/Hbm-s-Nuclear-Tech-GIT#642]
I try to delete the recipe in the hbm template.txt,  but it doesn't work.I remember there is a way to ban recipe in the template folder by changing the config files, but I can't find it now. Has it been removed?

**Comment by HbmMods** [comment]
There used to be a config for blacklisting, but that was removed in favor of the proper recipe config file. Make sure that you rename `hbmTemplate.json` to `hbmAssembler.json` so the changed version is used.
