### ISSUE TITLE
Unlimited bullets by enchanting firearms.

### ISSUE THREAD

**Issue by LSK-LW** [HbmMods/Hbm-s-Nuclear-Tech-GIT#645]
![20220627184825](https://user-images.githubusercontent.com/12579533/175924917-ce751d0b-5c57-48a9-be8a-dd65999ecde1.png)
After using the infinite enchanting book to enchant, the bullets of some firearms are infinite.

**Comment by ncr-t** [comment]
it is an intended and hardcoded feature of the mod
