### ISSUE TITLE
energy going into the negatives when pulling power from machines

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#646]
### Describe the bug

im not exactly sure but when I was using the FEnSU and having it set on the buffer or even extract, it causes the machines connected to it to go into the negative values, resulting in me either having to break it or power it up back into the positive

the energy that is pulled into storage does not go up so that's a good thing. The only way to circumvent this at the moment is to use diodes

**Comment by ncr-t** [comment]
Were you using buffer mode ? If so, please read the notice on the children lock.

**Comment by Shibva** [comment]
I already have; and tbh it explains a lot

although like I said its doing it when its in extraction mode as well

**Comment by 7pheonix** [comment]
The FEnSU has caused reoccurring problems with the energy net and whenever it seems like it’s fixed, it never is, so Bob is trying his best to fix the thing.
> the only way to circumvent this is with the diodes

Then use the diodes - it’s literally their intended purpose, to give greater control over the energy net.

**Comment by HbmMods** [comment]
The FEnSU's transfer limit has been rewritten in the last release which should fix most issues relating to the power going all over the place due to overflowing.

**Comment by Shibva** [comment]
great
