### ISSUE TITLE
[minor bug] SILEX no longer renders FEL beam in block

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#648]
### Describe the bug

Tbh im not really sure if this a bug or just an optimization that was mode; either way here we are

from what I remember the FEL laser rendered inside the SILEX and it now doesn't seem to be doing that anymore, regardless of the beam type

**Comment by 7pheonix** [comment]
Very much known, and a rendering issue only
if we knew how to fix it we would but MC’s rendering engine is a fuck
Basically it only renders properly when one of the machines is loaded first, I can’t remember which

**Comment by HbmMods** [comment]
Actually managed to find a fix, although the beam *might* break some things when rendering in front of them, i don't think it'll be that big of a deal though.
