### ISSUE TITLE
some bugs from my alone survival 1.12.2

### ISSUE THREAD

**Issue by RaubtierMLGpro** [HbmMods/Hbm-s-Nuclear-Tech-GIT#652]
### blast furnase cant be feed with pipes and this is the only way to do star metal ingots
i try it with thermal expansion, applied energinstics. May be thats not a bug but this is not good idea to run with lava buckets

### particle aсcelerator uses same amount of energy with different coils
so i can build most smallest and use not too much of energy and dont spend space? Becouse then i build the big one it will use more energy

### RBMK is too laggy so the only way to use it - build it far away from your base and use chunk loaders
lag starts then i plase glass covers and normal covers and if rbmk is too large

### compatibility with biomes of planity
the structures are not spawns on biomes of this mod

thank you guys for updates for 1.12.2 i will post some of this issues then i see it. If my reports was helpfui please tell me

**Comment by Shibva** [comment]
This is the wrong place to post this, please go to the 1.12.2 github here for proper support https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/releases

the odds of getting support here are uncertain
