### ISSUE TITLE
funny belt ejector slots go BRRR

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#655]
### Describe the bug

seems like the slots for the belt ejector upgrades only work in one specific slot, easily to notice when the eject; speed upgrade only works in the second upgrade slot

**Comment by SoB1nary** [comment]
intentional

**Comment by Shibva** [comment]
it is?
why no indicaton thou?

**Comment by 7pheonix** [comment]
Do you by any chance have eyes?

**Comment by HbmMods** [comment]
![grafik](https://user-images.githubusercontent.com/16674258/176202703-916d22d4-a4c5-4c80-9309-e4490e08c9f5.png)

Mind the different shapes.

**Comment by Shibva** [comment]
._.

ok, to be fair, that is suttle of a difference. I dint even SEE that till ya pointed it out. if it had a red outline for being in the incorrect slot that would be easier to spot

**Comment by SoB1nary** [comment]
problem?

**Comment by SteamDoge9000** [comment]
https://tenor.com/view/troll-troll-face-meme-smile-smirk-gif-17259275

haha very funny, you probs had the same thing happen to you

**Comment by Shibva** [comment]
(stupid gif betrayed me)

Haha Verry funny, you probably had the same thing happen as well

**Comment by SoB1nary** [comment]
cry about it

**Comment by Shibva** [comment]
no u
