### ISSUE TITLE
FBP paticles causes breaks default water steam visual

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#657]
### Describe the bug

the name of the title should be self-explanatory but here's the breakdown

FBP is a mod that replaced the particles with cubic versions of themself, the mod works fine with others but it seems like it causes this issue because it doesn't give the particle the plain water has, and the mod itself prevents any other particle render from happening as a result

**Comment by Froooz** [comment]
That is clearly a problem from that mod, I guess if you want to use it then complaining to the person that made it would be a better idea, not really much that bob can do about even if he wanted to.
