### ISSUE TITLE
UI is abnormal after electric furnace installation and upgrade

### ISSUE THREAD

**Issue by sun00055555** [HbmMods/Hbm-s-Nuclear-Tech-GIT#661]
When I added the red machine upgrade to the furnace while it was running, there was an abnormal UI extension on the right side of the UI, and the machine did not work. It returned to normal after re-entering the world.
![2022-06-30_19 01 07](https://user-images.githubusercontent.com/96975176/176707592-52711e8b-64d8-4e1e-8ec3-efdad358a634.png)

**Comment by HbmMods** [comment]
That's a confirmed issue that has been fixed in the development version. You can fix it by removing the powder from the input slot, which resets the progress.

**Comment by Adam29Adam29** [comment]
Known, it will be fixed in next release

**Comment by sun00055555** [comment]
> 这是一个确定的问题，已经在开发版本中得到解决。您可以通过从输入槽中移除粉末来修复它，这将重置进度。

I also have a suggestion, can you add some quartz powder access, enhance the circuitry and the production of heating elements so that I often need to go to hell to dig quartz ore
Or to increase the output of quartz in the centrifuge formula, whether grinding or centrifugation really should not only have 2 quartz powder

**Comment by SoB1nary** [comment]
quartz is really common, so you don't even have to silktouch it. just veinmine, mate. 15 minutes and you should have like 4 stacks of it.
