### ISSUE TITLE
Greg turret crashes game if atempting to fire using the turret controler

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#668]
### Describe the bug

I was wondering if I would be able to use the turret facing at a target with my cursor and I found out it can, problem is that when I tried to fire it crashed my game

it was a ticking player crash
[crash-2022-07-07_14.17.47-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/9066358/crash-2022-07-07_14.17.47-server.txt)

**Comment by ncr-t** [comment]
are you using the black and purple controller ? if so, this item is deprecated

**Comment by Shibva** [comment]
oh, I was not aware of that.

closing issue
