### ISSUE TITLE
Conveyor ejector doesn't go the items to the right place

### ISSUE THREAD

**Issue by AlexMinecraft2012** [HbmMods/Hbm-s-Nuclear-Tech-GIT#669]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.
Conveyor ejector goes the items to the wrong place. It needs go to the left grid instead on the right

**Comment by HbmMods** [comment]
Left gird of what? What block did you connect it to?

**Comment by AlexMinecraft2012** [comment]
of the Conveyor ejector and I connect to the assembly machine

**Comment by Shibva** [comment]
um... maybe try giving some context of what you are doing and how you came across the issue, its difficult to understand what your trying to say

**Comment by HbmMods** [comment]
Confirmed issue from a few weeks back, things like assemblers would access items from the filter grid in addition to the buffer grid. Was resolved in the previous version.
