### ISSUE TITLE
This is bug or feature?🤨🤨

### ISSUE THREAD

**Issue by SannUlya** [HbmMods/Hbm-s-Nuclear-Tech-GIT#674]
I didn't find any recipe like this on NEI, are this is bug?. The version is 1.0.27_X4291.

![2022-07-11_18 11 08](https://user-images.githubusercontent.com/98253949/178252911-d437aaeb-3b81-4730-8641-970bf26bcdfb.png)

**Comment by anotherRandomPersonlol** [comment]
Probably a feature when u want to repair something idk

**Comment by ncr-t** [comment]
It’s a feature seen in Vanilla minecraft.

**Comment by HbmMods** [comment]
Indeed vanilla behavior, most tools with durability can be repaired this way.
