### ISSUE TITLE
git bash error

### ISSUE THREAD

**Issue by anotherRandomPersonlol** [HbmMods/Hbm-s-Nuclear-Tech-GIT#675]
$ ./gradlew build <-- i did command

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

pls help the file is installed on computer but i cant build it
its 1.7.10

image below

![image](https://user-images.githubusercontent.com/109078370/178256196-0bafb1a3-0cad-4893-9a89-296d362322e2.png)

also im not indo coding idk what is happening i just installed this and just did everything in order and this happened

**Comment by ncr-t** [comment]
Do you have OpenJDK8 installed ?

**Comment by anotherRandomPersonlol** [comment]
yes

**Comment by anotherRandomPersonlol** [comment]
but in a rar idk how to like activate it fully?

**Comment by ncr-t** [comment]
uncompress it

**Comment by ncr-t** [comment]
inside there should be a dot exe

**Comment by anotherRandomPersonlol** [comment]
how do u uncompress it

**Comment by anotherRandomPersonlol** [comment]
this?

![Zrzut ekranu 2022-07-11 135404](https://user-images.githubusercontent.com/109078370/178258628-cda222f3-4d06-4d59-a035-f175c026d21c.png)

**Comment by ncr-t** [comment]
you use 7zip or a similar program

**Comment by anotherRandomPersonlol** [comment]
where do i go now

![Zrzut ekranu 2022-07-11 135752](https://user-images.githubusercontent.com/109078370/178259155-d5094eca-1ede-4c18-a834-4a1e02cdd008.png)
w

**Comment by ncr-t** [comment]
idk google it I don’t use windows, search on how to install openjdk8 and that should tell you

**Comment by anotherRandomPersonlol** [comment]
F**k it im done im not even now trying i dont need this mod anymoore

**Comment by HbmMods** [comment]
`JAVA_HOME` is an environmental variable that has to point to your java install directory. Building the project isn't going to work without it.

> also im not indo coding idk

Assuming you're not actually going to make any changes, why not just download [yesterday's release?](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/releases/tag/1.0.27X4291) The .jar file is at the bottom.
