### ISSUE TITLE
A screwdriver to create a Key Imitation Kit can only be used once

### ISSUE THREAD

**Issue by KeTsarl** [HbmMods/Hbm-s-Nuclear-Tech-GIT#677]
After using a screwdriver, its durability decreases and it will no longer be able to be reused and it is necessary to create a new one.
![Скриншот 12-07-2022 152031](https://user-images.githubusercontent.com/109150286/178488411-48d12b56-fb02-4e19-ad91-485e3ed8a415.jpg)

**Comment by HbmMods** [comment]
Fixed in X4312.
