### ISSUE TITLE
Impact drill destroy the steel crate

### ISSUE THREAD

**Issue by SannUlya** [HbmMods/Hbm-s-Nuclear-Tech-GIT#678]
Version: HBM-NTM-.1.0.27_X4291.jar

Try to break steel crate using two of this mods: Silk touch and Fortune. You will got jerky magic.

![2022-07-13_04 07 58](https://user-images.githubusercontent.com/98253949/178596510-20485e5c-f3ef-46f1-a142-561ffa62eb6c.png)
Nothing magic.
![2022-07-13_04 08 27](https://user-images.githubusercontent.com/98253949/178596600-f49607cb-e076-4a6f-906d-18280d78b474.png)
Imagine how beautiful this, if you trying to mine quartz ore in nether beside of lava and use impact drill on silk touch mode. You forget change the mode and break the your steel crate [🗿](https://emojipedia.org/moai/).

![2022-07-13_04 08 49](https://user-images.githubusercontent.com/98253949/178596884-00a0011c-ea98-45e2-b7c7-a96fa80a4fce.png)
Now use fortune mode.

Just reported from myself. Just need to pull confirmation or maybe recommendation.

**Comment by HbmMods** [comment]
Fixed in X4327.
