### ISSUE TITLE
[bug] non-stabkables checker not preventing ntmContagion from applying to stackables

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#681]
### Describe the bug

its a funny thing how I came about this; so I was making a ritual to allow for the creation of Alexandrite (one that is jokingly expensive and needs a bit over 2mill LP; might double it again tbh) and I seemed to have done something unusual with the item placement. I had a block of bismuth a single one for a bit while handling asbestos and when I logging the items using /mt hand (CrafTweaker) I got this 
``<hbm:tile.block_bismuth>.withTag({ntmContagion: 1 as byte})``

not knowing that this was at the time (and only realizing its asbestos-related as I make this report) I looked at the open source and saw the note in regard to it only affecting non-stackables

it turns out it seems to do it to items that only have 1 item in the stack as well

so yeah, you might wanna look at that

(talk about an accidental discovery)

**Comment by HbmMods** [comment]
> `ntmContagion`

I'm afraid to say this but some items not stacking should be the least of your worries.

**Comment by Shibva** [comment]
yeah, im aware; I was just reporting something I saw and something it not applying right. I was in creative when this was happening, but me looking into it gave me some valuable info

trying to be a good semeritan

it was also taking place when I was in creative, progression wise

**Comment by Shibva** [comment]
though... while im thinking about this, is there a way to remove this contamination from the item?

**Comment by HbmMods** [comment]
I believe the radiolysis machine has a slot for decontaminating items using radiation (should be two slots above one another with a progress arrow).

**Comment by Shibva** [comment]
oh, so that's what that is. Heh, If I had wiki editing access id check to see if that's in there and add that.
