### ISSUE TITLE
Artillery turret bug?

### ISSUE THREAD

**Issue by Phillanor** [HbmMods/Hbm-s-Nuclear-Tech-GIT#686]
Hello, the recently added artillery turret, does not damage the player with a projectile, only with the "consequences of a projectile"
That is, ordinary projectiles from 1 to 3 (two safe and one HE) do not cause damage to the player, but they do damage to the vehicle (mod MCheli), but at the same time a nuclear projectile causes damage to the player (and then probably because of the mechanics of the shock wave of a nuclear explosion)
What's funny, the first time I tested it, everything worked.

**Comment by HbmMods** [comment]
Most likely an issue due to the way vanilla explosions do line-of-sight checks, a few weeks ago artillery shells and rockets got a new system where multiple LoS checks are done at a small offset to prevent tiny bumps in the terrain or even just the floor swallowing the entire blast.
