### ISSUE TITLE
Missing recipe for build fusion reactor

### ISSUE THREAD

**Issue by SannUlya** [HbmMods/Hbm-s-Nuclear-Tech-GIT#687]
Today I want to build fusion reactor for get some ionized particle. So I take my multiblock torch or whatever, then change it to fusion reactor. But when try to see the recipe of the fusion reactor control, I didn't find the recipe for make it.

![2022-07-20_10 01 54](https://user-images.githubusercontent.com/98253949/179887859-589d2fe6-200a-49a1-877a-f31d3818e3c1.png)

It didn't show any recipe when I click "R" on NEI.
![2022-07-20_10 02 03](https://user-images.githubusercontent.com/98253949/179888034-a7f14729-7aae-4f50-ac3b-e6c22626b7b0.png)

**Comment by AlexMinecraft2012** [comment]
This is an old fusion reactor.

**Comment by SannUlya** [comment]
> This is an old fusion reactor.

How to build new fusion reactor?

**Comment by SoB1nary** [comment]
https://ntm.fandom.com/wiki/Fusion_Reactor

**Comment by SannUlya** [comment]
> https://ntm.fandom.com/wiki/Fusion_Reactor

Thank you. I will try it
