### ISSUE TITLE
Conveyor inserters dont insert waste when waste is in stacks

### ISSUE THREAD

**Issue by stinkytoot200** [HbmMods/Hbm-s-Nuclear-Tech-GIT#689]
When the waste drum is full, and then extra waste accumulates in the conveyor inserter, if it's a stack of more than 1, it will not insert into the waste drum. It only inserts 1 at a time

https://user-images.githubusercontent.com/86577879/180491180-e6e08647-5528-4df0-9e43-15b7432dbcbb.mp4

**Comment by Shibva** [comment]
ok, I Was going to say something, but after watching the vid, that is valid. I can only assume the same issue goes for the actual waste drum that acts the same way in single item allowcation

**Comment by Shibva** [comment]
I can only assume that it goes in as a single piece for balance reasons

tbh, id let them stack; yet this could be kept the way it is if one were to wish to go through suffering (582 mode) but that's just my oppinion

**Comment by HbmMods** [comment]
Fixed in X4312.
