### ISSUE TITLE
are you going to add more doors?

### ISSUE THREAD

**Issue by Joey-Destroyah** [HbmMods/Hbm-s-Nuclear-Tech-GIT#69]

**Comment by HbmMods** [comment]
I recently got a new door model for a silo hatch [similar to this one](https://www.youtube.com/watch?v=j65XzcBLoKw), I'm planning on adding this in the upcoming version. Other than that, there's only vague plans for adding a few more doors but no models or planned release dates.

**Comment by Joey-Destroyah** [comment]
What about more of these doors? https://youtu.be/1wZPbjhd05Y?t=31

**Comment by Nos74** [comment]
https://youtu.be/m5VXEl0LYZk

**Comment by ShimmeringBlaze** [comment]
Perfect

**Comment by HbmMods** [comment]
Not sure why we'd need more doors like that since that's literally what we already have.

**Comment by Joey-Destroyah** [comment]
ok then. I think you should improvise on the door animations we currently have, but you do you.

**Comment by ShimmeringBlaze** [comment]
I don't see what's wrong with the current animations

**Comment by HbmMods** [comment]
I don't really see what's wrong with them

**Comment by Nos74** [comment]
here you go hbm https://youtu.be/oHyt7HR_Ixg

**Comment by Joey-Destroyah** [comment]
the real door looks like this.
![freegifmaker me_2gC56](https://user-images.githubusercontent.com/62820134/87467949-c49d1400-c5e6-11ea-970b-dd83b3445b64.gif)

**Comment by HbmMods** [comment]
Now we have to find someone who is willing to model and especially animate that little robot arm.

**Comment by Nos74** [comment]
![921765](https://user-images.githubusercontent.com/49816198/87467302-1f863980-c5ee-11ea-8aae-cbf8b9d3ad39.png)

**Comment by Joey-Destroyah** [comment]
your right about that. I was just reccomending something.

**Comment by Minecreep** [comment]
I could model that arm but I think it would be useless due to the door structure's size massively increasing. I could also make some more blast doors or whatever, but not sure what ppl and hbm want to see. Maybe suggest your ideas on discord, and maybe they will be approved.

>
