### ISSUE TITLE
Please reduce the fire rate of Artillery Turret in automatic mode

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#691]
(This is about an Enhancement.)

Greetings.
Recently I enjoyed the new artillery turrets.
However,I noticed that the turret always fires too many shells at one single target,which produces huge,deep holes on the map.
I hope that the turret can launch the next shell after the former one explode.Please reduce the fire rate of the turret in Long Range Automatic Mode.
Thank you! I always loved your Hbm mod and I hope it will get better and better!

(Btw,I can't wait to see the flak turret and mortar turret be completed,along with the "Fat.Ass"Tank that you mentioned before.)

**Comment by ghost** [comment]
I know that there are shells that don't break blocks which may ease the problem.However,what if the Greg locks on the mobs underground?And....if multi-guns fire at the same target,similar scenes may happen.

**Comment by HbmMods** [comment]
The rate of fire should be quite a bit lower for Artillery Mode just because of that, but I can lower it a bit further.

> Greg locks on the mobs underground

That shouldn't really happen since Greg's detector checks for targets to have sky access instead of the traditional line of sight. If it does happen it's definitely a bug.

**Comment by HbmMods** [comment]
The rate of fire in artillery mode was lowered by a good bit in X4312.
