### ISSUE TITLE
[Minor] chute logic should account for downward funneling 

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#692]
### Describe the bug
not realy a bug, more of an observation that I thought I should point out; though this is a minor thing and was most likely an oversight.

instead of putting just a bunch of words (for the bot to record) Ill also put an image to convey what im referring to

the chute does not seem to acknowledge conveyor inserters that are placed below it, and while render suggests that it would, it would instead eject outward in the direction that it would be supposedly facing.

![2022-07-23_15 11 10](https://user-images.githubusercontent.com/38770780/180619781-da1fcae9-343d-430c-b480-f90728f350d2.png)

**Comment by HbmMods** [comment]
Fixed in X4327.
