### ISSUE TITLE
Actual fix for the bolt action ammo thing

### ISSUE THREAD

**Issue by GrTaiyaki** [HbmMods/Hbm-s-Nuclear-Tech-GIT#7]
I think it's quite funny finding bugs in a bug fix,but i actually did
[GunBoltAction.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/1732793/GunBoltAction.txt)
Rename it to .java
To keep it short,you replaced only 1 of the 2 "lever_action_ammo" and the ammo still needs 12x74 buckshots to fire even if they are not needed

Actually i would try to build in real life a bolt action shotgun tho.
"surprises the enemy"

**Comment by HbmMods** [comment]
Not sure why you uploaded a fixed file when it's just one item field that needs to be replaced, but thank you nonetheless!
