### ISSUE TITLE
The "roof collapse" effect of fallout has some problems

### ISSUE THREAD

**Issue by sdddddf80** [HbmMods/Hbm-s-Nuclear-Tech-GIT#701]
It looks like that this effect also works on the last layer of bedrock, which means if you explode a nuke in a superflat world, the the last layer of bedrock will fall into the void, like this:
![2022-08-01_12 32 45](https://user-images.githubusercontent.com/53573250/182073863-766fc651-683b-4f0f-bc3b-18dd69b60f69.png)

**Comment by HbmMods** [comment]
Fixed in X4327.
