### ISSUE TITLE
~10000 barrels of nuclear waste crashed server

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#705]
I placed ~10000 barrels of nuclear waste, shot at them with a panzerschreck and the server crashed
Version is latest (X4312)
Crash log attached: https://drive.google.com/file/d/1j0zckAhSmhek-jOoSl8-3a5zhzMic_MT/view?usp=sharing (link because the report is too long)

**Comment by ncr-t** [comment]
considering you put down a few thousands barrel, it’s safe to say you made the server crash by your actions, as, it’s a huge amount of stuff to load
