### ISSUE TITLE
Nothing drops when breaking a Fractioning tower using a tool with Silk Touch or Fortune tool ability

### ISSUE THREAD

**Issue by Creeper-banner** [HbmMods/Hbm-s-Nuclear-Tech-GIT#707]
### Description

As the title, when I broke a Fractioning Tower using a Impact Drill with Silck Touch ability, nothing dropped. Then I tested other tools, and I found all tools with this ability and Fortune ability causes this issue, but vanilla enchantments doesn't cause this.
Mod version: X4312. I tested with no other mods installed.

(Sorry for my bad English :) )

**Comment by HbmMods** [comment]
Fixed in X4327.
