### ISSUE TITLE
custom recipe system can’t receive items from other mods

### ISSUE THREAD

**Issue by sdddddf80** [HbmMods/Hbm-s-Nuclear-Tech-GIT#712]
### Describe the bug

I can't let the custom recipe system use other mods' items, which makes it hard to combine hbm with a mod pack.

**Comment by TheForge129** [comment]
Can you send your custom recipe's JSON?

**Comment by sdddddf80** [comment]
![7080cb50317e739a](https://user-images.githubusercontent.com/53573250/184534777-cf414361-5220-46ff-82ea-8ce9f08e4564.png)

**Comment by TheForge129** [comment]
AE2's name in the ID handler is actually "appliedenergistics2", not the
much quicker and simpler ae2. I have no idea why this is the case, but
changing that should fix your issue
