### ISSUE TITLE
No way to load the chemical thrower

### ISSUE THREAD

**Issue by blinkor** [HbmMods/Hbm-s-Nuclear-Tech-GIT#719]
Not sure what type of fluid container or ammunition the chemical thrower accepts, but pressing R while having any fluid barrel in the inventory, hazardous fluid container, or right clicking a fluid barrel does not load the chemical thrower. I can still load the other weapons.

How do you properly load the chemical thrower?

**Comment by HbmMods** [comment]
Put it in a barrel with fluid, just like a jetpack.
