### ISSUE TITLE
Battery blocks have incorrect energy delta display when using IN-AND-OUT mode

### ISSUE THREAD

**Issue by Creeper-banner** [HbmMods/Hbm-s-Nuclear-Tech-GIT#720]
### Describe the bug

Whatever the real energy delta is, the display of the battery blocks using IN-AND-OUT mode is always +0HE/s. The display is correct when using another three modes.
HBM version: 1.0.27X4334

Edit: It only happens in a energy net with multiple battery blocks. If there is more than 3 battery blocks, the delta display will be around +0HE/s, and changing quickly (+1, +2, 0, -1, -2).

**Comment by HbmMods** [comment]
Fixed in X4347.
