### ISSUE TITLE
There is no way to make mercury

### ISSUE THREAD

**Issue by Qub810** [HbmMods/Hbm-s-Nuclear-Tech-GIT#721]
### I can't make mercury

Is the problem with the mod or is it something I'm doing wrong?
![2022-08-23_23 49 52](https://user-images.githubusercontent.com/111915150/186263162-41b17af6-e053-4445-b346-eb8b04416ef9.png)

**Comment by HbmMods** [comment]
Ore dict recipes don't work in the centrifuge right now, expect a fix later today.

**Comment by HbmMods** [comment]
Fixed in X4336.
