### ISSUE TITLE
Enhancement: add upgrade slots for centrifuge

### ISSUE THREAD

**Issue by Creeper-banner** [HbmMods/Hbm-s-Nuclear-Tech-GIT#723]
### Description

I found that almost all single-block machines have their own upgrade slots, excluding the centrifuge. And in the ore processing system, the centrifige is the slowest machine, because it can't be upgraded.
I think a centrifuge with one or two upgrade slots is better, as it will be faster and more efficient.

**Comment by Globalfirestorm10** [comment]
bob is not open to suggestions, but I think this might be able to pass off as an enhancment

**Comment by Creeper-banner** [comment]
> bob is not open to suggestions, but I think this might be able to pass off as an enhancment

So maybe I should rename it to "Enhancement".

**Comment by Creeper-banner** [comment]
> bob is not open to suggestions, but I think this might be able to pass off as an enhancment

So maybe I have to rename it to "enhancement".

**Comment by SoB1nary** [comment]
neither suggestions nor enhancements are considered. have a good day

**Comment by Antineutrino-4444** [comment]
better to find some dude who knows java coding and ask the code to be literally done and submitted to PR.

In fact i do agree with this idea oof :)

**Comment by HbmMods** [comment]
Upgrade slots were added in X4410.
