### ISSUE TITLE
Last update crash err

### ISSUE THREAD

**Issue by solundev** [HbmMods/Hbm-s-Nuclear-Tech-GIT#725]
![image](https://user-images.githubusercontent.com/82925878/187311165-40b61a04-c226-4388-8e05-a6cd0886e636.png)

**Comment by solundev** [comment]
Bug on minecraft side, solved with backup

**Comment by HbmMods** [comment]
`NoSuchFieldError: tanks`

Are you using the energy control mod? I believe it breaks with last week's update due to the changes in the fluid system.
