### ISSUE TITLE
Fluid Pipe capability from other Mods

### ISSUE THREAD

**Issue by TexThePlayer** [HbmMods/Hbm-s-Nuclear-Tech-GIT#726]
So i am Playing a small modpack made by me and NTM is one of my favorite mods in there, though for my small base i got a Railway set up with Traincraft and i cant load any NTM Fluids into the Tank carts because the Pipes wont connect to the Fluidloader from Railcraft. I can Connect the pipes to it from various mods like mekanism or Ender IO but NTMs wont, is the like an Adapter for it?
i cant even fill the Fluids from NTM in Tanks from other mods

**Comment by Antineutrino-4444** [comment]
HBM uses their own fluid system which makes it impossible to make it to be compatiable with other mods.
This: https://www.mcmod.cn/class/7426.html mod from a Chinese website is able to allow the transformation and make it compatiable with forge fluids. You can try it, google translate should be able to translate the website.

**Comment by TexThePlayer** [comment]
I installed the mod and my game crashes on startup, heres the Crash report:

**Comment by TexThePlayer** [comment]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 8/31/22 7:07 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: HA/Loader
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: HA/Loader
	at HA.CommonProxy.preInit(CommonProxy.java:20)
	at HA.HBMAddon.preInit(HBMAddon.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more
Caused by: java.lang.ClassNotFoundException: HA.Loader
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.lang.NoClassDefFoundError: ventivu/api/IReload
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 40 more
Caused by: java.lang.ClassNotFoundException: ventivu.api.IReload
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1523048664 bytes (1452 MB) / 3813670912 bytes (3637 MB) up to 8478261248 bytes (8085 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9096m -Xms256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 77 mods loaded, 77 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCH	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCH	itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCH	OpenComputers|Core{1.7.6+e84596e} [OpenComputers (Core)] (minecraft.jar) 
	UCH	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCH	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCH	betterbuilderswands{0.8.1} [Better Builder's Wands] (BetterBuildersWands-0.8.1-1.7.10r92+aec06c3.jar) 
	UCH	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCH	blur{MC1.7.10-1.0.1-2} [Blur] (Blur-MC1.7.10-1.0.1-2.jar) 
	UCH	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UCH	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
	UCH	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCH	CoroAI{v1.0} [CoroAI] (coroutil-1.7.10-1.1.6.jar) 
	UCH	BuildMod{v1.0} [Build Mod] (coroutil-1.7.10-1.1.6.jar) 
	UCH	CoroPets{v1.0} [CoroPets] (coroutil-1.7.10-1.1.6.jar) 
	UCH	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.7.10-1.1.6.jar) 
	UCH	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.7.10-1.1.6.jar) 
	UCH	creativecore{1.3.14} [CreativeCore] (CreativeCore v1.3.24 mc1.7.10.jar) 
	UCH	dsurround{1.0.6.4} [Dynamic Surroundings] (DynamicSurroundings-1.7.10-1.0.6.4.jar) 
	UCH	dynamictrees{1.7.10-0.7.2c} [Dynamic Trees] (DynamicTrees-1.7.10-0.7.2c.jar) 
	UCH	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCH	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCH	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCH	gravestone{0.7.10.3} [Gravestone] (GraveStone Mod 0.7.10.3.jar) 
	UCH	examplemod{1.0} [Example Mod] (GunpowderRecipeMod_1.7.2.jar) 
	UCH	hbm{1.0.27 BETA (4312)} [Hbm's Nuclear Tech] (HBM-NTM-[1.0.27_X4312].jar) 
	UCH	magcore{0.2.2} [MagCore] (MagCore-0.3.5 Release.jar) 
	UCE	HA{0.0.8} [HBMaddon] (HBMAddon-0.0.8.jar) 
	UCH	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCH	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCH	ironfurnaces{1.2.4} [Iron Furnaces] (Iron-Furnaces-Mod-1.7.10.jar) 
	UCH	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCH	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCH	littletiles{1.1.0} [LittleTiles] (LittleTiles v1.2.0 mc1.7.10.jar) 
	UCH	locks{1.0.0} [Locks] (Locks-1.0.0.jar) 
	UCH	Magneticraft{0.6.0-final} [Magneticraft] (magneticraft-0.6.1-final.jar) 
	UCH	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCH	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCH	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCH	mcheli{1.0.3} [MC Helicopter] (mcheli) 
	UCH	Mekanism{9.1.1} [Mekanism] (Mekanism-1.7.10-9.1.1.1031.jar) 
	UCH	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCH	mw{0.4.1} [Modern Warfare Contagion] (mw_2.0-0.4.1_mc1.7.10.jar) 
	UCH	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
	UCH	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCH	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCH	OpenComputers{1.7.6+e84596e} [OpenComputers] (OpenComputers-MC1.7.10-1.7.6+e84596e-universal.jar) 
	UCH	oreexcavation{1.1.134} [OreExcavation] (OreExcavation-1.1.134.jar) 
	UCH	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCH	parachutemod{1.7.10} [Parachute Mod] (parachutemod-1.7.10-2.5.6-01.jar) 
	UCH	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6-fix-1.jar) 
	UCH	pressure{1.3.0.fix1} [Pressure Pipes] (pressure-1.3.0.fix1-mc1.7.10.jar) 
	UCH	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCH	ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
	UCH	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
	UCH	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCH	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
	UCH	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCH	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCH	RealisticTorches{1.6.3} [Realistic Torches] (RealisticTorches-1.7.10-1.6.3.jar) 
	UCH	SparksHammers{1.7.10-1.6} [Spark's Hammers] (SparksHammers-1.7.10-1.6.1.jar) 
	UCH	tc{4.4.1_020-CE_5.0} [Traincraft - Community Edition] (Traincraft-4.4.1_020-CE_5.jar) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCH	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCH	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
	UCH	weather2{v2.3.19} [Localized Weather & Storms] (weather2-1.7.10-2.3.20.jar) 
	UCH	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	UCH	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCH	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCH	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UCH	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14800 Compatibility Profile Context 22.Q2 30.0.21020.2' Renderer: 'AMD Radeon RX 5700'
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	Mantle Environment: Environment healthy.
	List of loaded APIs: 
		* appliedenergistics2|API (rv2) from appliedenergistics2-rv2-stable-10.jar
		* BuildCraftAPI|blocks (1.0) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|core (2.0) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|crops (1.1) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|items (1.1) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|library (2.0) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|lists (1.0) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|statements (1.1) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|tablet (1.0) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|tiles (1.2) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|tools (1.0) from extrautilities-1.2.12.jar
		* BuildCraftAPI|transport (4.1) from Railcraft_1.7.10-9.12.2.0.jar
		* ChiselAPI (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Carving (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Rendering (0.1.1) from Chisel-2.9.5.11.jar
		* CoFHAPI (1.7.10R1.0.13) from EnderCore-1.7.10-0.2.0.39_beta.jar
		* CoFHAPI|block (1.7.10R1.0.13B1) from extrautilities-1.2.12.jar
		* CoFHAPI|energy (1.7.10R1.0.13) from ImmersiveEngineering-0.7.7.jar
		* CoFHAPI|item (1.7.10R1.0.10) from Mekanism-1.7.10-9.1.1.1031.jar
		* CoFHAPI|transport (1.7.10R1.0.13) from EnderCore-1.7.10-0.2.0.39_beta.jar
		* ComputerCraft|API (1.75) from Traincraft-4.4.1_020-CE_5.jar
		* ComputerCraft|API|FileSystem (1.75) from Traincraft-4.4.1_020-CE_5.jar
		* ComputerCraft|API|Lua (1.75) from Traincraft-4.4.1_020-CE_5.jar
		* ComputerCraft|API|Media (1.75) from Traincraft-4.4.1_020-CE_5.jar
		* ComputerCraft|API|Peripheral (1.75) from Traincraft-4.4.1_020-CE_5.jar
		* ComputerCraft|API|Permissions (1.75) from Traincraft-4.4.1_020-CE_5.jar
		* ComputerCraft|API|Redstone (1.75) from Traincraft-4.4.1_020-CE_5.jar
		* ComputerCraft|API|Turtle (1.75) from Traincraft-4.4.1_020-CE_5.jar
		* CoroAI|dynamicdifficulty (1.0) from coroutil-1.7.10-1.1.6.jar
		* ForgeRelocation|API (0.0.1.4) from ForgeRelocation-0.0.1.4-universal.jar
		* IC2API (1.0) from industrialcraft-2-2.2.827-experimental.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.7.7.jar
		* MagneticraftAPI (2.0.3) from magneticraft-0.6.1-final.jar
		* MagneticraftAPI|Computer (2.0.3) from magneticraft-0.6.1-final.jar
		* MagneticraftAPI|Computer|PreFab (2.0.3) from magneticraft-0.6.1-final.jar
		* MagneticraftAPI|ConveyorBelt (2.0.3) from magneticraft-0.6.1-final.jar
		* MagneticraftAPI|ConveyorBelt|PreFab (2.0.3) from magneticraft-0.6.1-final.jar
		* MagneticraftAPI|Electricity (2.0.3) from magneticraft-0.6.1-final.jar
		* MagneticraftAPI|Electricity|PreFab (2.0.3) from magneticraft-0.6.1-final.jar
		* MagneticraftAPI|Heat (2.0.3) from magneticraft-0.6.1-final.jar
		* MagneticraftAPI|Heat|PreFab (2.0.3) from magneticraft-0.6.1-final.jar
		* MagneticraftAPI|Kinetic (2.0.3) from magneticraft-0.6.1-final.jar
		* MagneticraftAPI|Pressure (2.0.3) from magneticraft-0.6.1-final.jar
		* MagneticraftAPI|Pressure|PreFab (2.0.3) from magneticraft-0.6.1-final.jar
		* MagneticraftAPI|Radiation (2.0.3) from magneticraft-0.6.1-final.jar
		* MagneticraftAPI|Recipes (2.0.3) from magneticraft-0.6.1-final.jar
		* MagneticraftAPI|Steel (2.0.3) from magneticraft-0.6.1-final.jar
		* MagneticraftAPI|Tools (2.0.3) from magneticraft-0.6.1-final.jar
		* MagneticraftAPI|Util (2.0.3) from magneticraft-0.6.1-final.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
		* MekanismAPI|reactor (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
		* MekanismAPI|recipe (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
		* OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.6+e84596e-universal.jar
		* OpenComputersAPI|Core (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.6+e84596e-universal.jar
		* OpenComputersAPI|Driver (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.6+e84596e-universal.jar
		* OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.6+e84596e-universal.jar
		* OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.6+e84596e-universal.jar
		* OpenComputersAPI|FileSystem (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.6+e84596e-universal.jar
		* OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.6+e84596e-universal.jar
		* OpenComputersAPI|Machine (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.6+e84596e-universal.jar
		* OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.6+e84596e-universal.jar
		* OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.6+e84596e-universal.jar
		* OpenComputersAPI|Prefab (6.0.0-alpha) from OpenComputers-MC1.7.10-1.7.6+e84596e-universal.jar
		* pressureAPI (1.3.0.fix1) from pressure-1.3.0.fix1-mc1.7.10.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|carts (1.6.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|core (1.5.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|electricity (2.0.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|events (1.0.0) from Traincraft-4.4.1_020-CE_5.jar
		* RailcraftAPI|fuel (1.0.0) from Traincraft-4.4.1_020-CE_5.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|items (1.0.0) from Traincraft-4.4.1_020-CE_5.jar
		* RailcraftAPI|locomotive (1.1.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|signals (2.3.0) from Traincraft-4.4.1_020-CE_5.jar
		* RailcraftAPI|tracks (2.3.0) from Railcraft_1.7.10-9.12.2.0.jar
		* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.12.2.0.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.

**Comment by Antineutrino-4444** [comment]
you can then try this mod:
https://www.mcmod.cn/class/6081.html
this however does not have a recipy for the converter which might require you to add custom recipes to the machine
it allows fluid transferr between HBM and MEK but only limiting them in a few kinds like heavy water. some will also convert to BC fluid like crude oil.
so, it is not changing the whole fluid system which should help deal with crashing problems (caused by the addon) but there are few limitations.

**Comment by TexThePlayer** [comment]
Thanks this mod worked and actually helped me with my Traincraft Oil Line!

**Comment by TexThePlayer** [comment]
i convert The oil to BC Oil and then back to HBM Oil

**Comment by toddw183** [comment]
> HBM uses their own fluid system which makes it impossible to make it to be compatiable with other mods. This: https://www.mcmod.cn/class/7426.html mod from a Chinese website is able to allow the transformation and make it compatiable with forge fluids. You can try it, google translate should be able to translate the website.

I downloaded the first mod but can't seem to get it to work. How are you suppose to set the block up?

**Comment by Antineutrino-4444** [comment]
Try the second one that I posted

> you can then try this mod: https://www.mcmod.cn/class/6081.html this however does not have a recipy for the converter which might require you to add custom recipes to the machine it allows fluid transferr between HBM and MEK but only limiting them in a few kinds like heavy water. some will also convert to BC fluid like crude oil. so, it is not changing the whole fluid system which should help deal with crashing problems (caused by the addon) but there are few limitations.

**Comment by Antineutrino-4444** [comment]
You have to custom the recipe of the converter and I will try to find a working version for the first mod

**Comment by Antineutrino-4444** [comment]
https://github.com/Ventivu/HBMAdder/releases/tag/0.7
are you downloading from this? and if you can add a crash report, I can (or you can) add an issue in the page so that it will be solved
