### ISSUE TITLE
Hi, dont know if this is the right place to ask this but I dont know how to contact creator of 1.12 fork.

### ISSUE THREAD

**Issue by Scapulaunit12** [HbmMods/Hbm-s-Nuclear-Tech-GIT#73]
Uhm, hi I have a simple question, will the 1.12 version of this mod ever be on curseforge

 Love the mod btw and the 1.12 fork.

**Comment by Drillgon200** [comment]
That's me, and bob can put it on curseforge if he wants to after I do a test playthrough of the whole thing to find as many bugs as possible.

**Comment by Scapulaunit12** [comment]
ah, thanks for clarifying and thank you for the fork lol
