### ISSUE TITLE
Item Duplication Bug

### ISSUE THREAD

**Issue by OppaiHacker** [HbmMods/Hbm-s-Nuclear-Tech-GIT#733]
When Shift+left clicking a stackable item in RBMK Storage Column that isn't on 1st slot (by which I mean that for example an used fuel rod sits in slot 1, and some stackable item in slot below it) it gets moved to slot 1 in 2nd row and **_gets duplicated_**. Works with everything that can be stacked. 

HBM Version: 1.0.27_X4312 

https://user-images.githubusercontent.com/89047121/188512421-54ce7e5c-11a9-43db-a5c5-899f34e40594.mp4

**Comment by Shibva** [comment]
the DTX rod be doing some funny shit lel

**Comment by HbmMods** [comment]
Fixed in X4375.
