### ISSUE TITLE
Balefire Bomb Blow Up My Game

### ISSUE THREAD

**Issue by OppaiHacker** [HbmMods/Hbm-s-Nuclear-Tech-GIT#734]
When i try to type float value to the bomb timer game goes brrrrr

HBM Version: 1.0.27_X4312 

https://user-images.githubusercontent.com/89047121/188513710-5927d844-bcc3-4eba-b8b0-18cc28182c6e.mp4

**Comment by HbmMods** [comment]
Fixed in X4375.
