### ISSUE TITLE
Enhancement: diagnosing Black Lung progression

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#737]
### Describe the Enhancement

(second revision before posting, this time way shorter)

add a spirometer to allow for a player to view the level of exposure to Black Lung (considering the IRL device checks for lung capacity and such disease would in fact make it harder to breathe)

**Comment by Vaern** [comment]
Please do not post enhancements or suggestions here.

**Comment by Shibva** [comment]
k, besides. I have college to do anyway so the activity here from me will drop.
