### ISSUE TITLE
minor: forgotten recipe or intentonal?

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#738]
### Describe the bug

It seems you missed both the factory casings when removing their recipes. However, I think that maybe instead of getting rid of them you could instead make the recipe x8, the block itself if its just reduced to nothing more than a block (if it has any ticking stuff in it taken out) it could be "salvaged" as decoration blocks.

**Comment by HbmMods** [comment]
Most remaining factory parts have been removed, the casing blocks now use a more generic name and crafting them yields 8 blocks instead of 1.
