### ISSUE TITLE
Crash when leaving server.

### ISSUE THREAD

**Issue by FireIP** [HbmMods/Hbm-s-Nuclear-Tech-GIT#74]
[crash-2020-07-19_14.29.47-client.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/4943699/crash-2020-07-19_14.29.47-client.txt)

This issue alsou occures when the instance was imported to Twitch but it then occures when trying to join a server.
[crash-2020-07-19_14.47.38-client.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/4943711/crash-2020-07-19_14.47.38-client.txt)

**Comment by Drillgon200** [comment]
Steps to reproduce? I've joined several servers with this and it didn't do this crash. Anyway I slapped a try/catch band aid on it so it's "fixed" now I guess.

**Comment by FireIP** [comment]
For me this crash reliably happens when Leaving My server. Also I tried playing a singleplayer world and when saving and quitting the game just freezes and I have to force quit it the world seems to be saving properly though.
If it would help I could send you the modpack and the adress of my server. (Preferably in a private message)
I was able to reproduce this by generating a World with the modversion 1.3.3a and later playing with 1.3.4a.
Though this only seems to happen when the other mods are installed.

**Comment by Silivek** [comment]
I also have the same error and it can happen any time I join or leave the server, not 100% of the time though.

**Comment by FireIP** [comment]
If the installation was imported from a zip with the Twitch launcher it may help to use an older install and manually update it. For me this helped with crashing when joining.

**Comment by godtm3** [comment]
Nuclear_pashtet IS A STUPID SAND NIGGER
