### ISSUE TITLE
Most items are not visible on the conveyor belt

### ISSUE THREAD

**Issue by Herestmain** [HbmMods/Hbm-s-Nuclear-Tech-GIT#741]
### Describe the bug

I can see the Blocks on the conveyor belt , but most of the Item that on the conveyor belt can't be seen . Maybe it's because most Items don't have a volume .

**Comment by MCNaOtlichnoYT** [comment]
Set graphics to fancy, that helped me. Maybe you also need to set particles to all.

**Comment by Herestmain** [comment]
thanks
