### ISSUE TITLE
Visual Bug: LIghting issues arise when item in template renders in assebler

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#742]
### Describe the bug

I noticed that an annoying lighting bug happens if an item is rendered by putting a template in the assembly machine. for the sake of simplifying an explanation, here's a side by side

with the item rendering
![image](https://user-images.githubusercontent.com/38770780/189465696-f7284f17-0dad-4966-858f-8bc24f2c92c3.png)

Without the item rendering
![image](https://user-images.githubusercontent.com/38770780/189465707-4f2ee1e7-eb5e-4976-a8e5-06b4b25ce23d.png)

as you can see the lighting difference on blocks like the chest can be noted. a Fix for this would be appreciated if possible

**Comment by Shibva** [comment]
I was in a community that delt with a somewhat simular issue, something about the items OpenGL casting or whatever its called not being wraped properly or something. I cant recall the full details but I do know its a GL related issue (that doezs persist if optifine is removed)

**Comment by HbmMods** [comment]
Fixed in X4375.
