### ISSUE TITLE
[minor ]Crafting issue: Napalm B is uncreatable since fluid container update

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#744]
### Describe the bug

im not surprised of this because such a small thing can fly under the radar. apparently, the recipe for creating Napalm B in a blast furnace still uses a legacy item in its recipe
![image](https://user-images.githubusercontent.com/38770780/189499710-1d5cef62-fdef-4201-ab28-6817c9b2dde8.png)

**Comment by HbmMods** [comment]
Fixed in X4375.
