### ISSUE TITLE
Upgraded RBMK Explosión

### ISSUE THREAD

**Issue by tutueldias** [HbmMods/Hbm-s-Nuclear-Tech-GIT#751]
I propose to improve the explosion of the RBMK reactor is that when it explodes the lid of the reactor flies off like chernobyl and that black smoke loaded with radiation comes out, that radiation comes out of the RBMk drebirs and that there is 1 new structure similar to the Chernobyl nuclear power plant and with four varaciones the 1 built and did not destroy it, the 2 destroyed and with very high radiation almost 9000000, the 3 with the first sarcophagus and the 4 with the second sarcophagus.

**Comment by TheForge129** [comment]
shut up
stop
issues thread is not for suggestions

**Comment by tutueldias** [comment]
man don't get aggressive either

**Comment by burningwater202** [comment]
HBM does not take suggestions, plain and simple

People take this as a suggestion thread and start throwing out random suggestions and that makes other people think it's ok to send suggestions and all of a sudden no issues are being fixed and it's all "ples bring my favorite item from fortnite111~!!12" 

If you want something to be in the mod, go ahead and make a fork and do it on your own, then you can have it while everyone else uses the main branch

**Comment by tutueldias** [comment]
I didn't understand XD

**Comment by Antineutrino-4444** [comment]
Simple, if you know how to code, make a pull request. It is that simple and it is much more likely that your idea will be used, even it is not added into the main HBM thread, other people can also download it and try it out or something.
But if you CANNOT DO SO, STOP TALKING ABOUT THEM ESPECIALLY IN ISSUES!
