### ISSUE TITLE
Fallout isn't being created by nuclear bombs

### ISSUE THREAD

**Issue by Hunterandruff** [HbmMods/Hbm-s-Nuclear-Tech-GIT#755]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.

We are trying to get Fallout to get Gold-198 for a custom craft, however both the Micro-Nuclear and Nuclear bombs don't produce the block fallout. They have the particle effects of Fallout being created, however it doesn't gather on the ground. Am I using an incorrect bomb or is my game glitched?

**Comment by Hunterandruff** [comment]
I forgot to write this, however we are using HBM mod version 1.6.9a

**Comment by HbmMods** [comment]
Fallout was never implemented in 1.12. Also please report bugs relating to 1.12 to the respective [issues board](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/issues), this repository is only for 1.7.10.
