### ISSUE TITLE
[1.12.2] Cannot extract power from HE to RF Converter

### ISSUE THREAD

**Issue by Tech0verlord** [HbmMods/Hbm-s-Nuclear-Tech-GIT#76]
Seeing as the 1.12 repo doesn't have the issue tracker open, I'll be posting in here in hopes that it will be seen by Drillgon200. Haven't tested this with the 1.7 version, so no idea if it is an issue here as well.

Came across this mod and wanted to make a minimalistic modpack for myself around it. Major mods include:

- Applied Energistics 2
- JEI
- HBM Nuclear Tech
- OpenComputers
- XNet

One major problem I've come across, though, is I can't seem to pull power generated from this mod to use with other mods, except in 2 very specific cases (will get to those laster). Reading through the wiki I saw that there was a power converter to convert HE to RF. So I've been trying all day to use it. The thing is, no matter what I do to attempt to pull power from the Converter, no power was being transfered or moved. I've tried using XNet to pull power, placed an AE2 Energy Acceptor to try to power a basic AE network, P2P - FE busses (after powering the network with a creative cell), OpenComputers PowerConverter, and nothing seemed to work.

I then proceeded to install other mods, to make sure I wasn't doing something wrong, or if something was wrong with the power converter. I installed Extra Utilities 2, EnderIO, RFtools, and Mekanism.

Extra Utilities: I tried using various combinations of the energy Transfer Node and pipes to no avail, energy wouldn't transfer out of the HE converter to Xnet controller or the AE2 acceptor.

EnderIO: I tried the various tiers of energy conduits, configured specifically as pull from the HE converter and push into the controller, and no energy transfered.

RFtools: I tried the various powercells attached directly to the HE converter, and nothing, the powercells wouldn't charge.

Mekanism: I tried the basic Universal Cable, and at first it didn't work. Used the Configurator and put the end on the HE converter to pull, and what do you know, it started moving the power and charged the Xnet Controller.

So out of all the various ways to transfer power out of the converter the only way that actually worked was using Mekanism's Universal Cable. Now this was only 1 of the 2 cases where I saw energy move. The second case is pretty much useless, putting the HE to RF converter next to a RF to HE Converter showed the energy being transfered and converted.

Is there something I'm missing? There's no way that it's intended that the only way to draw power out of the Converter is with Mekanism, is it?

Attached screenshots show some of my attempts, before installing  all the various extra mods
![2020-07-21_03 39 09](https://user-images.githubusercontent.com/2433224/88028135-3e149500-cb06-11ea-8f51-3e4cebab5e16.png)
![2020-07-21_03 57 24](https://user-images.githubusercontent.com/2433224/88028182-508ece80-cb06-11ea-9901-5245816f6af7.png)
![2020-07-21_03 39 42](https://user-images.githubusercontent.com/2433224/88028209-584e7300-cb06-11ea-8cd2-f3d80558e106.png)
![2020-07-21_03 38 43](https://user-images.githubusercontent.com/2433224/88028226-5dabbd80-cb06-11ea-9aa0-62bdcbd43e57.png)
![2020-07-21_03 39 01](https://user-images.githubusercontent.com/2433224/88028232-5e445400-cb06-11ea-8c5a-8d60017b50da.png)

**Comment by HbmMods** [comment]
Until very recently, the 1.7 branch implemented the wrong parts of the COFH API which were incompatible with a slightly different implementation for the same API that is favored by other mods. Though the old one did indeed work with a couple of other mods, it was fixed nonetheless about a week ago.
My guess is that the API was ported as-is along with its inconsistencies and Drillgon ported the converters with the same broken implementation.

**Comment by Drillgon200** [comment]
Oh, you need to open an issue tracker? I thought that just happened automatically. Well, it probably does use the same broken implementation, and I'm not really sure how to fix it. I made it actively fill forge energy receivers around it as well now, so maybe that'll help.

**Comment by HbmMods** [comment]
It should happen automatically, perhaps that doesn't apply to forked projects?

**Comment by Joij21** [comment]
Yeah I can't find the issue tracker on the 1.12.2 branch either.

**Comment by TheForge129** [comment]
me neither

**Comment by Drillgon200** [comment]
Alright I clicked the issues button, now there should be an issue tracker for my fork.

**Comment by GODTM** [comment]
1.12 version sucks use the 1.7 drillcunts code is kinda shabby but now thats out of the way can you crush my cock with a rock

**Comment by sendhelppls213** [comment]
Would you mind stopping existing?

**Comment by GODTM** [comment]
listen here you stupid rock crab you min stop being a jim

**Comment by godtm3** [comment]
Nuclear_pashtet IS A STUPID SAND NIGGER
