### ISSUE TITLE
dupe items

### ISSUE THREAD

**Issue by Phillanor** [HbmMods/Hbm-s-Nuclear-Tech-GIT#764]
If you install several boxes in a row (any)
One has resources, the other does not.
And then break them with a tool with a vein miner - all the boxes will contain resources from the first one.
![2022-10-11_22 19 22](https://user-images.githubusercontent.com/81444400/195180130-a6276fe7-bf6f-42dc-b661-1e7560c53198.png)
![2022-10-11_22 19 23](https://user-images.githubusercontent.com/81444400/195180137-eb5edec6-09ae-4df1-9c94-2dd3ab46129b.png)
![2022-10-11_22 19 24](https://user-images.githubusercontent.com/81444400/195180140-93754899-bc80-49c6-94a4-b7f14726a4de.png)
![2022-10-11_22 19 25](https://user-images.githubusercontent.com/81444400/195180148-d0229e48-2659-41b0-bc03-becbe441ad39.png)
![2022-10-11_22 20 32](https://user-images.githubusercontent.com/81444400/195180267-c82136a5-5b3e-451d-aaf6-c90e482d7e16.png)
![2022-10-11_22 19 30](https://user-images.githubusercontent.com/81444400/195180155-95e4abd1-9e73-4cd0-9ae2-067e0c86aa01.png)
![2022-10-11_22 19 31](https://user-images.githubusercontent.com/81444400/195180156-928b5775-3c0d-49c6-834a-40566ef336dd.png)
![2022-10-11_22 19 32](https://user-images.githubusercontent.com/81444400/195180159-008e6fae-eaac-4940-a8da-d52688165dcd.png)
![2022-10-11_22 19 33](https://user-images.githubusercontent.com/81444400/195180161-e4ef2099-821c-47cb-a4fd-80ba24864655.png)
![2022-10-11_22 19 37](https://user-images.githubusercontent.com/81444400/195180163-e076f1b2-c665-43fb-859c-6fd67078ed7a.png)

**Comment by HbmMods** [comment]
Fixed in X4389.
