### ISSUE TITLE
Breeding reactor break balance bug

### ISSUE THREAD

**Issue by githubuser434** [HbmMods/Hbm-s-Nuclear-Tech-GIT#77]
after the small nuclear reactor shutdown, the breeding reactors that surround the fuel rods continue to function and are able to perform an large (possibly infinite) number of operations here is the screenshot:
![bug](https://user-images.githubusercontent.com/66527840/88029782-bb59fd00-cb3a-11ea-9625-5f1ef53531b1.png)
please somebody fix this annoying bug it's a total balance breaker

**Comment by HbmMods** [comment]
The breeding reactor was never balanced in the first place, it'll be reworked soon anyway.

**Comment by HbmMods** [comment]
I could not replicate the issue, even if there were one, the most recent changes to the breeding reactor would still mitigate that.
