### ISSUE TITLE
cyclotron with all 4 items crashes game

### ISSUE THREAD

**Issue by username90001** [HbmMods/Hbm-s-Nuclear-Tech-GIT#770]
i tried upgrade cyclotron with coin of mask man thermonuclear dust diamond gavel or how is it called and box of boxcars result when i opened it it crashed my game why

**Comment by Antineutrino-4444** [comment]
please attach the crash report or no one can possibly help you...

**Comment by username90001** [comment]
it always crashes just put all 4 items and open it

**Comment by HbmMods** [comment]
Can't replicate, please provide a crash report.

**Comment by username90001** [comment]
it doesnot happen in new versions
