### ISSUE TITLE
RBMK crane can't be moved using Open Computers

### ISSUE THREAD

**Issue by MCNaOtlichnoYT** [HbmMods/Hbm-s-Nuclear-Tech-GIT#771]
1. Run lua in OC
2. c=require("component")
3. r=c.rbmk_crane
4. r.load() works OK
5. r.move('up') or any other direction does not move the crane

**Comment by BallOfEnergy1** [comment]
From what I see, I don't see any changes in this section (of the code) since the original post, so I'll see if I can change some things to get it back working. (Yes, very late reply.)

**Comment by BallOfEnergy1** [comment]
Looks like it was fixed in recent versions, this issue can be closed.
