### ISSUE TITLE
(Addition) Cruise missiles, MIRVs, and size 20 parts?

### ISSUE THREAD

**Issue by Joey-Destroyah** [HbmMods/Hbm-s-Nuclear-Tech-GIT#778]
Seeing as the latest update says long range gps trolling, this may suggest that cruise missiles are on the way.
Then again, I am sure that cruise missile development may be more complicated then the ballistic missiles of now.

Speaking of ballistic missiles, will there be any use for the size 20 launch pad and engine other than adapting to size 15?

Also, maybe add MIRV warheads to either standalone missiles or custom missiles like old versions.

Thanks for attending my TED talk.

**Comment by SoB1nary** [comment]
this is a friendly reminder that no suggestions, enhancements or additions are allowed here
long-range gps guided trolling simply means that the himars turret got added in
like 1.25 contributors are currently working on custom missiles and mirv warheads in particular
