### ISSUE TITLE
the problem with the departure of missiles from the new tower

### ISSUE THREAD

**Issue by asddsa3211233** [HbmMods/Hbm-s-Nuclear-Tech-GIT#780]
### Describe the bug

 
hello I have a problem with the new rocket tower the fact is that when I press start the rocket takes off and freezes in place and literally stops my game(the game does not crash, so there is no error message)

**Comment by HbmMods** [comment]
Was the turret in automatic mode or did you use the artillery remote? Which missile type was it?

**Comment by asddsa3211233** [comment]
I used the remote control mode

**Comment by asddsa3211233** [comment]
I used both types of rockets

**Comment by HbmMods** [comment]
Could you try it again with the new version X4403? There was a related issue with artillery rockets and I suspect that might have been what caused them not moving in some cases.
