### ISSUE TITLE
add minechem support

### ISSUE THREAD

**Issue by username90001** [HbmMods/Hbm-s-Nuclear-Tech-GIT#781]
i want free technecium from nether

**Comment by HbmMods** [comment]
Could you be a bit more specific as to what that means? Do you want crafting support for certain ore dict tags or special compat recipes?

**Comment by username90001** [comment]
i mean i want get materials like niobium and other from minechem things like technecium isotope or niobium - i mean make it possible to craft things from hbm by using materials from minechem in chemical synthiser

**Comment by username90001** [comment]
> Could you be a bit more specific as to what that means? Do you want crafting support for certain ore dict tags or special compat recipes?

i mean i want get materials like niobium and other from minechem things like technecium isotope or niobium - i mean make it possible to craft things from hbm by using materials from minechem in chemical synthiser

**Comment by username90001** [comment]
uh?

**Comment by HbmMods** [comment]
Most elements already work and those that don't would be incredibly broken, you are of course free to add your own recipes using a recipe tweaker or one of NTM's recipe configs.
