### ISSUE TITLE
Chunk loader for nukes

### ISSUE THREAD

**Issue by Granniesgotaids** [HbmMods/Hbm-s-Nuclear-Tech-GIT#783]
Sorry if I shouldn't be posting this here, I have no idea where else to post it. Is chunk loader for nuclear weapons possible? Then if the player goes out of range the weapon will explode anyway and fallout wouldn't stop if you leave the blast site. That would be really cool if it was possible or planned.

**Comment by username90001** [comment]
it already does as i know

**Comment by Granniesgotaids** [comment]
Oh, I might just be retarded, nevermind.
