### ISSUE TITLE
Can't get the assembly machine to automatically insert and eject 

### ISSUE THREAD

**Issue by toddw183** [HbmMods/Hbm-s-Nuclear-Tech-GIT#785]
Using version [1.0.27_X4312]. I've have been using the 1.12 version of HBM and just recently started messing with the 1.7 version. In the 1.12 version all you had to do was set a chest next to the insert and ejection slots of the assembly machine and it would automatically pull any items that were used by the templet from the insert side and then eject the finished product into the chest on the ejection side. But I can't get it to work on the 1.7 version. I've tried using the conveyor belts with the ejector and insertor blocks but nothing seems to work.

**Comment by toddw183** [comment]
Ok. so seems like it's the types chests used. Doesn't like Iron Chest chests, Thermal Foundation's Strongboxes, actual Additions Crates. Seems to only like vanilla chests and HBM crates.

**Comment by HbmMods** [comment]
Should have been fixed a few versions back, all larger machines now use a standardized IO system that uses vanilla's hopper IO rules (prior, small assemblers had a small hardcoded list of things they could access).
