### ISSUE TITLE
[Not Mod Related but I Need Help] Unable to build from the source file

### ISSUE THREAD

**Issue by Antineutrino-4444** [HbmMods/Hbm-s-Nuclear-Tech-GIT#786]
So I have encountered with this not mod related issue that is really bothering me. I does not know a good spot to post this issue so I hope that you guys can help me out here. Another solution is to possibly give me someplace that I can post my problem and get help. However, in either of the cases, thank you so much for trying to solve this problem so below is the information that you might need (ask for more is necessary).

Computer OS: Mac Monterey
When trying to build the mod from the source code on Github, an error occurred when running following commands in terminal.
1. cd [The Source File Folder Directory]
2. (sudo) ./gradlew build (Tried this command both with or without sudo)
3. Starts to download stuff and after it is done and the package is extracted, this following error popped up:
"FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '14.0.2'."

Here is the Java version info the system is telling me through the command "java -version":
"openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment Zulu14.29+23-CA (build 14.0.2+12)
OpenJDK 64-Bit Server VM Zulu14.29+23-CA (build 14.0.2+12, mixed mode, sharing)"

**Comment by HbmMods** [comment]
The project only works with Java 8, your JDK is for Java 14. If you have multiple versions of JDK installed, either remove the other versions or make sure that the JAVA_HOME and PATH variables only point to the Java 8 install.

**Comment by Antineutrino-4444** [comment]
I tried uninstall the original Java and install a Java 8 version (at least i think it is) from this website: https://www.java.com/en/download/
But then the error code turn into:
"FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '18.0.2.1'."

**Comment by HbmMods** [comment]
It says that the JDK version that is used is 18, but you need 8. [You can get open JDK builds from Adoptium](https://adoptium.net/temurin/releases/?version=8), I believe nowadays the ones hosted on Oracle require an account or something.

**Comment by Antineutrino-4444** [comment]
Thank! It is now working properly!
