### ISSUE TITLE
very easy way to make nuke explosions less lagy and much more faster near instant

### ISSUE THREAD

**Issue by username90001** [HbmMods/Hbm-s-Nuclear-Tech-GIT#791]
i was experimenting with mods and found that if u place nuclear bomb on tile accelerator from mod tile accelerators i used maxium power tile accelerator explosion was near instant but no mushroom or radioation so i xd how to make it work oh and also tile accelerators hard to create and max is extreme hard because it needs very expensive materials to craft so add it

**Comment by Antineutrino-4444** [comment]
maybe it is me but i just can't understand what you are talking right here...
please add in screenshots to "support" your claim and make it easier for people to understand

**Comment by username90001** [comment]
i just put a nuclear bomb block on a tile accelerator bomb and after linked it to detonator and after fully covered it with accelerators and after comited hiroshima

**Comment by Antineutrino-4444** [comment]
> i just put a nuclear bomb block on a tile accelerator bomb and after linked it to detonator and after fully covered it with accelerators and after comited hiroshima

what do you mean by "a tile accelerator bomb", and what do you mean by "fully covered it with accelerators"? Can you just please organize your language and see it as your middle school writing accessment...

**Comment by SoB1nary** [comment]
breaking news: speeding ticks up makes things faster

**Comment by username90001** [comment]
> > i just put a nuclear bomb block on a tile accelerator bomb and after linked it to detonator and after fully covered it with accelerators and after comited hiroshima
> 
> what do you mean by "a tile accelerator bomb", and what do you mean by "fully covered it with accelerators"? Can you just please organize your language and see it as your middle school writing accessment...

i mean i covered nuclear bomb block with time accelerators

**Comment by username90001** [comment]
@HbmMods nukes are much more faster with tile acelerator block from mod called tile accelerator

**Comment by burningwater202** [comment]
If you speed up the tick rate using any kind of acceleration mod (tile accelerator, torcherino etc.) this could happen, yes. But to stay performant on a majority of systems while cranking up the tick speed on a complex calculation isn’t as easy as it sounds

My assumption is that Bob has a specific rate set that strikes a balance between speed and performance so that it doesn’t turn the entire game into a slideshow for those on lower end hardware

…but I could also be completely wrong as well. Guess we’ll see how he responds

**Comment by username90001** [comment]
> If you speed up the tick rate using any kind of acceleration mod (tile accelerator, torcherino etc.) this could happen, yes. But to stay performant on a majority of systems while cranking up the tick speed on a complex calculation isn’t as easy as it sounds
> 
> My assumption is that Bob has a specific rate set that strikes a balance between speed and performance so that it doesn’t turn the entire game into a slideshow for those on lower end hardware
> 
> …but I could also be completely wrong as well. Guess we’ll see how he responds

i mean explosion is instant without problems but if bomb is really strong it will freeze game for few secounds but after it will end lags no aftermath lags or freezes
only problem no radiation mushroom and fallout 
and bobcat put huh tag today
