### ISSUE TITLE
Can't lock doors.

### ISSUE THREAD

**Issue by Mooshroom8** [HbmMods/Hbm-s-Nuclear-Tech-GIT#792]
Using the newest version, I am trying to lock my doors but they just open. I am currently trying to use a padlock on a metal door. When I right click it, it just opens.

**Comment by Antineutrino-4444** [comment]
Sir, padlocks are for Safes...
You cannot lock doors in any possible form.

**Comment by HbmMods** [comment]
What kind of door are you trying to lock? Locks are only compatible with multiblock blast doors.

**Comment by Mooshroom8** [comment]
Well crap. How do I replace a two block door with a friggin blast door? Just thought a padlock made more sense for a normal door.

**Comment by Mooshroom8** [comment]
accident

**Comment by Mooshroom8** [comment]
It has been a while, but the issue persists. I can't even lock other multiblock doors, Such as the fire door.

**Comment by HbmMods** [comment]
The new doors had the issue that locks would only work when clicking on the core block, that was fixed recently, locks should behave as expected. You will need to shift-click to install the lock though, as a normal right-click just opens it.
