### ISSUE TITLE
"Maxwell" 5G upgrade effect only renders for one player

### ISSUE THREAD

**Issue by TehTemmie** [HbmMods/Hbm-s-Nuclear-Tech-GIT#793]
Version: NTM 1.0.27-X4403

Issue: The "mutation" effect from a "Maxwell" turret with the 5G upgrade is only visible on the player with the effect. Other players on a server cannot see the afflicted player's model turning into Astolfo. Only tested in LAN mode using one online and one offline instance of Minecraft.

**Comment by HbmMods** [comment]
Is the effect visible if the viewer relogs? I recall seeing a similar issue on a server recently.

**Comment by TehTemmie** [comment]
Just checked, the effect becomes visible if either player relogs, doesn't matter if it's the viewer or the one affected. I imagine the visibility works something like this (I only tested with 2 players so I can't confirm what a third player would see):
- Player A gets inflicted with 5G mutation, only Player A can see it
- Player B relogs and can see it now, any other players still cannot
- Player A relogs, everyone can see it now

A similar thing seems to apply with getting rid of the effect by using milk (after a relog so the effect is visible to other players), though dying seems to update the player model properly

**Comment by HbmMods** [comment]
I think I found the issue, potions aren't actually synchronized to other players, it's only the average potion color for the particle effect. I'll just have to find another way to get this information to clients, then.

**Comment by HbmMods** [comment]
Fixed in X4585
