### ISSUE TITLE
[suggestion] euphmium powered warp drive spaceship

### ISSUE THREAD

**Issue by username90001** [HbmMods/Hbm-s-Nuclear-Tech-GIT#794]
reusable spaceship that uses euphmium because of antigravity and with advanced rocketry can launch player to other planets or solar systems

**Comment by SoB1nary** [comment]
one) NO SUGGESTIONS PLEASE
two) this guy's braincells are quantum entangled with uffr's

**Comment by burningwater202** [comment]
Friendly reminder that suggestions are not appreciated in any way shape or form, any suggestion you make will be closed without consideration and you will be mocked senselessly until the end of time.
You will not be warned again.
