### ISSUE TITLE
Screen becomes solid color when holding items from the mod

### ISSUE THREAD

**Issue by RandomMinecraftPlayer** [HbmMods/Hbm-s-Nuclear-Tech-GIT#798]
It makes the screen a solid color I cant roll back my driver help me please fix this or tell me how to fix it youtubers ive seen arent having these problems

**Comment by RandomMinecraftPlayer** [comment]
Please help

**Comment by Mooshroom8** [comment]
I think its with your graphics card, try installing older drivers.
Worked for my friends!

**Comment by RandomMinecraftPlayer** [comment]
how
do i

**Comment by RandomMinecraftPlayer** [comment]
i tried it didnt work

**Comment by RandomMinecraftPlayer** [comment]
help me now!












it doesnt work


































































































































































AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by burningwater202** [comment]
Throwing a tantrum won’t get you anywhere here. If you don’t know how to install drivers for your graphics card go to www.google.com and figure it out. There’s bound to be millions of pages showing exactly how to do it.

**Comment by RandomMinecraftPlayer** [comment]
i have tried it does not work
even though i did that

**Comment by HbmMods** [comment]
Collecting the GPU drivers issue in #985
