### ISSUE TITLE
Request:Mixed suits

### ISSUE THREAD

**Issue by neumannfe** [HbmMods/Hbm-s-Nuclear-Tech-GIT#8]
I had a problem with the hazmat suits because i had chestplate and helmet from p and a alloy and the other parts from normal hazmat cloth.when i walked towards a nuclear barrel i dies. Could you add that it is possible to wear mixed suits?

**Comment by GrTaiyaki** [comment]
I think it would be easy also for me to implement a function which prevents the player from dying due to radiations if he uses mixed suits.
If hbm wants I'll make it an official part of the game while he works on more complex and less braindead things

**Comment by HbmMods** [comment]
Indeed, it would be rather easy to do that, but that's not how the suits are intended to be used.
