### ISSUE TITLE
absolute black screen because of draconic evolution mod

### ISSUE THREAD

**Issue by username90001** [HbmMods/Hbm-s-Nuclear-Tech-GIT#800]
i cant play with it or with dragonapi i xd why it just absolute black

**Comment by firefoxyz** [comment]
check logs, is it a openGL error 1282?

**Comment by firefoxyz** [comment]
and what version of minecraft are you using? 1.12.2?

**Comment by username90001** [comment]
> and what version of minecraft are you using? 1.12.2?

1.7.10 + near 180 mods

**Comment by HbmMods** [comment]
I've used NTM together with DAPI and DE before and it worked just fine, what makes you think it's those mods and not one of the other 180?

**Comment by username90001** [comment]
how do i find mod that makes draconic evolution make minecraft blakc

**Comment by ST3V3P4U1** [comment]
I'm getting the OpenGL error 1281 on 1.12.2 forge and I tried deleting shaders
