### ISSUE TITLE
Blast resistance blocks of ntm

### ISSUE THREAD

**Issue by Timohen21** [HbmMods/Hbm-s-Nuclear-Tech-GIT#802]
Hello, I would really like to know if it is possible to somehow change the explosion resistance of some blocks from the ntm mod, for example concrete, it seems to me that it is too impenetrable, even a nuclear explosion almost does not destroy it at close range.
If you know, please help me to change these values

**Comment by redshadow3** [comment]
well not directly in the config so you would need to find it in the open source version and cchange it but you probably arent a programmer or dev so idk

im not a programmer or dev either so i might be wrong

**Comment by HbmMods** [comment]
Resistance for things like concrete were rebalanced a while ago, making nukes a lot more effective. Only the highest tier blocks like CMB bricks are still near-invulnerable to nukes.
