### ISSUE TITLE
Causing massive lag:  HBM's Nuclear Tech Mod loaded a new chunk [...] while populating chunk [...], causing cascading worldgen lag.

### ISSUE THREAD

**Issue by nsde** [HbmMods/Hbm-s-Nuclear-Tech-GIT#806]
Hello! 
I'm running a Minecraft server:

Mod version: `hbm-1.6.9a-G`
Server RAM: `7GB`

And my console is spammed with the following messages:

```
[00:34:12] [Server thread/WARN] [FML]: HBM's Nuclear Tech Mod loaded a new chunk [-165, -457] in dimension 0 (overworld) while populating chunk [-164, -457], causing cascading worldgen lag.
[00:34:12] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
```

Is there a way to fix this without having to reset the world (we have done a lot of progress)?

Thanks!

**Comment by nsde** [comment]
![image](https://user-images.githubusercontent.com/67185896/201444505-77a300a6-6baf-43e2-90fe-9de170938b4e.png)

**Comment by bulutthecat** [comment]
I am also having this issue? why is this invalid? and what is causing this? I am on the latest 1.8.3a-G version, and encountering this bug the second I start a server, not even on an old world.

**Comment by burningwater202** [comment]
It’s a 1.12 issue, this is the 1.7.10 GitHub. This github has nothing to do with the 1.12 versions which are handled by completely different users. Please consult the respective GitHubs for your issue

**Comment by Ijustplaymc** [comment]
> It’s a 1.12 issue, this is the 1.7.10 GitHub. This github has nothing to do with the 1.12 versions which are handled by completely different users. Please consult the respective GitHubs for your issue

This issue occurs on the 1.7 version now

**Comment by Vaern** [comment]
the error message described does not actually exist in 1.7.10, although cascading worldgen is possible. that's likely due to meteor/jungle dungeons or even one of the larger, schematic-based structures

**Comment by Spinni23** [comment]
![Screenshot 2024-10-22 114621](https://github.com/user-attachments/assets/5fe11832-c921-4e89-ac5b-456872b6be7f)
mein game laggt und der bildschirm ist grün

**Comment by Spinni23** [comment]
weiß jemand wie ich es ändern kann?
