### ISSUE TITLE
How to disable absolutely all explosions in private?

### ISSUE THREAD

**Issue by Phillanor** [HbmMods/Hbm-s-Nuclear-Tech-GIT#807]
How to disable absolutely all explosions in private?
All flags in private are for disabling the explosion, it works for some items and explosives, but not for the rest...

**Comment by TheForge129** [comment]
You should be able to set explosion radii in the config to 0

**Comment by Phillanor** [comment]
> 

Won't that completely disable the explosions? I need to achieve the absence of destruction only in worldguard regions

**Comment by HbmMods** [comment]
Worldguard doesn't provide an API I can use (that I know of), nor will it protect against nuclear explosions since they are very much distinct from vanilla ones. You can either remove the recipes for bombs or implement server rules for that case.
