### ISSUE TITLE
Anti Ballistic Missile Lagging Game to 2 FPS

### ISSUE THREAD

**Issue by Cojoe78** [HbmMods/Hbm-s-Nuclear-Tech-GIT#810]
I launched a few anti-ballistic missiles trying to test a radar-based anti-ballistic missile system but none of the missiles locked onto the target missile and instead kept traveling up. I expected them to explode or disappear at some altitude but they’re currently over 11,000,000 and still going. I did this over my base that I spent way too long on making to abandon it and it has lagged my game out so badly that the frame rate sits around 2 FPS. Please help me!!

**Comment by HbmMods** [comment]
Anti ballistic missiles should automatically despawn after going past Y:2000, although that might not be the case on older 1.7.10 versions or on 1.12.2. 1.12.2 has the `/kill @e` command, I don't know how that version handles entity IDs but the name for anti ballistic missiles is `entity_missile_anti`, it might have a prefix such as `hbm.` or `hbm:`. If killing it doesn't work, you should be able to remove it with an NBT or world editor.
