### ISSUE TITLE
Issue when using hardcore darkness mod with hbm ntm

### ISSUE THREAD

**Issue by rambo0247** [HbmMods/Hbm-s-Nuclear-Tech-GIT#812]
When using hbm ntm with [hardcore darkness mod](https://www.curseforge.com/minecraft/mc-mods/hardcore-darkness), hardcore darkness stops working entirely.

Without hbm ntm:
![image](https://user-images.githubusercontent.com/60529713/201747077-2421f432-efe1-4512-8e65-ca441cb61e28.png)

With hbm ntm:
![image](https://user-images.githubusercontent.com/60529713/201747108-e83b4a07-f4c5-4043-ab61-f301c23fa5a1.png)

versions:
HBM-NTM-[1.0.27_X4417]
HardcoreDarkness-MC1.7.10-1.7

**Comment by rambo0247** [comment]
After further testing by checking every version, it breaks with hardcore darkness starting on version `HBM-NTM-[1.0.27_X4130]`

**Comment by rambo0247** [comment]
did a compare on github between 4130(when it started breaking) and 4026(last working version)
saw this addition `src/main/java/com/hbm/blocks/generic/BlockDirt.java`
![image](https://user-images.githubusercontent.com/60529713/201777236-1746eaf6-da6f-4901-9f28-9a391a648432.png)

just guessing, idk

**Comment by rambo0247** [comment]
after seeing 

> did a compare on github between 4130(when it started breaking) and 4026(last working version) saw this addition `src/main/java/com/hbm/blocks/generic/BlockDirt.java` ![image](https://user-images.githubusercontent.com/60529713/201777236-1746eaf6-da6f-4901-9f28-9a391a648432.png)
> 
> just guessing, idk

did more testing and the problem only occurs above grand which is for the dirt block change you made above im guessing.
Underground when surrounded by stone it works fine. 
![image](https://user-images.githubusercontent.com/60529713/201778942-f4d28c89-b196-4a9d-9d1b-5bf01a9a6ed0.png)

**Comment by HbmMods** [comment]
Looks like it works in X4040 (the version right after X4026) but it's already broken in X4116 (before X4130). There's six more versions between that that I'll have to try out, but I suspect it might be NTM's skybox replacement, hence why it still works correctly underground.

**Comment by rambo0247** [comment]
curious if theres anything i can do on my end in the immediate future to fix or has to be you.

**Comment by HbmMods** [comment]
I think I got it, X4053 added a custom world provider class which handles sky color, fog and some brightness related stuff. I'll just slap a config on that so it can be turned off, it's only really relevant to post-impact effects anyway.

**Comment by rambo0247** [comment]
alright, thanks

**Comment by HbmMods** [comment]
Version X4431 now has two new config options for disabling NTM's custom world provider and skyboxes (`1.31_enableSkyboxes` and `1.32_enableImpactWorldProvider`). Simply disabling the world provider should work, but if it doesn't you can also try disabling the skybox (reverting it to vanilla) as well.
