### ISSUE TITLE
enhachment - end globules trixite ore generation

### ISSUE THREAD

**Issue by username90001** [HbmMods/Hbm-s-Nuclear-Tech-GIT#814]
make trixite generate in globules from end globules mod

**Comment by TheForge129** [comment]
If I understand ore generation correctly, unless End Globules treats the
globules as ore clusters, trixite should be able to generate

**Comment by HbmMods** [comment]
Trixite generation doesn't check for the main island, it will try to generate ores everywhere from Y:0-127. If it doesn't generate then it's either because it's too high up or because the globules use the wrong kind of world gen and generate after the ores.

**Comment by username90001** [comment]
> Trixite generation doesn't check for the main island, it will try to generate ores everywhere from Y:0-127. If it doesn't generate then it's either because it's too high up or because the globules use the wrong kind of world gen and generate after the ores.

i was trying to find trixite on those globules when using ATG alternative terrarian generator i didnot found anything only on main island
