### ISSUE TITLE
My game Keep crashing When Im Joining the world

### ISSUE THREAD

**Issue by Assasinowy** [HbmMods/Hbm-s-Nuclear-Tech-GIT#818]
My game Keep crashing when i want to join my world with rbmk Reactor on it 
There is the Crashlog
I'm Playing On 1.12 Version

// Who set us up the TNT?

Time: 11/20/22 10:50 AM
Description: Exception while ticking a block

java.lang.NullPointerException: Exception while ticking a block
	at com.hbm.main.ClientProxy.effectNT(ClientProxy.java:1200)
	at com.hbm.blocks.machine.rbmk.RBMKDebrisRadiating.func_180650_b(RBMKDebrisRadiating.java:60)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.hbm.main.ClientProxy.effectNT(ClientProxy.java:1200)
	at com.hbm.blocks.machine.rbmk.RBMKDebrisRadiating.func_180650_b(RBMKDebrisRadiating.java:60)

-- Block being ticked --
Details:
	Block: hbm:pribris_radiating[meta=0]
	Block location: World: (548,60,-456), Chunk: (at 4,3,8 in 34,-29; contains blocks 544,0,-464 to 559,255,-449), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)

**Comment by Assasinowy** [comment]
I need Fast Feedback

**Comment by TheOriginalGolem** [comment]
Please send the full crash log file

**Comment by Assasinowy** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ReachFixPlugin (ReachFix-1.12.2-1.0.5.jar)
  CQRPlugin (Chocolate_Quest_Repoured-1.12.2-2.6.12B.jar)
  midnight (themidnight-0.3.5.jar)
  FutureMC (future-mc-0.2.10.1.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 11/20/22 11:37 AM
Description: Exception while ticking a block

java.lang.NullPointerException: Exception while ticking a block
	at com.hbm.main.ClientProxy.effectNT(ClientProxy.java:1200)
	at com.hbm.blocks.machine.rbmk.RBMKDebrisRadiating.func_180650_b(RBMKDebrisRadiating.java:60)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.hbm.main.ClientProxy.effectNT(ClientProxy.java:1200)
	at com.hbm.blocks.machine.rbmk.RBMKDebrisRadiating.func_180650_b(RBMKDebrisRadiating.java:60)

-- Block being ticked --
Details:
	Block: hbm:pribris_radiating[meta=0]
	Block location: World: (509,61,-603), Chunk: (at 13,3,5 in 31,-38; contains blocks 496,0,-608 to 511,255,-593), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)

-- Affected level --
Details:
	Level name: Charnobyl 2
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -3966946006514940988
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 3;minecraft:bedrock,3*minecraft:stone,52*minecraft:sandstone;2;
	Level spawn location: World: (527,4,-630), Chunk: (at 15,0,10 in 32,-40; contains blocks 512,0,-640 to 527,255,-625), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Level time: 81956 game time, 81956 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 26933 (now: false), thunder time: 31123 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3052218392 bytes (2910 MB) / 6643777536 bytes (6336 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 54 mods loaded, 54 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version           | Source                                            | Signature                                |
	|:------ |:-------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2            | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                  | 9.42              | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2860.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2860      | forge-1.12.2-14.23.5.2860.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | reachfix             | 1.0.5             | minecraft.jar                                     | None                                     |
	| LCHIJA | damageindicatorsmod  | 1.0               | [1.12.2]DamageIndicatorsMod-3.5.1.jar             | None                                     |
	| LCHIJA | bspkrscore           | 7.6.0.1           | [1.12]bspkrsCore-universal-7.6.0.1.jar            | None                                     |
	| LCHIJA | treecapitator        | 1.43.0            | [1.12]TreeCapitator-client-1.43.0.jar             | None                                     |
	| LCHIJA | aether_legacy        | 1.5.3.2           | aether-1.12.2-v1.5.3.2.jar                        | None                                     |
	| LCHIJA | autoreglib           | 1.3-32            | AutoRegLib-1.3-32.jar                             | None                                     |
	| LCHIJA | ichunutil            | 7.2.2             | iChunUtil-1.12.2-7.2.2.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | backtools            | 7.0.1             | BackTools-1.12.2-7.0.1.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | betternether         | 0.1.8.6           | betternether-0.1.8.6.jar                          | None                                     |
	| LCHIJA | bibliocraft          | 2.4.6             | BiblioCraft[v2.4.6][MC1.12.2].jar                 | None                                     |
	| LCHIJA | camera               | 1.0.9             | camera-1.0.9.jar                                  | None                                     |
	| LCHIJA | jei                  | 4.16.1.302        | jei_1.12.2-4.16.1.302.jar                         | None                                     |
	| LCHIJA | cqrepoured           | 2.6.12B           | Chocolate_Quest_Repoured-1.12.2-2.6.12B.jar       | None                                     |
	| LCHIJA | cloudboots           | 1.4.1             | CloudBoots-1.12.2-1.4.1.jar                       | None                                     |
	| LCHIJA | codechickenlib       | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux         | 2.1.1             | RedstoneFlux-1.12-2.1.1.1-universal.jar           | None                                     |
	| LCHIJA | cofhcore             | 4.6.6             | CoFHCore-1.12.2-4.6.6.1-universal.jar             | None                                     |
	| LCHIJA | cofhworld            | 1.4.0             | CoFHWorld-1.12.2-1.4.0.1-universal.jar            | None                                     |
	| LCHIJA | coralreef            | 2.0               | CoralReef-2.5-1.12.2.jar                          | None                                     |
	| LCHIJA | craftstudioapi       | 1.0.0             | CraftStudio-1.0.0.93-mc1.12-alpha.jar             | None                                     |
	| LCHIJA | energymeters         | 1.0.2             | energymeters-1.12.2-1.0.2.jar                     | None                                     |
	| LCHIJA | forgelin             | 1.8.2             | Forgelin-1.8.2.jar                                | None                                     |
	| LCHIJA | futuremc             | 0.2.6             | future-mc-0.2.10.1.jar                            | None                                     |
	| LCHIJA | geckolib3            | 3.0.30            | geckolib-forge-1.12.2-3.0.31.jar                  | None                                     |
	| LCHIJA | gravestone           | 1.10.3            | gravestone-1.10.3.jar                             | None                                     |
	| LCHIJA | hbm                  | hbm-1.6.9A-1.12.2 | hbm-1.6.9a-G.jar                                  | None                                     |
	| LCHIJA | waila                | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| LCHIJA | icbmclassic          | 1.12.2-4.0.1.75   | ICBM-classic-1.12.2-4.0.1b75.jar                  | None                                     |
	| LCHIJA | inventorypets        | 2.0.15            | inventorypets-1.12-2.0.15.jar                     | None                                     |
	| LCHIJA | ironchest            | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                   | None                                     |
	| LCHIJA | journeymap           | 1.12.2-5.7.1      | journeymap-1.12.2-5.7.1.jar                       | None                                     |
	| LCHIJA | lightningrods        | 1.0.0             | LightningRods-1.12.2-1.0.1.jar                    | None                                     |
	| LCHIJA | lucky                | 7.6.0             | lucky-block-forge-1.12.2-2.0.jar                  | None                                     |
	| LCHIJA | mca                  | 6.1.0             | MCA-1.12.2-6.1.0-universal.jar                    | None                                     |
	| LCHIJA | mutantbeasts         | 1.12.2-1.0.2      | MutantBeasts-1.12.2-1.0.2.jar                     | None                                     |
	| LCHIJA | nuclearcraft         | 2.18zzz           | NuclearCraft-2.18zzz-1.12.2_1.jar                 | None                                     |
	| LCHIJA | harvestcraft         | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zg.jar                   | None                                     |
	| LCHIJA | refinedstorage       | 1.6.16            | refinedstorage-1.6.16.jar                         | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | refinedstorageaddons | 0.4.5             | refinedstorageaddons-0.4.5.jar                    | None                                     |
	| LCHIJA | thermalfoundation    | 2.6.7             | ThermalFoundation-1.12.2-2.6.7.1-universal.jar    | None                                     |
	| LCHIJA | thermalexpansion     | 5.5.7             | ThermalExpansion-1.12.2-5.5.7.1-universal.jar     | None                                     |
	| LCHIJA | thermalcultivation   | 0.3.1             | ThermalCultivation-1.12.2-0.3.1.8-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermaldynamics      | 2.5.6             | ThermalDynamics-1.12.2-2.5.6.1-universal.jar      | None                                     |
	| LCHIJA | thermalinnovation    | 0.3.1             | ThermalInnovation-1.12.2-0.3.1.8-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | travelersbackpack    | 1.0.35            | TravelersBackpack-1.12.2-1.0.35.jar               | None                                     |
	| LCHIJA | twilightforest       | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar     | None                                     |
	| LCHIJA | waystones            | 4.1.0             | Waystones_1.12.2-4.1.0.jar                        | None                                     |
	| LCHIJA | worldedit            | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| LCHIJA | midnight             | 0.3.5             | themidnight-0.3.5.jar                             | None                                     |
	| LCHIJA | totemexpansion       | 1.2.2             | totemexpansion-1.2.2-1.12.2.jar                   | None                                     |

	Loaded coremods (and transformers): 
ReachFixPlugin (ReachFix-1.12.2-1.0.5.jar)
  meldexun.reachfix.asm.ReachFixClassTransformer
CQRPlugin (Chocolate_Quest_Repoured-1.12.2-2.6.12B.jar)
  team.cqr.cqrepoured.asm.CQRClassTransformer
midnight (themidnight-0.3.5.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
FutureMC (future-mc-0.2.10.1.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 3
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 512.78
	OpenGlRenderer: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by Howdidibreakit** [comment]
Well, your a RBMK seems to have blown up, and the debris is somehow causing the problem. You'll have to go into your world folder and remove the block, if you can't do that, you'll have to remove the entire chunk.
