### ISSUE TITLE
steam engine cant be used at full power

### ISSUE THREAD

**Issue by Bencek123** [HbmMods/Hbm-s-Nuclear-Tech-GIT#819]
hello there. In the Hbm version X4417 do to for some reason the fluid ducts cant transmit steam fast enough to the steam engine, so because of that it cant run at full power it just eats the steam instantly and after that the steam need some time to arrive again.
Anyway to make the transmission of these ducts instant?

**Comment by HbmMods** [comment]
That's a flaw of the old fluid system which is being phased out. Many things already use the new one, and ducts already exist, but they are currently unobtainable. You could place barrels for buffering in and outputs since those use the new system which transfers fluids at a per-tick basis.

**Comment by Bencek123** [comment]
thank you for the reply.
