### ISSUE TITLE
[1.7.10_1.0.27_X4417] Neutrino Lens ID Bug

### ISSUE THREAD

**Issue by Sapounakis45** [HbmMods/Hbm-s-Nuclear-Tech-GIT#822]
At the latest update 4417 (1.7.10) i am trying to use the Neutrino lens and they dont appear to be working neither in my server nor in a test world. I linked it to a satellite as requested by the description of the item.

I have the HUD to "ON" and using the T-45 Power armor. I am providing some screenshots to help understand the problem.

Do i do something wrong?

![image2](https://user-images.githubusercontent.com/119158184/204127371-8a0307d1-9489-4e1a-9caf-283bcbb77602.png)
![image1](https://user-images.githubusercontent.com/119158184/204127372-52edd3f9-a2b8-4f7c-89c0-038e53890c79.png)
![image](https://user-images.githubusercontent.com/119158184/204127374-4cd0f787-0d5b-4f32-96e4-72d34b056c63.png)

![2022-11-27_11 07 45](https://user-images.githubusercontent.com/119158184/204127385-62ad4408-6159-4dd0-9734-fa41101c9376.png)
![2022-11-27_11 07 41](https://user-images.githubusercontent.com/119158184/204127386-fe1b93b5-4fe6-403e-9a1a-db61088b811b.png)

-The last 2 photos are a test of the thing put to work. The github changelog suggests it can identify oil , put in the test though behind the wall nothing shows up.

**Comment by Sapounakis45** [comment]
EDIT : i did more testing and found out that the Satellite on ID 0 , while the Lens had the ID of 98786 , actually made the thing work

**Comment by HbmMods** [comment]
Thank you for reporting, while this had been a known issue for a while now, that last detail was just what I needed. Should be fixed in X4431, I'm leaving the issue open for now.

**Comment by Sapounakis45** [comment]
> Thank you for reporting, while this had been a known issue for a while now, that last detail was just what I needed. Should be fixed in X4431, I'm leaving the issue open for now.

I saw that a little late , Thanks for Replying and solving the issue. i might test the new version out and update you if you need to close the issue
