### ISSUE TITLE
Inconsistency between stated efficiency and actual efficiency of Leviathan Turbine

### ISSUE THREAD

**Issue by TehTemmie** [HbmMods/Hbm-s-Nuclear-Tech-GIT#824]
NTM Version 1.0.27X4431 (Though the bug has probably existed since steam turbines were reworked to have efficiencies)

The leviathan turbine lists its efficiency as 85%, but it actually produces the same amount of energy as the industrial turbine, which lists its efficiency as 100%. It also produces more energy than the steam engine or single-block turbine, both of which also list their efficiencies as 85%.

**Comment by HbmMods** [comment]
Fixed in X4438.
