### ISSUE TITLE
Automatic I/O puts items into wrong slots in barrels

### ISSUE THREAD

**Issue by TehTemmie** [HbmMods/Hbm-s-Nuclear-Tech-GIT#825]
NTM Version: 1.0.27X4431
Automated I/O tiles (e.g. hoppers and conveyor inserters) put filled containers into the slot for filling containers (the upper right slot) and empty containers into the slot for emptying containers (the upper middle slot) when inserting items into barrels. In other words, filled and empty containers' slots are swapped when trying to automate insertion.

Below is an image of what happens when I put a stack of filled and empty fluid tank items into a conveyor inserter, with the filled tanks being put first:
![image](https://user-images.githubusercontent.com/36060353/204572318-07b37a00-3b1e-438e-aa1a-ce97cffbd1e7.png)

**Comment by HbmMods** [comment]
Fixed in X4438.
