### ISSUE TITLE
Fallout Config doesn't read/write all parameters from/to json

### ISSUE THREAD

**Issue by TehTemmie** [HbmMods/Hbm-s-Nuclear-Tech-GIT#826]
NTM Version: 1.0.27X4431
The default NTM fallout config has different min and max ranges for several block conversions (fallout entries). Several fallout entries also have differing "primary conversion" chances. None of these parameters (minDist, maxDist, primaryChance) nor the "isSolid" tag are read from hbmFallout.json. Additionally, when writing the default config to _hbmFallout.json, minDist and maxDist are not written, nor is the "isSolid" tag.

The above paragraph in table form:
Parameter		Missing Operations (R/W)	Used in default config?
minDist			RW						Yes
maxDist			RW						Yes
primaryChance	R						Yes
isSolid			RW						No

**Comment by HbmMods** [comment]
Should be fixed in X4438, haven't tested it though.

**Comment by TehTemmie** [comment]
Finally got around to testing hbmFallout.json after over a month (using version 1.0.27 X4474), here are the issues I've noticed:
1. Chances in the config that are below 100% are treated as 0% due to it being read as an integer instead of a double.
2. maximumDistancePercent is read as minDist, overwriting the value from minimumDistancePercent.

**Comment by HbmMods** [comment]
Should be fixed in X4476.
