### ISSUE TITLE
New fluid system is not working - it  makes tech be just expensive decoration that dont even do anything

### ISSUE THREAD

**Issue by username90001** [HbmMods/Hbm-s-Nuclear-Tech-GIT#829]
i did a refinery and conected heavy oil to fluid burner and it not working i even tried boxpipes after i tried to connect industrial turbine to boiler and no steam input return old fluid system new fluid system is broken trash

**Comment by HbmMods** [comment]
> return old fluid system new fluid system is broken trash

The old system still exists, the pipes haven't been changed at all, any older setups continue to work the way they have before and working around any broken bits in the new system is incredibly easy, all of which things you would have known if only you had read the changelog.
