### ISSUE TITLE
[Question] Cannot use/Unable to get Redstone-over-Radio Receiver and Transmitter working

### ISSUE THREAD

**Issue by Antineutrino-4444** [HbmMods/Hbm-s-Nuclear-Tech-GIT#830]
Just like the title suggests, how to use the Redstone-over-Radio Receiver and Transmitter? With setting the same frequency for both the receiver and transmitter, even the transmitter have a signal, but the receiver does not have any redstone output.

**Comment by HbmMods** [comment]
Could you send a screenshot of how the transmitter is connected to the redstone input? In order for it to pick up the input, the block that it is connected to has to receive the signal, just like how one would toggle a normal redstone torch. Also make sure that both transmitter and receiver either use "Redstone Passthrough" or a valid custom signal mapping.

**Comment by Antineutrino-4444** [comment]
Can I please ask how does the custom signal mapping works? I just found out that the receiver have to be pointed directly but it still cannot travel to other places

**Comment by HbmMods** [comment]
The custom map translates an incoming signal (0-15) to any chosen message and vice versa. With the current set of RoR blocks this has very limited uses, but one could for example use a single transmitter torch that sends a custom message based on the input signal's strength to toggle up to 16 receivers, although only one at a time. The feature will make more sense once signals can be used in more ways than just redstone, for example a pager that displays a message on screen or perhaps a control signal setting the parameters for a machine.

**Comment by Antineutrino-4444** [comment]
Alright! Thanks for helping me out!
