### ISSUE TITLE
[Question and possible bug] Structures gen

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#834]
### Describe the bug

I have read in the changelog that some structures are no more, what are these structres? I ask because from what I interpreted I believe Ive seen a few of them generate afterward. if this is the case I will investigate this further to confirm its a bug and make a report on it on further investigation

thanks in advance

**Comment by Vaern** [comment]
The only structures removed so far are the helipad / radio shack. It's impossible for them to generate anymore, as the classes and code handling their generation no longer exist.

**Comment by Shibva** [comment]
can ya give me a visual on the 2? ill take your word on it, just curious to comfirm I am thinking of radio shack as the one im thinking on

**Comment by Vaern** [comment]
They're always paired together, so there shouldn't be any confusion. Even on worlds from previous versions, their generation should no longer occur.

**Comment by Shibva** [comment]
wait, is it the large antenna tower?

**Comment by Vaern** [comment]
Nope

**Comment by Shibva** [comment]
ok, im guessing its the other one then, the one that looks like a station 


heh, guess it went out of bussness like the real counterpart did XD

**Comment by redshadow3** [comment]
> heh, guess it went out of bussness like the real counterpart did XD

haha
