### ISSUE TITLE
cant find the .json for changing how much oil is extracted from one oil deposit block

### ISSUE THREAD

**Issue by redshadow3** [HbmMods/Hbm-s-Nuclear-Tech-GIT#838]
i cant find where i need to edit to change the amount of oil that can be generated from a single oil deposit block, i checked the config .json's but i cant find it

yes you dont need to tell me this is a skill issue, im bad at searching

**Comment by HbmMods** [comment]
It's in `.minecraft/config/hbmConfig/hbmMachines.json`, the entries for the oil pumps should be the ones on the very bottom.

**Comment by redshadow3** [comment]
im dumb, the config wasnt changed as i didnt actually run the mod before trying to edit it, thanks for the update and new industrial generator though!
