### ISSUE TITLE
deuterium production chemical plant problem

### ISSUE THREAD

**Issue by redshadow3** [HbmMods/Hbm-s-Nuclear-Tech-GIT#840]
the production of deuterium in the chemical plant requires 8000 heavy water to produce only 400 liquid oxygen and 400 deuterium, and no this isnt a typo (why would you expect that in a bug report?), 8000 heavy water for 400 LOX and 400 deuterium

**Comment by HbmMods** [comment]
Values are as intended and consistent with the second electrolysis recipe.
