### ISSUE TITLE
(QUESTION) why does deuterium production require 8000 heavy water for just 400 lox and 400 deuterium?

### ISSUE THREAD

**Issue by redshadow3** [HbmMods/Hbm-s-Nuclear-Tech-GIT#842]
i set this as a bug earlier but HBMmods replied this is intended, why? its not fun having to place like over 100 deuterium towers just for one fusion reactor

**Comment by SoB1nary** [comment]
You don't need over a hundred - you need like ten. I would recommend increasing the amount of water you give your towers instead of increasing their amount. You need A LOT of water - like 6 heavy infinite barrels.

**Comment by redshadow3** [comment]
> You don't need over a hundred - you need like ten. I would recommend increasing the amount of water you give your towers instead of increasing their amount. You need A LOT of water - like 6 heavy infinite barrels.

i have 4 heavy infinite water barrels and theyre full even when the plasma heater is out of deut

edit: also the problem is the chemical plants take WAY too much, its not a typo in the title

**Comment by SoB1nary** [comment]
You're wrong, lmao.

**Comment by redshadow3** [comment]
![2022-12-11_14 02 32](https://user-images.githubusercontent.com/106045016/206905200-dfa31688-ca37-455f-a670-d2290f6e827e.png)


> You're wrong, lmao.

**Comment by 7pheonix** [comment]
do you by any chance have thermos or any other optimisation mods/plugins installed

**Comment by redshadow3** [comment]
> do you by any chance have thermos or any other optimisation mods/plugins installed

foamfix and betterfps due to lag from loading a  lot of blown-up caves
it didnt help much though
also HBMmods said this:  "Values are as intended and consistent with the second electrolysis recipe.", although he is right, the cryo-electrolysis uses 8000 water for only 800 liquid hydrogen and 800 liquid oxygen which would be 1600, so he didnt lie but then the other recipe is also broken

edit: removing both didnt do anything,i have other mods installed though but i dont think they use anything that could interfere
these are mods that dont add stuff like blocks and items: worldedit, NEI ,journeymap , waila and wawla

ill run HBM alone and see if it is also broken, then if it is then its HBM's problem not incompatibility

**Comment by redshadow3** [comment]
> ill run HBM alone and see if it is also broken, then if it is then its HBM's problem not incompatibility

nope it still says 8000 on both recipes

**Comment by 7pheonix** [comment]
again, It’s intended, and for a standard fusion setup you should only need at the most around 20 towers

**Comment by redshadow3** [comment]
> again, It’s intended, and for a standard fusion setup you should only need at the most around 20 towers

52 towers, 8 heavy water barrels, 4 chemical plants and the towers and chemical plants still cant keep up with the fusion reactor
and why is 8000 intended in them? like the water in cryo-electrolysis doesnt shrink about 6x in size does it?
and over shrink in size over 8x in the heavy water cryo-electrolysis

also why would you ask if i have plugins or optimization mods installed if it was intended?

**Comment by redshadow3** [comment]
oh i see the problem, the deuterium towers have connections at the bottom sides right? well those are specified whether "this side is input and this side is output" why couldnt they make it input/output like on chemical plants, and why are those recipes made to ignore the conservation of mass?
