### ISSUE TITLE
Mining Satellites Produce Less Resources Than They Should

### ISSUE THREAD

**Issue by TehTemmie** [HbmMods/Hbm-s-Nuclear-Tech-GIT#845]
NTM Version: 1.0.27X4445
The landing pad for mining satellites (specifically the "AddToInv()" function) seems to treat all "loot" stack sizes as equal to 1 even if the stack size in the loot table is greater than 1 (e.g. If the miner rolls a stack of 48 moon turf, it will only add 1 turf instead of 48). This reduces the yield of most mining satellite loot, especially moon turf.

**Comment by HbmMods** [comment]
oops

**Comment by HbmMods** [comment]
Fixed in X4473.
