### ISSUE TITLE
ams reactor does not give energy!, dfc not working!

### ISSUE THREAD

**Issue by TheMgfeedthebeast** [HbmMods/Hbm-s-Nuclear-Tech-GIT#846]
hello! just made an ams reactor and it does not give power out and requires batteries to feed the stabilizers / can't use copper cables.
![Capture](https://user-images.githubusercontent.com/96387416/208299054-6c0cd94a-91e3-4a96-bb27-63431007e0e5.jpg)

**Comment by ncr-t** [comment]
The AMS reactor’s functionality is no longer present in the mod. it’s only a decorative structure now.

**Comment by TheMgfeedthebeast** [comment]
ohh

**Comment by TheMgfeedthebeast** [comment]
and also the dfc reactors act funny

**Comment by TheMgfeedthebeast** [comment]
followed some tutorials and the did not work the reactor just exploded tried it like 10 times

**Comment by username90001** [comment]
get stability field and also do not try use it without chunk loading block mods or else u will get hiroshima if u forget to disable it when rejoining game

**Comment by TheMgfeedthebeast** [comment]
What do you mean by stability field?

**Comment by username90001** [comment]
stabilizer laser

**Comment by TheMgfeedthebeast** [comment]
like the lens, of course i use it

**Comment by username90001** [comment]
i mean dfc

**Comment by TheMgfeedthebeast** [comment]
yeah i use it

**Comment by TheMgfeedthebeast** [comment]
i know thats not the problem

**Comment by TheForge129** [comment]
whar?

**Comment by TheMgfeedthebeast** [comment]
i made a looping dfc reactor and it has lots of issues, like just exploding

**Comment by redshadow3** [comment]
maybe youre feeding it too much power?
