### ISSUE TITLE
giving visuals to duct connecting blocks that are not full-blocks visualy [low priority]

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#850]
### Describe the bug

im not exacaly sure how to word this so heres a picture to help describe what I mean

<img width="277" alt="image" src="https://user-images.githubusercontent.com/38770780/208500156-c52a7662-0811-408f-9883-206b9387a9d9.png">
the gap here is what im refering to, maybe adding some sort of popup that can connect visualy in some way to the pipe

**Comment by username90001** [comment]
this is not bug this is because of model

**Comment by redshadow3** [comment]
> this is not bug this is because of model

if its not a bug its still an issue but the duct system was just redone so there is a lot of this happening

**Comment by username90001** [comment]
it has to look like this  probaly

**Comment by HbmMods** [comment]
Not planned.
