### ISSUE TITLE
When filter used on PaA Hazmat suit gives boots

### ISSUE THREAD

**Issue by RandomMinecraftPlayer** [HbmMods/Hbm-s-Nuclear-Tech-GIT#851]
It gives a new pair of the boots I was wearing when used the filter combo

**Comment by HbmMods** [comment]
Were you in creative mode at the time you equipped the boots? There's apparently a syncing issue that causes boots to be duplicated when equipping them with shift-click, but it only happens sporadically and with all types of boots so I'm guessing it's a vanilla bug.

**Comment by RandomMinecraftPlayer** [comment]
I just right clicked in creative
