### ISSUE TITLE
Desh is being shown as my error and its invisible in recipes

### ISSUE THREAD

**Issue by frugal200** [HbmMods/Hbm-s-Nuclear-Tech-GIT#853]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.
 

So the desh ingots in recipes is invisible and is being called "I AM ERROR" and we knowing its desh put desh in the recipe and in the assembly machine to craft the item but even the assembly machine doesnt understand its desh so it doesnt craft . how do i fix this i tried reinstalling the jar for the mod . 
![image](https://user-images.githubusercontent.com/87532525/209117096-8df417d6-d8ca-4df6-a4e1-46eda39fc47b.png)

**Comment by redshadow3** [comment]
see if removing any other mod might fix it, i can see you have mekanism so im pretty sure you have more mods than just a pair so again try removing other mods

**Comment by Howdidibreakit** [comment]
Do any other templates have this bug with desh? Do you have galacticraft installed? Also, try checking the ID for Desh, it could be a problem with the thing trying to retrieve the desh name and checking for it, but it doesn't get the right item and just counts it as null, as in the code when it encounters a null thing it says "I AM ERROR". Also nice power armor (how do you have schrabidium but not desh tools?)

**Comment by Howdidibreakit** [comment]
Has the bug been fixed yet?
