### ISSUE TITLE
Reasim In/Outlets

### ISSUE THREAD

**Issue by OlorinIV** [HbmMods/Hbm-s-Nuclear-Tech-GIT#855]
### Describe the bug

RBMK Reasim inlets and outlets still use the old, deprecated fluid system for their upper and under surfaces.

**Comment by redshadow3** [comment]
good that i read this before running my reasim rbmk

**Comment by Canesven** [comment]
Sometimes ReaSim RBMK also creates a problem with negative water

**Comment by HbmMods** [comment]
Fixed in X4473.
