### ISSUE TITLE
Two press recipes for coal dust

### ISSUE THREAD

**Issue by MCNaOtlichnoYT** [HbmMods/Hbm-s-Nuclear-Tech-GIT#859]
Press has two recipes which take in coal dust and a flat stamp. The first one gives coal, the second one gives coal briquettes. In fact, the first one is performed if you insert these resources.
Maybe the recipe for coal should be changed or even removesd. Lignite dust has only a recipe for briquettes.
![2022-12-28_23 37 14](https://user-images.githubusercontent.com/105880094/209869904-c512c321-02fb-4103-8eca-0988715f28f9.png)
![2022-12-28_23 37 15](https://user-images.githubusercontent.com/105880094/209869906-12b00056-fca1-44ee-a69e-f68380aabe11.png)

**Comment by MCNaOtlichnoYT** [comment]
![2022-12-12_21 32 34](https://user-images.githubusercontent.com/105880094/209869947-7723f28b-6b18-473e-b4f4-1b99aeebe46d.png)

**Comment by redshadow3** [comment]
yeah the briquettes should be the only recipe cos the flat stamp to coal doesnt make sense as coal on its own is naturally formed and not just a flat item (unless you dont want it to be realistic)

**Comment by HbmMods** [comment]
Fixed in X4473.
