### ISSUE TITLE
What are gas shales for?

### ISSUE THREAD

**Issue by redshadow3** [HbmMods/Hbm-s-Nuclear-Tech-GIT#861]
i've been thinking what gas shales are for, theyve been in the mod for very long but seem to server no purpose, they just get treated as stone by derricks and pumpjacks, theyve become a part of the world through world generation but idk how to extract them can someone tell me what theyre for?

**Comment by OlorinIV** [comment]
1.This is not an issue, go to discord or somewhere else for these questions later on.
2.Gas shales are items like mercury droplets, placing them in input slots of containers marked 'Petroleum Gas' will give you 250mB of petroleum gas, which could be used directly to craft polymer bars in a chemplant.

**Comment by redshadow3** [comment]
> 1.This is not an issue, go to discord or somewhere else for these questions later on.

there is a question label which is confusing but thanks for the answer, (though i think it should be extractable with derricks or pumpjacks)
