### ISSUE TITLE
we need fluid valve

### ISSUE THREAD

**Issue by username90001** [HbmMods/Hbm-s-Nuclear-Tech-GIT#862]
we just need it

**Comment by redshadow3** [comment]
the issues tab is not for suggestions

**Comment by redshadow3** [comment]
it coul work just like how the power storage blocks do, change input output state depending if redstone input is on or off, youll know what i mean

**Comment by HbmMods** [comment]
Valves, both with redstone functionality and flow restrictions much like how there's power switches and diodes are already confirmed.
