### ISSUE TITLE
The Conveyor Sorter is crashing my game[bug]

### ISSUE THREAD

**Issue by Easebola** [HbmMods/Hbm-s-Nuclear-Tech-GIT#866]
NTM Version:1.0.27X4445
This morning, while trying to make spent nuclear fuel reprocessing, one of the conveyor sorters crashed the game while entering a double-link fuel rod.
By analyzing the crash report, I found that this seems to be an issue with the sorter.
Subsequently, just as I tried to enter this save again, the game crashed again.

**Comment by HbmMods** [comment]
Do you have the actual crash report?

**Comment by Canesven** [comment]
[crash-2023-01-13_17.47.32-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/10410289/crash-2023-01-13_17.47.32-server.txt)
This is another crash due to Conveyor Sorter
@HbmMods

**Comment by HbmMods** [comment]
Should be fixed in X4480, although since I can't replicate the crash I don't have any means of verifying it.
