### ISSUE TITLE
RBMK meltdown crashed my game

### ISSUE THREAD

**Issue by Easebola** [HbmMods/Hbm-s-Nuclear-Tech-GIT#869]
Today, my RBMK reactor crashed due to a lack of water supply, but my game crashed after the reactor meltdown.
According to the Minecraft crash report, I found out that this was about crashed caused by TileEntityRBMKRod.java.

**Comment by HbmMods** [comment]
Could you please provide the actual crash report

**Comment by EMEnderMan2581** [comment]
![image](https://user-images.githubusercontent.com/94626653/211269515-0d0227da-c951-47f8-883e-34640fce3cfe.png)

**Comment by ncr-t** [comment]
Please provide the entire crash report, as it gives much more context to everything.

**Comment by Canesven** [comment]
[crash-2023-01-09_13.33.27-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/10371708/crash-2023-01-09_13.33.27-server.txt)

**Comment by HbmMods** [comment]
Fixed in X4473.
