### ISSUE TITLE
Sound bugs

### ISSUE THREAD

**Issue by Howdidibreakit** [HbmMods/Hbm-s-Nuclear-Tech-GIT#870]
### Describe the bug
I can't tell if this is just a quirk with Minecraft's sound system, but, noticeably with the centrifuge, when it gets done with the sound once, it doesn't play the sound again without reloading chunks. I think this is a bug with the duration of the centrifuging being shorter than the duration of the sound, causing it to try to play the same sound file in the middle of playing the sound file, and that just completely breaks it. Or you just didn't make it loop like the shredder. Either way, still annoying. (also the shredder's blades only turn yellow in the gui when they are literally on their last limb on durability)

**Comment by Howdidibreakit** [comment]
Is uuh, nobody gonna try to help me with this? Has nobody even seen this yet?

**Comment by Shibva** [comment]
Ya know. Your not the only one experiencing this. I've seem to have ALSO noticed my game not playing any sounds for the machines when passively running.

Do you have any other mods? If so try creating a separate instance and performing the Binary method to see if the issue resolves to narrow down what mod(s) could be causing it 

It's all I can offer up without more information like your mod list

**Comment by Howdidibreakit** [comment]
I don't know exactly what mods off the top of my head, but I know there's.
Compact machines, Looking glass, mystcraft, applied energistics 2*, Caveworld*, tinkers construct, voxels*, nuclear tech mod, morph mod, ichunutil, primative mobs*, worldmap*, and I think like, 2 others that I don't remember.
*Error happened before these mods were added

**Comment by HbmMods** [comment]
Looped sounds should be fixed now since sounds now restart themselves properly when canceled and canceling should happen way less frequently due to the higher sound cap.
