### ISSUE TITLE
Some nukes can break bedrock

### ISSUE THREAD

**Issue by TehTemmie** [HbmMods/Hbm-s-Nuclear-Tech-GIT#873]
Version 1.0.27X4474 (I know I'm not consistent with how I state the version, even when I make several reports at around the same time)

The high yield mini nuke, which probably shouldn't be able to break bedrock, can do so anyways. This seems to only happen if there is a block with lower blast resistance nearby that the nuke can destroy, and may take multiple nuclear explosions. Other more powerful nukes may do the same thing (untested). Regular mini nukes don't appear to break bedrock (tested in-game).

**Comment by HbmMods** [comment]
All nukes that use the larger algorithm have a special condition where in a small radius (depending on blast strength), it will simply delete all blocks no matter the blast resistance, and high yield mini nukes have such a small radius that it takes a lucky hit for it to work. Not exactly a bug per-se, but it would be better to have an added condition that prevents holes in the bedrock floor.

**Comment by Howdidibreakit** [comment]
Yeah, better yet, (This might be already in the config) being able to turn off bedrock breaking, including black holes. I'm sure that the black hole code for destroying blocks works something like this. CheckforBlock, If air, then don't destroy, if else, then turn into the corresponding entity and remove the block. The way to integrate this would be simple, If air then don't destroy, if bedrock don't destroy. It's probably completely different than what I think it might be but that's as much as I know.

**Comment by HbmMods** [comment]
This used to be a bug where the MK5's "skip ahead" function would go into the negatives and break blocks that it shouldn't in a small radius, including bedrock. Mini nukes usually don't have the necessary yield to break bedrock even within the inner threshold.
