### ISSUE TITLE
Dark Matter Recipe in NEI

### ISSUE THREAD

**Issue by poisontrigger** [HbmMods/Hbm-s-Nuclear-Tech-GIT#876]
Recipe in 1.7.10 (1.0.27_X4445 - version used -- custom fork with Virus removed ) shows 100,000 Coil Strength where it should be 200,000

**Comment by HbmMods** [comment]
The recipe is defined as requiring 100,000, where are you getting the other number from?

**Comment by poisontrigger** [comment]
The Wiki Says 200,000 and when I tried it in-game with 40 Chlorophyte Coils (2500 ea) total of 100,000, it said more coil strength required.

**Comment by HbmMods** [comment]
> 40 Chlorophyte Coils (2500 ea) total of 100,000

Keep in mind that coils around the core and on the outer edge of corners aren't counted, in general you should never build an accelerator that hits the required number just barely. You can confirm this by looking into the stats tab, it will show the total coil strength of the previous run.

**Comment by Shibva** [comment]
> Recipe in 1.7.10 (1.0.27_X4445 - version used -- custom fork with Virus removed ) shows 100,000 Coil Strength where it should be 200,000 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

Just out of curiosity
Why did you remove the virus? (Assuming the ones in the mod that destroy the world). There's a config for that and it's disabled by default
