### ISSUE TITLE
How can I find minerals in bedrock?

### ISSUE THREAD

**Issue by Hacker6400** [HbmMods/Hbm-s-Nuclear-Tech-GIT#877]
i can't find the bedrock ore and i not have any idea to extract

**Comment by HbmMods** [comment]
Bedrock ore generates under square patches of depth rock, unlike depth nodes which are spherical.

**Comment by redshadow3** [comment]
> Bedrock ore generates under square patches of depth rock, unlike depth nodes which are spherical.

what about bedrock oil deposits?

also i think it might be possible to destroy bedrock oil deposit cos i was doing explosive mining and found an empty area in bedrock, the explosives i used werent strong enough to destroy depth rock though

**Comment by HbmMods** [comment]
Bedrock oil can be seen from the surface from the patches of oily dirt/sand it generates.
