### ISSUE TITLE
Industrial Mixer Battery Slot Doesn't work

### ISSUE THREAD

**Issue by datboiiskool** [HbmMods/Hbm-s-Nuclear-Tech-GIT#878]
I tried putting a self-charging battery in the battery slot, but it doesn't charge the machine.
![im_bug](https://user-images.githubusercontent.com/79916314/212457140-90f851b3-9b5d-4288-a6b8-b1aeed05b0f7.png)

**Comment by HbmMods** [comment]
Fixed in X4480.
