### ISSUE TITLE
Some of the effects of the firestorms don't work

### ISSUE THREAD

**Issue by sdddddf80** [HbmMods/Hbm-s-Nuclear-Tech-GIT#882]
### Describe the bug

Some of the effects of the firestorms don't work,such as boilers won't heat up, barrels filled with water won't explode, cooling towers still  work and RBMK parts won't heat up on their own
![2023-01-15_13 46 31](https://user-images.githubusercontent.com/53573250/212526551-139a2074-cbc9-4294-9a6f-1164ef82e0f7.png)
![2023-01-15_13 46 42](https://user-images.githubusercontent.com/53573250/212526558-5b2c018c-91a0-40f2-99a1-464149f87142.png)
![2023-01-15_14 19 07](https://user-images.githubusercontent.com/53573250/212526560-11b13a49-6e48-4e8f-9f2c-8fddc6a35213.png)
![2023-01-15_14 31 43](https://user-images.githubusercontent.com/53573250/212526563-084391b5-e15c-4a80-9aca-929da207e736.png)

**Comment by HbmMods** [comment]
Fixed in X4480.
