### ISSUE TITLE
Screen zooms in when I hold an item.

### ISSUE THREAD

**Issue by Jooj-0808** [HbmMods/Hbm-s-Nuclear-Tech-GIT#886]
### Screen zooms in when I hold an item.

The screen zooms in whenever I hold any item. I am using the most recent version and have re-installed both forge and the mod multiple times.

**Comment by Howdidibreakit** [comment]
Any other mods? if not, then no clue.

**Comment by Howdidibreakit** [comment]
Make sure Minecraft is running on your dedicated GPU.

**Comment by Jooj-0808** [comment]
Alright

**Comment by Jooj-0808** [comment]
Worked.
