### ISSUE TITLE
Tool suggestion

### ISSUE THREAD

**Issue by Howdidibreakit** [HbmMods/Hbm-s-Nuclear-Tech-GIT#887]
Radioactive materials are dangerous, sometimes you literally cannot hold some stuff, so how about a tool to fix that?
The Radiation Hazard Holding Bag, it's a lead bag, you can hold up to 8 radioactive items in each of the 5 slots. (like, every slot has a stack cap of 8, but there are 5 slots). When holding radioactive material in there, it divides the radiation by 4, and when held in main hand, you can automatically put it in the bag when picking up a radioactive item. (Like if there was a balefire shard on the ground, if you held the bag out while you picked up the shard, it would instantly be in the bag.). It would be crafted in the assembly machine with;
x4 Lead plates
x2 Rope
x2 Advanced Hazard Cloth (I forgot the name)
Takes 10 seconds to make.
I think this would be a great addition to the game, helpful for mid game when dealing with spent rods, and late game when dealing with balefire.

**Comment by Howdidibreakit** [comment]
I mean, I think you were already thinking of adding this, with the lead box.

**Comment by username90001** [comment]
u dont need this any mod with backpack or in inventory storage things protect u from radiation also iron crate or steel can work too

**Comment by OlorinIV** [comment]
Look, you could give yourself an injection of taint and sniff some cloud. That would make you invincible against rad.

**Comment by Antineutrino-4444** [comment]
well that is a bit expensive
but if it is late game then obviously a pretty good solution :>

> Look, you could give yourself an injection of taint and sniff some cloud. That would make you invincible against rad.

**Comment by Howdidibreakit** [comment]
username90001 ever consider that that's not intended? If it works, then use it, but it's not supposed to be the way it is for those things. And how would you grab anything thats very radioactive with that?

**Comment by username90001** [comment]
Auto collect droped items into backpack 
or use hopper that will make radiactive things to into iron chest or steel

**Comment by Howdidibreakit** [comment]
You answered one half of the problem. This still wasn't intended, sure, you're free to do it with other mods, but it's not what the mod author may have intended, bob or the backpack guy.

**Comment by OlorinIV** [comment]
> well that is a bit expensive but if it is late game then obviously a pretty good solution :>
> 
> > Look, you could give yourself an injection of taint and sniff some cloud. That would make you invincible against rad.

Late game seriously? I reckon it'd be possible to speedrun the whole setup in 1 hour if lucky enough.

**Comment by Howdidibreakit** [comment]
Yeah, that you can do as well, but it'd be useful for carrying nuclear fuel as well, since nobody would get tainted heart just to walk over to the reactor with their rods, but still don't want to get a LOT of rads. Like an intermediate between nullification and dealing with it.

**Comment by HbmMods** [comment]
![grafik](https://user-images.githubusercontent.com/16674258/220342841-347d6de0-37d7-4530-ae13-d1555cef4d3c.png)

lad

**Comment by Howdidibreakit** [comment]
Does it work?

**Comment by Howdidibreakit** [comment]
I'm gonna close this because it's been here for too long, I assume that's what the lead box is going to do, or something similar
