### ISSUE TITLE
Create recipe and item another mod

### ISSUE THREAD

**Issue by Phillanor** [HbmMods/Hbm-s-Nuclear-Tech-GIT#892]
how to add a recipe to the HBM Nuclear tech mod to get an item from another mod?

**Comment by OlorinIV** [comment]
If you're asking for crafting table recipes, there is a mod called CraftTweaker.
If you're asking for NTM-introduced recipes, there is a config file that could customize recipes.
Example shown below:
The Centrifuge:
![企业微信截图_16745804004631](https://user-images.githubusercontent.com/104282311/214361523-7ebb6e06-7daf-4d9f-b64d-1e6c24c6f270.png)
![企业微信截图_16745803784212](https://user-images.githubusercontent.com/104282311/214361585-4c4c2d17-59f4-43ca-993a-342557234567.png)
The Cyclotron:
![企业微信截图_16745804721378](https://user-images.githubusercontent.com/104282311/214361750-7da6f751-d8a9-45a1-b4d7-b68ab4afe034.png)
![企业微信截图_16745803555825](https://user-images.githubusercontent.com/104282311/214361776-6e0fb4a0-70c8-428b-b034-a69b8ea0520a.png)

**Comment by Phillanor** [comment]
thank you, It's just that past times, for some unknown reason, changes in the config files took their original meaning when loading, and it only helped if I changed the configs in the code itself...
But it was a pretty old version of the mod..

**Comment by Phillanor** [comment]
And... it happened again...

**Comment by Howdidibreakit** [comment]
What does that mean? Do the recipes just not change?

**Comment by Phillanor** [comment]
I am changing the recipe in the files on
the config/_hbmAssembler server.json
I save, reboot the server and during the startup process I see the file being updated again, and when I open it I see that the changes have disappeared. The file has returned to its initial state.

**Comment by sdddddf80** [comment]
> 

REMOVE UNDERSCORE TO ENABLE RECIPE LOADING - RECIPES WILL RESET TO DEFAULT OTHERWISE

**Comment by OlorinIV** [comment]
delete that _ before the json files to make them work
![企业微信截图_16746159367887](https://user-images.githubusercontent.com/104282311/214471276-9e3fa6b6-183a-416d-b200-89d3f420d9d8.png)
Three files are active while others aren't. There is also a prompt message below, but that's recently added.

**Comment by Phillanor** [comment]
thank you

**Comment by Phillanor** [comment]
oh... i delete underscore
restart.. and two files:)
1._hbmAssembler
2.hbmAssembler
