### ISSUE TITLE
[Workspace] Workspace creation issues 

### ISSUE THREAD

**Issue by Shibva** [HbmMods/Hbm-s-Nuclear-Tech-GIT#895]
Following the contribution directions I downloaded the src files from the forge page and merged the files from NTM to the forge source files; I then tried to use BASH to setup the decompiled workspace but when running I ran into this error

```
Execution failed for task ':downloadClient'.
> java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/1.7.10.jar
```

This could just be me but I might need a second opinion

**Comment by Shibva** [comment]
if I recall correctly, forge did a fuckup and the original files are no longer avalable at that locatioin. if this is the case then the instructions would need to be updated.

**Comment by martemen** [comment]
Hi @Shibva,
I had the same problem and fixed it on my [fork](https://github.com/martemen/Hbm-s-Nuclear-Tech-GIT), the first two commits fixed the problem. [Commit one](https://github.com/martemen/Hbm-s-Nuclear-Tech-GIT/commit/1ecd569a28e299751d1d36e0962dfe077e39b401), [Commit two](https://github.com/martemen/Hbm-s-Nuclear-Tech-GIT/commit/77a029f8b4835176cd2ef5443bbd5b72ad1db1cc). I plan to merge my repo back to this one at some point.

**Comment by Shibva** [comment]
Does it come with IDE intogrstionn or just the fix?

**Comment by martemen** [comment]
It works for me in Intellij idea.
