### ISSUE TITLE
Ancient Pyramid not spawning

### ISSUE THREAD

**Issue by darthvader45** [HbmMods/Hbm-s-Nuclear-Tech-GIT#898]
### Describe the bug

When I go searching in deserts, I expect to find the odd concrete pyramid sticking out of the desert, filled to the brim with ancient scrap metal in its deepest depths.  However, even with both config options labeled: I:4.24_pyramidSpawn set to 10, not a single pyramid shows up, even in a customized world where the only biomes are desert, desertHills and river.

**Comment by darthvader45** [comment]
The last version I remember it working in was 1.6.4a-Gv2, which is a couple minor versions ago.

**Comment by RandomMinecraftPlayer** [comment]
Have you used the locate command?
