### ISSUE TITLE
a very interesting thing

### ISSUE THREAD

**Issue by asddsa3211233** [HbmMods/Hbm-s-Nuclear-Tech-GIT#899]
### Describe the bug

 I'm playing on version 1 7 10 I liked the new types of turrets, especially Greg's artillery and rocket artillery, but with the last update I noticed a political subtext (the person who edited the rocket artillery was Ukrainian or something like that?) We are talking about crosses (surprisingly similar to the cross of the Armed Forces of Ukraine) located on the side of this tower (I was born in Lugansk and have a dislike for the Armed Forces of Ukraine), can you remove it? Nevertheless, I hope that fashion, at least, will be out of politics (I am writing from a translator).

**Comment by ncr-t** [comment]
As you can see in many of NTM's model, there are many references to countries, there's even a russian flag on the soyuz, or the iranian flag on the centrifuges. The "politics" will stay
