### ISSUE TITLE
[1.12.2] My World Corrupts when i using HBM's NTM mod

### ISSUE THREAD

**Issue by Kazimmaster** [HbmMods/Hbm-s-Nuclear-Tech-GIT#900]
Whenever i try to join my world, this error message appears:

![BUGGG](https://user-images.githubusercontent.com/53466369/215730846-16345638-6cee-404c-89da-88970d4c9d2f.png)

Im clicking to yes and joining the world(i got backup so i don't need make a one). But when i joined the world, i see most of blocks and TileEntities (stuff comes from other mods) changed with NTM blocks (Also other mod's blocks). But When i joining without NTM mod, everything is normal.

(I would like to point out that the map was created and builded before NTM mod downloaded.)

There is some Comparison Screenshots maybe can help:

Comparison 1
Without Mod:
![Minecraft 1 12 2 31 01 2023 13_25_19](https://user-images.githubusercontent.com/53466369/215736673-c867495b-f0a9-4ea1-82fb-c16d0db975a2.png)

With Mod:
![Minecraft 1 12 2 31 01 2023 13_31_45](https://user-images.githubusercontent.com/53466369/215736789-e49faabf-4ab8-4a0b-adb7-66ae87544042.png)

Comparison 2
Without Mod:
![No NTM Apartment](https://user-images.githubusercontent.com/53466369/215737259-d7aec208-1e17-4365-b1b8-01872497ef8a.png)

With Mod (hmm... mycelium for balcony?):
![With NTM Apartment(myceliumBalcony)](https://user-images.githubusercontent.com/53466369/215737485-24fd2f21-5ba7-4eb6-8548-e5f291a68bc5.png)

Mod list:

![ModsList](https://user-images.githubusercontent.com/53466369/215738514-e2dfb1dd-ade6-4fc0-bf91-78efee5a8303.png)

I think the issue is Block ID changes that caused by mod removing, adding but im not sure. But i really need help. I don't want remove
the mod or lose the map.

**Comment by Howdidibreakit** [comment]
It seems to be something with the chisel mod, could you tell us what blocks are being replaced, and from what mod. It seems that the hbm mod is displacing the id's of another mod, also, one thing I noticed is on the first image, there's a lot of displacement around the door, and it replaces what I assume to be quartz blocks with it's own cyan concrete. As far as my knowledge goes of minecraft, this is a fault of one the mod itself (HBM) and it's only solvable by always having the mod installed. It's triggered by game crashed as well, did your game ever crash when building it?

**Comment by Kazimmaster** [comment]
No. My game didn't crashed (Thankfully it didn't. if it got crashed it can be a big issue).

>also, one thing I noticed is on the first image, there's a lot of displacement around the door, and it replaces what I assume to be quartz blocks with it's own cyan concrete.

No. Its a normal thing i just closed that place with a Bibliocraft Map Frame before world corruption (I created a quartz map frame with furniture paneler for closing cyan concrete. An alternative to closing it with littletiles. But map frames disappeared too.)


The Chisel blocks are disappeared (Transformed to Air). Replaced things are:

- Littletile Tiles transformed to Bibliocraft painting frames, NTM Coils and DFC Fuel Injectors (And maybe other things i don't know)
- MrCrayFish Furniture mod fences (Birch ones transformed to NTM Mycelium, White ones transformed to Englarite Bricks)
- MrCrayFish Furniture mod Hedges (leave styled fences) Transformed to Meteorite bricks.
- MrCrayFish Furniture mod Modern Tables Transformed to NTM Rusty Green Steel Pipes
- ArchitectureCraft Shapes are disappeared too.
- ArchitectureCraft Sawbench Transformed To Plasma Heater Compodent.
- Bibliocraft Cases Transformed to DFC Receivers.
- Bibliocraft Signs Transformed to Particle Accelerator Analysis Chamber Wall
- Techguns Bunker Door Transformed to NTM Roll of Insulatıon

That's all i know.

I fixed most places of world but im still holding unfixed version.

**Comment by Howdidibreakit** [comment]
Using JEI, can you see the block id's of the blocks being replaced and the blocks that are doing the replacing. (PS: I have no idea what I'm doing but maybe this could tell us why this is happening) There doesn't seem to be a fix that I know of, I did look up a bit, and it seems to be a dead end.

**Comment by Kazimmaster** [comment]
I did some experiments for fixing the world. I copied the zone with WorldEdit that's need for me without NTM mod and i pasted it with mod. But its ended with more mess and failure. 

The problem is on the Block ID's. When NTM mod added, most block ID's changes with new things. This is not just valid for NTM. Its valid for most mods. If you add too much mods and enter an old world that's not including most mods that you have now the world have a chance to the corrupt. This happened me before about 1-2 years ago but in that days i don't have the NTM mod. This is a Minecraft issue i think.

**Comment by Howdidibreakit** [comment]
Unfortunately, it's almost impossible to fix easily, you will have to fix the problem manually by replacing all the glitched blocks. World Edit will make it easier, but that's all. This bug also happens when you load a map that used blocks from a newer version.

**Comment by Kazimmaster** [comment]
I think i don't need go deeper for this issue. Im closing the issue. Its a Minecraft bug and its unfixable. Only way to prevent this bug, entering the worlds when everytime a mod installed, removed (for prevent major ID changes).

I memorized the changed block's new and old ID's and i replaced them using WorldEdit. There is nothing more to do. This is only way to treating corrupted places.
