### ISSUE TITLE
Super Mario RPG

### ISSUE THREAD

**Issue by Nos74** [HbmMods/Hbm-s-Nuclear-Tech-GIT#91]
Super-Mar-i-o R-P-G!
It is the on-ly one just for me.
When I play the game, I get lost in a phase.
Then I find out I'm stuck in Geno's Maze.

Super-Mar-i-o R-P-G!
It is the on-ly one just for me.
When I play the game, I get lost in a phase.
Then I find out I'm stuck in Geno's Maze.

Gimme Frog Coins!
Gimme Ice Bombs!
Gimme Frog Coins!
Gimme Mushrooms!

Gimme See Ya!
Gimme Star Rod!
Gimme Cookies!
Gimme Lamb's Lure!

I want e-everything I need,
I must play this more and more,
I need to get those damn frog coins
To pay off all my credit cards!

There are many secrets in the game!
Many of which drive some peeps insane!
Why we try to cheat in a really good game?
Just sounds like crap and it makes you look lame!

Exiting the forest is super simple:
All you do is follow these path turns
For the rest of your gaming life...

Follow Geno's route here...
Follow Geno's route here...
Follow Geno's route here...
I'm a gaming god!
![file-history-luigis-mansion-luigi-png-free-png-images-clipart-luigis-mansion-png-920_1686](https://user-images.githubusercontent.com/49816198/91201717-2fa63400-e6d7-11ea-84b8-88256fb2662e.jpg)

**Comment by HbmMods** [comment]
meme.png
