### ISSUE TITLE
Artillery and Missiles do not work outside of rendered chunks/stuck in unloaded chunks

### ISSUE THREAD

**Issue by beeffeter456** [HbmMods/Hbm-s-Nuclear-Tech-GIT#910]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.

ver. 4501X

The problem that I am having is that missiles and artillery do not function properly outside loaded chunks. Missiles have to be chunk traced to their destination to work, and artillery doesn't function properly unless the chunks are always loaded, say with a chunk loader, when I understand this shouldn't be the case. Missiles also disappear off radar as well. If you load back into a chunk after using the artillery remote for either the rocket or conventional artillery, all shots that were fired just explode in front of the turret at once. This is all happening in a mod pack. 

I don't know if there is a mod conflict or something, but as far as I am aware that isn't likely.  But here is the list anyway:

[mod list.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/10701263/mod.list.txt)

**Comment by likeproblem** [comment]
I think problem is with OptiFine, or any stuff what changes chunk work. Idk, because you have very big modpack

**Comment by HbmMods** [comment]
Missiles and artillery shells load their own chunks, there's been some reports like this before but it was never clear what caused it. I'm pretty sure it's some mod screwing with chunkloading, you could start by removing your performance mods since those are likely contenders.

**Comment by Howdidibreakit** [comment]
It's Optifine or something similar, quick question, what does dynamic surroundings and moving world do? Those might also be contenders for the problem. In optifine, I think you can turn off things related to chunks in performance, try that.

**Comment by username90001** [comment]
maybe it is because of some chunk loading block mod

**Comment by redshadow3** [comment]
oh i had a similiar issue, i tried to shoot artillery while it was in an unloaded chunk but the rocket instead of hitting where i aimed it got stuck in the unloaded chunk it got shot out of, and exploded, im using Foamfix and betterFPS

**Comment by username90001** [comment]
> oh i had a similiar issue, i tried to shoot artillery while it was in an unloaded chunk but the rocket instead of hitting where i aimed it got stuck in the unloaded chunk it got shot out of, and exploded, im using Foamfix and betterFPS

why not optifine

**Comment by redshadow3** [comment]
> > oh i had a similiar issue, i tried to shoot artillery while it was in an unloaded chunk but the rocket instead of hitting where i aimed it got stuck in the unloaded chunk it got shot out of, and exploded, im using Foamfix and betterFPS
> 
> why not optifine

beacause i dont know how to run optifine and forge at the same time, if you try to run mods on optifine alone they just dont run

**Comment by HbmMods** [comment]
> beacause i dont know how to run optifine and forge at the same time, if you try to run mods on optifine alone they just dont run

What do you mean "on optifine", optifine isn't a modloader, it's a mod.

**Comment by redshadow3** [comment]
> What do you mean "on optifine", optifine isn't a modloader, it's a mod.

i know it isnt a modloader, it doesnt load mods, idk how you got optifine as a mod but the only way i know how to run it is as a version in the minecraft launcher, when you download it from the optifine site you get an installer not a mod, this is really frustrating for me idk how you get optifine as a mod

like literally you cant get it as a mod you can only get an installer for optifine that will put it as a version into your minecraft launcher


and if you say "look up a guide" i did and it said both forge and optifine are optimization mods and both are modloaders, and also it just said to extract optifine inside of a shaders folder and then just run forge 

another guide said to do a "few simple steps" but didnt say at all how to do them, like test this or put that into a file

another said to put the forge API into a file (not specified which file) and run optifine on the launcher

**Comment by Howdidibreakit** [comment]
You can actually still get optifine normally, I don't know how to describe it, but you still can.

**Comment by redshadow3** [comment]
> You can actually still get optifine normally, I don't know how to describe it, but you still can.

i dunno what you mean by normally, the launcher version or the mod version of it? and if you know how to get it as a mod then please tell me

**Comment by redshadow3** [comment]
also this isnt exactly the same but similiar, if shells are spammed from an artillery cannon and several stay in a chunk they stop moving and their velocity becomes 0 until loaded again, when loaded they will fall and explode in the chunk they stopped in, im not sure why it happens though, this is basically the same thing as the optimization mods messing with chunkloading by projectiles but i wasnt using those when i was spamming the napalm shells

**Comment by redshadow3** [comment]
but i also experienced the original issue when using FoamFix and BetterFPS for optimization, i tried firing at something with a missile artillery, i was far enough that the artillery wasnt being loaded by me and the rocket just never hit my target so i checked on the rocket artillery and an explosion occured exactly when i came back and also the center of it was at the missile artillery, it worked fine when it was in my render distance but when it wasnt the missile would stay sort of inside the launcher until its invulnerable state turned off and it would explode when the chunk it was in loaded

or much shorter: optimization mods probably prevented chunkloaders from working and caused the shell/missile to stay inside artillery and when the projectiles' invulnerable state ran out they would explode as they were colliding with the artillery

**Comment by Howdidibreakit** [comment]
Yeah something along the lines of, like for 1.12.2, you download it from the optifine site and just, download it. If it says installer it's the wrong one, it's something like optifine g5 or something. It's easier to find for the later versions of minecraft, like 1.12.2. I think it does exist for 1.7.10 though, just dunno where cause I'm on a school computer so those sites are blocked

**Comment by username90001** [comment]
> Yeah something along the lines of, like for 1.12.2, you download it from the optifine site and just, download it. If it says installer it's the wrong one, it's something like optifine g5 or something. It's easier to find for the later versions of minecraft, like 1.12.2. I think it does exist for 1.7.10 though, just dunno where cause I'm on a school computer so those sites are blocked

why u wont get normal pc

**Comment by Howdidibreakit** [comment]
I have a laptop and a school laptop, I do this stuff on the school laptop when I have nothing else to do, this is off topic though, also, try removing mods and launching, like, remove the better fps mod and see if that fixes it, if not, then add it back and remove a different one that might cause the problem.

**Comment by redshadow3** [comment]
> remove the better fps mod and see if that fixes it

ive done that long ago and mentioned it in another comment, both of them were messing with the artillery chunkloading and just causing it to not chunkload somehow

**Comment by HbmMods** [comment]
Finally got around identifying the issue, there's a rounding error that causes missiles to get stuck when they enter an unloaded chunk right next to the chunk border. It's a matter of luck if that happens for any given trajectory, and the issue doesn't have anything to do with a mod conflict.

**Comment by NEKO-001** [comment]
> Finally got around identifying the issue, there's a rounding error that causes missiles to get stuck when they enter an unloaded chunk right next to the chunk border. It's a matter of luck if that happens for any given trajectory, and the issue doesn't have anything to do with a mod conflict.

Is there any hope of fixing this problem within the next month? I'm planning a big game with your mod.

**Comment by HbmMods** [comment]
The next update will be out tomorrow.
