### ISSUE TITLE
1.8.2

### ISSUE THREAD

**Issue by TakeTwo4444** [HbmMods/Hbm-s-Nuclear-Tech-GIT#916]
I am making a mod pack for 1.18.2 and I really want to be able to use this for my modpack.

**Comment by burningwater202** [comment]
Feel free to port it to 1.18.2 then

**Comment by HbmMods** [comment]
you probably want to be [here](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/releases) then
