### ISSUE TITLE
Ore Acidizer Glitch

### ISSUE THREAD

**Issue by Nici660** [HbmMods/Hbm-s-Nuclear-Tech-GIT#918]
You can use any fluid (as far as i know) to fill the Ore Acidizer if you use the recently deprecated fluid duct and a barrel or something similar to fill it. This works with both sulfuric acid and hydrogen peroxide (the fluid you use to fill the acidizer just gets transformed into whatever template your using) and as they are still craftable so this is usable in survival. (Btw. **HBM** where on earth do you get holotapes from?)
![2023-02-19_20 58 00](https://user-images.githubusercontent.com/85819475/219972250-c9242630-b0a7-46bc-a478-ecf565f53fa0.png)
![2023-02-19_20 58 17](https://user-images.githubusercontent.com/85819475/219972252-a5468fd1-43e5-46ec-9c87-5b6fa241eb62.png)

**Comment by HbmMods** [comment]
Fixed in X4522.
