### ISSUE TITLE
Flying just over asphalt in creative gives you incredible speed

### ISSUE THREAD

**Issue by redshadow3** [HbmMods/Hbm-s-Nuclear-Tech-GIT#919]
if you use creative and fly just over asphalt and then move some direction you will basically launch at mach 3 in that direction.

by just over asphalt i mean like less than half a block but still not standing on it, the issue can be replicated by just doing the same thing the title says.

**Comment by HbmMods** [comment]
Fixed in X4522.

**Comment by redshadow3** [comment]
there should be a tag for "fixed in newer version"
