### ISSUE TITLE
putting an effectiveness upgrade lvl 1 into a laser mining drill increases width to 7 instead of 5

### ISSUE THREAD

**Issue by redshadow3** [HbmMods/Hbm-s-Nuclear-Tech-GIT#923]
if you put an effectiveness upgrade lvl 1 in a laser mining drill the width of the hole it makes is increased to 7 instead of 5, from the default 3 meters

possibly intentional but in the effectiveness upgrade's description on the laser mining drill it says increases width by +1m and not +2m

**Comment by HbmMods** [comment]
The upgrade works as intended.

> description on the laser mining drill it says increases width by +1m

Where does it say that? Neither the upgrades themselves nor the mining laser specify the distance.

**Comment by redshadow3** [comment]
> Where does it say that? Neither the upgrades themselves nor the mining laser specify the distance.

it says that on the effectiveness upgrade under mining drill, ill be back in a minute with a screenshot

**Comment by redshadow3** [comment]
![2023-02-25_16 50 44](https://user-images.githubusercontent.com/106045016/221366460-4b996a91-9471-4074-9547-1f4f9d218f3f.png)
here it is +1m

**Comment by HbmMods** [comment]
It doesn't say mining laser anywhere, only "Mining Drill" which is something completely different.

![image](https://user-images.githubusercontent.com/16674258/221367056-6a59d389-70ea-45b9-9b20-517b7e0c92fa.png)

**Comment by redshadow3** [comment]
i thought its the same thing sorry then, but then the effectiveness upgrade lacks the mining laser description
