### ISSUE TITLE
Infinite FEL power when running on visible light

### ISSUE THREAD

**Issue by redshadow3** [HbmMods/Hbm-s-Nuclear-Tech-GIT#925]
in creative i filled up an FEL with an infinite battery and turned it on, but later when i removed the battery and the power went down to 8,75K the FEL kept running without using that little amount of power, meaning it didnt use any power

info: FEL was not connected to a power network and i double checked it without optimization, used visible light

**Comment by redshadow3** [comment]
ok i found out more about this bug and uhhh...

the FEL laser itself does exist, physically in the game, you can see it but it doesnt exist, it doesnt power SILEX's it doesnt blind and set entities on fire it doesnt destroy blocks anything that a normal FEL laser does

in short the FEL laser will only exist visually in this too low power state but the FEL machine itself acts like normal

**Comment by HbmMods** [comment]
Fixed in X4522.
