### ISSUE TITLE
There are no custom missile warheads

### ISSUE THREAD

**Issue by lIGrxmRxpxxrIl** [HbmMods/Hbm-s-Nuclear-Tech-GIT#927]
Why there is a custom missile assembly station but no custom warhead assembly station? + There is a MIRV warhead in the Alcater and 1.12.2 version in the mod but not in the 1.7.10 version wtf plz add a custom warhead assembly station without limts (something like 1 hundred mt warhead or 40 200kt warheads) PLZ HBM MODS ADD THIS

**Comment by HbmMods** [comment]
> but no custom warhead assembly station

Because there are no custom warheads.

> There is a MIRV warhead in the Alcater and 1.12.2 version in the mod but not in the 1.7.10 version wtf plz add

no
