### ISSUE TITLE
a suggestion Can add more doors in version 1.7.10?

### ISSUE THREAD

**Issue by gegedelanjiaohoada** [HbmMods/Hbm-s-Nuclear-Tech-GIT#928]
Can those interesting doors in version 1.12.2 be added to version 1.7.10?

**Comment by Antineutrino-4444** [comment]
great idea
but this is issue, meaning it is not for suggestion and i believe others have already proposed this before :>

**Comment by Antineutrino-4444** [comment]
)tho i does want more doors in 1.7.10

**Comment by Globalfirestorm10** [comment]
Suggestions are sadly not accepted

**Comment by OctoberE** [comment]
bruhh

**Comment by Antineutrino-4444** [comment]
dude the doors are already added

**Comment by Antineutrino-4444** [comment]
check the newest version

**Comment by BallOfEnergy1** [comment]
Some doors have already been added, however not all doors have been due to the difficulty of porting them.
