### ISSUE TITLE
boilers set to make steam can hold 6,400,000mb of steam

### ISSUE THREAD

**Issue by redshadow3** [HbmMods/Hbm-s-Nuclear-Tech-GIT#929]
when a boiler is set to make steam from water the shown amount of steam it can hold is 6400000mb of steam or 6400 buckets of steam
![2023-02-26_14 30 56](https://user-images.githubusercontent.com/106045016/221413583-d3b5894d-f1df-4869-b114-ff2a1501e9ff.png)
im pretty sure this isnt intended but again, im not the developer here so it might, idk why it would be made like that but ok,

dense steam,super dense steam and ultra dense steam can only store 6400 of their steam type but the inserted steam has a storage of 64000 mb, which as you see is the same case for water in boilers

**Comment by redshadow3** [comment]
oh its intended... ok? ill wait for the answer why it is cos i have no idea or just close it without saying anything

**Comment by HbmMods** [comment]
The boiler's output buffer changes with compression, 1mB of water equals 100mB of steam so the output buffer becomes 100x larger.
