### ISSUE TITLE
[ThermalFoundation compatibility issue] Assembler refuse to accept pulverized gold

### ISSUE THREAD

**Issue by craft90** [HbmMods/Hbm-s-Nuclear-Tech-GIT#93]
In my test modpack (around a 100 mods) I noticed a troubling bug. I was attempting to make the circuits required for the Chemical plant. However the Assembler did not work with pulverized gold from Thermal Foundation (despise the oredict being dustGold). As the Shredder only returned TE gold dust I got stuck and unable to progress. Luckily I could use the TE forge converter book to turn the pulverized gold into powdered gold. The Assembler did accept that. I'm not a mod developer myself but I've some experience with error searching mods and I have a hunch that maybe it's either a ore-dictionary/compatibility issue or perhaps due to TE using damage values to differ its ores and dusts.

**Comment by HbmMods** [comment]
This issue has been brought to my attention a few days ago, the automated script that converted all the assembler recipes back when I reworked the recipe system didn't register some of the ore dicst stacks correctly, so things like cobalt ingots and almost all powders weren't using the ore dict. I went over all the recipes again and fixed every instance I could find (the fixed version should be in the latest commit), but chances are high that I might have missed a few of them (there's a couple hundred recipes after all).

I'm leaving this issue open for any future reports of missing ore dict functionality.

**Comment by craft90** [comment]
Understood. The issue do remain (at least for advanced circuits as it's the only one I've tested) in version 3605.

**Comment by HbmMods** [comment]
The version containing that commit hasn't been released yet but it is planned for sunday.

**Comment by craft90** [comment]
It's working now! I haven't tested all recipes but the one for the Advanced Circuit works now.

**Comment by GODTM** [comment]
thats good to hear your issue is now fixed
 but now can you crush my cock with a rock nigger

**Comment by godtm3** [comment]
Nuclear_pashtet IS A STUPID SAND NIGGER

**Comment by HbmMods** [comment]
Closing this since there hasn't been any reports of missing ore dict items lately.
