### ISSUE TITLE
[URGENT] Item Duplication Bug and Potential Unwanted Feature of the Containment Box [X4522]

### ISSUE THREAD

**Issue by Antineutrino-4444** [HbmMods/Hbm-s-Nuclear-Tech-GIT#931]
The newly added containment box in version X4522 currently is able of duplicating items through inserting any item inside of the containment box while it was being stacked (the containment box). After seperating the containment boxes, the item will remain in all boxes seperated and duplicating items.

The possible unwanted feature is that the radiation leak from each containment box can be reduced again by putting it inside of the containment box and so on, which might be a balance issue that dear bob might want to fix.

If screenshots are required for either bugs/problems, please let me know and I will include them ASAP.

**Comment by Antineutrino-4444** [comment]
In order to dupe more than 20 items per time, the player simply needs to put them into other containers like crates or other containment boxes, which makes this issue much more problematic.

**Comment by HbmMods** [comment]
ow

**Comment by HbmMods** [comment]
Fixed in X4525.
