### ISSUE TITLE
List of Enhancements :D

### ISSUE THREAD

**Issue by likeproblem** [HbmMods/Hbm-s-Nuclear-Tech-GIT#933]
*Add more F1 ponder videos to machinery(I love them on stirling engines, look like you were inspired by Create)
*Heat tube, have a chance to lose heat, so it has tiers 3-4, bigger means more heat saves.
*Make damaged status for more tanks.

*Remake nuclear kaboom code, so it doesn't make A HOLY BIG CRAP HOLE. Like crater will be real size, like Little Boy had 250 meters of fireball which evaporated everything. So make plz these queue of kaboom:
1. Fireball expanding and almost litteraly destroying all blocks.
2. Everything in radius X is set on fire(like all wood and entities, don't apply on stuff behind walls AND NOT GLASS)
3. Wave is coming! It don't apply if nuclear bomb was detonated high in air. It knockback all entities which get through, except some walls can stop wave. In some area all blocks are destroyed by wave, like you can survive from wave underground. Also glass in big area is sent to backrooms.
4. Small EMP destroy. YOUUUUUUUUUUUURS EEEEEEELEEEEEEEEEECTRICITY IS GOOOOOOOOOOOOOONE
5. Nuclear Mushroom :D. Also don't apply high in air.
6. Radiation 💯 

PLZZZZZZZZZ ADDDD

I'm gonna edit it if I have more ideas :DD

EDITED:
*RBMK covers or generally all RBMK kaboom things can break ceiling at big speed.(took from 1.12.2)            (ALREADY)
*You can extinguish damaged tanks on fire with a fire extinguisher.                                      (NEEDED IN MAIN VERSION)

P.S. I make this list for 1.7.10 version

**Comment by Globalfirestorm10** [comment]
Neither enhancments nor suggestions are accepted

**Comment by Globalfirestorm10** [comment]
idk, the creator of this mod seems to hate them

**Comment by burningwater202** [comment]
suggestions clog up the GitHub and make it so that it is harder to address actual issues with the mod.

**Comment by Globalfirestorm10** [comment]
Fair, but why does the creator outright hate suggestions? I get it's his mod, but the least he could do is listen to some feedback

**Comment by burningwater202** [comment]
hey man to each their own, if Bob doesn’t like suggestions he doesn’t like suggestions

…Most likely due to them being spammed at him from every angle through here, discord and everywhere else

**Comment by sdddddf80** [comment]
you can pull requests

**Comment by HbmMods** [comment]
* Planned, but not very high priority for now
* Not planned, heat can already be transported by using coolant and heat exchangers
* Already planned
* Not planned

**Comment by username90001** [comment]
> 

tasr bomb will just insanely strong and it will explode ur pc instead of enemy
