### ISSUE TITLE
[suggestion/enhacement] Add bedrock ores to creative menu

### ISSUE THREAD

**Issue by Tungstenfur** [HbmMods/Hbm-s-Nuclear-Tech-GIT#935]
just read title
something is wrong with my NEI and i cant use get bedrock ores in creative

**Comment by sdddddf80** [comment]
it requires special nbt structure，you can copy from a naturally occurring bedrock ore.

**Comment by signed-firmware** [comment]
may i ask how do you copy the NBT structure because when i middle click on ti its just iron powder
