### ISSUE TITLE
agresive lunar chickens bug

### ISSUE THREAD

**Issue by username90001** [HbmMods/Hbm-s-Nuclear-Tech-GIT#936]
if u have epic siege mod installed and use gerald i used it in flat world
chickens will find u and kill u

make if feature instead 
chicken turn into a lunar chicken 9000 and kill players with thermonuclear laser

**Comment by username90001** [comment]
huh is not an answer

**Comment by JameH2** [comment]
this is by far the worst thing I have ever read, please do better

**Comment by username90001** [comment]
when u drop gerald into earth chickens become agressive
