### ISSUE TITLE
Crash on world creation with minefactory reloaded due to village generation

### ISSUE THREAD

**Issue by defiantGrace** [HbmMods/Hbm-s-Nuclear-Tech-GIT#937]
There is a crash during world generation caused due to HBM modifying village generation and some sort of conflict with HBM and minefactory reloaded 
[crash-2023-03-04_22.38.41-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/10890827/crash-2023-03-04_22.38.41-server.txt)

**Comment by HbmMods** [comment]
Fixed in X4543.
