### ISSUE TITLE
crane bug

### ISSUE THREAD

**Issue by UG-rim** [HbmMods/Hbm-s-Nuclear-Tech-GIT#938]
crane can only move down and right(

**Comment by HbmMods** [comment]
Works fine with just NTM installed, are you sure the keybinds don't conflict with something else?

**Comment by sdddddf80** [comment]
I think he is talking about the oc support of the crane

**Comment by UG-rim** [comment]
> Works fine with just NTM installed, are you sure the keybinds don't conflict with something else?

the oc support have this problem

**Comment by Voxelstice** [comment]
i do not know how to fix the crane not moving in all directions, the crane's code is strange

**Comment by HbmMods** [comment]
![image](https://user-images.githubusercontent.com/16674258/224560508-9c9476d5-016e-4d8a-92ae-cf7a2ce5b125.png)

The switch's got no `break`s

**Comment by HbmMods** [comment]
Should be fixed in the upcoming version next week (although I can't test it because idk how OC works)

**Comment by RandomMinecraftPlayer** [comment]
Are the keybinds being used somewhere else?

**Comment by redshadow3** [comment]
keybinds make the key become red if it is used in several keybinds at once

**Comment by HbmMods** [comment]
Fixed in X4543.
