### ISSUE TITLE
Assembly factory doesn't work even with proper supplies.

### ISSUE THREAD

**Issue by RandomMinecraftPlayer** [HbmMods/Hbm-s-Nuclear-Tech-GIT#941]
When I fill it with stuff it won't work correctly please help

**Comment by OlorinIV** [comment]
Assemfac needs water, power, stuff and template. You sure you had all these ready?

**Comment by burningwater202** [comment]
Gonna need a little more info or else you won’t be getting anywhere anytime soon. Can you take screenshots of the issue? Can you explain what you’ve already tried?

**Comment by RandomMinecraftPlayer** [comment]
oh i found it oh okay
