### ISSUE TITLE
Render bug

### ISSUE THREAD

**Issue by Ruslanllll** [HbmMods/Hbm-s-Nuclear-Tech-GIT#944]
After update 1.0.27_X4525 with gl4es renderer this happens
![Screenshot_20230308-000514_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/86971528/223731976-e6e28801-0713-4fdf-9024-203f4b600893.jpg)

**Comment by Ruslanllll** [comment]
oh, the bug is caused by some other mod

**Comment by Kkelos** [comment]
How did you download mods on pojavlauncher???

**Comment by TheForge129** [comment]
use the jar installer for forge and put the mods in pojav's .minecraft
directory
