### ISSUE TITLE
rbmk console refresh rate

### ISSUE THREAD

**Issue by AVASSON** [HbmMods/Hbm-s-Nuclear-Tech-GIT#948]
Hello author, I want to modify the refresh rate of the RBMK console by changing the source code. Excuse me, how can I modify it?

**Comment by HbmMods** [comment]
https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/blob/master/src/main/java/com/hbm/tileentity/machine/rbmk/TileEntityRBMKConsole.java#L60

`if(this.worldObj.getTotalWorldTime() % 10 == 0) {`

10 is the delay between re-scans, if you want constant scanning then either use 1 or remove the condition entirely.

**Comment by AVASSON** [comment]
thanks
