### ISSUE TITLE
Oilwell radiation fallout

### ISSUE THREAD

**Issue by Kkelos** [HbmMods/Hbm-s-Nuclear-Tech-GIT#949]
### Describe the bug
This is more of a question and not a bug. 

Why, when I'm extracting oil falls some radioactive fallout. Is that how it should be?

**Comment by HbmMods** [comment]
Oil pumps spawn dense radon gas when drilling through uranium ore, which has a chance of creating fallout layers when despawning.

**Comment by Kkelos** [comment]
Ok, understood
