### ISSUE TITLE
How to disable ghosts desappearance?

### ISSUE THREAD

**Issue by Kkelos** [HbmMods/Hbm-s-Nuclear-Tech-GIT#952]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.

This is not a bug, this is question.
With a large dose of digamma, ghost(file name) mobs will spawn in the distance, but if you get close to them, they will disappear.

How to disable this disappearance function at a certain distance? In the config? I just want to take a closer look at them :3

**Comment by HbmMods** [comment]
There's no config for that, but you can use either a scope (like Lil'Pipsqueak) or Optifine's zoom to get a closer look. The despawn range is an area 50 blocks in every cardinal direction, try to get as close as possible.

**Comment by Kkelos** [comment]
ok

**Comment by Kkelos** [comment]
Hmmm, can it be configured in "EntityGhost.class" file?
