### ISSUE TITLE
Door noise still plays after full opening

### ISSUE THREAD

**Issue by RandomMinecraftPlayer** [HbmMods/Hbm-s-Nuclear-Tech-GIT#954]
When I press esc, The door still has motion after its fully open it plays the noise, Im in the latest version of the 1.7.10

**Comment by HbmMods** [comment]
The door noise is based on tile ticking which doesn't happen during TPS lag or the game being paused while the opening animation is based on system time which always passes consistently. It's just a bit of an oddity of the animation system.
