### ISSUE TITLE
[suggestion]About vehicle systems

### ISSUE THREAD

**Issue by xinghuan2hao** [HbmMods/Hbm-s-Nuclear-Tech-GIT#956]
Hello, are there any plans to add some vehicles to the HBM module? There are many ways to deliver nuclear strikes on targets, but I think the most common form of nuclear strikes is a mobile platform launch by nuclear submarines or strategic bombers and missile launchers. Of course, it is obvious that making a nuclear submarine vehicle will be troublesome, so can you start with a simple launch vehicle, such as a strategic bomber or a missile launch vehicle.

**Comment by HbmMods** [comment]
The only current type of vehicle planned is trains, other types would require a more complex simulation for the physics to work properly, and there's already mods that do that pretty well.

Both Flan's Mod and MCHeli have missile carriers and ships with high yield ammo as well as a config system that allows for custom recipes or even vehicles to be made, so making missiles craftable with NTM's plutonium should be possible.

**Comment by xinghuan2hao** [comment]
> The only current type of vehicle planned is trains, other types would require a more complex simulation for the physics to work properly, and there's already mods that do that pretty well.
> 
> Both Flan's Mod and MCHeli have missile carriers and ships with high yield ammo as well as a config system that allows for custom recipes or even vehicles to be made, so making missiles craftable with NTM's plutonium should be possible.

Hello, the vehicle or aircraft module is not easy to use the nuclear attack system in HBMmod, let alone the missiles loaded with HBMmod, this linkage is not very easy, so as a mod that provides a complete nuclear industry system and nuclear weapons system, I think it is more appropriate to officially make a mobile launch platform.
By the way, will there be Russian missile trains？

**Comment by HbmMods** [comment]
I don't have a list of train cars yet, the only confirmed one right now is an artillery train car which will be equivalent to the artillery turret.

**Comment by xinghuan2hao** [comment]
> I don't have a list of train cars yet, the only confirmed one right now is an artillery train car which will be equivalent to the artillery turret.

Waiting for your train system, I think it will be very special
Finally, I hope you have had a good life and create better mods for MC players
