### ISSUE TITLE
Visual fog glitch near depth stone

### ISSUE THREAD

**Issue by iocmet** [HbmMods/Hbm-s-Nuclear-Tech-GIT#957]
Version: `HBM-NTM-[1.0.27_X4525]`
https://user-images.githubusercontent.com/63492966/226070177-4a4089a4-a914-421f-923c-9eebd400c65a.mp4
This happened for me two times, currently not happening

**Comment by HbmMods** [comment]
Depth rock doesn't do anything special in regards to rendering so it causing anything like that is out of the question. It's most likely the depth fog interacting with one of your mods, do you have optifine or hardcoredarkness installed?

**Comment by iocmet** [comment]
Yes i have optifine, also i installed dynamicsurrounding and i think this started happening after installing it

**Comment by iocmet** [comment]
![image](https://user-images.githubusercontent.com/63492966/226765709-58136127-21cb-45c9-b3ec-8f363476d21c.png)
I think one of this DynamicSurrounding options causes this bug, don't know exactly because it gone

**Comment by iocmet** [comment]
![image](https://user-images.githubusercontent.com/63492966/226768041-fa37dbdf-bd2b-44d6-bdf8-36c44c64818c.png)
