### ISSUE TITLE
Blocks blast resistance limited with 60

### ISSUE THREAD

**Issue by iocmet** [HbmMods/Hbm-s-Nuclear-Tech-GIT#958]
Version: `HBM-NTM-[1.0.27_X4525]`
Blast resistance of blocks from HBM not getting bigger than 60, it also causes unblockable FEL laser
![image](https://user-images.githubusercontent.com/63492966/226074307-a560155d-018b-4491-b60d-c5586e235fdf.png)

**Comment by iocmet** [comment]
After removing all other mod i still have this issue
![image](https://user-images.githubusercontent.com/63492966/226075394-bd9a4713-8301-4322-8499-91db4f92cbe0.png)
![image](https://user-images.githubusercontent.com/63492966/226075407-256863e8-7cd3-4938-bbef-5ca60f025380.png)

**Comment by HbmMods** [comment]
Asphalt having a resistance of 60 is intended, could you check if for example concrete is affected too? The blast resistance value for concrete should be 2,400.

**Comment by iocmet** [comment]
Oh, okay i will check with concrete later

**Comment by iocmet** [comment]
WarpDrive mod causes this, with it concrete and other blocks blast resistance gets limited with 63

**Comment by iocmet** [comment]
![image](https://user-images.githubusercontent.com/63492966/226653611-43f6b2c0-9672-4ed4-9783-eef7ae454dde.png)
Found part of code that causes this i think

**Comment by iocmet** [comment]
Fixed by commenting this code (not think that author of mod will update 1.7.10 version)
