### ISSUE TITLE
question about fusion reactor

### ISSUE THREAD

**Issue by githubguyidk** [HbmMods/Hbm-s-Nuclear-Tech-GIT#959]
I looked at the recipes GUI in the fusion reactor I saw a recipe called "Balefire plasma" I thought it looked really cool so I wanted to try it out but I couldn't find it so my question is how can I make/produce balefire plasma

**Comment by username90001** [comment]
> I looked at the recipes GUI in the fusion reactor I saw a recipe called "Balefire plasma" I thought it looked really cool so I wanted to try it out but I couldn't find it so my question is how can I make/produce balefire plasma

antimatter and bf rocket fuel as i remember

**Comment by username90001** [comment]
bf means balefire
