### ISSUE TITLE
question about fusion reactor

### ISSUE THREAD

**Issue by githubguyidk** [HbmMods/Hbm-s-Nuclear-Tech-GIT#960]
I saw this recipe in the fusion reactor GUI and its called "balefire plasma" my question is how can I produce/make balefire plasma

**Comment by MCNaOtlichnoYT** [comment]
10 MHE + 1000 mb BF Rocket Fuel + 1000 mb Antimatter in plasma heater
You get 2000 mb balefire plasma

**Comment by username90001** [comment]
did u just did same question
