### ISSUE TITLE
containment box items duping

### ISSUE THREAD

**Issue by CaxTheA1** [HbmMods/Hbm-s-Nuclear-Tech-GIT#964]
well when you have 64 containment box and put an item inside they will multiply if you separate the boxs and idk if its a bug but dont make sense putting boxes inside another and if you fill a containment box with any block then make more as the same and put in another box and do it again it will crash

obs: im testing in a 4gb ram notebook so maybe that would be the problem

minecraft version:1.7.10(TLauncher)
hbm ntm version:1.2.07_X4522(aka the last in the curseforge rn)
other mods im using: BetterFPS1.0.1,worldedit-forge-mc1.7.10-6.1.1dist,Optifine-1.7.10_HD_U_E7 and tlskincape_1.7.10-1.4
playing in aternos.org creative

(i will put NEI and play survival)

**Comment by Antineutrino-4444** [comment]
The dupe issue was already reported previously, the newest github version already fixed this problem.

I am not completely sure about the crashing problem, but it might be the nbt data being too big? (im no programmer so don’t take this too seriously)

From: CaxTheA1 ***@***.***>
Date: Tuesday, March 21, 2023 at 08:51
To: HbmMods/Hbm-s-Nuclear-Tech-GIT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [HbmMods/Hbm-s-Nuclear-Tech-GIT] containment box items duping (Issue #964)

well when you have 64 containment box and put an item inside they will multiply if you separate the boxs and idk if its a bug but dont make sense putting boxes inside another and if you fill a containment box with any block then make more as the same and put in another box and do it again it will crash

obs: im testing in a 4gb ram notebook so maybe that would be the problem

minecraft version:1.7.10(TLauncher)
hbm ntm version:1.2.07_X4522(aka the last in the curseforge rn)
other mods im using: BetterFPS1.0.1,worldedit-forge-mc1.7.10-6.1.1dist,Optifine-1.7.10_HD_U_E7 and tlskincape_1.7.10-1.4
playing in aternos.org creative

(i will put JEI and play survival)

**Comment by CaxTheA1** [comment]
oh okay ty
