### ISSUE TITLE
[1.0.27_X4543H1] Server can't start owing to I18nUtil class not found.

### ISSUE THREAD

**Issue by gengyunmaster** [HbmMods/Hbm-s-Nuclear-Tech-GIT#966]
I have encountered a problem when updating NTM from version 4480 to 4543H1. The client works fine, but the server can't start. Here is the crash report generated during initializing process. Could you please help me check whether there is a bug? Thank you!
[crash-2023-03-24_03.31.12-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/11055291/crash-2023-03-24_03.31.12-server.txt)

**Comment by HbmMods** [comment]
Fixed in X4550.
