### ISSUE TITLE
the melting point of RBMK fuel rods

### ISSUE THREAD

**Issue by AVASSON** [HbmMods/Hbm-s-Nuclear-Tech-GIT#967]
Hello, sorry to bother you, how to modify the melting point of RBMK fuel rods?

**Comment by HbmMods** [comment]
Fuel stats are defined here: https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/blob/master/src/main/java/com/hbm/items/ModItems.java#L3573

If you just want to disable meltdowns without compiling the mod yourself, change the gamerule `dialDisableMeltdowns` to `false`.
