### ISSUE TITLE
Opening most turret ui shuts down the server.

### ISSUE THREAD

**Issue by TheBigEEEEE** [HbmMods/Hbm-s-Nuclear-Tech-GIT#968]
Opening any turret ui that isn't artillery or that small green one instantly shuts down the server no matter what.

Im using an aternos server if that helps.

<html>
<body>

---- Minecraft Crash Report ----
--
2 | // Don't be sad, have a hug! <3
3 |  
4 | Time: 3/25/23 5:27 PM
5 | Description: Exception in server tick loop
6 |  
7 | java.lang.AbstractMethodError: Method com/hbm/tileentity/turret/TileEntityTurretHoward.provideContainer(ILnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/world/World;III)Lnet/minecraft/inventory/Container; is abstract
8 | at com.hbm.tileentity.turret.TileEntityTurretHoward.provideContainer(TileEntityTurretHoward.java)
9 | at com.hbm.handler.GUIHandler.getServerGuiElement(GUIHandler.java:20)
10 | at cpw.mods.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:243)
11 | at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:75)
12 | at com.hbm.blocks.turret.TurretHoward.func_149727_a(TurretHoward.java:62)
13 | at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
14 | at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
15 | at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
16 | at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
17 | at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
18 | at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
19 | at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
20 | at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
21 | at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
22 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
23 | at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
24 |  
25 |  
26 | A detailed walkthrough of the error, its code path and all known details is as follows:
27 | ---------------------------------------------------------------------------------------
28 |  
29 | -- System Details --
30 | Details:
31 | Minecraft Version: 1.7.10
32 | Operating System: Linux (amd64) version 5.4.0-96-generic
33 | Java Version: 1.8.0_362, Temurin
34 | Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
35 | Memory: 797620272 bytes (760 MB) / 1400373248 bytes (1335 MB) up to 1771044864 bytes (1689 MB)
36 | JVM Flags: 3 total; -XX:MaxMetaspaceSize=300M -Xmx1900M -Xms950M
37 | AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
38 | IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
39 | FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 27 mods loaded, 27 mods active
40 | States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
41 | UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
42 | UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge.jar)
43 | UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge.jar)
44 | UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar)
45 | UCHIJAAAA	fiskheroescore{2.1.2} [Fisk's Superheroes Core] (FiskHeroes-1.7.10-2.1.2.jar)
46 | UCHIJAAAA	securitycraft{v1.8.13} [SecurityCraft] ([1.7.10] SecurityCraft v1.8.13.jar)
47 | UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar)
48 | UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
49 | UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar)
50 | UCHIJAAAA	fiskheroes{2.1.2} [Fisk's Superheroes] (FiskHeroes-1.7.10-2.1.2.jar)
51 | UCHIJAAAA	fisktag{1.0.0} [FiskTag] (FiskHeroes-1.7.10-2.1.2.jar)
52 | UCHIJAAAA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar)
53 | UCHIJAAAA	GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta.jar)
54 | UCHIJAAAA	hbm{1.0.27 BETA (4522)} [Hbm's Nuclear Tech] (HBM-NTM-[1.0.27_X4522].jar)
55 | UCHIJAAAA	trackapi{1.2} [Track API] (TrackAPI-1.2.jar)
56 | UCHIJAAAA	universalmodcore{1.1.4} [UniversalModCore] (UniversalModCore-1.7.10-forge-1.1.4-899c85.jar)
57 | UCHIJAAAA	immersiverailroading{1.9.1} [Immersive Railroading] (ImmersiveRailroading-1.7.10-forge-1.9.1.jar)
58 | UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar)
59 | UCHIJAAAA	Mekanism{9.10.26} [Mekanism Community Edition] (Mekanism-Community-Edition-1.7.10-9.10.26-Core.jar)
60 | UCHIJAAAA	mw{0.4.1} [Modern Warfare Contagion] (mw_2.0-0.4.1_mc1.7.10.jar)
61 | UCHIJAAAA	openmodularturrets{2.2.11-245} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.2.11-245.jar)
62 | UCHIJAAAA	oreexcavation{1.1.134} [OreExcavation] (OreExcavation-1.1.134.jar)
63 | UCHIJAAAA	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6-fix-1.jar)
64 | UCHIJAAAA	Techguns{0.1.2_alphatest4.1} [Techguns] (Techguns.beta.1.2_alphatest4.1.jar)
65 | UCHIJAAAA	waystones{1.0.12} [Waystones] (Waystones-mc1.7.10-1.0.12.jar)
66 | UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
67 | UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
68 | AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
69 | Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
70 | AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
71 | Profiler Position: N/A (disabled)
72 | Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
73 | Player Count: 1 / 20; [EntityPlayerMP['TheBig_EEEEE'/371, l='world', x=190.54, y=71.13, z=495.13]]
74 | Is Modded: Definitely; Server brand changed to 'fml,forge'
75 | Type: Dedicated Server (map_server.txt)

</body>
</html>
[spoiler]---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 3/[2](https://aternos.org/files/crash-reports/crash-2023-03-25_17.27.49-server.txt#L2)5/2[3](https://aternos.org/files/crash-reports/crash-2023-03-25_17.27.49-server.txt#L3) 5:27 PM
Description: Exception in server tick loop

java.lang.AbstractMethodError: Method com/hbm/tileentity/turret/TileEntityTurretHoward.provideContainer(ILnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/world/World;III)Lnet/minecraft/inventory/Container; is abstract
	at com.hbm.tileentity.turret.TileEntityTurretHoward.provideContainer(TileEntityTurretHoward.java)
	at com.hbm.handler.GUIHandler.getServerGuiElement(GUIHandler.java:20)
	at cpw.mods.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:2[4](https://aternos.org/files/crash-reports/crash-2023-03-25_17.27.49-server.txt#L4)3)
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:7[5](https://aternos.org/files/crash-reports/crash-2023-03-25_17.27.49-server.txt#L5))
	at com.hbm.blocks.turret.TurretHoward.func_149727_a(TurretHoward.java:[6](https://aternos.org/files/crash-reports/crash-2023-03-25_17.27.49-server.txt#L6)2)
	at net.minecraft.server.management.ItemInWorldManager.func_[7](https://aternos.org/files/crash-reports/crash-2023-03-25_17.27.49-server.txt#L7)307[8](https://aternos.org/files/crash-reports/crash-2023-03-25_17.27.49-server.txt#L8)_a(ItemInWorldManager.java:376)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:[9](https://aternos.org/files/crash-reports/crash-2023-03-25_17.27.49-server.txt#L9))
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.[10](https://aternos.org/files/crash-reports/crash-2023-03-25_17.27.49-server.txt#L10)
	Operating System: Linux (amd64) version 5.4.0-96-generic
	Java Version: 1.8.0_362, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 797620272 bytes (760 MB) / 1400373248 bytes (1335 MB) up to 1771044864 bytes (1689 MB)
	JVM Flags: 3 total; -XX:MaxMetaspaceSize=300M -Xmx1900M -Xms950M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	fiskheroescore{2.1.2} [Fisk's Superheroes Core] (FiskHeroes-1.7.10-2.1.2.jar) 
	UCHIJAAAA	securitycraft{v1.8.13} [SecurityCraft] ([1.7.10] SecurityCraft v1.8.13.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.9.5.[11](https://aternos.org/files/crash-reports/crash-2023-03-25_17.27.49-server.txt#L11)} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	fiskheroes{2.1.2} [Fisk's Superheroes] (FiskHeroes-1.7.10-2.1.2.jar) 
	UCHIJAAAA	fisktag{1.0.0} [FiskTag] (FiskHeroes-1.7.10-2.1.2.jar) 
	UCHIJAAAA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJAAAA	GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta.jar) 
	UCHIJAAAA	hbm{1.0.27 BETA (4522)} [Hbm's Nuclear Tech] (HBM-NTM-[1.0.27_X4522].jar) 
	UCHIJAAAA	trackapi{1.2} [Track API] (TrackAPI-1.2.jar) 
	UCHIJAAAA	universalmodcore{1.1.4} [UniversalModCore] (UniversalModCore-1.7.10-forge-1.1.4-899c85.jar) 
	UCHIJAAAA	immersiverailroading{1.9.1} [Immersive Railroading] (ImmersiveRailroading-1.7.10-forge-1.9.1.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	Mekanism{9.10.26} [Mekanism Community Edition] (Mekanism-Community-Edition-1.7.10-9.10.26-Core.jar) 
	UCHIJAAAA	mw{0.4.1} [Modern Warfare Contagion] (mw_2.0-0.4.1_mc1.7.10.jar) 
	UCHIJAAAA	openmodularturrets{2.2.11-245} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.2.11-245.jar) 
	UCHIJAAAA	oreexcavation{1.1.134} [OreExcavation] (OreExcavation-1.1.134.jar) 
	UCHIJAAAA	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6-fix-1.jar) 
	UCHIJAAAA	Techguns{0.1.2_alphatest4.1} [Techguns] (Techguns.beta.1.2_alphatest4.1.jar) 
	UCHIJAAAA	waystones{1.0.[12](https://aternos.org/files/crash-reports/crash-2023-03-25_17.27.49-server.txt#L12)} [Waystones] (Waystones-mc1.7.10-1.0.12.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	AE2 Version: beta rv3-beta-6 for Forge 10.[13](https://aternos.org/files/crash-reports/crash-2023-03-25_17.27.49-server.txt#L13).4.[14](https://aternos.org/files/crash-reports/crash-2023-03-25_17.27.49-server.txt#L14)48
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 20; [EntityPlayerMP['TheBig_EEEEE'/371, l='world', x=[19](https://aternos.org/files/crash-reports/crash-2023-03-25_17.27.49-server.txt#L19)0.54, y=71.13, z=[49](https://aternos.org/files/crash-reports/crash-2023-03-25_17.27.49-server.txt#L49)5.13]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by HbmMods** [comment]
Fixed in X4550.
