### ISSUE TITLE
Trouble in locating rods on Opencomputer

### ISSUE THREAD

**Issue by estriene** [HbmMods/Hbm-s-Nuclear-Tech-GIT#969]
on Opencomputer, all the rods are in a same component name, only can use uid to discriminate them.

and that's maybe better to have a way to locates rods, or it'll be a big problem to form a completely reactor on the computer

**Comment by SoB1nary** [comment]
you can shift-control-right click on a rod with an opencomputers analyzer to copy it's id, then use component.proxy
in case you're using an adapter, simply Don't. use a cable instead

**Comment by UG-rim** [comment]
so it's impossible to write a program can use for every reactor without troublesome setups in these versions?

sure we can register(? rods by analyzer,  but isn't it very pesky to setup a big reactor?

**Comment by SoB1nary** [comment]
Yeah, you really can't tell where each rod is located without an analyzer.
However, you can use [component.list](https://ocdoc.cil.li/api:component) to get a list of, say, fuel rods, if you don't care for where the rod is.

**Comment by UG-rim** [comment]
that's exactly the thing is.
most of reactors use not only one type of the fuel
(i think(?. so it's important to know which rod keep what type of the fuel or the locate of the rod

**Comment by UG-rim** [comment]
that's exactly the thing is.
most of reactors use not only one type of the fuel (i think(?.
so it's important to know which rod keep what type of the fuel or the locate of the rod
but it could be done by a crane kepping a fuel to test where the rod is and mate the id one by one.
(terrible.

**Comment by BallOfEnergy1** [comment]
You can use a simple line of code to loop through each rod and add it to an array of rods. Example:
for x in component.list("put rod name here") do table.add(rod_list, x) end
Currently looking into adding coordinate reading into the RBMK OC compatibility, however for now, the rods don't particularly have to be sorted, unless you're trying to keep fuel, which I'm also planning to add.

**Comment by BallOfEnergy1** [comment]
You can also make an initiation system of sorts to find which fuels correspond to which rods by removing fuels from rods, then checking if the fuel values equal "N/A", then storing those fuel rods in an array with a specified index. Example:
for x in component.list("rbmk_fuel_rod") do while component.invoke(x, "getDepletion") != "N/A" do end table.add(rod_table_sorted, x) end

**Comment by UG-rim** [comment]
so sorting rods can't be full-automatically now, it's simple to deal with for a single reactor. but I'm looking for a way to control a reactor full-automatically, and can be used for every reactor. this meas the code can just be installed to run without pesky setups

**Comment by BallOfEnergy1** [comment]
It might be possible to do so after I fix my new OC compat code, as it'll be possible to read fuel types and coordinates of RBMK columns.

**Comment by BallOfEnergy1** [comment]
But so far, it's not possible in the way you're describing.

**Comment by UG-rim** [comment]
waiting...😺😺😺

**Comment by BallOfEnergy1** [comment]
On my fork of NTM there's a branch called 'BallOfEnergy1-OC-Test-1', which should have the ability to grab the fuel type. However, I need somebody to test it, so if anyone can grab, build, and test it, that'd be great.

**Comment by BallOfEnergy1** [comment]
Unable to test my code at the moment due to PC issues.

**Comment by Voxelstice** [comment]
i didnt really think about locating rods that much for some reason, i'll code that soon

**Comment by BallOfEnergy1** [comment]
I've made a wonky prototype of reading fuel from rods, just I haven't gotten around to locating them

**Comment by UG-rim** [comment]
> 
one code for one reactor
not suitable for every players

**Comment by UG-rim** [comment]
> 
one code for one reactor
easy for coders
not suitable for every players

**Comment by BallOfEnergy1** [comment]
I'm slowly getting around to coding it in, however it's taking a while as I'm currently sick. (It will come eventually)

**Comment by BallOfEnergy1** [comment]
Ok, this can be closed, feature has been added in most recent commit.
