### ISSUE TITLE
adventurebackpack and hbm4550 cause crash

### ISSUE THREAD

**Issue by mcmso** [HbmMods/Hbm-s-Nuclear-Tech-GIT#973]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.

https://paste.ubuntu.com/p/qDh2kjyjTP/

https://discord.com/channels/320301110759784449/708382585721716787/1089677714870521856

**Comment by BallOfEnergy1** [comment]
Looks like a mod conflict to me, what were you doing when it crashed?

**Comment by mcmso** [comment]
> Looks like a mod conflict to me, what were you doing when it crashed?

I have the same problem as the guy on the discord link
This also happens when you create an archive or when you enter an archive

**Comment by HbmMods** [comment]
Try setting the config option `enableStatReRegistering` to `false`

**Comment by mcmso** [comment]
> Try setting the config option `enableStatReRegistering` to `false`
                           
                  **It actually works**


The response time was a little longer because the package I tested was gtnh

**Comment by mcmso** [comment]
Thank you for your help but it's clear that the problem isn't just with one mod
Thank you again

**Comment by HbmMods** [comment]
Should be fixed properly in X4551, please try the new version with the config set to default.

**Comment by mcmso** [comment]
I think you did fix this bug in 4551 but it seems to have caused a new bug
https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/issues/983

**Comment by HbmMods** [comment]
Fixed in X4561.
