### ISSUE TITLE
crash when entering a new minecraft world

### ISSUE THREAD

**Issue by asddsa3211233** [HbmMods/Hbm-s-Nuclear-Tech-GIT#974]
crash when entering a new minecraft world (with a new version of this mod)
[crash-2023-03-27_22.10.50-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/11080265/crash-2023-03-27_22.10.50-server.txt)

**Comment by BallOfEnergy1** [comment]
I'm not completely sure, however it looks like a mod conflict with MutantCreatures.

**Comment by HbmMods** [comment]
Set the config option `enableStatReRegistering` to `false`

**Comment by HbmMods** [comment]
Fixed in X4561.
