### ISSUE TITLE
Squids making throwing up noise when having rad sickness

### ISSUE THREAD

**Issue by RagexPrince683** [HbmMods/Hbm-s-Nuclear-Tech-GIT#975]
### Describe the bug

Not sure if this is a bug or not but I have found at least on version 3920 that squids will make the barfing noise present when having radiation sickness.

**Comment by BallOfEnergy1** [comment]
All mobs have this effect; pretty sure it's completely intended.

**Comment by RagexPrince683** [comment]
> All mobs have this effect; pretty sure it's completely intended.

Oh okay, just seems weird. Maybe make this a config option if it isn't already?

**Comment by HbmMods** [comment]
Mobs tagged as water creatures should no longer throw up.
