### ISSUE TITLE
runclient failed after I changed the gradle version to 7.4.2

### ISSUE THREAD

**Issue by sdddddf80** [HbmMods/Hbm-s-Nuclear-Tech-GIT#977]
### Describe the bug

I want more functions like debugClient in gradle-7.4.2. But debugClient failed after I changed the gradle version to 7.4.2.
First, it can't get the dependencies. 
`Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings
2 actionable tasks: 1 executed, 1 up-to-date
<-------------> 0% WAITING
> IDLE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find codechicken:CodeChickenCore:1.7.10-1.0.4.29.
     Searched in the following locations:
       - https://maven.minecraftforge.net/codechicken/CodeChickenCore/1.7.10-1.0.4.29/CodeChickenCore-1.7.10-1.0.4.29-src.jar
       - https://repo.maven.apache.org/maven2/codechicken/CodeChickenCore/1.7.10-1.0.4.29/CodeChickenCore-1.7.10-1.0.4.29.pom
       - https://libraries.minecraft.net/codechicken/CodeChickenCore/1.7.10-1.0.4.29/CodeChickenCore-1.7.10-1.0.4.29.pom
       - https://modmaven.dev/codechicken/CodeChickenCore/1.7.10-1.0.4.29/CodeChickenCore-1.7.10-1.0.4.29.pom
       - file:/C:/Users/29801/.gradle/caches/minecraft/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/CodeChickenCore-1.7.10-1.0.4.29-src.jar
       - file:/C:/Users/29801/.gradle/caches/minecraft/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/CodeChickenCore-src.jar
     Required by:
         project :
   > Could not find codechicken:CodeChickenLib:1.7.10-1.1.3.140.
     Searched in the following locations:
       - https://maven.minecraftforge.net/codechicken/CodeChickenLib/1.7.10-1.1.3.140/CodeChickenLib-1.7.10-1.1.3.140-src.jar
       - https://repo.maven.apache.org/maven2/codechicken/CodeChickenLib/1.7.10-1.1.3.140/CodeChickenLib-1.7.10-1.1.3.140.pom
       - https://libraries.minecraft.net/codechicken/CodeChickenLib/1.7.10-1.1.3.140/CodeChickenLib-1.7.10-1.1.3.140.pom
       - https://modmaven.dev/codechicken/CodeChickenLib/1.7.10-1.1.3.140/CodeChickenLib-1.7.10-1.1.3.140.pom
       - file:/C:/Users/29801/.gradle/caches/minecraft/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/CodeChickenLib-1.7.10-1.1.3.140-src.jar
       - file:/C:/Users/29801/.gradle/caches/minecraft/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/CodeChickenLib-src.jar
     Required by:
         project :
   > Could not find codechicken:NotEnoughItems:1.7.10-1.0.3.74.
     Searched in the following locations:
       - https://maven.minecraftforge.net/codechicken/NotEnoughItems/1.7.10-1.0.3.74/NotEnoughItems-1.7.10-1.0.3.74-src.jar
       - https://repo.maven.apache.org/maven2/codechicken/NotEnoughItems/1.7.10-1.0.3.74/NotEnoughItems-1.7.10-1.0.3.74.pom
       - https://libraries.minecraft.net/codechicken/NotEnoughItems/1.7.10-1.0.3.74/NotEnoughItems-1.7.10-1.0.3.74.pom
       - https://modmaven.dev/codechicken/NotEnoughItems/1.7.10-1.0.3.74/NotEnoughItems-1.7.10-1.0.3.74.pom
       - file:/C:/Users/29801/.gradle/caches/minecraft/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/NotEnoughItems-1.7.10-1.0.3.74-src.jar
       - file:/C:/Users/29801/.gradle/caches/minecraft/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/NotEnoughItems-src.jar
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Could not execute build using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-7.4.2-bin.zip'.`

After I I downloaded all the missing dependencies to the local specified path, it still faild.
` Task :processResources FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings
3 actionable tasks: 2 executed, 1 up-to-date
<====---------> 37% EXECUTING [1m 34s]
> IDLE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processResources'.
> Entry mcmod.info is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.4.2/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Could not execute build using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-7.4.2-bin.zip'.`

**Comment by BallOfEnergy1** [comment]
Sounds like there was a duplicate mcmod.info.
