### ISSUE TITLE
mushroom cloud (realism problem)

### ISSUE THREAD

**Issue by lIGrxmRxpxxrIl** [HbmMods/Hbm-s-Nuclear-Tech-GIT#979]
conventional explosive custom nukes create a mushroom cloud

**Comment by SoB1nary** [comment]
any sufficiently powerful explosive will create a mushroom cloud, that's how it works

**Comment by lIGrxmRxpxxrIl** [comment]
i know but a conventional explosive has to be way more powerfull to create a mushroom cloud

**Comment by lIGrxmRxpxxrIl** [comment]
then why does a daisy cutter doesnt create a mushroom

**Comment by SoB1nary** [comment]
must be a skill issue on it's part

**Comment by burningwater202** [comment]
My man I don’t know what you expected, this mod has a strawberry flavored superalloy and a gun that drops boxcars on your enemies

if you’re looking for perfect realism I hate to say it but I don’t think Minecraft is the game for you

**Comment by BallOfEnergy1** [comment]
> My man I don’t know what you expected, this mod has a strawberry flavored superalloy and a gun that drops boxcars on your enemies
> 
> if you’re looking for perfect realism I hate to say it but I don’t think Minecraft is the game for you

well said

**Comment by HbmMods** [comment]
The next person to open another god damn issue because "muh realismé" gets punt-kicked into the fucking stratosphere.
