### ISSUE TITLE
T45 armor does not render on player body correctly

### ISSUE THREAD

**Issue by AlexOberfranc** [HbmMods/Hbm-s-Nuclear-Tech-GIT#98]

**Comment by sendhelppls213** [comment]
It's really hard to make 3d models display correctly as armor.

**Comment by AlexOberfranc** [comment]
No I know it is I am just letting you know because it was working on an older version.

**Comment by HbmMods** [comment]
The way armor is rendered on the player hasn't changed since 2016, do you by any chance have other mods installed? And what exactly do you mean by "not render correctly", are there missing parts, errors with the rotations or misplaced texture?

**Comment by AlexOberfranc** [comment]
this is what I meant by the rendering
![2020-09-24_18 13 28](https://user-images.githubusercontent.com/32021115/94209390-df66f100-fe91-11ea-9cc1-f44e5ec1ed8b.png)

**Comment by sendhelppls213** [comment]
Do you have any other mods/shaders/texture packs?

**Comment by AlexOberfranc** [comment]
i have vics modern warfare in there

**Comment by Drillgon200** [comment]
Vic's modern warfare is known to cause problems with this mod's custom armor models.

**Comment by GODTM** [comment]
CRUSH MY COCK WITH A ROCK NIGGER

**Comment by HbmMods** [comment]
I'd say you should test the armor without Vic's installed, I'm fairly certain that it's the culprit, we've already observed similar issues with gas masks.

**Comment by godtm3** [comment]
Nuclear_pashtet IS A STUPID SAND NIGGER

**Comment by Here-is-your-stupid-name** [comment]
that might be it. i remember it stopped working after I updated VMW

**Comment by Here-is-your-stupid-name** [comment]
Okay so I tested it and the latest version of Vic's that doesn't break the suit graphics (at least for me) is 
mw-1.11.7.7_mc1.7.10.jar 
released 18.8.2018 or 8/18/2018
