### ISSUE TITLE
HBM 4451 I18n resources crush

### ISSUE THREAD

**Issue by mcmso** [HbmMods/Hbm-s-Nuclear-Tech-GIT#983]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.
[crash-2023-03-28_18.58.39-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/11131024/crash-2023-03-28_18.58.39-server.txt)

**Comment by mcmso** [comment]
On the server

**Comment by HbmMods** [comment]
Similar issue as #973, try starting the server with the `enableStatReRegistering` config option turned off.

**Comment by HbmMods** [comment]
Fixed in X4561.
