### ISSUE TITLE
Minecraft 1.7.10 Graphics Issues

### ISSUE THREAD

**Issue by HbmMods** [HbmMods/Hbm-s-Nuclear-Tech-GIT#985]
Since about summer 2022, there have been increasing reports of issues where the game's graphics would glitch out when holding items or looking at certain things (terrain or the entire screen becomes solid color, incorrect textures being bound, etc.).

Strictly speaking, this isn't an issue to NTM in itself since it has been reported on instances running different mods or no mods at all. The issue is likely caused by a faulty update that has been rolled out to PCs with Intel UHD series integrated GPUs, although there have been a few reports of the same thing happening with certain dedicated NVIDIA or integrated AMD cards.

Nevertheless, there are a few approaches as to how this issue could be fixed:
* Downgrading the graphics drivers to an earlier version, probably one from early 2022 (I don't know the exact version numbers for the UHD drivers, but exact versions shouldn't really matter anyway). This method seems to be the most effective, but be warned that messing with your drivers may have some side effects, so perhaps try this option when the other ones don't work.
* Switching GPU, often times PCs that have dedicated GPUs that should work correctly also come with integrated GPUs running alongside them, depending on the brand and driver, it's possible to define what GPU the game runs on. For NVIDIA cards, this can usually be done in the NVIDIA control panel in the tab "Manage 3D settings".
* Using a different launcher, it's unclear how that would fix a rendering issue (possibly due to different graphics libraries being used), but there has been one report where simply switching the launcher seemingly fixed it.
* Using [Neodymium](https://github.com/makamys/Neodymium), a performance mod that changes the way chunk rendering works which has the side effect of also fixing this issue. Due to the change in rendering, Neodymium might have some incompatibilities with certain other graphics mods, so be sure to check out the project's readme before using it.

~~A cheer for auto-updating drivers! Hip hip hooray!~~

**Comment by HbmMods** [comment]
(closing because it's not so much of a fixable issue on my side that can be completed but rather an announcement)

**Comment by coolestkid91021** [comment]
oh ok

**Comment by alexhoopes** [comment]
@HbmMods, am currently having an issue on a M1 Macbook Pro, without the mod added to mods folder I am able to load into the game and see the forge loading screen, once the mod is added I get no forge loading screen and just a white screen. Does this fall under graphics issues or should I open a new issue?

**Comment by Poopooracoocoo** [comment]
Commenting here because this shows up in Google searches. 

https://www.planetminecraft.com/blog/how-to-fix-1-7-10-graphic-bug/ suggests using [Neodymium](https://github.com/makamys/Neodymium/releases/latest). The mod says it "reimplements chunk rendering in Minecraft 1.7.10 using modern OpenGL. This should improve performance on most hardware."

**Comment by DDnerd001** [comment]
https://github.com/makamys/Neodymium/issues/56
well I need an alternative

**Comment by pablojejeje** [comment]
Suggestions to improve nuclear bombs and add planes in HBM's NTM

Hi, I have some ideas to improve and expand the mechanics of nuclear bombs in HBM’s NTM:

1. Multiple custom nuclear bombs:
Allow different types or designs of nuclear bombs besides the standard custom nuke, each with unique effects or features.


2. Equivalence of nuclear bombs in rods:
A way to determine how much each type of nuclear bomb equals in rods to facilitate conversion or usage within the mod, especially for custom bombs.


3. Planes carrying nuclear bombs:
Add planes that can carry and drop nuclear bombs from the air, adding a new strategic and visual dimension to the mod.



Thank you for considering these suggestion.

**Comment by pablojejeje** [comment]
I don't know, I don't know where to put ideas :(

**Comment by burningwater202** [comment]
Put ideas nowhere

**Comment by pablojejeje** [comment]
It doesn't matter, in the end a contributor called me an idiot.

**Comment by HELLYEAHegeal** [comment]
Can you guys fix the rbmk reactor being invisible when i add too much  steam channels or other things? I use mobile using a java launcher please notice me it been pissing me off for a moth
