### ISSUE TITLE
crash with twilightforest

### ISSUE THREAD

**Issue by mcmso** [HbmMods/Hbm-s-Nuclear-Tech-GIT#986]
TwilightForest-2.4.0.jar
HBM-NTM-.1.0.27_X4550.jar
### Describe the bug
I think maybe the TFBiome Decorator is broken
Can you set up a configuration file in config to manage the generation of HBMS and add a dimension whitelist or blacklist

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.
[crash-2023-04-05_15.01.56-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/11157618/crash-2023-04-05_15.01.56-server.txt)
[crash-2023-04-05_18.05.21-server.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/11157619/crash-2023-04-05_18.05.21-server.txt)

**Comment by HbmMods** [comment]
The first crash should be fixable by disabling randomly spawning landmines. The second one seems to be caused by the active world instance not having a world provider for some reason, although I can just add a safeguard for that specific case.

**Comment by HbmMods** [comment]
Both crashes should be fixed in X4561, please close the issue if you can confirm.
