### ISSUE TITLE
"Ough" crash in inventory

### ISSUE THREAD

**Issue by LeKripiY** [HbmMods/Hbm-s-Nuclear-Tech-GIT#988]
The game crashed whilst rendering screen
Error: java.lang.ClassCastException: com.hbm.items.machine.ItemWatzPellet cannot be cast to com.hbm.items.machine.ItemRBMKRod

Turns out having this item on screen makes the game crash, i don't really know how this happened, but every time into my creative inventory and search "item" the game crash, same when i go to the fuel tab.

**Comment by HbmMods** [comment]
Fixed in X4561.
