### ISSUE TITLE
Why can't I get the blind effect while holding an item in the inventory that blinds you????

### ISSUE THREAD

**Issue by Kkelos** [HbmMods/Hbm-s-Nuclear-Tech-GIT#989]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.

When I hold an item in my inventory that blinds you (for example, shrabidium trisulfite), I don't get blinding effect. But when I type "/effect "player name" 15"(blinding effect) command works. Why?

Video: https://youtu.be/xKsniEPjGmo](https://youtu.be/xKsniEPjGmo

**Comment by HbmMods** [comment]
I think it's because of the cell's low blinding level causing the effect only to last for about half a second, which is too short so it gets stuck during the "fade-out" of the blindness effect, so it's not really visible at all. I'll just crank up the blindness to 3 seconds, that should fix it.

**Comment by HbmMods** [comment]
Fixed in X4561.
