### ISSUE TITLE
Game crash when attempting to set mixer recipe

### ISSUE THREAD

**Issue by TehTemmie** [HbmMods/Hbm-s-Nuclear-Tech-GIT#992]
Version: X4561
Attempting to set the recipe of a mixer to one that only uses one fluid type crashes the game. (Presumably, a recipe with no fluid types would also crash, but no mixer recipes are fluidless). The issue is probably this line, which tries to access input2's type without checking if input2 is null beforehand:
https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/blob/4e80951d54e6536b5307db127d21e6c6adba5cc6/src/main/java/com/hbm/tileentity/machine/TileEntityMachineMixer.java#L149

Crash log: https://pastebin.com/k0Xxc11M

**Comment by HbmMods** [comment]
Fixed in X4562
