### ISSUE TITLE
How 2 disable generating one structure?

### ISSUE THREAD

**Issue by Kkelos** [HbmMods/Hbm-s-Nuclear-Tech-GIT#995]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.

On my test world, I saw that the sulfur plast can break end portal frame. Is there any function in config to disable spawning this structure?

**Comment by username90001** [comment]
> ### Describe the bug
> Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.
> 
> On my test world, I saw that the sulfur plast can break end portal frame. Is there any function in config to disable spawning this structure?

it is bug and it must be fixed
if it wont be fixed or idk ur unlucky try download mod on telecakes to tp into nether adn end using cakes
