### ISSUE TITLE
Mining laser auto crystallizer 

### ISSUE THREAD

**Issue by Granniesgotaids** [HbmMods/Hbm-s-Nuclear-Tech-GIT#996]
The mining laser is not crystalizing tungsten, titanium, uranium, rare earth ore or thorium. It appears to crystalize everything else fine as far as I've noticed. I am using the latest version

**Comment by SoB1nary** [comment]
it now only acidises ores that require peroxide to do so, all the ones you mentioned requires sulfuric acid and therefore cannot be acidizer in the laser miner

**Comment by Granniesgotaids** [comment]
ah, that makes sense. Considering that the recipe for sulfuric acid is just hydrogen peroxide and water I hope that the laser could just use some sulfur.

**Comment by HbmMods** [comment]
With version X4607, crystallizer upgrades now also use sulfuric acid.
