### ISSUE TITLE
Fluid Bug

### ISSUE THREAD

**Issue by siebeboenne** [HbmMods/Hbm-s-Nuclear-Tech-GIT#997]
I had a 256 000 mB tank in my survival world but when I turned the setting to output (orange) all the high-performance solvent in the tank disappeared.

It only happens when it is connected to the ore acidizers with a pipe, the acidizers didn't have the right fluid ID yet.
When I changed it back to input (blue) the high-perf solvent did not come back.

I have sufficient knowledge of the mod to know that this is a bug and not a mistake on my side.

version: HBM-NTM-.1.0.27_X4551

**Comment by HbmMods** [comment]
Can't replicate, does it still happen in the most recent version? do you have anything else connected to the pipe net?
