### ISSUE TITLE
question about assembly machine

### ISSUE THREAD

**Issue by githubguyidk** [HbmMods/Hbm-s-Nuclear-Tech-GIT#998]
I've been wondering how to craft the assembly machine I tried using NEI for help it is saying for me to use an anvil but the anvil is too small so I am wondering if there is a way to craft the assembly machine

**Comment by HbmMods** [comment]
Click on the assembly machine in the list at the bottom to select it, then click the anvil shaped blue botton on top of the list. It'll use materials directly from your inventory.
