### ISSUE TITLE
RBMK Heat Exchanger

### ISSUE THREAD

**Issue by AVASSON** [HbmMods/Hbm-s-Nuclear-Tech-GIT#999]
Hello author, how can I restore the RBMK heat exchanger? I want to build a RBMK pressurized water reactor, but I don't want to use heat exchanger heaters and large boilers

**Comment by TehTemmie** [comment]
Sounds like you're looking for the RBMK steam channel, which directly boils water into steam (or any of its various levels of compression) by using heat from a RBMK fuel rod

**Comment by AVASSON** [comment]
No, what I want is an RBMK heat exchanger, which has been removed since X4438

**Comment by AVASSON** [comment]
How can I restore the RBMK heat exchanger?

**Comment by HbmMods** [comment]
Your options are:
- Using the new heat exchanging heaters, as they have consistent conversion rates and high throughput
- Downgrade to an older version where the old heat exchanger still exists, even though both the conversion rate and throughput are terrible
- Learn java and add the RBMK heat exchanger to the currernt version yourself
